// Seeds of the mutation probe: each is a TypeScript text that tsc 6.0.2 parses without a diagnostic.
// One group for each production of the reference that the unit compares: class elements and their modifiers,
// heritage clauses, parameter lists.
module.exports = [
  // class elements
  ["member", "class C { x; }"],
  ["member", "class C { x = 1; y: number; z?: string; w!: number; }"],
  ["member", "class C { public x = 1; private y: number; protected z; readonly r = 1; static s; }"],
  ["member", "class C { static readonly a = 1; public static b; private static readonly c: number = 1; }"],
  ["member", "abstract class C { abstract x: number; abstract m(): void; protected abstract get a(): number; }"],
  ["member", "class C { declare x: number; declare readonly y; static declare z: string; }"],
  ["member", "class C extends B { override m() {} public override x = 1; }"],
  ["member", "class C { accessor x = 1; static accessor y; }"],
  ["member", "class C { m() {} async am() {} *g() {} async *ag() {} }"],
  ["member", "class C { get a() { return 1 } set a(v) {} static get b() { return 1 } static set b(v) {} }"],
  ["member", "class C { constructor() {} }"],
  ["member", "class C { constructor(public a: number, private readonly b = 1, protected c?: string) {} }"],
  ["member", "class C { \"constructor\"() {} }"],
  ["member", "class C { [k: string]: any; static [k: number]: string; readonly [k: symbol]: number; }"],
  ["member", "class C { [a] = 1; [b]() {} static [c]; get [d]() { return 1 } }"],
  ["member", "class C { #p = 1; #m() {} static #s; get #a() { return 1 } }"],
  ["member", "class C { static {} static { this.x = 1; } }"],
  ["member", "class C { m(): void; m(a?: number): void {} }"],
  ["member", "class C { m<T>(a: T): T { return a } x?<T>(): void; }"],
  ["member", "class C { 1 = 1; 'a' = 2; 2n() {} \"b\"() {} }"],
  ["member", "class C { @dec x; @dec() m() {} @a @b static s = 1; @dec accessor y; }"],
  ["member", "class C { m(@dec a, @dec() b: number) {} constructor(@dec public p) {} }"],
  ["member", "class C { x; ; y }"],
  ["member", "class C {\n x\n y\n m() {}\n static\n z = 1\n}"],
  ["member", "class C { get; set; static; async; readonly; declare; abstract; accessor; override; public; }"],
  ["member", "class C { get = 1; set() {} static() {} async<T>() {} }"],
  ["member", "class C { if() {} class() {} function() {} new() {} delete; in; typeof; var = 1; }"],
  ["member", "declare class C { x: number; m(): void; constructor(a: number); static s: string; get g(): number; }"],
  ["member", "const k = class { x = 1; m() {} static s; };"],
  // heritage clauses
  ["heritage", "class C extends B {}"],
  ["heritage", "class C extends B<T> {}"],
  ["heritage", "class C extends a.b.c<T, U> {}"],
  ["heritage", "class C extends f() {}"],
  ["heritage", "class C extends (a, b) {}"],
  ["heritage", "class C extends B implements I, J<T> {}"],
  ["heritage", "class C implements I {}"],
  ["heritage", "class C<T> extends B<T> implements I<T>, a.J {}"],
  ["heritage", "class C extends class {} {}"],
  ["heritage", "class C extends null {}"],
  ["heritage", "class C extends a[b] {}"],
  ["heritage", "const k = class extends B {};"],
  ["heritage", "const k = class K<T> extends B<T> implements I {};"],
  ["heritage", "export default class extends B {}"],
  ["heritage", "export class C extends B implements I {}"],
  ["heritage", "declare class C extends B implements I {}"],
  ["heritage", "abstract class C extends B {}"],
  ["heritage", "interface I extends A, B<T>, a.C {}"],
  ["heritage", "interface I<T> extends A<T> { x: T }"],
  // parameter lists
  ["params", "function f(a, b = 1, ...c) {}"],
  ["params", "function f(a: number, b?: string, c: boolean = true, ...d: any[]) {}"],
  ["params", "function f(this: Window, a) {}"],
  ["params", "function f({ a, b: [c, d = 1], ...e }: T, [x, , y, ...z]: U) {}"],
  ["params", "function f<T>(a: T): T { return a }"],
  ["params", "async function f(a) {}"],
  ["params", "function* g(a) {}"],
  ["params", "const f = function (a, b) {};"],
  ["params", "const g = function* n(a) {};"],
  ["params", "const o = { m(a, b = 1) {}, get x() { return 1 }, set x(v) {}, async n() {}, *g() {}, [k]() {} };"],
  ["params", "declare function f(a: number, ...rest: string[]): void;"],
  ["params", "function f(a): void; function f(a?) {}"],
  ["params", "class C { m(a, b?: number, ...c) {} set s(v: number) {} constructor(a, public b) {} }"],
  ["params", "const a = (x, y = 1, ...z) => x;"],
  ["params", "const b = async (x: number, y?: string) => x;"],
  ["params", "const d = <T,>(x: T): T => x;"],
  ["params", "type F = (a: number, b?: string, ...c: any[]) => void;"],
  ["params", "interface I { m(a, b?): void; new (x: number): I; (y): void; get p(): number; set p(v: number); }"],
];
