// The hand-written inputs of the unit, by production of the reference. Each entry: [group, source, loader?].
// `node targeted.cjs > targeted.json` writes them as the list that probe.cjs reads.
const T = [];
const add = (g, list, l) => { for (const s of list) T.push(l ? { g, s, l } : { g, s }); };

add("parseModifiers: order, repeats, place (checker)", [
  "class C { public public x; }",
  "class C { public private x; }",
  "class C { static static x; }",
  "class C { readonly readonly x; }",
  "class C { declare declare x; }",
  "abstract class C { abstract abstract x; }",
  "class C { accessor accessor x; }",
  "class C { override override x; }",
  "class C { async async m() {} }",
  "class C { static public x; }",
  "class C { readonly public x; }",
  "class C { readonly static x; }",
  "class C { async public m() {} }",
  "class C { async static m() {} }",
  "class C { override public x; }",
  "class C { readonly override x; }",
  "class C { accessor static x; }",
  "class C { accessor readonly x; }",
  "class C { readonly accessor x; }",
  "class C { accessor public x; }",
  "class C { accessor declare x; }",
  "class C { declare accessor x; }",
  "class C { accessor override x; }",
  "abstract class C { abstract static x; }",
  "abstract class C { static abstract x; }",
  "abstract class C { abstract private x; }",
  "abstract class C { private abstract x; }",
  "abstract class C { abstract public x; }",
  "abstract class C { abstract override x; }",
  "abstract class C { abstract accessor x; }",
  "abstract class C { abstract async m(); }",
  "abstract class C { async abstract m(); }",
  "class C { abstract x; }",
  "class C { abstract m(); }",
  "abstract class C { abstract m() {} }",
  "abstract class C { abstract get a() { return 1 } }",
  "abstract class C { abstract x = 1; }",
  "abstract class C { abstract #x; }",
  "class C { declare m() {} }",
  "class C { declare get a() { return 1 } }",
  "class C { declare #x; }",
  "class C { declare x = 1; }",
  "class C { declare async m() {} }",
  "class C { async declare m() {} }",
  "class C { declare override x; }",
  "class C { override declare x; }",
  "class C { public #x; }",
  "class C { private #x; }",
  "class C { export x; }",
  "class C { export m() {} }",
  "class C { default x; }",
  "class C { const x = 1; }",
  "class C { const\n x = 1; }",
  "class C { in x; }",
  "class C { out x; }",
  "class C { async x; }",
  "class C { async get a() { return 1 } }",
  "class C { async constructor() {} }",
  "class C { static constructor() {} }",
  "class C { override constructor() {} }",
  "class C { public constructor() {} }",
  "class C { readonly m() {} }",
  "class C { readonly get a() { return 1 } }",
  "class C { accessor m() {} }",
  "class C { accessor get a() { return 1 } }",
  "class C { accessor constructor() {} }",
  "class C { public static {} }",
  "class C { @dec static {} }",
  "class C { async static {} }",
  "class C { static static {} }",
  "class C { readonly [k: string]: any; }",
  "class C { public [k: string]: any; }",
  "class C { static [k: string]: any; }",
  "class C { declare [k: string]: any; }",
  "class C { abstract [k: string]: any; }",
  "class C { async [k: string]: any; }",
  "class C { @dec [k: string]: any; }",
  "class C { accessor [k: string]: any; }",
  "class C { override [k: string]: any; }",
]);
add("parseModifiers: a line break or a token that follows no modifier", [
  "class C { public\n x }",
  "class C { private\n x = 1 }",
  "class C { protected\n x: number }",
  "class C { readonly\n x }",
  "class C { override\n x }",
  "class C { static\n x }",
  "class C { declare\n x }",
  "class C { abstract\n x }",
  "class C { accessor\n x }",
  "class C { async\n m() {} }",
  "class C { get\n a() { return 1 } }",
  "class C { set\n a(v) {} }",
  "class C { public static\n x }",
  "class C { static public\n x }",
  "class C { public\n static x }",
  "class C { public }",
  "class C { public; static; readonly = 1; declare() {} abstract<T>() {} override?: number; accessor!: number; async: any }",
  "class C { public ...x }",
  "class C { public {} }",
  "class C { public * g() {} }",
  "class C { public 1() {} }",
  "class C { public 'a'() {} }",
  "class C { public 1n() {} }",
  "class C { public #p }",
  "class C { public [a] }",
  "class C { get 1n() { return 1 } }",
  "class C { set 1n(v) {} }",
  "class C { static 1n = 1 }",
  "class C { async 1n() {} }",
  "class C { get *g() {} }",
  "class C { set *g() {} }",
  "class C { static *g() {} }",
  "class C { async *g() {} }",
  "class C { * async g() {} }",
  "class C { * get a() {} }",
  "class C { * * g() {} }",
  "class C { get get a() { return 1 } }",
  "class C { get set a() { return 1 } }",
  "class C { get static a() { return 1 } }",
  "class C { get public a() { return 1 } }",
  "class C { get async a() { return 1 } }",
  "class C { static get static a() { return 1 } }",
]);
add("parseClassElement: what starts no member, Declaration expected", [
  "class C { @dec }",
  "class C { @dec ; }",
  "class C { @dec @dec2 }",
  "class C { public @dec x }",
  "class C { @dec public x }",
  "class C { public @dec }",
  "class C { static @dec x }",
  "class C { + }",
  "class C { = 1 }",
  "class C { ( }",
  "class C { ? }",
  "class C { ! }",
  "class C { . }",
  "class C { , }",
  "class C { => }",
  "class C { < }",
  "class C { ... }",
  "class C { var x; }",
  "class C { let x; }",
  "class C { function f() {} }",
  "class C { class D {} }",
  "class C { if (x) {} }",
  "class C { return; }",
  "class C { x y }",
  "class C { x; y z }",
  "class C { 1 2 }",
  "class C { 'a' b }",
  "class C { [a] b }",
  "class C { #a b }",
  "class C { static static x }",
  "class C { typ x }",
  "class C { functio f() {} }",
  "class C { declare }",
  "class C { type x }",
  "class C { interface x }",
  "class C { x is y }",
]);
add("parsePropertyDeclaration and parseSemicolonAfterPropertyName", [
  "class C { x! }",
  "class C { x!: number }",
  "class C { x!: number = 1 }",
  "class C { x! = 1 }",
  "class C { static x!: number }",
  "class C { x\n!: number }",
  "class C { x?!: number }",
  "class C { x!?: number }",
  "class C { x?? }",
  "class C { x?: number }",
  "class C { x? }",
  "class C { x? = 1 }",
  "class C { accessor x?: number }",
  "class C { accessor x!: number }",
  "class C { x!() {} }",
  "class C { x!<T>() {} }",
  "class C { x?() {} }",
  "class C { x?<T>(): void }",
  "class C { x: number() }",
  "class C { x = 1() }",
  "class C { x() }",
  "class C { x: number = }",
  "class C { x = }",
  "class C { x: }",
  "class C { x: number y }",
  "class C { x = 1 y }",
  "class C { x = 1, y = 2 }",
  "class C { x, y }",
  "class C { x: number, y: string }",
  "class C { x = yield }",
  "class C { x = await 1 }",
  "async function f() { class C { x = await 1 } }",
  "function* g() { class C { x = yield 1 } }",
  "class C { x = 1 in y }",
  "class C { [a, b] = 1 }",
  "class C { [a, b]() {} }",
  "class C { [a = 1] }",
  "class C { [] }",
  "class C { []: number }",
  "class C { [...a]: number }",
  "class C { [a?]: number }",
  "class C { [a?: string]: number }",
  "class C { [public a: string]: number }",
  "class C { [a: string, b: number]: any }",
  "class C { [a: string,]: any }",
  "class C { [a: string] }",
  "class C { [a: string]: }",
  "class C { [a: string]: any = 1 }",
  "class C { [a: string]?: any }",
  "class C { [a: string]!: any }",
  "class C { [a: string](): any }",
  "class C { [a: string]: any, [b: number]: any }",
  "class C { [a = 1: string]: any }",
  "class C { [a: string = 1]: any }",
  "class C { [k!: string]: any }",
  "class C { [(k): string]: any }",
  "class C { [k as any: string]: any }",
  "class C { [<T>k: string]: any }",
  "class C { [k<T>: string]: any }",
  "class C { get [k: string]: any }",
  "class C { set [k: string]: any }",
  "class C { * [k: string]: any }",
  "class C { async [k: string]: any }",
  "class C { static * [k: string]: any }",
  "class C { static get [k: string]: any }",
  "class C { get []: any }",
  "class C { * [...a]: any }",
  "class C { [this: string]: any }",
  "class C { [await: string]: any }",
  "class C { [yield: string]: any }",
  "class C { [k: string]\n: any }",
]);
add("parseMethodDeclaration, accessors, constructors", [
  "class C { m }",
  "class C { m( }",
  "class C { m() }",
  "class C { m();\n m() {} }",
  "class C { m() => 1 }",
  "class C { m(): }",
  "class C { m<>() {} }",
  "class C { m<T,>() {} }",
  "class C { *m(); }",
  "class C { async m(); }",
  "class C { get a() }",
  "class C { get a(); }",
  "class C { set a(v) }",
  "class C { get a }",
  "class C { get a = 1 }",
  "class C { get a: number }",
  "class C { get a<T>() { return 1 } }",
  "class C { set a<T>(v) {} }",
  "class C { get a(x) { return 1 } }",
  "class C { get a(this: C) { return 1 } }",
  "class C { get a(this: C, x) { return 1 } }",
  "class C { set a() {} }",
  "class C { set a(x, y) {} }",
  "class C { set a(this: C, x) {} }",
  "class C { set a(...x) {} }",
  "class C { set a(x?) {} }",
  "class C { set a(x = 1) {} }",
  "class C { set a(x): void {} }",
  "class C { get a?() { return 1 } }",
  "class C { set a?(v) {} }",
  "class C { get a!() { return 1 } }",
  "class C { static get a?() { return 1 } }",
  "class C { get #a?() { return 1 } }",
  "class C { get [a]?() { return 1 } }",
  "class C { get 'a'?() { return 1 } }",
  "class C { constructor }",
  "class C { constructor; }",
  "class C { constructor = 1 }",
  "class C { constructor: number }",
  "class C { constructor?() {} }",
  "class C { constructor!() {} }",
  "class C { constructor?: number }",
  "class C { constructor<T>() {} }",
  "class C { constructor(): void {} }",
  "class C { constructor(): C; constructor() {} }",
  "class C { constructor();\n constructor() {} }",
  "class C { 'constructor' }",
  "class C { 'constructor' = 1 }",
  "class C { 'constructor'() {} }",
  "class C { 'constructor'?() {} }",
  "class C { 'constructor'!() {} }",
  "class C { 'constructor'<T>() {} }",
  "class C { \"constructor\": number }",
  "class C { static constructor }",
  "class C { static 'constructor'() {} }",
  "class C { get constructor() { return 1 } }",
  "class C { set constructor(v) {} }",
  "class C { *constructor() {} }",
  "class C { async constructor() {} }",
  "class C { async *constructor() {} }",
  "class C { get 'constructor'() { return 1 } }",
  "class C { constructor() {} constructor() {} }",
  "class C { #constructor }",
  "class C { #constructor() {} }",
  "class C { static prototype }",
  "class C { static prototype() {} }",
  "class C { static 'prototype' = 1 }",
  "class C { static get prototype() { return 1 } }",
  "class C { prototype }",
  "class C { @dec constructor() {} }",
  "class C { @dec get a() { return 1 } @dec set a(v) {} }",
  "class C { @dec m(); m() {} }",
  "class C { m(): void\n n(): void {} }",
  "class C { m()\n {} }",
  "class C { static { await 1 } }",
  "class C { static { return } }",
  "class C { static { yield } }",
  "class C { static { arguments } }",
  "class C { static {} {} }",
  "class C { static\n{} }",
  "class C { static async {} }",
]);
add("parseParameter and parseParameters", [
  "function f(this) {}",
  "function f(this: T) {}",
  "function f(a, this: T) {}",
  "function f(this: T, this: U) {}",
  "function f(this?: T) {}",
  "function f(this = 1) {}",
  "function f(...this) {}",
  "function f(public this) {}",
  "function f(readonly this: T) {}",
  "class C { m(@dec this) {} }",
  "class C { m(@dec this: C) {} }",
  "class C { constructor(public this) {} }",
  "function f(this,) {}",
  "const a = (this) => 1;",
  "const a = (this: T) => 1;",
  "const a = function (this: T) {};",
  "function f(...a, b) {}",
  "function f(...a,) {}",
  "function f(...a = 1) {}",
  "function f(...a?) {}",
  "function f(...a?: T[]) {}",
  "function f(...a: T[] = []) {}",
  "function f(......a) {}",
  "function f(... ...a) {}",
  "function f(...{ a }) {}",
  "function f(...[a]) {}",
  "declare function f(...a, b);",
  "declare function f(...a,);",
  "declare class C { m(...a,); }",
  "class C { m(...a,); m(...a) {} }",
  "class C { m(...a,) {} }",
  "function f(a?, b) {}",
  "function f(a? = 1) {}",
  "function f(a?: number = 1) {}",
  "function f(a = 1?) {}",
  "function f(a: number?) {}",
  "function f(a!) {}",
  "function f(a!: number) {}",
  "function f(a?!) {}",
  "function f(a??) {}",
  "function f(a = 1: number) {}",
  "function f(a: number = 1 = 2) {}",
  "function f(a, a) {}",
  "function f(a,, b) {}",
  "function f(, a) {}",
  "function f(a,) {}",
  "function f(a b) {}",
  "function f(a; b) {}",
  "function f(a {}",
  "function f(1) {}",
  "function f('a') {}",
  "function f(a.b) {}",
  "function f(#a) {}",
  "function f(class) {}",
  "function f(if) {}",
  "function f(enum) {}",
  "function f(null) {}",
  "function f(void) {}",
  "function f(static) {}",
  "function f(public) {}",
  "function f(let) {}",
  "function f(yield) {}",
  "function f(await) {}",
  "async function f(await) {}",
  "function* g(yield) {}",
  "function f(async) {}",
  "function f(of) {}",
  "function f(type) {}",
  "function f(@dec a) {}",
  "function f(public a) {}",
  "function f(private a: number) {}",
  "function f(readonly a) {}",
  "function f(override a) {}",
  "function f(public\n a) {}",
  "function f(static a) {}",
  "function f(declare a) {}",
  "function f(abstract a) {}",
  "function f(async a) {}",
  "function f(export a) {}",
  "function f(accessor a) {}",
  "function f(const a) {}",
  "function f(in a) {}",
  "function f(out a) {}",
  "function f(default a) {}",
  "function f(public public a) {}",
  "function f(public private a) {}",
  "function f(readonly public a) {}",
  "function f(public readonly a) {}",
  "function f(public {a}) {}",
  "function f(public [a]) {}",
  "function f(public ...a) {}",
  "function f(...public a) {}",
  "function f(public a?) {}",
  "function f(public = 1) {}",
  "function f(public: number) {}",
  "function f(public, private) {}",
  "function f(readonly) {}",
  "function f(readonly: number, override?: string) {}",
  "class C { constructor(public a) {} }",
  "class C { constructor(public\n a) {} }",
  "class C { constructor(readonly\n a) {} }",
  "class C { constructor(public readonly\n a) {} }",
  "class C { constructor(public public a) {} }",
  "class C { constructor(public private a) {} }",
  "class C { constructor(readonly readonly a) {} }",
  "class C { constructor(readonly public a) {} }",
  "class C { constructor(override readonly a) {} }",
  "class C { constructor(readonly override a) {} }",
  "class C { constructor(static a) {} }",
  "class C { constructor(declare a) {} }",
  "class C { constructor(abstract a) {} }",
  "class C { constructor(async a) {} }",
  "class C { constructor(export a) {} }",
  "class C { constructor(accessor a) {} }",
  "class C { constructor(const a) {} }",
  "class C { constructor(public {a}) {} }",
  "class C { constructor(public [a]) {} }",
  "class C { constructor(public ...a) {} }",
  "class C { constructor(...public a) {} }",
  "class C { constructor(public a?) {} }",
  "class C { constructor(public a!) {} }",
  "class C { constructor(public a = 1) {} }",
  "class C { constructor(public) {} }",
  "class C { constructor(public = 1) {} }",
  "class C { constructor(public: number) {} }",
  "class C { constructor(public, private) {} }",
  "class C { constructor(public?: number) {} }",
  "class C { constructor(@dec public a) {} }",
  "class C { constructor(public @dec a) {} }",
  "class C { constructor(public a); constructor(a) {} }",
  "class C { m(public a) {} }",
  "class C { m(public\n a) {} }",
  "class C { set s(public a) {} }",
  "declare class C { constructor(public a); }",
  "const o = { m(public a) {} };",
  "const a = (public a) => 1;",
  "const a = (public) => 1;",
  "const a = (readonly a: number) => 1;",
  "const a = function (public a) {};",
  "type F = (public a: number) => void;",
  "type F = new (public a: number) => C;",
  "interface I { m(public a): void }",
  "interface I { new (public a): I }",
  "interface I { (public a): void }",
  "type F = (this: T, a) => void;",
  "type F = (a, this: T) => void;",
  "type F = (...a, b) => void;",
  "type F = (a?, b) => void;",
  "type F = (a = 1) => void;",
  "type F = (...this) => void;",
  "type F = (@dec a) => void;",
]);
add("binding patterns of a parameter", [
  "function f({ a }) {}",
  "function f({ a, }) {}",
  "function f({ a: b }) {}",
  "function f({ a = 1 }) {}",
  "function f({ a: b = 1 }) {}",
  "function f({ ...a }) {}",
  "function f({ ...a, }) {}",
  "function f({ ...a, b }) {}",
  "function f({ ...{ a } }) {}",
  "function f({ ...[a] }) {}",
  "function f({ ...a = 1 }) {}",
  "function f({ ...a.b }) {}",
  "function f({ a.b }) {}",
  "function f({ 'a' }) {}",
  "function f({ 1 }) {}",
  "function f({ [a] }) {}",
  "function f({ 'a': b, 1: c, [d]: e, 2n: g }) {}",
  "function f({ class }) {}",
  "function f({ if }) {}",
  "function f({ export, default: d }) {}",
  "function f({ this }) {}",
  "function f({ null }) {}",
  "function f({ new }) {}",
  "function f({ static }) {}",
  "function f({ let }) {}",
  "function f({ yield }) {}",
  "function f({ await }) {}",
  "async function f({ await }) {}",
  "function* g({ yield }) {}",
  "function f({ class: c }) {}",
  "function f({ class = 1 }) {}",
  "function f({ a: class }) {}",
  "function f({ a: 1 }) {}",
  "function f({ a: b.c }) {}",
  "function f({ a: (b) }) {}",
  "function f({ a b }) {}",
  "function f({ a; b }) {}",
  "function f({ , a }) {}",
  "function f({ a,, b }) {}",
  "function f({ a() {} }) {}",
  "function f({ get a() {} }) {}",
  "function f({ #a }) {}",
  "function f({ #a: b }) {}",
  "function f({ a: #b }) {}",
  "function f({ a }: ) {}",
  "function f({ a }?) {}",
  "function f({ a }?: T) {}",
  "function f({ a }!) {}",
  "function f([a]) {}",
  "function f([a,]) {}",
  "function f([, a, , b, ,]) {}",
  "function f([a = 1]) {}",
  "function f([...a]) {}",
  "function f([...a,]) {}",
  "function f([...a, b]) {}",
  "function f([...a = 1]) {}",
  "function f([...[a]]) {}",
  "function f([...{ a }]) {}",
  "function f([... ...a]) {}",
  "function f([a.b]) {}",
  "function f([1]) {}",
  "function f([class]) {}",
  "function f([this]) {}",
  "function f([a b]) {}",
  "function f([a; b]) {}",
  "function f([a: b]) {}",
  "function f([a?]) {}",
  "function f([a!]) {}",
  "function f([#a]) {}",
  "function f([(a)]) {}",
  "function f([a]?) {}",
  "let { class } = x;",
  "let { export: e, if: i } = x;",
  "let [class] = x;",
  "let { a: { class } } = x;",
  "const a = ({ class }) => 1;",
  "const a = ([class]) => 1;",
  "try {} catch ({ class }) {}",
]);
add("parseHeritageClauses, parseHeritageClause, parseExpressionWithTypeArguments", [
  "class C extends {}",
  "class C extends {} {}",
  "class C extends {}, B {}",
  "class C extends {} implements I {}",
  "class C extends {} extends B {}",
  "class C extends { a: 1 } {}",
  "class C extends { a: 1 }.a {}",
  "class C extends {}.a {}",
  "class C extends {}() {}",
  "class C extends {}[a] {}",
  "class C extends",
  "class C extends ;",
  "class C extends B",
  "class C extends B;",
  "class C extends B, D {}",
  "class C extends B, {}",
  "class C extends B, {} {}",
  "class C extends B, {",
  "class C extends B extends D {}",
  "class C extends B implements I extends D {}",
  "class C implements I extends B {}",
  "class C implements I implements J {}",
  "class C implements {}",
  "class C implements I, {}",
  "class C implements",
  "class C implements I,",
  "class C extends B, implements I {}",
  "class C extends implements I {}",
  "class C extends extends B {}",
  "class C extends B implements {}",
  "class C extends B implements implements I {}",
  "class C extends B,, D {}",
  "class C extends , B {}",
  "class C extends B D {}",
  "class C extends B.D {}",
  "class C extends B.D<T> {}",
  "class C extends B<T>.D {}",
  "class C extends B<T><U> {}",
  "class C extends B<> {}",
  "class C extends B<T,> {}",
  "class C extends B<T {}",
  "class C extends B?.D {}",
  "class C extends B! {}",
  "class C extends B!.D {}",
  "class C extends B<T>! {}",
  "class C extends B as any {}",
  "class C extends (B as any) {}",
  "class C extends <any>B {}",
  "class C extends B satisfies X {}",
  "class C extends B() {}",
  "class C extends B()<T> {}",
  "class C extends B<T>() {}",
  "class C extends B`t` {}",
  "class C extends B<T>`t` {}",
  "class C extends B[0] {}",
  "class C extends new B {}",
  "class C extends new B() {}",
  "class C extends new B<T>() {}",
  "class C extends new B<T> {}",
  "class C extends class {} {}",
  "class C extends class D extends E {} {}",
  "class C extends function () {} {}",
  "class C extends async function () {} {}",
  "class C extends async () => {} {}",
  "class C extends () => {} {}",
  "class C extends a => a {}",
  "class C extends (a) {}",
  "class C extends (a, b) {}",
  "class C extends [] {}",
  "class C extends [B][0] {}",
  "class C extends `t` {}",
  "class C extends /re/ {}",
  "class C extends 1 {}",
  "class C extends 1n {}",
  "class C extends 'a' {}",
  "class C extends null {}",
  "class C extends undefined {}",
  "class C extends true {}",
  "class C extends this {}",
  "class C extends this.B {}",
  "class C extends super {}",
  "class C extends super.B {}",
  "class C extends super() {}",
  "class C extends import('a') {}",
  "class C extends import.meta {}",
  "class C extends import.meta.B {}",
  "class C extends import {}",
  "class C extends new.target {}",
  "class C extends !B {}",
  "class C extends -B {}",
  "class C extends +B {}",
  "class C extends ~B {}",
  "class C extends typeof B {}",
  "class C extends void B {}",
  "class C extends delete B {}",
  "class C extends ++B {}",
  "class C extends --B {}",
  "class C extends B++ {}",
  "class C extends await B {}",
  "class C extends yield {}",
  "class C extends yield B {}",
  "async function f() { class C extends await B {} }",
  "function* g() { class C extends yield {} }",
  "function* g() { class C extends yield B {} }",
  "function* g() { class C extends (yield B) {} }",
  "export class C extends await B {}",
  "class C extends B + D {}",
  "class C extends B = D {}",
  "class C extends B ? D : E {}",
  "class C extends B || D {}",
  "class C extends B ?? D {}",
  "class C extends B in D {}",
  "class C extends B instanceof D {}",
  "class C extends @dec class {} {}",
  "class C extends #p {}",
  "class C extends B.#p {}",
  "class C extends let {}",
  "class C extends static {}",
  "class C extends async {}",
  "class C extends implements {}",
  "class C extends implements implements I {}",
  "class C extends public {}",
  "class C extends if {}",
  "class C extends var {}",
  "class C extends enum {}",
  "class C extends = B {}",
  "class C extends ) {}",
  "class C extends ... B {}",
  "class implements {}",
  "class implements implements I {}",
  "class implements extends B {}",
  "class extends {}",
  "class extends extends B {}",
  "class C implements I {}",
  "class C implements I<T>, a.J, a.b.K<T, U> {}",
  "class C implements I() {}",
  "class C implements I[0] {}",
  "class C implements new I {}",
  "class C implements (I) {}",
  "class C implements typeof I {}",
  "class C implements keyof I {}",
  "class C implements readonly I[] {}",
  "class C implements I[] {}",
  "class C implements I | J {}",
  "class C implements I & J {}",
  "class C implements { a: 1 } {}",
  "class C implements [I] {}",
  "class C implements string {}",
  "class C implements void {}",
  "class C implements null {}",
  "class C implements this {}",
  "class C implements 'a' {}",
  "class C implements 1 {}",
  "class C implements () => void {}",
  "class C implements I? {}",
  "class C implements I! {}",
  "class C implements I<T>! {}",
  "class C implements I.J.K {}",
  "class C implements I?.J {}",
  "class C implements I.#p {}",
  "class C implements import('a') {}",
  "class C implements import('a').I {}",
  "class C implements I<> {}",
  "class C implements I<T,> {}",
  "class C implements I, {}",
  "class C implements I J {}",
  "class C implements !I {}",
  "class C implements I extends B {}",
  "class C implements super {}",
  "class C implements super<T> {}",
  "class C implements class {} {}",
  "class C implements function () {} {}",
  "class C implements I as J {}",
  "class C implements a.<T> {}",
  "class C implements a. {}",
  "class C implements a.b<T>.c {}",
  "const k = class extends B {};",
  "const k = class extends !B {};",
  "const k = class extends B, D {};",
  "const k = class implements I {};",
  "const k = class K extends {} {};",
  "export default class extends B {}",
  "export default class extends !B {}",
  "declare class C extends !B {}",
  "declare class C extends B, D {}",
  "declare class C extends B extends D {}",
  "abstract class C extends B implements I {}",
  "@dec class C extends B {}",
  "interface I extends A {}",
  "interface I extends A, B<T>, c.D {}",
  "interface I extends {}",
  "interface I extends",
  "interface I extends A, {}",
  "interface I extends A,, B {}",
  "interface I extends A B {}",
  "interface I extends A extends B {}",
  "interface I implements A {}",
  "interface I extends A implements B {}",
  "interface I extends A() {}",
  "interface I extends A[0] {}",
  "interface I extends !A {}",
  "interface I extends typeof A {}",
  "interface I extends keyof A {}",
  "interface I extends A | B {}",
  "interface I extends A[] {}",
  "interface I extends string {}",
  "interface I extends void {}",
  "interface I extends 'a' {}",
  "interface I extends { a: 1 } {}",
  "interface I extends (A) {}",
  "interface I extends new A {}",
  "interface I extends A! {}",
  "interface I extends A?.B {}",
  "interface I extends A.B.C<T> {}",
  "interface I extends A<T>.B {}",
  "interface I extends A<> {}",
  "interface I extends A<T,> {}",
  "interface I extends import('a').A {}",
  "interface I extends this {}",
  "interface I extends class {} {}",
  "interface I<T> extends A<T> {}",
  "declare class C { } interface I extends C {}",
]);
add("decorators: parseDecorator, parseDecoratorExpression", [
  "class C { @dec x }",
  "class C { @dec() x }",
  "class C { @a.b.c x }",
  "class C { @a.b() x }",
  "class C { @a().b x }",
  "class C { @a[0] x }",
  "class C { @a['b']() {} }",
  "class C { @(a) x }",
  "class C { @(a, b) x }",
  "class C { @new A x }",
  "class C { @new A() x }",
  "class C { @class {} x }",
  "class C { @function () {} x }",
  "class C { @a<T> x }",
  "class C { @a<T>() x }",
  "class C { @a! x }",
  "class C { @a!.b x }",
  "class C { @a?.b x }",
  "class C { @a?.() x }",
  "class C { @a`t` x }",
  "class C { @!a x }",
  "class C { @-a x }",
  "class C { @typeof a x }",
  "class C { @void a x }",
  "class C { @<T>a x }",
  "class C { @++a x }",
  "class C { @a++ x }",
  "class C { @a + b x }",
  "class C { @a = b }",
  "class C { @await a x }",
  "class C { @yield x }",
  "async function f() { class C { @await a x } }",
  "async function f() { class C { @await x } }",
  "class C { @this.a x }",
  "class C { @super.a x }",
  "class C { @1 x }",
  "class C { @'a' x }",
  "class C { @[a] x }",
  "class C { @{} x }",
  "class C { @#p x }",
  "class C { @a.#p x }",
  "class C { @ x }",
  "class C { @@a x }",
  "class C { @a @b x }",
  "class C { @a\n@b\nx }",
  "class C { @a\nx }",
  "class C { @import('a') x }",
  "class C { @import.meta x }",
  "@dec class C {}",
  "@!dec class C {}",
  "@dec export class C {}",
  "export @dec class C {}",
  "@dec export default class {}",
  "export default @dec class {}",
  "@a export @b class C {}",
  "@dec abstract class C {}",
  "@dec declare class C {}",
  "@dec function f() {}",
  "@dec let x;",
  "@dec interface I {}",
  "@dec enum E {}",
  "@dec type T = 1;",
  "@dec namespace N {}",
  "@dec",
  "const k = @dec class {};",
  "const k = @!dec class {};",
  "class C { m(@dec a, @dec() b, @a.b c, @(d) e) {} }",
  "class C { m(@!dec a) {} }",
  "class C { m(@dec) {} }",
  "class C { m(@dec ...a) {} }",
  "class C { m(...@dec a) {} }",
  "class C { m(@dec { a }) {} }",
  "class C { m(@dec @dec2 a) {} }",
  "class C { constructor(@dec a) {} }",
  "function f(@dec a) {}",
  "const o = { m(@dec a) {} };",
  "const a = (@dec a) => 1;",
  "const o = { @dec m() {} };",
  "const o = { @dec a: 1 };",
]);
add("object literal members with class syntax (parseObjectLiteralElement)", [
  "const o = { public a: 1 };",
  "const o = { static a: 1 };",
  "const o = { readonly a: 1 };",
  "const o = { async a: 1 };",
  "const o = { public m() {} };",
  "const o = { static m() {} };",
  "const o = { declare m() {} };",
  "const o = { a?: 1 };",
  "const o = { a!: 1 };",
  "const o = { m?() {} };",
  "const o = { m!() {} };",
  "const o = { a? };",
  "const o = { a! };",
  "const o = { get a?() { return 1 } };",
  "const o = { m(); };",
  "const o = { m() };",
  "const o = { m<T>(a: T): T { return a } };",
  "const o = { get a<T>() { return 1 } };",
  "const o = { get a(x) { return 1 } };",
  "const o = { set a() {} };",
  "const o = { a = 1 };",
  "const o = { [k: string]: 1 };",
  "const o = { constructor() {}, 'constructor': 1 };",
  "const o = { #a: 1 };",
  "const o = { a: 1; b: 2 };",
]);
add("JavaScript files: the same productions", [
  "class C { public x }",
  "class C { x?: number }",
  "class C { x! }",
  "class C { m(): void {} }",
  "class C { constructor(public a) {} }",
  "class C { declare x }",
  "class C { abstract x }",
  "class C { readonly x }",
  "class C { [k: string]: any }",
  "class C { static static x }",
  "class C { get a?() { return 1 } }",
  "class C implements I {}",
  "class C extends B<T> {}",
  "class C<T> {}",
  "class C extends !B {}",
  "class C extends {} {}",
  "class C extends B, D {}",
  "function f(a?) {}",
  "function f(a: number) {}",
  "function f(this) {}",
  "function f(public a) {}",
  "function f<T>() {}",
  "function f(): void {}",
  "function f({ class }) {}",
  "function f(...a, b) {}",
  "function f(...a,) {}",
  "class C { m(); }",
  "class C { accessor x }",
  "class C { @dec x }",
  "class C { static {} }",
  "class C { x y }",
  "class C { m!() {} }",
  "class C { constructor?() {} }",
], "js");
console.log(JSON.stringify(T));
