const g = "TS1357 enum";
const rows = [
  'enum E { a b }',
  'enum E { a = 1 b }',
  'enum E { a b c }',
  'enum E { a\nb }',
  'enum E { a = 1\nb = 2 }',
  'enum E { a; b }',
  'enum E { a; }',
  'enum E { a;\nb }',
  'enum E { a, b }',
  'enum E { a, b, }',
  'enum E { a,, b }',
  'enum E { , a }',
  'enum E { a = 1; b = 2 }',
  'enum E { "a" "b" }',
  'enum E { "a" b }',
  'enum E { ["a"] b }',
  'enum E { a "b" }',
  'enum E { a 1 }',
  'enum E { a: 1 }',
  'enum E { a = }',
  'enum E { a = , b }',
  'enum E { a( }',
  'enum E { a ) }',
  'enum E { a ] }',
  'enum E { a + b }',
  'enum E { a = 1 + }',
  'enum E { a = b c }',
  'enum E { a = b\nc }',
  'enum E { a = b, c d }',
  'enum E { a }',
  'enum E { }',
  'enum E { a',
  'enum E { a b',
  'enum E { a,',
  'enum E { 1 }',
  'enum E { 1n }',
  'enum E { [x] }',
  'enum E { [x] = 1 }',
  'enum E { ["a" + "b"] }',
  'enum E { [`a`] }',
  'enum E { #a }',
  'enum E { `a` }',
  'enum E { class }',
  'enum E { a = 1, class = 2 }',
  'enum E { a.b }',
  'enum E { a? }',
  'enum E { a! }',
  'enum E { public a }',
  'enum E { a = 1 as const }',
  'enum E { a = <any>1 }',
  'enum E { a = yield }',
  'enum E { a = await }',
  'const enum E { a b }',
  'declare enum E { a b }',
  'export enum E { a b }',
  'declare const enum E { a = 1 b }',
  'namespace N { enum E { a b } }',
  'enum E { a = 1 /* c */ b }',
  'enum E { a\n= 1 }',
  'enum E { a =\n1 }',
  'enum E { a, ...b }',
  'enum E { ...b }',
  'enum { a }',
  'enum E',
  'enum E;',
  'enum E a }',
  'enum class { a }',
  'enum E extends F { a }',
  'enum E<T> { a }',
  'enum E { a } b',
  'enum E { a = 1 } = 2',
  'enum E { a = () => { return 1 } b }',
  'enum E { a = function() {} b }',
  'enum E { a = x ? y : z w }',
  'enum E { a = b in c }',
  'enum E { a = 1, } ;',
];
const out = rows.map(s => ({ s, g }));
for (const s of ['enum E { a b }', 'enum E { a }']) out.push({ s, l: "js", g: g + " (js)" });
for (const s of ['enum E { a b }', 'declare enum E { a; b }', 'export enum E { a = 1 b }']) out.push({ s, l: "dts", g: g + " (d.ts)" });
process.stdout.write(JSON.stringify(out));
