const rows = [];
const add = (g, list) => { for (const s of list) rows.push({ s, g }); };
add("v members", [
  'class C { get a?<T>() { return 1 } }',
  'class C { constructor }',
  'class C { constructor = 1 }',
  'class C { constructor: T }',
  'class C { constructor; }',
  'class C { constructor<T>() {} }',
  'class C { constructor\n() {} }',
  'class C { "constructor"() {} }',
  'class C { "constructor"?() {} }',
  'class C { "constructor"<T>() {} }',
  'class C { static prototype }',
  'class C { public type x }',
  'class C { public const x }',
  'class C { public var x }',
  'class C { declare foo bar }',
  'class C { x! = 1 y }',
  'class C { x!\n() {} }',
  'class C { x?() {} }',
  'class C { x?<T>() {} }',
  'class C { x? y }',
  'class C { x! y }',
  'class C { 1 y }',
  'class C { #a y }',
  'class C { [a] y }',
  'class C { static x y }',
  'class C { accessor x y }',
  'class C { asynx m() {} }',
  'class C { publicx: number }',
  'class C { get }',
  'class C { get; set; static; async; accessor }',
  'class C { get = 1; set: T; async() {} }',
  'class C { static async }',
  'class C { public get }',
  'class C { number x }',
  'class C { any x }',
  'class C { of x }',
  'class C { await x }',
  'class C { yield x }',
  'class C { let x }',
  'class C { static\n{ } }',
  'class C { public static {} }',
  'class C { @d static {} }',
  'class C { async *[Symbol.iterator]() {} }',
  'class C { async [a]() {} }',
  'class C { async [a] = 1 }',
  'class C { accessor [a]() {} }',
  'class C { accessor [a] = 1 }',
  'class C { async "m"() {} }',
  'class C { async #m() {} }',
  'class C { async m<T>() {} }',
  'class C { async m?() {} }',
  'class C { async m? }',
  'class C { accessor m?() {} }',
]);
add("v parameters", [
  'function f(public {a}) {}',
  'function f(public [a]) {}',
  'function f(...a, b) {}',
  'function f(...a,) {}',
  'function f(...a = 1) {}',
  'function f(...a,, b) {}',
  'function f(...[a], b) {}',
  'class C { constructor(public "a") {} }',
  'class C { constructor(public 1) {} }',
  'class C { constructor(public class) {} }',
  'class C { constructor(public #a) {} }',
  'class C { constructor(public) {} }',
  'class C { constructor(public, a) {} }',
  'class C { constructor(public = 1) {} }',
  'class C { constructor(public: number) {} }',
  'class C { constructor(public?) {} }',
  'class C { constructor(public readonly) {} }',
  'class C { constructor(readonly public) {} }',
  'class C { constructor(public a b) {} }',
  'class C { constructor(public a: number b) {} }',
  'class C { constructor(a, public) {} }',
  'function f(static a) {}',
  'function f(declare a) {}',
  'function f(abstract a) {}',
  'function f(accessor a) {}',
  'function f(out a) {}',
  'function f(in a) {}',
  'function f(export a) {}',
  'function f(default a) {}',
  'function f(const a) {}',
  'function f(static static a) {}',
  'function f(public static public a) {}',
  'function f(static {a}) {}',
  'function f(static ...a) {}',
  'function f(static this) {}',
  'function f(a] {}',
  'function f(a,] {}',
  'function f(] {}',
]);
process.stdout.write(JSON.stringify(rows));
