// The expected values in the tables are what Vite 8.3 evaluates the same call to in the same tree.
export type Entry = [key: string, kind: "lazy" | "eager", value: unknown];
export type Case = [code: string, expected: Entry[]];

export const tree = {
  "outside.ts": "export default 'outside';",
  "proj/package.json":
    '{ "name": "proj", "type": "module", "imports": { "#dir/*": "./src/dir/*", "#one": "./src/dir/a.ts" } }',
  "proj/src/dir/a.ts": "export default 'a'; export const setup = 'setup a'; export const name = 'a';",
  "proj/src/dir/b.ts": "export default 'b'; export const setup = 'setup b'; export const name = 'b';",
  "proj/src/dir/c.ts": "export default 'c'; export const setup = 'setup c'; export const name = 'c';",
  "proj/src/dir/Upper.ts": "export default 'upper';",
  "proj/src/dir/skip.ts": "export default 'skip';",
  "proj/src/dir/data.json": '{ "n": 1 }',
  "proj/src/dir/.dot.ts": "export default 'dotfile';",
  "proj/src/dir/.hidden/h.ts": "export default 'hidden';",
  "proj/src/dir/node_modules/pkg/index.ts": "export default 'in node_modules';",
  "proj/src/dir/sub/d.ts": "export default 'sub/d';",
  "proj/src/other/o.ts": "export default 'other';",
  "proj/src/[id]/(group)/{x}/p.ts": "export default 'p';",
  "proj/src/[id]/(group)/{x}/q.ts": "export default 'q';",
  "proj/src/üñí/é.ts": "export default 'e-acute';",
  "proj/src/üñí/日本.ts": "export default 'nihon';",
  "proj/src/üñí/😀.ts": "export default 'emoji';",
  "proj/src/üñí/a b.ts": "export default 'space';",
  "proj/src/üñí/it's.ts": "export default 'apostrophe';",
  "proj/src/harness.js": `
    const plain = v => (v && v[Symbol.toStringTag] === "Module" ? { ...v } : v);
    export async function describeGlob(object) {
      if (Object.getPrototypeOf(object) !== Object.prototype) return "not a plain object";
      const out = [];
      for (const [key, value] of Object.entries(object))
        out.push(typeof value === "function" ? [key, "lazy", plain(await value())] : [key, "eager", plain(value)]);
      return out;
    }`,
};

export const A = { default: "a", name: "a", setup: "setup a" };
export const B = { default: "b", name: "b", setup: "setup b" };
export const C = { default: "c", name: "c", setup: "setup c" };

// prettier-ignore
export const cases: Case[] = [
  ['import.meta.glob("./dir/*.ts")', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./dir/skip.ts", "lazy", {"default":"skip"}]]],
  ['import.meta.glob("./dir/*.ts", { eager: true })', [["./dir/Upper.ts", "eager", {"default":"upper"}], ["./dir/a.ts", "eager", A], ["./dir/b.ts", "eager", B], ["./dir/c.ts", "eager", C], ["./dir/skip.ts", "eager", {"default":"skip"}]]],
  ['import.meta.glob(["./dir/*.ts", "./other/*.ts", "!**/skip.ts"])', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./other/o.ts", "lazy", {"default":"other"}]]],
  ['import.meta.glob("./dir/[ab].ts", { import: "setup" })', [["./dir/a.ts", "lazy", "setup a"], ["./dir/b.ts", "lazy", "setup b"]]],
  ['import.meta.glob("./dir/[ab].ts", { import: "setup", eager: true })', [["./dir/a.ts", "eager", "setup a"], ["./dir/b.ts", "eager", "setup b"]]],
  ['import.meta.glob("./dir/[ab].ts", { import: "default" })', [["./dir/a.ts", "lazy", "a"], ["./dir/b.ts", "lazy", "b"]]],
  ['import.meta.glob("./dir/[ab].ts", { import: "default", eager: true })', [["./dir/a.ts", "eager", "a"], ["./dir/b.ts", "eager", "b"]]],
  ['import.meta.glob("./dir/a.ts", { import: "*" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { import: "*", eager: true })', [["./dir/a.ts", "eager", A]]],
  ['import.meta.glob("./dir/a.ts", { import: "" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { import: "missing" })', [["./dir/a.ts", "lazy", null]]],
  ['import.meta.glob("./dir/a.ts", { import: "not an identifier" })', [["./dir/a.ts", "lazy", null]]],
  ['import.meta.glob("./dir/**/*.ts")', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./dir/skip.ts", "lazy", {"default":"skip"}], ["./dir/sub/d.ts", "lazy", {"default":"sub/d"}]]],
  ['import.meta.glob("./dir/**/*.ts", { exhaustive: true })', [["./dir/.dot.ts", "lazy", {"default":"dotfile"}], ["./dir/.hidden/h.ts", "lazy", {"default":"hidden"}], ["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./dir/node_modules/pkg/index.ts", "lazy", {"default":"in node_modules"}], ["./dir/skip.ts", "lazy", {"default":"skip"}], ["./dir/sub/d.ts", "lazy", {"default":"sub/d"}]]],
  ['import.meta.glob("./dir/**")', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./dir/data.json", "lazy", {"default":{"n":1},"n":1}], ["./dir/skip.ts", "lazy", {"default":"skip"}], ["./dir/sub/d.ts", "lazy", {"default":"sub/d"}]]],
  ['import.meta.glob("./dir/*")', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C], ["./dir/data.json", "lazy", {"default":{"n":1},"n":1}], ["./dir/skip.ts", "lazy", {"default":"skip"}]]],
  ['import.meta.glob("/src/dir/[ab].ts")', [["/src/dir/a.ts", "lazy", A], ["/src/dir/b.ts", "lazy", B]]],
  ['import.meta.glob("/src/dir/[ab].ts", { eager: true, import: "name" })', [["/src/dir/a.ts", "eager", "a"], ["/src/dir/b.ts", "eager", "b"]]],
  ['import.meta.glob(["./dir/a.ts", "/src/dir/b.ts"])', [["/src/dir/a.ts", "lazy", A], ["/src/dir/b.ts", "lazy", B]]],
  ['import.meta.glob(["/src/dir/[ab].ts", "!./dir/a.ts"])', [["/src/dir/b.ts", "lazy", B]]],
  ['import.meta.glob("/../outside.ts")', [["../outside.ts", "lazy", {"default":"outside"}]]],
  ['import.meta.glob("../../outside.ts")', [["../../outside.ts", "lazy", {"default":"outside"}]]],
  ['import.meta.glob("./**/[ad].ts", { base: "./dir" })', [["./a.ts", "lazy", A], ["./sub/d.ts", "lazy", {"default":"sub/d"}]]],
  ['import.meta.glob("./*/a.ts", { base: "/src" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./a.ts", { base: "../src/dir" })', [["./a.ts", "lazy", A]]],
  ['import.meta.glob("../other/*.ts", { base: "./dir" })', [["../other/o.ts", "lazy", {"default":"other"}]]],
  ['import.meta.glob("/src/dir/a.ts", { base: "./dir" })', [["./a.ts", "lazy", A]]],
  ['import.meta.glob("/src/dir/a.ts", { base: "./other" })', [["../dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { base: "" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./nope/*.ts")', []],
  ['import.meta.glob("./*.ts")', []],
  ['import.meta.glob("./main.ts", { query: "?x" })', []],
  ['import.meta.glob([])', []],
  ['import.meta.glob(["!./dir/a.ts"])', []],
  ['import.meta.glob(["./dir/a.ts", , "./dir/b.ts"])', [["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B]]],
  ['import.meta.glob(["./dir/a.ts", "./dir/a.ts", "./dir/[ab].ts"])', [["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B]]],
  ['import.meta.glob(["./dir/*.ts", "!./dir/[a-c].ts", "./dir/a.ts"])', [["./dir/Upper.ts", "lazy", {"default":"upper"}], ["./dir/skip.ts", "lazy", {"default":"skip"}]]],
  ['import.meta.glob(`./dir/a.ts`)', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/{a,c}.ts")', [["./dir/a.ts", "lazy", A], ["./dir/c.ts", "lazy", C]]],
  ['import.meta.glob("./dir/?.ts")', [["./dir/a.ts", "lazy", A], ["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C]]],
  ['import.meta.glob("./dir/[!a].ts")', [["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C]]],
  ['import.meta.glob("./dir/[^a].ts")', [["./dir/b.ts", "lazy", B], ["./dir/c.ts", "lazy", C]]],
  ['import.meta.glob("./dir/+(a|b).ts")', []],
  ['import.meta.glob("./dir/sub/../a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/./a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir//a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/*/../a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/.*.ts")', [["./dir/.dot.ts", "lazy", {"default":"dotfile"}]]],
  ['import.meta.glob("./dir/.hidden/*.ts")', [["./dir/.hidden/h.ts", "lazy", {"default":"hidden"}]]],
  ['import.meta.glob("./dir/node_modules/**/*.ts")', [["./dir/node_modules/pkg/index.ts", "lazy", {"default":"in node_modules"}]]],
  ['import.meta.glob(["./dir/node_modules/**/*.ts", "./dir/a.ts"])', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob(["./dir/node_modules/**/*.ts", "./dir/a.ts"], { exhaustive: true })', [["./dir/a.ts", "lazy", A], ["./dir/node_modules/pkg/index.ts", "lazy", {"default":"in node_modules"}]]],
  ['import.meta.glob("./dir/*/pkg/*.ts")', []],
  ['import.meta.glob("./dir/a.ts", { query: "?x=1" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { query: "x=1" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { query: "" })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { query: {} })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { query: { x: 1, y: "z", b: true, f: 1.5 } })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { query: { "a b": "c&d/é" } })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { eager: false, exhaustive: false, caseSensitive: true })', [["./dir/a.ts", "lazy", A]]],
  ['import.meta.glob("./dir/a.ts", { "eager": true, })', [["./dir/a.ts", "eager", A]]],
  ['import.meta.glob("./dir/a.ts", { eager: !0 })', [["./dir/a.ts", "eager", A]]],
  ['import.meta.glob<{ default: string }>("./dir/a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['(import.meta.glob)("./dir/a.ts")', [["./dir/a.ts", "lazy", A]]],
  ['(() => import.meta.glob("./dir/a.ts", { eager: true }))()', [["./dir/a.ts", "eager", A]]],
  ['[import.meta.glob("./dir/a.ts"), import.meta.glob("./dir/b.ts", { eager: true })][1]', [["./dir/b.ts", "eager", B]]],
  ['import.meta.glob("./dir/*.json")', [["./dir/data.json", "lazy", {"default":{"n":1},"n":1}]]],
  ['import.meta.glob("./dir/*.json", { import: "n", eager: true })', [["./dir/data.json", "eager", 1]]],
  ['import.meta.glob("./\\\\[id\\\\]/**/p.ts")', [["./[id]/(group)/{x}/p.ts", "lazy", {"default":"p"}]]],
  ['import.meta.glob("./*/*/*/[pq].ts")', [["./[id]/(group)/{x}/p.ts", "lazy", {"default":"p"}], ["./[id]/(group)/{x}/q.ts", "lazy", {"default":"q"}]]],
  ['import.meta.glob("./**/q.ts")', [["./[id]/(group)/{x}/q.ts", "lazy", {"default":"q"}]]],
  ['Object.fromEntries(Object.keys(import.meta.glob("./dir/[ab].ts")).map(key => [key, 1]))', [["./dir/a.ts", "eager", 1], ["./dir/b.ts", "eager", 1]]],
  ['Object.fromEntries(Object.values(import.meta.glob("./dir/[ab].ts", { eager: true, import: "name" })).map(name => [name, 1]))', [["a", "eager", 1], ["b", "eager", 1]]],
  ['import.meta.glob("./üñí/*.ts")', [["./üñí/a b.ts", "lazy", {"default":"space"}], ["./üñí/it's.ts", "lazy", {"default":"apostrophe"}], ["./üñí/é.ts", "lazy", {"default":"e-acute"}], ["./üñí/日本.ts", "lazy", {"default":"nihon"}], ["./üñí/😀.ts", "lazy", {"default":"emoji"}]]],
  ['import.meta.glob("./üñí/*.ts", { eager: true, import: "default" })', [["./üñí/a b.ts", "eager", "space"], ["./üñí/it's.ts", "eager", "apostrophe"], ["./üñí/é.ts", "eager", "e-acute"], ["./üñí/日本.ts", "eager", "nihon"], ["./üñí/😀.ts", "eager", "emoji"]]],
  ['import.meta.glob("./*/日*.ts")', [["./üñí/日本.ts", "lazy", {"default":"nihon"}]]],
];
