// printer/emitflags.go: the flags that a transformation or the node builder leaves on a node for the printer.
use crate::nodebuilder::types::define_flags;

define_flags!(EmitFlags: u32 {
    NONE = 0,
    SINGLE_LINE = 1 << 0,
    MULTI_LINE = 1 << 1,
    NO_LEADING_SOURCE_MAP = 1 << 2,
    NO_TRAILING_SOURCE_MAP = 1 << 3,
    NO_NESTED_SOURCE_MAPS = 1 << 4,
    NO_TOKEN_LEADING_SOURCE_MAPS = 1 << 5,
    NO_TOKEN_TRAILING_SOURCE_MAPS = 1 << 6,
    NO_LEADING_COMMENTS = 1 << 7,
    NO_TRAILING_COMMENTS = 1 << 8,
    NO_NESTED_COMMENTS = 1 << 9,
    HELPER_NAME = 1 << 10,
    EXPORT_NAME = 1 << 11,
    LOCAL_NAME = 1 << 12,
    INDENTED = 1 << 13,
    NO_INDENTATION = 1 << 14,
    REUSE_TEMP_VARIABLE_SCOPE = 1 << 15,
    CUSTOM_PROLOGUE = 1 << 16,
    NO_ASCII_ESCAPING = 1 << 17,
    EXTERNAL_HELPERS = 1 << 18,
    START_ON_NEW_LINE = 1 << 19,
    INDIRECT_CALL = 1 << 20,
    ASYNC_FUNCTION_BODY = 1 << 21,
    NO_LEXICAL_ARGUMENTS = 1 << 22,
    TRANSFORM_PRIVATE_STATIC_ELEMENTS = 1 << 23,
    NO_LEXICAL_THIS = 1 << 24,
    NO_SOURCE_MAP = (1 << 2) | (1 << 3),
    NO_TOKEN_SOURCE_MAPS = (1 << 5) | (1 << 6),
    NO_COMMENTS = (1 << 7) | (1 << 8),
});
