// Snippets on which parsers differ: sloppy mode, Annex B, JSX as acorn reads it, what only TypeScript 5 or only Babel accepts.
//
//   bun gaps.ts <out.jsonl>
//
// Writes a line {"id", "filename", "code", "sourceType", "parser"} for each: the input of ../ast/expected.ts, ../ast/expected-espree.ts,
// `bun-lint ast estree-batch` and `bun-lint parser errors`. ../ast/diff.ts compares the trees.
import { writeFileSync } from "node:fs";
const out: string[] = [];
let n = 0;
function add(filename: string, sourceType: string, codes: string[]) {
  for (const code of codes) out.push(JSON.stringify({ id: `${filename}:${sourceType}#${n++}: ${code.slice(0, 60).replace(/[^ -~]/g, "~")}`, filename, code, sourceType, parser: /\.[cm]?jsx?$/.test(filename) ? "espree" : "typescript" }));
}
const both = [
  "<>x<\n/>", "<a>x< /a>", "<a>x< /* c */ /a>", "<>x< // c\n/>", "<a>x</ a>", "<a>x</\na>", "<a /\n>", "<\n></>", "<a><b/>< / a>",
  "x = a <// c\nb;", "x = a </* c */b;", "x = a >// c\nb", "x = a</b/.test(c)",
  "new import.meta.x()", "new import.meta.x", "new import.meta", "new import.meta()", "new (import.meta.x)()", "new import('a')", "new import('a').b", "new import('a')()",
  "foo.\nbar in x;", "foo?.\nbar instanceof x;", "x = foo?.a.\nbar in y;", "foo.\nbar\nbaz", "foo.\nif (x) y", "foo.\nbar baz",
  "<a />.b", "<a />.b()", "<></>[0]", "x = <a />.b", "<a />()", "<a />`x`", "<a />++", "new <a />", "new <a />()", "class C extends <a /> {}", "<a /> < b", "<a />?.b", "typeof <a />.b", "-<a/>", "x = <a/> ? 1 : 2", "a = <b/>\n<c/>",
  "\uFEFF#!/x\n/* lowercase */", "\uFEFF#!/usr/bin/env node\nvar a = 1;\n", "#!/x\nvar a", "\uFEFFvar a",
  "var \u1C8A;", "var a\u0897;", "var a\\u0897;", "class C { #a\u0897 }", "var \\u1C89", "var \u{10D4A}", "var \u088F",
  "class C { #m = 1; static access(obj) { return obj?.#m; } }", "class C { #m; f(o) { o?.#m(); o?.a.#m; o?.a.#m.b?.#m; delete o?.#m.a } }",
  "for (let a = () => { b in c }; ;);", "for (let a = function () { b in c }; ;);", "for (let a = [b in c]; ;);", "for (a = [b in c]; ;);", "for ([a in b]; ;);", "for (let a = (b = c in d) => {}; ;);", "for (let a = function (b = c in d) {}; ;);",
  "for (let a = {b: c in d}; ;);", "for (let a = {[c in d]: 1}; ;);", "for (let a = {b(x = c in d) { e in f }}; ;);", "for (let a = class { x = c in d; [e in f]() { g in h } static { i in j } }; ;);", "for (let a = class extends (b in c) {}; ;);", "for (let a = `${b in c}`; ;);", "for (let a = b[c in d]; ;);", "for (let a = b(c in d); ;);", "for (let a = b ? c in d : e; ;);", "for (let [a = b in c] = []; ;);", "for (let {a = b in c} = {}; ;);", "for ([ x = 'x' in {} ] of [[]]);", "for ({ x = 'x' in {} } of [[]]);", "for (var a = async (b = c in d) => { e in f }; ;);", "for (var a = <b c={d in e}>{f in g}</b>; ;);", "for (var a = new b(c in d); ;);",
  "export * from 'a'\nwith { type: 'json' }", "export {a} from 'a'\nwith { type: 'json' }", "import a from 'a'\nwith { type: 'json' }", "import 'a'\nwith { type: 'json' }", "export * as b from 'a' with { type: 'json' }",
  "x = (@dec class {}, 1)", "x = @dec class {}", "(@dec class {})", "@dec class A {}", "export @dec class A {}", "@dec export class A {}", "export default @dec class {}",
  "try {} finally {}", "<a>{...e}</a>", "var { \\u0061 } = b", "var { \\u0061 = 1 } = b", "({ \\u0061 } = b)", "({ \\u0061 })",
  "class A { 1n = 3; 1n() {} }", "({ 1n: 3, 1n() {} })", "var { 1n: a } = b",
  "(async ())", "typeof d.i\\u{6e}terface", "class A { static async constructor() {} }",
  "a?.b?.c", "await (x)", "await x", "for await (x of y);",
  "static in a", "readonly in a", "accessor in a", "abstract in a", "declare in a", "type in a", "namespace in a", "module in a", "override in a", "public in a", "global in a", "async in a", "of in a", "get in a", "using in a",
  "type\nA = 1", "declare\nfoo", "namespace\nfoo", "module\nfoo", "abstract\nclass A {}", "interface\nFoo\n{}", "type = 1", "declare = 1", "module.exports = 1", "namespace.a", "global.a = 1", "abstract()", "enum1 = 2",
  "a = b\n++c", "a\n/b/g", "x = y / z / w", "a ? (b) : c => d", "a ? (b) : (c) => d", "a ? (b, c) : d => e", "a ? b : (c) : d => e",
  "a < b > c", "a < b > (c)", "f<T>(x)", "a<b>c", "a<b>>c", "new A<B>(c)", "a < b >> c", "(a < b) > c", "f(a < b, c > (d))", "a<b>`x`", "a?.<b>(c)",
  "x = a as b", "x = a satisfies b", "a!", "a!.b", "x = <T>y",
  "/[/]/", "/a/dgimsuy", "/a/v", "a = /=/", "a /= /b/",
  "'\\u2028'", "'\u2028'", "`\\u{g}`", "tag`\\u{g}`",
  "({ async *[a]() {}, get [b]() {}, set c(d) {} })", "class A { static {} static static; static async *a() {} get; set; async; static }", "class A { 'constructor'() {} }", "class A { get\na() {} }", "class A { static\na }", "class A { accessor a; accessor\nb; static accessor c }",
  "label: function f() {}", "if (a) function f() {}", "if (a) function f() {} else function g() {}",
  "import a, * as b from 'c'", "import { default as a, 'b c' as d } from 'e'", "export { a as 'b c' }; var a", "export * as 'a b' from 'c'", "import.meta", "import('a', { with: {} })", "import('a',)",
  "import defer * as a from 'b'", "import source a from 'b'", "import.defer('a')", "import.source('a')",
  "using a = b", "{ using a = b, c = d }", "await using a = b", "for (using a of b);", "for (await using a of b);", "for await (using a of b);", "using\na = b", "using[a]", "using.a", "using(a)", "for (using of of);", "for (using of = a;;);", "for (using in a);", "for (using o\\u0066 of of);", "for await (using \\u006ff of of);", "{ using \\u0061b = c; }", "{ \\u0075sing a = b }", "await\n using x = h()",
  "a ??= b; a ||= c; a &&= d", "a ** b ** c", "(-a) ** b", "a?.[b]?.(c)", "a?.b\n`c`", "1_000", ".1e-1_0", "0b1n", "0.0_1",
  "x = { __proto__: a, __proto__ }", "({ a = 1 } = b)", "[a = 1, ...b] = c", "({ ...a.b } = c)", "[(a)] = b", "[(a.b)] = c", "({ a: (b) } = c)",
  "function* g() { yield\n* 2 }", "function* g() { yield /a/ }", "function* g() { yield* a; yield; (yield) }", "async function f() { await /a/; for await (a of b); }", "async () => await a", "async a => a", "async (a) => a", "async\n(a) => a", "async\na => a", "async\nfunction f() {}",
  "var async; async\n(a)", "(async)", "async()", "async(a, b)", "new async()", "async.a", "async = 1", "async ? a : b", "async: a",
  "a = function* () {}", "a = async function* b() {}", "class A extends B { constructor() { super(); super.a; super[b] } }", "new.target", "function f() { new.target }",
  "do a; while (b) c", "do {} while (a)\nb", "if (a); else;", "for (;;);", "switch (a) { case b: default: case c: }", "a: b: c;", "a: { break a }", "with1: 1", "debugger", "throw a", ";;",
  "`a${b}c${`d${e}`}`", "a`b`", "a.b`c`", "a`b``c`", "new a`b`", "new a`b`()",
  "<a b='&amp;' c=\"d\" e={f} {...g} h:i='j' k-l />", "<a.b.c></a.b.c>", "<a:b></a:b>", "<a-b></a-b>", "<a>&amp;&nbsp;&#65;&#x41;&foo;</a>", "<a>{/* c */}</a>", "<a>{}</a>", "<a b=<c/> />", "<a b=<></> />", "<this.a />", "<this />", "<a>'\"</a>", "<a>\n  b\n  c\n</a>", "<a>></a>", "<a>}</a>", "<A<B />", "<a b={...c} />", "<a {.../* c */d} />", "<a // c\n/>", "<a /* c */ b /* d */ = /* e */ 'f' />", "< a />", "<a. b />", "<a .b />", "<a : b />", "<a>{b}{c}</a>", "<a\n/>", "<a b\n=\n'c'/>", "<a>\u00a0</a>", "<a b='\n'/>", "<a b='\\'/>", "<a b='c\\'/>",
];
const script = [
  "{ <!-- a\n}", "{\n--> a\n}", "a <!--b", "-->", "--> a\nb", "/* c */ --> a\nb", "/*\n*/ --> a\nb", "a\n--> b\nc", "a --> b", "x = a <!--b\n+ c", "<!---->", "a<!--b\n", "a = b\n/* c */ /* d\n */ --> e\n", "a-->b", "a--\n>b", "<!-- a", "'<!--'", "`<!--`", "/<!--/", "// <!--\na", "x = y-->0",
  "for (let = 1;;);", "for (let = [];;);", "for (let();;);", "for (let([]);;);", "for (let()[a];;);", "for (let`[]`;;);", "for (let.a;;);", "for (let.a = 1;;);", "for (let.a[b];;);", "for (let;;);", "for (let in foo);", "for (let.a in foo);", "for (let()[a] in foo);", "for (let.a.b in foo);", "for (let, a;;);", "for (let ? a : b;;);", "for (let + 1;;);", "for (let\n;;);", "for (let instanceof a;;);", "for (let in a, b);",
  "while (false) let // ASI\nx = 1;", "if (false) let // ASI\nx = 1;", "if (1) let\n{}", "for (x of y) let // ASI\n x = 1", "L: let\n{}", "do let\nwhile (a)", "if (a) let; else let", "with (a) let\nb", "for (;;) let\nx", "for (a in b) let\nx", "if (a) let\nlet\nb", "if (a) let\nx\nelse let\ny",
  "let", "let;", "let = 1", "let\nx", "let\n[a] = b", "let [a] = b", "let\n{a} = b", "let.a", "let()", "let++", "let\n++a", "let: a", "let\nlet", "var let", "let in a", "let instanceof a", "let\nin a", "(let)", "(let[a])", "a = let", "let => a", "(let) => a", "let\nyield", "let\nawait", "let await = 1", "let yield = 1", "let async = 1", "let static", "let of", "let\nof", "typeof let", "let `a`", "let ? a : b", "let, a", "function let() {}", "function f(let) {}", "let\nfunction f() {}", "let\nclass A {}", "let\nif (a) b", "let /a/g", "let\n/a/g", "let\n(a)", "let == 1", "let || a",
  "l\\u0065t // ASI\na;", "\\u006cet[x];", "l\\u0065t\na", "l\\u0065t = 1", "l\\u0065t\n[a] = b", "var l\\u0065t",
  "01", "08", "019.5", "({ 012: 1 })", "'\\1'", "\"\\08\"", "'\\8'", "'\\9'", "(08).a", "(0123).a", "0123.a", "0123.toString()", "08.5", "09e1", "09.1_1", "09e1_1", "00", "07", "0777", "-010", "010 + 1", "'\\0'", "'\\00'", "'\\07'", "'\\377'", "'\\400'", "'\\18'", "'\\0a'", "`\\0`", "tag`\\1`", "a = { 010: 1, 08: 2 }", "class A { 010() {} }", "'\\1'; 'use strict'", "function f() { '\\1' }", "08n1", "08.a1", "0_1x",
  "await", "await (x)", "await(x)", "await\n(x)", "await = 1", "var await", "await.a", "await instanceof Function", "assert(await instanceof Function);", "await in a", "await ? a : b", "function await() {}", "await => a", "(await) => a", "for (await of []);", "for (await of [of]);", "for (await in a);", "for (await;;);", "await: a", "await + 1", "await\nx", "await / a / b", "function f() { await }", "function f(await) {}", "function f() { var await; await(1) }", "x = { await }", "({ await } = a)", "class A { await() {} }", "class A { [await]() {} }", "await `a`", "await++", "await[a]", "new await", "new await()", "typeof await", "a = await", "-await", "await ** 2", "async function f() { function g() { await } }", "async function f() { function g(await) {} }", "() => await", "() => { await }", "(a = await) => a", "async (a = await) => a",
  "yield", "yield = 1", "var yield", "yield in a", "yield\nx", "yield * 2", "yield / a / b", "yield(a)", "yield.a", "yield ? a : b", "function yield() {}", "yield => a", "(yield) => a", "yield: a", "function f() { yield }", "function* g() { function h() { yield } }", "function* g() { function h(yield) {} }", "x = { yield }", "yield instanceof a", "yield + 1", "yield++", "yield[a]", "yield `a`", "new yield", "typeof yield", "function* yield() {}", "x = function yield() {}", "for (yield in a);", "for (yield of a);", "for (yield;;);", "function* g() { (function yield() {}) }",
  "for (var a = 1 in b);", "for (var a = (b in c) in {});", "for (var a = [b in c] in {});", "for (var a = function (x = b in c) {} in {});", "for (var a = () => { b in c } in {});", "for (var a = b ? c : d in e);", "for (var a = 0 in b, c);",
  "if (a) function f() {}", "if (a) function f() {} else function g() {}", "if (a) ; else function g() {}", "a: function f() {}", "a: b: function f() {}", "while (a) b: function f() {}1",
  "implements", "interface", "package", "private", "protected", "public", "static", "var static, interface, package", "static = 1", "interface\nA\n{}", "public\nclass A {}", "private\na", "function static() {}", "static: a", "static\na", "static()", "implements in a", "interface in a", "package.a", "private = public", "protected++",
  "with (a) b", "with (a) { b }", "delete a", "arguments = 1", "eval = 1", "function f(a, a) {}", "var eval", "function f(eval) {}", "try {} catch (eval) {}", "({ eval } = a)", "eval++", "arguments => a",
  "return", "function f() { return\na }", "a = b\n(c)", "var a\n\n\nb", "x\n++\ny", "/* */ a", "a /* \n */ ++b", "new.target",
  "try {} catch (e) { var e }", "try {} catch (e) { for (var e of a); }1", "function f() {} function f() {}", "{ function f() {} function f() {} }", "var a; var a", "switch (a) { case 1: function f() {} case 2: function f() {} }",
  "a = 0; a\n<!--\nb", "/(?<a>.)\\k<a>/", "/\\k<a>/", "/\\c/", "/[\\c]/", "/a{/", "/{/", "/]/", "/\\1/", "/(?=a)*/", "/\\8/", "/[\\d-a]/", "/\\u{1}/", "/\\p{L}/", "/(?<!a)*/1",
  "import('a')", "import.meta",
  "async function f() { await\nx }", "async () => { await x }", "async function await() {}", "x = async function await() {}1", "async function f() { var await }1", "x = async await => a1",
  "'use strict'; 010", "function f() { 'use strict'; 010 }", "function f() { 'use strict'; let }", "'use strict'; yield", "'use strict'; var let",
];
const module = ["await (x)", "await x", "await\n(x)", "await /a/", "await [a]", "await `a`", "await +a", "await -a", "for await (a of b);", "function f() { await }", "export default await a", "a = await b", "await a ** 2", "(await a) ** 2", "class A { [await a]() {} }", "class A { a = await }", "class A { static { await } }", "export {}; <!-- a", "010", "'\\1'", "let\nx", "if (a) let\nx", "yield", "var await", "await", "export default function () {} /a/", "export default class {} /a/", "export default (a, b)", "export default async function () {}", "export default async () => {}", "export default async", "export default a = b", "export default {}", "export default [] ", "export default function* () {}", "export default abstract", "export default interface", "export default type", "export default enum1", "export { a }; var a", "export var a, b", "export function f() {}", "export class A {}", "export const a = 1", "export let a", "export async function f() {}", "export * from 'a'", "export {} from 'a'", "import {} from 'a'", "import a from 'a'", "import type from 'a'", "import type, { a } from 'b'", "import { type } from 'a'", "import { type as as } from 'a'", "import { as as as } from 'a'", "import defer from 'a'", "import source from 'a'", "import { a as b, } from 'c'", "export { default } from 'a'", "export { default as a } from 'b'", "export { a as default }; var a", "import * as a from 'b' with { type: 'json', 'a': 'b' }", "import a from 'b' assert { type: 'json' }", "export * from 'b' assert { type: 'json' }", "import a from 'b'\nassert\n({})"];
add("file.js", "module", both); add("file.js", "script", both); add("file.js", "script", script); add("file.js", "commonjs", ["return", "return a", "await (x)", "new.target", "<!-- a", "let\nx", "010", "using a = b"]); add("file.js", "module", module); add("file.js", "module", script);
add("file.cjs", "script", ["await (x)", "await x", "import.meta", "export {}"]); add("file.mjs", "script", ["await (x)"]); add("file.cjs", "module", ["await (x)"]);
const ts = ["const a = foo<?>;", "type T = typeof foo<?>;", "let g: A<?>;", "foo<string?>", "foo<?string>", "let g: *", "let g: string!", "let g: ?", "let g: A<?, ?>",
  "interface I { #constructor(): void; #a: 1 }", "type T = { #a(): void }", "interface I { get #a(): 1; set #b(c) }",
  "x = (@dec class {}, 1)", "class A { public async a!: number }", "({ export @d m() {} })", "let a: function(string): void", "let a: import('m')<>",
  "import a from 'm' assert { type: 'json' }", "export * from 'm' assert { type: 'json' }", "type A = import('A', { assert: { 'resolution-mode': 'import' } })", "type A = import('A', { with: { 'resolution-mode': 'import' } })",
  "for (let a = () => { b in c }; ;);", "for (let a = function () { b in c }; ;);", "for (let a = () => { a && b in c }; ;);", "for (let a = () => { L: b in c }; ;);", "for (let a = () => { if (x) b in c }; ;);", "for (let a = [b in c]; ;);", "for (let a = class { m() { b in c } }; ;);", "for (let a = { m() { b in c } }; ;);", "for (let a = () => { async in c }; ;);", "for (let a = () => { (b) in c }; ;);", "for (let a = () => { 1 in c }; ;);", "for (let a = () => { let in c }; ;);", "for (let a = () => { type in c }; ;);", "for (let a = () => { this in c }; ;);", "for (let a = () => { await in c }; ;);",
  "await (x)", "await x", "new import.meta.x()", "foo.\nbar in x;", "class C { #m; f(o) { o?.#m } }", "for (let in foo);", "for (let;;);", "for (let = 1;;);", "if (a) let\nx", "<!-- a", "010", "'\\1'", "\uFEFF#!/x\nvar a", "var \u1C8A;",
  "(class extends f<<T>(v: T) => void> {});", "f<<T>(v: T) => void>()", "new f<<T>(v: T) => void>()", "class A extends B<<T>() => void> {}", "class A implements B<<T>() => void> {}", "interface A extends B<<T>() => void> {}", "let a: B<<T>() => void>", "a<<T>() => void>`x`",
  "export * from 'a'\nwith { type: 'json' }", "import a from 'a'\nwith { type: 'json' }", "enum A { 'b', c = 1, ['d'] }", "declare module 'a';", "abstract class A { abstract a(): void }", "namespace A.B {}", "module A {}", "declare global {}", "type A = `a${B}`", "let a = <T,>(b: T) => b", "let a = <T>b", "a satisfies B", "a as const", "a!", "a!!", "a!.b!", "function f(this: A) {}", "class A<in out T> {}", "function f<const T>() {}", "let a: unique symbol", "let a: asserts b", "function f(a): asserts a is B {}", "accessor", "class A { accessor a = 1; declare b; override c; readonly d }", "import type A from 'a'", "import { type A } from 'a'", "export type { A }", "export type * from 'a'", "export type * as A from 'a'", "import A = require('a')", "import type A = require('a')", "export import A = B.C", "export = A", "export as namespace A", "import defer * as a from 'b'", "using a = b", "await using a = b",
];
add("file.ts", "module", ts); add("file.ts", "script", ts); add("file.cts", "script", ["await (x)", "await x"]); add("file.mts", "script", ["await (x)"]); add("file.cts", "module", ["await (x)"]);
add("file.tsx", "module", ["<Component<<T>(v: T) => void> />", "<a>x< /a>", "<a />.b", "<A<B> />", "<A<B>></A>", "x = a <// c\nb", "<T,>(a: T) => a", "<T extends U>(a: T) => a", "new <a/>", "<>x<\n/>"]);
writeFileSync(process.argv[2], out.join("\n") + "\n");
console.log(out.length);
