declare const s: string, n: number, b: boolean, o: { a: 1 }, sym: symbol, u: string | undefined, bi: bigint, an: any;
const a1 = s * n;
const a2 = n + o;
const a3 = b + b;
const a4 = b & b;
const a5 = s < n;
const a6 = s === n;
const a7 = o instanceof n;
const a8 = n in o;
const a9 = "a" in s;
const a10 = (n, s);
const a11 = u.length;
const a12 = -sym;
const a13 = +bi;
const a14 = bi + n;
const a15 = n << 32;
const a16 = s ?? n;
const a17 = { } === { };
const a18 = n === NaN;
const a19 = !s && n;
const a20: number = s || n;
const a21 = typeof s === "strin";
const a22 = void 0 ?? 1;
let m = 1; m++; s++; (n as any)++;
const k = 1; k = 2; k += 1;
delete o.a;
delete s;
[m, s] = [1, 2];
({ a: m } = { a: "x" });
n = s;
an **= bi;
const a23 = await n;
const a24 = n ? s : b;
const a25: string = a24;
