import { describe, expect, test } from "bun:test";
import { bunEnv, bunExe, isWindows, tempDir } from "harness";
import { join } from "path";

// --compile --bytecode embeds pre-generated bytecode for internal modules
// (node:fs, node:stream etc) into the standalone executable so they don't
// need to be parsed at runtime. This test verifies the executable still
// works correctly with the embedded builtin bytecode.
describe("compile --bytecode builtin modules", () => {
  test("internal modules work in standalone executable with bytecode", async () => {
    using dir = tempDir("compile-builtin-bytecode", {
      "app.js": `
        const fs = require("node:fs");
        const path = require("node:path");
        const stream = require("node:stream");
        const util = require("node:util");

        // Use functions from each module to ensure bytecode decodes correctly
        const tmpFile = path.join(process.env.TMPDIR || "/tmp", "builtin-bc-test-" + Date.now() + ".txt");
        fs.writeFileSync(tmpFile, "hello");
        const content = fs.readFileSync(tmpFile, "utf8");
        fs.unlinkSync(tmpFile);

        const readable = stream.Readable.from(["a", "b", "c"]);
        let chunks = [];
        readable.on("data", c => chunks.push(c));
        readable.on("end", () => {
          console.log(JSON.stringify({
            content,
            chunks: chunks.join(""),
            inspected: util.inspect({ x: 1 }),
          }));
        });
      `,
    });

    const outfile = join(String(dir), isWindows ? "app.exe" : "app");

    await using buildProc = Bun.spawn({
      cmd: [bunExe(), "build", "--compile", "--bytecode", join(String(dir), "app.js"), "--outfile", outfile],
      env: bunEnv,
      stderr: "pipe",
      stdout: "pipe",
    });
    const [, buildStderr, buildExit] = await Promise.all([
      buildProc.stdout.text(),
      buildProc.stderr.text(),
      buildProc.exited,
    ]);
    expect(buildStderr).not.toContain("error");
    expect(buildExit).toBe(0);

    await using runProc = Bun.spawn({
      cmd: [outfile],
      env: bunEnv,
      stderr: "pipe",
      stdout: "pipe",
    });
    const [runStdout, runStderr, runExit] = await Promise.all([
      runProc.stdout.text(),
      runProc.stderr.text(),
      runProc.exited,
    ]);

    expect(runStderr).toBe("");
    const output = JSON.parse(runStdout.trim());
    expect(output).toEqual({
      content: "hello",
      chunks: "abc",
      inspected: "{ x: 1 }",
    });
    expect(runExit).toBe(0);
  });

  test("executable without --bytecode still works (no builtin bytecode)", async () => {
    using dir = tempDir("compile-no-builtin-bytecode", {
      "app.js": `
        const fs = require("node:fs");
        console.log(typeof fs.readFileSync);
      `,
    });

    const outfile = join(String(dir), isWindows ? "app.exe" : "app");

    await using buildProc = Bun.spawn({
      cmd: [bunExe(), "build", "--compile", join(String(dir), "app.js"), "--outfile", outfile],
      env: bunEnv,
      stderr: "pipe",
      stdout: "pipe",
    });
    await buildProc.exited;
    expect(buildProc.exitCode).toBe(0);

    await using runProc = Bun.spawn({
      cmd: [outfile],
      env: bunEnv,
      stderr: "pipe",
      stdout: "pipe",
    });
    const [stdout, , exitCode] = await Promise.all([runProc.stdout.text(), runProc.stderr.text(), runProc.exited]);

    expect(stdout.trim()).toBe("function");
    expect(exitCode).toBe(0);
  });
});
