bun_core::comptime_string_set! {
    // The v1 list repeats several v2.3 entries verbatim — duplicates dropped here
    // (commented inline) because duplicate keys are a compile error.
    pub static ALL_YARN_COMMANDS = {
    // yarn v2.3 commands
    b"add",
    b"bin",
    b"cache",
    b"config",
    b"dedupe",
    b"dlx",
    b"exec",
    b"explain",
    b"info",
    b"init",
    b"install",
    b"link",
    b"node",
    b"npm",
    b"pack",
    b"patch",
    b"plugin",
    b"rebuild",
    b"remove",
    b"run",
    b"set",
    b"unplug",
    b"up",
    b"why",
    b"workspace",
    b"workspaces",

    // yarn v1 commands
    b"access",
    // b"add",
    b"audit",
    b"autoclean",
    // b"bin",
    // b"cache",
    b"check",
    // b"config",
    b"create",
    // b"exec",
    b"generate-lock-entry",
    b"generateLockEntry",
    b"global",
    b"help",
    b"import",
    // b"info",
    // b"init",
    // b"install",
    b"licenses",
    // b"link",
    b"list",
    b"login",
    b"logout",
    // b"node",
    b"outdated",
    b"owner",
    // b"pack",
    b"policies",
    b"publish",
    // b"remove",
    // b"run",
    b"tag",
    b"team",
    b"unlink",
    // b"unplug",
    b"upgrade",
    b"upgrade-interactive",
    b"upgradeInteractive",
    b"version",
    b"versions",
    // b"why",
    // b"workspace",
    // b"workspaces",
    };
}
