use core::mem::size_of;

use bun_collections::{ByteList, MultiArrayList};
use bun_core::{err, Ordinal};
use bun_logger::Loc;
use bun_output::{declare_scope, scoped_log};
use bun_paths::{self, PathBuffer, Platform};
use bun_semver::String as SemverString;
use bun_str::{self, strings, ZigStringSlice};
use bun_sys;

use crate::vlq::decode as decode_vlq;
use crate::{LineColumnOffset, ParseResult, ParseResultFail, ParsedSourceMap};

declare_scope!(SourceMap, visible);

// TODO(port): MultiArrayList SoA column accessors (`items_generated()`, `items_original()`,
// `items_source_index()`, `items_name_index()`, `slice()`/`slice_mut()`) are assumed to be
// generated by a derive on the element struct in `bun_collections`. Exact API is Phase-B.

#[derive(Clone, Copy)]
pub struct Mapping {
    pub generated: LineColumnOffset,
    pub original: LineColumnOffset,
    pub source_index: i32,
    pub name_index: i32, // = -1
}

impl Default for Mapping {
    fn default() -> Self {
        Self {
            generated: LineColumnOffset::default(),
            original: LineColumnOffset::default(),
            source_index: 0,
            name_index: -1,
        }
    }
}

/// Optimization: if we don't care about the "names" column, then don't store the names.
#[derive(Clone, Copy, Default)]
pub struct MappingWithoutName {
    pub generated: LineColumnOffset,
    pub original: LineColumnOffset,
    pub source_index: i32,
}

impl MappingWithoutName {
    pub fn to_named(&self) -> Mapping {
        Mapping {
            generated: self.generated,
            original: self.original,
            source_index: self.source_index,
            name_index: -1,
        }
    }
}

pub enum ListValue {
    WithoutNames(MultiArrayList<MappingWithoutName>),
    WithNames(MultiArrayList<Mapping>),
}

impl Default for ListValue {
    fn default() -> Self {
        ListValue::WithoutNames(MultiArrayList::default())
    }
}

impl ListValue {
    pub fn memory_cost(&self) -> usize {
        match self {
            ListValue::WithoutNames(list) => list.memory_cost(),
            ListValue::WithNames(list) => list.memory_cost(),
        }
    }

    pub fn ensure_total_capacity(&mut self, count: usize) -> Result<(), bun_alloc::AllocError> {
        match self {
            ListValue::WithoutNames(list) => list.ensure_total_capacity(count),
            ListValue::WithNames(list) => list.ensure_total_capacity(count),
        }
    }
}

#[derive(Default)]
pub struct List {
    pub r#impl: ListValue,
    pub names: Box<[SemverString]>,
    pub names_buffer: ByteList,
}

impl List {
    fn ensure_with_names(&mut self) -> Result<(), bun_alloc::AllocError> {
        if matches!(self.r#impl, ListValue::WithNames(_)) {
            return Ok(());
        }

        // PORT NOTE: reshaped for borrowck — move the without_names list out, build the
        // with_names list, then assign back. The old list drops at end of scope.
        let ListValue::WithoutNames(without_names) =
            core::mem::replace(&mut self.r#impl, ListValue::WithNames(MultiArrayList::default()))
        else {
            unreachable!()
        };

        let mut with_names: MultiArrayList<Mapping> = MultiArrayList::default();
        with_names.ensure_total_capacity(without_names.len())?;
        // `without_names` drops at end of scope (was `defer without_names.deinit(allocator)`).

        // SAFETY: capacity reserved on the line above; columns are fully overwritten below.
        unsafe { with_names.set_len(without_names.len()) };
        let old_slices = without_names.slice();
        let mut new_slices = with_names.slice_mut();

        new_slices
            .generated_mut()
            .copy_from_slice(old_slices.generated());
        new_slices
            .original_mut()
            .copy_from_slice(old_slices.original());
        new_slices
            .source_index_mut()
            .copy_from_slice(old_slices.source_index());
        new_slices.name_index_mut().fill(-1);

        self.r#impl = ListValue::WithNames(with_names);
        Ok(())
    }

    fn find_index_from_generated(
        line_column_offsets: &[LineColumnOffset],
        line: Ordinal,
        column: Ordinal,
    ) -> Option<usize> {
        let mut count = line_column_offsets.len();
        let mut index: usize = 0;
        while count > 0 {
            let step = count / 2;
            let i: usize = index + step;
            let mapping = line_column_offsets[i];
            if mapping.lines.zero_based() < line.zero_based()
                || (mapping.lines.zero_based() == line.zero_based()
                    && mapping.columns.zero_based() <= column.zero_based())
            {
                index = i + 1;
                count = count.saturating_sub(step + 1);
            } else {
                count = step;
            }
        }

        if index > 0 {
            if line_column_offsets[index - 1].lines.zero_based() == line.zero_based() {
                return Some(index - 1);
            }
        }

        None
    }

    pub fn find_index(&self, line: Ordinal, column: Ordinal) -> Option<usize> {
        match &self.r#impl {
            ListValue::WithoutNames(list) => {
                if let Some(i) =
                    Self::find_index_from_generated(list.items_generated(), line, column)
                {
                    return Some(i);
                }
            }
            ListValue::WithNames(list) => {
                if let Some(i) =
                    Self::find_index_from_generated(list.items_generated(), line, column)
                {
                    return Some(i);
                }
            }
        }

        None
    }

    pub fn sort(&mut self) {
        match &mut self.r#impl {
            ListValue::WithoutNames(list) => {
                let ctx = SortContext { generated: list.items_generated() };
                // TODO(port): MultiArrayList::sort takes a context with `less_than(a_index, b_index)`;
                // borrowck requires the column slice borrow not overlap the sort's &mut self.
                list.sort(ctx);
            }
            ListValue::WithNames(list) => {
                let ctx = SortContext { generated: list.items_generated() };
                list.sort(ctx);
            }
        }
    }

    pub fn append(&mut self, mapping: &Mapping) -> Result<(), bun_alloc::AllocError> {
        match &mut self.r#impl {
            ListValue::WithoutNames(list) => {
                list.push(MappingWithoutName {
                    generated: mapping.generated,
                    original: mapping.original,
                    source_index: mapping.source_index,
                })?;
            }
            ListValue::WithNames(list) => {
                list.push(*mapping)?;
            }
        }
        Ok(())
    }

    pub fn find(&self, line: Ordinal, column: Ordinal) -> Option<Mapping> {
        match &self.r#impl {
            ListValue::WithoutNames(list) => {
                if let Some(i) =
                    Self::find_index_from_generated(list.items_generated(), line, column)
                {
                    return Some(list.get(i).to_named());
                }
            }
            ListValue::WithNames(list) => {
                if let Some(i) =
                    Self::find_index_from_generated(list.items_generated(), line, column)
                {
                    return Some(list.get(i));
                }
            }
        }

        None
    }

    pub fn generated(&self) -> &[LineColumnOffset] {
        match &self.r#impl {
            ListValue::WithoutNames(list) => list.items_generated(),
            ListValue::WithNames(list) => list.items_generated(),
        }
    }

    pub fn original(&self) -> &[LineColumnOffset] {
        match &self.r#impl {
            ListValue::WithoutNames(list) => list.items_original(),
            ListValue::WithNames(list) => list.items_original(),
        }
    }

    pub fn source_index(&self) -> &[i32] {
        match &self.r#impl {
            ListValue::WithoutNames(list) => list.items_source_index(),
            ListValue::WithNames(list) => list.items_source_index(),
        }
    }

    pub fn name_index(&self) -> &[i32] {
        match &self.r#impl {
            // TODO(port): Zig `inline else` calls `.items(.name_index)` on both arms, but
            // `MappingWithoutName` has no `name_index` field — relies on Zig lazy analysis.
            // Return an empty slice for the without-names case.
            ListValue::WithoutNames(_list) => &[],
            ListValue::WithNames(list) => list.items_name_index(),
        }
    }

    // `deinit` dropped: all fields (`MultiArrayList`, `ByteList`, `Box<[SemverString]>`)
    // own their storage and free on Drop.

    pub fn get_name(&self, index: i32) -> Option<&[u8]> {
        if index < 0 {
            return None;
        }
        let i = usize::try_from(index).unwrap();

        if i >= self.names.len() {
            return None;
        }

        if matches!(self.r#impl, ListValue::WithNames(_)) {
            let str: &SemverString = &self.names[i];
            return Some(str.slice(self.names_buffer.slice()));
        }

        None
    }

    pub fn memory_cost(&self) -> usize {
        self.r#impl.memory_cost()
            + self.names_buffer.memory_cost()
            + (self.names.len() * size_of::<SemverString>())
    }

    pub fn ensure_total_capacity(&mut self, count: usize) -> Result<(), bun_alloc::AllocError> {
        self.r#impl.ensure_total_capacity(count)
    }
}

struct SortContext<'a> {
    generated: &'a [LineColumnOffset],
}

impl<'a> SortContext<'a> {
    pub fn less_than(&self, a_index: usize, b_index: usize) -> bool {
        let a = self.generated[a_index];
        let b = self.generated[b_index];

        if a.lines.zero_based() != b.lines.zero_based() {
            return a.lines.zero_based() < b.lines.zero_based();
        }
        if a.columns.zero_based() != b.columns.zero_based() {
            return a.columns.zero_based() < b.columns.zero_based();
        }
        a_index < b_index
    }
}

pub struct Lookup<'a> {
    pub mapping: Mapping,
    pub source_map: Option<&'a ParsedSourceMap>,
    /// Owned by default_allocator always
    /// use `get_source_code` to access this as a Slice
    // TODO(port): lifetime — comment says "owned by default_allocator"; ownership is
    // transferred into the returned ZigStringSlice in `get_source_code`.
    pub prefetched_source_code: Option<Box<[u8]>>,

    pub name: Option<&'a [u8]>,
}

impl<'a> Lookup<'a> {
    /// This creates a bun.String if the source remap *changes* the source url,
    /// which is only possible if the executed file differs from the source file:
    ///
    /// - `bun build --sourcemap`, it is another file on disk
    /// - `bun build --compile --sourcemap`, it is an embedded file.
    pub fn display_source_url_if_needed(&self, base_filename: &[u8]) -> Option<bun_str::String> {
        let source_map = self.source_map?;
        // See doc comment on `external_source_names`
        if source_map.external_source_names.len() == 0 {
            return None;
        }
        let source_idx = usize::try_from(self.mapping.source_index).ok()?;
        if source_idx >= source_map.external_source_names.len() {
            return None;
        }

        let name = &source_map.external_source_names[source_idx];

        if source_map.is_standalone_module_graph {
            return Some(bun_str::String::clone_utf8(name));
        }

        if bun_paths::is_absolute(base_filename) {
            let dir = bun_paths::dirname(base_filename, Platform::Auto);
            return Some(bun_str::String::clone_utf8(bun_paths::join_abs(
                dir,
                Platform::Auto,
                name,
            )));
        }

        Some(bun_str::String::init(name))
    }

    /// Only valid if `lookup.source_map.is_external()`
    /// This has the possibility of invoking a call to the filesystem.
    ///
    /// This data is freed after printed on the assumption that printing
    /// errors to the console are rare (this isnt used for error.stack)
    pub fn get_source_code(self, base_filename: &[u8]) -> Option<ZigStringSlice> {
        let bytes: Box<[u8]> = 'bytes: {
            if let Some(code) = self.prefetched_source_code {
                break 'bytes code;
            }

            let source_map = self.source_map?;
            debug_assert!(source_map.is_external());

            let Some(provider) = source_map.underlying_provider.provider() else {
                return None;
            };

            let index = usize::try_from(self.mapping.source_index).ok()?;

            // Standalone module graph source maps are stored (in memory) compressed.
            // They are decompressed on demand.
            if source_map.is_standalone_module_graph {
                let serialized = source_map.standalone_module_graph_data();
                if index >= source_map.external_source_names.len() {
                    return None;
                }

                let code = serialized.source_file_contents(index);

                return Some(ZigStringSlice::from_utf8_never_free(code?));
            }

            if let Some(parsed) = provider.get_source_map(
                base_filename,
                source_map.underlying_provider.load_hint,
                // TODO(port): `.{ .source_only = @intCast(index) }` — enum/union variant from
                // SourceProvider; exact Rust type TBD.
                crate::SourceContentHint::SourceOnly(index),
            ) {
                if let Some(contents) = parsed.source_contents {
                    break 'bytes contents;
                }
            }

            if index >= source_map.external_source_names.len() {
                return None;
            }

            let name = &source_map.external_source_names[index];

            let mut buf = PathBuffer::uninit();
            let normalized = bun_paths::join_abs_string_buf_z(
                bun_paths::dirname(base_filename, Platform::Auto),
                &mut buf,
                &[name],
                Platform::Loose,
            );
            match bun_sys::File::read_from(bun_sys::Fd::cwd(), normalized) {
                bun_sys::Result::Ok(r) => break 'bytes r,
                bun_sys::Result::Err(_) => return None,
            }
        };

        Some(ZigStringSlice::init(bytes))
    }
}

impl Mapping {
    #[inline]
    pub fn generated_line(&self) -> i32 {
        self.generated.lines.zero_based()
    }

    #[inline]
    pub fn generated_column(&self) -> i32 {
        self.generated.columns.zero_based()
    }

    #[inline]
    pub fn source_index(&self) -> i32 {
        self.source_index
    }

    #[inline]
    pub fn original_line(&self) -> i32 {
        self.original.lines.zero_based()
    }

    #[inline]
    pub fn original_column(&self) -> i32 {
        self.original.columns.zero_based()
    }

    #[inline]
    pub fn name_index(&self) -> i32 {
        self.name_index
    }
}

#[derive(Default, Clone, Copy)]
pub struct ParseOptions {
    pub allow_names: bool,
    pub sort: bool,
}

const HALF_USIZE: usize = size_of::<usize>() / 2;
const SEMICOLON_RUN: [u8; HALF_USIZE] = [b';'; HALF_USIZE];

pub fn parse(
    bytes: &[u8],
    estimated_mapping_count: Option<usize>,
    sources_count: i32,
    input_line_count: usize,
    options: ParseOptions,
) -> ParseResult {
    scoped_log!(SourceMap, "parse mappings ({} bytes)", bytes.len());

    let mut mapping = List::default();
    // `errdefer mapping.deinit(allocator)` deleted: `List: Drop` and this fn returns no error union.

    if let Some(count) = estimated_mapping_count {
        if mapping.ensure_total_capacity(count).is_err() {
            return ParseResult::Fail(ParseResultFail {
                msg: "Out of memory",
                err: err!("OutOfMemory"),
                loc: Loc::default(),
                ..Default::default()
            });
        }
    }

    let mut generated = LineColumnOffset { lines: Ordinal::START, columns: Ordinal::START };
    let mut original = LineColumnOffset { lines: Ordinal::START, columns: Ordinal::START };
    let mut name_index: i32 = 0;
    let mut source_index: i32 = 0;
    let mut needs_sort = false;
    let mut remain = bytes;
    let mut has_names = false;
    while remain.len() > 0 {
        if remain[0] == b';' {
            generated.columns = Ordinal::START;

            while remain.starts_with(&SEMICOLON_RUN) {
                generated.lines = generated.lines.add_scalar(HALF_USIZE as i32);
                remain = &remain[HALF_USIZE..];
            }

            while remain.len() > 0 && remain[0] == b';' {
                generated.lines = generated.lines.add_scalar(1);
                remain = &remain[1..];
            }

            if remain.len() == 0 {
                break;
            }
        }

        // Read the generated column
        let generated_column_delta = decode_vlq(remain, 0);

        if generated_column_delta.start == 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Missing generated column value",
                err: err!("MissingGeneratedColumnValue"),
                value: generated.columns.zero_based(),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }

        needs_sort = needs_sort || generated_column_delta.value < 0;

        generated.columns = generated.columns.add_scalar(generated_column_delta.value);
        if generated.columns.zero_based() < 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Invalid generated column value",
                err: err!("InvalidGeneratedColumnValue"),
                value: generated.columns.zero_based(),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }

        remain = &remain[generated_column_delta.start..];

        // According to the specification, it's valid for a mapping to have 1,
        // 4, or 5 variable-length fields. Having one field means there's no
        // original location information, which is pretty useless. Just ignore
        // those entries.
        if remain.len() == 0 {
            break;
        }

        match remain[0] {
            b',' => {
                remain = &remain[1..];
                continue;
            }
            b';' => {
                continue;
            }
            _ => {}
        }

        // Read the original source
        let source_index_delta = decode_vlq(remain, 0);
        if source_index_delta.start == 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Invalid source index delta",
                err: err!("InvalidSourceIndexDelta"),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
                ..Default::default()
            });
        }
        source_index += source_index_delta.value;

        if source_index < 0 || source_index >= sources_count {
            return ParseResult::Fail(ParseResultFail {
                msg: "Invalid source index value",
                err: err!("InvalidSourceIndexValue"),
                value: source_index,
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }
        remain = &remain[source_index_delta.start..];

        // Read the original line
        let original_line_delta = decode_vlq(remain, 0);
        if original_line_delta.start == 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Missing original line",
                err: err!("MissingOriginalLine"),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
                ..Default::default()
            });
        }

        original.lines = original.lines.add_scalar(original_line_delta.value);
        if original.lines.zero_based() < 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Invalid original line value",
                err: err!("InvalidOriginalLineValue"),
                value: original.lines.zero_based(),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }
        remain = &remain[original_line_delta.start..];

        // Read the original column
        let original_column_delta = decode_vlq(remain, 0);
        if original_column_delta.start == 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Missing original column value",
                err: err!("MissingOriginalColumnValue"),
                value: original.columns.zero_based(),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }

        original.columns = original.columns.add_scalar(original_column_delta.value);
        if original.columns.zero_based() < 0 {
            return ParseResult::Fail(ParseResultFail {
                msg: "Invalid original column value",
                err: err!("InvalidOriginalColumnValue"),
                value: original.columns.zero_based(),
                loc: Loc { start: i32::try_from(bytes.len() - remain.len()).unwrap() },
            });
        }
        remain = &remain[original_column_delta.start..];

        if remain.len() > 0 {
            match remain[0] {
                b',' => {
                    // 4 column, but there's more on this line.
                    remain = &remain[1..];
                }
                // 4 column, and there's no more on this line.
                b';' => {}

                // 5th column: the name
                c => {
                    // Read the name index
                    let name_index_delta = decode_vlq(remain, 0);
                    if name_index_delta.start == 0 {
                        return ParseResult::Fail(ParseResultFail {
                            msg: "Invalid name index delta",
                            err: err!("InvalidNameIndexDelta"),
                            value: i32::from(c),
                            loc: Loc {
                                start: i32::try_from(bytes.len() - remain.len()).unwrap(),
                            },
                        });
                    }
                    remain = &remain[name_index_delta.start..];

                    if options.allow_names {
                        name_index += name_index_delta.value;
                        if !has_names {
                            if mapping.ensure_with_names().is_err() {
                                return ParseResult::Fail(ParseResultFail {
                                    msg: "Out of memory",
                                    err: err!("OutOfMemory"),
                                    loc: Loc {
                                        start: i32::try_from(bytes.len() - remain.len()).unwrap(),
                                    },
                                    ..Default::default()
                                });
                            }
                        }
                        has_names = true;
                    }

                    if remain.len() > 0 {
                        match remain[0] {
                            // There's more on this line.
                            b',' => {
                                remain = &remain[1..];
                            }
                            // That's the end of the line.
                            b';' => {}
                            _ => {}
                        }
                    }
                }
            }
        }
        // `catch |err| bun.handleOom(err)` → panic on OOM; do not silently drop the mapping.
        mapping
            .append(&Mapping {
                generated,
                original,
                source_index,
                name_index,
            })
            .expect("OOM");
    }

    if needs_sort && options.sort {
        mapping.sort();
    }

    ParseResult::Success(ParsedSourceMap {
        // TODO(port): `ref_count: .init()` — ParsedSourceMap uses intrusive refcounting;
        // exact init depends on bun_ptr::IntrusiveRc shape in Phase B.
        ref_count: Default::default(),
        mappings: mapping,
        input_line_count,
        ..Default::default()
    })
}

// ──────────────────────────────────────────────────────────────────────────
// PORT STATUS
//   source:     src/sourcemap/Mapping.zig (605 lines)
//   confidence: medium
//   todos:      6
//   notes:      MultiArrayList SoA column accessor API is assumed; ParseResult/ParsedSourceMap/Loc field shapes from sibling files; List::sort has a borrowck hazard (column slice vs &mut self).
// ──────────────────────────────────────────────────────────────────────────
