[package]
name = "bun_sema_standalone"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[[bin]]
name = "bun-sema"
path = "main.rs"

[dependencies]
bun_sema.workspace = true
bun_sema_driver.workspace = true
bun_js_parser.workspace = true
bun_threading.workspace = true
bun_alloc.workspace = true
bun_paths.workspace = true
libc.workspace = true

[lints]
