// Research scratch (rules-code-path): the own case lists of the four rules and ESLint's answers.
// usage: node cases/make.cjs   writes cases/{edge,ts}-<rule>.json and answers/{edge,ts}-<rule>.jsonl
// The lists are in the form that ../round2-oracle/proto-1b/regen.cjs reads beside it (cases/*-<rule>.json).
"use strict";
const fs = require("fs");
const path = require("path");
const { verify } = require("../../round2-oracle/proto-1b/eslint-side.cjs");
const S = body => `switch (x) { ${body} }`;
const C = (body, heritage = "B") => `class A extends ${heritage} { constructor() { ${body} } }`;
const lists = {
	"edge-no-fallthrough": [
		// The comment that permits it: the last one before the next clause, or the last one before the `}` of a lone block.
		S("case 1: a(); /* falls through */ case 2: b(); }").slice(0, -2),
		S("case 1: a(); // falls through\n case 2: b();"),
		S("case 1: a(); // fall through\n case 2: b();"),
		S("case 1: a(); // fallthrough\n case 2: b();"),
		S("case 1: a(); // FALLS-THROUGH\n case 2: b();"),
		S("case 1: a(); // Falls Through\n case 2: b();"),
		S("case 1: a(); // falls\tthrough\n case 2: b();"),
		S("case 1: a(); /* falls\nthrough */ case 2: b();"),
		S("case 1: a(); /* falls  through */ case 2: b();"),
		S("case 1: a(); /* this falls through to the next */ case 2: b();"),
		S("case 1: a(); /* fall\u017f through */ case 2: b();"),
		S("case 1: a(); /* falls\u00a0through */ case 2: b();"),
		S("case 1: a(); /* falls\u2028through */ case 2: b();"),
		S("case 1: a(); /* falls through */ /* other */ case 2: b();"),
		S("case 1: a(); /* other */ /* falls through */ case 2: b();"),
		S("case 1: a(); // falls through\n // other\n case 2: b();"),
		S("case 1: a() /* falls through */; case 2: b();"),
		S("case 1: /* falls through */ a(); case 2: b();"),
		S("case 1: a(); case /* falls through */ 2: b();"),
		S("case 1: a(); // eslint-disable-line falls through\n case 2: b();"),
		S("case 1: a(); // eslint-disable-next-line falls through\n case 2: b();"),
		S("case 1: a(); /* eslint-enable falls through */ case 2: b();"),
		S("case 1: a(); /* eslint-env falls through */ case 2: b();"),
		S("case 1: a(); /* eslint falls through */ case 2: b();"),
		S("case 1: a(); /* global falls through */ case 2: b();"),
		S("case 1: a(); /* globals falls through */ case 2: b();"),
		S("case 1: a(); /* exported falls through */ case 2: b();"),
		S("case 1: a(); /*   exported\nfalls through */ case 2: b();"),
		S("case 1: a(); /* eslintfalls through */ case 2: b();"),
		S("case 1: a(); /* globalize: falls through */ case 2: b();"),
		S("case 1: a(); /* eslint-disabled falls through */ case 2: b();"),
		S("case 1: { a(); /* falls through */ } case 2: b();"),
		S("case 1: { a(); // falls through\n } case 2: b();"),
		S("case 1: { /* falls through */ } case 2: b();"),
		S("case 1: { /* falls through */ a(); } case 2: b();"),
		S("case 1: { a(); } /* falls through */ case 2: b();"),
		S("case 1: { a(); /* other */ } /* falls through */ case 2: b();"),
		S("case 1: { a(); /* falls through */ } /* other */ case 2: b();"),
		S("case 1: { a(); /* falls through */ /* other */ } case 2: b();"),
		S("case 1: { a(); } { /* falls through */ } case 2: b();"),
		S("case 1: a(); { /* falls through */ } case 2: b();"),
		S("case 1: { { /* falls through */ } } case 2: b();"),
		S("case 1: if (a) { /* falls through */ } case 2: b();"),
		S("case 1: L: { /* falls through */ } case 2: b();"),
		S("case 1: {} case 2: b();"),
		S("case 1: ; case 2: b();"),
		S("case 1: a = '// falls through'; case 2: b();"),
		S("case 1: a = `// falls through`; case 2: b();"),
		S("case 1: a = `${b}// falls through\n`; case 2: b();"),
		S("case 1: a = /\\/\\/ falls through/; case 2: b();"),
		S("case 1: a = b / 2 // falls through\n ; case 2: b();"),
		S("case 1: a = b / 2 / c; // falls through\n case 2: b();"),
		S("case 1: a = /re/ // falls through\n case 2: b();"),
		// Where the report is, and which word it names.
		S("case 1: a();\n\n   case 2: b();"),
		S("case 1: a(); default: b();"),
		S("case 1: a(); /* c */ default: b();"),
		S("default: a(); case 1: b();"),
		S("case 1: a(); case (2): b();"),
		S("case 1: a(); case ((2)): b();"),
		S("case 1: a(); case\n 2: b();"),
		S("case 1: a(); case /* c */ 2: b();"),
		S("case a.default: a(); default: b();"),
		S("case 1: a.default(); default: b();"),
		S("case 1: a = b ? c.default : d; default: b();"),
		S("case 1: a = { default: 1 }; default: b();"),
		S("case 1: switch (y) { default: a(); } default: b();"),
		S("case 1: (function () { switch (y) { default: a(); } })(); default: b();"),
		S("case 1: (a).default; default: b();"),
		S("case 1: a?.default; default: b();"),
		S("case 1: class K { default() {} } default: b();"),
		S("case 1: a(); case 2: b(); case 3: c(); default: d();"),
		// An empty clause: lines between its `:` and the next clause.
		S("case 1: case 2: b();"),
		S("case 1:\n case 2: b();"),
		S("case 1:\n\n case 2: b();"),
		S("case 1:\r\n\r\n case 2: b();"),
		S("case 1:\r\r case 2: b();"),
		S("case 1:\u2028\u2028 case 2: b();"),
		S("case 1: // c\n\n case 2: b();"),
		S("case 1:\n // c\n case 2: b();"),
		S("case 1:\n // falls through\n case 2: b();"),
		S("case 1: /* a\n b\n c */ case 2: b();"),
		S("case 1\n\n:\n case 2: b();"),
		S("case (1\n\n):\n case 2: b();"),
		S("case (1):\n\n case 2: b();"),
		S("case a ? b : c:\n\n case 2: b();"),
		S("case { a: 1 }.a:\n\n case 2: b();"),
		S("default:\n\n case 2: b();"),
		S("default\n\n:\n case 2: b();"),
		S("case 1:\n\n default: b();"),
		S("case 1:\n\n"),
		S("case 1: case 2:\n\n case 3: a();"),
		// Whether the end of the clause is reached.
		S("case 1: a(); break; case 2: b();"),
		S("case 1: return; case 2: b();").replace(/^/, "function f() { ") + " }",
		S("case 1: throw a; case 2: b();"),
		S("case 1: if (a) break; case 2: b();"),
		S("case 1: if (a) break; else break; case 2: b();"),
		S("case 1: if (a) { break; } else { throw b; } case 2: b();"),
		S("case 1: while (true) {} case 2: b();"),
		S("case 1: while (a) { break; } case 2: b();"),
		S("case 1: for (;;) {} case 2: b();"),
		S("case 1: for (;;) { break; } case 2: b();"),
		S("case 1: do { break; } while (a); case 2: b();"),
		S("case 1: try { break; } finally { } case 2: b();"),
		S("case 1: try { a(); } finally { break; } case 2: b();"),
		S("case 1: try { throw a; } catch (e) { break; } case 2: b();"),
		S("case 1: try { a(); } catch (e) { break; } case 2: b();"),
		S("case 1: { break; } case 2: b();"),
		S("case 1: { a(); break; b(); } case 2: b();"),
		S("case 1: break; a(); case 2: b();"),
		S("case 1: switch (y) { case 1: break; } case 2: b();"),
		S("case 1: switch (y) { default: return; } case 2: b();").replace(/^/, "function f() { ") + " }",
		`L: ${S("case 1: break L; case 2: b();")}`,
		`L: while (a) ${S("case 1: continue L; case 2: b();")}`,
		`while (a) ${S("case 1: continue; case 2: b();")}`,
		S("case 1: L: break L; case 2: b();"),
		S("case 1: function g() { return; } case 2: b();"),
		S("case 1: class K {} case 2: b();"),
		S("case 1: var v; case 2: b();"),
		S("case 1: a && b(); case 2: b();"),
		S("case 1: process.exit(); case 2: b();"),
		S("case 1: debugger; case 2: b();"),
		S("case 1: 'use strict'; case 2: b();"),
		S("case 1: a(); case 2: b(); break; case 3: c(); default: d(); break; case 4: e();"),
		S("case 1: a(); default: d(); case 2: e();"),
		S("default: case 1: a();"),
		S(""),
		S("case 1: a();"),
		S("default: a();"),
		`function f() { ${S("case 1: return 1; case 2: return 2; default: a(); case 3: b(); }")} `,
		`switch (x) { case 1: a(); /* falls through */ case 2: switch (y) { case 3: b(); case 4: c(); } default: d(); }`,
		`foo: ${S("case 1: { break foo; } case 2: a();")}`,
		`switch (x) { case 1: a()\n// falls through\ncase 2: b() }`,
		`switch (x) { case 1: a() <!-- falls through\n case 2: b() }`,
		`switch (x) { case 1: a()\n--> falls through\n case 2: b() }`,
	],
	"ts-no-fallthrough": [
		S("case 1: type T = number; case 2: break;"),
		S("case 1: interface I {} case 2: break;"),
		S("case 1: declare const y: number; case 2: break;"),
		S("case 1: enum E { A } case 2: break;"),
		S("case 1: namespace N { } case 2: break;"),
		S("case 1: namespace N { export const a = 1 } case 2: break;"),
		S("case 1: declare function f(): void; case 2: break;"),
		S("case 1: function f(): void; function f() {} case 2: break;"),
		S("case 1: abstract class K {} case 2: break;"),
		S("case 1 as number: a(); case (2)!: break;"),
		S("case 1: a() as any; /* falls through */ case 2: break;"),
		S("case 1: a()!; case <number>2: break;"),
		S("case 1: a<string>(); default: break;"),
		S("case 1: a = b as typeof c.default; default: break;"),
		S("case 1: let v: { default: number }; default: break;"),
		S("case 1: let v: import('m').default; default: break;"),
		S("case 1 as number:\n\n case 2: break;"),
		S("case (1 as number):\n\n case 2: break;"),
		S("case x satisfies { a: 1 } ? 1 : 2:\n\n case 2: break;"),
		S("case 1: { type T = 1; /* falls through */ } case 2: break;"),
		S("case 1: type T = 1; // falls through\n case 2: break;"),
		S("case E.A: return 1; case E.B: a(); case E.C: break;").replace(/^/, "enum E { A, B, C } function f(x: E) { ") + " }",
		`function f(x: never): never { ${S("case 1: assertNever(x); case 2: break;")} }`,
		`function f(x: number) { ${S("case 1: throw new Error() as never; case 2: break;")} }`,
	],
	"edge-constructor-super": [
		C(""), C("super();"), C("super(); super();"), C("return;"), C("return a;"), C("if (a) super();"), C("if (a) super(); else super();"),
		C("a && super();"), C("a || super();"), C("a ?? super();"), C("a ? super() : super();"), C("a ? super() : 0;"),
		C("while (a) super();"), C("do { super(); } while (a);"), C("for (;;) super();"), C("for (;; super()) {}"), C("for (super();;) {}"), C("for (; super();) {}"),
		C("for (var k in super()) {}"), C("for (var k of a) super();"), C("for (k in a) { super(); break; }"),
		C("try { super(); } catch (e) { }"), C("try { super(); } catch (e) { super(); }"), C("try { a(); } finally { super(); }"), C("try { super(); } finally { a(); }"),
		C("try { return; } finally { super(); }"), C("try { throw a; } catch { super(); }"),
		C("switch (a) { case 1: super(); break; default: super(); }"), C("switch (a) { case 1: super(); default: super(); }"), C("switch (a) { default: super(); case 1: break; }"),
		C("switch (a) { case 1: super(); }"), C("switch (a) { default: break; case 1: super(); }"),
		C("L: { super(); break L; }"), C("L: { if (a) break L; super(); }"),
		C("throw a;"), C("if (a) throw b; super();"), C("if (a) return b; super();"), C("if (a) return; super();"),
		C("(() => super())();"), C("var f = () => { super(); };"), C("function g() { } super();"), C("class K extends B { constructor() { super(); } }"),
		C("class K extends B { constructor() { } } super();"), C("var o = { m() { super.x; } }; super();"),
		C("super(); return;"), C("super(); return a;"), C("return a; super();"), C("super(); throw a;"),
		C("super()", "null"), C("", "null"), C("return a;", "null"), C("super();", "undefined"), C("super();", "void 0"),
		C("super();", "(B)"), C("super();", "B.C"), C("super();", "B()"), C("super();", "new B"), C("super();", "class {}"), C("super();", "function () {}"),
		C("super();", "(() => {})"), C("super();", "'s'"), C("super();", "1"), C("super();", "1n"), C("super();", "true"), C("super();", "/r/"), C("super();", "`t`"), C("super();", "tag`t`"),
		C("super();", "(a && b)"), C("super();", "(a && 1)"), C("super();", "(1 && b)"), C("super();", "(a || 1)"), C("super();", "(1 || 2)"), C("super();", "(a ?? 1)"), C("super();", "(1 ?? 2)"),
		C("super();", "(a ? b : 1)"), C("super();", "(a ? 1 : b)"), C("super();", "(a ? 1 : 2)"), C("super();", "(a, 1)"), C("super();", "(1, a)"), C("super();", "(1, 2, a)"), C("super();", "(a, (b, 1))"),
		C("super();", "(a = b)"), C("super();", "(a = 1)"), C("super();", "(a &&= b)"), C("super();", "(a &&= 1)"), C("super();", "(a ||= 1)"), C("super();", "(a ??= 1)"), C("super();", "(1 ??= 2)".replace("1 ??=", "a ??=")),
		C("super();", "(a += b)"), C("super();", "(a -= b)"), C("super();", "(a **= b)"), C("super();", "(a >>>= b)"),
		C("super();", "this"), C("super();", "a?.b"), C("super();", "(a?.b)"), C("super();", "a?.()"), C("super();", "a[b]"), C("super();", "a.#b".replace("a.#b", "a.b")),
		C("super();", "(-a)"), C("super();", "(!a)"), C("super();", "(typeof a)"), C("super();", "(a + b)"), C("super();", "(a++)"), C("super();", "[]"), C("super();", "({})"),
		C("super();", "(async function () {})"), C("super();", "(function* () {})"), C("super();", "(async () => {})"),
		"function* g() { class A extends (yield) { constructor() { super(); } } }",
		"async function g() { class A extends (await a) { constructor() { super(); } } }",
		"function g() { class A extends new.target { constructor() { super(); } } }",
		"class A extends import.meta { constructor() { super(); } }",
		"class A extends import('m') { constructor() { super(); } }",
		"class A extends B { 'constructor'() { } }",
		"class A extends B { \"constructor\"() { super(); } }",
		"class A extends B { ['constructor']() { } }",
		"class A extends B { static constructor() { } }",
		"class A extends B { constructor\n() { } }",
		"class A extends B { /* c */ constructor /* d */ () { } }",
		"class A extends B { m() {} ; constructor() { } ; n() {} }",
		"(class extends B { constructor() { } })",
		"(class A extends B { constructor() { } })",
		"export default class extends B { constructor() { } }",
		"export class A extends B { constructor() { } }",
		"class A { constructor() { } }",
		"class A { constructor() { class K extends B { constructor() { } } } }",
		"class A extends B { constructor(a = super()) { } }",
		"class A extends B { constructor(a = super()) { super(); } }",
		"class A extends B { constructor(a = b ? super() : 0) { } }",
		"class A extends B { constructor({ a = super() }) { } }",
		"class A extends B { constructor([a = super()] = []) { } }",
		"class A extends B { constructor() { var a = [super()]; } }",
		"class A extends B { constructor() { var a = { [super()]: 1 }; } }",
		"class A extends B { constructor() { var a = { b: super() }; } }",
		"class A extends B { constructor() { `${super()}`; } }",
		"class A extends B { constructor() { foo(super()); } }",
		"class A extends B { constructor() { new (super())(); } }",
		"class A extends B { constructor() { super().a; } }",
		"class A extends B { constructor() { super()?.a; } }",
		"class A extends B { constructor() { a?.[super()]; } }",
		"class A extends B { constructor() { a?.b(super()); } }",
		"class A extends B { constructor() { a = super(); } }",
		"class A extends B { constructor() { a ||= super(); } }",
		"class A extends B { constructor() { a &&= super(); } }",
		"class A extends B { constructor() { a ??= super(); } }",
		"class A extends B { constructor() { [a = super()] = b; } }",
		"class A extends B { constructor() { ({ a = super() } = b); } }",
		"class A extends B { constructor() { class K { [super()]() {} } } }",
		"class A extends B { constructor() { class K extends super() { } } }",
		"class A extends B { constructor() { (super(), super()); } }",
		"class A extends B { constructor() { super(super()); } }",
		"class A extends B { constructor() { !super(); } }",
		"class A extends B { constructor() { if (super()) { } } }",
		"class A extends B { constructor() { while (super()) { } } }",
		"class A extends B { constructor() { do { } while (super()); } }",
		"class A extends B { constructor() { for (;;) { super(); break; } } }",
		"class A extends B { constructor() { for (;;) { if (a) { super(); break; } } } }",
		"class A extends B { constructor() { for (var i = 0; i < n; i++) { } super(); } }",
		"class A extends B { constructor() { for (var i = 0; i < n; i++) { if (a) continue; } super(); } }",
		"class A extends B { constructor() { super(); for (var i = 0; i < n; i++) { a(); } } }",
		"class A extends B { constructor() { while (a) { if (b) { super(); return; } } } }",
		"class A extends B { constructor() { while (a) { super(); } super(); } }",
		"class A extends B { constructor() { L: while (a) { while (b) { super(); continue L; } } } }",
		"class A extends B { constructor() { switch (a) { case 1: super(); break; case 2: super(); break; } } }",
		"class A extends B { constructor() { switch (a) { case 1: super(); case 2: break; default: super(); } } }",
		"class A extends B { constructor() { switch (a) { default: case 1: super(); } } }",
		"class A extends B { constructor() { switch (a) { case 1: default: break; case 2: super(); } } }",
		"class A extends B { constructor() { try { a(); } catch (e) { return; } super(); } }",
		"class A extends B { constructor() { try { a(); super(); } catch (e) { super(); } } }",
		"class A extends B { constructor() { try { super(); a(); } catch (e) { super(); } } }",
		"class A extends B { constructor() { try { if (a) return; } finally { super(); } } }",
		"class A extends B { constructor() { try { super(); } finally { if (a) return; } } }",
		"class A extends B { constructor() { with (a) { super(); } } }",
	],
	"ts-constructor-super": [
		"class A extends (B as any) { constructor() { super(); } }",
		"class A extends B! { constructor() { super(); } }",
		"class A extends (<any>B) { constructor() { super(); } }",
		"class A extends (B satisfies C) { constructor() { super(); } }",
		"class A extends B<T> { constructor() { super(); } }",
		"class A extends (B<T>) { constructor() { super(); } }",
		"class A extends B.C<T> { constructor() { super(); } }",
		"class A extends mixin(B)<T> { constructor() { super(); } }",
		"class A extends (B as any) { constructor() { } }",
		"class A extends (null as any) { constructor() { super(); } }",
		"class A extends (null as any) { constructor() { } }",
		"class A extends (a || B as any) { constructor() { super(); } }",
		"class A extends ((a as any) || B) { constructor() { super(); } }",
		"class A extends ((a as any) && (B as any)) { constructor() { super(); } }",
		"class A extends (a ? (B as any) : 1) { constructor() { super(); } }",
		"class A extends (a, B as any) { constructor() { super(); } }",
		"class A extends (x = B as any) { constructor() { super(); } }",
		"class A extends B { public constructor() { } }",
		"class A extends B { private   constructor() { } }",
		"class A extends B { protected constructor() { super(); } }",
		"class A extends B { constructor(); constructor(a?: any) { } }",
		"class A extends B { constructor(a: string); constructor(a: number); constructor(a: any) { super(); } }",
		"class A extends B { constructor(private a: string) { } }",
		"class A extends B { constructor(private a: string) { super(); } }",
		"class A extends B { constructor() { super() as any; } }",
		"class A extends B { constructor() { super()!; } }",
		"class A extends B { constructor() { (<any>super()); } }",
		"class A extends B { constructor() { return x as any; } }",
		"class A extends B { constructor() { return x!; } }",
		"class A extends B { constructor() { if (a) super(); else return <any>x; } }",
		"class A extends B { constructor() { for (;; (a && super()) as any) { if (b) break; } } }",
		"class A extends B { constructor() { for (;; (a ? super() : 0)!) { if (b) break; } } }",
		"class A extends B implements I { constructor() { } }",
		"class A implements I { constructor() { } }",
		"abstract class A extends B { constructor() { super(); } abstract m(): void; }",
		"abstract class A extends B { constructor() { } }",
		"declare class A extends B { constructor(); }",
		"declare namespace N { class A extends B { constructor(); } }",
		"namespace N { export class A extends B { constructor() { } } }",
		"class A extends B { constructor() { enum E { X = 1 } super(); } }",
		"class A extends B { constructor() { type T = number; } }",
		"class A extends B { constructor() { let f = function (this: A) { }; super(); } }",
		"class A<T> extends B<T> { constructor() { super(); } }",
		"class A extends B { @dec m() {} constructor() { } }",
		"class A extends B { declare x: number; constructor() { } }",
		"class A extends B { x!: number; constructor() { super(); this.x = 1; } }",
		"class A extends B { constructor(a = super() as any) { } }",
		"class A extends B { constructor() { try { super(); } catch (e: unknown) { } } }",
	],
	"edge-no-this-before-super": [
		C("this.a = 0; super();"), C("this.a(); super();"), C("super.a(); super();"), C("super(this.a);"), C("super(this);"), C("super(super.a);"), C("super(() => this);"),
		C("super(); this.a = 0;"), C("super(); super.a();"), C("this;"), C("this.a;"), C("super.a;"), C("super[a];"), C("super.a.b.c;"), C("super.a();"), C("super[a]();"), C("super.a`t`;"),
		C("if (a) super(); this.a;"), C("if (a) super(); else super(); this.a;"), C("if (a) { super(); this.a; } this.b;"), C("a && super(); this.a;"), C("a ? super() : super(); this.a;"), C("a ? super() : 0; this.a;"),
		C("super() || this.a;"), C("super() && this.a;"), C("this.a || super();"), C("(super(), this.a);"), C("(this.a, super());"), C("foo(this, super());"), C("foo(super(), this);"),
		C("[this, super()];"), C("[super(), this];"), C("({ a: this, b: super() });"), C("({ a: super(), b: this });"), C("({ [this]: super() });"), C("`${this}${super()}`;"), C("`${super()}${this}`;"),
		C("this.a = super();"), C("this[super()];"), C("this[super()] = this;"), C("super()[this];"), C("new this(super());"), C("new (super())(this);"), C("a = this, super();"),
		C("while (a) { this.a; super(); }"), C("while (a) { super(); this.a; }"), C("while (a) { super(); } this.a;"), C("super(); while (a) { this.a; }"), C("do { this.a; } while (super());"), C("do { super(); } while (this.a);"),
		C("for (this.a;;) { super(); }"), C("for (;this.a;) { super(); }"), C("for (;;this.a) { super(); break; }"), C("for (super();;this.a) { }"), C("for (;;super()) { this.a; if (b) break; }"), C("for (var i = 0; i < n; i++) { if (a) { super(); } this.a; }"),
		C("for (var k in this) { super(); }"), C("for (var k of this.a) { super(); }"), C("for (this.k in a) { super(); }"), C("for (this.k of super()) { }"), C("for (var k in super()) { this.a; }"),
		C("try { this.a; super(); } catch (e) { }"), C("try { super(); } catch (e) { this.a; }"), C("try { super(); } finally { this.a; }"), C("try { a(); } finally { this.a; } super();"), C("try { super(); this.a; } catch (e) { this.b; } finally { this.c; }"),
		C("try { if (a) return; super(); } finally { this.a; }"), C("try { super(); } catch { super(); } this.a;"), C("try { throw a; } catch { super(); } this.a;"),
		C("switch (a) { case 1: super(); break; case 2: this.a; }"), C("switch (a) { case 1: super(); case 2: this.a; }"), C("switch (a) { case this.a: super(); }"), C("switch (this.a) { case 1: super(); }"),
		C("switch (a) { default: this.a; case 1: super(); }"), C("switch (a) { case 1: super(); default: this.a; case 2: this.b; }"), C("switch (super()) { case this.a: }"),
		C("L: { if (a) break L; super(); } this.a;"), C("L: { super(); break L; } this.a;"), C("if (a) return; this.a; super();"), C("if (a) throw this.a; super();"), C("return this;"), C("return this.a;"), C("throw this;"),
		C("var f = () => this; super();"), C("var f = () => super.a; super();"), C("var f = function () { this.a; }; super();"), C("function g() { this.a; } super();"),
		C("class K { m() { this.a; } } super();"), C("class K { x = this.a; } super();"), C("class K { static { this.a; } } super();"), C("class K { [this.a]() {} } super();"), C("class K extends this.a {} super();"),
		C("class K extends B { constructor() { this.a; super(); } } super();"), C("var o = { m() { this.a; super.b; } }; super();"), C("var o = { [this.a]: 1, get g() { return this; } }; super();"),
		C("this.a;", "null"), C("this.a;", "undefined"), C("this.a;", "void 0"), C("this.a;", "(null)"), C("this.a;", "(a, null)"), C("this.a;", "(void a)"), C("this.a; super();", "0"), C("this.a; super();", "B.C"), C("super.a;", "null"),
		"class A { constructor() { this.a; } }",
		"class A { constructor() { this.a; super.b; } }",
		"class A extends B { m() { this.a; super.b; } }",
		"class A extends B { x = this.a; y = super.b; constructor() { super(); } }",
		"class A extends B { static { this.a; super.b; } constructor() { super(); } }",
		"class A extends B { constructor(a = this.a) { super(); } }",
		"class A extends B { constructor(a = super.b) { super(); } }",
		"class A extends B { constructor(a = super(), b = this.a) { } }",
		"class A extends B { constructor(a = this.a, b = super()) { } }",
		"class A extends B { constructor({ a = this }, [b = super.c]) { super(); } }",
		"class A extends B { constructor(...[a = this]) { super(); } }",
		"class A extends B { 'constructor'() { this.a; super(); } }",
		"class A extends B { ['constructor']() { this.a; super(); } }",
		"class A extends B { static constructor() { this.a; } }",
		"(class extends B { constructor() { this.a; super(); } })",
		"export default class extends B { constructor() { this.a; super(); } }",
		"class A extends B { constructor() { this\n.a; super(); } }",
		"class A extends B { constructor() { (this).a; ((super.b)); super(); } }",
		"class A extends B { constructor() { this?.a; this?.(); super(); } }",
		"class A extends B { constructor() { typeof this; void this; delete this.a; !this; -this; super(); } }",
		"class A extends B { constructor() { this.a++; --this.b; this.c += 1; this.d ??= 2; super(); } }",
		"class A extends B { constructor() { a = { ...this }; b = [...this]; foo(...this); super(); } }",
		"class A extends B { constructor() { this.a`t`; super(); } }",
		"class A extends B { constructor() { a in this; this instanceof B; #p in this; super(); } #p; }",
		"class A extends B { constructor() { ({ a: this.a } = b); [this.c] = d; super(); } }",
		"class A extends B { constructor() { for ({ a: this.a } of b) { } super(); } }",
		"function* g() { class A extends B { constructor() { this.a; super(); } } }",
		"class A extends B { constructor() { super(); } } class C extends D { constructor() { this.a; super(); } }",
	],
	"ts-no-this-before-super": [
		"class A extends B { constructor() { (this as any).x; super(); } }",
		"class A extends B { constructor() { this!.x; super(); } }",
		"class A extends B { constructor() { (<any>this).x; super(); } }",
		"class A extends B { constructor() { (this satisfies A).x; super(); } }",
		"class A extends B { constructor() { foo(this as any, super.x!); super(); } }",
		"class A extends B { constructor() { super() as any; this.x; } }",
		"class A extends B { constructor() { super()!; this.x; } }",
		"class A extends B { constructor() { (super() as any) || this.x; } }",
		"class A extends B { constructor(); constructor(a?: number) { this.x; super(); } }",
		"class A extends B { constructor(private x: number) { this.x; super(); } }",
		"class A extends B { constructor(private x: number) { super(); this.x; } }",
		"class A extends B { constructor(x: typeof this) { super(); } }",
		"class A extends B { constructor(x: typeof this.y) { super(); } }",
		"class A extends B { constructor() { let x: typeof this; super(); } }",
		"class A extends B { constructor() { let x: this; super(); } }",
		"class A extends B { constructor() { let x = y as this; super(); } }",
		"class A extends B { constructor() { let x = <this>y; super(); } }",
		"class A extends B { constructor() { let f = (a: this) => a; super(); } }",
		"class A extends B { constructor(x = this) { super(); } }",
		"class A extends B { m(this: A) {} constructor() { let f = function (this: A) { this.x; }; super(); } }",
		"class A extends (null as any) { constructor() { this.x; } }",
		"class A extends (undefined!) { constructor() { this.x; } }",
		"class A extends (<any>void 0) { constructor() { this.x; } }",
		"class A extends (B as any) { constructor() { this.x; super(); } }",
		"class A extends B<T> { constructor() { this.x; super(); } }",
		"class A extends B { x: number = this.y; constructor() { super(); } }",
		"class A extends B { declare x: number; constructor() { this.x; super(); } }",
		"class A extends B { constructor() { enum E { X = this.x } super(); } }",
		"class A extends B { constructor() { namespace N { export const a = 1; } super(); this.x; } }",
		"class A extends B { constructor() { this.x = <T,>(a: T) => a; super(); } }",
		"class A extends B { constructor() { for (const k of this.list as any[]) { } super(); } }",
		"abstract class A extends B { constructor() { this.x; super(); } abstract m(): void; }",
		"class A extends B implements I { constructor() { this.x; super(); } }",
		"class A extends B { @dec(this) m() {} constructor() { super(); } }",
		"class A extends B { constructor(@dec(this) a: any) { super(); } }",
	],
};
const tsx = ["class A extends B { constructor() { <this.Foo>{this.x}</this.Foo>; super(); } }", "class A extends B { constructor() { <this />; super(); } }", "class A extends B { constructor() { <div a={this.a} {...this.b}>{super.c}</div>; super(); } }"];
fs.mkdirSync(path.join(__dirname, "../answers"), { recursive: true });
for (const [name, list] of Object.entries(lists)) {
	const rule = name.replace(/^(edge|ts)-/u, "");
	const ts = name.startsWith("ts-");
	const cases = list.map(code => (ts ? { code, ext: "ts" } : code));
	if (name === "ts-no-this-before-super") for (const code of tsx) cases.push({ code, ext: "tsx" });
	if (name === "edge-no-this-before-super") for (const code of tsx) cases.push({ code, ext: "jsx" });
	fs.writeFileSync(path.join(__dirname, `${name}.json`), "[\n" + cases.map(c => JSON.stringify(c)).join(",\n") + "\n]\n");
	const lines = [];
	let fatal = 0, reports = 0;
	for (const c of cases) {
		const code = typeof c === "string" ? c : c.code;
		const ext = typeof c === "string" ? "js" : c.ext;
		const r = verify(code, ext, [rule]);
		if (r.fatal) { fatal++; lines.push(JSON.stringify({ code, ext: r.ext, fatal: r.fatal.message })); continue; }
		reports += r.messages.length;
		lines.push(JSON.stringify({ code, ext: r.ext, eslint: r.messages.map(m => ({ line: m.line, column: m.column, message: m.message })) }));
	}
	fs.writeFileSync(path.join(__dirname, "../answers", `${name}.jsonl`), lines.join("\n") + "\n");
	console.log(`${name}: ${cases.length} cases, ${fatal} that the parser rejects, ${reports} reports`);
}
