// What is assigned to.
a[i] = 1;
a[i] += 1;
a[i]++;
--a[i];
delete a[i];
[a[i]] = [0];
[...a[i]] = [0];
[a[i] = 1] = [0];
[[a[i]]] = [[0]];
({ foo: a[i] } = { foo: 0 });
({ foo: a[i] }) = { foo: 0 };
({ foo: [a[i]] } = { foo: [0] });
({ foo: { bar: a[i] } }) = { foo: 0 };
({ ...a[i] } = {});
({ ...a[i] });
[...a[i]];
[(a[i])] = [0];
[([a[i]])] = [0];
(a[i] as number)++;
(<number>a[i])++;
(a[i] satisfies number)++;
[...a[i]!] = [0];
a[i]! = 1;
for (a[i] of b);
for (a[i] in b);
for ([a[i]] of b);
for ({ x: a[i] } of b);
for (a[i] = 0; ; );
x = { y = 1 };
({ y = a[i] } = {});
