const fs = require("fs");
const cases = [
  ["coded-semicolon", "let x 1;"],
  ["coded-expression", "let x = ;"],
  ["coded-statement", "}"],
  ["coded-identifier", "let = 1; var 1;"],
  ["coded-reserved", "var class;"],
  ["coded-string", "x;\nlet s = \"abc\nlet t;"],
  ["coded-template", "x;\nlet s = `abc"],
  ["coded-comment", "x; /* abc"],
  ["coded-type", "let x: ;"],
  ["coded-paren", "f(1;"],
  ["coded-brace", "function f() {"],
  ["coded-arrow", "let f = (a): => a;"],
  ["coded-union-fn", "let x = y as A | () => void;"],
  ["coded-member", "let x = y as { a A };"],
  ["coded-two", "declare function f(: void;"],
  ["first-string", "\"abc"],
  ["first-template", "`abc"],
  ["first-comment", "/* abc"],
  ["first-char", "\\"],
  ["first-number", "1__0;"],
  ["first-hash", "#"],
  ["first-at", "@"],
  ["first-regex", "/abc"],
  ["first-close", ")"],
  ["lexer-number-sep", "x; let a = 1__0;"],
  ["lexer-number-bin", "x; let a = 0b12;"],
  ["lexer-number-ident", "x; let a = 3in [];"],
  ["lexer-escape", "x; let a = \"\\u{110000}\";"],
  ["lexer-escape-x", "x; let a = \"\\xZZ\";"],
  ["lexer-ident-escape", "x; let \\u0000 = 1;"],
  ["lexer-char", "x; let a = 1 \\ 2;"],
  ["lexer-regex", "x; let a = /abc\n/;"],
  ["lexer-regex-flag", "x; let a = /a/gg;"],
  ["lexer-bigint", "x; let a = 1.5n;"],
  ["lexer-hash", "x; # y;"],
  ["lexer-octal-bigint", "x; let a = 01n;"],
  ["lexer-private", "x; class A { # x; }"],
  ["unexpected-enum-member", "enum E { 1 }"],
  ["unexpected-import", "import 1 from \"x\";"],
  ["unexpected-export", "export 1;"],
  ["unexpected-class-member", "class A { 1 + 2 }"],
  ["unexpected-object", "let o = { 1 + 2 };"],
  ["unexpected-binding", "let [1] = a;"],
  ["unexpected-arrow-param", "let f = (1) => 1;"],
  ["unexpected-for", "for (;;"],
  ["unexpected-case", "switch (a) { foo }"],
  ["unexpected-catch", "try {} catch 1 {}"],
  ["unexpected-try", "try {}"],
  ["unexpected-new", "new;"],
  ["unexpected-dot", "a.;"],
  ["unexpected-optional", "a?.;"],
  ["unexpected-jsx", "let a = <div;"],
  ["unexpected-decorator", "@dec let x;"],
  ["unexpected-modifier", "class A { public public x; }"],
  ["unexpected-type-arg", "f<1 +>();"],
  ["unexpected-interface", "interface { }"],
  ["unexpected-type-alias", "type = 1;"],
  ["unexpected-namespace", "namespace 1 {}"],
  ["unexpected-declare", "declare 1;"],
  ["unexpected-abstract", "abstract let x;"],
  ["parser-const-init", "const a;"],
  ["parser-redeclare", "let a; let a;"],
  ["parser-await", "var await;"],
  ["parser-await-fn", "function f() { await 1; }"],
  ["parser-yield", "function f() { yield 1; }"],
  ["parser-super", "super.x;"],
  ["parser-html", "a\n<!-- b\n"],
  ["parser-dup-private", "class A { #x; #x; }"],
  ["parser-invalid-assign-target", "({ a: 1 } = 1);"],
  ["parser-rest-last", "let [...a, b] = c;"],
  ["parser-default-dup", "export default 1; export default 2;"],
  ["parser-label", "a: a: ;"],
  ["parser-getter-args", "class A { get x(a) {} }"],
  ["parser-setter-args", "class A { set x() {} }"],
  ["parser-new-target", "new.target;"],
  ["parser-ctor-generator", "class A { *constructor() {} }"],
  ["parser-for-init", "for (let a = 1 of b);"],
  ["parser-for-await", "for await (;;);"],
  ["parser-enum-computed", "enum E { [a] = 1 }"],
  ["parser-param-prop", "function f(private a) {}"],
  ["parser-optional-required", "function f(a?, b) {}"],
  ["parser-accessor-type-param", "class A { get x<T>() { return 1 } }"],
  ["parser-abstract-body", "abstract class A { abstract m() {} }"],
  ["parser-declare-init", "declare const x = 1 + ;"],
  ["parser-import-assign", "import x = ;"],
  ["parser-export-equals", "export = ;"],
  ["parser-satisfies", "let a = b satisfies ;"],
  ["parser-non-null-new", "new a!();"],
  ["parser-using", "using x;"],
  ["parser-with-stmt", "with (a) b;"],
  ["parser-octal", "let a = 071;"],
  ["parser-delete", "delete x;"],
  ["warn-html-close", "x\n--> y\n"],
  ["warn-then-error", "x\n--> y\nlet z = ;\n"],
];
const names = [];
for (const [k, code] of cases) { fs.writeFileSync(`${k}.ts`, code); names.push(`${k}.ts`); }
fs.writeFileSync("names.list", names.join("\n") + "\n");
fs.writeFileSync("cases.json", JSON.stringify(cases));
