const fs = require("fs");
const cases = {
  with: "with (a) b;",
  octal: "var a = 071;",
  octalEscape: 'var a = "\\071";',
  nonOctal8: 'var a = "\\8";',
  deleteVar: "var x; delete x;",
  dupeArgs: "function f(a, a) {}",
  topReturn: "return;",
  topAwait: "await x;",
  importWith: 'import x from "y"; with (a) b;',
  exportOctal: "export {}; var a = 071;",
  useStrictWith: '"use strict"; with (a) b;',
  useStrictOctal: '"use strict"; var a = 071;',
  classWith: "class A { m() { with (a) b; } }",
  letYield: "var yield;",
  varLet: "var let;",
  evalAssign: "eval = 1;",
  argumentsAssign: "arguments = 1;",
  reservedPublic: "var public;",
  reservedInterface: "var interface;",
  htmlComment: "a\n<!-- b\n",
  varAwait: "var await;",
  importMeta: "import.meta.url;",
  newTarget: "new.target;",
  labelledFn: "a: function f() {}",
  ifFn: "if (a) function f() {}",
  importAndReturn: 'import x from "y"; return;',
  exportAndAwaitVar: "export {}; var await;",
  fnUseStrictOctal: 'function f() { "use strict"; return 071; }',
  legacyOctalLike: "var a = 08;",
  enumWord: "var enum;",
  staticWord: "var static;",
  implementsWord: "var implements;",
  asyncArrowAwait: "async () => { await 1 };",
  redeclareLet: "let a; let a;",
  redeclareVarLet: "var a; let a;",
  fnRedeclare: "function f() {} function f() {}",
  letFnRedeclare: "let f; function f() {}",
  catchRedeclare: "try {} catch (e) { let e; }",
  breakOutside: "break;",
  continueOutside: "continue;",
  undefinedLabel: "foo: while (1) { break bar; }",
  dupLabel: "a: a: ;",
  superOutside: "super.x;",
  dupProto: "({ __proto__: 1, __proto__: 2 });",
  regexInvalid: "/(/;",
  regexFlags: "/a/gg;",
  privateUndeclared: "class A { m() { this.#x; } }",
  dupPrivate: "class A { #x; #x; }",
  dupConstructor: "class A { constructor() {} constructor() {} }",
  invalidAssign: "1 = 2;",
  invalidUpdate: "++a++;",
  constNoInit: "const a;",
  optionalAssign: "a?.b = 1;",
  yieldOutside: "yield 1;",
  awaitInNonAsync: "function f() { await 1; }",
  deleteIdentStrict: '"use strict"; var x; delete x;',
  dupeArgsStrict: '"use strict"; function f(a, a) {}',
  dupeArgsArrow: "(a, a) => 1;",
  exportDupe: "var a; export { a, a };",
  exportUndeclared: "export { nope };",
  importDupe: 'import { a } from "x"; import { a } from "y";',
  usingDecl: "using x = y;",
  decorators: "@dec class A {}",
};
const exts = ["js", "jsx", "mjs", "cjs", "ts", "tsx", "mts", "cts"];
const names = [];
for (const [k, code] of Object.entries(cases)) for (const e of exts) { const n = `${k}.${e}`; fs.writeFileSync(n, code + "\n"); names.push(n); }
fs.writeFileSync("names.list", names.join("\n") + "\n");
fs.writeFileSync("cases.json", JSON.stringify(cases, null, 1));
