- name: 'bug'
  color: 'd73a4a'
- name: 'segfault'
  color: 'b60205'
- name: 'documentation'
  color: '0075ca'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'wontfix'
  color: 'cfd3d7'
- name: 'question'
  color: 'd876e3'
- name: 'enhancement'
  color: 'a2eeef'
- name: 'good first issue'
  color: '7057ff'
- name: 'help wanted'
  color: '008672'
- name: 'infrastructure'
  color: '7c5f8a'
- name: 'invalid'
  color: 'e4e669'
- name: 'need repro'
  color: 'c66037'
- name: 'node.js'
  color: '0E8A16'
- name: 'napi'
  color: 'BE05D2'
- name: 'esm<>cjs'
  color: '7dcde3'
- name: 'performance'
  color: 'E99695'
- name: 'polyfill'
  color: 'f9c5e6'
- name: 'tracking'
  color: '5319E7'
- name: 'transpiler'
  color: 'BFDADC'
- name: 'typescript'
  color: '87511b'
- name: 'chore'
  color: 'cfd3d7'
- name: 'templates'
  color: 'FBCA04'
- name: 'benchmarks'
  color: 'FBCA04'
- name: 'tests'
  color: 'FBCA04'
- name: 'packages:bun'
  color: 'FBCA04'
- name: 'packages:bun-darwin-aarch64'
  color: 'FBCA04'
- name: 'packages:bun-error'
  color: 'FBCA04'
- name: 'packages:bun-framework-next'
  color: 'FBCA04'
- name: 'packages:bun-landing'
  color: 'FBCA04'
- name: 'packages:bun-linux-x64'
  color: 'FBCA04'
- name: 'packages:bun-macro-relay'
  color: 'FBCA04'
- name: 'packages:bun-types'
  color: 'FBCA04'
- name: 'packages:bun-wasm'
  color: 'FBCA04'
