// Generated with scripts/generate-perf-trace-events.sh
// clang-format off
#define FOR_EACH_TRACE_EVENT(macro) \
  macro(Bundler.BindImportsToExports, 0) \
  macro(Bundler.breakOutputIntoPieces, 1) \
  macro(Bundler.cloneAST, 2) \
  macro(Bundler.CloneLinkerGraph, 3) \
  macro(Bundler.computeChunks, 4) \
  macro(Bundler.CreateNamespaceExports, 5) \
  macro(Bundler.FigureOutCommonJS, 6) \
  macro(Bundler.findAllImportedPartsInJSOrder, 7) \
  macro(Bundler.findReachableFiles, 8) \
  macro(Bundler.generateChunksInParallel, 9) \
  macro(Bundler.generateCodeForFileInChunkCss, 10) \
  macro(Bundler.generateCodeForFileInChunkJS, 11) \
  macro(Bundler.generateIsolatedHash, 12) \
  macro(Bundler.generateSourceMapForChunk, 13) \
  macro(Bundler.markFileLiveForTreeShaking, 14) \
  macro(Bundler.markFileReachableForCodeSplitting, 15) \
  macro(Bundler.MatchImportsWithExports, 16) \
  macro(Bundler.onParseTaskComplete, 17) \
  macro(Bundler.ParseJS, 18) \
  macro(Bundler.ParseJSON, 19) \
  macro(Bundler.ParseJSON5, 20) \
  macro(Bundler.ParseTOML, 21) \
  macro(Bundler.ParseYAML, 22) \
  macro(Bundler.postProcessJSChunk, 23) \
  macro(Bundler.readFile, 24) \
  macro(Bundler.renameSymbolsInChunk, 25) \
  macro(Bundler.ResolveExportStarStatements, 26) \
  macro(Bundler.scanImportsAndExports, 27) \
  macro(Bundler.treeShakingAndCodeSplitting, 28) \
  macro(Bundler.Worker.create, 29) \
  macro(Bundler.WrapDependencies, 30) \
  macro(Bundler.writeChunkToDisk, 31) \
  macro(Bundler.writeOutputFilesToDisk, 32) \
  macro(ExtractTarball.extract, 33) \
  macro(FolderResolver.readPackageJSONFromDisk.folder, 34) \
  macro(FolderResolver.readPackageJSONFromDisk.workspace, 35) \
  macro(JSBundler.addPlugin, 36) \
  macro(JSBundler.hasAnyMatches, 37) \
  macro(JSBundler.matchOnLoad, 38) \
  macro(JSBundler.matchOnResolve, 39) \
  macro(JSGlobalObject.create, 40) \
  macro(JSParser.analyze, 41) \
  macro(JSParser.parse, 42) \
  macro(JSParser.postvisit, 43) \
  macro(JSParser.visit, 44) \
  macro(JSPrinter.print, 45) \
  macro(JSPrinter.printWithSourceMap, 46) \
  macro(ModuleResolver.resolve, 47) \
  macro(PackageInstaller.install, 48) \
  macro(PackageManifest.Serializer.loadByFile, 49) \
  macro(PackageManifest.Serializer.save, 50) \
  macro(RuntimeTranspilerCache.fromFile, 51) \
  macro(RuntimeTranspilerCache.save, 52) \
  macro(RuntimeTranspilerCache.toFile, 53) \
  macro(StandaloneModuleGraph.serialize, 54) \
  macro(Symbols.followAll, 55) \
  macro(TestCommand.printCodeCoverageLCov, 56) \
  macro(TestCommand.printCodeCoverageLCovAndText, 57) \
  macro(TestCommand.printCodeCoverageText, 58) \
  // end
