//! BoringSSL FFI surface.
//!
//! This crate re-exports BoringSSL's upstream `bssl-sys` (generated by bindgen
//! from the in-tree `vendor/boringssl` headers; see `scripts/build/codegen.ts`)
//! and layers a small Bun-specific compat surface on top so existing callers
//! keep the ergonomics the old hand-rolled module provided: safe no-arg
//! wrappers for the thread-local error queue and digest singletons, RAII
//! handle owners, and `opaque_ref`/`opaque_mut` helpers on the handle types.
//!
//! The higher-level `bssl-crypto` is re-exported as `crypto` for callers that
//! can use the idiomatic API; `constant_time_eq` delegates to it.
#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]

use core::ffi::{c_char, c_int};

use bssl_sys as bindgen;
pub use bssl_sys::*;

/// Upstream idiomatic wrappers (`digest`, `hmac`, `aead`, `rsa`, `mem`, ...).
pub use bssl_crypto as crypto;

mod ext;
pub use ext::*;

/// bindgen emits this as `i32` from `#define ... 0x00000004L`; callers pass it
/// to `SSL_set_options`/`SSL_clear_options` which take `u32`.
pub const SSL_OP_LEGACY_SERVER_CONNECT: u32 = bindgen::SSL_OP_LEGACY_SERVER_CONNECT as u32;

// ═══════════════════════════════════════════════════════════════════════════
// Safe wrappers — no-arg / value-arg functions with no caller preconditions
//
// bindgen marks every extern `unsafe`. These are the subset Bun calls from
// safe code: thread-local error queue accessors, static digest singletons,
// and idempotent library-init no-ops. Defining them as items shadows the
// `pub use bssl_sys::*` glob so callers keep the bare-call ergonomics.
// ═══════════════════════════════════════════════════════════════════════════

macro_rules! safe_shim {
    ($( $(#[$m:meta])* fn $name:ident($($arg:ident : $t:ty),*) $(-> $ret:ty)? ;)+) => {$(
        $(#[$m])*
        #[inline]
        pub fn $name($($arg: $t),*) $(-> $ret)? {
            // SAFETY: no pointer arguments / no caller-side preconditions.
            unsafe { bindgen::$name($($arg),*) }
        }
    )+};
}

safe_shim! {
    fn CRYPTO_library_init();
    fn SSL_library_init() -> c_int;
    fn SSL_load_error_strings();
    fn ERR_load_BIO_strings();
    fn ERR_load_ERR_strings();
    fn ERR_load_crypto_strings();
    fn OpenSSL_add_all_algorithms();

    fn ERR_clear_error();
    fn ERR_get_error() -> u32;
    fn ERR_peek_error() -> u32;
    fn ERR_peek_last_error() -> u32;
    fn ERR_lib_error_string(packed_error: u32) -> *const c_char;
    fn ERR_func_error_string(packed_error: u32) -> *const c_char;
    fn ERR_reason_error_string(packed_error: u32) -> *const c_char;

    fn EVP_md4() -> *const EVP_MD;
    fn EVP_md5() -> *const EVP_MD;
    fn EVP_md5_sha1() -> *const EVP_MD;
    fn EVP_ripemd160() -> *const EVP_MD;
    fn EVP_sha1() -> *const EVP_MD;
    fn EVP_sha224() -> *const EVP_MD;
    fn EVP_sha256() -> *const EVP_MD;
    fn EVP_sha384() -> *const EVP_MD;
    fn EVP_sha512() -> *const EVP_MD;
    fn EVP_sha512_224() -> *const EVP_MD;
    fn EVP_sha512_256() -> *const EVP_MD;
    fn EVP_sha3_224() -> *const EVP_MD;
    fn EVP_sha3_256() -> *const EVP_MD;
    fn EVP_sha3_384() -> *const EVP_MD;
    fn EVP_sha3_512() -> *const EVP_MD;
    fn EVP_blake2b256() -> *const EVP_MD;
    fn EVP_blake2b512() -> *const EVP_MD;

    fn TLS_with_buffers_method() -> *const SSL_METHOD;
    fn BIO_s_mem() -> *const BIO_METHOD;
    fn ENGINE_new() -> *mut ENGINE;

    fn X509V3_EXT_get_nid(nid: c_int) -> *const X509V3_EXT_METHOD;
}
