/opt/homebrew/opt/llvm@16/bin/ld64.lld\
  -demangle \
  -lto_library \
  /opt/homebrew/Cellar/llvm@16/16.0.6/lib/libLTO.dylib \
  -dynamic \
  -arch \
  arm64 \
  -dead_strip \
  -exported_symbols_list \
  /Users/dave/code/bun/src/symbols.txt \
  -platform_version \
  macos \
  11.0.0 \
  14.0 \
  -syslibroot \
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk \
  -o \
  bun-profile \
  -search_paths_first \
  -headerpad_max_install_names \
  /Users/dave/code/bun/build/bun-zig.o \
  -lresolv \
  -licucore \
  /opt/homebrew/opt/libiconv/lib/libiconv.a \
  /opt/homebrew/opt/icu4c/lib/libicudata.a \
  /opt/homebrew/opt/icu4c/lib/libicui18n.a \
  /opt/homebrew/opt/icu4c/lib/libicuuc.a \
  /Users/dave/code/bun/src/deps/libz.a \
  /Users/dave/code/bun/src/deps/libcrypto.a \
  /Users/dave/code/bun/src/deps/libssl.a \
  /Users/dave/code/bun/src/deps/libdecrepit.a \
  /Users/dave/code/bun/src/deps/libarchive.a \
  /Users/dave/code/bun/src/deps/libmimalloc.a \
  /Users/dave/code/bun/src/deps/libzstd.a \
  /Users/dave/code/bun/src/deps/libcares.a \
  /Users/dave/code/bun/src/deps/libbase64.a \
  /Users/dave/code/bun/src/deps/libtcc.a \
  /Users/dave/code/bun/src/deps/liblolhtml.a \
  bun-webkit/lib/libWTF.a \
  bun-webkit/lib/libJavaScriptCore.a \
  bun-webkit/lib/libbmalloc.a \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ActiveDOMCallback.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/AsyncContextFrame.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunClientData.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunDebugger.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunGCOutputConstraint.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunInjectedScriptHost.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunInspector.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunPlugin.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunProcess.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunString.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/BunWorkerGlobalScope.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/CallSite.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/CallSitePrototype.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/CodeCoverage.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/CommonJSModuleRecord.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/DOMException.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/DOMFormData.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/DOMURL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/DOMWrapperWorld.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ErrorStackTrace.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ImportMetaObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/InternalModuleRegistry.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSBuffer.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSBufferEncodingType.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSBufferList.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSBundlerPlugin.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSCTaskScheduler.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSCUSocketsLoopIntegration.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSDOMExceptionHandling.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSDOMFile.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSDOMGlobalObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSDOMWrapper.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSDOMWrapperCache.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSEnvironmentVariableMap.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSFFIFunction.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSMockFunction.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSNextTickQueue.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSReadableHelper.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSReadableState.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSSocketAddress.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/JSStringDecoder.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/KeyObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/MarkingConstraint.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ModuleLoader.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/NodeVMScript.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/Path.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ProcessBindingConstants.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ProcessBindingNatives.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ProcessBindingUV.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ProcessIdentifier.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/RegularExpression.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ScriptExecutionContext.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/Serialization.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/Strong.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/URLDecomposition.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/URLSearchParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ZigConsoleClient.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ZigGeneratedCode.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ZigGlobalObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/ZigSourceProvider.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/bindings.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/blob.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/bun-simdutf.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/c-bindings.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/coroutine.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/helpers.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/inlines.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/isBuiltinModule.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/napi.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/napi_external.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/objects.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/simdutf.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/spawn.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/sqlite/JSSQLStatement.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/AbortController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/AbortSignal.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ActiveDOMObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/BroadcastChannel.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/BunBroadcastChannelRegistry.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/CloseEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/CommonAtomStrings.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ContextDestructionObserver.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/CustomEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/CustomEventCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/DOMJITHelpers.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ErrorCallback.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ErrorEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/Event.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventContext.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventDispatcher.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventEmitter.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventFactory.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventListenerMap.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventNames.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventPath.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventTarget.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventTargetConcrete.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/EventTargetFactory.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/FetchHeaders.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/HTTPHeaderField.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/HTTPHeaderMap.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/HTTPHeaderNames.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/HTTPHeaderValues.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/HTTPParsers.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/IdentifierEventListenerMap.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/InternalWritableStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSAbortAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSAbortController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSAbortSignal.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSAbortSignalCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSAddEventListenerOptions.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSBroadcastChannel.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSByteLengthQueuingStrategy.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSCallbackData.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSCloseEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSCountQueuingStrategy.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSCustomEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMBindingInternalsBuiltins.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMBuiltinConstructorBase.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMConstructorBase.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMConvertDate.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMConvertNumbers.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMConvertStrings.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMConvertWebGL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMException.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMFormData.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMGuardedObject.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMIterator.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMPromise.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMPromiseDeferred.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSDOMURL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSErrorCallback.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSErrorEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSErrorEventCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSErrorHandler.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventDOMJIT.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventEmitter.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventEmitterCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventInit.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventListener.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventListenerOptions.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventModifierInit.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventTarget.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSEventTargetCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSFetchHeaders.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessageChannel.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessageChannelCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessageEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessageEventCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessagePort.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSMessagePortCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableByteStreamController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamBYOBReader.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamBYOBRequest.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamDefaultController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamDefaultReader.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamSink.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamSource.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSReadableStreamSourceCustom.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSStructuredSerializeOptions.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSTextEncoder.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSTransformStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSTransformStreamDefaultController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSURLSearchParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWebSocket.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWorker.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWorkerOptions.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWritableStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWritableStreamDefaultController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWritableStreamDefaultWriter.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/JSWritableStreamSink.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessageChannel.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessageEvent.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessagePort.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessagePortChannel.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessagePortChannelProvider.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessagePortChannelProviderImpl.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/MessagePortChannelRegistry.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ParsedContentType.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ReadableStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ReadableStreamDefaultController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ReadableStreamSink.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ReadableStreamSource.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/ScriptWrappable.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/SerializedScriptValue.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/SharedBuffer.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/StructuredClone.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/TextEncoder.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/WebCoreTypedArrayController.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/WebSocket.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/Worker.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/WritableStream.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcore/weak_handle.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CommonCryptoDERUtilities.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CBC.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CBCOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CFB.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CFBOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CTR.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CTROpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_GCM.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_GCMOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_KW.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_KWOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDH.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDHOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDSA.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDSAOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmEd25519.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHKDF.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHKDFOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHMAC.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHMACOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmPBKDF2.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmPBKDF2OpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSAES_PKCS1_v1_5.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSAES_PKCS1_v1_5OpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSASSA_PKCS1_v1_5.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSASSA_PKCS1_v1_5OpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_OAEP.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_OAEPOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_PSS.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_PSSOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRegistry.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRegistryOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA1.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA224.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA256.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA384.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA512.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoDigest.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKey.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyAES.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyEC.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyECOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyHMAC.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyOKP.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyOKPOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSA.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSAComponents.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSAOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/CryptoKeyRaw.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSAesCbcCfbParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSAesCtrParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSAesGcmParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSAesKeyParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoAesKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoAlgorithmParameters.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoEcKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoHmacKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoKey.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyPair.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyUsage.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoRsaHashedKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSCryptoRsaKeyAlgorithm.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSEcKeyParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSEcdhKeyDeriveParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSEcdsaParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSHkdfParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSHmacKeyParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSJsonWebKey.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSPbkdf2Params.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaHashedImportParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaHashedKeyGenParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaKeyGenParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaOaepParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaOtherPrimesInfo.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSRsaPssParams.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/JSSubtleCrypto.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/OpenSSLUtilities.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/SerializedCryptoKeyWrapOpenSSL.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/webcrypto/SubtleCrypto.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/workaround-missing-symbols.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/bindings/wtf-bindings.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/modules/BunObjectModule.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/bun.js/modules/ObjectModule.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/deps/libuwsockets.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/deps/picohttpparser/picohttpparser.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/src/io/io_darwin.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/bsd.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/context.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/crypto/openssl.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/crypto/root_certs.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/crypto/sni_tree.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/eventing/epoll_kqueue.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/eventing/libuv.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/loop.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/quic.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/socket.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/packages/bun-usockets/src/udp.c.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/codegen/ZigGeneratedClasses.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/codegen/JSSink.cpp.o \
  /Users/dave/code/bun/build2/CMakeFiles/bun-profile.dir/codegen/WebCoreJSBuiltins.cpp.o \
  -lc++ \
  -lSystem \
  /opt/homebrew/Cellar/llvm@16/16.0.6/lib/clang/16/lib/darwin/libclang_rt.osx.a \
  -v