#include "root.h"

#include "ZigGlobalObject.h"
#include "JavaScriptCore/Identifier.h"
#include "JavaScriptCore/JSCJSValue.h"
#include "JavaScriptCore/JSObject.h"
#include "JavaScriptCore/ObjectConstructor.h"

#include <zlib.h>
#include <brotli/encode.h>
#include <brotli/decode.h>

#include "Constants.h"

#define Z_MIN_WINDOWBITS 8
#define Z_MAX_WINDOWBITS 15
#define Z_DEFAULT_WINDOWBITS 15
#define Z_MIN_CHUNK 64
#define Z_MAX_CHUNK std::numeric_limits<double>::infinity()
#define Z_DEFAULT_CHUNK (16 * 1024)
#define Z_MIN_MEMLEVEL 1
#define Z_MAX_MEMLEVEL 9
#define Z_DEFAULT_MEMLEVEL 8
#define Z_MIN_LEVEL -1
#define Z_MAX_LEVEL 9
#define Z_DEFAULT_LEVEL Z_DEFAULT_COMPRESSION

enum node_zlib_mode {
    NONE,
    DEFLATE,
    INFLATE,
    GZIP,
    GUNZIP,
    DEFLATERAW,
    INFLATERAW,
    UNZIP,
    BROTLI_DECODE,
    BROTLI_ENCODE
};

#define NODE_DEFINE_CONSTANT(obj, C) obj->putDirect(vm, JSC::Identifier::fromString(vm, WTF::ASCIILiteral::fromLiteralUnsafe(#C)), JSC::jsNumber(C))

JSC::JSValue ZlibConstants(Zig::GlobalObject* globalObject)
{
    auto& vm = globalObject->vm();
    auto target = JSC::constructEmptyObject(globalObject, globalObject->objectPrototype(), 0);

    NODE_DEFINE_CONSTANT(target, Z_NO_FLUSH);
    NODE_DEFINE_CONSTANT(target, Z_PARTIAL_FLUSH);
    NODE_DEFINE_CONSTANT(target, Z_SYNC_FLUSH);
    NODE_DEFINE_CONSTANT(target, Z_FULL_FLUSH);
    NODE_DEFINE_CONSTANT(target, Z_FINISH);
    NODE_DEFINE_CONSTANT(target, Z_BLOCK);

    NODE_DEFINE_CONSTANT(target, Z_OK);
    NODE_DEFINE_CONSTANT(target, Z_STREAM_END);
    NODE_DEFINE_CONSTANT(target, Z_NEED_DICT);
    NODE_DEFINE_CONSTANT(target, Z_ERRNO);
    NODE_DEFINE_CONSTANT(target, Z_STREAM_ERROR);
    NODE_DEFINE_CONSTANT(target, Z_DATA_ERROR);
    NODE_DEFINE_CONSTANT(target, Z_MEM_ERROR);
    NODE_DEFINE_CONSTANT(target, Z_BUF_ERROR);
    NODE_DEFINE_CONSTANT(target, Z_VERSION_ERROR);

    NODE_DEFINE_CONSTANT(target, Z_NO_COMPRESSION);
    NODE_DEFINE_CONSTANT(target, Z_BEST_SPEED);
    NODE_DEFINE_CONSTANT(target, Z_BEST_COMPRESSION);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_COMPRESSION);
    NODE_DEFINE_CONSTANT(target, Z_FILTERED);
    NODE_DEFINE_CONSTANT(target, Z_HUFFMAN_ONLY);
    NODE_DEFINE_CONSTANT(target, Z_RLE);
    NODE_DEFINE_CONSTANT(target, Z_FIXED);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_STRATEGY);
    NODE_DEFINE_CONSTANT(target, ZLIB_VERNUM);

    NODE_DEFINE_CONSTANT(target, DEFLATE);
    NODE_DEFINE_CONSTANT(target, INFLATE);
    NODE_DEFINE_CONSTANT(target, GZIP);
    NODE_DEFINE_CONSTANT(target, GUNZIP);
    NODE_DEFINE_CONSTANT(target, DEFLATERAW);
    NODE_DEFINE_CONSTANT(target, INFLATERAW);
    NODE_DEFINE_CONSTANT(target, UNZIP);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODE);
    NODE_DEFINE_CONSTANT(target, BROTLI_ENCODE);

    NODE_DEFINE_CONSTANT(target, Z_MIN_WINDOWBITS);
    NODE_DEFINE_CONSTANT(target, Z_MAX_WINDOWBITS);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_WINDOWBITS);
    NODE_DEFINE_CONSTANT(target, Z_MIN_CHUNK);
    NODE_DEFINE_CONSTANT(target, Z_MAX_CHUNK);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_CHUNK);
    NODE_DEFINE_CONSTANT(target, Z_MIN_MEMLEVEL);
    NODE_DEFINE_CONSTANT(target, Z_MAX_MEMLEVEL);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_MEMLEVEL);
    NODE_DEFINE_CONSTANT(target, Z_MIN_LEVEL);
    NODE_DEFINE_CONSTANT(target, Z_MAX_LEVEL);
    NODE_DEFINE_CONSTANT(target, Z_DEFAULT_LEVEL);

    NODE_DEFINE_CONSTANT(target, BROTLI_OPERATION_PROCESS);
    NODE_DEFINE_CONSTANT(target, BROTLI_OPERATION_FLUSH);
    NODE_DEFINE_CONSTANT(target, BROTLI_OPERATION_FINISH);
    NODE_DEFINE_CONSTANT(target, BROTLI_OPERATION_EMIT_METADATA);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_MODE);
    NODE_DEFINE_CONSTANT(target, BROTLI_MODE_GENERIC);
    NODE_DEFINE_CONSTANT(target, BROTLI_MODE_TEXT);
    NODE_DEFINE_CONSTANT(target, BROTLI_MODE_FONT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DEFAULT_MODE);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_QUALITY);
    NODE_DEFINE_CONSTANT(target, BROTLI_MIN_QUALITY);
    NODE_DEFINE_CONSTANT(target, BROTLI_MAX_QUALITY);
    NODE_DEFINE_CONSTANT(target, BROTLI_DEFAULT_QUALITY);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_LGWIN);
    NODE_DEFINE_CONSTANT(target, BROTLI_MIN_WINDOW_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_MAX_WINDOW_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_LARGE_MAX_WINDOW_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DEFAULT_WINDOW);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_LGBLOCK);
    NODE_DEFINE_CONSTANT(target, BROTLI_MIN_INPUT_BLOCK_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_MAX_INPUT_BLOCK_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_SIZE_HINT);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_LARGE_WINDOW);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_NPOSTFIX);
    NODE_DEFINE_CONSTANT(target, BROTLI_PARAM_NDIRECT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_RESULT_ERROR);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_RESULT_SUCCESS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_PARAM_LARGE_WINDOW);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_NO_ERROR);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_SUCCESS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_NEEDS_MORE_INPUT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_NEEDS_MORE_OUTPUT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_RESERVED);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_CL_SPACE);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_TRANSFORM);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_DICTIONARY);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_PADDING_1);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_PADDING_2);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_FORMAT_DISTANCE);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_INVALID_ARGUMENTS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES);
    NODE_DEFINE_CONSTANT(target, BROTLI_DECODER_ERROR_UNREACHABLE);

    return target;
}
