// used by generate-node-errors.ts
type ErrorCodeMapping = Array<
  [
    /** error.code  */
    code: string,
    /** Constructor **/
    ctor: typeof TypeError | typeof RangeError | typeof Error | typeof SyntaxError,
    /** error.name. Defaults to `Constructor.name` (that is, mapping[1].name  */
    name?: string,
    (typeof TypeError | typeof RangeError | typeof Error | typeof SyntaxError)?,
    (typeof TypeError | typeof RangeError | typeof Error | typeof SyntaxError)?,
  ]
>;

const errors: ErrorCodeMapping = [
  ["ABORT_ERR", Error, "AbortError"],
  ["ERR_AMBIGUOUS_ARGUMENT", TypeError],
  ["ERR_ASSERTION", Error],
  ["ERR_BROTLI_INVALID_PARAM", RangeError],
  ["ERR_BUFFER_OUT_OF_BOUNDS", RangeError],
  ["ERR_BUFFER_TOO_LARGE", RangeError],
  ["ERR_CRYPTO_ECDH_INVALID_FORMAT", TypeError],
  ["ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY", Error],
  ["ERR_CRYPTO_INCOMPATIBLE_KEY", Error],
  ["ERR_CRYPTO_INVALID_CURVE", TypeError],
  ["ERR_CRYPTO_INVALID_DIGEST", TypeError],
  ["ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE", TypeError],
  ["ERR_CRYPTO_INVALID_SCRYPT_PARAMS", RangeError],
  ["ERR_CRYPTO_INVALID_STATE", Error],
  ["ERR_CRYPTO_JWK_UNSUPPORTED_CURVE", Error],
  ["ERR_CRYPTO_OPERATION_FAILED", Error],
  ["ERR_CRYPTO_SCRYPT_INVALID_PARAMETER", Error],
  ["ERR_DLOPEN_FAILED", Error],
  ["ERR_ENCODING_INVALID_ENCODED_DATA", TypeError],
  ["ERR_ILLEGAL_CONSTRUCTOR", TypeError],
  ["ERR_INCOMPATIBLE_OPTION_PAIR", TypeError],
  ["ERR_INVALID_ARG_TYPE", TypeError],
  ["ERR_INVALID_ARG_VALUE", TypeError],
  ["ERR_INVALID_CURSOR_POS", TypeError],
  ["ERR_INVALID_IP_ADDRESS", TypeError],
  ["ERR_INVALID_PROTOCOL", TypeError],
  ["ERR_INVALID_RETURN_VALUE", TypeError],
  ["ERR_INVALID_STATE", Error, undefined, TypeError, RangeError],
  ["ERR_INVALID_THIS", TypeError],
  ["ERR_INVALID_URI", URIError],
  ["ERR_IPC_CHANNEL_CLOSED", Error],
  ["ERR_IPC_DISCONNECTED", Error],
  ["ERR_IPC_ONE_PIPE", Error],
  ["ERR_METHOD_NOT_IMPLEMENTED", Error],
  ["ERR_MISSING_ARGS", TypeError],
  ["ERR_MULTIPLE_CALLBACK", Error],
  ["ERR_OUT_OF_RANGE", RangeError],
  ["ERR_PARSE_ARGS_INVALID_OPTION_VALUE", TypeError],
  ["ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL", TypeError],
  ["ERR_PARSE_ARGS_UNKNOWN_OPTION", TypeError],
  ["ERR_SCRIPT_EXECUTION_INTERRUPTED", Error],
  ["ERR_SCRIPT_EXECUTION_TIMEOUT", Error],
  ["ERR_SERVER_NOT_RUNNING", Error],
  ["ERR_SOCKET_ALREADY_BOUND", Error],
  ["ERR_SOCKET_BAD_BUFFER_SIZE", TypeError],
  ["ERR_SOCKET_BAD_PORT", RangeError],
  ["ERR_SOCKET_BAD_TYPE", TypeError],
  ["ERR_SOCKET_DGRAM_IS_CONNECTED", Error],
  ["ERR_SOCKET_DGRAM_NOT_CONNECTED", Error],
  ["ERR_SOCKET_DGRAM_NOT_RUNNING", Error],
  ["ERR_STREAM_ALREADY_FINISHED", Error],
  ["ERR_STREAM_CANNOT_PIPE", Error],
  ["ERR_STREAM_DESTROYED", Error],
  ["ERR_STREAM_NULL_VALUES", TypeError],
  ["ERR_STREAM_PREMATURE_CLOSE", Error],
  ["ERR_STREAM_PUSH_AFTER_EOF", Error],
  ["ERR_STREAM_RELEASE_LOCK", Error, "AbortError"],
  ["ERR_STREAM_UNABLE_TO_PIPE", Error],
  ["ERR_STREAM_UNSHIFT_AFTER_END_EVENT", Error],
  ["ERR_STREAM_WRITE_AFTER_END", Error],
  ["ERR_STRING_TOO_LONG", Error],
  ["ERR_UNAVAILABLE_DURING_EXIT", Error],
  ["ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET", Error],
  ["ERR_UNHANDLED_ERROR", Error],
  ["ERR_UNKNOWN_CREDENTIAL", Error],
  ["ERR_UNKNOWN_ENCODING", TypeError],
  ["ERR_UNKNOWN_SIGNAL", TypeError],
  ["ERR_ZLIB_INITIALIZATION_FAILED", Error],
  ["MODULE_NOT_FOUND", Error],

  // Bun-specific
  ["ERR_FORMDATA_PARSE_ERROR", TypeError],
  ["ERR_BODY_ALREADY_USED", Error],
  ["ERR_STREAM_WRAP", Error],
  ["ERR_BORINGSSL", Error],

  // Console
  ["ERR_CONSOLE_WRITABLE_STREAM", TypeError, "TypeError"],

  // FS
  ["ERR_DIR_CLOSED", Error],

  // DNS
  ["ERR_DNS_SET_SERVERS_FAILED", Error],

  // TLS
  ["ERR_TLS_CERT_ALTNAME_FORMAT", SyntaxError],
  ["ERR_TLS_CERT_ALTNAME_INVALID", Error],
  ["ERR_TLS_SNI_FROM_SERVER", Error],

  // NET
  ["ERR_SOCKET_CLOSED_BEFORE_CONNECTION", Error],
  ["ERR_SOCKET_CLOSED", Error],

  // HTTP2
  ["ERR_INVALID_HTTP_TOKEN", TypeError],
  ["ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED", TypeError],
  ["ERR_HTTP2_SEND_FILE", Error],
  ["ERR_HTTP2_SEND_FILE_NOSEEK", Error],
  ["ERR_HTTP2_HEADERS_SENT", Error, "ERR_HTTP2_HEADERS_SENT"],
  ["ERR_HTTP2_INFO_STATUS_NOT_ALLOWED", RangeError],
  ["ERR_HTTP2_STATUS_INVALID", RangeError],
  ["ERR_HTTP2_INVALID_PSEUDOHEADER", TypeError],
  ["ERR_HTTP2_INVALID_HEADER_VALUE", TypeError],
  ["ERR_HTTP2_PING_CANCEL", Error],
  ["ERR_HTTP2_STREAM_ERROR", Error],
  ["ERR_HTTP2_INVALID_SINGLE_VALUE_HEADER", TypeError],
  ["ERR_HTTP2_SESSION_ERROR", Error],
  ["ERR_HTTP2_INVALID_SESSION", Error],
  ["ERR_HTTP2_INVALID_HEADERS", Error],
  ["ERR_HTTP2_PING_LENGTH", RangeError],
  ["ERR_HTTP2_INVALID_STREAM", Error],
  ["ERR_HTTP2_TRAILERS_ALREADY_SENT", Error],
  ["ERR_HTTP2_TRAILERS_NOT_READY", Error],
  ["ERR_HTTP2_PAYLOAD_FORBIDDEN", Error],
  ["ERR_HTTP2_NO_SOCKET_MANIPULATION", Error],
  ["ERR_HTTP2_SOCKET_UNBOUND", Error],
  ["ERR_HTTP2_ERROR", Error],
  ["ERR_HTTP2_OUT_OF_STREAMS", Error],

  // AsyncHooks
  ["ERR_ASYNC_TYPE", TypeError],
  ["ERR_INVALID_ASYNC_ID", RangeError],
  ["ERR_ASYNC_CALLBACK", TypeError],

  // Postgres
  ["ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2", Error, "PostgresError"],
  ["ERR_POSTGRES_SERVER_ERROR", Error, "PostgresError"],
  ["ERR_POSTGRES_SYNTAX_ERROR", SyntaxError, "PostgresError"],
  ["ERR_POSTGRES_CONNECTION_CLOSED", Error, "PostgresError"],
  ["ERR_POSTGRES_EXPECTED_REQUEST", Error, "PostgresError"],
  ["ERR_POSTGRES_EXPECTED_STATEMENT", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_BACKEND_KEY_DATA", TypeError, "PostgresError"],
  ["ERR_POSTGRES_INVALID_BINARY_DATA", TypeError, "PostgresError"],
  ["ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING", TypeError, "PostgresError"],
  ["ERR_POSTGRES_INVALID_BYTE_SEQUENCE", TypeError, "PostgresError"],
  ["ERR_POSTGRES_INVALID_CHARACTER", TypeError, "PostgresError"],
  ["ERR_POSTGRES_INVALID_MESSAGE_LENGTH", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_MESSAGE", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_QUERY_BINDING", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_SERVER_KEY", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_SERVER_SIGNATURE", Error, "PostgresError"],
  ["ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET", Error, "PostgresError"],
  ["ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET", Error, "PostgresError"],
  ["ERR_POSTGRES_OVERFLOW", TypeError, "PostgresError"],
  ["ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64", Error, "PostgresError"],
  ["ERR_POSTGRES_SASL_SIGNATURE_MISMATCH", Error, "PostgresError"],
  ["ERR_POSTGRES_TLS_NOT_AVAILABLE", Error, "PostgresError"],
  ["ERR_POSTGRES_TLS_UPGRADE_FAILED", Error, "PostgresError"],
  ["ERR_POSTGRES_UNEXPECTED_MESSAGE", Error, "PostgresError"],
  ["ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD", Error, "PostgresError"],
  ["ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD", Error, "PostgresError"],
  ["ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT", TypeError, "PostgresError"],
  ["ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE", TypeError, "PostgresError"],
  ["ERR_POSTGRES_IDLE_TIMEOUT", Error, "PostgresError"],
  ["ERR_POSTGRES_CONNECTION_TIMEOUT", Error, "PostgresError"],
  ["ERR_POSTGRES_LIFETIME_TIMEOUT", Error, "PostgresError"],
  ["ERR_POSTGRES_INVALID_TRANSACTION_STATE", Error, "PostgresError"],
  ["ERR_POSTGRES_QUERY_CANCELLED", Error, "PostgresError"],
  ["ERR_POSTGRES_UNSAFE_TRANSACTION", Error, "PostgresError"],

  // S3
  ["ERR_S3_MISSING_CREDENTIALS", Error],
  ["ERR_S3_INVALID_METHOD", Error],
  ["ERR_S3_INVALID_PATH", Error],
  ["ERR_S3_INVALID_ENDPOINT", Error],
  ["ERR_S3_INVALID_SIGNATURE", Error],
  ["ERR_S3_INVALID_SESSION_TOKEN", Error],

  // URL
  ["ERR_INVALID_URL", TypeError],
  ["ERR_INVALID_URL_SCHEME", TypeError],
  ["ERR_INVALID_FILE_URL_HOST", TypeError],
  ["ERR_INVALID_FILE_URL_PATH", TypeError],
];
export default errors;
