// usage: node rows.cjs   prints, for the sources named below, the first diagnostic of typescript-go as a row of a Rust test:
// (source, loader, code, start, end, text), offsets in bytes. "parses" where typescript-go reports nothing.
const { parse } = require("./parse.cjs");
const recs = [...parse(__dirname + "/out1.tsc-go-head.txt"), ...parse(__dirname + "/out2.tsc-go-head.txt")];
const by = new Map(recs.map(r => [r.l + "\u0000" + r.s, r]));
const groups = {
  "TS2880": ['import x from "y" assert { type: "json" };', 'import "y" assert { type: "json" };', 'export * from "y" assert { type: "json" };', 'export { a } from "y" assert { type: "json" };', 'import type x from "y" assert { type: "json" };', 'import x from "y" /* c */ assert /* d */ { type: "json" };', 'import x from "y" assert;', 'type T = import("y", { assert: { "resolution-mode": "import" } });', 'let v: import("y", { assert: { "resolution-mode": "import" } }).T;', ["js", 'import x from "y" assert { type: "json" };'], 'import("y", { assert: { type: "json" } });', 'import x from "y" with { type: "json" };', 'import x from "y"\nwith { type: "json" };', 'export * from "y"\nwith { type: "json" };', 'import x from "y"\nwith (a) {}'],
  "TS1357 TS1132": ["enum E { A B }", "enum E { A = 1 B }", "enum E { A; B }", "enum E { A = 1; }", 'enum E { "a" "b" }', "enum E { A: 1 }", "enum E { A /* c */ B }", "declare enum E { A B }", "enum E { A, , B }", "enum E { , }", "enum E { + }", "enum E { >> }", "enum E { A, B", "enum E { A = }", "enum E { A, B, }", "enum E { class = 1, var, }"],
  "TS1130 TS1129 TS1472": ["switch (x) { foo; }", "switch (x) { ) }", "switch (x) { >> }", "switch (x) {", "switch (x) { case 1: ) }", "switch (x) { default: ) }", "switch (x) { case 1: default: ) }", "switch (x) { case 1: { ) } }", "switch (x) { case 1: if (a) ) }", "switch (x) { case 1: catch }", "switch (x) { case 1: in }", "switch (x) { case 1:", "switch (x) { case 1: switch (y) { case 2: ) } }", "try {} foo", "try {}", "try {} ;", "function f() { try {} }", "try {} catch foo", "try {} catch", "try {} finally foo", "{", "{ foo;", "function f() {", "namespace N {", "if (x)", "x = () => {"],
  "TS1135 TS1137": ["f(:)", "f(a, :)", "f(;", "f(", "f(a,", "f(+)", "f(...;)", "f(*)", "f(in)", "f(a, case)", "new A(:)", "f?.(:)", "f<T>(:)", "f(a, >>)", "f((;))", "f(a[:])", "x = [:]", "x = [a, :]", "x = [;", "x = [", "x = [a,", "x = [.]", "x = [a, in]", "x = [+]", "x = [a, var]", "x = [<T>:]", "x = [!:]", "x = [(a, :)]", "x = [a[:]]", "x = [function () { a, : }]", "[:] = x", "x = [a,\n:]"],
  "TS1136 TS1068 TS1146": ["x = {:}", "x = {a: 1, )}", "x = {", "x = {a: 1,", "x = {.}", "x = {*}", "x = {,}", "x = {a: 1, >>}", "({)})", "class C { : }", "class C { ) }", "class C { x; ) }", "class C { foo() {} ) }", "class C { >> }", "x = class { ) }", "class C { static {} ) }", "class C { * ) }", "class C { @dec ) }", "class C { @dec }", "class C { @dec /* c */ ) }", "class C {", ["js", "class C { ) }"]],
  "TS1180 TS1181 TS1134 TS1389 TS1138 TS1390": ["var {:} = x", "var {a, :} = x", "var {", "var {a: } = x", "var {...} = x", "function f({:}) {}", "var [:] = x", "var [a, :] = x", "var [", "var [...] = x", "var [class] = x", "var [[:]] = x", "var [#a] = x", "for (var [a, :] of x) {}", "try {} catch ([a, :]) {}", "var :", "var a, :", "var class", "var a, null", "var a, >>", "var #b", "var a, =>", "var a, in", "var ;", "var a, ;", "{ var }", "var }", "let a, class", "function f(:) {}", "function f(a, :) {}", "function f(", "function f(a, ]) {}", "function f(class) {}", "function f(a, null) {}", "function f(1) {}", "function f(a, *) {}", "function f(a, -) {}", "function f(a, >>) {}", "function f(...) {}", "function f(#a) {}", "class C { m(:) {} }", "x = { m(:) {} }", "type T = { m(:): void }", "type T = new (:) => void", "try {} catch (#a) {}"],
  "TS1139": ["function f<:>() {}", "function f<T, :>() {}", "class C<:> {}", "type T<U, 1> = 1", "type T<class> = 1", "type T<U,", "function f<T, () {}", "class C<T, extends D {}", "type T<in> = 1", "function f<>() {}", "function f<T,>() {}"],
  "TS1442 TS1436 TS1441 TS1434 TS1435 TS1144": ["class C { x: number y }", "class C { x: number = 1 y }", "class C { x = 1 y }", "class C { x y }", "class C { x, y }", "class C { x! y }", "class C { static ) }", "class C { public static ) }", "class C { get ) }", "class C { var x }", "class C { declare ) }", "class C { async ) }", "class C { cosnt x }", "class C { 1 y }", "class C { #x y }", "class C { x @dec y }", "class C { x: number @dec y }", "class C { x: number() }", "class C { x?: number (y) }", "class C { x: number\n(y) }", "class C { a: number, b }", "class C { a: number: string }", "class C { foo() bar }", "class C { constructor() bar }", "class C { get x() bar }", "class C { foo(): void bar }", "function f() bar", "function f() => 1", "declare function f() bar", "x = function () bar", "x = { m() bar }", ["js", "function f() bar"], ["js", "class C { foo() bar }"]],
  "missing semicolon": ["foo bar", "foo 1", "foo {}", "  foo bar", "foo /* c */ bar", "{ foo bar }", "if (a) foo bar", "label: foo bar", "throw foo bar", "do x while (y) z", "clas C {}", "cosnt x = 1", "varfoo bar", "is x", "module {}", "module 1", "type 1", "interface {}", "interface 1", "a.b c", "foo() bar", "(foo) bar", "foo! bar", "x = 1 y", "static foo", "a`b` c", ["js", "foo bar"]],
  "TS1260": ["\\u0076ar x = 1;", "x = tru\\u0065;", "x = \\u0076ar;", "\\u0065lse", "var \\u0076ar = 1;", "foo.\\u0076ar;", "\\u0061sync function f() {}", "l\\u0065t x = 1;", "\\u0074ype T = number;", "\\u0069nterface I {}", "n\\u0061mespace N {}", "d\\u0065clare const x: number;", "\\u0061bstract class C {}", "class C { st\\u0061tic x = 1 }", "class C { \\u0067et x() { return 1 } }", "class C \\u0065xtends D {}", "let x: \\u0073tring;", "let x: k\\u0065yof T;", "let x: \\u0074ypeof y;", "type T = \\u0076oid;", "x = y inst\\u0061nceof z;", "x = y \\u0069n z;", "x \\u0061s T;", "try {} c\\u0061tch {}", "switch (x) { c\\u0061se 1: }", "label: br\\u0065ak label;", "export d\\u0065fault 1;", "var \\u0061sync = 1;", "let \\u0074ype = 1;"],
};
for (const [name, list] of Object.entries(groups)) {
  console.log("// " + name);
  for (const e of list) {
    const [l, s] = typeof e === "string" ? ["ts", e] : e;
    const src = s.replace(/\\\\u/g, "\\u");
    const r = by.get(l + "\u0000" + src);
    const lit = 'b"' + src.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
    const loader = l === "js" ? "Js" : "Ts";
    if (!r) { console.log("// NOT PROBED " + lit); continue; }
    if (r.goOk) { console.log(`(${lit}, Loader::${loader}, parses),`); continue; }
    const m = /^@(\d+)\+(\d+) TS(\d+) (.*)$/.exec(r.go[0]);
    console.log(`(${lit}, Loader::${loader}, ${m[3]}, ${m[1]}, ${+m[1] + +m[2]}, ${JSON.stringify(m[4])}),`);
  }
}
