(Array<string>).name;
(fn1<string>).bind(obj);
(fn2<string, number>).bind(obj);
a[(Array<string>)];
a[(Array<string>).name];
(Array<string>).a;
(Array<string>)?.a;
(Array<string>)[a];
(Array<string>)?.[a];
(Array<string>)["a"];
(Array<string>)?.["a"];
(Array<string>)[`a`];
(Array<string>)?.[`a`];
(Array<string>)[(Array<string>)];
