const t = new Bun.Transpiler({ loader: "ts" });
const td = new Bun.Transpiler({ loader: "ts", tsconfig: JSON.stringify({ compilerOptions: { experimentalDecorators: true } }) });
const show = (label, src, tr = t) => { let out; try { out = tr.transformSync(src); } catch (e) { out = "ERROR: " + (e?.errors?.map(x => x.message).join(" | ") ?? e.message); } console.log(label.padEnd(60), JSON.stringify(out)); };
show("namespace a.b {}", "namespace a.b {}");
show("namespace as_ { export const a = 1 }", "namespace as_ { export const a = 1 }");
show("export namespace as_ { export const a = 1 }", "export namespace as_ { export const a = 1 }");
show("namespace a.b.c { export const a = 1 }", "namespace a.b.c { export const a = 1 }");
show("let type: any; type", "let type: any; type T = 1;");
show("function f() { type T = 1; return 1 as any }", "function f() { type T = 1; return 1 as any }");
show("function f() { interface I {} }", "function f() { interface I {} }");
show("{ type T = 1 }", "{ type T = 1 }");
show("class C {}", "class C { [k: string]: number; }");
show('enum E { "x" = 1 }', 'enum E { "x" = 1 }');
show('enum E { "x" }', 'enum E { "x" }');
show('enum E { "x" = 1, B = x }', 'enum E { "x" = 1, B = x }');
show('enum E { "x" = 1, B = E.x }', 'enum E { "x" = 1, B = E.x }');
show('enum E { "a-b" = 1, B = E["a-b"] }', 'enum E { "a-b" = 1, B = E["a-b"] }');
show('const enum E { "x" = 1 } var v = E.x;', 'const enum E { "x" = 1 } var v = E.x;');
show('export enum E { "x" = 1 }', 'export enum E { "x" = 1 }');
show('enum E { "x" = "s" }', 'enum E { "x" = "s" }');
show("(a as Foo) <= b;", "(a as Foo) <= b;");
show("var x = (a as Foo) <= b ? c : d;", "var x = (a as Foo) <= b ? c : d;");
show("while ((a as A) <= (b as B)) {}", "while ((a as A) <= (b as B)) {}");
show("var v = a ? (<T>(b)) : c => d;", "var v = a ? (<T>(b)) : c => d;");
show("var v = a ? b : c => d;", "var v = a ? b : c => d;");
show("var v = a ? async(b) : c => d;", "var v = a ? async(b) : c => d;");
show("var v = a ? x : c ? (<T>(d)) : e => f;", "var v = a ? x : c ? (<T>(d)) : e => f;");
show("class C implements I<T> {}", "class C implements I<T> {}");
show('namespace N { x("x"); }', 'namespace N { x("x"); }');
show('namespace N { (import("x")); }', 'namespace N { (import("x")); }');
show('namespace N { (import.meta); }', 'namespace N { (import.meta); }');
show('namespace N { import.meta.url; } today', 'namespace N { import.meta.url; }');
show("@d() class C {}", "@d() class C {}");
show("class C { @d() m() {} }", "class C { @d() m() {} }");
show("@d export default abstract class C {}", "@d export default abstract class C {}");
show("export default @d class C {}", "export default @d class C {}");
show("@d export default class C {}", "@d export default class C {}");
show("LEGACY @d export default abstract class C {}", "@d export default abstract class C {}", td);
show("LEGACY export default @d class C {}", "export default @d class C {}", td);
show("LEGACY @d export default class C {}", "@d export default class C {}", td);
show("STD class C { accessor a = 1 }", "class C { accessor a = 1 }");
show("STD class C { static accessor a = 1 }", "class C { static accessor a = 1 }");
show("STD abstract class C { abstract accessor a: number }", "abstract class C { abstract accessor a: number }");
show("STD declare class C { accessor a: number }", "declare class C { accessor a: number }");
show("STD class C { accessor #a = 1 }", "class C { accessor #a = 1 }");
show("abstract declare => declare abstract class C {}", "declare abstract class C {}");
show("export declare abstract class C {}", "export declare abstract class C {}");
show("if (x) type T = 1;", "if (x) type T = 1;");
show("label: type T = 1;", "label: type T = 1;");
show("export default interface I {}", "export default interface I {}");
