// One probe per line. The array length in the error of each line is the size (or the alignment) of the type.
use bun_ast as a;
use bun_js_parser as j;
const _: [(); 0] = [(); core::mem::size_of::<j::P<'static, true, false>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::P<'static, false, false>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::P<'static, true, true>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::P<'static, false, true>>()];
const _: [(); 0] = [(); core::mem::align_of::<j::P<'static, true, false>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::lexer::Lexer<'static>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::lexer::LexerSnapshot<'static>>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Msg>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Expr>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Stmt>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Binding>()];
const _: [(); 0] = [(); core::mem::size_of::<a::E::Arrow>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::Decl>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::Arg>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::Fn>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::Property>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::Class>()];
const _: [(); 0] = [(); core::mem::size_of::<a::G::FnBody>()];
const _: [(); 0] = [(); core::mem::size_of::<a::ts::Metadata>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Data>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Location>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Log>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Symbol>()];
const _: [(); 0] = [(); core::mem::size_of::<a::Scope>()];
const _: [(); 0] = [(); core::mem::size_of::<a::E::Function>()];
const _: [(); 0] = [(); core::mem::size_of::<a::E::Binary>()];
const _: [(); 0] = [(); core::mem::size_of::<j::p::StartsForParseOnly>()];
const _: [(); 0] = [(); core::mem::size_of::<Option<Box<j::p::StartsForParseOnly>>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::ParserOptions<'static>>()];
const _: [(); 0] = [(); core::mem::size_of::<j::Parser<'static>>()];
