const jsc = globalThis[Symbol.for("Bun.lazy")]("bun:jsc");

export const describe = jsc.describe;
export const describeArray = jsc.describeArray;
export const gcAndSweep = jsc.gcAndSweep;
export const fullGC = jsc.fullGC;
export const edenGC = jsc.edenGC;
export const heapSize = jsc.heapSize;
export const heapStats = jsc.heapStats;
export const memoryUsage = jsc.memoryUsage;
export const getRandomSeed = jsc.getRandomSeed;
export const setRandomSeed = jsc.setRandomSeed;
export const isRope = jsc.isRope;
export const callerSourceOrigin = jsc.callerSourceOrigin;
export const noFTL = jsc.noFTL;
export const noOSRExitFuzzing = jsc.noOSRExitFuzzing;
export const optimizeNextInvocation = jsc.optimizeNextInvocation;
export const numberOfDFGCompiles = jsc.numberOfDFGCompiles;
export const releaseWeakRefs = jsc.releaseWeakRefs;
export const totalCompileTime = jsc.totalCompileTime;
export const reoptimizationRetryCount = jsc.reoptimizationRetryCount;
export const drainMicrotasks = jsc.drainMicrotasks;
export default jsc;
