const H = "/tmp/conf-it-1b/td/test/cli/lint/conformance";
const { emptyCheck, replayCheck, resultLine, runInstance } = await import(`${H}/runner`);
const { tsgoRules } = await import(`${H}/runner/diagnosticwriter`);
const { getErrorBaseline } = await import(`${H}/runner/error_baseline`);
const { toWriterInput } = await import(`${H}/runner/shape`);
function baselineOf(units: any[], diagnostics: any[]): Uint8Array {
  const written = toWriterInput(tsgoRules, units, diagnostics);
  return tsgoRules.model.toBytes(getErrorBaseline(tsgoRules, written.files, written.diagnostics, false).text);
}
const unitInput = (unit: any) => (_i: any, _root: string | undefined) => ({ ok: true, input: { currentDirectory: "/.src", rootFiles: [unit.unitName], otherFiles: [], units: [unit], symlinks: [], options: {} } });
const unit = { unitName: "/.src/a.ts", content: 'const x: number = "s";\n' };
const known = { category: "error", code: 2322, messageText: "Type 'string' is not assignable to type 'number'.", location: { file: unit.unitName, start: 6, length: 1 }, relatedInformation: [] };
const printed = { file: unit.unitName, line: 1, character: 7 };
const options = { input: unitInput(unit), oracle: () => baselineOf([unit], [known]) };
const E = { name: "a.ts", status: "run", oracle: { class: "E" } };
const C = { name: "a.ts", status: "run", oracle: { class: "C" } };
const reports = (result: any) => async () => result;
const line = async (instance: any, check: any, more: any = {}) => JSON.stringify(resultLine(await runInstance(instance, check, { ...options, ...more })));
console.log(await line(E, replayCheck(options.oracle)));
console.log(await line(C, emptyCheck));
console.log(await line(E, emptyCheck));
console.log(await line(C, reports({ diagnostics: [known] })));
console.log(await line(C, reports({ diagnostics: [{ ...known, location: printed }] })));
console.log(await line(C, reports({ diagnostics: [{ ...known, location: undefined }] })));
console.log(await line(E, reports({ diagnostics: [{ ...known, location: { ...known.location, length: 5 } }] })));
console.log(await line(E, reports({ diagnostics: [{ ...known, location: printed }] })));
console.log(await line(E, reports({ diagnostics: [{ ...known, location: printed, messageText: "Other." }] })));
console.log(await line(E, reports({ diagnostics: [known, { ...known, code: 2323, messageText: "More.", location: { ...known.location, start: 18, length: 3 } }] })));
console.log(await line({ ...C, status: "skip", skipReason: "unsupported target ES5" }, emptyCheck));
console.log(await line({ ...C, status: "skip" }, emptyCheck));
console.log(await line(C, emptyCheck, { input: () => ({ ok: false, reason: "the instance has a drive root" }) }));
console.log(await line(C, reports({ diagnostics: [], unavailable: "the command is no linter" })));
console.log(await line(C, reports({ diagnostics: [], standIns: ["checker.getTypeOfExpression"] })));
console.log(await line(C, reports({ diagnostics: [{ ...known, code: -1 }] })));
console.log(await line(C, async () => { throw new Error("the command ended by the signal SIGSEGV"); }));
console.log(await line(E, emptyCheck, { oracle: () => { throw new Error("ENOENT"); } }));
console.log(await line(E, reports({ diagnostics: [known] }), { oracle: () => { throw new Error("ENOENT"); } }));
console.log(await line(E, emptyCheck, { oracle: () => new Uint8Array() }));
console.log(await line(C, reports({ diagnostics: [{ ...known, location: { file: unit.unitName, line: 99, character: 1 } }] })));
console.log(await line(C, async () => new Promise(() => {}), { timeoutMs: 50 }));
const long = "x".repeat(600);
console.log((await line(E, reports({ diagnostics: [{ ...known, messageText: long + "A" }] }), { oracle: () => baselineOf([unit], [{ ...known, messageText: long + "B" }]) })).length, await line(E, reports({ diagnostics: [{ ...known, messageText: long + "A" }] }), { oracle: () => baselineOf([unit], [{ ...known, messageText: long + "B" }]) }).then(s => s.slice(0, 12) + " ... " + s.slice(-70)));
const direct = (expected: string | undefined, actual: string | undefined, reason = "") => JSON.stringify(resultLine({ instance: E, outcome: "fail", reason, first: { line: 3, expected, actual } }));
const same = "x".repeat(700);
console.log(direct(same + "a" + "y".repeat(700), same + "b").length, direct(same + "a" + "y".repeat(700), same + "b").slice(0, 60));
console.log(direct("a\tb\x1b[0m\r \u2028\x85\x00\x7f", undefined));
console.log(direct(undefined, "z".repeat(501)).slice(-20));
console.log(direct("same", "same", "the baseline differs from the oracle at byte 9, line 3"));
console.log(JSON.stringify(resultLine({ instance: E, outcome: "crash", reason: "the check threw: Error: a\rb\x1b[31m\u2028c" })));
