// posix types live in `crate::posix` (moved from bun_sys).
pub use crate::posix::E;
pub use crate::posix::S;
pub use crate::posix::mode_t as Mode;

#[repr(u16)]
#[derive(
    Copy, Clone, Eq, PartialEq, Hash, Debug, strum::IntoStaticStr, strum::EnumString, enum_map::Enum,
)]
pub enum SystemErrno {
    SUCCESS = 0,
    EPERM = 1,
    ENOENT = 2,
    ESRCH = 3,
    EINTR = 4,
    EIO = 5,
    ENXIO = 6,
    E2BIG = 7,
    ENOEXEC = 8,
    EBADF = 9,
    ECHILD = 10,
    EDEADLK = 11,
    ENOMEM = 12,
    EACCES = 13,
    EFAULT = 14,
    ENOTBLK = 15,
    EBUSY = 16,
    EEXIST = 17,
    EXDEV = 18,
    ENODEV = 19,
    ENOTDIR = 20,
    EISDIR = 21,
    EINVAL = 22,
    ENFILE = 23,
    EMFILE = 24,
    ENOTTY = 25,
    ETXTBSY = 26,
    EFBIG = 27,
    ENOSPC = 28,
    ESPIPE = 29,
    EROFS = 30,
    EMLINK = 31,
    EPIPE = 32,
    EDOM = 33,
    ERANGE = 34,
    EAGAIN = 35,
    EINPROGRESS = 36,
    EALREADY = 37,
    ENOTSOCK = 38,
    EDESTADDRREQ = 39,
    EMSGSIZE = 40,
    EPROTOTYPE = 41,
    ENOPROTOOPT = 42,
    EPROTONOSUPPORT = 43,
    ESOCKTNOSUPPORT = 44,
    EOPNOTSUPP = 45,
    EPFNOSUPPORT = 46,
    EAFNOSUPPORT = 47,
    EADDRINUSE = 48,
    EADDRNOTAVAIL = 49,
    ENETDOWN = 50,
    ENETUNREACH = 51,
    ENETRESET = 52,
    ECONNABORTED = 53,
    ECONNRESET = 54,
    ENOBUFS = 55,
    EISCONN = 56,
    ENOTCONN = 57,
    ESHUTDOWN = 58,
    ETOOMANYREFS = 59,
    ETIMEDOUT = 60,
    ECONNREFUSED = 61,
    ELOOP = 62,
    ENAMETOOLONG = 63,
    EHOSTDOWN = 64,
    EHOSTUNREACH = 65,
    ENOTEMPTY = 66,
    EPROCLIM = 67,
    EUSERS = 68,
    EDQUOT = 69,
    ESTALE = 70,
    EREMOTE = 71,
    EBADRPC = 72,
    ERPCMISMATCH = 73,
    EPROGUNAVAIL = 74,
    EPROGMISMATCH = 75,
    EPROCUNAVAIL = 76,
    ENOLCK = 77,
    ENOSYS = 78,
    EFTYPE = 79,
    EAUTH = 80,
    ENEEDAUTH = 81,
    EIDRM = 82,
    ENOMSG = 83,
    EOVERFLOW = 84,
    ECANCELED = 85,
    EILSEQ = 86,
    ENOATTR = 87,
    EDOOFUS = 88,
    EBADMSG = 89,
    EMULTIHOP = 90,
    ENOLINK = 91,
    EPROTO = 92,
    ENOTCAPABLE = 93,
    ECAPMODE = 94,
    ENOTRECOVERABLE = 95,
    EOWNERDEAD = 96,
    EINTEGRITY = 97,
}

impl SystemErrno {
    pub const MAX: u16 = 98;

    /// On FreeBSD `ENOTSUP` is not a distinct errno; libc aliases it to
    /// `EOPNOTSUPP` (45). Provide the alias so cross-platform call sites that
    /// match `ENOTSUP` compile.
    pub const ENOTSUP: SystemErrno = SystemErrno::EOPNOTSUPP;
}

#[allow(non_upper_case_globals)]
pub mod uv_e {
    use super::SystemErrno;
    // libuv errno-space fallbacks for codes FreeBSD lacks natively. Values are
    // `-UV_E*` from libuv's <uv/errno.h> (see src/libuv_sys/libuv.zig:873-932).
    use bun_libuv_sys as libuv;
    // Zig `@"2BIG"` (raw ident starting with digit) — Rust idents prefixed `_`.
    crate::__decl_uv_e! {
        _2BIG          = SystemErrno::E2BIG as i32           => "E2BIG",
        ACCES          = SystemErrno::EACCES as i32          => "EACCES",
        ADDRINUSE      = SystemErrno::EADDRINUSE as i32      => "EADDRINUSE",
        ADDRNOTAVAIL   = SystemErrno::EADDRNOTAVAIL as i32   => "EADDRNOTAVAIL",
        AFNOSUPPORT    = SystemErrno::EAFNOSUPPORT as i32    => "EAFNOSUPPORT",
        AGAIN          = SystemErrno::EAGAIN as i32          => "EAGAIN",
        ALREADY        = SystemErrno::EALREADY as i32        => "EALREADY",
        BADF           = SystemErrno::EBADF as i32           => "EBADF",
        BUSY           = SystemErrno::EBUSY as i32           => "EBUSY",
        CANCELED       = SystemErrno::ECANCELED as i32       => "ECANCELED",
        CHARSET        = -libuv::UV_ECHARSET                 => "ECHARSET",
        CONNABORTED    = SystemErrno::ECONNABORTED as i32    => "ECONNABORTED",
        CONNREFUSED    = SystemErrno::ECONNREFUSED as i32    => "ECONNREFUSED",
        CONNRESET      = SystemErrno::ECONNRESET as i32      => "ECONNRESET",
        DESTADDRREQ    = SystemErrno::EDESTADDRREQ as i32    => "EDESTADDRREQ",
        EXIST          = SystemErrno::EEXIST as i32          => "EEXIST",
        FAULT          = SystemErrno::EFAULT as i32          => "EFAULT",
        HOSTUNREACH    = SystemErrno::EHOSTUNREACH as i32    => "EHOSTUNREACH",
        INTR           = SystemErrno::EINTR as i32           => "EINTR",
        INVAL          = SystemErrno::EINVAL as i32          => "EINVAL",
        IO             = SystemErrno::EIO as i32             => "EIO",
        ISCONN         = SystemErrno::EISCONN as i32         => "EISCONN",
        ISDIR          = SystemErrno::EISDIR as i32          => "EISDIR",
        LOOP           = SystemErrno::ELOOP as i32           => "ELOOP",
        MFILE          = SystemErrno::EMFILE as i32          => "EMFILE",
        MSGSIZE        = SystemErrno::EMSGSIZE as i32        => "EMSGSIZE",
        NAMETOOLONG    = SystemErrno::ENAMETOOLONG as i32    => "ENAMETOOLONG",
        NETDOWN        = SystemErrno::ENETDOWN as i32        => "ENETDOWN",
        NETUNREACH     = SystemErrno::ENETUNREACH as i32     => "ENETUNREACH",
        NFILE          = SystemErrno::ENFILE as i32          => "ENFILE",
        NOBUFS         = SystemErrno::ENOBUFS as i32         => "ENOBUFS",
        NODEV          = SystemErrno::ENODEV as i32          => "ENODEV",
        NOENT          = SystemErrno::ENOENT as i32          => "ENOENT",
        NOMEM          = SystemErrno::ENOMEM as i32          => "ENOMEM",
        NONET          = -libuv::UV_ENONET                   => "ENONET",
        NOSPC          = SystemErrno::ENOSPC as i32          => "ENOSPC",
        NOSYS          = SystemErrno::ENOSYS as i32          => "ENOSYS",
        NOTCONN        = SystemErrno::ENOTCONN as i32        => "ENOTCONN",
        NOTDIR         = SystemErrno::ENOTDIR as i32         => "ENOTDIR",
        NOTEMPTY       = SystemErrno::ENOTEMPTY as i32       => "ENOTEMPTY",
        NOTSOCK        = SystemErrno::ENOTSOCK as i32        => "ENOTSOCK",
        NOTSUP         = -libuv::UV_ENOTSUP                  => "ENOTSUP",
        PERM           = SystemErrno::EPERM as i32           => "EPERM",
        PIPE           = SystemErrno::EPIPE as i32           => "EPIPE",
        PROTO          = SystemErrno::EPROTO as i32          => "EPROTO",
        PROTONOSUPPORT = SystemErrno::EPROTONOSUPPORT as i32 => "EPROTONOSUPPORT",
        PROTOTYPE      = SystemErrno::EPROTOTYPE as i32      => "EPROTOTYPE",
        ROFS           = SystemErrno::EROFS as i32           => "EROFS",
        SHUTDOWN       = SystemErrno::ESHUTDOWN as i32       => "ESHUTDOWN",
        SPIPE          = SystemErrno::ESPIPE as i32          => "ESPIPE",
        SRCH           = SystemErrno::ESRCH as i32           => "ESRCH",
        TIMEDOUT       = SystemErrno::ETIMEDOUT as i32       => "ETIMEDOUT",
        TXTBSY         = SystemErrno::ETXTBSY as i32         => "ETXTBSY",
        XDEV           = SystemErrno::EXDEV as i32           => "EXDEV",
        FBIG           = SystemErrno::EFBIG as i32           => "EFBIG",
        NOPROTOOPT     = SystemErrno::ENOPROTOOPT as i32     => "ENOPROTOOPT",
        RANGE          = SystemErrno::ERANGE as i32          => "ERANGE",
        NXIO           = SystemErrno::ENXIO as i32           => "ENXIO",
        MLINK          = SystemErrno::EMLINK as i32          => "EMLINK",
        HOSTDOWN       = SystemErrno::EHOSTDOWN as i32       => "EHOSTDOWN",
        REMOTEIO       = -libuv::UV_EREMOTEIO                => "EREMOTEIO",
        NOTTY          = SystemErrno::ENOTTY as i32          => "ENOTTY",
        FTYPE          = SystemErrno::EFTYPE as i32          => "EFTYPE",
        ILSEQ          = SystemErrno::EILSEQ as i32          => "EILSEQ",
        OVERFLOW       = SystemErrno::EOVERFLOW as i32       => "EOVERFLOW",
        SOCKTNOSUPPORT = SystemErrno::ESOCKTNOSUPPORT as i32 => "ESOCKTNOSUPPORT",
        NODATA         = -libuv::UV_ENODATA                  => "ENODATA",
        UNATCH         = -libuv::UV_EUNATCH                  => "EUNATCH",
        NOEXEC         = SystemErrno::ENOEXEC as i32         => "ENOEXEC",
    }
}
pub use uv_e as UV_E;

use super::GetErrno;

// FreeBSD has no raw-syscall return convention (unlike Linux's `-errno` in
// `usize`); every kernel entry goes through libc, so all widths route to the
// thread-local `__error()` slot.
impl_get_errno_libc!(i32, u32, isize, usize, i64);

// ported from: src/errno/freebsd_errno.zig
