// Targeted inputs: [id, code]. Group is the id prefix.
// g: generic-call ambiguity. c: class member modifier words. s: contextual statement keywords.
// a: arrow return type after a parenthesis. j: JSX. x: TypeScript-only syntax in a JavaScript file. p: parentheses, comments, pragmas.
export const inputs = [
  ["g01", "a<b>(c)"],
  ["g02", "a < b > c"],
  ["g03", "a<b>\nc"],
  ["g04", "f(a<b,c>(d))"],
  ["g05", "a<b>`t`"],
  ["g06", "new a<b>(c)"],
  ["g07", "a<b<c>>(d)"],
  ["g08", "a < b > /re/.test(c)"],
  ["g09", "async<T>(x)"],
  ["g10", "a<b>>(c)"],
  ["g11", "a<<b>(c)>(d)"],
  ["g12", "a?.b<c>(d)"],
  ["g14", "a<b>=c"],
  ["g15", "a<b>>=c"],
  ["g16", "if (a < b && c > (d)) {}"],
  ["g17", "a < b, c > (d)"],
  ["g19", "a < b > -c"],
  ["g21", "a < b > [c]"],
  ["g22", "x = a < b > {}"],
  ["g24", "a<b>;"],
  ["g27", "a < typeof b > (c)"],
  ["g29", "a < this > (c)"],
  ["g30", "a < 's' > (c)"],
  ["g31", "a < 1 > (c)"],
  ["g32", "a < -1 > (c)"],
  ["g33", "a < [b] > (c)"],
  ["g33b", "a < {b} > (c)"],
  ["g34", "a < b | c > (d)"],
  ["g36", "a < b.c > (d)"],
  ["g37", "a < b[c] > (d)"],
  ["g39", "a < !b > (c)"],
  ["g42", "a < (b) > (c)"],
  ["g43", "a < b > (c) > (d)"],
  ["g44", "a?.<b>(c)"],
  ["g45", "class A extends B<C> {}"],
  ["g46", "a < b >\n(c)"],
  ["g47", "for (var i = 0; i < n > (0); i++) {}"],
  ["g48", "x = a<b>(c) ? d : e"],
  ["g49", "a<b>>>(c)"],
  ["g50", "a<b>\n.c"],

  ["c01", "class A { public\n x = 1 }"],
  ["c02", "class A { readonly\n *gen() {} }"],
  ["c03", "class A { declare\n x }"],
  ["c04", "class A { abstract\n x }"],
  ["c05", "class A { override\n ['x']() {} }"],
  ["c06", "class A { private\n #x = 1 }"],
  ["c07", "class A { protected\n 0 = 1 }"],
  ["c08", "class A { static\n x = 1 }"],
  ["c09", "class A { accessor\n x = 1 }"],
  ["c10", "class A { accessor x = 1 }"],
  ["c11", "class A { public = 1; readonly; override() {}; declare = 2; abstract() {} }"],
  ["c12", "class A { get\n x() { return 1 } }"],
  ["c13", "class A { async\n x() {} }"],
  ["c15", "class A { public\n static x = 1 }"],
  ["c16", "class A { readonly\n; x }"],
  ["c17", "class A { declare; static; accessor; abstract }"],
  ["c19", "(class implements {})"],
  ["c20", "class A { public\n 'x' = 1 }"],
  ["c21", "class A { static accessor x = 1 }"],
  ["c22", "class A { public x = 1 }"],
  ["c23", "class A { private\n get x() { return 1 } }"],
  ["c24", "class A { override\n static\n x = 1 }"],
  ["c25", "x = { public\n, readonly: 1, get declare() { return 1 }, async override() {}, static: 2 }"],

  ["s01", "type\nFoo = 1"],
  ["s03", "namespace\nfoo\n{}"],
  ["s04", "module\nfoo\n{}"],
  ["s05", "abstract\nclass A {}"],
  ["s06", "declare\nclass A {}"],
  ["s07", "interface\nFoo\n{}"],
  ["s08", "global\n{}"],
  ["s09", "declare\nglobal\n{}"],
  ["s10", "type = 1; type(1); type.x; type\n= 2"],
  ["s11", "namespace.x = 1; module.exports = 1; declare(x); abstract = 2"],
  ["s12", "module\n'x'"],
  ["s13", "type: for (;;) break type;"],
  ["s14", "declare: x; namespace: y; abstract: z; module: w; global: u;"],
  ["s18", "export default abstract\nclass A {}"],
  ["s19", "import type from 'x'; type;"],
  ["s20", "import type, { a } from 'x'; import typ, * as ns from 'y';"],
  ["s21", "import { type } from 'x'; import { type as t } from 'x'; import { type as as } from 'x';"],
  ["s22", "var type; export { type }; export { type as t };"],
  ["s24", "import { as } from 'x'; import { as as as2 } from 'x';"],
  ["s25", "export * as type from 'x'"],
  ["s29", "var as = 1, satisfies = 2, x, y; x\nas\ny; x\nsatisfies\ny"],
  ["s32", "var any, unknown, never, string, number, keyof, infer, is, asserts, readonly, unique, out, override, accessor, satisfies, type, declare, abstract, namespace, module, global;"],
  ["s33", "function f(readonly, override, declare, abstract, type, of, async) {}"],
  ["s34", "function f(public, private, protected, static, interface, implements, package) {}"],
  ["s35", "async\nfunction f() {}"],
  ["s36", "let async; async\nx => 1"],
  ["s37", "x = async y => 1; z = async (y) => 1; w = async(y)"],
  ["s38", "import { a } from 'x'; class a {}"],
  ["s39", "try {} catch (e) {} finally {}"],
  ["s40", "var x = 1; export { x as default }"],
  ["s41", "interface\n= 1"],
  ["s42", "enum = 1"],
  ["s43", "declare\nconst x = 1"],
  ["s44", "abstract\n(class {})"],

  ["a01", "a ? (b) : c => d"],
  ["a02", "a ? (b, c) : d"],
  ["a03", "a ? b ? (c) : d => e : f"],
  ["a04", "switch (x) { case (a): b => c; }"],
  ["a05", "a ? (b) : c => d ? e : f"],
  ["a06", "a ? (b = 1) : c => d"],
  ["a07", "a ? ({b}) : c => d"],
  ["a08", "a ? async (b) : c => d"],
  ["a10", "a ? (b) : (c) => d"],
  ["a12", "a ? (b) => c : d"],
  ["a14", "a ? (b) : c => (d) : e => f"],
  ["a15", "a ? b ? (c) : (d) => e : f"],
  ["a16", "a ? (b ? (c) : d => e) : f"],
  ["a19", "switch (x) { case (a): (b); }"],
  ["a21", "switch (x) { case (a): (b) => c; }"],
  ["a23", "x = { a: (b) }; y = a ? (b) : (c)"],
  ["a24", "a ? b ? (c) : d => (e) : f"],
  ["a25", "a ? (b) : c => { d } "],
  ["a26", "a ? b ? c : (d) : e => f"],
  ["a27", "switch (x) { case (a): async => c; }"],
  ["a28", "a ? b ? async (c) : d => e : f"],

  ["a30", "x ? y => ({ y }) : z => ({ z })"],
  ["a31", "a ? (b) => (c): d => e"],
  ["a32", "x ? y => (y) : z => z"],
  ["a33", "x ? () => (y) : z => z"],
  ["a34", "f(x ? y => (y) : z => z)"],
  ["a35", "x ? y => z => (w) : v => v"],
  ["a36", "x ? y => (y) : (z) => z"],
  ["a37", "x ? async y => (y) : z => z"],
  ["a40", "x ? [y => (y)] : z => z"],
  ["a41", "x ? y => (y, w) : z => z"],
  ["a42", "x ? y => (y) ? (w) : u => u : z => z"],
  ["a43", "x ? (y => (y)) : z => z"],
  ["a44", "switch (x) { case y => (y): z => z; }"],
  ["a45", "x ? y => (y) : z"],
  ["a46", "x ? y => { return (y) } : z => z"],

  ["j01", "const x = <div/>"],
  ["j02", "const x = <A extends b>y</A>"],
  ["j03", "const x = <A extends>y</A>"],
  ["j04", "const x = <A extends={1}>y</A>"],
  ["j05", "const x = <T,>(y) => y"],
  ["j06", "const x = <A b='1'>{/* c */}</A>"],
  ["j08", "const x = <div>{a<b>(c)}</div>"],
  ["j11", "const x = <T>y</T>"],
  ["j12", "const x = <div\n  // line\n  a='1' /* block */ />"],
  ["j14", "const x = <A<T> b='1' />"],
  ["j15", "f(<T>() => x</T>)"],
  ["j16", "const x = <T>y"],
  ["j17", "const x = <A const>y</A>"],
  ["j18", "const x = <const>y</const>"],
  ["j19", "const x = <A extends b='1'>y</A>"],

  ["x01", "let x: number = 1"],
  ["x02", "function f(a?: number): void {}"],
  ["x03", "interface I {}"],
  ["x04", "type T = number"],
  ["x05", "enum E { A }"],
  ["x06", "namespace N {}"],
  ["x06b", "module M {}"],
  ["x07", "declare const x"],
  ["x08", "x!"],
  ["x08b", "x as y"],
  ["x08c", "x satisfies y"],
  ["x09", "class A implements B {}"],
  ["x10", "class A<T> {}"],
  ["x10b", "function f<T>() {}"],
  ["x10c", "x = <T,>(y) => y"],
  ["x11", "class A { public x; private y() {}; readonly z; override u() {}; static s }"],
  ["x11b", "class A { abstract w; declare v }"],
  ["x12", "class A { constructor(public x) {} }"],
  ["x13", "import type { A } from 'x'"],
  ["x13b", "export type { A }"],
  ["x13c", "import { type A } from 'x'"],
  ["x13d", "var A; export { type A }"],
  ["x14", "import x = require('y')"],
  ["x14b", "export = x"],
  ["x14c", "export as namespace X"],
  ["x15", "function f(); function f() {}"],
  ["x16", "class A { m(); m() {} }"],
  ["x18", "class A extends B<T> {}"],
  ["x19", "function f(this: any) {}"],
  ["x21", "@dec class A {}"],
  ["x21b", "class A { @dec m() {} }"],
  ["x21c", "@dec export class A {}"],
  ["x21d", "export @dec class A {}"],
  ["x21e", "@dec export @dec2 class A {}"],
  ["x21f", "function f(@dec x) {}"],
  ["x22", "var v = function f<T>() {}"],
  ["x23", "try {} catch (e: any) {}"],
  ["x25", "abstract class A {}"],
  ["x27", "class A { x?: number; y!: string; m?() {} }"],
  ["x28", "const enum E {}"],
  ["x28b", "declare module 'm' {}"],
  ["x28c", "declare global {}"],
  ["x29", "export default interface I {}"],
  ["x31", "function f(a: number = 1, ...r: any[]) {}"],
  ["x32", "let f = (a: number): string => ''"],
  ["x33", "let g = async <T,>(a: T) => a"],
  ["x34", "let h = <T>y"],
  ["x35", "new A<T>()"],
  ["x36", "f<T>()"],
  ["x37", "let x = y as const"],
  ["x38", "class A { [k: string]: number }"],
  ["x39", "import { a } from 'x'; var a;"],
  ["x40", "var v: typeof import('y')"],

  ["x50", "let x!: number"],
  ["x51", "class A { declare x; static y; accessor z; async m() {} }"],
  ["x52", "declare function f(a: number): void"],
  ["x53", "function f(a?) {}"],
  ["x54", "var f = function (this: any, a) {}"],
  ["x55", "class A { get x(): number { return 1 } set x(v: number) {} }"],
  ["x56", "class A { constructor(); constructor(a: number) {} }"],
  ["x57", "export default class<T> {}"],
  ["x58", "var o = { m<T>() {}, get x(): number { return 1 } }"],
  ["x59", "const x = y!.z!()"],
  ["x61", "import type X from 'x'; import type * as N from 'y'; export type * from 'z'; export type * as M from 'w';"],
  ["x62", "export import a = b.c"],
  ["x63", "import a = b.c"],
  ["x64", "export declare const x: number; export abstract class A {}"],
  ["x65", "namespace A.B.C {}"],
  ["x66", "let x: number, y: string"],
  ["x67", "for (let i: number = 0;;) {}"],
  ["x69", "class A<in out T> {}"],
  ["x70", "function f(x): x is string { return true }"],
  ["x71", "@dec function f() {}"],
  ["x72", "@dec var x"],
  ["x73", "export @dec default class {}"],
  ["x74", "class A { @dec constructor() {} }"],
  ["x75", "a = b satisfies c as d"],
  ["x76", "enum E { A = 1, B }; declare enum F {}; const enum G {}"],
  ["x80", "abstract class A { abstract m(): void; abstract x: number }"],
  ["x82", "type A<T> = T"],
  ["x83", "interface I<T> extends J<T> { m<U>(): void }"],
  ["x84", "function f<const T>(x: T) {}"],
  ["x85", "class A { m<T>(this: A, ...a: T[]): a is any { return true } }"],
  ["x86", "var type; export { type as default }"],
  ["x87", "function f(this) {}"],
  ["x88", "let x!"],
  ["x89", "class A { static { } static x; static m() {} static async *g() {} }"],
  ["x90", "export default function <T>(a: T) {}"],
  ["x91", "class A extends B implements C, D {}"],
  ["x92", "x = function* <T>() {}; y = async function <T>() {}; z = async <T,>() => {}"],

  ["x93", "@x<y> class A {}"],
  ["x94", "@x<y>() class A {}"],
  ["x95", "@x! class A {}"],
  ["x96", "class A { @(a<b>(c)) m() {} }"],
  ["x97", "var a = b?.<c>(d)"],
  ["x98", "var a = <A<T> />"],

  ["p01", "// @ts-check\n/** @type {number} */\nvar x = /** @type {any} */ (y);"],
  ["p02", "// @ts-nocheck\nvar x = (1, 2);"],
  ["p03", "/// <reference path='a.d.ts' />\n/// <reference types='node' />\nvar x;"],
  ["p04", "#!/usr/bin/env node\n// @ts-check\nvar x = ((a)), y = (a) => (b), z = typeof (a), w = (a).b, v = (a, b);"],
  ["p05", "delete (a.b); (a) = 1; (a.b)++; [(a)] = b; ({ x: (a) } = b); for ((a) of b) ; (a)?.b; (a?.b).c; new (a.b()); (function(){})(); (() => 1)(); (a, b) => 1; async (a) => 1;"],
  ["p06", "if ((a)) (b); while ((a)) ; do ; while ((a)); for ((a); (b); (c)) ; switch ((a)) { case (b): } with ((a)) ; throw (a);"],
  ["p07", "x = a ? (b) : (c); y = `${(a)}`; z = [(a), ...(b)]; w = { ...(a), [(b)]: (c) }; f((a), ...(b)); new A((a));"],
  ["p08", "class A extends (B) { [(a)] = (b); static { (c); } } export default (a);"],
];
