// The rows of test/bundler/transpiler/typescript-grammar.test.ts: per group, [loader, source, expected] and one-line comments between them.
const accessor = (key, value, isStatic) => {
  const names = `{ __privateAdd as __privateAdd_jy12bb7f, __privateGet as __privateGet_t4v9rzz2, __privateSet as __privateSet_3ajc9ey2 }`;
  const s = isStatic ? "static " : "";
  const add = `__privateAdd_jy12bb7f(this, _${key}$1, ${value});`;
  const init = isStatic ? "" : `  constructor() {\n    ${add}\n  }\n`;
  const tail = isStatic ? `  static {\n    ${add}\n  }\n` : "";
  return (
    `import ${names} from "bun:wrap";\nvar _${key}$1;\n\nclass C {\n${init}  static {\n    _${key}$1 = new WeakMap;\n  }\n` +
    `  ${s}get ${key}() {\n    return __privateGet_t4v9rzz2(this, _${key}$1);\n  }\n  ${s}set ${key}(v) {\n    __privateSet_3ajc9ey2(this, _${key}$1, v);\n  }\n${tail}}\n`
  );
};
export const ACCESSOR_X = accessor("x", "undefined", false);
export const STATIC_ACCESSOR_X = accessor("x", "1", true);
const C = text => ({ comment: text });
export const groups = [
  ["type forms", [
    C("A reserved word is the name of a type reference."),
    ["ts", "let x: if;", "let x;\n"],
    ["ts", "let x: class;", "let x;\n"],
    ["ts", "let x: function;", "let x;\n"],
    ["ts", "let x: in;", "let x;\n"],
    ["ts", "let x: extends;", "let x;\n"],
    ["ts", "let x: super;", "let x;\n"],
    ["ts", "let x: delete;", "let x;\n"],
    ["ts", "let x: if.x;", "let x;\n"],
    ["ts", "let x: class<T>;", "let x;\n"],
    ["ts", "let x: | if;", "let x;\n"],
    ["ts", "let x: A | if;", "let x;\n"],
    ["ts", "let x: A & class;", "let x;\n"],
    ["ts", "let x: keyof if;", "let x;\n"],
    ["ts", "let x: (if);", "let x;\n"],
    ["ts", "let x: (class);", "let x;\n"],
    ["ts", "let x: `${if}`;", "let x;\n"],
    ["tsx", "let x: if;", "let x;\n"],
    C("A reserved word is the label of a rest element of a tuple."),
    ["ts", "type X = [...const: A[]];", ""],
    ["ts", "type X = [...in: A[]];", ""],
    ["ts", "type X = [...class: A[]];", ""],
    ["ts", "type X = [...if: A[]];", ""],
    C("An import type takes type arguments, and an expression as the value of an attribute."),
    ["ts", 'let x: typeof import("x")<C>;', "let x;\n"],
    ["ts", 'type X = typeof import("x")<C>;', ""],
    ["ts", 'let x: import("x")<T>;', "let x;\n"],
    ["ts", 'type X = import("x")<T>;', ""],
    ["ts", 'let x: import("x", { with: { a: "b" } })<T>;', "let x;\n"],
    ["ts", 'let x: import("x", { with: { a: "b" + "c" } });', "let x;\n"],
    ["ts", 'type X = import("x", { with: { a: "b" + "c" } });', ""],
    ["ts", 'let x: import("x").A.<T>;', "let x;\n"],
    ["ts", 'type X = import("x").A.<T>;', ""],
    C("The type of an assertion predicate starts on the line after its subject."),
    ["ts", "type X = (a) => asserts a\nis B;", ""],
    ["ts", "const f = (a): (a) => asserts a\nis B => 0;", "const f = (a) => 0;\n"],
    ["ts", "const f = (a): asserts a\nis B => 0;", "const f = (a) => 0;\n"],
    ["ts", "const f = (a): asserts this\nis B => 0;", "const f = (a) => 0;\n"],
    ["ts", "function f(): asserts this\nis B { throw 0 }", "function f() {\n  throw 0;\n}\n"],
  ]],
  ["object types", [
    C("A contextual keyword of an expression is the name of a type alias and of an interface."),
    ["ts", "type as = 1", ""],
    ["ts", "declare type as = 1", ""],
    ["ts", "type satisfies = 1", ""],
    ["ts", "interface as {}", ""],
    ["ts", "export interface as {}", ""],
    ["ts", "interface satisfies {}", ""],
    C("A parameter of a signature member has an initializer or a modifier."),
    ["ts", "type X = { a(b = 1): A };", ""],
    ["ts", "let x: { a(b = 1): A };", "let x;\n"],
    ["ts", "interface I { (a = 1): A }", ""],
    ["ts", "type X = { a(public b: B): A };", ""],
    C("An interface extends an expression."),
    ["ts", "interface I extends a() {}", ""],
    ["ts", "interface I extends a.b() {}", ""],
  ]],
  ["signatures, type parameters and type arguments", [
    C("A parameter of a function type has an initializer or a modifier."),
    ["ts", "let g: (a = 1) => void;", "let g;\n"],
    ["ts", "let x: ({ a = 1 }) => void;", "let x;\n"],
    ["ts", "let x: (public a: A) => void;", "let x;\n"],
    ["tsx", "let g: (a = 1) => void;", "let g;\n"],
    C("An array pattern of a signature has a hole."),
    ["ts", "let x: ([a, , b]) => void;", "let x;\n"],
    ["ts", "type X = ([a, , b]) => void;", ""],
    ["ts", "let x: new ([a, , b]) => A;", "let x;\n"],
    ["ts", "type X = { ([a, , b]): void };", ""],
    ["ts", "type X = { new ([a, , b]): A };", ""],
    C("A function type with such a parameter is a type argument."),
    ["ts", "let x: A<(a = 1) => void>;", "let x;\n"],
    ["ts", "type X = A<([a, , b]) => void>;", ""],
    ["ts", "class C extends B<(a = 1) => void> {}", "class C extends B {\n}\n"],
    C("A modifier before a parameter of a function that is no constructor is dropped."),
    ["ts", "function f(public a: A) {}", "function f(a) {}\n"],
    C("A comma follows the rest parameter of a signature of a declared class."),
    ["ts", "declare class C { m(...a,): void; }", ""],
    ["ts", "declare class C { constructor(...a,); }", ""],
    ["ts", "declare class C { m(...a: A[],): void; }", ""],
    ["ts", "declare class C { constructor(...a: A[],); }", ""],
    C("A type parameter of a function is named out."),
    ["ts", "function f<out>() {}", "function f() {}\n"],
    ["ts", "const f = function <out>() {};", "const f = function() {};\n"],
    ["ts", "function f<out = A>() {}", "function f() {}\n"],
    ["ts", "const f = function <out = A>() {};", "const f = function() {};\n"],
    ["ts", "function f<const out>() {}", "function f() {}\n"],
    ["ts", "const f = function <const out>() {};", "const f = function() {};\n"],
    ["ts", "const f = <out>(a): T => a;", "const f = (a) => a;\n"],
    ["ts", "const f = <out>(a: T) => a;", "const f = (a) => a;\n"],
    ["ts", "const f = <out = A>(a): T => a;", "const f = (a) => a;\n"],
    ["ts", "const f = <out = A>(a: T) => a;", "const f = (a) => a;\n"],
    ["ts", "const f = <const out>(a): T => a;", "const f = (a) => a;\n"],
    ["tsx", "const f = function g<out>() {};", "const f = function g() {};\n"],
    ["tsx", "async function f<out>() {}", "async function f() {}\n"],
    ["tsx", "const f = function g<out = A>() {};", "const f = function g() {};\n"],
    ["tsx", "async function f<const out>() {}", "async function f() {}\n"],
    ["tsx", "const f = <out = A>() => 0;", "const f = () => 0;\n"],
    ["tsx", "const f = async <out = A>() => 0;", "const f = async () => 0;\n"],
  ]],
  ["expressions", [
    C("The type of a type assertion is named out or is a reserved word."),
    ["ts", "const v = <out>x;", "const v = x;\n"],
    ["ts", "<out>x;", "x;\n"],
    ["ts", "const v = <out>(x);", "const v = x;\n"],
    ["ts", "const v = <in>x;", "const v = x;\n"],
    ["ts", "const v = <in>(x);", "const v = x;\n"],
    ["ts", "const v = <if>x;", "const v = x;\n"],
    ["ts", "const v = <class>x;", "const v = x;\n"],
    ["ts", "const v = <enum>x;", "const v = x;\n"],
    C("A type parameter of an arrow function is named out."),
    ["ts", "const v = <out>(x) => x;", "const v = (x) => x;\n"],
    ["ts", "const v = <out, T>(x) => x;", "const v = (x) => x;\n"],
    ["ts", "const v = <out = A>(x) => x;", "const v = (x) => x;\n"],
    ["tsx", "f(<out, T>(x) => x);", "f((x) => x);\n"],
    ["tsx", "f(<out = A>(x) => x);", "f((x) => x);\n"],
    C("The type after as, after satisfies and of a return is a reserved word."),
    ["ts", "const v = x as if;", "const v = x;\n"],
    ["ts", "const v = x as var;", "const v = x;\n"],
    ["ts", "const v = x satisfies if;", "const v = x;\n"],
    ["ts", "const v = (): if => x;", "const v = () => x;\n"],
    ["tsx", "x as if;", "x;\n"],
    ["tsx", "x as var;", "x;\n"],
    C("A comparison follows the type after as and satisfies."),
    ["ts", "const v = x as T <= y;", "const v = x <= y;\n"],
    ["ts", "x as T <= y;", "x <= y;\n"],
    ["ts", "const v = x satisfies T <= y;", "const v = x <= y;\n"],
    ["tsx", "f(x as T <= y);", "f(x <= y);\n"],
    ["tsx", "const v = [x as T <= y];", "const v = [x <= y];\n"],
    C("The colon of a conditional follows an operand or the body of an arrow function in parentheses."),
    ["ts", "x = a ? 1 + async(b) : c;", "x = a ? 1 + async(b) : c;\n"],
    ["ts", "x = a ? -<T>(b) : c;", "x = a ? -b : c;\n"],
    ["ts", "x = a ? <T>(b) : c => d;", "x = a ? b : (c) => d;\n"],
    ["ts", "x = a ? y => (b) : c => d;", "x = a ? (y) => b : (c) => d;\n"],
    ["ts", "x = a ? (y) => (b) : c => d;", "x = a ? (y) => b : (c) => d;\n"],
    ["ts", "x = a ? <T>(y: T) => (b) : c => d;", "x = a ? (y) => b : (c) => d;\n"],
    ["tsx", "x = a ? y => ({ y }) : z => ({ z });", "x = a ? (y) => ({ y }) : (z) => ({ z });\n"],
  ]],
  ["class members", [
    C("A comma ends an index signature."),
    ["ts", "class C { [k: string]: T, }", "class C {\n}\n"],
    ["ts", "abstract class C extends B { [k: string]: T, }", "class C extends B {\n}\n"],
    ["ts", "const c = class { [k: string]: T, };", "const c = class {\n};\n"],
    ["ts", "declare class C { [k: string]: T, }", ""],
    C("A modifier before a parameter of a method is dropped."),
    ["ts", "class C { m(public a: A) {} }", "class C {\n  m(a) {}\n}\n"],
    C("A class implements an expression."),
    ["ts", "class C implements a() {}", "class C {\n}\n"],
    C("With experimentalDecorators, accessor is a modifier in a class without decorators."),
    ["decorators", "class C { accessor x: T; }", ACCESSOR_X],
    ["decorators", "class C { static accessor x = 1; }", STATIC_ACCESSOR_X],
    ["decorators", "class C { accessor #x: T; }", "class C {\n  #x;\n}\n"],
    ["decorators", "class C { static accessor #x = 1; }", "class C {\n  static #x = 1;\n}\n"],
    ["decorators", "abstract class C extends B { abstract accessor x: T; }", "class C extends B {\n}\n"],
    ["decorators", "declare class C { accessor x: T; }", ""],
  ]],
  ["module syntax", [
    C("The attributes of an import start on the next line."),
    ["ts", 'import A from "x"\nwith { type: "json" };', 'import A from "x";\n'],
    C("A statement of a namespace starts with import and is no import."),
    ["ts", 'namespace N { import("x"); }', 'var N;\n((N) => {\n  import("x");\n})(N ||= {});\n'],
    ["ts", "namespace N { import.meta; }", "var N;\n((N) => {})(N ||= {});\n"],
    C("abstract stands before declare."),
    ["ts", "abstract declare class C {}", ""],
    ["ts", "export abstract declare class C {}", ""],
    C("The name of an enum member is a string in brackets."),
    ["ts", 'enum E { ["x"] }', 'var E;\n((E) => {\n  E[E["x"] = 0] = "x";\n})(E ||= {});\n'],
    ["ts", 'enum E { ["x"] = 1 }', 'var E;\n((E) => {\n  E[E["x"] = 1] = "x";\n})(E ||= {});\n'],
    ["ts", "enum E { ['x'] = 1, B = E.x }", 'var E;\n((E) => {\n  E[E["x"] = 1] = "x";\n  E[E["B"] = 1] = "B";\n})(E ||= {});\n'],
    ["ts", "enum E { [`x`] = 1 }", 'var E;\n((E) => {\n  E[E["x"] = 1] = "x";\n})(E ||= {});\n'],
    C("A contextual keyword of an expression is the name of a namespace."),
    ["ts", "namespace as {}", ""],
    ["ts", "declare namespace as {}", ""],
    ["ts", "namespace as { export const x = 1; }", "var as;\n((as) => {\n  as.x = 1;\n})(as ||= {});\n"],
    ["ts", "namespace as.b { export const x = 1; }", "var as;\n((as) => {\n  let b;\n  ((b) => {\n    b.x = 1;\n  })(b = as.b ||= {});\n})(as ||= {});\n"],
    ["ts", "namespace satisfies { export const x = 1; }", "var satisfies;\n((satisfies) => {\n  satisfies.x = 1;\n})(satisfies ||= {});\n"],
  ]],
];
const guard = name => {
  const parts = name.split(".");
  return parts.map((_, i) => `typeof ${parts.slice(0, i + 1).join(".")} === "undefined"`).join(" || ") + ` ? Object : ${name}`;
};
const prop = (type, tag) => [`class C { @d p: ${type}; }`, "type", tag];
const param = (type, tag) => [`class C { @d m(a: ${type}) {} }`, "paramtypes", `[${tag}]`];
const ret = (type, tag) => [`class C { @d m(): ${type} { throw 0 } }`, "returntype", tag];
export const metadata = [
  C("The operands of | and & are the check type of a conditional type."),
  prop("number | A extends B ? string : never", "String"),
  prop("K & A extends B ? string : never", "String"),
  prop("K | A extends B ? string[] : number[]", "Array"),
  prop("string | A extends B ? () => void : () => void", "Function"),
  prop("K | A extends B ? null : K", "Object"),
  param("number | A extends B ? string : string", "String"),
  ret("string & A extends B ? never : string", "String"),
  C("The operand of keyof, readonly and unique ends before extends."),
  prop("keyof A extends B ? string : never", "String"),
  prop("readonly A[] extends B ? string : number", "Object"),
  prop("unique symbol extends B ? string : never", "String"),
  param("keyof A extends B ? () => void : () => void", "Function"),
  ret("readonly A[] extends B ? unknown : string", "Object"),
  C("The type after the colon of a conditional type takes | and &."),
  prop("A extends B ? string : never | number", "Object"),
  prop("A extends B ? unknown : string & string", "Object"),
  C("A keyword before a dot is the first name of a type reference."),
  prop("any.b", guard("any.b")),
  prop("string.b", guard("string.b")),
  prop("bigint.b<T>", guard("bigint.b")),
  prop("undefined.b", "Object"),
  param("never.b", guard("never.b")),
  C("unique takes the whole type after it."),
  prop("unique symbol[]", "Object"),
  prop("unique [A]", "Object"),
  C("The branches of a conditional type merge as the operands of | do."),
  prop("X extends Y ? number : never", "Number"),
  prop("X extends Y ? K : K", "Object"),
  prop("X extends Y ? A : (A | null)", "Object"),
  prop("(X extends Y ? string : unknown)", "Object"),
  prop("X extends infer U extends V ? string : never", "String"),
  C("An operand of | and & counts as what it serializes to."),
  prop("string | (never | never)", "Object"),
  prop("(null | undefined) | string", "Object"),
  prop("A.B | C.D", "Object"),
  param("A.B & A.C", "Object"),
  C("An import type and unique symbol are Object."),
  prop("A | unique symbol", "Object"),
  prop('import("x") | A', "Object"),
  prop('import("x")["y"]', "Object"),
  C("A type predicate is Boolean and an assertion predicate is undefined."),
  prop("this is B", "Boolean"),
  ret("a is B", "Boolean"),
  ret("a is B | C", "Boolean"),
  ret("string is B", "Boolean"),
  ret("asserts a", "undefined"),
  ret("asserts a is B", "undefined"),
  ret("asserts this is B", "undefined"),
  ret("asserts a | B", "Object"),
  ret("A | asserts a", "Object"),
];
