// Types and the tag that the committed test typescript-grammar-decorator-metadata.test.ts expects for them.
export const ofProperty = [
  ["number | A extends B ? string : string", "String"],
  ["number | A extends B ? string : never", "String"],
  ["K & A extends B ? string : never", "String"],
  ["string & A extends B ? never : string", "String"],
  ["K | A extends B ? string[] : number[]", "Array"],
  ["string | A extends B ? () => void : () => void", "Function"],
  ["K | A extends B ? null : K", "Object"],
  ["keyof A extends B ? string : never", "String"],
  ["keyof A extends B ? () => void : () => void", "Function"],
  ["readonly A[] extends B ? string : number", "Object"],
  ["readonly A[] extends B ? unknown : string", "Object"],
  ["unique symbol extends B ? string : never", "String"],
  ["A extends B ? string : never | number", "Object"],
  ["A extends B ? never : string | number", "Object"],
  ["A extends B ? string : unknown | null", "Object"],
  ["A extends B ? unknown : string & string", "Object"],
  ["A extends B ? string : never & K", "Object"],
  ["any.b", 'typeof any === "undefined" || typeof any.b === "undefined" ? Object : any.b'],
  ["string.b", 'typeof string === "undefined" || typeof string.b === "undefined" ? Object : string.b'],
  ["never.b", 'typeof never === "undefined" || typeof never.b === "undefined" ? Object : never.b'],
  ["bigint.b<T>", 'typeof bigint === "undefined" || typeof bigint.b === "undefined" ? Object : bigint.b'],
  ["undefined.b", "Object"],
  ["unique symbol[]", "Object"],
  ["unique [A]", "Object"],
  ["X extends Y ? number : never", "Number"],
  ["X extends Y ? never : string & string", "String"],
  ["X extends Y ? string : never & string", "Object"],
  ["X extends Y ? K : K", "Object"],
  ["X extends Y ? never : A.B", "Object"],
  ["X extends Y ? A : (A | null)", "Object"],
  ["X extends Y ? A<B> : null", "Object"],
  ["(X extends Y ? string : unknown)", "Object"],
  ["X extends infer U extends V ? string : never", "String"],
  ["string | (never | never)", "Object"],
  ["string | never & string", "Object"],
  ["(null | undefined) | string", "Object"],
  ["string & (unknown & unknown)", "Object"],
  ["A.B | C.D", "Object"],
  ["A.B & A.C", "Object"],
  ["A | unique symbol", "Object"],
  ["unique symbol & A", "Object"],
  ['A | import("x")', "Object"],
  ['import("x") | A', "Object"],
  ['import("x")["y"]', "Object"],
  ["this is B", "Boolean"],
  ["this is this", "Boolean"],
];
export const ofReturnType = [
  ["a is B", "Boolean"],
  ["a is B | C", "Boolean"],
  ["a is B extends C ? D : E", "Boolean"],
  ["string is B", "Boolean"],
  ["this is B", "Boolean"],
  ["asserts a", "undefined"],
  ["asserts a is B", "undefined"],
  ["asserts this", "undefined"],
  ["asserts this is B", "undefined"],
  ["asserts a | B", "Object"],
  ["A | asserts a", "Object"],
];
