# Build and test Bun on macOS, Linux, and Windows.
# https://buildkite.com/docs/pipelines/defining-steps

steps:
  - key: "darwin-aarch64-build"
    label: ":darwin: aarch64"
    steps:
      - key: "darwin-aarch64-build-deps"
        label: ":darwin: aarch64 - build-deps"
        artifact_paths: "build/bun-deps/**/*"
        command: "./scripts/all-dependencies.sh"
        agents:
          queue: "build-darwin"
          os: "darwin"
          arch: "aarch64"
        env:
          CPU_TARGET: "native"
          CCACHE_DIR: "$$HOME/.cache/ccache"
          SCCACHE_DIR: "$$HOME/.cache/sccache"
          ZIG_LOCAL_CACHE_DIR: "$$HOME/.cache/zig-cache"
          BUN_DEPS_CACHE_DIR: "$$HOME/.cache/bun-deps"
      - key: "darwin-aarch64-build-zig"
        label: ":darwin: aarch64 - build-zig"
        artifact_paths:
          - "build/bun-zig.o"
        command:
          - "./scripts/build-bun-zig.sh"
          - "darwin"
          - "aarch64"
        agents:
          queue: "build-darwin"
          os: "darwin"
          arch: "aarch64"
        env:
          CPU_TARGET: "native"
          CCACHE_DIR: "$$HOME/.cache/ccache"
          SCCACHE_DIR: "$$HOME/.cache/sccache"
          ZIG_LOCAL_CACHE_DIR: "$$HOME/.cache/zig-cache"
          BUN_DEPS_CACHE_DIR: "$$HOME/.cache/bun-deps"
      - key: "darwin-aarch64-build-cpp"
        label: ":darwin: aarch64 - build-cpp"
        artifact_paths: "build/bun-cpp-objects.a"
        command: "./scripts/build-bun-cpp.sh --fast"
        agents:
          queue: "build-darwin"
          os: "darwin"
          arch: "aarch64"
        env:
          CPU_TARGET: "native"
          CCACHE_DIR: "$$HOME/.cache/ccache"
          SCCACHE_DIR: "$$HOME/.cache/sccache"
          ZIG_LOCAL_CACHE_DIR: "$$HOME/.cache/zig-cache"
          BUN_DEPS_CACHE_DIR: "$$HOME/.cache/bun-deps"
      - key: "darwin-aarch64-build-bun-nolto"
        label: ":darwin: aarch64 - build-bun (no-lto)"
        artifact_paths:
          - "darwin-aarch64-nolto.zip"
          - "darwin-aarch64-nolto-profile.zip"
        command: "./scripts/buildkite-link-bun.sh --tag darwin-aarch64 --fast"
        depends_on:
          - "darwin-aarch64-build-deps"
          - "darwin-aarch64-build-zig"
          - "darwin-aarch64-build-cpp"
        agents:
          queue: "build-darwin"
          os: "darwin"
          arch: "aarch64"
        env:
          CPU_TARGET: "native"
          CCACHE_DIR: "$$HOME/.cache/ccache"
          SCCACHE_DIR: "$$HOME/.cache/sccache"
          ZIG_LOCAL_CACHE_DIR: "$$HOME/.cache/zig-cache"
          BUN_DEPS_CACHE_DIR: "$$HOME/.cache/bun-deps"
      - key: "darwin-aarch64-build-bun"
        label: ":darwin: aarch64 - build-bun"
        artifact_paths:
          - "darwin-aarch64.zip"
          - "darwin-aarch64-profile.zip"
        command: "./scripts/buildkite-link-bun.sh --tag darwin-aarch64"
        depends_on:
          - "darwin-aarch64-build-bun-nolto"
        agents:
          queue: "build-darwin"
          os: "darwin"
          arch: "aarch64"
        env:
          CPU_TARGET: "native"
          CCACHE_DIR: "$$HOME/.cache/ccache"
          SCCACHE_DIR: "$$HOME/.cache/sccache"
          ZIG_LOCAL_CACHE_DIR: "$$HOME/.cache/zig-cache"
          BUN_DEPS_CACHE_DIR: "$$HOME/.cache/bun-deps"
