// Block-scalar conformance matrix.
//
// Each case below was validated by ≥3/4 consensus across eemeli/yaml (1.2.2),
// js-yaml (1.2), PyYAML (1.1), and ruamel.yaml (1.2). Inputs were drawn from a
// combinatorial generator (header × chomp × indicator × indent-boundary ×
// whitespace-position × context × EOL × EOF) plus an adversarial pass for
// unicode/mixed-EOL/nesting/pathological edges. The "oracle-split" group at
// the bottom covers inputs where the four reference parsers disagree (the
// spec is unambiguous; one or more refs deviate from it) and locks in the
// answer Bun derives from the spec, with the per-ref outputs in the comment
// column for context.

import { YAML } from "bun";
import { describe, expect, test } from "bun:test";

describe("block scalar conformance matrix", () => {
  describe("hdr", () => {
    test.each([
      ["hdr/|/basic", "- |\n x\n", ["x\n"]],
      ["hdr/|1/basic", "- |1\n x\n", ["x\n"]],
      ["hdr/|2/basic", "- |2\n  x\n", ["x\n"]],
      ["hdr/|3/basic", "- |3\n   x\n", ["x\n"]],
      ["hdr/|9/basic", "- |9\n         x\n", ["x\n"]],
      ["hdr/|-/basic", "- |-\n x\n", ["x"]],
      ["hdr/|1-/basic", "- |1-\n x\n", ["x"]],
      ["hdr/|-1/basic", "- |-1\n x\n", ["x"]],
      ["hdr/|-2/basic", "- |-2\n  x\n", ["x"]],
      ["hdr/|2-/basic", "- |2-\n  x\n", ["x"]],
      ["hdr/|-3/basic", "- |-3\n   x\n", ["x"]],
      ["hdr/|3-/basic", "- |3-\n   x\n", ["x"]],
      ["hdr/|9-/basic", "- |9-\n         x\n", ["x"]],
      ["hdr/|-9/basic", "- |-9\n         x\n", ["x"]],
      ["hdr/|+/basic", "- |+\n x\n", ["x\n"]],
      ["hdr/|1+/basic", "- |1+\n x\n", ["x\n"]],
      ["hdr/|+1/basic", "- |+1\n x\n", ["x\n"]],
      ["hdr/|2+/basic", "- |2+\n  x\n", ["x\n"]],
      ["hdr/|+2/basic", "- |+2\n  x\n", ["x\n"]],
      ["hdr/|+3/basic", "- |+3\n   x\n", ["x\n"]],
      ["hdr/|3+/basic", "- |3+\n   x\n", ["x\n"]],
      ["hdr/|9+/basic", "- |9+\n         x\n", ["x\n"]],
      ["hdr/|+9/basic", "- |+9\n         x\n", ["x\n"]],
      ["hdr/>/basic", "- >\n x\n", ["x\n"]],
      ["hdr/>1/basic", "- >1\n x\n", ["x\n"]],
      ["hdr/>2/basic", "- >2\n  x\n", ["x\n"]],
      ["hdr/>3/basic", "- >3\n   x\n", ["x\n"]],
      ["hdr/>9/basic", "- >9\n         x\n", ["x\n"]],
      ["hdr/>-/basic", "- >-\n x\n", ["x"]],
      ["hdr/>-1/basic", "- >-1\n x\n", ["x"]],
      ["hdr/>1-/basic", "- >1-\n x\n", ["x"]],
      ["hdr/>2-/basic", "- >2-\n  x\n", ["x"]],
      ["hdr/>-2/basic", "- >-2\n  x\n", ["x"]],
      ["hdr/>-3/basic", "- >-3\n   x\n", ["x"]],
      ["hdr/>3-/basic", "- >3-\n   x\n", ["x"]],
      ["hdr/>9-/basic", "- >9-\n         x\n", ["x"]],
      ["hdr/>-9/basic", "- >-9\n         x\n", ["x"]],
      ["hdr/>+/basic", "- >+\n x\n", ["x\n"]],
      ["hdr/>+1/basic", "- >+1\n x\n", ["x\n"]],
      ["hdr/>1+/basic", "- >1+\n x\n", ["x\n"]],
      ["hdr/>+2/basic", "- >+2\n  x\n", ["x\n"]],
      ["hdr/>2+/basic", "- >2+\n  x\n", ["x\n"]],
      ["hdr/>+3/basic", "- >+3\n   x\n", ["x\n"]],
      ["hdr/>3+/basic", "- >3+\n   x\n", ["x\n"]],
      ["hdr/>+9/basic", "- >+9\n         x\n", ["x\n"]],
      ["hdr/>9+/basic", "- >9+\n         x\n", ["x\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("boundary", () => {
    test.each([
      ["boundary/|1/at1+1", "- |1\n  x\n", [" x\n"]],
      ["boundary/|1/at1+2", "- |1\n   x\n", ["  x\n"]],
      ["boundary/|2/at2+1", "- |2\n   x\n", [" x\n"]],
      ["boundary/|2/at2+2", "- |2\n    x\n", ["  x\n"]],
      ["boundary/|3/at3+1", "- |3\n    x\n", [" x\n"]],
      ["boundary/|3/at3+2", "- |3\n     x\n", ["  x\n"]],
      ["boundary/|1-/at1+1", "- |1-\n  x\n", [" x"]],
      ["boundary/|1-/at1+2", "- |1-\n   x\n", ["  x"]],
      ["boundary/|2-/at2+1", "- |2-\n   x\n", [" x"]],
      ["boundary/|2-/at2+2", "- |2-\n    x\n", ["  x"]],
      ["boundary/|3-/at3+1", "- |3-\n    x\n", [" x"]],
      ["boundary/|3-/at3+2", "- |3-\n     x\n", ["  x"]],
      ["boundary/|1+/at1+1", "- |1+\n  x\n", [" x\n"]],
      ["boundary/|1+/at1+2", "- |1+\n   x\n", ["  x\n"]],
      ["boundary/|2+/at2+1", "- |2+\n   x\n", [" x\n"]],
      ["boundary/|2+/at2+2", "- |2+\n    x\n", ["  x\n"]],
      ["boundary/|3+/at3+1", "- |3+\n    x\n", [" x\n"]],
      ["boundary/|3+/at3+2", "- |3+\n     x\n", ["  x\n"]],
      ["boundary/>1/at1+1", "- >1\n  x\n", [" x\n"]],
      ["boundary/>1/at1+2", "- >1\n   x\n", ["  x\n"]],
      ["boundary/>2/at2+1", "- >2\n   x\n", [" x\n"]],
      ["boundary/>2/at2+2", "- >2\n    x\n", ["  x\n"]],
      ["boundary/>3/at3+1", "- >3\n    x\n", [" x\n"]],
      ["boundary/>3/at3+2", "- >3\n     x\n", ["  x\n"]],
      ["boundary/>1-/at1+1", "- >1-\n  x\n", [" x"]],
      ["boundary/>1-/at1+2", "- >1-\n   x\n", ["  x"]],
      ["boundary/>2-/at2+1", "- >2-\n   x\n", [" x"]],
      ["boundary/>2-/at2+2", "- >2-\n    x\n", ["  x"]],
      ["boundary/>3-/at3+1", "- >3-\n    x\n", [" x"]],
      ["boundary/>3-/at3+2", "- >3-\n     x\n", ["  x"]],
      ["boundary/>1+/at1+1", "- >1+\n  x\n", [" x\n"]],
      ["boundary/>1+/at1+2", "- >1+\n   x\n", ["  x\n"]],
      ["boundary/>2+/at2+1", "- >2+\n   x\n", [" x\n"]],
      ["boundary/>2+/at2+2", "- >2+\n    x\n", ["  x\n"]],
      ["boundary/>3+/at3+1", "- >3+\n    x\n", [" x\n"]],
      ["boundary/>3+/at3+2", "- >3+\n     x\n", ["  x\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("ws", () => {
    test.each([
      ["ws/|/lead/w0", "- |\n\n  text\n", ["\ntext\n"]],
      ["ws/|/trail/w0", "- |\n  text\n\n", ["text\n"]],
      ["ws/|/trail-eof/w0", "- |\n  text\n", ["text\n"]],
      ["ws/|/mid/w0", "- |\n  a\n\n  b\n", ["a\n\nb\n"]],
      ["ws/|/only/w0", "- |\n\n", [""]],
      ["ws/|/only-eof/w0", "- |\n", [""]],
      ["ws/|/only2/w0", "- |\n\n\n", [""]],
      ["ws/|/lead/w1", "- |\n \n  text\n", ["\ntext\n"]],
      ["ws/|/trail/w1", "- |\n  text\n \n", ["text\n"]],
      ["ws/|/trail-eof/w1", "- |\n  text\n ", ["text\n"]],
      ["ws/|/mid/w1", "- |\n  a\n \n  b\n", ["a\n\nb\n"]],
      ["ws/|/only/w1", "- |\n \n", [""]],
      ["ws/|/only-eof/w1", "- |\n ", [""]],
      ["ws/|/only2/w1", "- |\n \n \n", [""]],
      ["ws/|/lead/w2", "- |\n  \n  text\n", ["\ntext\n"]],
      ["ws/|/trail/w2", "- |\n  text\n  \n", ["text\n"]],
      ["ws/|/trail-eof/w2", "- |\n  text\n  ", ["text\n"]],
      ["ws/|/mid/w2", "- |\n  a\n  \n  b\n", ["a\n\nb\n"]],
      ["ws/|/only/w2", "- |\n  \n", [""]],
      ["ws/|/only-eof/w2", "- |\n  ", [""]],
      ["ws/|/only2/w2", "- |\n  \n  \n", [""]],
      ["ws/|/trail/w3", "- |\n  text\n   \n", ["text\n \n"]],
      ["ws/|/mid/w3", "- |\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/|/only/w3", "- |\n   \n", [""]],
      ["ws/|/only-eof/w3", "- |\n   ", [""]],
      ["ws/|/only2/w3", "- |\n   \n   \n", [""]],
      ["ws/|/trail/w4", "- |\n  text\n    \n", ["text\n  \n"]],
      ["ws/|/mid/w4", "- |\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/|/only/w4", "- |\n    \n", [""]],
      ["ws/|/only-eof/w4", "- |\n    ", [""]],
      ["ws/|/only2/w4", "- |\n    \n    \n", [""]],
      ["ws/|2/lead/w0", "- |2\n\n  text\n", ["\ntext\n"]],
      ["ws/|2/trail/w0", "- |2\n  text\n\n", ["text\n"]],
      ["ws/|2/trail-eof/w0", "- |2\n  text\n", ["text\n"]],
      ["ws/|2/mid/w0", "- |2\n  a\n\n  b\n", ["a\n\nb\n"]],
      ["ws/|2/only/w0", "- |2\n\n", [""]],
      ["ws/|2/only-eof/w0", "- |2\n", [""]],
      ["ws/|2/only2/w0", "- |2\n\n\n", [""]],
      ["ws/|2/lead/w1", "- |2\n \n  text\n", ["\ntext\n"]],
      ["ws/|2/trail/w1", "- |2\n  text\n \n", ["text\n"]],
      ["ws/|2/trail-eof/w1", "- |2\n  text\n ", ["text\n"]],
      ["ws/|2/mid/w1", "- |2\n  a\n \n  b\n", ["a\n\nb\n"]],
      ["ws/|2/only/w1", "- |2\n \n", [""]],
      ["ws/|2/only-eof/w1", "- |2\n ", [""]],
      ["ws/|2/only2/w1", "- |2\n \n \n", [""]],
      ["ws/|2/lead/w2", "- |2\n  \n  text\n", ["\ntext\n"]],
      ["ws/|2/trail/w2", "- |2\n  text\n  \n", ["text\n"]],
      ["ws/|2/trail-eof/w2", "- |2\n  text\n  ", ["text\n"]],
      ["ws/|2/mid/w2", "- |2\n  a\n  \n  b\n", ["a\n\nb\n"]],
      ["ws/|2/only/w2", "- |2\n  \n", [""]],
      ["ws/|2/only-eof/w2", "- |2\n  ", [""]],
      ["ws/|2/only2/w2", "- |2\n  \n  \n", [""]],
      ["ws/|2/lead/w3", "- |2\n   \n  text\n", [" \ntext\n"]],
      ["ws/|2/trail/w3", "- |2\n  text\n   \n", ["text\n \n"]],
      ["ws/|2/mid/w3", "- |2\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/|2/only/w3", "- |2\n   \n", [" \n"]],
      ["ws/|2/only2/w3", "- |2\n   \n   \n", [" \n \n"]],
      ["ws/|2/lead/w4", "- |2\n    \n  text\n", ["  \ntext\n"]],
      ["ws/|2/trail/w4", "- |2\n  text\n    \n", ["text\n  \n"]],
      ["ws/|2/mid/w4", "- |2\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/|2/only/w4", "- |2\n    \n", ["  \n"]],
      ["ws/|2/only2/w4", "- |2\n    \n    \n", ["  \n  \n"]],
      ["ws/|-/lead/w0", "- |-\n\n  text\n", ["\ntext"]],
      ["ws/|-/trail/w0", "- |-\n  text\n\n", ["text"]],
      ["ws/|-/trail-eof/w0", "- |-\n  text\n", ["text"]],
      ["ws/|-/mid/w0", "- |-\n  a\n\n  b\n", ["a\n\nb"]],
      ["ws/|-/only/w0", "- |-\n\n", [""]],
      ["ws/|-/only-eof/w0", "- |-\n", [""]],
      ["ws/|-/only2/w0", "- |-\n\n\n", [""]],
      ["ws/|-/lead/w1", "- |-\n \n  text\n", ["\ntext"]],
      ["ws/|-/trail/w1", "- |-\n  text\n \n", ["text"]],
      ["ws/|-/trail-eof/w1", "- |-\n  text\n ", ["text"]],
      ["ws/|-/mid/w1", "- |-\n  a\n \n  b\n", ["a\n\nb"]],
      ["ws/|-/only/w1", "- |-\n \n", [""]],
      ["ws/|-/only-eof/w1", "- |-\n ", [""]],
      ["ws/|-/only2/w1", "- |-\n \n \n", [""]],
      ["ws/|-/lead/w2", "- |-\n  \n  text\n", ["\ntext"]],
      ["ws/|-/trail/w2", "- |-\n  text\n  \n", ["text"]],
      ["ws/|-/trail-eof/w2", "- |-\n  text\n  ", ["text"]],
      ["ws/|-/mid/w2", "- |-\n  a\n  \n  b\n", ["a\n\nb"]],
      ["ws/|-/only/w2", "- |-\n  \n", [""]],
      ["ws/|-/only-eof/w2", "- |-\n  ", [""]],
      ["ws/|-/only2/w2", "- |-\n  \n  \n", [""]],
      ["ws/|-/trail/w3", "- |-\n  text\n   \n", ["text\n "]],
      ["ws/|-/trail-eof/w3", "- |-\n  text\n   ", ["text\n "]],
      ["ws/|-/mid/w3", "- |-\n  a\n   \n  b\n", ["a\n \nb"]],
      ["ws/|-/only/w3", "- |-\n   \n", [""]],
      ["ws/|-/only-eof/w3", "- |-\n   ", [""]],
      ["ws/|-/only2/w3", "- |-\n   \n   \n", [""]],
      ["ws/|-/trail/w4", "- |-\n  text\n    \n", ["text\n  "]],
      ["ws/|-/trail-eof/w4", "- |-\n  text\n    ", ["text\n  "]],
      ["ws/|-/mid/w4", "- |-\n  a\n    \n  b\n", ["a\n  \nb"]],
      ["ws/|-/only/w4", "- |-\n    \n", [""]],
      ["ws/|-/only-eof/w4", "- |-\n    ", [""]],
      ["ws/|-/only2/w4", "- |-\n    \n    \n", [""]],
      ["ws/|2-/lead/w0", "- |2-\n\n  text\n", ["\ntext"]],
      ["ws/|2-/trail/w0", "- |2-\n  text\n\n", ["text"]],
      ["ws/|2-/trail-eof/w0", "- |2-\n  text\n", ["text"]],
      ["ws/|2-/mid/w0", "- |2-\n  a\n\n  b\n", ["a\n\nb"]],
      ["ws/|2-/only/w0", "- |2-\n\n", [""]],
      ["ws/|2-/only-eof/w0", "- |2-\n", [""]],
      ["ws/|2-/only2/w0", "- |2-\n\n\n", [""]],
      ["ws/|2-/lead/w1", "- |2-\n \n  text\n", ["\ntext"]],
      ["ws/|2-/trail/w1", "- |2-\n  text\n \n", ["text"]],
      ["ws/|2-/trail-eof/w1", "- |2-\n  text\n ", ["text"]],
      ["ws/|2-/mid/w1", "- |2-\n  a\n \n  b\n", ["a\n\nb"]],
      ["ws/|2-/only/w1", "- |2-\n \n", [""]],
      ["ws/|2-/only-eof/w1", "- |2-\n ", [""]],
      ["ws/|2-/only2/w1", "- |2-\n \n \n", [""]],
      ["ws/|2-/lead/w2", "- |2-\n  \n  text\n", ["\ntext"]],
      ["ws/|2-/trail/w2", "- |2-\n  text\n  \n", ["text"]],
      ["ws/|2-/trail-eof/w2", "- |2-\n  text\n  ", ["text"]],
      ["ws/|2-/mid/w2", "- |2-\n  a\n  \n  b\n", ["a\n\nb"]],
      ["ws/|2-/only/w2", "- |2-\n  \n", [""]],
      ["ws/|2-/only-eof/w2", "- |2-\n  ", [""]],
      ["ws/|2-/only2/w2", "- |2-\n  \n  \n", [""]],
      ["ws/|2-/lead/w3", "- |2-\n   \n  text\n", [" \ntext"]],
      ["ws/|2-/trail/w3", "- |2-\n  text\n   \n", ["text\n "]],
      ["ws/|2-/trail-eof/w3", "- |2-\n  text\n   ", ["text\n "]],
      ["ws/|2-/mid/w3", "- |2-\n  a\n   \n  b\n", ["a\n \nb"]],
      ["ws/|2-/only/w3", "- |2-\n   \n", [" "]],
      ["ws/|2-/only-eof/w3", "- |2-\n   ", [" "]],
      ["ws/|2-/only2/w3", "- |2-\n   \n   \n", [" \n "]],
      ["ws/|2-/lead/w4", "- |2-\n    \n  text\n", ["  \ntext"]],
      ["ws/|2-/trail/w4", "- |2-\n  text\n    \n", ["text\n  "]],
      ["ws/|2-/trail-eof/w4", "- |2-\n  text\n    ", ["text\n  "]],
      ["ws/|2-/mid/w4", "- |2-\n  a\n    \n  b\n", ["a\n  \nb"]],
      ["ws/|2-/only/w4", "- |2-\n    \n", ["  "]],
      ["ws/|2-/only-eof/w4", "- |2-\n    ", ["  "]],
      ["ws/|2-/only2/w4", "- |2-\n    \n    \n", ["  \n  "]],
      ["ws/|+/lead/w0", "- |+\n\n  text\n", ["\ntext\n"]],
      ["ws/|+/trail/w0", "- |+\n  text\n\n", ["text\n\n"]],
      ["ws/|+/trail-eof/w0", "- |+\n  text\n", ["text\n"]],
      ["ws/|+/mid/w0", "- |+\n  a\n\n  b\n", ["a\n\nb\n"]],
      ["ws/|+/only/w0", "- |+\n\n", ["\n"]],
      ["ws/|+/only-eof/w0", "- |+\n", [""]],
      ["ws/|+/only2/w0", "- |+\n\n\n", ["\n\n"]],
      ["ws/|+/lead/w1", "- |+\n \n  text\n", ["\ntext\n"]],
      ["ws/|+/trail/w1", "- |+\n  text\n \n", ["text\n\n"]],
      ["ws/|+/trail-eof/w1", "- |+\n  text\n ", ["text\n"]],
      ["ws/|+/mid/w1", "- |+\n  a\n \n  b\n", ["a\n\nb\n"]],
      ["ws/|+/only/w1", "- |+\n \n", ["\n"]],
      ["ws/|+/only2/w1", "- |+\n \n \n", ["\n\n"]],
      ["ws/|+/lead/w2", "- |+\n  \n  text\n", ["\ntext\n"]],
      ["ws/|+/trail/w2", "- |+\n  text\n  \n", ["text\n\n"]],
      ["ws/|+/trail-eof/w2", "- |+\n  text\n  ", ["text\n"]],
      ["ws/|+/mid/w2", "- |+\n  a\n  \n  b\n", ["a\n\nb\n"]],
      ["ws/|+/only/w2", "- |+\n  \n", ["\n"]],
      ["ws/|+/only2/w2", "- |+\n  \n  \n", ["\n\n"]],
      ["ws/|+/trail/w3", "- |+\n  text\n   \n", ["text\n \n"]],
      ["ws/|+/mid/w3", "- |+\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/|+/only/w3", "- |+\n   \n", ["\n"]],
      ["ws/|+/only2/w3", "- |+\n   \n   \n", ["\n\n"]],
      ["ws/|+/trail/w4", "- |+\n  text\n    \n", ["text\n  \n"]],
      ["ws/|+/mid/w4", "- |+\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/|+/only/w4", "- |+\n    \n", ["\n"]],
      ["ws/|+/only2/w4", "- |+\n    \n    \n", ["\n\n"]],
      ["ws/|2+/lead/w0", "- |2+\n\n  text\n", ["\ntext\n"]],
      ["ws/|2+/trail/w0", "- |2+\n  text\n\n", ["text\n\n"]],
      ["ws/|2+/trail-eof/w0", "- |2+\n  text\n", ["text\n"]],
      ["ws/|2+/mid/w0", "- |2+\n  a\n\n  b\n", ["a\n\nb\n"]],
      ["ws/|2+/only/w0", "- |2+\n\n", ["\n"]],
      ["ws/|2+/only-eof/w0", "- |2+\n", [""]],
      ["ws/|2+/only2/w0", "- |2+\n\n\n", ["\n\n"]],
      ["ws/|2+/lead/w1", "- |2+\n \n  text\n", ["\ntext\n"]],
      ["ws/|2+/trail/w1", "- |2+\n  text\n \n", ["text\n\n"]],
      ["ws/|2+/trail-eof/w1", "- |2+\n  text\n ", ["text\n"]],
      ["ws/|2+/mid/w1", "- |2+\n  a\n \n  b\n", ["a\n\nb\n"]],
      ["ws/|2+/only/w1", "- |2+\n \n", ["\n"]],
      ["ws/|2+/only-eof/w1", "- |2+\n ", [""]],
      ["ws/|2+/only2/w1", "- |2+\n \n \n", ["\n\n"]],
      ["ws/|2+/lead/w2", "- |2+\n  \n  text\n", ["\ntext\n"]],
      ["ws/|2+/trail/w2", "- |2+\n  text\n  \n", ["text\n\n"]],
      ["ws/|2+/trail-eof/w2", "- |2+\n  text\n  ", ["text\n"]],
      ["ws/|2+/mid/w2", "- |2+\n  a\n  \n  b\n", ["a\n\nb\n"]],
      ["ws/|2+/only/w2", "- |2+\n  \n", ["\n"]],
      ["ws/|2+/only2/w2", "- |2+\n  \n  \n", ["\n\n"]],
      ["ws/|2+/lead/w3", "- |2+\n   \n  text\n", [" \ntext\n"]],
      ["ws/|2+/trail/w3", "- |2+\n  text\n   \n", ["text\n \n"]],
      ["ws/|2+/mid/w3", "- |2+\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/|2+/only/w3", "- |2+\n   \n", [" \n"]],
      ["ws/|2+/only2/w3", "- |2+\n   \n   \n", [" \n \n"]],
      ["ws/|2+/lead/w4", "- |2+\n    \n  text\n", ["  \ntext\n"]],
      ["ws/|2+/trail/w4", "- |2+\n  text\n    \n", ["text\n  \n"]],
      ["ws/|2+/mid/w4", "- |2+\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/|2+/only/w4", "- |2+\n    \n", ["  \n"]],
      ["ws/|2+/only2/w4", "- |2+\n    \n    \n", ["  \n  \n"]],
      ["ws/>/lead/w0", "- >\n\n  text\n", ["\ntext\n"]],
      ["ws/>/trail/w0", "- >\n  text\n\n", ["text\n"]],
      ["ws/>/trail-eof/w0", "- >\n  text\n", ["text\n"]],
      ["ws/>/mid/w0", "- >\n  a\n\n  b\n", ["a\nb\n"]],
      ["ws/>/only/w0", "- >\n\n", [""]],
      ["ws/>/only-eof/w0", "- >\n", [""]],
      ["ws/>/only2/w0", "- >\n\n\n", [""]],
      ["ws/>/lead/w1", "- >\n \n  text\n", ["\ntext\n"]],
      ["ws/>/trail/w1", "- >\n  text\n \n", ["text\n"]],
      ["ws/>/trail-eof/w1", "- >\n  text\n ", ["text\n"]],
      ["ws/>/mid/w1", "- >\n  a\n \n  b\n", ["a\nb\n"]],
      ["ws/>/only/w1", "- >\n \n", [""]],
      ["ws/>/only-eof/w1", "- >\n ", [""]],
      ["ws/>/only2/w1", "- >\n \n \n", [""]],
      ["ws/>/lead/w2", "- >\n  \n  text\n", ["\ntext\n"]],
      ["ws/>/trail/w2", "- >\n  text\n  \n", ["text\n"]],
      ["ws/>/trail-eof/w2", "- >\n  text\n  ", ["text\n"]],
      ["ws/>/mid/w2", "- >\n  a\n  \n  b\n", ["a\nb\n"]],
      ["ws/>/only/w2", "- >\n  \n", [""]],
      ["ws/>/only-eof/w2", "- >\n  ", [""]],
      ["ws/>/only2/w2", "- >\n  \n  \n", [""]],
      ["ws/>/trail/w3", "- >\n  text\n   \n", ["text\n \n"]],
      ["ws/>/mid/w3", "- >\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/>/only/w3", "- >\n   \n", [""]],
      ["ws/>/only-eof/w3", "- >\n   ", [""]],
      ["ws/>/only2/w3", "- >\n   \n   \n", [""]],
      ["ws/>/trail/w4", "- >\n  text\n    \n", ["text\n  \n"]],
      ["ws/>/mid/w4", "- >\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/>/only/w4", "- >\n    \n", [""]],
      ["ws/>/only-eof/w4", "- >\n    ", [""]],
      ["ws/>/only2/w4", "- >\n    \n    \n", [""]],
      ["ws/>2/lead/w0", "- >2\n\n  text\n", ["\ntext\n"]],
      ["ws/>2/trail/w0", "- >2\n  text\n\n", ["text\n"]],
      ["ws/>2/trail-eof/w0", "- >2\n  text\n", ["text\n"]],
      ["ws/>2/mid/w0", "- >2\n  a\n\n  b\n", ["a\nb\n"]],
      ["ws/>2/only/w0", "- >2\n\n", [""]],
      ["ws/>2/only-eof/w0", "- >2\n", [""]],
      ["ws/>2/only2/w0", "- >2\n\n\n", [""]],
      ["ws/>2/lead/w1", "- >2\n \n  text\n", ["\ntext\n"]],
      ["ws/>2/trail/w1", "- >2\n  text\n \n", ["text\n"]],
      ["ws/>2/trail-eof/w1", "- >2\n  text\n ", ["text\n"]],
      ["ws/>2/mid/w1", "- >2\n  a\n \n  b\n", ["a\nb\n"]],
      ["ws/>2/only/w1", "- >2\n \n", [""]],
      ["ws/>2/only-eof/w1", "- >2\n ", [""]],
      ["ws/>2/only2/w1", "- >2\n \n \n", [""]],
      ["ws/>2/lead/w2", "- >2\n  \n  text\n", ["\ntext\n"]],
      ["ws/>2/trail/w2", "- >2\n  text\n  \n", ["text\n"]],
      ["ws/>2/trail-eof/w2", "- >2\n  text\n  ", ["text\n"]],
      ["ws/>2/mid/w2", "- >2\n  a\n  \n  b\n", ["a\nb\n"]],
      ["ws/>2/only/w2", "- >2\n  \n", [""]],
      ["ws/>2/only-eof/w2", "- >2\n  ", [""]],
      ["ws/>2/only2/w2", "- >2\n  \n  \n", [""]],
      ["ws/>2/lead/w3", "- >2\n   \n  text\n", [" \ntext\n"]],
      ["ws/>2/trail/w3", "- >2\n  text\n   \n", ["text\n \n"]],
      ["ws/>2/mid/w3", "- >2\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/>2/only/w3", "- >2\n   \n", [" \n"]],
      ["ws/>2/only2/w3", "- >2\n   \n   \n", [" \n \n"]],
      ["ws/>2/lead/w4", "- >2\n    \n  text\n", ["  \ntext\n"]],
      ["ws/>2/trail/w4", "- >2\n  text\n    \n", ["text\n  \n"]],
      ["ws/>2/mid/w4", "- >2\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/>2/only/w4", "- >2\n    \n", ["  \n"]],
      ["ws/>2/only2/w4", "- >2\n    \n    \n", ["  \n  \n"]],
      ["ws/>-/lead/w0", "- >-\n\n  text\n", ["\ntext"]],
      ["ws/>-/trail/w0", "- >-\n  text\n\n", ["text"]],
      ["ws/>-/trail-eof/w0", "- >-\n  text\n", ["text"]],
      ["ws/>-/mid/w0", "- >-\n  a\n\n  b\n", ["a\nb"]],
      ["ws/>-/only/w0", "- >-\n\n", [""]],
      ["ws/>-/only-eof/w0", "- >-\n", [""]],
      ["ws/>-/only2/w0", "- >-\n\n\n", [""]],
      ["ws/>-/lead/w1", "- >-\n \n  text\n", ["\ntext"]],
      ["ws/>-/trail/w1", "- >-\n  text\n \n", ["text"]],
      ["ws/>-/trail-eof/w1", "- >-\n  text\n ", ["text"]],
      ["ws/>-/mid/w1", "- >-\n  a\n \n  b\n", ["a\nb"]],
      ["ws/>-/only/w1", "- >-\n \n", [""]],
      ["ws/>-/only-eof/w1", "- >-\n ", [""]],
      ["ws/>-/only2/w1", "- >-\n \n \n", [""]],
      ["ws/>-/lead/w2", "- >-\n  \n  text\n", ["\ntext"]],
      ["ws/>-/trail/w2", "- >-\n  text\n  \n", ["text"]],
      ["ws/>-/trail-eof/w2", "- >-\n  text\n  ", ["text"]],
      ["ws/>-/mid/w2", "- >-\n  a\n  \n  b\n", ["a\nb"]],
      ["ws/>-/only/w2", "- >-\n  \n", [""]],
      ["ws/>-/only-eof/w2", "- >-\n  ", [""]],
      ["ws/>-/only2/w2", "- >-\n  \n  \n", [""]],
      ["ws/>-/trail/w3", "- >-\n  text\n   \n", ["text\n "]],
      ["ws/>-/trail-eof/w3", "- >-\n  text\n   ", ["text\n "]],
      ["ws/>-/mid/w3", "- >-\n  a\n   \n  b\n", ["a\n \nb"]],
      ["ws/>-/only/w3", "- >-\n   \n", [""]],
      ["ws/>-/only-eof/w3", "- >-\n   ", [""]],
      ["ws/>-/only2/w3", "- >-\n   \n   \n", [""]],
      ["ws/>-/trail/w4", "- >-\n  text\n    \n", ["text\n  "]],
      ["ws/>-/trail-eof/w4", "- >-\n  text\n    ", ["text\n  "]],
      ["ws/>-/mid/w4", "- >-\n  a\n    \n  b\n", ["a\n  \nb"]],
      ["ws/>-/only/w4", "- >-\n    \n", [""]],
      ["ws/>-/only-eof/w4", "- >-\n    ", [""]],
      ["ws/>-/only2/w4", "- >-\n    \n    \n", [""]],
      ["ws/>2-/lead/w0", "- >2-\n\n  text\n", ["\ntext"]],
      ["ws/>2-/trail/w0", "- >2-\n  text\n\n", ["text"]],
      ["ws/>2-/trail-eof/w0", "- >2-\n  text\n", ["text"]],
      ["ws/>2-/mid/w0", "- >2-\n  a\n\n  b\n", ["a\nb"]],
      ["ws/>2-/only/w0", "- >2-\n\n", [""]],
      ["ws/>2-/only-eof/w0", "- >2-\n", [""]],
      ["ws/>2-/only2/w0", "- >2-\n\n\n", [""]],
      ["ws/>2-/lead/w1", "- >2-\n \n  text\n", ["\ntext"]],
      ["ws/>2-/trail/w1", "- >2-\n  text\n \n", ["text"]],
      ["ws/>2-/trail-eof/w1", "- >2-\n  text\n ", ["text"]],
      ["ws/>2-/mid/w1", "- >2-\n  a\n \n  b\n", ["a\nb"]],
      ["ws/>2-/only/w1", "- >2-\n \n", [""]],
      ["ws/>2-/only-eof/w1", "- >2-\n ", [""]],
      ["ws/>2-/only2/w1", "- >2-\n \n \n", [""]],
      ["ws/>2-/lead/w2", "- >2-\n  \n  text\n", ["\ntext"]],
      ["ws/>2-/trail/w2", "- >2-\n  text\n  \n", ["text"]],
      ["ws/>2-/trail-eof/w2", "- >2-\n  text\n  ", ["text"]],
      ["ws/>2-/mid/w2", "- >2-\n  a\n  \n  b\n", ["a\nb"]],
      ["ws/>2-/only/w2", "- >2-\n  \n", [""]],
      ["ws/>2-/only-eof/w2", "- >2-\n  ", [""]],
      ["ws/>2-/only2/w2", "- >2-\n  \n  \n", [""]],
      ["ws/>2-/lead/w3", "- >2-\n   \n  text\n", [" \ntext"]],
      ["ws/>2-/trail/w3", "- >2-\n  text\n   \n", ["text\n "]],
      ["ws/>2-/trail-eof/w3", "- >2-\n  text\n   ", ["text\n "]],
      ["ws/>2-/mid/w3", "- >2-\n  a\n   \n  b\n", ["a\n \nb"]],
      ["ws/>2-/only/w3", "- >2-\n   \n", [" "]],
      ["ws/>2-/only-eof/w3", "- >2-\n   ", [" "]],
      ["ws/>2-/only2/w3", "- >2-\n   \n   \n", [" \n "]],
      ["ws/>2-/lead/w4", "- >2-\n    \n  text\n", ["  \ntext"]],
      ["ws/>2-/trail/w4", "- >2-\n  text\n    \n", ["text\n  "]],
      ["ws/>2-/trail-eof/w4", "- >2-\n  text\n    ", ["text\n  "]],
      ["ws/>2-/mid/w4", "- >2-\n  a\n    \n  b\n", ["a\n  \nb"]],
      ["ws/>2-/only/w4", "- >2-\n    \n", ["  "]],
      ["ws/>2-/only-eof/w4", "- >2-\n    ", ["  "]],
      ["ws/>2-/only2/w4", "- >2-\n    \n    \n", ["  \n  "]],
      ["ws/>+/lead/w0", "- >+\n\n  text\n", ["\ntext\n"]],
      ["ws/>+/trail/w0", "- >+\n  text\n\n", ["text\n\n"]],
      ["ws/>+/trail-eof/w0", "- >+\n  text\n", ["text\n"]],
      ["ws/>+/mid/w0", "- >+\n  a\n\n  b\n", ["a\nb\n"]],
      ["ws/>+/only/w0", "- >+\n\n", ["\n"]],
      ["ws/>+/only-eof/w0", "- >+\n", [""]],
      ["ws/>+/only2/w0", "- >+\n\n\n", ["\n\n"]],
      ["ws/>+/lead/w1", "- >+\n \n  text\n", ["\ntext\n"]],
      ["ws/>+/trail/w1", "- >+\n  text\n \n", ["text\n\n"]],
      ["ws/>+/trail-eof/w1", "- >+\n  text\n ", ["text\n"]],
      ["ws/>+/mid/w1", "- >+\n  a\n \n  b\n", ["a\nb\n"]],
      ["ws/>+/only/w1", "- >+\n \n", ["\n"]],
      ["ws/>+/only2/w1", "- >+\n \n \n", ["\n\n"]],
      ["ws/>+/lead/w2", "- >+\n  \n  text\n", ["\ntext\n"]],
      ["ws/>+/trail/w2", "- >+\n  text\n  \n", ["text\n\n"]],
      ["ws/>+/trail-eof/w2", "- >+\n  text\n  ", ["text\n"]],
      ["ws/>+/mid/w2", "- >+\n  a\n  \n  b\n", ["a\nb\n"]],
      ["ws/>+/only/w2", "- >+\n  \n", ["\n"]],
      ["ws/>+/only2/w2", "- >+\n  \n  \n", ["\n\n"]],
      ["ws/>+/trail/w3", "- >+\n  text\n   \n", ["text\n \n"]],
      ["ws/>+/mid/w3", "- >+\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/>+/only/w3", "- >+\n   \n", ["\n"]],
      ["ws/>+/only2/w3", "- >+\n   \n   \n", ["\n\n"]],
      ["ws/>+/trail/w4", "- >+\n  text\n    \n", ["text\n  \n"]],
      ["ws/>+/mid/w4", "- >+\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/>+/only/w4", "- >+\n    \n", ["\n"]],
      ["ws/>+/only2/w4", "- >+\n    \n    \n", ["\n\n"]],
      ["ws/>2+/lead/w0", "- >2+\n\n  text\n", ["\ntext\n"]],
      ["ws/>2+/trail/w0", "- >2+\n  text\n\n", ["text\n\n"]],
      ["ws/>2+/trail-eof/w0", "- >2+\n  text\n", ["text\n"]],
      ["ws/>2+/mid/w0", "- >2+\n  a\n\n  b\n", ["a\nb\n"]],
      ["ws/>2+/only/w0", "- >2+\n\n", ["\n"]],
      ["ws/>2+/only-eof/w0", "- >2+\n", [""]],
      ["ws/>2+/only2/w0", "- >2+\n\n\n", ["\n\n"]],
      ["ws/>2+/lead/w1", "- >2+\n \n  text\n", ["\ntext\n"]],
      ["ws/>2+/trail/w1", "- >2+\n  text\n \n", ["text\n\n"]],
      ["ws/>2+/trail-eof/w1", "- >2+\n  text\n ", ["text\n"]],
      ["ws/>2+/mid/w1", "- >2+\n  a\n \n  b\n", ["a\nb\n"]],
      ["ws/>2+/only/w1", "- >2+\n \n", ["\n"]],
      ["ws/>2+/only-eof/w1", "- >2+\n ", [""]],
      ["ws/>2+/only2/w1", "- >2+\n \n \n", ["\n\n"]],
      ["ws/>2+/lead/w2", "- >2+\n  \n  text\n", ["\ntext\n"]],
      ["ws/>2+/trail/w2", "- >2+\n  text\n  \n", ["text\n\n"]],
      ["ws/>2+/trail-eof/w2", "- >2+\n  text\n  ", ["text\n"]],
      ["ws/>2+/mid/w2", "- >2+\n  a\n  \n  b\n", ["a\nb\n"]],
      ["ws/>2+/only/w2", "- >2+\n  \n", ["\n"]],
      ["ws/>2+/only2/w2", "- >2+\n  \n  \n", ["\n\n"]],
      ["ws/>2+/lead/w3", "- >2+\n   \n  text\n", [" \ntext\n"]],
      ["ws/>2+/trail/w3", "- >2+\n  text\n   \n", ["text\n \n"]],
      ["ws/>2+/mid/w3", "- >2+\n  a\n   \n  b\n", ["a\n \nb\n"]],
      ["ws/>2+/only/w3", "- >2+\n   \n", [" \n"]],
      ["ws/>2+/only2/w3", "- >2+\n   \n   \n", [" \n \n"]],
      ["ws/>2+/lead/w4", "- >2+\n    \n  text\n", ["  \ntext\n"]],
      ["ws/>2+/trail/w4", "- >2+\n  text\n    \n", ["text\n  \n"]],
      ["ws/>2+/mid/w4", "- >2+\n  a\n    \n  b\n", ["a\n  \nb\n"]],
      ["ws/>2+/only/w4", "- >2+\n    \n", ["  \n"]],
      ["ws/>2+/only2/w4", "- >2+\n    \n    \n", ["  \n  \n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("empties", () => {
    test.each([
      ["empties/|/L0T2", "- |\n  text\n\n\n", ["text\n"]],
      ["empties/|/L0T3", "- |\n  text\n\n\n\n", ["text\n"]],
      ["empties/|/L1T1", "- |\n\n  text\n\n", ["\ntext\n"]],
      ["empties/|/L1T2", "- |\n\n  text\n\n\n", ["\ntext\n"]],
      ["empties/|/L1T3", "- |\n\n  text\n\n\n\n", ["\ntext\n"]],
      ["empties/|/L2T0", "- |\n\n\n  text\n", ["\n\ntext\n"]],
      ["empties/|/L2T1", "- |\n\n\n  text\n\n", ["\n\ntext\n"]],
      ["empties/|/L2T2", "- |\n\n\n  text\n\n\n", ["\n\ntext\n"]],
      ["empties/|/L2T3", "- |\n\n\n  text\n\n\n\n", ["\n\ntext\n"]],
      ["empties/|/L3T0", "- |\n\n\n\n  text\n", ["\n\n\ntext\n"]],
      ["empties/|/L3T1", "- |\n\n\n\n  text\n\n", ["\n\n\ntext\n"]],
      ["empties/|/L3T2", "- |\n\n\n\n  text\n\n\n", ["\n\n\ntext\n"]],
      ["empties/|/L3T3", "- |\n\n\n\n  text\n\n\n\n", ["\n\n\ntext\n"]],
      ["empties/|/M0", "- |\n  a\n  b\n", ["a\nb\n"]],
      ["empties/|/M2", "- |\n  a\n\n\n  b\n", ["a\n\n\nb\n"]],
      ["empties/|/M3", "- |\n  a\n\n\n\n  b\n", ["a\n\n\n\nb\n"]],
      ["empties/|-/L0T2", "- |-\n  text\n\n\n", ["text"]],
      ["empties/|-/L0T3", "- |-\n  text\n\n\n\n", ["text"]],
      ["empties/|-/L1T1", "- |-\n\n  text\n\n", ["\ntext"]],
      ["empties/|-/L1T2", "- |-\n\n  text\n\n\n", ["\ntext"]],
      ["empties/|-/L1T3", "- |-\n\n  text\n\n\n\n", ["\ntext"]],
      ["empties/|-/L2T0", "- |-\n\n\n  text\n", ["\n\ntext"]],
      ["empties/|-/L2T1", "- |-\n\n\n  text\n\n", ["\n\ntext"]],
      ["empties/|-/L2T2", "- |-\n\n\n  text\n\n\n", ["\n\ntext"]],
      ["empties/|-/L2T3", "- |-\n\n\n  text\n\n\n\n", ["\n\ntext"]],
      ["empties/|-/L3T0", "- |-\n\n\n\n  text\n", ["\n\n\ntext"]],
      ["empties/|-/L3T1", "- |-\n\n\n\n  text\n\n", ["\n\n\ntext"]],
      ["empties/|-/L3T2", "- |-\n\n\n\n  text\n\n\n", ["\n\n\ntext"]],
      ["empties/|-/L3T3", "- |-\n\n\n\n  text\n\n\n\n", ["\n\n\ntext"]],
      ["empties/|-/M0", "- |-\n  a\n  b\n", ["a\nb"]],
      ["empties/|-/M2", "- |-\n  a\n\n\n  b\n", ["a\n\n\nb"]],
      ["empties/|-/M3", "- |-\n  a\n\n\n\n  b\n", ["a\n\n\n\nb"]],
      ["empties/|+/L0T2", "- |+\n  text\n\n\n", ["text\n\n\n"]],
      ["empties/|+/L0T3", "- |+\n  text\n\n\n\n", ["text\n\n\n\n"]],
      ["empties/|+/L1T1", "- |+\n\n  text\n\n", ["\ntext\n\n"]],
      ["empties/|+/L1T2", "- |+\n\n  text\n\n\n", ["\ntext\n\n\n"]],
      ["empties/|+/L1T3", "- |+\n\n  text\n\n\n\n", ["\ntext\n\n\n\n"]],
      ["empties/|+/L2T0", "- |+\n\n\n  text\n", ["\n\ntext\n"]],
      ["empties/|+/L2T1", "- |+\n\n\n  text\n\n", ["\n\ntext\n\n"]],
      ["empties/|+/L2T2", "- |+\n\n\n  text\n\n\n", ["\n\ntext\n\n\n"]],
      ["empties/|+/L2T3", "- |+\n\n\n  text\n\n\n\n", ["\n\ntext\n\n\n\n"]],
      ["empties/|+/L3T0", "- |+\n\n\n\n  text\n", ["\n\n\ntext\n"]],
      ["empties/|+/L3T1", "- |+\n\n\n\n  text\n\n", ["\n\n\ntext\n\n"]],
      ["empties/|+/L3T2", "- |+\n\n\n\n  text\n\n\n", ["\n\n\ntext\n\n\n"]],
      ["empties/|+/L3T3", "- |+\n\n\n\n  text\n\n\n\n", ["\n\n\ntext\n\n\n\n"]],
      ["empties/|+/M0", "- |+\n  a\n  b\n", ["a\nb\n"]],
      ["empties/|+/M2", "- |+\n  a\n\n\n  b\n", ["a\n\n\nb\n"]],
      ["empties/|+/M3", "- |+\n  a\n\n\n\n  b\n", ["a\n\n\n\nb\n"]],
      ["empties/>/L0T2", "- >\n  text\n\n\n", ["text\n"]],
      ["empties/>/L0T3", "- >\n  text\n\n\n\n", ["text\n"]],
      ["empties/>/L1T1", "- >\n\n  text\n\n", ["\ntext\n"]],
      ["empties/>/L1T2", "- >\n\n  text\n\n\n", ["\ntext\n"]],
      ["empties/>/L1T3", "- >\n\n  text\n\n\n\n", ["\ntext\n"]],
      ["empties/>/L2T0", "- >\n\n\n  text\n", ["\n\ntext\n"]],
      ["empties/>/L2T1", "- >\n\n\n  text\n\n", ["\n\ntext\n"]],
      ["empties/>/L2T2", "- >\n\n\n  text\n\n\n", ["\n\ntext\n"]],
      ["empties/>/L2T3", "- >\n\n\n  text\n\n\n\n", ["\n\ntext\n"]],
      ["empties/>/L3T0", "- >\n\n\n\n  text\n", ["\n\n\ntext\n"]],
      ["empties/>/L3T1", "- >\n\n\n\n  text\n\n", ["\n\n\ntext\n"]],
      ["empties/>/L3T2", "- >\n\n\n\n  text\n\n\n", ["\n\n\ntext\n"]],
      ["empties/>/L3T3", "- >\n\n\n\n  text\n\n\n\n", ["\n\n\ntext\n"]],
      ["empties/>/M0", "- >\n  a\n  b\n", ["a b\n"]],
      ["empties/>/M2", "- >\n  a\n\n\n  b\n", ["a\n\nb\n"]],
      ["empties/>/M3", "- >\n  a\n\n\n\n  b\n", ["a\n\n\nb\n"]],
      ["empties/>-/L0T2", "- >-\n  text\n\n\n", ["text"]],
      ["empties/>-/L0T3", "- >-\n  text\n\n\n\n", ["text"]],
      ["empties/>-/L1T1", "- >-\n\n  text\n\n", ["\ntext"]],
      ["empties/>-/L1T2", "- >-\n\n  text\n\n\n", ["\ntext"]],
      ["empties/>-/L1T3", "- >-\n\n  text\n\n\n\n", ["\ntext"]],
      ["empties/>-/L2T0", "- >-\n\n\n  text\n", ["\n\ntext"]],
      ["empties/>-/L2T1", "- >-\n\n\n  text\n\n", ["\n\ntext"]],
      ["empties/>-/L2T2", "- >-\n\n\n  text\n\n\n", ["\n\ntext"]],
      ["empties/>-/L2T3", "- >-\n\n\n  text\n\n\n\n", ["\n\ntext"]],
      ["empties/>-/L3T0", "- >-\n\n\n\n  text\n", ["\n\n\ntext"]],
      ["empties/>-/L3T1", "- >-\n\n\n\n  text\n\n", ["\n\n\ntext"]],
      ["empties/>-/L3T2", "- >-\n\n\n\n  text\n\n\n", ["\n\n\ntext"]],
      ["empties/>-/L3T3", "- >-\n\n\n\n  text\n\n\n\n", ["\n\n\ntext"]],
      ["empties/>-/M0", "- >-\n  a\n  b\n", ["a b"]],
      ["empties/>-/M2", "- >-\n  a\n\n\n  b\n", ["a\n\nb"]],
      ["empties/>-/M3", "- >-\n  a\n\n\n\n  b\n", ["a\n\n\nb"]],
      ["empties/>+/L0T2", "- >+\n  text\n\n\n", ["text\n\n\n"]],
      ["empties/>+/L0T3", "- >+\n  text\n\n\n\n", ["text\n\n\n\n"]],
      ["empties/>+/L1T1", "- >+\n\n  text\n\n", ["\ntext\n\n"]],
      ["empties/>+/L1T2", "- >+\n\n  text\n\n\n", ["\ntext\n\n\n"]],
      ["empties/>+/L1T3", "- >+\n\n  text\n\n\n\n", ["\ntext\n\n\n\n"]],
      ["empties/>+/L2T0", "- >+\n\n\n  text\n", ["\n\ntext\n"]],
      ["empties/>+/L2T1", "- >+\n\n\n  text\n\n", ["\n\ntext\n\n"]],
      ["empties/>+/L2T2", "- >+\n\n\n  text\n\n\n", ["\n\ntext\n\n\n"]],
      ["empties/>+/L2T3", "- >+\n\n\n  text\n\n\n\n", ["\n\ntext\n\n\n\n"]],
      ["empties/>+/L3T0", "- >+\n\n\n\n  text\n", ["\n\n\ntext\n"]],
      ["empties/>+/L3T1", "- >+\n\n\n\n  text\n\n", ["\n\n\ntext\n\n"]],
      ["empties/>+/L3T2", "- >+\n\n\n\n  text\n\n\n", ["\n\n\ntext\n\n\n"]],
      ["empties/>+/L3T3", "- >+\n\n\n\n  text\n\n\n\n", ["\n\n\ntext\n\n\n\n"]],
      ["empties/>+/M0", "- >+\n  a\n  b\n", ["a b\n"]],
      ["empties/>+/M2", "- >+\n  a\n\n\n  b\n", ["a\n\nb\n"]],
      ["empties/>+/M3", "- >+\n  a\n\n\n\n  b\n", ["a\n\n\nb\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("fold", () => {
    test.each([
      ["fold/>/n", "- >\n  a\n", ["a\n"]],
      ["fold/>/m", "- >\n    a\n", ["a\n"]],
      ["fold/>/nm", "- >\n  a\n    b\n", ["a\n  b\n"]],
      ["fold/>/mm", "- >\n    a\n    b\n", ["a b\n"]],
      ["fold/>/nmn", "- >\n  a\n    b\n  c\n", ["a\n  b\nc\n"]],
      ["fold/>/nnmmnn", "- >\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f\n"]],
      ["fold/>/n_m", "- >\n  a\n\n    b\n", ["a\n\n  b\n"]],
      ["fold/>/m_m", "- >\n    a\n\n    b\n", ["a\nb\n"]],
      ["fold/>/m__m", "- >\n    a\n\n\n    b\n", ["a\n\nb\n"]],
      ["fold/>/_n", "- >\n\n  a\n", ["\na\n"]],
      ["fold/>/_m", "- >\n\n    a\n", ["\na\n"]],
      ["fold/>2/n", "- >2\n  a\n", ["a\n"]],
      ["fold/>2/m", "- >2\n    a\n", ["  a\n"]],
      ["fold/>2/nn", "- >2\n  a\n  b\n", ["a b\n"]],
      ["fold/>2/nm", "- >2\n  a\n    b\n", ["a\n  b\n"]],
      ["fold/>2/mn", "- >2\n    a\n  b\n", ["  a\nb\n"]],
      ["fold/>2/mm", "- >2\n    a\n    b\n", ["  a\n  b\n"]],
      ["fold/>2/nmn", "- >2\n  a\n    b\n  c\n", ["a\n  b\nc\n"]],
      ["fold/>2/mnm", "- >2\n    a\n  b\n    c\n", ["  a\nb\n  c\n"]],
      ["fold/>2/nnmmnn", "- >2\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f\n"]],
      ["fold/>2/n_m", "- >2\n  a\n\n    b\n", ["a\n\n  b\n"]],
      ["fold/>2/m_n", "- >2\n    a\n\n  b\n", ["  a\n\nb\n"]],
      ["fold/>2/m_m", "- >2\n    a\n\n    b\n", ["  a\n\n  b\n"]],
      ["fold/>2/n__n", "- >2\n  a\n\n\n  b\n", ["a\n\nb\n"]],
      ["fold/>2/m__m", "- >2\n    a\n\n\n    b\n", ["  a\n\n\n  b\n"]],
      ["fold/>2/_n", "- >2\n\n  a\n", ["\na\n"]],
      ["fold/>2/_m", "- >2\n\n    a\n", ["\n  a\n"]],
      ["fold/>2/__m_n", "- >2\n\n\n    a\n\n  b\n", ["\n\n  a\n\nb\n"]],
      ["fold/>-/n", "- >-\n  a\n", ["a"]],
      ["fold/>-/m", "- >-\n    a\n", ["a"]],
      ["fold/>-/nm", "- >-\n  a\n    b\n", ["a\n  b"]],
      ["fold/>-/mm", "- >-\n    a\n    b\n", ["a b"]],
      ["fold/>-/nmn", "- >-\n  a\n    b\n  c\n", ["a\n  b\nc"]],
      ["fold/>-/nnmmnn", "- >-\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f"]],
      ["fold/>-/n_m", "- >-\n  a\n\n    b\n", ["a\n\n  b"]],
      ["fold/>-/m_m", "- >-\n    a\n\n    b\n", ["a\nb"]],
      ["fold/>-/m__m", "- >-\n    a\n\n\n    b\n", ["a\n\nb"]],
      ["fold/>-/_n", "- >-\n\n  a\n", ["\na"]],
      ["fold/>-/_m", "- >-\n\n    a\n", ["\na"]],
      ["fold/>2-/n", "- >2-\n  a\n", ["a"]],
      ["fold/>2-/m", "- >2-\n    a\n", ["  a"]],
      ["fold/>2-/nn", "- >2-\n  a\n  b\n", ["a b"]],
      ["fold/>2-/nm", "- >2-\n  a\n    b\n", ["a\n  b"]],
      ["fold/>2-/mn", "- >2-\n    a\n  b\n", ["  a\nb"]],
      ["fold/>2-/mm", "- >2-\n    a\n    b\n", ["  a\n  b"]],
      ["fold/>2-/nmn", "- >2-\n  a\n    b\n  c\n", ["a\n  b\nc"]],
      ["fold/>2-/mnm", "- >2-\n    a\n  b\n    c\n", ["  a\nb\n  c"]],
      ["fold/>2-/nnmmnn", "- >2-\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f"]],
      ["fold/>2-/n_m", "- >2-\n  a\n\n    b\n", ["a\n\n  b"]],
      ["fold/>2-/m_n", "- >2-\n    a\n\n  b\n", ["  a\n\nb"]],
      ["fold/>2-/m_m", "- >2-\n    a\n\n    b\n", ["  a\n\n  b"]],
      ["fold/>2-/n__n", "- >2-\n  a\n\n\n  b\n", ["a\n\nb"]],
      ["fold/>2-/m__m", "- >2-\n    a\n\n\n    b\n", ["  a\n\n\n  b"]],
      ["fold/>2-/_n", "- >2-\n\n  a\n", ["\na"]],
      ["fold/>2-/_m", "- >2-\n\n    a\n", ["\n  a"]],
      ["fold/>2-/__m_n", "- >2-\n\n\n    a\n\n  b\n", ["\n\n  a\n\nb"]],
      ["fold/>+/n", "- >+\n  a\n", ["a\n"]],
      ["fold/>+/m", "- >+\n    a\n", ["a\n"]],
      ["fold/>+/nm", "- >+\n  a\n    b\n", ["a\n  b\n"]],
      ["fold/>+/mm", "- >+\n    a\n    b\n", ["a b\n"]],
      ["fold/>+/nmn", "- >+\n  a\n    b\n  c\n", ["a\n  b\nc\n"]],
      ["fold/>+/nnmmnn", "- >+\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f\n"]],
      ["fold/>+/n_m", "- >+\n  a\n\n    b\n", ["a\n\n  b\n"]],
      ["fold/>+/m_m", "- >+\n    a\n\n    b\n", ["a\nb\n"]],
      ["fold/>+/m__m", "- >+\n    a\n\n\n    b\n", ["a\n\nb\n"]],
      ["fold/>+/_n", "- >+\n\n  a\n", ["\na\n"]],
      ["fold/>+/_m", "- >+\n\n    a\n", ["\na\n"]],
      ["fold/>2+/n", "- >2+\n  a\n", ["a\n"]],
      ["fold/>2+/m", "- >2+\n    a\n", ["  a\n"]],
      ["fold/>2+/nn", "- >2+\n  a\n  b\n", ["a b\n"]],
      ["fold/>2+/nm", "- >2+\n  a\n    b\n", ["a\n  b\n"]],
      ["fold/>2+/mn", "- >2+\n    a\n  b\n", ["  a\nb\n"]],
      ["fold/>2+/mm", "- >2+\n    a\n    b\n", ["  a\n  b\n"]],
      ["fold/>2+/nmn", "- >2+\n  a\n    b\n  c\n", ["a\n  b\nc\n"]],
      ["fold/>2+/mnm", "- >2+\n    a\n  b\n    c\n", ["  a\nb\n  c\n"]],
      ["fold/>2+/nnmmnn", "- >2+\n  a\n  b\n    c\n    d\n  e\n  f\n", ["a b\n  c\n  d\ne f\n"]],
      ["fold/>2+/n_m", "- >2+\n  a\n\n    b\n", ["a\n\n  b\n"]],
      ["fold/>2+/m_n", "- >2+\n    a\n\n  b\n", ["  a\n\nb\n"]],
      ["fold/>2+/m_m", "- >2+\n    a\n\n    b\n", ["  a\n\n  b\n"]],
      ["fold/>2+/n__n", "- >2+\n  a\n\n\n  b\n", ["a\n\nb\n"]],
      ["fold/>2+/m__m", "- >2+\n    a\n\n\n    b\n", ["  a\n\n\n  b\n"]],
      ["fold/>2+/_n", "- >2+\n\n  a\n", ["\na\n"]],
      ["fold/>2+/_m", "- >2+\n\n    a\n", ["\n  a\n"]],
      ["fold/>2+/__m_n", "- >2+\n\n\n    a\n\n  b\n", ["\n\n  a\n\nb\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("tab", () => {
    test.each([
      ["tab/|/after-ci", "- |\n  \ttext\n", ["\ttext\n"]],
      ["tab/|/mid-content", "- |\n  a\tb\n", ["a\tb\n"]],
      ["tab/|/line2", "- |\n  a\n  \tb\n", ["a\n\tb\n"]],
      ["tab/|-/after-ci", "- |-\n  \ttext\n", ["\ttext"]],
      ["tab/|-/mid-content", "- |-\n  a\tb\n", ["a\tb"]],
      ["tab/|-/line2", "- |-\n  a\n  \tb\n", ["a\n\tb"]],
      ["tab/|+/after-ci", "- |+\n  \ttext\n", ["\ttext\n"]],
      ["tab/|+/mid-content", "- |+\n  a\tb\n", ["a\tb\n"]],
      ["tab/|+/line2", "- |+\n  a\n  \tb\n", ["a\n\tb\n"]],
      ["tab/>/after-ci", "- >\n  \ttext\n", ["\ttext\n"]],
      ["tab/>/mid-content", "- >\n  a\tb\n", ["a\tb\n"]],
      ["tab/>/line2", "- >\n  a\n  \tb\n", ["a\n\tb\n"]],
      ["tab/>-/after-ci", "- >-\n  \ttext\n", ["\ttext"]],
      ["tab/>-/mid-content", "- >-\n  a\tb\n", ["a\tb"]],
      ["tab/>-/line2", "- >-\n  a\n  \tb\n", ["a\n\tb"]],
      ["tab/>+/after-ci", "- >+\n  \ttext\n", ["\ttext\n"]],
      ["tab/>+/mid-content", "- >+\n  a\tb\n", ["a\tb\n"]],
      ["tab/>+/line2", "- >+\n  a\n  \tb\n", ["a\n\tb\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("ctx", () => {
    test.each([
      ["ctx/root/|", "|\n text\n", "text\n"],
      ["ctx/root/|1", "|1\n text\n", "text\n"],
      ["ctx/root/|2", "|2\n  text\n", "text\n"],
      ["ctx/root/|-", "|-\n text\n", "text"],
      ["ctx/root/|1-", "|1-\n text\n", "text"],
      ["ctx/root/|2-", "|2-\n  text\n", "text"],
      ["ctx/root/|+", "|+\n text\n", "text\n"],
      ["ctx/root/|1+", "|1+\n text\n", "text\n"],
      ["ctx/root/|2+", "|2+\n  text\n", "text\n"],
      ["ctx/root/>", ">\n text\n", "text\n"],
      ["ctx/root/>1", ">1\n text\n", "text\n"],
      ["ctx/root/>2", ">2\n  text\n", "text\n"],
      ["ctx/root/>-", ">-\n text\n", "text"],
      ["ctx/root/>1-", ">1-\n text\n", "text"],
      ["ctx/root/>2-", ">2-\n  text\n", "text"],
      ["ctx/root/>+", ">+\n text\n", "text\n"],
      ["ctx/root/>1+", ">1+\n text\n", "text\n"],
      ["ctx/root/>2+", ">2+\n  text\n", "text\n"],
      ["ctx/seq0/|", "- |\n text\n", ["text\n"]],
      ["ctx/seq0/|1", "- |1\n  text\n", [" text\n"]],
      ["ctx/seq0/|2", "- |2\n   text\n", [" text\n"]],
      ["ctx/seq0/|-", "- |-\n text\n", ["text"]],
      ["ctx/seq0/|1-", "- |1-\n  text\n", [" text"]],
      ["ctx/seq0/|2-", "- |2-\n   text\n", [" text"]],
      ["ctx/seq0/|+", "- |+\n text\n", ["text\n"]],
      ["ctx/seq0/|1+", "- |1+\n  text\n", [" text\n"]],
      ["ctx/seq0/|2+", "- |2+\n   text\n", [" text\n"]],
      ["ctx/seq0/>", "- >\n text\n", ["text\n"]],
      ["ctx/seq0/>1", "- >1\n  text\n", [" text\n"]],
      ["ctx/seq0/>2", "- >2\n   text\n", [" text\n"]],
      ["ctx/seq0/>-", "- >-\n text\n", ["text"]],
      ["ctx/seq0/>1-", "- >1-\n  text\n", [" text"]],
      ["ctx/seq0/>2-", "- >2-\n   text\n", [" text"]],
      ["ctx/seq0/>+", "- >+\n text\n", ["text\n"]],
      ["ctx/seq0/>1+", "- >1+\n  text\n", [" text\n"]],
      ["ctx/seq0/>2+", "- >2+\n   text\n", [" text\n"]],
      ["ctx/seq0+sib/|", "- |\n text\n- sib\n", ["text\n", "sib"]],
      ["ctx/seq0+sib/|1", "- |1\n  text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/|2", "- |2\n   text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/|-", "- |-\n text\n- sib\n", ["text", "sib"]],
      ["ctx/seq0+sib/|1-", "- |1-\n  text\n- sib\n", [" text", "sib"]],
      ["ctx/seq0+sib/|2-", "- |2-\n   text\n- sib\n", [" text", "sib"]],
      ["ctx/seq0+sib/|+", "- |+\n text\n- sib\n", ["text\n", "sib"]],
      ["ctx/seq0+sib/|1+", "- |1+\n  text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/|2+", "- |2+\n   text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/>", "- >\n text\n- sib\n", ["text\n", "sib"]],
      ["ctx/seq0+sib/>1", "- >1\n  text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/>2", "- >2\n   text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/>-", "- >-\n text\n- sib\n", ["text", "sib"]],
      ["ctx/seq0+sib/>1-", "- >1-\n  text\n- sib\n", [" text", "sib"]],
      ["ctx/seq0+sib/>2-", "- >2-\n   text\n- sib\n", [" text", "sib"]],
      ["ctx/seq0+sib/>+", "- >+\n text\n- sib\n", ["text\n", "sib"]],
      ["ctx/seq0+sib/>1+", "- >1+\n  text\n- sib\n", [" text\n", "sib"]],
      ["ctx/seq0+sib/>2+", "- >2+\n   text\n- sib\n", [" text\n", "sib"]],
      ["ctx/map0/|", "k: |\n  text\n", { "k": "text\n" }],
      ["ctx/map0/|1", "k: |1\n   text\n", { "k": "  text\n" }],
      ["ctx/map0/|2", "k: |2\n    text\n", { "k": "  text\n" }],
      ["ctx/map0/|-", "k: |-\n  text\n", { "k": "text" }],
      ["ctx/map0/|1-", "k: |1-\n   text\n", { "k": "  text" }],
      ["ctx/map0/|2-", "k: |2-\n    text\n", { "k": "  text" }],
      ["ctx/map0/|+", "k: |+\n  text\n", { "k": "text\n" }],
      ["ctx/map0/|1+", "k: |1+\n   text\n", { "k": "  text\n" }],
      ["ctx/map0/|2+", "k: |2+\n    text\n", { "k": "  text\n" }],
      ["ctx/map0/>", "k: >\n  text\n", { "k": "text\n" }],
      ["ctx/map0/>1", "k: >1\n   text\n", { "k": "  text\n" }],
      ["ctx/map0/>2", "k: >2\n    text\n", { "k": "  text\n" }],
      ["ctx/map0/>-", "k: >-\n  text\n", { "k": "text" }],
      ["ctx/map0/>1-", "k: >1-\n   text\n", { "k": "  text" }],
      ["ctx/map0/>2-", "k: >2-\n    text\n", { "k": "  text" }],
      ["ctx/map0/>+", "k: >+\n  text\n", { "k": "text\n" }],
      ["ctx/map0/>1+", "k: >1+\n   text\n", { "k": "  text\n" }],
      ["ctx/map0/>2+", "k: >2+\n    text\n", { "k": "  text\n" }],
      ["ctx/map0+sib/|", "k: |\n  text\nz: 9\n", { "k": "text\n", "z": 9 }],
      ["ctx/map0+sib/|1", "k: |1\n   text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/|2", "k: |2\n    text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/|-", "k: |-\n  text\nz: 9\n", { "k": "text", "z": 9 }],
      ["ctx/map0+sib/|1-", "k: |1-\n   text\nz: 9\n", { "k": "  text", "z": 9 }],
      ["ctx/map0+sib/|2-", "k: |2-\n    text\nz: 9\n", { "k": "  text", "z": 9 }],
      ["ctx/map0+sib/|+", "k: |+\n  text\nz: 9\n", { "k": "text\n", "z": 9 }],
      ["ctx/map0+sib/|1+", "k: |1+\n   text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/|2+", "k: |2+\n    text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/>", "k: >\n  text\nz: 9\n", { "k": "text\n", "z": 9 }],
      ["ctx/map0+sib/>1", "k: >1\n   text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/>2", "k: >2\n    text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/>-", "k: >-\n  text\nz: 9\n", { "k": "text", "z": 9 }],
      ["ctx/map0+sib/>1-", "k: >1-\n   text\nz: 9\n", { "k": "  text", "z": 9 }],
      ["ctx/map0+sib/>2-", "k: >2-\n    text\nz: 9\n", { "k": "  text", "z": 9 }],
      ["ctx/map0+sib/>+", "k: >+\n  text\nz: 9\n", { "k": "text\n", "z": 9 }],
      ["ctx/map0+sib/>1+", "k: >1+\n   text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/map0+sib/>2+", "k: >2+\n    text\nz: 9\n", { "k": "  text\n", "z": 9 }],
      ["ctx/seq1/|", "-\n  - |\n   text\n", [["text\n"]]],
      ["ctx/seq1/|1", "-\n  - |1\n    text\n", [[" text\n"]]],
      ["ctx/seq1/|2", "-\n  - |2\n     text\n", [[" text\n"]]],
      ["ctx/seq1/|-", "-\n  - |-\n   text\n", [["text"]]],
      ["ctx/seq1/|1-", "-\n  - |1-\n    text\n", [[" text"]]],
      ["ctx/seq1/|2-", "-\n  - |2-\n     text\n", [[" text"]]],
      ["ctx/seq1/|+", "-\n  - |+\n   text\n", [["text\n"]]],
      ["ctx/seq1/|1+", "-\n  - |1+\n    text\n", [[" text\n"]]],
      ["ctx/seq1/|2+", "-\n  - |2+\n     text\n", [[" text\n"]]],
      ["ctx/seq1/>", "-\n  - >\n   text\n", [["text\n"]]],
      ["ctx/seq1/>1", "-\n  - >1\n    text\n", [[" text\n"]]],
      ["ctx/seq1/>2", "-\n  - >2\n     text\n", [[" text\n"]]],
      ["ctx/seq1/>-", "-\n  - >-\n   text\n", [["text"]]],
      ["ctx/seq1/>1-", "-\n  - >1-\n    text\n", [[" text"]]],
      ["ctx/seq1/>2-", "-\n  - >2-\n     text\n", [[" text"]]],
      ["ctx/seq1/>+", "-\n  - >+\n   text\n", [["text\n"]]],
      ["ctx/seq1/>1+", "-\n  - >1+\n    text\n", [[" text\n"]]],
      ["ctx/seq1/>2+", "-\n  - >2+\n     text\n", [[" text\n"]]],
      ["ctx/map1/|", "a:\n  k: |\n    text\n", { "a": { "k": "text\n" } }],
      ["ctx/map1/|1", "a:\n  k: |1\n     text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/|2", "a:\n  k: |2\n      text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/|-", "a:\n  k: |-\n    text\n", { "a": { "k": "text" } }],
      ["ctx/map1/|1-", "a:\n  k: |1-\n     text\n", { "a": { "k": "  text" } }],
      ["ctx/map1/|2-", "a:\n  k: |2-\n      text\n", { "a": { "k": "  text" } }],
      ["ctx/map1/|+", "a:\n  k: |+\n    text\n", { "a": { "k": "text\n" } }],
      ["ctx/map1/|1+", "a:\n  k: |1+\n     text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/|2+", "a:\n  k: |2+\n      text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/>", "a:\n  k: >\n    text\n", { "a": { "k": "text\n" } }],
      ["ctx/map1/>1", "a:\n  k: >1\n     text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/>2", "a:\n  k: >2\n      text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/>-", "a:\n  k: >-\n    text\n", { "a": { "k": "text" } }],
      ["ctx/map1/>1-", "a:\n  k: >1-\n     text\n", { "a": { "k": "  text" } }],
      ["ctx/map1/>2-", "a:\n  k: >2-\n      text\n", { "a": { "k": "  text" } }],
      ["ctx/map1/>+", "a:\n  k: >+\n    text\n", { "a": { "k": "text\n" } }],
      ["ctx/map1/>1+", "a:\n  k: >1+\n     text\n", { "a": { "k": "  text\n" } }],
      ["ctx/map1/>2+", "a:\n  k: >2+\n      text\n", { "a": { "k": "  text\n" } }],
      ["ctx/compact/|", "- - |\n   text\n", [["text\n"]]],
      ["ctx/compact/|1", "- - |1\n    text\n", [[" text\n"]]],
      ["ctx/compact/|2", "- - |2\n     text\n", [[" text\n"]]],
      ["ctx/compact/|-", "- - |-\n   text\n", [["text"]]],
      ["ctx/compact/|1-", "- - |1-\n    text\n", [[" text"]]],
      ["ctx/compact/|2-", "- - |2-\n     text\n", [[" text"]]],
      ["ctx/compact/|+", "- - |+\n   text\n", [["text\n"]]],
      ["ctx/compact/|1+", "- - |1+\n    text\n", [[" text\n"]]],
      ["ctx/compact/|2+", "- - |2+\n     text\n", [[" text\n"]]],
      ["ctx/compact/>", "- - >\n   text\n", [["text\n"]]],
      ["ctx/compact/>1", "- - >1\n    text\n", [[" text\n"]]],
      ["ctx/compact/>2", "- - >2\n     text\n", [[" text\n"]]],
      ["ctx/compact/>-", "- - >-\n   text\n", [["text"]]],
      ["ctx/compact/>1-", "- - >1-\n    text\n", [[" text"]]],
      ["ctx/compact/>2-", "- - >2-\n     text\n", [[" text"]]],
      ["ctx/compact/>+", "- - >+\n   text\n", [["text\n"]]],
      ["ctx/compact/>1+", "- - >1+\n    text\n", [[" text\n"]]],
      ["ctx/compact/>2+", "- - >2+\n     text\n", [[" text\n"]]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("eof", () => {
    test.each([
      ["eof/|/no-nl-after-hdr", "- |", [""]],
      ["eof/|2/no-nl-after-hdr", "- |2", [""]],
      ["eof/|-/no-nl-after-hdr", "- |-", [""]],
      ["eof/|-/content-no-nl", "- |-\n  text", ["text"]],
      ["eof/|2-/no-nl-after-hdr", "- |2-", [""]],
      ["eof/|2-/content-no-nl", "- |2-\n  text", ["text"]],
      ["eof/|+/no-nl-after-hdr", "- |+", [""]],
      ["eof/|2+/no-nl-after-hdr", "- |2+", [""]],
      ["eof/>/no-nl-after-hdr", "- >", [""]],
      ["eof/>2/no-nl-after-hdr", "- >2", [""]],
      ["eof/>-/no-nl-after-hdr", "- >-", [""]],
      ["eof/>-/content-no-nl", "- >-\n  text", ["text"]],
      ["eof/>2-/no-nl-after-hdr", "- >2-", [""]],
      ["eof/>2-/content-no-nl", "- >2-\n  text", ["text"]],
      ["eof/>+/no-nl-after-hdr", "- >+", [""]],
      ["eof/>2+/no-nl-after-hdr", "- >2+", [""]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("crlf", () => {
    test.each([
      ["crlf/|/10", "- |\r\n  a\r\n  b\r\n", ["a\nb\n"]],
      ["crlf/|/12", "- |\r\n  a\r\n\r\n  b\r\n", ["a\n\nb\n"]],
      ["crlf/|/7", "- |\r\n\r\n  a\r\n", ["\na\n"]],
      ["crlf/|-/10", "- |-\r\n  a\r\n  b\r\n", ["a\nb"]],
      ["crlf/|-/12", "- |-\r\n  a\r\n\r\n  b\r\n", ["a\n\nb"]],
      ["crlf/|-/7", "- |-\r\n\r\n  a\r\n", ["\na"]],
      ["crlf/|+/10", "- |+\r\n  a\r\n  b\r\n", ["a\nb\n"]],
      ["crlf/|+/12", "- |+\r\n  a\r\n\r\n  b\r\n", ["a\n\nb\n"]],
      ["crlf/|+/7", "- |+\r\n\r\n  a\r\n", ["\na\n"]],
      ["crlf/>/10", "- >\r\n  a\r\n  b\r\n", ["a b\n"]],
      ["crlf/>/12", "- >\r\n  a\r\n\r\n  b\r\n", ["a\nb\n"]],
      ["crlf/>/7", "- >\r\n\r\n  a\r\n", ["\na\n"]],
      ["crlf/>-/10", "- >-\r\n  a\r\n  b\r\n", ["a b"]],
      ["crlf/>-/12", "- >-\r\n  a\r\n\r\n  b\r\n", ["a\nb"]],
      ["crlf/>-/7", "- >-\r\n\r\n  a\r\n", ["\na"]],
      ["crlf/>+/10", "- >+\r\n  a\r\n  b\r\n", ["a b\n"]],
      ["crlf/>+/12", "- >+\r\n  a\r\n\r\n  b\r\n", ["a\nb\n"]],
      ["crlf/>+/7", "- >+\r\n\r\n  a\r\n", ["\na\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("special", () => {
    test.each([
      ["special/|/---", "- |\n  ---\n", ["---\n"]],
      ["special/|/...", "- |\n  ...\n", ["...\n"]],
      ["special/|/- x", "- |\n  - x\n", ["- x\n"]],
      ["special/|/: x", "- |\n  : x\n", [": x\n"]],
      ["special/|/? x", "- |\n  ? x\n", ["? x\n"]],
      ["special/|/# comm", "- |\n  # comment\n", ["# comment\n"]],
      ["special/|/|", "- |\n  |\n", ["|\n"]],
      ["special/|/>", "- |\n  >\n", [">\n"]],
      ['special/|/"q"', '- |\n  "q"\n', ['"q"\n']],
      ["special/|/'s'", "- |\n  's'\n", ["'s'\n"]],
      ["special/|/{a:1}", "- |\n  {a:1}\n", ["{a:1}\n"]],
      ["special/|/[1,2]", "- |\n  [1,2]\n", ["[1,2]\n"]],
      ["special/>/---", "- >\n  ---\n", ["---\n"]],
      ["special/>/...", "- >\n  ...\n", ["...\n"]],
      ["special/>/- x", "- >\n  - x\n", ["- x\n"]],
      ["special/>/: x", "- >\n  : x\n", [": x\n"]],
      ["special/>/? x", "- >\n  ? x\n", ["? x\n"]],
      ["special/>/# comm", "- >\n  # comment\n", ["# comment\n"]],
      ["special/>/|", "- >\n  |\n", ["|\n"]],
      ["special/>/>", "- >\n  >\n", [">\n"]],
      ['special/>/"q"', '- >\n  "q"\n', ['"q"\n']],
      ["special/>/'s'", "- >\n  's'\n", ["'s'\n"]],
      ["special/>/{a:1}", "- >\n  {a:1}\n", ["{a:1}\n"]],
      ["special/>/[1,2]", "- >\n  [1,2]\n", ["[1,2]\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("multi", () => {
    test.each([
      ["multi/|/f1s1", "- |\n a\n b\n", ["a\nb\n"]],
      ["multi/|/f1s2", "- |\n a\n  b\n", ["a\n b\n"]],
      ["multi/|/f1s3", "- |\n a\n   b\n", ["a\n  b\n"]],
      ["multi/|/f1s4", "- |\n a\n    b\n", ["a\n   b\n"]],
      ["multi/|/f1s5", "- |\n a\n     b\n", ["a\n    b\n"]],
      ["multi/|/f2s3", "- |\n  a\n   b\n", ["a\n b\n"]],
      ["multi/|/f2s4", "- |\n  a\n    b\n", ["a\n  b\n"]],
      ["multi/|/f2s5", "- |\n  a\n     b\n", ["a\n   b\n"]],
      ["multi/|/f4s4", "- |\n    a\n    b\n", ["a\nb\n"]],
      ["multi/|/f4s5", "- |\n    a\n     b\n", ["a\n b\n"]],
      ["multi/|-/f1s1", "- |-\n a\n b\n", ["a\nb"]],
      ["multi/|-/f1s2", "- |-\n a\n  b\n", ["a\n b"]],
      ["multi/|-/f1s3", "- |-\n a\n   b\n", ["a\n  b"]],
      ["multi/|-/f1s4", "- |-\n a\n    b\n", ["a\n   b"]],
      ["multi/|-/f1s5", "- |-\n a\n     b\n", ["a\n    b"]],
      ["multi/|-/f2s3", "- |-\n  a\n   b\n", ["a\n b"]],
      ["multi/|-/f2s4", "- |-\n  a\n    b\n", ["a\n  b"]],
      ["multi/|-/f2s5", "- |-\n  a\n     b\n", ["a\n   b"]],
      ["multi/|-/f4s4", "- |-\n    a\n    b\n", ["a\nb"]],
      ["multi/|-/f4s5", "- |-\n    a\n     b\n", ["a\n b"]],
      ["multi/|+/f1s1", "- |+\n a\n b\n", ["a\nb\n"]],
      ["multi/|+/f1s2", "- |+\n a\n  b\n", ["a\n b\n"]],
      ["multi/|+/f1s3", "- |+\n a\n   b\n", ["a\n  b\n"]],
      ["multi/|+/f1s4", "- |+\n a\n    b\n", ["a\n   b\n"]],
      ["multi/|+/f1s5", "- |+\n a\n     b\n", ["a\n    b\n"]],
      ["multi/|+/f2s3", "- |+\n  a\n   b\n", ["a\n b\n"]],
      ["multi/|+/f2s4", "- |+\n  a\n    b\n", ["a\n  b\n"]],
      ["multi/|+/f2s5", "- |+\n  a\n     b\n", ["a\n   b\n"]],
      ["multi/|+/f4s4", "- |+\n    a\n    b\n", ["a\nb\n"]],
      ["multi/|+/f4s5", "- |+\n    a\n     b\n", ["a\n b\n"]],
      ["multi/>/f1s1", "- >\n a\n b\n", ["a b\n"]],
      ["multi/>/f1s2", "- >\n a\n  b\n", ["a\n b\n"]],
      ["multi/>/f1s3", "- >\n a\n   b\n", ["a\n  b\n"]],
      ["multi/>/f1s4", "- >\n a\n    b\n", ["a\n   b\n"]],
      ["multi/>/f1s5", "- >\n a\n     b\n", ["a\n    b\n"]],
      ["multi/>/f2s3", "- >\n  a\n   b\n", ["a\n b\n"]],
      ["multi/>/f2s5", "- >\n  a\n     b\n", ["a\n   b\n"]],
      ["multi/>/f4s5", "- >\n    a\n     b\n", ["a\n b\n"]],
      ["multi/>-/f1s1", "- >-\n a\n b\n", ["a b"]],
      ["multi/>-/f1s2", "- >-\n a\n  b\n", ["a\n b"]],
      ["multi/>-/f1s3", "- >-\n a\n   b\n", ["a\n  b"]],
      ["multi/>-/f1s4", "- >-\n a\n    b\n", ["a\n   b"]],
      ["multi/>-/f1s5", "- >-\n a\n     b\n", ["a\n    b"]],
      ["multi/>-/f2s3", "- >-\n  a\n   b\n", ["a\n b"]],
      ["multi/>-/f2s5", "- >-\n  a\n     b\n", ["a\n   b"]],
      ["multi/>-/f4s5", "- >-\n    a\n     b\n", ["a\n b"]],
      ["multi/>+/f1s1", "- >+\n a\n b\n", ["a b\n"]],
      ["multi/>+/f1s2", "- >+\n a\n  b\n", ["a\n b\n"]],
      ["multi/>+/f1s3", "- >+\n a\n   b\n", ["a\n  b\n"]],
      ["multi/>+/f1s4", "- >+\n a\n    b\n", ["a\n   b\n"]],
      ["multi/>+/f1s5", "- >+\n a\n     b\n", ["a\n    b\n"]],
      ["multi/>+/f2s3", "- >+\n  a\n   b\n", ["a\n b\n"]],
      ["multi/>+/f2s5", "- >+\n  a\n     b\n", ["a\n   b\n"]],
      ["multi/>+/f4s5", "- >+\n    a\n     b\n", ["a\n b\n"]],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });

  describe("adv", () => {
    test.each([
      ["adv/unicode/bom-mid-content", "key: |\n  ab﻿cd\n", { "key": "ab﻿cd\n" }],
      ["adv/unicode/zwsp-after-indent", "key: |\n  ​hidden start\n", { "key": "​hidden start\n" }],
      ["adv/unicode/zwsp-splits-indent", "key: |\n ​ inner\n", { "key": "​ inner\n" }],
      ["adv/unicode/keep-chomp-zwsp-trailing", "key: |+\n  text\n  ​\n\n", { "key": "text\n​\n\n" }],
      ["adv/unicode/zwj-emoji-family", "key: |\n  👨‍👩‍👧‍👦\n  end\n", { "key": "👨‍👩‍👧‍👦\nend\n" }],
      ["adv/unicode/combining-after-indent", "key: |\n  ́orphan\n", { "key": "́orphan\n" }],
      ["adv/unicode/combining-before-fold", "key: >\n  café\n  noir\n", { "key": "café noir\n" }],
      ["adv/unicode/astral-content-multiline", "key: |\n  𐐷𝕳\n  x\n", { "key": "𐐷𝕳\nx\n" }],
      ["adv/unicode/cjk-multiline-indent", "key: |\n  日本語\n  中文\n", { "key": "日本語\n中文\n" }],
      ["adv/unicode/bidi-controls", "key: |\n  ‮desrever‬ normal\n", { "key": "‮desrever‬ normal\n" }],
      ["adv/unicode/rtl-hebrew-folded", "key: >\n  שלום\n  עולם\n", { "key": "שלום עולם\n" }],
      ["adv/mixed-eol/crlf-header-lf-body", "x: |\r\n  a\n  b\n", { "x": "a\nb\n" }],
      ["adv/mixed-eol/lf-header-crlf-body", "x: |\n  a\r\n  b\r\n", { "x": "a\nb\n" }],
      ["adv/mixed-eol/lone-cr-mid-body", "x: |\n  a\r  b\n", { "x": "a\nb\n" }],
      ["adv/mixed-eol/lone-cr-as-only-break", "x: |\r  hello\r  world\r", { "x": "hello\nworld\n" }],
      ["adv/mixed-eol/cr-at-eof-no-lf", "x: |\n  a\n  b\r", { "x": "a\nb\n" }],
      ["adv/mixed-eol/crlf-blank-line-keep", "x: |+\n  a\n\r\n\r\n", { "x": "a\n\n\n" }],
      ["adv/mixed-eol/crlf-blank-line-fold", "x: >\n  a\r\n\r\n  b\n", { "x": "a\nb\n" }],
      ["adv/mixed-eol/lf-cr-reversed-pair", "x: |\n  a\n\r  b\n", { "x": "a\n\nb\n" }],
      ["adv/mixed-eol/cr-only-blank-then-body", "x: |\r\r  text\n", { "x": "\ntext\n" }],
      ["adv/mixed-eol/mixed-every-line", "x: |\r\n  a\n  b\r  c\r\n  d\n", { "x": "a\nb\nc\nd\n" }],
      ["adv/mixed-eol/crlf-ws-only-line", "x: |\n  a\n  \r\n  b\n", { "x": "a\n\nb\n" }],
      ["adv/mixed-eol/cr-inside-more-indented-fold", "x: >\n  a\r\n    b\r    c\r\n  d\n", { "x": "a\n  b\n  c\nd\n" }],
      ["adv/mixed-eol/double-cr", "x: |\n  a\r\r  b\n", { "x": "a\n\nb\n" }],
      ["adv/mixed-eol/crlf-then-lone-cr-trailing-strip", "x: |-\n  a\r\n\r\n\r", { "x": "a" }],
      ["adv/mixed-eol/cr-splits-indent-indicator-line", "x: |2\r  ok\n", { "x": "ok\n" }],
      ["adv/mixed-eol/crlf-in-seq-compact", "- |\r\n  a\r\n- |\n  b\n", ["a\n", "b\n"]],
      ["adv/mixed-eol/lone-cr-at-eof-only", "x: |\n  a\r", { "x": "a\n" }],
      ["adv/mixed-eol/crlf-header-cr-body-lf-tail", "k: >\r\n  one\r  two\r\n  three\n", { "k": "one two three\n" }],
      ["adv/mixed-eol/cr-before-crlf", "x: |\n  a\r\r\n  b\n", { "x": "a\n\nb\n" }],
      ["adv/mixed-eol/header-comment-crlf", "x: | # comment\r\n  body\n", { "x": "body\n" }],
      [
        "adv/mixed-eol/nested-map-mixed-endings",
        "outer:\r\n  inner: |\n    line1\r\n    line2\n",
        { "outer": { "inner": "line1\nline2\n" } },
      ],
      ["adv/mixed-eol/fold-crlf-blank-runs", "x: >+\n  p1\r\n\r\n\r\n  p2\r\n\r\n", { "x": "p1\n\np2\n\n" }],
      ["adv/mixed-eol/bare-cr-eof-after-header", "x: |\r", { "x": "" }],
      ["adv/comments/hdr-hash-empty", "key: | #\n  text\n", { "key": "text\n" }],
      ["adv/comments/hdr-both-orders-comment", "a: |+2 # c1\n  x\nb: |2+ # c2\n  y\n", { "a": "x\n", "b": "y\n" }],
      ["adv/comments/hdr-comment-has-indicators", "key: | # |+2 >-9 fake\n  text\n", { "key": "text\n" }],
      ["adv/comments/hdr-comment-crlf", "key: | # cmt\r\n  text\r\n", { "key": "text\n" }],
      [
        "adv/comments/body-hash-at-indent",
        "key: |\n  text\n  # literal\nnext: v\n",
        { "key": "text\n# literal\n", "next": "v" },
      ],
      ["adv/comments/body-hash-autodetect", "key: |\n # first\n  more\n", { "key": "# first\n more\n" }],
      ["adv/comments/body-hash-inline", "key: |\n  text # not a comment\n", { "key": "text # not a comment\n" }],
      ["adv/comments/fold-hash-joins", "key: >\n  a\n  # b\n  c\n", { "key": "a # b c\n" }],
      ["adv/comments/fold-hash-more-indented", "key: >\n  a\n    # deep\n  b\n", { "key": "a\n  # deep\nb\n" }],
      ["adv/comments/fold-strip-hash-only", "key: >-\n  #\n  #\n", { "key": "# #" }],
      ["adv/comments/trail-hash-below-indent", "key: |\n  text\n # trail\nnext: v\n", { "key": "text\n", "next": "v" }],
      ["adv/comments/trail-only-empty-scalar", "key: |\n# c1\n# c2\nnext: v\n", { "key": "", "next": "v" }],
      [
        "adv/comments/trail-keep-preserves-empties",
        "key: |+\n  text\n\n\n# trail\nnext: v\n",
        { "key": "text\n\n\n", "next": "v" },
      ],
      [
        "adv/comments/trail-ws-at-content-indent",
        "key: |\n  text\n# c1\n  \n# c2\nnext: v\n",
        { "key": "text\n", "next": "v" },
      ],
      ["adv/comments/root-zero-indent-hash", "|\nline\n# still content\n", "line\n# still content\n"],
      [
        "adv/comments/nested-trail-mid-indent",
        "a:\n  b: |\n    text\n   # at3\n  c: v\n",
        { "a": { "b": "text\n", "c": "v" } },
      ],
      [
        "adv/comments/nested-trail-double-dedent",
        "a:\n  b: |\n    text\n# at0\nc: top\n",
        { "a": { "b": "text\n" }, "c": "top" },
      ],
      ["adv/comments/explicit-one-boundary", "key: |1\n #col1\n#col0\nnext: v\n", { "key": "#col1\n", "next": "v" }],
      ["adv/anchor-tag/anchor-tag-literal", "key: &a !!str |\n  hello\n  world\n", { "key": "hello\nworld\n" }],
      ["adv/anchor-tag/tag-anchor-reversed", "key: !!str &a |\n  hello\n  world\n", { "key": "hello\nworld\n" }],
      ["adv/anchor-tag/full-combo-indent-strip", "key: &a !!str |2-\n  hi\n  there\n\n\n", { "key": "hi\nthere" }],
      ["adv/anchor-tag/full-combo-folded-chomp-first", "key: !!str &a >-2\n  one\n  two\n\n", { "key": "one two" }],
      ["adv/anchor-tag/anchor-keep-indent9", "key: &a >+9\n         deep\n\n\n", { "key": "deep\n\n\n" }],
      [
        "adv/anchor-tag/anchor-literal-then-alias",
        "a: &x |\n  shared\n  text\nb: *x\n",
        { "a": "shared\ntext\n", "b": "shared\ntext\n" },
      ],
      ["adv/anchor-tag/anchor-folded-then-alias", "a: &x >\n  fo\n  ld\nb: *x\n", { "a": "fo ld\n", "b": "fo ld\n" }],
      ["adv/anchor-tag/anchor-consumes-pipe", "key: &a|\n  text\n", { "key": "text" }],
      ["adv/anchor-tag/anchor-consumes-gt", "key: &a>\n  text\n", { "key": "text" }],
      [
        "adv/anchor-tag/verbatim-tag-literal",
        "key: !<tag:yaml.org,2002:str> |\n  verbatim tag\n",
        { "key": "verbatim tag\n" },
      ],
      ["adv/anchor-tag/seq-anchor-tag-alias", "- &a !!str |\n    item one\n- *a\n", ["item one\n", "item one\n"]],
      [
        "adv/anchor-tag/props-on-separate-lines",
        "key:\n  &a\n  !!str\n  |\n    multiline props\n",
        { "key": "multiline props\n" },
      ],
      ["adv/anchor-tag/nonspecific-tag-literal", "key: ! |\n  forced string\n", { "key": "forced string\n" }],
      ["adv/anchor-tag/props-header-at-eof", "key: &a !!str |", { "key": "" }],
      ["adv/anchor-tag/props-header-comment-empty-keep", "key: &a !!str |+ # trailing\n\n\n", { "key": "\n\n" }],
      ["adv/anchor-tag/tag-anchor-folded-crlf", "key: !!str &a >\r\n  cr\r\n  lf\r\n", { "key": "cr lf\n" }],
      [
        "adv/nesting/five-deep-map-1space-indent",
        "a:\n b:\n  c:\n   d:\n    e: |\n     x\n     y\n",
        { "a": { "b": { "c": { "d": { "e": "x\ny\n" } } } } },
      ],
      ["adv/nesting/five-deep-compact-seq", "- - - - - |\n          deep\n          er\n", [[[[["deep\ner\n"]]]]]],
      ["adv/nesting/three-deep-compact-explicit-indent", "- - - |2\n        text\n", [[["  text\n"]]]],
      ["adv/nesting/header-next-line-after-colon", "key:\n  |\n   text\nother: 1\n", { "key": "text\n", "other": 1 }],
      ["adv/nesting/content-mimics-map-with-block", "|\n  key: |\n  next: >\n  end\n", "key: |\nnext: >\nend\n"],
      [
        "adv/nesting/compact-seq-map-block-then-sibling-key",
        "- key: |\n    line1\n    line2\n  sib: 2\n- item2\n",
        [{ "key": "line1\nline2\n", "sib": 2 }, "item2"],
      ],
      [
        "adv/nesting/compact-seq-seq-map-block-sibling",
        "- - a: |\n      text\n    b: y\n  - c: z\n",
        [[{ "a": "text\n", "b": "y" }, { "c": "z" }]],
      ],
      [
        "adv/nesting/map-seq-compact-seq-multi-dedent",
        "a:\n  - - |\n      x\n    - y\n  - z\nb: end\n",
        { "a": [["x\n", "y"], "z"], "b": "end" },
      ],
      ["adv/nesting/anchor-tag-block-deep-compact", "- - &a !!str |\n    text\n- - *a\n", [["text\n"], ["text\n"]]],
      ["adv/nesting/mixed-compact-newline-deep-seq", "- - -\n      - - |\n          x\n", [[[[["x\n"]]]]]],
      ["adv/nesting/content-mimics-nested-seq-block", "- |\n  - |\n  - >\n  - text\n", ["- |\n- >\n- text\n"]],
      ["adv/nesting/seq-items-block-header-own-line", "-\n  |\n   a\n-\n  >\n   b\n", ["a\n", "b\n"]],
      ["adv/nesting/explicit-empty-block-key-value", "? |\n: |\nnext: x\n", { "": "", "next": "x" }],
      ["adv/boundaries/ind9-exact", "|9\n         a\n", "a\n"],
      ["adv/boundaries/ind9-over-by-1", "|9\n          a\n", " a\n"],
      ["adv/boundaries/ind9-blank8-then-content9", "|9\n        \n         a\n", "\na\n"],
      ["adv/boundaries/ind9-keep-trail-under", "|9+\n         a\n        \n       \n", "a\n\n\n"],
      ["adv/boundaries/fold9-9-10-9", ">9\n         a\n          b\n         c\n", "a\n b\nc\n"],
      ["adv/boundaries/ind9-lead-blank20", "|9\n                    \n         a\n", "           \na\n"],
      [
        "adv/boundaries/deep7-ind9-exact16",
        "a:\n b:\n  c:\n   d:\n    e:\n     f:\n      g:\n       h: |9\n                x\n",
        { "a": { "b": { "c": { "d": { "e": { "f": { "g": { "h": "x\n" } } } } } } } },
      ],
      [
        "adv/boundaries/deep7-ind1-min-indent-tie",
        "a:\n b:\n  c:\n   d:\n    e:\n     f:\n      g:\n       h: |1\n        x\n       i: y\n",
        { "a": { "b": { "c": { "d": { "e": { "f": { "g": { "h": "x\n", "i": "y" } } } } } } } },
      ],
      ["adv/boundaries/ind9-bare-eof", "|9", ""],
      ["adv/boundaries/ind9-strip-ws-only-exact", "|9-\n         \n         \n", ""],
      ["adv/boundaries/ind9-strip-ws-only-under", "|9-\n        \n       \n", ""],
      ["adv/boundaries/ind9-tab-at-col9", "|9\n         \ta\n", "\ta\n"],
      [
        "adv/boundaries/nest2-ind9-exact11",
        "k:\n  v: |9\n           x\n           y\n  w: 1\n",
        { "k": { "v": "x\ny\n", "w": 1 } },
      ],
      ["adv/boundaries/fold9-first-line-over", ">9\n          a\n         b\n          c\n", " a\nb\n c\n"],
      ["adv/boundaries/ind3-wide-blank-excess-content", "|3\n          \n   a\n", "       \na\n"],
      [
        "adv/pathological/indent-500-spaces",
        "|\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    x\n",
        "x\n",
      ],
      [
        "adv/pathological/leading-100-empties",
        "|\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n x\n",
        "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nx\n",
      ],
      [
        "adv/pathological/keep-100-trailing",
        "|+\n x\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
        "x\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
      ],
      ["adv/pathological/body-only-dash", "|\n -\n", "-\n"],
      ["adv/pathological/body-triple-dash", "|\n ---\n", "---\n"],
      ["adv/pathological/body-single-dot", "|\n .\n", ".\n"],
      ["adv/pathological/body-triple-dot", "|\n ...\n", "...\n"],
      ["adv/pathological/body-only-pipe", "|\n |\n", "|\n"],
      ["adv/pathological/folded-body-gt", ">\n >\n", ">\n"],
      [
        "adv/pathological/header-at-col-200",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: |\n x\n",
        {
          "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa":
            "x\n",
        },
      ],
      ["adv/pathological/bom-in-body", "|\n ﻿x\n", "﻿x\n"],
      [
        "adv/pathological/explicit-1-actual-200",
        "|1\n                                                                                                                                                                                                        x\n",
        "                                                                                                                                                                                                       x\n",
      ],
      [
        "adv/pathological/keep-only-empties",
        "|+\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
        "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
      ],
      [
        "adv/pathological/line-500-chars",
        "|\n aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
      ],
      ["adv/pathological/seq-items-body-dash", "- |\n  -\n- |\n  - -\n", ["-\n", "- -\n"]],
      [
        "adv/pathological/folded-50-mid-empties",
        ">\n a\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n b\n",
        "a\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nb\n",
      ],
      [
        "adv/interaction/seq-three-chomps-shared-wsonly-trail",
        "- |+\n  x\n\n  \n- |-\n  x\n\n  \n- |\n  x\n\n  \n",
        ["x\n\n\n", "x", "x\n"],
      ],
      [
        "adv/interaction/seq-four-distinct-headers",
        "- |\n  a\n- >\n  b\n  c\n- |-\n  d\n- >+\n  e\n\n",
        ["a\n", "b c\n", "d", "e\n\n"],
      ],
      [
        "adv/interaction/map-fold-then-literal-same-body",
        "a: >\n  one\n  two\nb: |\n  one\n  two\n",
        { "a": "one two\n", "b": "one\ntwo\n" },
      ],
      [
        "adv/interaction/seq-empty-blocks-all-chomps",
        "- |+\n- |-\n- |\n- >+\n- >-\n- end\n",
        ["", "", "", "", "", "end"],
      ],
      [
        "adv/interaction/nested-compact-seq-mixed-styles",
        "- - |\n      a\n  - >\n      b\n      c\n  - |-\n      d\n",
        [["a\n", "b c\n", "d"]],
      ],
      [
        "adv/interaction/keep-trailing-ownership-between-items",
        "- |+\n  a\n\n\n- |-\n  b\n\n\n- end\n",
        ["a\n\n\n", "b", "end"],
      ],
      [
        "adv/interaction/anchor-block-alias-then-fold",
        "- &x |\n  text\n- *x\n- >\n  fold\n  me\n",
        ["text\n", "text\n", "fold me\n"],
      ],
      ["adv/interaction/crlf-item-then-lf-item", "- |\r\n  a\r\n- >\n  b\n  c\n", ["a\n", "b c\n"]],
      ["adv/interaction/content-masquerades-as-map-key", "a: |\n  x\n  b: |\n    y\n", { "a": "x\nb: |\n  y\n" }],
      [
        "adv/interaction/autodetect-indent-varies-per-item",
        "- |\n      deep\n- |\n  shallow\n- |\n    mid\n",
        ["deep\n", "shallow\n", "mid\n"],
      ],
    ] as const)("%s", (_id, input, expected) => {
      expect(YAML.parse(input)).toEqual(expected);
    });
  });
});

// On these inputs the four reference parsers disagree (typically 2-2). The
// spec is unambiguous; one or more refs deviate from it. The expected values
// lock in the spec-derived answer; the comment column shows what each
// reference parser produces. If any of these change, re-derive from the spec
// — don't pick a ref to match.
describe("block scalar oracle-split (refs disagree)", () => {
  test.each([
    [
      "ws/|/trail-eof/w3",
      "- |\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    [
      "ws/|/trail-eof/w4",
      "- |\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    [
      "ws/|2/trail-eof/w3",
      "- |2\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/|2/only-eof/w3", "- |2\n   ", [" \n"], 'ee=[""] js=[" \\n"] py=[" "] ru=[" "]'],
    [
      "ws/|2/trail-eof/w4",
      "- |2\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/|2/only-eof/w4", "- |2\n    ", ["  \n"], 'ee=[""] js=["  \\n"] py=["  "] ru=["  "]'],
    ["ws/|+/only-eof/w1", "- |+\n ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    ["ws/|+/only-eof/w2", "- |+\n  ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/|+/trail-eof/w3",
      "- |+\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/|+/only-eof/w3", "- |+\n   ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/|+/trail-eof/w4",
      "- |+\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/|+/only-eof/w4", "- |+\n    ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    ["ws/|2+/only-eof/w2", "- |2+\n  ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/|2+/trail-eof/w3",
      "- |2+\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/|2+/only-eof/w3", "- |2+\n   ", [" \n"], 'ee=["\\n"] js=[" \\n"] py=[" "] ru=[" "]'],
    [
      "ws/|2+/trail-eof/w4",
      "- |2+\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/|2+/only-eof/w4", "- |2+\n    ", ["  \n"], 'ee=["\\n"] js=["  \\n"] py=["  "] ru=["  "]'],
    [
      "ws/>/trail-eof/w3",
      "- >\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    [
      "ws/>/trail-eof/w4",
      "- >\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    [
      "ws/>2/trail-eof/w3",
      "- >2\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/>2/only-eof/w3", "- >2\n   ", [" \n"], 'ee=[""] js=[" \\n"] py=[" "] ru=[" "]'],
    [
      "ws/>2/trail-eof/w4",
      "- >2\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/>2/only-eof/w4", "- >2\n    ", ["  \n"], 'ee=[""] js=["  \\n"] py=["  "] ru=["  "]'],
    ["ws/>+/only-eof/w1", "- >+\n ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    ["ws/>+/only-eof/w2", "- >+\n  ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/>+/trail-eof/w3",
      "- >+\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/>+/only-eof/w3", "- >+\n   ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/>+/trail-eof/w4",
      "- >+\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/>+/only-eof/w4", "- >+\n    ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    ["ws/>2+/only-eof/w2", "- >2+\n  ", ["\n"], 'ee=["\\n"] js=["\\n"] py=[""] ru=[""]'],
    [
      "ws/>2+/trail-eof/w3",
      "- >2+\n  text\n   ",
      ["text\n \n"],
      'ee=["text\\n \\n"] js=["text\\n \\n"] py=["text\\n "] ru=["text\\n "]',
    ],
    ["ws/>2+/only-eof/w3", "- >2+\n   ", [" \n"], 'ee=["\\n"] js=[" \\n"] py=[" "] ru=[" "]'],
    [
      "ws/>2+/trail-eof/w4",
      "- >2+\n  text\n    ",
      ["text\n  \n"],
      'ee=["text\\n  \\n"] js=["text\\n  \\n"] py=["text\\n  "] ru=["text\\n  "]',
    ],
    ["ws/>2+/only-eof/w4", "- >2+\n    ", ["  \n"], 'ee=["\\n"] js=["  \\n"] py=["  "] ru=["  "]'],
    ["eof/|/content-no-nl", "- |\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/|2/content-no-nl", "- |2\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/|+/content-no-nl", "- |+\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/|2+/content-no-nl", "- |2+\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/>/content-no-nl", "- >\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/>2/content-no-nl", "- >2\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/>+/content-no-nl", "- >+\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    ["eof/>2+/content-no-nl", "- >2+\n  text", ["text\n"], 'ee=["text\\n"] js=["text\\n"] py=["text"] ru=["text"]'],
    [
      "adv/unicode/nel-content-literal",
      "key: |\n  line1line2\n",
      { "key": "line1line2\n" },
      'ee={"key":"line1line2\\n"} js={"key":"line1line2\\n"} py="__ERR__" ru="__ERR__"',
    ],
    [
      "adv/unicode/ls-in-folded-no-fold",
      "key: >\n  word1 word2\n  word3\n",
      { "key": "word1 word2 word3\n" },
      'ee={"key":"word1 word2 word3\\n"} js={"key":"word1 word2 word3\\n"} py="__ERR__" ru="__ERR__"',
    ],
    [
      "adv/unicode/ps-only-line-folded",
      "key: >\n  one\n   \n  two\n",
      { "key": "one   two\n" },
      'ee={"key":"one   two\\n"} js={"key":"one   two\\n"} py={"key":"one \\ntwo\\n"} ru={"key":"one \\ntwo\\n"}',
    ],
    [
      "adv/unicode/crlf-with-nel",
      "key: |\r\n  ab\r\n  c\r\n",
      { "key": "ab\nc\n" },
      'ee={"key":"ab\\nc\\n"} js={"key":"ab\\nc\\n"} py="__ERR__" ru="__ERR__"',
    ],
    [
      "adv/comments/hdr-hash-tab-sep",
      "key: |\t# tabsep\n  text\n",
      { "key": "text\n" },
      'ee={"key":"text\\n"} js={"key":"text\\n"} py="__ERR__" ru="__ERR__"',
    ],
    [
      "adv/anchor-tag/null-tag-nonempty-block",
      "key: !!null |\n  not actually null\n",
      { "key": "not actually null\n" },
      'ee={"key":"not actually null\\n"} js="__ERR__" py={"key":null} ru={"key":null}',
    ],
    [
      "adv/nesting/header-dedented-after-colon",
      "key:\n|\n text\n",
      // [199] s-l+block-scalar(n,c) requires s-separate(n+1,c) before `|`;
      // for `key:` at n=0 the `|` must be at indent ≥ 1. ee/js error, py/ru
      // accept; Bun now sides with the spec-compliant refs.
      "__ERR__",
      'ee="__ERR__" js="__ERR__" py={"key":"text\\n"} ru={"key":"text\\n"}',
    ],
    [
      "adv/interaction/empty-block-then-docsep",
      "|\n---\nfoo\n",
      ["", "foo"],
      'ee="__ERR__" js="---\\nfoo\\n" py="__ERR__" ru="---\\nfoo\\n"',
    ],
    [
      "adv/interaction/keep-only-empties-then-docsep",
      "|+\n\n\n---\nbar\n",
      ["\n\n", "bar"],
      'ee="__ERR__" js="\\n\\n---\\nbar\\n" py="__ERR__" ru="\\n\\n---\\nbar\\n"',
    ],
    [
      "adv/interaction/tab-separation-before-block-header",
      "-\t|\n  a\n-\t>\n  b\n  c\n",
      ["a\n", "b c\n"],
      'ee=["a\\n","b c\\n"] js=["a\\n","b c\\n"] py="__ERR__" ru="__ERR__"',
    ],
  ] as const)("%s", (_id, input, expected, _oracles) => {
    if (expected === "__ERR__") {
      expect(() => YAML.parse(input)).toThrow();
    } else {
      expect(YAML.parse(input)).toEqual(expected);
    }
  });
});
