const inputs = [
  ["js", "1 = 2"],
  ["js", "([]) = 1"],
  ["js", "[...a, b] = c"],
  ["js", "let x = ;"],
  ["js", "function f( {"],
  ["js", "a + = 1"],
  ["js", "({a:1} = 1)"],
  ["js", "for (let x of y z) {}"],
  ["js", "const a = 1; a = 2;"],
  ["js", "let a; let a;"],
  ["js", "class A { constructor(){} constructor(){} }"],
  ["js", "return 1"],
  ["js", "function f(){ break; }"],
  ["js", "x: x: 1"],
  ["js", "continue;"],
  ["js", "({a}) => { 'use strict'; }"],
  ["js", "delete x; export {}"],
  ["js", "with (a) {} export {}"],
  ["js", "var yield; export {}"],
  ["js", "await 1; function f(){ await 1 }"],
  ["js", "new.target"],
  ["js", "super.x"],
  ["js", "import.meta; import x from 'y'; x = 1;"],
  ["js", "({ get a(x){} })"],
  ["js", "a?.b = 1"],
  ["js", "++a++"],
  ["js", "`${`"],
  ["js", "/(/"],
  ["js", "'abc"],
  ["js", "#!/usr/bin/env node\nlet a = 1;"],
  ["js", "<div/>"],
  ["js", "@dec class A {}"],
  ["ts", "let x: number = ;"],
  ["ts", "1 = 2"],
  ["ts", "enum E { A = , }"],
  ["ts", "const a = 1; a = 2;"],
  ["ts", "function f(a?: number, b: number) {}"],
  ["ts", "abstract class A { abstract m() {} }"],
  ["ts", "let x: = 1"],
  ["ts", "type A = ;"],
  ["ts", "interface I { a: }"],
  ["ts", "#!/usr/bin/env bun\nlet a: number = 1;"],
  ["ts", "export const x: number;"],
  ["ts", "declare const x: number;"],
  ["ts", "export declare const x: number;"],
  ["ts", "export function f(): void;"],
  ["ts", "export default function f(): void;"],
  ["ts", "export class A { m(): void; x: number; }"],
  ["ts", "declare module 'x' { export const y: number; }"],
  ["ts", "export namespace N { const a: number; }"],
  ["ts", "declare namespace N { const a: number; }"],
  ["ts", "export = foo;"],
  ["ts", "import {m} from './m' with {type:'macro'}; const v = m();"],
  ["js", "import {m} from './m' with {type:'macro'}; const v = m();"],
  ["tsx", "const a = <T,>(x: T) => <div>{x}</div>;"],
  ["ts", "const a = <T>(x: T) => x;"],
  ["ts", "@dec class A { @dec m() {} }"],
  ["ts", "class A { constructor(@dec x: number) {} }"],
];
const out = [];
for (const [loader, code] of inputs) {
  let scan = "ok", full = "ok";
  try { new Bun.Transpiler({ loader }).scanImports(code); } catch (e) { scan = "ERR " + String(e.errors?.[0]?.message ?? e.message).slice(0, 60); }
  try { new Bun.Transpiler({ loader, allowBunRuntime: false }).transformSync(code); } catch (e) { full = "ERR " + String(e.errors?.[0]?.message ?? e.message).slice(0, 60); }
  out.push(`${loader.padEnd(3)} | ${JSON.stringify(code).slice(0, 58).padEnd(58)} | scan: ${scan.padEnd(64)} | full: ${full}`);
}
console.log(out.join("\n"));
