#!/usr/bin/env bun
// Declaration files (.d.ts, ambient context for the whole file). Bun has no such mode: the loader is ts.
// Reference: parseSourceFileWorker 431 (NodeFlagsAmbient for declaration files), parseFunctionBlockOrSemicolon 3530,
// parseDeclaration 1124, parseVariableDeclarationList 1554, getCommentPragmas 6455, extractPragmas 6463.
import { each, writeGroup } from "./gen-lib.mjs";

const statements = [
  "export declare const a: A;", "declare const a: A;", "export const a: A;", "const a: A;", "let a: A;", "var a: A;", "export let a: A;", "export var a: A, b: B;",
  "export const a = 1;", 'export const a = "s";', "export const a = -1;", "export const a = 1n;", "export const a = true;", "export const a = {};", "export const a = E.A;",
  "export const a = b;", "export const a: A = 1;", "export const a;", "export let a = 1;", "export var a = 1;", "export const a: unique symbol;", "export declare const { a, b }: A;",
  "export const { a, b }: A;", "export declare let [a]: A;", "export const a: A, b: B;", "export declare let a!: A;", "export using a: A;",
  "declare function f(): void;", "export function f(): void;", "function f(): void;", "export declare function f(): void;", "export function f(): void", "export function f()",
  "export function f() {}", "function f() {}", "declare function f() {}", "export function f(a: A, b?: B, ...c: C[]): D;", "export function f(a: A): void; export function f(a: B): void;",
  "export function f(a: A): void\nexport function f(a: B): void", "export function f<T>(a: T): a is T;", "export function f(a: any): asserts a;", "export function f(a: any): asserts a is A;",
  "export function f(this: A, ...a: any[]): void;", "export function f<const T>(a: T): T;", "export function f(a = 1): void;", "export function f({ a }: A, [b]: B): void;",
  "export function f(public a: A): void;", "export function f(a: A,): void;", "export function f(...a: A[],): void;", "export function* f(): A;", "export async function f(): Promise<A>;",
  "export declare async function f(): Promise<A>;", "export default function f(): void;", "export default function (): void;", "export default function f<T>(a: T): T;",
  "export default function f(): void; export default function f(a: A): void;", "export default async function f(): Promise<void>;", "export default function f() {}",
  "export default class C {}", "export default class {}", "export default class C<T> extends D<T> implements I<T> { m(): void; a: A }", "export default abstract class C { abstract m(): void }",
  "export default interface I {}", "export default a;", "declare const a: A; export default a;", "export default A.B;", "export default 1;", "export default {};", "export default a as A;",
  "export default function f(): void;\nexport default interface f {}", "export default enum E {}", "export default namespace N {}", "export default type X = A;", "export default declare class C {}",
  "export = A;", "export = A.B;", "declare const a: A;\nexport = a;", "declare namespace N {}\nexport = N;", "export = 1;", "export = {};", "export = class {};", "export = function (): void;",
  "export as namespace N;", "export as namespace N;\nexport = N;", "export as namespace N;\nexport const a: A;", "export as namespace N.M;", "export as namespace;",
  "declare namespace N { function f(): void; const a: A; class C { m(): void } }", "namespace N { function f(): void }", "export namespace N { const a: A; function f(): void }",
  "export declare namespace N { const a: A }", "export declare namespace N.M {}", "export namespace N { export const a: A }", "export namespace N { declare const a: A }",
  "export namespace N { function f() {} }", "export namespace N { const a = f() }", "export namespace N { export {} }", "export namespace N { export { a } }", "export namespace N { a; }",
  "declare module M {}", "module M {}", "export module M {}", 'declare module "m" {}', 'declare module "m";', 'module "m" {}', 'export declare module "m" {}',
  'declare module "m" { export default function f(): void; }', 'declare module "m" { const a: A; export = a; }', 'declare module "*.svg" { const content: string; export default content; }',
  'declare module "m" { function f(): void; export function g(): void; class C {} }', 'declare module "m" { import { A } from "n"; export { A } }', 'declare module "m" { export * from "n"; }',
  "declare global {}", "declare global { interface Window { a: A } var b: B; function f(): void }", "global {}", "export declare global {}", "export {};\ndeclare global { var a: A }",
  "interface I {}", "export interface I {}", "declare interface I {}", "interface I { (a: A): B; new (a: A): I; readonly [k: string]: A; m?(): void; get a(): A; set a(v: A); }",
  "interface I { a: A = 1 }", "interface I { m() {} }", "interface I extends J<K>, L.M {}", "type X = A;", "export type X = A;", "declare type X = A;", "export declare type X<T> = T;",
  "export type X = { [K in keyof A]: A[K] };", "export type { A };", 'export type { A } from "m";', 'export type * from "m";', 'export type * as N from "m";', "export { a, type B };",
  'import type { A } from "m";', 'import { A } from "m";', 'import { type A } from "m";', 'import A from "m";', 'import * as A from "m";', 'import "m";', 'import type A = require("m");',
  'import A = require("m");', "import A = N.B;", "export import A = N.A;", 'export import A = require("m");', 'export * from "m";', 'export * as N from "m";', 'export { a } from "m";',
  "export {};", "export { a };", "export { a as default };", "declare const a: A; export { a as default };",
  "export class C {}", "class C {}", "declare class C {}", "export declare class C {}", "export abstract class C { abstract m(): void; protected abstract readonly a: A }",
  "export declare class C<T = any> extends D<T> implements I<T> {}", "export class C { private a; protected b: B; constructor(a: A); m(): void; static s(): void; get g(): A; set g(v: A); readonly r: A; #p; static #q: A }",
  "export class C { m() {} }", "export class C { a = 1 }", "export class C { static readonly a = 1 }", "export class C { readonly a = 1 }", 'export class C { static readonly a = "s" }',
  "export class C { readonly a = -1 }", "export class C { readonly a = 1n }", "export class C { readonly a = true }", "export class C { readonly a = {} }", "export class C { readonly a: A = 1 }",
  "export class C { static a = 1 }", "export class C { constructor(public a: A) }", "export class C { constructor(public a: A); }", "export class C { constructor(a: A) {} }",
  "export class C { constructor(); constructor(a: A); }", "export class C { private constructor(); }", "export class C { protected constructor(a: A, b?: B); }", "export class C { get a() { return 1 } }",
  "export class C { get a(): A; set a(v: A); }", "export class C { get a(): A\nset a(v: A) }", "export class C { accessor a: A }", "export class C { static accessor a: A; }", "export class C { static {} }",
  "export class C { declare a: A }", "export class C { @d a: A }", "@d export class C {}", "export class C { m(@d a: A): void }", "export class C { [Symbol.iterator](): Iterator<A>; }",
  "export class C { readonly [k: string]: A }", "export class C { static [k: string]: A }", "export class C { m?(): void; a?: A; b!: B }", 'export class C { "a-b": A; 1: B; }',
  "export class C { m(): void; m(a: A): void; }", "export class C { m(): void\nm(a: A): void }", "export class C { m(): void m(a: A): void }", "export class C { a: A b: B }", "export class C { a: A\nb: B }",
  "export class C { async m(): Promise<void>; }", "export class C { *m(): Generator<A>; }", "export class C { m(a = 1): void; }", "export class C { m(this: C): void; }", "export class C { override m(): void; }",
  "export class C { private m(); private static n(); private a; private get b(); private set b(value: any); }", "export class C { private m(a: A): B; }", "export class C { #m(): void; }", "export class C { static #m(): void; }",
  "export enum E { A = 1 }", "export enum E { A, B = A }", "export enum E { A = f() }", 'export enum E { A = "a".length }', "export declare enum E {}", "export const enum E { A }", "export declare const enum E { A = 1 }",
  "enum E {}", "const enum E {}", "declare enum E {}",
  "a;", "a = 1;", "f();", "if (a) {}", "for (;;) {}", "while (a) {}", "do {} while (a)", "switch (a) {}", "try {} catch {}", "throw a;", "return;", "debugger;", "{}", ";", "label: a;", "label: {}",
  "with (a) {}", "break;", "continue;", '"use strict";', "1;", "`t`;", "a as A;", "a!;", "<A>a;", "new A();", "class {};", "(class {});", "function () {};", "(function () {});", "() => {};",
  "declare const a: A; a;", "export const a: A; export function f(): void; export class C {} export interface I {} export type X = A; export enum E {} export namespace N {}",
  "export declare const a: typeof import('m');", "export declare const a: import('m').A<B>;", 'export declare type X = import("m", { with: { "resolution-mode": "import" } }).A;',
  'export declare const a: import("m", { assert: { "resolution-mode": "import" } }).A;', "export declare const a: typeof import('m', { with: { 'resolution-mode': 'require' } });",
  "declare function f(): void; declare namespace f { const a: A }", "declare class C {} declare namespace C { const a: A }", "declare const a: A<B>\ndeclare const c: C",
  "export declare const a: A\nexport declare function f(): void\nexport declare class C {}\nexport {}",
];

const pragmas = [
  '/// <reference types="node" />', '/// <reference path="a.d.ts" />', '/// <reference lib="es2015" />', '/// <reference no-default-lib="true"/>', '/// <amd-module name="m"/>',
  '/// <amd-dependency path="a" name="b"/>', '/// <reference types="node" resolution-mode="import" />', '/// <reference types="node" preserve="true" />', "/// <reference types='node' />",
  '///<reference types="node"/>', '/// <reference types="node">', '/// <reference types=node />', '/// <reference types="node" /> trailing', '  /// <reference types="node" />',
  '//// <reference types="node" />', '// / <reference types="node" />', '/* /// <reference types="node" /> */', '/** <reference types="node" /> */', '/// <reference />', "/// <reference",
  '/// <Reference types="node" />', '/// <reference TYPES="node" />', '/// <reference types="" />', '/// <reference unknown="a" />', '/// <reference types="a" path="b" lib="c" />',
  '/// <reference types="node" />\n/// <reference path="a.d.ts" />\n/// <reference lib="dom" />', '/// <reference types="node" />\n\n// comment\n/// <reference path="a.d.ts" />',
  '// comment\n/// <reference types="node" />', '/* comment */\n/// <reference types="node" />', '#!/usr/bin/env node\n/// <reference types="node" />', '"use strict";\n/// <reference types="node" />',
  'export {};\n/// <reference types="node" />', 'declare const a: A;\n/// <reference types="node" />', '/// <reference types="node" />\nexport declare const a: A;', "// @ts-nocheck", "// @ts-check",
  "// @ts-nocheck\nexport declare const a: A;", "/* @ts-nocheck */", "/** @ts-nocheck */", "//@ts-nocheck", "// @ts-nocheck trailing", "// @TS-NOCHECK", "//  @ts-nocheck", "// x @ts-nocheck",
  "// @ts-check\n// @ts-nocheck", "export {};\n// @ts-nocheck", "// @ts-ignore\nexport declare const a: A;", "// @ts-expect-error\nexport declare const a: A;", "/* @ts-ignore */\nexport declare const a: A;",
  "// @jsx h", "/** @jsx h */", "/** @jsxFrag Fragment */", "/** @jsxImportSource preact */", "/** @jsxRuntime automatic */", "// @ts-nocheck\n/// <reference types='node' />", "/// <reference types='node' />\n// @ts-nocheck",
  "\ufeff/// <reference types='node' />", "\ufeffexport declare const a: A;", "/// <reference types='node' />\r\n/// <reference path='a.d.ts' />\r\nexport {};",
];

writeGroup("10-declaration-files.txt", "Declaration files.", [
  { prefix: "dts", kind: "dts", items: statements },
  { prefix: "pragma.dts", kind: "dts", items: pragmas },
  { prefix: "pragma.ts", kind: "file", items: each(pragmas, p => `${p}\nlet v = 1;`) },
]);
