#!/usr/bin/env bun
// "declare", namespaces, enums, ambient modules.
// Reference: parseDeclaration 1124 (ambient context), parseDeclarationWorker 1151, scanStartOfDeclaration 6123,
// parseModuleDeclaration 2202, parseAmbientExternalModuleDeclaration 2218, parseModuleOrNamespaceDeclaration 2254,
// parseModuleBlock 2242, parseEnumDeclaration 2181, parseEnumMember 2171, parseVariableDeclarationList 1554.
import { each, writeGroup } from "./gen-lib.mjs";

const words = ["type", "as", "of", "is", "async", "await", "yield", "let", "static", "public", "implements", "package", "interface", "abstract", "declare", "readonly", "global", "namespace", "module", "require", "constructor", "from", "get", "set", "using", "any", "string", "number", "object", "undefined", "unknown", "never", "arguments", "eval", "if", "class", "function", "default", "in", "new", "typeof", "enum", "extends", "import", "export", "var", "const", "void", "null", "this", "true"];

const declares = [
  "declare var a;", "declare var a: A;", "declare var a: A, b: B;", "declare var a = 1;", "declare var a: A = 1;", "declare let a: A;",
  "declare let a;", "declare let a = 1;", "declare const a: A;", "declare const a = 1;", 'declare const a = "s";', "declare const a = -1;",
  "declare const a = 1n;", "declare const a = true;", "declare const a = {};", "declare const a = E.A;", "declare const a = b;",
  "declare const a: A = 1;", "declare const a;", "declare const a, b;", "declare const a: A, b = 1;", "declare const { a }: A;",
  "declare const { a } = b;", "declare let [a]: A;", "declare var { a, b: [c] }: A;", "declare const a: unique symbol;", "declare let a!: A;",
  "declare using a: A;", "declare using a = b;", "declare await using a: A;", "declare var", "declare var;", "declare const", "declare let",
  "declare let\na: A;", "declare var a: A\ndeclare var b: B", "declare var a: A declare var b: B", "declare var a: A; declare var b: B",
  "declare function f(): void;", "declare function f(): void", "declare function f();", "declare function f()", "declare function f() {}",
  "declare function f(): void {}", "declare function f<T>(a: T): T;", "declare function f(a?: A, ...b: B[]): C;", "declare function f(a = 1): void;",
  "declare function f(a: A = 1): void;", "declare function f({ a }: A, [b]: B): void;", "declare function f({ a = 1 }): void;",
  "declare function f(...a, b): void;", "declare function f(...a,): void;", "declare function f(...a: A[],): void;", "declare function f(a,): void;",
  "declare function f(this: A): void;", "declare function f(a: any): a is A;", "declare function f(a: any): asserts a;",
  "declare function f(a: any): asserts a is A;", "declare function f(public a: A): void;", "declare function f(@d a: A): void;",
  "declare function* f(): A;", "declare async function f(): A;", "declare async function* f(): A;", "declare function f(): void; declare function f(a: A): void;",
  "declare function f(): void\ndeclare function f(a: A): void", "declare function f(): void function g() {}", "declare function f(): void declare function g(): void",
  "declare function (): void;", "declare function default(): void;", "declare function f: A;", "declare function f<T>;", "declare function",
  "declare function f(): A<B>\ndeclare function g(): C", "declare function f(): typeof a\ndeclare function g(): C", "declare function f(): A\n(b)",
  "declare class C {}", "declare class C<T> extends D<T> implements I<T> {}", "declare class C { a: A; m(): void; constructor(a: A); static s: A; get g(): A; set g(v: A); [k: string]: A; private p; protected q: A; readonly r: A; #x: A; declare y: A }",
  "declare class C { m() {} }", "declare class C { a = 1 }", "declare class C { static readonly a = 1 }", "declare class C { readonly a = 1 }",
  "declare class C { static {} }", "declare class C { constructor(public a: A); }", "declare class C { constructor(public a: A) {} }",
  "declare class C { get a() { return 1 } }", "declare class C { accessor a: A }", "declare class C { m(): void; m(a: A): void }",
  "declare class C { @d m(): void }", "declare class C { abstract m(): void }", "declare class C { m?(): void; a?: A; b!: B }",
  "declare abstract class C { abstract m(): void; abstract a: A; protected abstract readonly b: B }", "declare class", "declare class {}",
  "declare class C", "declare class C extends D", "declare @d class C {}", "@d declare class C {}", "declare class C {} declare class D {}",
  "declare enum E { A, B = 1, C = 'c', D = A | B }", "declare enum E {}", "declare const enum E { A }", "declare const enum E { A = 'a'.length }",
  "declare enum E { A = f() }", "const declare enum E {}", "declare enum", "declare const enum", "declare enum E", "declare const\nenum E {}",
  "declare namespace N {}", "declare namespace N { const a: A; function f(): void; class C {} interface I {} type X = A; enum E {} namespace M {} export const b: B; var c; let d }",
  "declare namespace N.M.O {}", "declare namespace N { export {} }", "declare namespace N { export { a } }", "declare namespace N { export default a }",
  "declare namespace N { export = a }", "declare namespace N { import a = M.b }", "declare namespace N { export import a = M.b }",
  "declare namespace N { import a from 'm' }", "declare namespace N { export * from 'm' }", "declare namespace N { declare const a: A }",
  "declare namespace N { function f() {} }", "declare namespace N { const a = 1; let b = 2; var c = 3 }", "declare namespace N { a; }",
  "declare namespace N { if (a) {} }", "declare namespace N { f(); }", "declare namespace N { class C { m() {} } }", "declare namespace N { ; }",
  "declare namespace N { {} }", "declare namespace N { label: a }", "declare namespace N { return }", "declare namespace N { export function f(): void }",
  "declare namespace N { export function f(): void\nexport function g(): void }", "declare namespace N { function f(): void function g(): void }",
  "declare namespace N", "declare namespace N;", "declare namespace", "declare namespace {}", "declare namespace N { namespace M { const a: A } }",
  "declare module M {}", "declare module M.N {}", "declare module M { const a: A }", 'declare module "m" {}', 'declare module "m";', 'declare module "m"',
  "declare module 'm' {}", "declare module `m` {}", 'declare module "*.css" { const a: string; export default a }', 'declare module "m" { export = A }',
  'declare module "m" { import a from "n"; export { a } }', 'declare module "m" { export * from "n" }', 'declare module "m" { export default function f(): void }',
  'declare module "m" { export default class {} }', 'declare module "m" { export default interface I {} }', 'declare module "m" { const a: A; export default a }',
  'declare module "m" { export const a: A; export function f(): void; export class C {} export type X = A; export interface I {} export enum E {} export namespace N {} }',
  'declare module "m" { function f() {} }', 'declare module "m" { const a = f() }', 'declare module "m" { a; }', 'declare module "m" { declare const a: A }',
  'declare module "m" { declare module "n" {} }', 'declare module "m" { namespace N {} module O {} }', 'declare module "m" { export as namespace A }',
  'declare module "m" { import type { A } from "n"; export type { A } }', 'declare module "m" { import a = require("n"); export import b = a.c }',
  'declare module "m" {} declare module "n" {}', 'declare module "m" {}\ndeclare module "n" {}', 'declare module "m"\ndeclare module "n"',
  'declare module "m"; declare module "n";', 'declare module "m" "n"', 'declare module "m".n {}', 'declare module "m" extends A {}', 'declare module "m"<T> {}',
  'declare module "m" {', "declare module 1 {}", "declare module {}", "declare module", "declare module;", 'declare module\n"m" {}', 'declare module "m"\n{}',
  "declare global {}", "declare global { interface Window { a: A } }", "declare global { var a: A }", "declare global { const a: A; function f(): void }",
  "declare global;", "declare global", "declare global { a; }", "declare global {} declare global {}", "declare global.a {}", "declare global a {}",
  "declare\nglobal {}", "declare global\n{}", "declare namespace global {}", "declare module global {}", "export declare global {}",
  "declare global { export {} }", 'declare module "m" { global { var a: A } }', "declare namespace N { global {} }",
  "global {}", "global { var a: A }", "global;", "global = 1;", "global();", "global.a;", "global\n{}", "var global = 1;", "global + 1;",
  'module "m" {}', 'module "m";', 'module "m"', 'namespace "m" {}', 'export module "m" {}', 'module\n"m" {}', 'module "m"\n{}',
  "declare type X = A;", "declare interface I {}", "declare import a = b;", "declare import a from 'm';", "declare import 'm';", "declare export default a;",
  "declare export { a };", "declare export * from 'm';", "declare;", "declare = 1;", "declare();", "declare.a;", "declare\nconst a: A = 1;",
  "declare\nconst a: A;", "declare\nfunction f(): void", "declare\nfunction f() {}", "declare\nclass C {}", "declare\nvar a;", "declare\nenum E {}",
  "declare\nnamespace N {}", "declare\nmodule M {}", "declare\ninterface I {}", "declare\ntype X = A;", "declare\nlet a;", "declare declare const a: A;",
  "declare async function f(): void;", "declare a;", "declare a: A;", "declare {}", "declare if (a) {}", "declare return;", "declare 1;",
  "declare +a;", "declare ? a : b;", "declare => 1;", "(declare) => 1;", "a = declare;", "var declare = 1;", "let declare: declare;", "declare `t`;",
  "declare\n(a);", "declare in a;", "declare instanceof A;", "declare++;", "declare as A;", "declare!;", "declare<A>(b);", "declare<A>;",
  "namespace N { declare const a: A }", "namespace N { export declare const a: A }", "namespace N { declare function f(): void }",
  "function f() { declare const a: A }", "function f() { declare function g(): void }", "{ declare const a: A }", "{ declare class C {} }",
  "if (a) declare const b: B;", "label: declare const a: A;", "for (;;) declare const a: A;", "class C { declare a: A }", "declare label: a",
  "declare public class C {}", "declare static const a: A;", "declare readonly a: A;", "declare abstract;", "declare abstract\nclass C {}",
  "declare const a: A<B>\ndeclare const c: C", "declare const a: typeof b\ndeclare const c: C", "declare var a: A.B\n<C>d;",
];

const namespaces = [
  "namespace N {}", "namespace N { export const a = 1 }", "namespace N.M {}", "namespace N.M.O { export const a = 1 }", "namespace N { namespace M {} }",
  "namespace N { export namespace M {} }", "module M {}", "module M.N {}", "module M { export const a = 1 }", "namespace\nN {}", "module\nM {}",
  "namespace N\n{}", "module M\n{}", "namespace N.\nM {}", "namespace N\n.M {}", "namespace N {", "namespace {}", "namespace N.{}", "namespace N. M {}",
  "namespace N..M {}", "namespace .N {}", 'namespace "N" {}', "namespace 1 {}", "namespace N<T> {}", "namespace N extends M {}", "namespace N()",
  "namespace N = M;", "namespace N;", "namespace N", "namespace N {};", "namespace N {} namespace N {}", "namespace N { } namespace M { }",
  "namespace N.default {}", "namespace N.class.if {}", "namespace N.type.as {}", "namespace N.#a {}", 'namespace N."a" {}', "namespace N.1 {}",
  "namespace N { export default a }", "namespace N { import a = M.b }", "namespace N { export import a = M.b }", "namespace N { import a = require('m') }",
  "namespace N { import a from 'm' }", "namespace N { import 'm' }", "namespace N { export * from 'm' }", "namespace N { export { a } }",
  "namespace N { export { a } from 'm' }", "namespace N { export {} }", "namespace N { export = a }", "namespace N { export as namespace A }",
  "namespace N { return }", "namespace N { await a }", "namespace N { yield }", "namespace N { break }", "namespace N { this.a }", "namespace N { super.a }",
  "namespace N { new.target }", "namespace N { arguments }", "namespace N { type X = A; interface I {} }", "namespace N { export type X = A }",
  "namespace N { export interface I {} }", "namespace N { export declare const a: A }", "namespace N { declare module 'm' {} }",
  "namespace N { export let a: A, b: B = 1 }", "namespace N { export var a: A }", "namespace N { export const [a, b] = c }",
  "namespace N { export const { a, b: { c } } = d }", "namespace N { export const { a = 1, ...b } = c }", "namespace N { export function f<T>(a: T): T { return a } }",
  "namespace N { export class C<T> {} }", "namespace N { export enum E {} }", "namespace N { export const enum E {} }", "namespace N { export abstract class C {} }",
  "namespace N { export async function f() {} }", "namespace N { export function* f() {} }", "namespace N { export using a = b }",
  "namespace N { export a }", "namespace N { export; }", "namespace N { export export const a = 1 }", "namespace N { export public a }",
  "namespace N { export let a }\nnamespace N { a = 1 }", "namespace N { export const a = 1; export const b = a }", "namespace N { let a: A = 1; a as B; <B>a; a! }",
  "namespace N { @d class C {} }", "namespace N { export @d class C {} }", "namespace N { @d export class C {} }", "namespace N { export default class {} }",
  "async namespace N {}", "abstract namespace N {}", "static namespace N {}", "public namespace N {}", "const namespace N {}", "readonly namespace N {}",
  "export namespace N {}", "export default namespace N {}", "export declare namespace N {}", "declare export namespace N {}", "@d namespace N {}",
  "function f() { namespace N {} }", "{ namespace N {} }", "if (a) namespace N {}", "label: namespace N {}", "for (;;) namespace N {}", "class C { namespace N {} }",
  "function f() { module M {} }", "{ module M {} }", "namespace N { { namespace M {} } }", "namespace N { function f() { namespace M {} } }",
  "namespace;", "namespace = 1;", "namespace();", "namespace.a;", "var namespace = 1;", "namespace\n(a);", "namespace + 1;", "namespace => 1;",
  "(namespace) => 1;", "a = namespace;", "namespace\n{}", "namespace `t`;", "namespace++;", "namespace in a;", "namespace as A;", "namespace!;",
  "namespace<A>(b);", "namespace ? a : b;", "let namespace: namespace;",
  "module;", "module = 1;", "module();", "module.exports = 1;", "module\n.exports = 1;", "var module = 1;", "module\n(a);", "module + 1;", "module => 1;",
  "(module) => 1;", "a = module;", "module\n{}", "module `t`;", "module++;", "module in a;", "module as A;", "module!;", "module<A>(b);",
  "module ? a : b;", "let module: module;", "module\nM\n{}", "namespace\nN\n{}", "typeof module;", "module.id as A;",
  ...each(words, w => `namespace ${w} {}`),
  ...each(words, w => `module ${w} {}`),
  ...each(words, w => `namespace N.${w} {}`),
  ...each(words, w => `declare namespace ${w} {}`),
];

const enums = [
  "enum E {}", "enum E { A }", "enum E { A, }", "enum E { A, B }", "enum E { A = 1 }", "enum E { A = 1, B, C = 'c' }", 'enum E { "A" }',
  'enum E { "A" = 1 }', "enum E { 'a-b' = 1 }", "enum E { 1 }", "enum E { 1 = 2 }", "enum E { 1.5 }", "enum E { 0x10 }", "enum E { 1n }", "enum E { -1 }",
  "enum E { [a] }", "enum E { [a] = 1 }", 'enum E { ["a"] }', 'enum E { ["a"] = 1 }', "enum E { [`a`] = 1 }", "enum E { [`a${b}`] = 1 }", "enum E { [1] = 1 }",
  'enum E { ["a" + "b"] = 1 }', "enum E { [a.b] = 1 }", "enum E { #a }", "enum E { #a = 1 }", "enum E { `a` }", "enum E { `a` = 1 }", "enum E { A B }",
  "enum E { A\nB }", "enum E { A = 1\nB }", "enum E { A; B }", "enum E { A; }", "enum E { A = }", "enum E { = 1 }", "enum E { , }", "enum E { ,A }",
  "enum E { A,, B }", "enum E { A,, }", "enum E { A = B.C }", "enum E { A = 1 << 2, B = A | 1, C = -A, D = ~A, E = 'a'.length, F = f() }",
  "enum E { A = (1) }", "enum E { A = 1 as any }", "enum E { A = <any>1 }", "enum E { A = 1! }", "enum E { A = 1 satisfies number }", "enum E { A = a ? 1 : 2 }",
  "enum E { A = a, b }", "enum E { A = (a, b) }", "enum E { A = 1 in a }", "enum E { A = () => 1 }", "enum E { A = (a: A): B => a }", "enum E { A = <T>(a: T) => a }",
  "enum E { A = function () {} }", "enum E { A = class {} }", "enum E { A = yield }", "enum E { A = await 1 }", "enum E { A = await }", "enum E { A = this }",
  "enum E { A = new.target }", "enum E { A = import.meta }", "enum E { A = a = 1 }", "enum E { A = [1] }", "enum E { A = {} }", "enum E { A = `a` }",
  "enum E { A = `a${1}` }", "enum E { A = 'a' + 'b' }", "enum E { A = E.B, B = 1 }", "enum E { A = B, B = 1 }", "enum E { A = A }", "enum E { A, A }",
  "enum E { A = f<T>(a) }", "enum E { A = a<b>(c) }", "enum E { A = a < b > c }", "enum E { A = a<B> }", "enum E { A = typeof a }", "enum E { A = void 0 }",
  "enum E { if, class, default, function, new, typeof, void, null, true, this, in, instanceof }", "enum E { type, as, of, async, await, yield, let, static }",
  "enum E { if = 1 }", "enum E { in = 1 }", "enum E { constructor }", "enum E { prototype }", "enum E { __proto__ }", "enum E { Infinity, NaN, undefined }",
  "enum E { A: 1 }", "enum E { A() {} }", "enum E { get A }", "enum E { get A() { return 1 } }", "enum E { static A }", "enum E { readonly A }",
  "enum E { public A }", "enum E { declare A }", "enum E { ...a }", "enum E { A? }", "enum E { A! }", "enum E { A?: 1 }", "enum E { @d A }",
  "enum E { A = 1, }", "enum E {\n  A,\n  B,\n}", "enum E {\n  A = 1\n  ,B\n}", "enum E { /* c */ A /* d */ = /* e */ 1 /* f */ , }",
  "enum {}", "enum E", "enum E;", "enum", "enum;", "enum E {", "enum E { A", "enum E { A =", "enum E }", "enum\nE {}", "enum E\n{}", "enum E<T> {}",
  "enum E extends F {}", "enum E implements F {}", "enum E.F {}", 'enum "E" {}', "enum 1 {}", "enum E() {}", "enum E = {}", "enum E {};",
  "const enum E {}", "const enum E { A = 1, B = A }", "const enum E { A = 'a', B = `b` }", "const\nenum E {}", "const enum\nE {}", "const enum", "const enum;",
  "const enum {}", "const const enum E {}", "enum const E {}", "let enum E {}", "var enum E {}", "export enum E {}", "export const enum E {}",
  "export default enum E {}", "export default const enum E {}", "declare enum E {}", "declare const enum E {}", "export declare enum E {}",
  "export declare const enum E {}", "async enum E {}", "abstract enum E {}", "static enum E {}", "public enum E {}", "readonly enum E {}", "@d enum E {}",
  "enum E {} enum E {}", "enum E { A } enum E { B = A }", "enum E { A }\nenum E { B = 1 }", "enum E { A } namespace E { export const b = 1 }",
  "function f() { enum E { A } }", "{ enum E {} }", "if (a) enum E {}", "label: enum E {}", "for (;;) enum E {}", "class C { enum E {} }",
  "namespace N { enum E {} export enum F {} export const enum G {} }", "var v = enum E {};", "(enum E {})", "a = enum;", "enum.a;", "var enum = 1;",
  ...each(words, w => `enum ${w} {}`),
  ...each(words, w => `enum E { ${w} }`),
  ...each(words, w => `enum E { ${w} = 1 }`),
];

writeGroup("08-declare-namespace-enum-ambient.txt", "declare, namespace, enum, ambient modules.", [
  { prefix: "declare", kind: "file", items: declares },
  { prefix: "namespace", kind: "file", items: namespaces },
  { prefix: "enum", kind: "file", items: enums },
]);
