#!/usr/bin/env bun
// Module syntax: type-only imports and exports, import equals, export assignment, export as namespace.
// Reference: parseImportDeclarationOrImportEqualsDeclaration 2279, parseImportEqualsDeclaration 2343, parseModuleReference 2352,
// parseImportClause 2393, parseImportOrExportSpecifier 2457, parseExportAssignment 2555, parseNamespaceExportDeclaration 2575,
// parseExportDeclaration 2588, tryParseImportAttributes 2545, parseDeclarationWorker 1151 (export).
import { each, writeGroup } from "./gen-lib.mjs";

const words = ["type", "as", "from", "of", "async", "await", "yield", "let", "static", "default", "if", "class", "function", "defer", "source", "module", "namespace", "global", "declare", "abstract", "interface", "enum", "any", "string", "undefined", "arguments", "eval", "implements", "package", "public"];

const imports = [
  'import type A from "m";', 'import type { A } from "m";', 'import type * as A from "m";', 'import type A, { B } from "m";',
  'import type A, * as B from "m";', 'import type from "m";', 'import type, { A } from "m";', 'import type, * as A from "m";',
  'import type type from "m";', 'import type from from "m";', 'import type as from "m";', 'import type * as from from "m";',
  'import type * as type from "m";', 'import type * as as from "m";', 'import type { type } from "m";', 'import type { type A } from "m";',
  'import type { A as B } from "m";', 'import type { default as A } from "m";', 'import type { "a" as b } from "m";', 'import type {} from "m";',
  'import type { A, } from "m";', 'import type { A, B as C, } from "m";', 'import type { , } from "m";', 'import type { A B } from "m";',
  'import type "m";', "import type;", "import type", 'import type A;', 'import type A from;', 'import type { A };', 'import type * from "m";',
  'import type * as from "m";', 'import type A, B from "m";', 'import type { A }, B from "m";', 'import type A from "m" with { type: "json" };',
  'import type { A } from "m" with { "resolution-mode": "import" };', 'import type { A } from "m" assert { "resolution-mode": "import" };',
  'import type A from "m"\nimport type B from "n"', 'import type\nA from "m";', 'import\ntype A from "m";', 'import type A\nfrom "m";',
  'import type A from\n"m";', 'import type\n{ A } from "m";', 'import type\n* as A from "m";', 'import type\nfrom "m";',
  'import type A = require("m");', "import type A = B.C;", "import type A = B;", 'import type type = require("m");', "import type = B;",
  'import type = require("m");', "import type from = B;", 'import type from = require("m");', "import type as = B;",
  'import A = require("m");', "import A = B.C.D;", "import A = B;", "import A = B.default;", "import A = B.class;", "import A = class;",
  'import A = require("m").B;', "import A = require(m);", "import A = require();", 'import A = require("m", "n");', "import A = require;",
  "import A = require.B;", "import A = B<C>;", "import A = B[0];", "import A = B();", "import A = typeof B;", "import A = import('m');",
  "import A = 1;", 'import A = "m";', "import A =", "import A = B.;", "import A = B.#c;", "import A = this;", "import A = this.B;",
  "import A\n= B;", "import A =\nB;", "import A = B\n.C;", 'import { A } = require("m");', "import * as A = B;", 'import A, B = require("m");',
  'export import A = B.C;', 'export import A = require("m");', "export import type A = B;", 'export import type A = require("m");',
  "export import A = B;\nexport import C = D.E;", "export default import A = B;", "declare import A = B;", "export declare import A = B;",
  'import { type A } from "m";', 'import { type A as B } from "m";', 'import { type } from "m";', 'import { type as } from "m";',
  'import { type as as } from "m";', 'import { type as as as } from "m";', 'import { type as as as as } from "m";', 'import { type type } from "m";',
  'import { type type as type } from "m";', 'import { type as type } from "m";', 'import { type "a" as b } from "m";', 'import { type "a" } from "m";',
  'import { type default as A } from "m";', 'import { type default } from "m";', 'import { type if as A } from "m";', 'import { type A as if } from "m";',
  'import { type A, B, type C as D } from "m";', 'import { type, A } from "m";', 'import { A, type } from "m";', 'import { type as, A } from "m";',
  'import { type\nA } from "m";', 'import { type A, } from "m";', 'import { type A B } from "m";', 'import { type type type } from "m";',
  'import { type as B } from "m";', 'import { type as as B } from "m";', 'import { type as as as B } from "m";', 'import { type from } from "m";',
  'import { type from as from } from "m";', 'import { type of } from "m";', 'import { type await } from "m";', 'import { type yield } from "m";',
  'import { type 1 } from "m";', 'import { type * as A } from "m";', 'import { type { A } } from "m";', 'import { type A.B } from "m";',
  'import { "a" as type } from "m";', 'import { a as type } from "m";', 'import { type as "a" } from "m";', 'import { type A as "b" } from "m";',
  'import A, { type B } from "m";', 'import A, type { B } from "m";', 'import A, type B from "m";', 'import { A }, type { B } from "m";',
  'import a from "m" with { type: "json" };', 'import a from "m" assert { type: "json" };', 'import a from "m"\nassert { type: "json" };',
  'import a from "m"\nwith { type: "json" };', 'import "m" with {};', 'import "m" with { type: "json", };', 'import "m" with { "type": "json" };',
  'import "m" with { type: 1 };', 'import "m" with { type };', 'import "m" with { [type]: "json" };', 'import "m" with { 1: "json" };',
  'import "m" with', 'import "m" with { type: "json" } with { a: "b" };', 'import "m" as A;', 'import a from "m" as A;',
  'import defer * as a from "m";', 'import defer from "m";', 'import defer a from "m";', 'import defer { a } from "m";', 'import defer, { a } from "m";',
  'import defer = B;', 'import defer from from "m";', 'import defer * as defer from "m";', 'import source a from "m";', 'import source from "m";',
  'import("m");', 'import("m") as A;', 'import<A>("m");', "import.meta as A;", "import.meta!;", 'import("m")!;', 'import("m", { with: { type: "json" } });',
  'var v = import("m") as Promise<A>;', 'var v = <A>import("m");', 'var v = await import("m") as A;', "import type('m');", "import type.a;",
  ...each(words, w => `import type ${w} from "m";`),
  ...each(words, w => `import type { ${w} } from "m";`),
  ...each(words, w => `import { type ${w} } from "m";`),
  ...each(words, w => `import { type ${w} as A } from "m";`),
  ...each(words, w => `import { type A as ${w} } from "m";`),
  ...each(words, w => `import ${w} = A.B;`),
  ...each(words, w => `import type ${w} = A.B;`),
  ...each(words, w => `import A = ${w}.B;`),
  ...each(words, w => `import A = B.${w};`),
];

const exports_ = [
  "export type { A };", 'export type { A } from "m";', 'export type { A as B } from "m";', 'export type { A as default } from "m";',
  'export type { default } from "m";', 'export type { default as A } from "m";', 'export type { "a" as b } from "m";', 'export type { A as "b" } from "m";',
  'export type * from "m";', 'export type * as A from "m";', 'export type * as default from "m";', 'export type * as "a" from "m";',
  'export type * as type from "m";', 'export type * as from from "m";', 'export type * as as from "m";', "export type *;", "export type * as A;",
  'export type * from;', 'export type * as from "m";', 'export type * as A, { B } from "m";', 'export type *, { A } from "m";',
  'export type * from "m" with { type: "json" };', 'export type { A } from "m" with { "resolution-mode": "import" };',
  "export type {};", 'export type {} from "m";', "export type { A, B as C, };", "export type { , };", "export type { A B };",
  "export type { type A };", "export type { type };", "export type { A }\nexport type { B }", "export type\n{ A };", "export type\nA = B;",
  "export type\n* from 'm';", "export type", "export type;", "export type = 1;", "export type A;", "export type A", "export type { A } from;",
  'export type { A } "m";', 'export type A from "m";', 'export type A, { B } from "m";', "export type { default };", "export type { if };",
  "export type { A as if };", "export type { if as A };", 'export type { if } from "m";', 'export type { "a" };', 'export type { "a" } from "m";',
  "export { type A };", "export { type A as B };", 'export { type A } from "m";', "export { type };", "export { type as };",
  "export { type as as };", "export { type as as as };", "export { type as as as as };", "export { type type };", "export { type type as type };",
  'export { type "a" } from "m";', 'export { type "a" as b } from "m";', 'export { type A as "b" };', 'export { type A as "b" } from "m";',
  'export { type default } from "m";', 'export { type default as A } from "m";', "export { type A as default };", "export { type as default };",
  "export { type A, B, type C as D };", "export { type, A };", "export { A, type };", "export { type\nA };", "export { type A, };",
  "export { type A B };", "export { type if };", 'export { type if } from "m";', "export { type A as if };", "export { type * };",
  "export { type { A } };", "export { type A.B };", "export { type 1 };", "export { A as type };", "export { type as type };",
  'export { type from } from "m";', "export { type from };", "export { type of };", "export { type await };", "export { type yield };",
  "export {};", 'export {} from "m";', "export { A, };", "export { , };", "export { A as B, C as default };", 'export { default } from "m";',
  'export { default as default } from "m";', 'export * from "m";', 'export * as A from "m";', 'export * as default from "m";',
  'export * as "a" from "m";', 'export * from "m" with { type: "json" };', 'export { a } from "m" with { type: "json" };',
  'export { a } from "m" assert { type: "json" };', 'export { a } "m";', "export { a } from;", "export * as A;", "export *;", "export * as;",
  "export = A;", "export = A.B;", "export = { a: 1 };", "export = class {};", "export = class C<T> {};", "export = function () {};",
  "export = function f<T>(a: T): T { return a };", "export = <T>(a: T) => a;", "export = a as A;", "export = <A>a;", "export = a!;",
  "export = 1;", 'export = "s";', "export = [a];", "export = a, b;", "export = a = b;", "export =", "export =;", "export = A\nexport = B",
  "export\n= A;", "export =\nA;", "export = A; export default B;", "export = interface I {}", "export = type X = 1", "export = enum E {}",
  "export = namespace N {}", "export = declare class C {}", "export = abstract class C {}", "export = async function () {}",
  "export = await a;", "export = yield;", "export = import('m');", "export = new A();", "export = typeof a;", "export = a ? b : c;",
  "declare export = A;", "export declare = A;", "export default = A;", "@d export = A;", "namespace N { export = A }", "{ export = A }",
  "function f() { export = A }", "if (a) export = A;",
  "export as namespace A;", "export as namespace A", "export as namespace A.B;", "export as namespace;", "export as namespace",
  "export as namespace default;", "export as namespace type;", "export as namespace as;", "export as namespace namespace;",
  'export as namespace "A";', "export as namespace A, B;", "export as namespace A = B;", "export as namespace A {}", "export as A;",
  "export as;", "export as", "export as module A;", "export as\nnamespace A;", "export as namespace\nA;", "export\nas namespace A;",
  "export as namespace A;\nexport as namespace B;", "declare export as namespace A;", "export declare as namespace A;",
  "@d export as namespace A;", "export default as namespace A;", "namespace N { export as namespace A }", "{ export as namespace A }",
  "export as namespace if;", "export as namespace await;", "export as namespace yield;", "export as namespace 1;",
  "export default A;", "export default interface I {}", "export default interface I<T> extends J<T> { a: A }", "export default interface {}",
  "export default interface\nI {}", "export default abstract class C {}", "export default abstract\nclass C {}", "export default enum E {}",
  "export default const enum E {}", "export default namespace N {}", "export default module M {}", "export default type X = A;",
  "export default declare class C {}", "export default declare function f(): void;", "export default async function f<T>() {}",
  "export default function <T>(a: T): T { return a }", "export default class<T> {}", "export default class implements I {}",
  "export default class C<T> extends D<T> implements I<T> {}", "export default (a: A): B => a;", "export default a as A;",
  "export default <A>a;", "export default a!;", "export default a satisfies A;", "export default { a: 1 } as const;", "export default type;",
  "export default type", "export default interface;", "export default abstract;", "export default declare;", "export default namespace;",
  "export default module;", "export default async;", "export default of;", "export default as;", "export default from;",
  "export default function f(): void;", "export default function (): void;", "export default var a: A;", "export default let a;",
  "export default const a = 1;", "export default a, b;", "export default;", "export default", "export default default;",
  "export default export default a;", "export default import a from 'm';", "export default @d class {}", "@d export default class {}",
  "export default @d abstract class {}", "export default abstract @d class {}", "export default async <T>(a: T) => a;",
  "export default async (a: A): Promise<B> => a;", "export default class { a: A; m(): void {} }", "export default function f(this: A) {}",
  "export declare const a: A;", "export declare let a: A, b: B;", "export declare var a;", "export declare function f(): void;",
  "export declare function f(): void", "export declare class C {}", "export declare enum E {}", "export declare const enum E {}",
  "export declare namespace N {}", "export declare module M {}", 'export declare module "m" {}', "export declare global {}",
  "export declare type X = A;", "export declare interface I {}", "export declare abstract class C {}", "export declare async function f(): void;",
  "export declare function* f(): void;", "export declare default class {}", "export declare;", "export declare", "export declare a;",
  "export declare { a };", "export declare * from 'm';", "export declare export const a: A;", "export declare declare const a: A;",
  "export declare\nconst a: A;", "export\ndeclare const a: A;", "declare export const a: A;", "declare export function f(): void;",
  "declare export class C {}", "declare export default class {}", "declare export { a };", "declare export * from 'm';",
  "export abstract class C {}", "export const enum E {}", "export enum E {}", "export namespace N {}", "export module M {}",
  "export interface I {}", "export async function f<T>() {}", "export function f<T>(a: T): T { return a }", "export class C<T> {}",
  "export const a: A = 1;", "export let a: A, b: B = 2;", "export var a: A;", "export const f = <T>(a: T) => a;", "export const f = (a: A): B => a;",
  "export const a = b as A;", "export const a = <A>b;", "export const a = b!;", "export const { a, b }: A = c;", "export const [a, b]: A = c;",
  "export let a!: A;", "export using a: A = b;", "export async;", "export type;", "export interface;", "export abstract;", "export namespace;",
  "export a;", "export A.B;", "export 1;", "export;", "export", "export export const a = 1;", "export public class C {}", "export static a;",
  "export readonly a;", "export import a from 'm';", "export import 'm';", "export import * as a from 'm';", "export import { a } from 'm';",
  "export function f(): void;", "export function f(): void; export function f(a?: any) {}", "export async function f(): Promise<void>;",
  "export class C { m(): void; m(a?: any) {} }", "export abstract class C { abstract m(): void }",
];

writeGroup("07-module-syntax.txt", "Module syntax.", [
  { prefix: "import", kind: "file", items: imports },
  { prefix: "export", kind: "file", items: exports_ },
]);
