// The inputs of the directive table: name, source. Every "//" and "/*" in them starts a comment.
const rows = [
  ["line-ignore", `// @ts-ignore\nlet x: number = 'a';`],
  ["line-expect-error", `// @ts-expect-error\nlet x: number = 'a';`],
  ["three-slashes", `/// @ts-ignore\nlet x;`],
  ["four-slashes", `//// @ts-ignore\nlet x;`],
  ["no-space-with-reason", `//@ts-expect-error: reason\nlet x;`],
  ["tab-and-space", `//\t @ts-ignore\nlet x;`],
  ["no-break-space", `//\u00a0@ts-ignore\nlet x;`],
  ["words-before", `// x @ts-ignore\nlet x;`],
  ["space-after-at", `// @ ts-ignore\nlet x;`],
  ["upper-case", `// @TS-IGNORE\nlet x;`],
  ["longer-word", `// @ts-ignored @ts-expect-errors\nlet x;`],
  ["nocheck-is-no-directive", `// @ts-nocheck\nlet x;`],
  ["trailing-comment", `let x; // @ts-ignore\nlet y;`],
  ["at-end-of-file", `let x;\n// @ts-expect-error`],
  ["block-one-line", `/* @ts-ignore */\nlet x;`],
  ["block-jsdoc-one-line", `/** @ts-expect-error */\nlet x;`],
  ["block-last-line", `/*\n * a\n * @ts-ignore */\nlet x;`],
  ["block-first-line-of-two", `/* @ts-ignore\n */\nlet x;`],
  ["block-middle-line", `/*\n * @ts-ignore\n * b\n */\nlet x;`],
  ["block-last-line-bare", `/*\n@ts-expect-error*/\nlet x;`],
  ["block-last-line-tab-stars", `/*\n\t ** @ts-expect-error */\nlet x;`],
  ["block-star-space-slash", `/*\n\t * / ** @ts-ignore */\nlet x;`],
  ["block-no-break-space-on-last-line", `/*\n\u00a0@ts-ignore */`],
  ["block-line-separator", `/* a\u2028 @ts-expect-error */\nlet x;`],
  ["two-blocks-on-a-line", `/* @ts-ignore */ /* @ts-expect-error */\nlet x;`],
  ["line-comment-holds-a-block", `// /* @ts-ignore */\nlet x;`],
  ["crlf", `// @ts-ignore\r\nlet x;\r\n/*\r\n * @ts-expect-error */\r\nlet y;\r\n`],
  ["carriage-return-only", `/*\r * @ts-ignore */\rlet x;`],
  ["after-hashbang", `#!/usr/bin/env bun\n// @ts-expect-error\nlet x: number = 'a';`],
  ["non-ascii-before", `/* \u00e9\n * \u00e9 */ /*\u00e9\n@ts-ignore */\nlet x;`],
  ["mixed", `// @ts-ignore\nlet a;\n/* @ts-expect-error */\nlet b;\n/*\n * a\n * @ts-ignore */\nlet c; // @ts-expect-error`],
];
require("fs").writeFileSync(__dirname + "/inputs.json", JSON.stringify(rows, null, 1));
console.error(rows.length + " inputs");
