
[package]
name = "bun-macro"
description = "Proc macros for writing Bun native plugins."
license = "MIT"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
napi = "2.16.13"
anyhow = "1.0.94"
