name: 🇹 TypeScript Type Bug Report
description: Report an issue with TypeScript types
labels: [bug, types]
body:
- type: markdown
  attributes:
    value: |
      Thank you for submitting a bug report. It helps make Bun better.

      If you need help or support using Bun, and are not reporting a bug, please
      join our [Discord](https://discord.gg/CXdq2DP29u) server, where you can ask questions in the [`#help`](https://discord.gg/32EtH6p7HN) forum.

      Make sure you are running the [latest](https://bun.sh/docs/installation#upgrading) version of Bun.
      The bug you are experiencing may already have been fixed.

      Please try to include as much information as possible.

- type: input
  attributes:
    label: What version of Bun is running?
    description: Copy the output of `bun --revision`
- type: input
  attributes:
    label: What platform is your computer?
    description: |
      For MacOS and Linux: copy the output of `uname -mprs`
      For Windows: copy the output of `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"` in the PowerShell console
- type: textarea
  attributes:
    label: What steps can reproduce the bug?
    description: Explain the bug and provide a code snippet that can reproduce it.
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the expected behavior?
    description: If possible, please provide text instead of a screenshot.
- type: textarea
  attributes:
    label: What do you see instead?
    description: If possible, please provide text instead of a screenshot.
- type: textarea
  attributes:
    label: Additional information
    description: Is there anything else you think we should know?
