name: Crash
description: CRASH
labels: [bug, crash]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a crash report. It helps make Bun better.

  - type: textarea
    id: remapped_trace
    attributes:
      label: Stack Trace
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any extra info?
      description: If this is a reproducible bug, please provide a code snippet or list of steps that can reproduce it.
