blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: https://discord.com/invite/CXdq2DP29u
    about: Join our Discord server for questions, support requests, or just to chat.
