[package]
name = "bun_libuv_sys"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[lints]
workspace = true

[dependencies]
strum.workspace = true
libc.workspace = true

[target.'cfg(any(windows, bun_portable))'.dependencies]
bun_windows_sys.workspace = true
bun_wyhash.workspace = true
bun_core.workspace = true

[target.'cfg(bun_portable)'.dependencies]
bun_portable_macros.workspace = true
