/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSGPUBufferBinding.h"

#include "JSDOMBindingFacade.h"
#include "JSDOMConvertInterface.h"
#include "JSDOMConvertNumbers.h"
#include "JSDOMConvertOptional.h"
#include "JSGPUBuffer.h"
#include <type_traits>
#include <wtf/IsIncreasing.h>



namespace WebCore {
using namespace JSC;

IGNORE_WARNINGS_BEGIN("invalid-offsetof")

static_assert(std::is_aggregate_v<GPUBufferBinding>);
static_assert(IsIncreasing<
      0
    , offsetof(GPUBufferBinding, buffer)
    , offsetof(GPUBufferBinding, offset)
    , offsetof(GPUBufferBinding, size)
>);

IGNORE_WARNINGS_END

template<> ConversionResult<IDLDictionary<GPUBufferBinding>> convertDictionary<GPUBufferBinding>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (!isNullOrUndefined && !object) [[unlikely]] {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return ConversionResultException { };
    }
    JSValue bufferValue;
    if (isNullOrUndefined)
        bufferValue = jsUndefined();
    else {
        bufferValue = WebCore::get(object, &lexicalGlobalObject, Identifier::fromString(vm, "buffer"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (bufferValue.isUndefined()) {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "buffer"_s, "GPUBufferBinding"_s, "GPUBuffer"_s);
        return ConversionResultException { };
    }
    auto bufferConversionResult = convertResult<IDLInterface<GPUBuffer>>(lexicalGlobalObject, bufferValue);
    if (bufferConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    JSValue offsetValue;
    if (isNullOrUndefined)
        offsetValue = jsUndefined();
    else {
        offsetValue = WebCore::get(object, &lexicalGlobalObject, Identifier::fromString(vm, "offset"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    auto offsetConversionResult = convertOptionalWithDefault<IDLEnforceRangeAdaptor<IDLUnsignedLongLong>>(lexicalGlobalObject, offsetValue, [&] -> ConversionResult<IDLEnforceRangeAdaptor<IDLUnsignedLongLong>> { return Converter<IDLEnforceRangeAdaptor<IDLUnsignedLongLong>>::ReturnType { 0 }; });
    if (offsetConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    JSValue sizeValue;
    if (isNullOrUndefined)
        sizeValue = jsUndefined();
    else {
        sizeValue = WebCore::get(object, &lexicalGlobalObject, Identifier::fromString(vm, "size"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    auto sizeConversionResult = convertResult<IDLOptional<IDLEnforceRangeAdaptor<IDLUnsignedLongLong>>>(lexicalGlobalObject, sizeValue);
    if (sizeConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    return GPUBufferBinding {
        bufferConversionResult.releaseReturnValue(),
        offsetConversionResult.releaseReturnValue(),
        sizeConversionResult.releaseReturnValue(),
    };
}

} // namespace WebCore

