/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSGPUOrigin2DDict.h"

#include "JSDOMBindingFacade.h"
#include "JSDOMConvertNumbers.h"
#include "JSDOMConvertOptional.h"
#include <type_traits>
#include <wtf/IsIncreasing.h>



namespace WebCore {
using namespace JSC;

IGNORE_WARNINGS_BEGIN("invalid-offsetof")

static_assert(std::is_aggregate_v<GPUOrigin2DDict>);
static_assert(IsIncreasing<
      0
    , offsetof(GPUOrigin2DDict, x)
    , offsetof(GPUOrigin2DDict, y)
>);

IGNORE_WARNINGS_END

template<> ConversionResult<IDLDictionary<GPUOrigin2DDict>> convertDictionary<GPUOrigin2DDict>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (!isNullOrUndefined && !object) [[unlikely]] {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return ConversionResultException { };
    }
    JSValue xValue;
    if (isNullOrUndefined)
        xValue = jsUndefined();
    else {
        xValue = WebCore::get(object, &lexicalGlobalObject, Identifier::fromString(vm, "x"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    auto xConversionResult = convertOptionalWithDefault<IDLEnforceRangeAdaptor<IDLUnsignedLong>>(lexicalGlobalObject, xValue, [&] -> ConversionResult<IDLEnforceRangeAdaptor<IDLUnsignedLong>> { return Converter<IDLEnforceRangeAdaptor<IDLUnsignedLong>>::ReturnType { 0 }; });
    if (xConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    JSValue yValue;
    if (isNullOrUndefined)
        yValue = jsUndefined();
    else {
        yValue = WebCore::get(object, &lexicalGlobalObject, Identifier::fromString(vm, "y"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    auto yConversionResult = convertOptionalWithDefault<IDLEnforceRangeAdaptor<IDLUnsignedLong>>(lexicalGlobalObject, yValue, [&] -> ConversionResult<IDLEnforceRangeAdaptor<IDLUnsignedLong>> { return Converter<IDLEnforceRangeAdaptor<IDLUnsignedLong>>::ReturnType { 0 }; });
    if (yConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    return GPUOrigin2DDict {
        xConversionResult.releaseReturnValue(),
        yConversionResult.releaseReturnValue(),
    };
}

} // namespace WebCore

