//! What is known about the elements of HTML: `ml_parser/html_tags.ts` of `angular-html-parser`, and the tables
//! that Prettier takes from `html-ua-styles`, `@prettier/html-tags`, `html-element-attributes` and
//! `@prettier/html-event-attributes`.

use super::lexer::ContentType;

/// The value of the CSS property `display`, as far as anything depends on it.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(crate) enum Display {
    None,
    Block,
    ListItem,
    InlineBlock,
    /// It starts with `table` and is not `table-cell`.
    Table,
    TableCell,
    /// `inline` and everything else.
    Inline,
}

impl Display {
    /// The display that a comment asks for.
    pub(crate) fn from_name(name: &[u8]) -> Display {
        match name {
            b"none" => Display::None,
            b"block" => Display::Block,
            _ if name.starts_with(b"table") => Display::Table,
            _ => Display::Inline,
        }
    }

    /// `isBlockLikeCssDisplay`
    pub(crate) fn is_block_like(self) -> bool {
        matches!(
            self,
            Display::Block | Display::ListItem | Display::Table | Display::TableCell
        )
    }
}

/// `HtmlTagDefinition`
#[derive(Debug)]
pub(crate) struct TagDefinition {
    closed_by_children: &'static [&'static [u8]],
    pub(crate) implicit_namespace_prefix: Option<&'static [u8]>,
    pub(crate) content_type: ContentType,
    pub(crate) closed_by_parent: bool,
    pub(crate) is_void: bool,
    pub(crate) ignore_first_lf: bool,
    pub(crate) prevent_namespace_inheritance: bool,
    pub(crate) can_self_close: bool,
}

impl TagDefinition {
    pub(crate) fn is_closed_by_child(&self, name: &[u8]) -> bool {
        self.is_void
            || self
                .closed_by_children
                .iter()
                .any(|it| it.eq_ignore_ascii_case(name))
    }
}

/// `name` and its length as a number. 0: it is empty, or has more than 15 bytes.
const fn key(name: &[u8]) -> u128 {
    let mut bytes = [0; 16];
    if name.len() < bytes.len() {
        bytes.split_at_mut(name.len()).0.copy_from_slice(name);
        bytes[15] = name.len() as u8;
    }
    u128::from_be_bytes(bytes)
}

/// Whether the keys of `table` grow, and none is 0.
const fn is_sorted<T>(table: &[(u128, T)]) -> bool {
    let (mut at, mut previous) = (0, 0);
    while at < table.len() {
        if table[at].0 <= previous {
            return false;
        }
        previous = table[at].0;
        at += 1;
    }
    true
}

/// What `table`, which is sorted, has for `name`.
fn lookup<T: Copy>(table: &[(u128, T)], name: &[u8]) -> Option<T> {
    let at = table
        .binary_search_by_key(&key(name), |entry| entry.0)
        .ok()?;
    table.get(at).map(|entry| entry.1)
}

/// Of an element that Angular's schema has, and that has no definition of its own.
const KNOWN: TagDefinition = TagDefinition {
    closed_by_children: &[],
    implicit_namespace_prefix: None,
    content_type: ContentType::ParsableData,
    closed_by_parent: false,
    is_void: false,
    ignore_first_lf: false,
    prevent_namespace_inheritance: false,
    can_self_close: false,
};

pub(crate) static DEFAULT_TAG_DEFINITION: TagDefinition = TagDefinition {
    can_self_close: true,
    ..KNOWN
};

const fn closed_by(children: &'static [&'static [u8]], closed_by_parent: bool) -> TagDefinition {
    TagDefinition {
        closed_by_children: children,
        closed_by_parent,
        ..KNOWN
    }
}

const fn namespace(prefix: &'static [u8], prevent_namespace_inheritance: bool) -> TagDefinition {
    TagDefinition {
        implicit_namespace_prefix: Some(prefix),
        prevent_namespace_inheritance,
        ..KNOWN
    }
}

const fn content(content_type: ContentType, ignore_first_lf: bool) -> TagDefinition {
    TagDefinition {
        content_type,
        ignore_first_lf,
        ..KNOWN
    }
}

const VOID: TagDefinition = TagDefinition {
    is_void: true,
    closed_by_parent: true,
    ..KNOWN
};
const P: TagDefinition = closed_by(
    &[
        b"address",
        b"article",
        b"aside",
        b"blockquote",
        b"div",
        b"dl",
        b"fieldset",
        b"footer",
        b"form",
        b"h1",
        b"h2",
        b"h3",
        b"h4",
        b"h5",
        b"h6",
        b"header",
        b"hgroup",
        b"hr",
        b"main",
        b"nav",
        b"ol",
        b"p",
        b"pre",
        b"section",
        b"table",
        b"ul",
    ],
    true,
);
const THEAD: TagDefinition = closed_by(&[b"tbody", b"tfoot"], false);
const TBODY: TagDefinition = closed_by(&[b"tbody", b"tfoot"], true);
const TFOOT: TagDefinition = closed_by(&[b"tbody"], true);
const TR: TagDefinition = closed_by(&[b"tr"], true);
const TD: TagDefinition = closed_by(&[b"td", b"th"], true);
const SVG: TagDefinition = namespace(b"svg", false);
const FOREIGN_OBJECT: TagDefinition = namespace(b"svg", true);
const MATH: TagDefinition = namespace(b"math", false);
const LI: TagDefinition = closed_by(&[b"li"], true);
const DT: TagDefinition = closed_by(&[b"dt", b"dd"], false);
const DD: TagDefinition = closed_by(&[b"dt", b"dd"], true);
const RB: TagDefinition = closed_by(&[b"rb", b"rt", b"rtc", b"rp"], true);
const RTC: TagDefinition = closed_by(&[b"rb", b"rtc", b"rp"], true);
const OPTGROUP: TagDefinition = closed_by(&[b"optgroup"], true);
const OPTION: TagDefinition = closed_by(&[b"option", b"optgroup"], true);
const PRE: TagDefinition = content(ContentType::ParsableData, true);
const RAW: TagDefinition = content(ContentType::RawText, false);
const TITLE: TagDefinition = content(ContentType::EscapableRawText, false);
const TEXTAREA: TagDefinition = content(ContentType::EscapableRawText, true);

/// What `getHtmlTagDefinition` knows, sorted by the keys.
const TAG_DEFINITIONS: &[(u128, &TagDefinition)] = &[
    (key(b"[element]"), &KNOWN),
    (key(b"[htmlelement]"), &KNOWN),
    (key(b"a"), &KNOWN),
    (key(b"abbr"), &KNOWN),
    (key(b"address"), &KNOWN),
    (key(b"area"), &VOID),
    (key(b"article"), &KNOWN),
    (key(b"aside"), &KNOWN),
    (key(b"audio"), &KNOWN),
    (key(b"b"), &KNOWN),
    (key(b"base"), &VOID),
    (key(b"bdi"), &KNOWN),
    (key(b"bdo"), &KNOWN),
    (key(b"blockquote"), &KNOWN),
    (key(b"body"), &KNOWN),
    (key(b"br"), &VOID),
    (key(b"button"), &KNOWN),
    (key(b"canvas"), &KNOWN),
    (key(b"caption"), &KNOWN),
    (key(b"cite"), &KNOWN),
    (key(b"code"), &KNOWN),
    (key(b"col"), &VOID),
    (key(b"colgroup"), &KNOWN),
    (key(b"content"), &KNOWN),
    (key(b"data"), &KNOWN),
    (key(b"datalist"), &KNOWN),
    (key(b"dd"), &DD),
    (key(b"del"), &KNOWN),
    (key(b"details"), &KNOWN),
    (key(b"dfn"), &KNOWN),
    (key(b"dialog"), &KNOWN),
    (key(b"dir"), &KNOWN),
    (key(b"div"), &KNOWN),
    (key(b"dl"), &KNOWN),
    (key(b"dt"), &DT),
    (key(b"em"), &KNOWN),
    (key(b"embed"), &VOID),
    (key(b"fieldset"), &KNOWN),
    (key(b"figcaption"), &KNOWN),
    (key(b"figure"), &KNOWN),
    (key(b"font"), &KNOWN),
    (key(b"footer"), &KNOWN),
    (key(b"foreignObject"), &FOREIGN_OBJECT),
    (key(b"form"), &KNOWN),
    (key(b"frame"), &KNOWN),
    (key(b"frameset"), &KNOWN),
    (key(b"geolocation"), &KNOWN),
    (key(b"h1"), &KNOWN),
    (key(b"h2"), &KNOWN),
    (key(b"h3"), &KNOWN),
    (key(b"h4"), &KNOWN),
    (key(b"h5"), &KNOWN),
    (key(b"h6"), &KNOWN),
    (key(b"head"), &KNOWN),
    (key(b"header"), &KNOWN),
    (key(b"hgroup"), &KNOWN),
    (key(b"hr"), &VOID),
    (key(b"html"), &KNOWN),
    (key(b"i"), &KNOWN),
    (key(b"iframe"), &KNOWN),
    (key(b"img"), &VOID),
    (key(b"input"), &VOID),
    (key(b"ins"), &KNOWN),
    (key(b"kbd"), &KNOWN),
    (key(b"keygen"), &KNOWN),
    (key(b"label"), &KNOWN),
    (key(b"legend"), &KNOWN),
    (key(b"li"), &LI),
    (key(b"link"), &VOID),
    (key(b"listing"), &PRE),
    (key(b"main"), &KNOWN),
    (key(b"map"), &KNOWN),
    (key(b"mark"), &KNOWN),
    (key(b"marquee"), &KNOWN),
    (key(b"math"), &MATH),
    (key(b"media"), &KNOWN),
    (key(b"menu"), &KNOWN),
    (key(b"menuitem"), &KNOWN),
    (key(b"meta"), &VOID),
    (key(b"meter"), &KNOWN),
    (key(b"nav"), &KNOWN),
    (key(b"noscript"), &KNOWN),
    (key(b"object"), &KNOWN),
    (key(b"ol"), &KNOWN),
    (key(b"optgroup"), &OPTGROUP),
    (key(b"option"), &OPTION),
    (key(b"output"), &KNOWN),
    (key(b"p"), &P),
    (key(b"param"), &VOID),
    (key(b"picture"), &KNOWN),
    (key(b"pre"), &PRE),
    (key(b"progress"), &KNOWN),
    (key(b"q"), &KNOWN),
    (key(b"rb"), &RB),
    (key(b"rp"), &RB),
    (key(b"rt"), &RB),
    (key(b"rtc"), &RTC),
    (key(b"ruby"), &KNOWN),
    (key(b"s"), &KNOWN),
    (key(b"samp"), &KNOWN),
    (key(b"script"), &RAW),
    (key(b"search"), &KNOWN),
    (key(b"section"), &KNOWN),
    (key(b"select"), &KNOWN),
    (key(b"selectedcontent"), &KNOWN),
    (key(b"slot"), &KNOWN),
    (key(b"small"), &KNOWN),
    (key(b"source"), &VOID),
    (key(b"span"), &KNOWN),
    (key(b"strong"), &KNOWN),
    (key(b"style"), &RAW),
    (key(b"sub"), &KNOWN),
    (key(b"summary"), &KNOWN),
    (key(b"sup"), &KNOWN),
    (key(b"svg"), &SVG),
    (key(b"table"), &KNOWN),
    (key(b"tbody"), &TBODY),
    (key(b"td"), &TD),
    (key(b"template"), &KNOWN),
    (key(b"textarea"), &TEXTAREA),
    (key(b"tfoot"), &TFOOT),
    (key(b"th"), &TD),
    (key(b"thead"), &THEAD),
    (key(b"time"), &KNOWN),
    (key(b"title"), &TITLE),
    (key(b"tr"), &TR),
    (key(b"track"), &VOID),
    (key(b"u"), &KNOWN),
    (key(b"ul"), &KNOWN),
    (key(b"unknown"), &KNOWN),
    (key(b"var"), &KNOWN),
    (key(b"video"), &KNOWN),
    (key(b"wbr"), &VOID),
];
const _: () = assert!(is_sorted(TAG_DEFINITIONS));

/// `getHtmlTagDefinition`
pub(crate) fn tag_definition(name: &[u8]) -> &'static TagDefinition {
    lookup(TAG_DEFINITIONS, name).unwrap_or(&DEFAULT_TAG_DEFINITION)
}

/// `HTML_TAGS.has(name)`
pub(crate) fn is_html_tag(name: &[u8]) -> bool {
    HTML_TAGS.binary_search(&name).is_ok()
}

/// `htmlEventAttributes.has(name)`
pub(crate) fn is_event_attribute(name: &[u8]) -> bool {
    name.starts_with(b"on") && HTML_EVENT_ATTRIBUTES.binary_search(&name).is_ok()
}

/// Whether the element with the name `element` is known, and has an attribute with the name `attribute`.
pub(crate) fn is_attribute_of_element(element: &[u8], attribute: &[u8]) -> bool {
    attributes_of_element(element).is_some_and(|attributes| {
        attributes.binary_search(&attribute).is_ok()
            || attributes_of_element(b"*")
                .is_some_and(|attributes| attributes.binary_search(&attribute).is_ok())
    })
}

/// `CSS_DISPLAY_TAGS`, sorted by the keys.
const CSS_DISPLAY_TAGS: &[(u128, Display)] = &[
    (key(b"address"), Display::Block),
    (key(b"area"), Display::None),
    (key(b"article"), Display::Block),
    (key(b"aside"), Display::Block),
    (key(b"audio"), Display::InlineBlock),
    (key(b"base"), Display::None),
    (key(b"basefont"), Display::None),
    (key(b"blockquote"), Display::Block),
    (key(b"body"), Display::Block),
    (key(b"button"), Display::InlineBlock),
    (key(b"caption"), Display::Table),
    (key(b"center"), Display::Block),
    (key(b"col"), Display::Table),
    (key(b"colgroup"), Display::Table),
    (key(b"datalist"), Display::None),
    (key(b"dd"), Display::Block),
    (key(b"details"), Display::Block),
    (key(b"dialog"), Display::Block),
    (key(b"dir"), Display::Block),
    (key(b"div"), Display::Block),
    (key(b"dl"), Display::Block),
    (key(b"dt"), Display::Block),
    (key(b"fieldset"), Display::Block),
    (key(b"figcaption"), Display::Block),
    (key(b"figure"), Display::Block),
    (key(b"footer"), Display::Block),
    (key(b"form"), Display::Block),
    (key(b"h1"), Display::Block),
    (key(b"h2"), Display::Block),
    (key(b"h3"), Display::Block),
    (key(b"h4"), Display::Block),
    (key(b"h5"), Display::Block),
    (key(b"h6"), Display::Block),
    (key(b"head"), Display::None),
    (key(b"header"), Display::Block),
    (key(b"hgroup"), Display::Block),
    (key(b"hr"), Display::Block),
    (key(b"html"), Display::Block),
    (key(b"input"), Display::InlineBlock),
    (key(b"legend"), Display::Block),
    (key(b"li"), Display::ListItem),
    (key(b"link"), Display::None),
    (key(b"listing"), Display::Block),
    (key(b"main"), Display::Block),
    (key(b"marquee"), Display::InlineBlock),
    (key(b"menu"), Display::Block),
    (key(b"meta"), Display::None),
    (key(b"meter"), Display::InlineBlock),
    (key(b"nav"), Display::Block),
    (key(b"noembed"), Display::None),
    (key(b"noframes"), Display::None),
    (key(b"object"), Display::InlineBlock),
    (key(b"ol"), Display::Block),
    (key(b"optgroup"), Display::Block),
    (key(b"option"), Display::Block),
    (key(b"p"), Display::Block),
    (key(b"param"), Display::Block),
    (key(b"plaintext"), Display::Block),
    (key(b"pre"), Display::Block),
    (key(b"progress"), Display::InlineBlock),
    (key(b"rp"), Display::None),
    (key(b"rt"), Display::Inline),
    (key(b"ruby"), Display::Inline),
    (key(b"script"), Display::Block),
    (key(b"search"), Display::Block),
    (key(b"section"), Display::Block),
    (key(b"select"), Display::InlineBlock),
    (key(b"slot"), Display::Inline),
    (key(b"source"), Display::Block),
    (key(b"style"), Display::None),
    (key(b"summary"), Display::Block),
    (key(b"table"), Display::Table),
    (key(b"tbody"), Display::Table),
    (key(b"td"), Display::TableCell),
    (key(b"template"), Display::Inline),
    (key(b"tfoot"), Display::Table),
    (key(b"th"), Display::TableCell),
    (key(b"thead"), Display::Table),
    (key(b"title"), Display::None),
    (key(b"tr"), Display::Table),
    (key(b"track"), Display::Block),
    (key(b"ul"), Display::Block),
    (key(b"video"), Display::InlineBlock),
    (key(b"xmp"), Display::Block),
];
const _: () = assert!(is_sorted(CSS_DISPLAY_TAGS));

/// `CSS_DISPLAY_TAGS[name]`
pub(crate) fn css_display_of_tag(name: &[u8]) -> Option<Display> {
    lookup(CSS_DISPLAY_TAGS, name)
}

/// Whether `CSS_WHITE_SPACE_TAGS[name]` starts with `pre`.
pub(crate) fn is_pre_tag(name: &[u8]) -> bool {
    matches!(
        name,
        b"listing" | b"plaintext" | b"pre" | b"textarea" | b"xmp"
    )
}

/// `@prettier/html-tags`, sorted.
const HTML_TAGS: [&[u8]; 151] = [
    b"a",
    b"abbr",
    b"acronym",
    b"address",
    b"applet",
    b"area",
    b"article",
    b"aside",
    b"audio",
    b"b",
    b"base",
    b"basefont",
    b"bdi",
    b"bdo",
    b"bgsound",
    b"big",
    b"blink",
    b"blockquote",
    b"body",
    b"br",
    b"button",
    b"canvas",
    b"caption",
    b"center",
    b"cite",
    b"code",
    b"col",
    b"colgroup",
    b"command",
    b"content",
    b"data",
    b"datalist",
    b"dd",
    b"del",
    b"details",
    b"dfn",
    b"dialog",
    b"dir",
    b"div",
    b"dl",
    b"dt",
    b"em",
    b"embed",
    b"fencedframe",
    b"fieldset",
    b"figcaption",
    b"figure",
    b"font",
    b"footer",
    b"form",
    b"frame",
    b"frameset",
    b"geolocation",
    b"h1",
    b"h2",
    b"h3",
    b"h4",
    b"h5",
    b"h6",
    b"head",
    b"header",
    b"hgroup",
    b"hr",
    b"html",
    b"i",
    b"iframe",
    b"image",
    b"img",
    b"input",
    b"ins",
    b"isindex",
    b"kbd",
    b"keygen",
    b"label",
    b"legend",
    b"li",
    b"link",
    b"listing",
    b"main",
    b"map",
    b"mark",
    b"marquee",
    b"math",
    b"menu",
    b"menuitem",
    b"meta",
    b"meter",
    b"multicol",
    b"nav",
    b"nextid",
    b"nobr",
    b"noembed",
    b"noframes",
    b"noscript",
    b"object",
    b"ol",
    b"optgroup",
    b"option",
    b"output",
    b"p",
    b"param",
    b"picture",
    b"plaintext",
    b"pre",
    b"progress",
    b"q",
    b"rb",
    b"rbc",
    b"rp",
    b"rt",
    b"rtc",
    b"ruby",
    b"s",
    b"samp",
    b"script",
    b"search",
    b"section",
    b"select",
    b"selectedcontent",
    b"shadow",
    b"slot",
    b"small",
    b"source",
    b"spacer",
    b"span",
    b"strike",
    b"strong",
    b"style",
    b"sub",
    b"summary",
    b"sup",
    b"svg",
    b"table",
    b"tbody",
    b"td",
    b"template",
    b"textarea",
    b"tfoot",
    b"th",
    b"thead",
    b"time",
    b"title",
    b"tr",
    b"track",
    b"tt",
    b"u",
    b"ul",
    b"var",
    b"video",
    b"wbr",
    b"xmp",
];

/// `@prettier/html-event-attributes`, sorted.
const HTML_EVENT_ATTRIBUTES: [&[u8]; 90] = [
    b"onabort",
    b"onafterprint",
    b"onauxclick",
    b"onbeforeinput",
    b"onbeforematch",
    b"onbeforeprint",
    b"onbeforetoggle",
    b"onbeforeunload",
    b"onblur",
    b"oncancel",
    b"oncanplay",
    b"oncanplaythrough",
    b"onchange",
    b"onclick",
    b"onclose",
    b"oncommand",
    b"oncontextlost",
    b"oncontextmenu",
    b"oncontextrestored",
    b"oncopy",
    b"oncuechange",
    b"oncut",
    b"ondblclick",
    b"ondrag",
    b"ondragend",
    b"ondragenter",
    b"ondragleave",
    b"ondragover",
    b"ondragstart",
    b"ondrop",
    b"ondurationchange",
    b"onemptied",
    b"onended",
    b"onerror",
    b"onfocus",
    b"onformdata",
    b"onhashchange",
    b"oninput",
    b"oninvalid",
    b"onkeydown",
    b"onkeypress",
    b"onkeyup",
    b"onlanguagechange",
    b"onload",
    b"onloadeddata",
    b"onloadedmetadata",
    b"onloadstart",
    b"onmessage",
    b"onmessageerror",
    b"onmousedown",
    b"onmouseenter",
    b"onmouseleave",
    b"onmousemove",
    b"onmouseout",
    b"onmouseover",
    b"onmouseup",
    b"onoffline",
    b"ononline",
    b"onpagehide",
    b"onpagereveal",
    b"onpageshow",
    b"onpageswap",
    b"onpaste",
    b"onpause",
    b"onplay",
    b"onplaying",
    b"onpopstate",
    b"onprogress",
    b"onratechange",
    b"onrejectionhandled",
    b"onreset",
    b"onresize",
    b"onscroll",
    b"onscrollend",
    b"onsecuritypolicyviolation",
    b"onseeked",
    b"onseeking",
    b"onselect",
    b"onslotchange",
    b"onstalled",
    b"onstorage",
    b"onsubmit",
    b"onsuspend",
    b"ontimeupdate",
    b"ontoggle",
    b"onunhandledrejection",
    b"onunload",
    b"onvolumechange",
    b"onwaiting",
    b"onwheel",
];

/// `html-element-attributes`: the attributes of the element with the name, sorted. `*`: of all elements.
fn attributes_of_element(name: &[u8]) -> Option<&'static [&'static [u8]]> {
    Some(match name {
        b"*" => &[
            b"accesskey",
            b"autocapitalize",
            b"autocorrect",
            b"autofocus",
            b"class",
            b"contenteditable",
            b"dir",
            b"draggable",
            b"enterkeyhint",
            b"exportparts",
            b"hidden",
            b"id",
            b"inert",
            b"inputmode",
            b"is",
            b"itemid",
            b"itemprop",
            b"itemref",
            b"itemscope",
            b"itemtype",
            b"lang",
            b"nonce",
            b"part",
            b"popover",
            b"slot",
            b"spellcheck",
            b"style",
            b"tabindex",
            b"title",
            b"translate",
            b"writingsuggestions",
        ],
        b"a" => &[
            b"charset",
            b"coords",
            b"download",
            b"href",
            b"hreflang",
            b"name",
            b"ping",
            b"referrerpolicy",
            b"rel",
            b"rev",
            b"shape",
            b"target",
            b"type",
        ],
        b"applet" => &[
            b"align",
            b"alt",
            b"archive",
            b"code",
            b"codebase",
            b"height",
            b"hspace",
            b"name",
            b"object",
            b"vspace",
            b"width",
        ],
        b"area" => &[
            b"alt",
            b"coords",
            b"download",
            b"href",
            b"hreflang",
            b"nohref",
            b"ping",
            b"referrerpolicy",
            b"rel",
            b"shape",
            b"target",
            b"type",
        ],
        b"audio" => &[
            b"autoplay",
            b"controls",
            b"crossorigin",
            b"loop",
            b"muted",
            b"preload",
            b"src",
        ],
        b"base" => &[b"href", b"target"],
        b"basefont" | b"font" => &[b"color", b"face", b"size"],
        b"blockquote" | b"q" => &[b"cite"],
        b"body" => &[
            b"alink",
            b"background",
            b"bgcolor",
            b"link",
            b"text",
            b"vlink",
        ],
        b"br" => &[b"clear"],
        b"button" => &[
            b"command",
            b"commandfor",
            b"disabled",
            b"form",
            b"formaction",
            b"formenctype",
            b"formmethod",
            b"formnovalidate",
            b"formtarget",
            b"name",
            b"popovertarget",
            b"popovertargetaction",
            b"type",
            b"value",
        ],
        b"canvas" => &[b"height", b"width"],
        b"caption" | b"div" | b"h1" | b"h2" | b"h3" | b"h4" | b"h5" | b"h6" | b"legend" | b"p" => {
            &[b"align"]
        }
        b"col" | b"colgroup" => &[b"align", b"char", b"charoff", b"span", b"valign", b"width"],
        b"data" => &[b"value"],
        b"del" | b"ins" => &[b"cite", b"datetime"],
        b"details" => &[b"name", b"open"],
        b"dialog" => &[b"closedby", b"open"],
        b"dir" | b"dl" | b"menu" => &[b"compact"],
        b"embed" => &[b"height", b"src", b"type", b"width"],
        b"fieldset" => &[b"disabled", b"form", b"name"],
        b"form" => &[
            b"accept",
            b"accept-charset",
            b"action",
            b"autocomplete",
            b"enctype",
            b"method",
            b"name",
            b"novalidate",
            b"target",
        ],
        b"frame" => &[
            b"frameborder",
            b"longdesc",
            b"marginheight",
            b"marginwidth",
            b"name",
            b"noresize",
            b"scrolling",
            b"src",
        ],
        b"frameset" => &[b"cols", b"rows"],
        b"head" => &[b"profile"],
        b"hr" => &[b"align", b"noshade", b"size", b"width"],
        b"html" => &[b"manifest", b"version"],
        b"iframe" => &[
            b"align",
            b"allow",
            b"allowfullscreen",
            b"allowpaymentrequest",
            b"allowusermedia",
            b"frameborder",
            b"height",
            b"loading",
            b"longdesc",
            b"marginheight",
            b"marginwidth",
            b"name",
            b"referrerpolicy",
            b"sandbox",
            b"scrolling",
            b"src",
            b"srcdoc",
            b"width",
        ],
        b"img" => &[
            b"align",
            b"alt",
            b"border",
            b"crossorigin",
            b"decoding",
            b"fetchpriority",
            b"height",
            b"hspace",
            b"ismap",
            b"loading",
            b"longdesc",
            b"name",
            b"referrerpolicy",
            b"sizes",
            b"src",
            b"srcset",
            b"usemap",
            b"vspace",
            b"width",
        ],
        b"input" => &[
            b"accept",
            b"align",
            b"alpha",
            b"alt",
            b"autocomplete",
            b"checked",
            b"colorspace",
            b"dirname",
            b"disabled",
            b"form",
            b"formaction",
            b"formenctype",
            b"formmethod",
            b"formnovalidate",
            b"formtarget",
            b"height",
            b"ismap",
            b"list",
            b"max",
            b"maxlength",
            b"min",
            b"minlength",
            b"multiple",
            b"name",
            b"pattern",
            b"placeholder",
            b"popovertarget",
            b"popovertargetaction",
            b"readonly",
            b"required",
            b"size",
            b"src",
            b"step",
            b"type",
            b"usemap",
            b"value",
            b"width",
        ],
        b"isindex" => &[b"prompt"],
        b"label" => &[b"for", b"form"],
        b"li" => &[b"type", b"value"],
        b"link" => &[
            b"as",
            b"blocking",
            b"charset",
            b"color",
            b"crossorigin",
            b"disabled",
            b"fetchpriority",
            b"href",
            b"hreflang",
            b"imagesizes",
            b"imagesrcset",
            b"integrity",
            b"media",
            b"referrerpolicy",
            b"rel",
            b"rev",
            b"sizes",
            b"target",
            b"type",
        ],
        b"map" | b"slot" => &[b"name"],
        b"meta" => &[
            b"charset",
            b"content",
            b"http-equiv",
            b"media",
            b"name",
            b"scheme",
        ],
        b"meter" => &[b"high", b"low", b"max", b"min", b"optimum", b"value"],
        b"object" => &[
            b"align",
            b"archive",
            b"border",
            b"classid",
            b"codebase",
            b"codetype",
            b"data",
            b"declare",
            b"form",
            b"height",
            b"hspace",
            b"name",
            b"standby",
            b"type",
            b"typemustmatch",
            b"usemap",
            b"vspace",
            b"width",
        ],
        b"ol" => &[b"compact", b"reversed", b"start", b"type"],
        b"optgroup" => &[b"disabled", b"label"],
        b"option" => &[b"disabled", b"label", b"selected", b"value"],
        b"output" => &[b"for", b"form", b"name"],
        b"param" => &[b"name", b"type", b"value", b"valuetype"],
        b"pre" => &[b"width"],
        b"progress" => &[b"max", b"value"],
        b"script" => &[
            b"async",
            b"blocking",
            b"charset",
            b"crossorigin",
            b"defer",
            b"fetchpriority",
            b"integrity",
            b"language",
            b"nomodule",
            b"referrerpolicy",
            b"src",
            b"type",
        ],
        b"select" => &[
            b"autocomplete",
            b"disabled",
            b"form",
            b"multiple",
            b"name",
            b"required",
            b"size",
        ],
        b"source" => &[
            b"height", b"media", b"sizes", b"src", b"srcset", b"type", b"width",
        ],
        b"style" => &[b"blocking", b"media", b"type"],
        b"table" => &[
            b"align",
            b"bgcolor",
            b"border",
            b"cellpadding",
            b"cellspacing",
            b"frame",
            b"rules",
            b"summary",
            b"width",
        ],
        b"tbody" | b"tfoot" | b"thead" => &[b"align", b"char", b"charoff", b"valign"],
        b"td" | b"th" => &[
            b"abbr", b"align", b"axis", b"bgcolor", b"char", b"charoff", b"colspan", b"headers",
            b"height", b"nowrap", b"rowspan", b"scope", b"valign", b"width",
        ],
        b"template" => &[
            b"shadowrootclonable",
            b"shadowrootcustomelementregistry",
            b"shadowrootdelegatesfocus",
            b"shadowrootmode",
            b"shadowrootserializable",
        ],
        b"textarea" => &[
            b"autocomplete",
            b"cols",
            b"dirname",
            b"disabled",
            b"form",
            b"maxlength",
            b"minlength",
            b"name",
            b"placeholder",
            b"readonly",
            b"required",
            b"rows",
            b"wrap",
        ],
        b"time" => &[b"datetime"],
        b"tr" => &[b"align", b"bgcolor", b"char", b"charoff", b"valign"],
        b"track" => &[b"default", b"kind", b"label", b"src", b"srclang"],
        b"ul" => &[b"compact", b"type"],
        b"video" => &[
            b"autoplay",
            b"controls",
            b"crossorigin",
            b"height",
            b"loop",
            b"muted",
            b"playsinline",
            b"poster",
            b"preload",
            b"src",
            b"width",
        ],
        _ => return None,
    })
}
