// Writes inputs.json: every site where the reference parser reads an expression, a decorator or a body inside type syntax.
// usage: node gen-inputs.cjs > inputs.json
const out = [];
const add = (site, id, text, opt = {}) => out.push({ id: site + id, site, text, ...opt });

// A: computed property names in type literals and interfaces
add("A", 1, "type T = { [Symbol.iterator]: number };");
add("A", 2, 'const k = "a"; type T = { [k]: number };');
add("A", 3, 'type T = { ["a"]: number; [1]: string; [-1]: string };');
add("A", 4, "type T = { [`a`]: number };");
add("A", 5, "declare const a: { b: { readonly c: unique symbol } }; type T = { [a.b.c]: number };");
add("A", 6, "declare const a: string, b: string; type T = { [a + b]: number };");
add("A", 7, "declare function f(): string; type T = { [f()]: number };");
add("A", 8, "declare const a: any, b: any, c: any; type T = { [a ? b : c]: number };");
add("A", 9, "declare const a: any, b: any; type T = { [a, b]: number };");
add("A", 10, "type T = { [+1]: number };");
add("A", 11, "declare const a: unique symbol; type T = { [(a)]: number };");
add("A", 12, "declare const a: any; type T = { [a as any]: number };");
add("A", 13, "declare const a: any; type T = { [a!]: number };");
add("A", 14, 'declare const a: any; type T = { [a["b"]]: number };');
add("A", 15, "declare const a: any; type T = { [typeof a]: number };");
add("A", 16, "declare const A: any, B: any; type T = { [A | B]: number };");
add("A", 17, "declare const A: any; type B = 1; type T = { [A<B>]: number };");
add("A", 18, "type T = { [A extends B ? C : D]: number };");
add("A", 19, "type T = { [keyof A]: number };");
add("A", 20, "type T = { [a[]]: number };");
add("A", 21, "type T = { [(x) => x]: number };");
add("A", 22, "type T = { [class {}]: number };");
add("A", 23, "type T = { [function () { return 1 }]: number };");
add("A", 24, 'type T = { [import("./x")]: number };');
add("A", 25, "declare const x: any; type T = { [await x]: number }; export {};");
add("A", 26, "function* g() { type T = { [yield]: number }; }");
add("A", 28, "interface I { [Symbol.iterator](): Iterator<number> }");
add("A", 29, "interface I { readonly [Symbol.toStringTag]: string }");
add("A", 30, "declare const k: unique symbol; interface I { [k]?: number }");
add("A", 31, "declare const k: unique symbol; interface I { get [k](): number; set [k](v: number) }");
add("A", 32, "declare const a: any; type T = { [a.b!.c]: number; [a?.b]: number };");
add("A", 33, "declare const x: any; type T = { [<any>x]: number };");
add("A", 34, "declare const b: string; type T = { [`a${b}`]: number };");
add("A", 35, "type T = { [1n]: number };");
add("A", 36, "type T = { [new Foo]: number; [this.x]: number; [import.meta.x]: number };");
add("A", 37, "declare let a: any, b: any; type T = { [a = b]: number };");
add("A", 38, "type T = { [/re/]: number };");
add("A", 39, "type T = { [<div/>]: number };", { tsx: true });
add("A", 41, "declare const a: any; type T = { [a satisfies string]: number };");
add("A", 43, "type T = { [async () => { await 1 }]: number };");
add("A", 44, "declare const k: unique symbol; type T = { [k]<U>(): void };");
add("A", 45, "type T = { [Symbol.iterator] };");
add("A", 46, "type T = { [a.b.c.d](x: number): void, [e]: string };");
add("A", 47, "type T = { [a\n.b]: number };");
add("A", 48, "type T = { [/*! legal */ a.b]: number };\nlet z = 1;");
add("A", 49, 'import { foo } from "./x"; type T = { [foo]: string }; export let t: T;');
add("A", 50, 'import { foo } from "./x"; type T = { [foo.bar]: string }; export let t: T;');
add("A", 51, 'import { foo } from "./x"; interface I { [foo](): void } export let t: I;');
add("A", 52, "type T = { [string]: number };");
add("A", 53, "type T = { [a.b<c>]: number };");
add("A", 54, "type T = { [[a, b]]: number };");
add("A", 55, "type T = { [{ a: 1 }]: number };");
add("A", 56, "type T = { [null]: number; [true]: number; [this]: number; [void 0]: number };");
add("A", 57, "type T = { [a & b]: number };");
add("A", 58, "type T = { [unique symbol]: number };");
add("A", 59, "type T = { [() => void]: number };");
add("A", 60, "type T = { [x is string]: number };");
add("A", 61, "type T = { [a.b.c[d]]: number };");
add("A", 62, "type T = { [-1n]: number; [- 1]: number };");
add("A", 63, "type T = { [a!.b]: number };");
add("A", 64, "type T = { [readonly string[]]: number };");
add("A", 65, "type T = { [typeof a.b]: number; [typeof import('x')]: number };");
add("A", 66, "type T = { [a.b]: number\n [c.d]: number };");
add("A", 67, "type T = { readonly [a.b]?: number; -readonly [c]: number };");
add("A", 68, "type T = { [Symbol.iterator]!: number };");

// B: parameter initializers in signatures
add("B", 1, "let g: (a = 1) => void;");
add("B", 2, "let g: (a: number = 1) => void;");
add("B", 3, "let g: (a?: number = 1) => void;");
add("B", 4, "let g: new (a = 1) => Foo;");
add("B", 5, "type T = { (a = 1): void };");
add("B", 6, "type T = { new (a = 1): Foo };");
add("B", 7, "type T = { m(a = 1): void };");
add("B", 8, "interface I { m(a = 1): void }");
add("B", 9, 'type T = { [a: string = "x"]: number };');
add("B", 10, "let g: (a = (b: number) => b) => void;");
add("B", 11, "let g: (a = function f() { var x; }) => void;");
add("B", 12, "let g: (a = class C { m() {} }) => void;");
add("B", 13, 'let g: (a = import("./x")) => void;');
add("B", 14, 'let g: (a = require("./x")) => void;');
add("B", 15, "declare const p: Promise<number>; let g: (a = await p) => void; export {};");
add("B", 16, "let g: (a = <div/>) => void;", { tsx: true });
add("B", 17, "let g: (a = import.meta.url) => void;");
add("B", 18, "let g: (a = b, c = a) => void;");
add("B", 19, "let g: (...a = []) => void;");
add("B", 20, "let g: (this = 1) => void;");
add("B", 21, "let g: (a = 1 in x) => void;");
add("B", 22, "for (let g: (a = 1 in x) => void = null!; ;) {}");
add("B", 23, "function* f() { let g: (a = yield 1) => void; }");
add("B", 24, "async function f() { let g: (a = await 1) => void; }");
add("B", 25, "let g: (a = b as T) => void;");
add("B", 26, "let g: (a = <T>(x: T) => x) => void;");
add("B", 27, "let g: (a = () => { return 1 }) => void;");
add("B", 28, "let g: (a = { b: 1, c() {} }) => void;");
add("B", 29, "let g: (a = `x${1}`) => void;");
add("B", 30, "let g: (a = 1, ) => void;");
add("B", 31, "function f(): (a = 1) => void { return null! }");
add("B", 32, "declare const dec: any; class C { @dec p: (a = 1) => void }", { deco: true });
add("B", 33, "let x = <(a = 1) => void>y;");
add("B", 34, "let x = y as (a = 1) => void;");
add("B", 35, "f<(a = 1) => void>(x);");
add("B", 36, "let x = (a): (b = 1) => void => a;");
add("B", 37, "let x = c ? (a): (b = 1) => void => a : d;");
add("B", 38, "type T<U = (a = 1) => void> = U;");
add("B", 39, "function f<T extends (a = 1) => void>() {}");
add("B", 40, "let g: (a = 1);");
add("B", 41, "let g: (a = 1) => (b = 2) => void;");
add("B", 42, "let g: (a = x > y) => void;");
add("B", 43, "let g: (a = x, y) => void;");
add("B", 44, "let g: (a = x => y) => void;");
add("B", 45, "let g: (a = async () => { await 1 }) => void;");
add("B", 46, "let g: (a = function* () { yield 1 }) => void;");
add("B", 47, "let g: (a = new.target) => void;");
add("B", 48, "class K extends B { p: (a = super.x) => void; }");
add("B", 49, "class K { p: (a = this.#x) => void; #x = 1; }");
add("B", 50, "let g: (a = arguments) => void;");
add("B", 51, "enum E { A = 1 } let g: (a = E.A) => void;");
add("B", 52, 'import { foo } from "./x"; let g: (a = foo) => void; export { g };');
add("B", 53, "let g: (a = /*! legal */ 1) => void;\nlet z = 1;");
add("B", 54, "let g: (a = () => { /*! legal */ return 1 }) => void;\nlet z = 1;");
add("B", 55, "let g: (a = 1) => void = null!, h = 2;");
add("B", 56, "let g: (a: number = 1, b?: string, ...c: any[]) => void;");
add("B", 57, "abstract class K { abstract m(a = 1): void; }");
add("B", 58, "function f(a = 1): void; function f() {}");
add("B", 59, "declare function f(a = 1): void;");
add("B", 60, "let g: (a = (0, function () { 'use strict'; with (x) {} })) => void;");

// C: binding patterns in signature parameters
add("C", 1, "let g: ({ a, b }: T) => void;");
add("C", 2, "let g: ([a, b]: T) => void;");
add("C", 3, "let g: ({ a = 1 }: T) => void;");
add("C", 4, "let g: ([a = 1]: T) => void;");
add("C", 5, "let g: ({ a: { b = 1 } }: T) => void;");
add("C", 6, "let g: ({ [k]: a }: T) => void;");
add("C", 7, "let g: ({ a, ...rest }: T) => void;");
add("C", 8, "let g: ([, a, ...b]: T) => void;");
add("C", 9, "let g: ({ a = (x) => x }: T) => void;");
add("C", 10, 'let g: ({ "a": b, 1: c }: T) => void;');
add("C", 11, "let g: ({ a } = {}) => void;");
add("C", 12, "let g: ({ a }) => void;");
add("C", 13, "let g: ({ a });");
add("C", 14, "let g: ({ a = 1 });");
add("C", 15, "let g: ([a]);");
add("C", 16, "let g: ({ a: 1 }: T) => void;");
add("C", 17, "let g: ({ if: x }: T) => void;");
add("C", 18, "let g: ({ a: string });");
add("C", 19, "let g: ([a, b]) => void;");
add("C", 20, "let g: ([a, b?]);");
add("C", 21, "let g: ({ a }?: T) => void;");
add("C", 22, "let g: ([a]: T, { b }: U) => void;");
add("C", 23, "let g: (...[a, b]: T) => void;");
add("C", 24, "let g: ({ a = 1 }) => void;");
add("C", 25, "let g: ({ a = 1 }, b);");
add("C", 26, "let g: ({ [a + b]: c = d }: T) => void;");
add("C", 27, "let g: ([[[[a]]]]: any) => void;");
add("C", 28, "let g: ({ a: [b, { c = () => { var v } }] }: any) => void;");
add("C", 29, "type T = { m({ a = 1 }: any): void; new ([b = 2]: any): T; ({ c = 3 }): void };");
add("C", 30, "let g: ({ a, }: T, ) => void;");
add("C", 31, "let g: ({ a = 1, b: { c } = {} }: T) => void;");
add("C", 32, "let g: ({ ...{ a } }: T) => void;");
add("C", 33, "let g: ({ #a: b }: T) => void;");
add("C", 34, "let g: ([a = 1, [b] = []] = []) => void;");

// D: decorators and modifiers on signature parameters
add("D", 1, "declare const dec: any; let g: (@dec a) => void;");
add("D", 2, "declare const dec: any; let g: (@dec() a: number) => void;");
add("D", 3, "declare const dec: any; type T = { m(@dec a): void };");
add("D", 4, "declare const foo: any; let g: (@(foo.bar()) a) => void;");
add("D", 5, "let g: (public a) => void;");
add("D", 6, "let g: (readonly a: string[]) => void;");
add("D", 7, "declare const dec: any; type T = { [@dec a: string]: number };");
add("D", 8, "type T = { [public a: string]: number };");
add("D", 9, "declare const dec: any; let g: (@dec) => void;");
add("D", 10, "declare const dec: any; let g: (@dec @dec2() public readonly a?: number = 1) => void;");
add("D", 11, "declare const dec: any; let g: (@dec this: any) => void;");
add("D", 12, "declare const dec: any; let g: (@dec ...a: any[]) => void;");
add("D", 13, "declare const dec: any; let g: (@dec { a }: any) => void;");
add("D", 14, "declare const dec: any; let g: (@dec.a.b<T>() a) => void;");
add("D", 15, "declare const dec: any; let g: (@((x) => x) a) => void;");
add("D", 16, "declare const dec: any; let g: (@dec(class { m() { var v } }) a) => void;");
add("D", 17, "declare const dec: any; async function f() { let g: (@(await dec) a) => void; }");
add("D", 18, "declare const dec: any; let g: new (@dec a) => Foo;");
add("D", 19, "declare const dec: any; class K { m(@dec a): void; m(a) {} }", { deco: true });
add("D", 20, "declare const dec: any; declare class K { m(@dec a): void; }", { deco: true });
add("D", 21, "let g: (public) => void;");
add("D", 22, "let g: (public, a) => void;");
add("D", 23, "let g: (override readonly a) => void;");
add("D", 24, "let g: (export a) => void;");
add("D", 25, "let g: (async a) => void;");
add("D", 26, "let g: (static a) => void;");
add("D", 27, "let g: (abstract a) => void;");
add("D", 28, "let g: (declare a) => void;");
add("D", 29, "let g: (accessor a) => void;");
add("D", 30, "let g: (in a) => void;");
add("D", 31, "let g: (out a) => void;");
add("D", 32, "let g: (const a) => void;");

// E: initializers of property signatures
add("E", 1, "type T = { a: number = 1 };");
add("E", 2, "interface I { a: number = 1 }");
add("E", 3, "type T = { a = 1 };");
add("E", 4, "type T = { a? = 1 };");
add("E", 5, "type T = { a = () => { var x } };");
add("E", 6, 'type T = { readonly a: string = "x"; b: number };');
add("E", 7, "type T = { a = 1, b = 2 };");
add("E", 8, "type T = { a = 1 b = 2 };");
add("E", 9, "type T = { a = 1\n b = 2 };");
add("E", 10, 'type T = { "a" = 1; 2 = 3; [k] = 4 };');
add("E", 11, "type T = { a: number = b in c };");
add("E", 12, "type T = { a = class { static { var q; } } };");
add("E", 13, 'type T = { a = import("./x") };');
add("E", 14, "type T = { a = x, y };");
add("E", 15, "interface I { m(): void = 1 }");
add("E", 16, "type T = { a: number = 1 }[];");
add("E", 17, "declare const dec: any; class C { @dec p: { a: number = 1 } }", { deco: true });
add("E", 18, "type T = { a = yield };");
add("E", 19, "type T = { a = await 1 }; export {};");

// F: accessors in type literals and interfaces
add("F", 1, "type T = { get x(): number; set x(v: number) };");
add("F", 2, "interface I { get x(): number }");
add("F", 3, "type T = { get x() { return 1 } };");
add("F", 4, "type T = { set x(v) { this.y = v } };");
add("F", 5, "type T = { get x(): number { return 1 }; y: string };");
add("F", 6, "type T = { get: number; set: string };");
add("F", 7, "type T = { get(): number; set(v: number): void };");
add("F", 8, "type T = { get x<U>(): U };");
add("F", 9, "declare const k: unique symbol; type T = { get [k](): number };");
add("F", 10, "type T = { get x() { return await 1 } }; export {};");
add("F", 11, "type T = { get x() { var a; function g() {} class K {} return 1 } };");
add("F", 12, 'type T = { get x() { return import("./y") } };');
add("F", 13, "type T = { m() { return 1 } };");
add("F", 14, "type T = { get x() };");
add("F", 15, "type T = { get x(): number, set x(v: number), };");
add("F", 16, "type T = { get x() { return 1 } y: string };");
add("F", 17, "type T = { get x() { return 1 }\n y: string };");
add("F", 18, "type T = { get x() { yield 1 } };");
add("F", 19, "type T = { get x() { return super.x } };");
add("F", 20, "type T = { get x() { return new.target } };");
add("F", 21, "type T = { get x() { return arguments } };");
add("F", 22, "type T = { get x() { 'use strict'; with (a) {} } };");
add("F", 23, "type T = { get x() { import a from 'b'; } };");
add("F", 24, "type T = { get x() { export const a = 1; } };");
add("F", 25, "type T = { get x() { return 1 } }; const after = 1;");
add("F", 26, "type T = { get\n x(): number };");
add("F", 27, "type T = { get ?: number; set?(): void };");
add("F", 28, "type T = { get x(a = 1) { return a } };");
add("F", 29, "interface I { get x() { return 1 } set x(v) {} }");
add("F", 30, "type T = { get x() { type U = 1; interface V {} enum W { A } namespace N { export const q = 1 } return 1 } };");
add("F", 31, "type T = { get x() { /*! legal */ return 1 } };\nlet z = 1;");
add("F", 32, "declare const dec: any; class C { @dec p: { get x() { return 1 } } }", { deco: true });
add("F", 33, "type T = { get x() { label: for (;;) { break label } } };");
add("F", 34, "type T = { get x() { return <div/> } };", { tsx: true });
add("F", 35, "type T = { get x() { using a = b; } };");
add("F", 36, "type T = { get 'x'(): number; set 1(v) ; get #p(): number };");
add("F", 37, "type T = { get x() => 1 };");
add("F", 38, "type T = { async get x() { await 1 } };");
add("F", 39, "type T = { static get x() { return 1 } };");
add("F", 40, "type T = { get x() { return 1 };; };");

// G: a type parameter constraint that is an expression
add("G", 1, "function f<T extends +1>() {}");
add("G", 2, "type T<U extends -1> = U;");
add("G", 3, "function f<T extends (a + b)>() {}");
add("G", 4, "function f<T extends !x>() {}");
add("G", 5, "function f<T extends ++x>() {}");
add("G", 6, "function f<T extends /re/>() {}");
add("G", 7, "function f<T extends class {}>() {}");
add("G", 8, "function f<T extends function () { var x }>() {}");
add("G", 9, "async function f<T extends await x>() {}");
add("G", 10, "function f<T extends delete x>() {}");
add("G", 11, "function f<T extends ~x>() {}");
add("G", 12, "class K<T extends +1> {}");
add("G", 13, "interface I<T extends +1> {}");
add("G", 14, "type A<T extends +1> = T;");
add("G", 15, "let g: <T extends +1>() => void;");
add("G", 16, "type M = { m<T extends +1>(): void };");
add("G", 17, "const h = <T extends +1>(x: T) => x;");
add("G", 18, "const h = <T extends +1,>(x: T) => x;", { tsx: true });
add("G", 19, "function f<T extends x++>() {}");
add("G", 20, 'function f<T extends "a" + "b">() {}');
add("G", 21, "function f<T extends void 0>() {}");
add("G", 22, "function f<T extends new Foo()>() {}");
add("G", 23, "declare const dec: any; function f<T extends @dec class {}>() {}");
add("G", 24, "function f<T extends --x, U>() {}");
add("G", 25, "function f<T extends +1 = 2>() {}");
add("G", 26, "function f<T extends ~x > y>() {}");
add("G", 27, "function f<T extends +x>>() {}");
add("G", 28, "function f<T extends + +1>() {}");
add("G", 29, "function f<T extends #p in x>() {}");
add("G", 30, "function f<T extends <U>x>() {}");
add("G", 31, "function f<T extends async function () { await 1 }>() {}");
add("G", 32, "function f<T extends super.x>() {}");
add("G", 33, "type A = B extends infer U extends +1 ? U : never;");
add("G", 34, "type M = { [K in +1]: K };");
add("G", 35, "class K { m<T extends +1>() {} }");
add("G", 36, "function f<T extends ...x>() {}");
add("G", 37, "function f<T extends yield>() {}");
add("G", 38, "function f<T extends +(a, () => { var q })>() {}");
add("G", 39, "f<T extends +1>(x);");
add("G", 40, "function f<T extends `a${b}`>() {}");
add("G", 41, "function f<T extends { a = 1 }>() {}");
add("G", 42, "function f<T extends function>() {}");
add("G", 43, "function f<T extends import.meta>() {}");
add("G", 44, "function f<T extends - x>() {}");
add("G", 45, "function f<T extends typeof +1>() {}");
add("G", 46, "function f<in T extends +1>() {}");

// H: import attributes of import types
add("H", 1, 'type T = import("./x", { with: { type: "json" } });');
add("H", 2, 'type T = import("./x", { with: { "resolution-mode": "import" } }).Foo;');
add("H", 3, 'type T = import("./x", { with: { type: foo() } });');
add("H", 4, 'type T = import("./x", { with: { type: a + b } });');
add("H", 5, 'type T = import("./x", { assert: { type: "json" } });');
add("H", 6, 'type T = import("./x", { with: { type: "json", } });');
add("H", 7, 'type T = import("./x", { with: { type: "json" }, });');
add("H", 8, 'type T = import("./x", { with: { type: (x) => x } });');
add("H", 9, 'type T = import("./x", { with: {} });');
add("H", 10, 'type T = typeof import("./x", { with: { type: "json" } });');
add("H", 11, 'type T = import("./x", { foo: { type: "json" } });');
add("H", 12, "type T = import(foo);");
add("H", 13, 'type T = import("./x", { with: { 1: "a" } });');
add("H", 14, 'type T = import("./x", { with: { type: "json" } }, );');
add("H", 15, 'type T = import("./x", { with: { type: `json` } });');
add("H", 16, 'type T = import("./x", { with: { type: "json"; } });');
add("H", 17, 'type T = import("./x", { with: { type: "a", mode: "b" } });');
add("H", 18, 'type T = import("./x", { with: { if: "a" } });');
add("H", 19, 'type T = import("./x", { with: { type: import("./y") } });');
add("H", 20, 'type T = import("./x", { with: { type } });');
add("H", 21, 'type T = import("./x", { with: { type: function () { var v } } });');
add("H", 22, 'type T = import("./x", { with: { type: "json" } }).A.B<C>;');
add("H", 23, 'type T = import("./x", { with });');
add("H", 24, 'type T = import("./x", );');
add("H", 25, 'type T = import("./x", { with: { type: y as string } });');
add("H", 26, 'type T = import("./x", { with: { type: "json" } } as any);');
add("H", 27, 'type T = import(`./x`);');
add("H", 28, 'type T = import("./x" | "./y");');

// I: heritage clauses of interfaces, and implements clauses
add("I", 1, "interface I extends A.B<C>, D {}");
add("I", 2, "interface I extends foo() {}");
add("I", 3, "interface I extends A[0] {}");
add("I", 4, "interface I extends (A) {}");
add("I", 5, "interface I extends A?.B {}");
add("I", 6, "interface I extends typeof x {}");
add("I", 7, "interface I extends { a: 1 } {}");
add("I", 8, "interface I extends class {} {}");
add("I", 9, "interface I extends new Foo {}");
add("I", 10, 'interface I extends import("x") {}');
add("I", 11, "interface I extends A<B>.C {}");
add("I", 12, "interface I extends string {}");
add("I", 13, "interface I extends A | B {}");
add("I", 14, "interface I extends Array<number>[] {}");
add("I", 15, "class C implements A.B<C>, D {}");
add("I", 16, "class C implements foo() {}");
add("I", 17, "class C implements A | B {}");
add("I", 18, "interface I extends A<B>() {}");
add("I", 19, "interface I extends a.b!.c {}");
add("I", 20, "interface I extends tag`x` {}");
add("I", 21, "interface I extends (() => void) {}");
add("I", 22, "interface I extends A.B.C, D<E<F>>, G {}");
add("I", 23, "interface I extends this {}");
add("I", 24, "interface I extends A<B>, C<D>> {}");
add("I", 25, "interface I extends function () { var q } {}");
add("I", 26, "interface I extends a.#b {}");
add("I", 27, "interface I extends super.x {}");
add("I", 28, "interface I extends import.meta {}");
add("I", 29, "interface I extends void {}");
add("I", 30, "interface I extends null {}");
add("I", 31, 'interface I extends "a" {}');
add("I", 32, "interface I extends A<B> {} class C extends K implements A<B>, M.N {}");
add("I", 33, "interface I extends A.B<C>\n{ }");
add("I", 34, "interface I extends keyof A {}");
add("I", 35, "interface I extends [A] {}");
add("I", 36, "interface I extends A & B {}");
add("I", 37, "class C implements {} {}");
add("I", 38, "class C implements (A) {}");
add("I", 39, "class C implements typeof x {}");
add("I", 40, "interface I extends A.default.if<B> {}");

// K: what the statement-level discards leave behind today
add("K", 1, 'declare function f() { import("./nope1"); }');
add("K", 2, 'declare class C { m() { require("./nope2") } }');
add("K", 3, 'abstract class C { abstract m() { import("./nope3") } }');
add("K", 4, 'function f(a = import("./nope4")): void; function f() {}');
add("K", 5, 'declare const c = import("./nope5");');
add("K", 6, 'declare namespace N { const c = require("./nope6"); }');
add("K", 7, 'declare class C { p = import("./nope7"); }');
add("K", 8, 'class C { declare p = import("./nope8"); }');
add("K", 9, 'declare function f(a = await 1): void; export {};');
add("K", 10, "declare function f(a = <div/>): void;", { tsx: true });
add("K", 11, "declare function f(a = import.meta.url): void;");
add("K", 12, 'import { foo } from "./x"; declare function f(a = foo): void;');
add("K", 13, 'import { foo } from "./x"; function f(a = foo): void; function f() {}');
add("K", 14, 'import { foo } from "./x"; abstract class C { abstract m(a = foo): void }');
add("K", 15, 'import { foo } from "./x"; class C { declare p = foo; }');
add("K", 16, 'import { foo } from "./x"; declare const c = foo;');

process.stdout.write(JSON.stringify(out, null, 1));
