set pagination off
set confirm off
set breakpoint pending off
handle SIGPWR nostop noprint
handle SIGXCPU nostop noprint
handle SIGUSR1 nostop noprint
handle SIGSEGV nostop noprint pass
handle SIGPIPE nostop noprint
tbreak _RINvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtBa_1p1PKb1_Kb0_E13build_in_typeNtNtCslI71YDjvLxT_7bun_ast4expr4ExprNCNvB2_18build_expr_in_type0EBa_
commands
silent
continue
end
tbreak _RINvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtBa_1p1PKb1_Kb0_E13build_in_typeNtNtCslI71YDjvLxT_7bun_ast7binding7BindingNCNvB2_30build_next_is_start_of_fn_type0EBa_
commands
silent
continue
end
tbreak _RINvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtBa_1p1PKb1_Kb0_E32build_type_script_type_argumentsKB16_KB1a_EBa_
commands
silent
continue
end
tbreak _RINvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtBa_1p1PKb1_Kb0_E32build_type_script_type_argumentsKB1a_KB16_EBa_
commands
silent
continue
end
tbreak _RINvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtBa_1p1PKb1_Kb0_E32build_type_script_type_argumentsKB1a_KB1a_EBa_
commands
silent
continue
end
tbreak _RNvMNtCsaISE7XrFnM6_13bun_js_parser5parseINtNtB4_1p1PKb1_Kb0_E22lint_arrow_return_typeB4_
commands
silent
continue
end
tbreak _RNvMNtCsaISE7XrFnM6_13bun_js_parser5parseINtNtB4_1p1PKb1_Kb0_E25parse_paren_expr_for_lintB4_
commands
silent
continue
end
tbreak _RNvMNtCsaISE7XrFnM6_13bun_js_parser5parseINtNtB4_1p1PKb1_Kb0_E29rewind_class_implements_entryB4_
commands
silent
continue
end
tbreak _RNvMNtCsaISE7XrFnM6_13bun_js_parser5parseINtNtB4_1p1PKb1_Kb0_E30parse_paren_expr_for_lint_coldB4_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse12parse_prefixINtNtB6_1p1PKb0_KB16_E25pfx_t_open_paren_for_lintB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse12parse_prefixINtNtB6_1p1PKb1_Kb0_E24pfx_t_less_than_for_lintB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse12parse_prefixINtNtB6_1p1PKb1_Kb0_E25pfx_t_open_paren_for_lintB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse12parse_prefixINtNtB6_1p1PKb1_Kb0_E30pfx_type_before_paren_for_lintB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse12parse_suffixINtNtB6_1p1PKb1_Kb0_E26sfx_typescript_as_for_lintB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse21parse_skip_typescriptINtNtB6_1p1PKb1_Kb0_E19rewind_lint_attemptB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse21parse_skip_typescriptINtNtB6_1p1PKb1_Kb0_E19rewind_to_read_markB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse21parse_skip_typescriptINtNtB6_1p1PKb1_Kb0_E22parse_and_drop_in_typeB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse21parse_skip_typescriptINtNtB6_1p1PKb1_Kb0_E54try_build_type_script_type_arguments_with_backtrackingB6_
commands
silent
continue
end
tbreak _RNvMNtNtCsaISE7XrFnM6_13bun_js_parser5parse8parse_fnINtNtB6_1p1PKb1_Kb0_E18lint_type_metadataB6_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsNtB5_12SyntaxErrors6record
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsNtB5_12SyntaxErrors6refine
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedNtB5_8Attached10annotation
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedNtB5_8Attached14this_parameter
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedNtB5_8Attached19type_parameter_list
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedNtB5_8Attached22jsx_type_argument_list
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedNtB5_8Attached6rewind
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E21lint_async_type_listsB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E21lint_class_implementsB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E25lint_type_arguments_afterB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E26lint_arrow_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E29lint_type_parameters_of_arrowB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E30lint_try_async_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E32lint_declaration_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E32lint_type_arguments_before_parenB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E33lint_type_arguments_in_expressionB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E33lint_type_parameters_before_parenB9_
commands
silent
continue
end
tbreak _RNvMs0_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsINtNtB9_1p1PKb1_Kb0_E35lint_forget_skipped_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E16lint_return_typeB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E18lint_class_extendsB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E19lint_this_parameterB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E20lint_type_annotationB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E20lint_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8attachedINtNtB9_1p1PKb1_Kb0_E23lint_jsx_type_argumentsB9_
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8wrappersNtB5_8Wrappers13parenthesized
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8wrappersNtB5_8Wrappers14type_assertion
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8wrappersNtB5_8Wrappers15as_or_satisfies
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8wrappersNtB5_8Wrappers20parenthesized_before
commands
silent
continue
end
tbreak _RNvMs1_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8wrappersNtB5_8Wrappers8non_null
commands
silent
continue
end
tbreak _RNvMs2_NtCsaISE7XrFnM6_13bun_js_parser1pNtB5_18StartsForParseOnly6rewind
commands
silent
continue
end
tbreak _RNvMs2_NtCsaISE7XrFnM6_13bun_js_parser1pNtB5_18StartsForParseOnly8for_lint
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb0_KB1a_E13unexpected_asB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb0_KB1a_E17code_syntax_errorB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb0_KB1a_E19start_syntax_errorsB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb1_Kb0_E13type_expectedB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb1_Kb0_E13unexpected_asB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb1_Kb0_E17code_syntax_errorB9_
commands
silent
continue
end
tbreak _RNvMs2_NtNtCsaISE7XrFnM6_13bun_js_parser5parse13syntax_errorsINtNtB9_1p1PKb1_Kb0_E19start_syntax_errorsB9_
commands
silent
continue
end
tbreak _RNvMs4_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_10ErasedData6export
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables11member_read
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables13import_equals
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables15member_modifier
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables15member_property
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables19exported_by_default
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables20statement_after_type
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables5class
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables6export
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables6global
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables6import
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables7dropped
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables7list_of
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables8declared
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables9namespace
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse6erasedNtB5_12ErasedTables9statement
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E22build_type_member_listB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E22build_type_script_typeB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E24build_tuple_element_typeB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E25build_type_script_fn_typeB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E28build_typescript_return_typeB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E29build_type_script_import_typeB9_
commands
silent
continue
end
tbreak _RNvMs5_NtNtCsaISE7XrFnM6_13bun_js_parser5parse9type_sinkINtNtB9_1p1PKb1_Kb0_E33build_type_script_type_parametersB9_
commands
silent
continue
end
tbreak _RNvMs6_NtCsaISE7XrFnM6_13bun_js_parser1pINtB5_1PKb1_Kb0_E14rewind_sidecarB7_
commands
silent
continue
end
tbreak _RNvMs_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsNtB4_8Generics18type_argument_list
commands
silent
continue
end
tbreak _RNvMs_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsNtB4_8Generics31declaration_type_parameter_list
commands
silent
continue
end
tbreak _RNvMs_NtNtCsaISE7XrFnM6_13bun_js_parser5parse8genericsNtB4_8Generics9rewind_to
commands
silent
continue
end
tbreak _RNvNtNtCsaISE7XrFnM6_13bun_js_parser5parse6erased11first_token
commands
silent
continue
end
tbreak _RNvNtNtCsaISE7XrFnM6_13bun_js_parser5parse6erased14keyword_before
commands
silent
continue
end
tbreak _RNvNtNtCsaISE7XrFnM6_13bun_js_parser5parse6erased14module_keyword
commands
silent
continue
end
tbreak _RNvNtNtCsaISE7XrFnM6_13bun_js_parser5parse6erased16token_end_before
commands
silent
continue
end
run
info breakpoints
