// GENERATED FILE — do not edit. Regenerate with:
//   bun src/codegen/generate-primordials.ts --bun=<bun> --webkit=<WebKit>
// oxlint-disable typescript/no-wrapper-object-types -- wrapper types model real prototype receivers
//
// Tamper-proof references to the original ECMAScript builtins, exposed by JSC
// (JSCPrimordials.h) as link-time constants and named after Node.js's primordials.
// Prototype methods, getters, and setters take the receiver via .$call/.$apply:
//
//   $ArrayPrototypePush.$call(array, value);
//   $MapPrototypeGetSize.$call(map);
//   $ObjectDefineProperty(target, key, descriptor);

type PrimordialMethod<Holder, Key extends PropertyKey> =
  Holder extends Record<Key, infer Method>
    ? Method extends (...args: infer Args) => infer Return
      ? (this: Holder, ...args: Args) => Return
      : Function
    : Function;
type PrimordialGetter<Holder, Key extends PropertyKey> =
  Holder extends Record<Key, infer Value> ? (this: Holder) => Value : Function;
type PrimordialSetter<Holder, Key extends PropertyKey> =
  Holder extends Record<Key, infer Value> ? (this: Holder, value: Value) => void : Function;
type PrimordialValue<Holder, Key extends PropertyKey> = Holder extends Record<Key, infer Value> ? Value : unknown;

declare const $Proxy: ProxyConstructor;
declare const $globalThis: PrimordialValue<typeof globalThis, "globalThis">;
declare const $decodeURI: PrimordialMethod<typeof globalThis, "decodeURI">;
declare const $decodeURIComponent: PrimordialMethod<typeof globalThis, "decodeURIComponent">;
declare const $encodeURI: PrimordialMethod<typeof globalThis, "encodeURI">;
declare const $encodeURIComponent: PrimordialMethod<typeof globalThis, "encodeURIComponent">;
declare const $escape: PrimordialMethod<typeof globalThis, "escape">;
declare const $eval: PrimordialMethod<typeof globalThis, "eval">;
declare const $unescape: PrimordialMethod<typeof globalThis, "unescape">;
declare const $AtomicsAdd: PrimordialMethod<Atomics, "add">;
declare const $AtomicsAnd: PrimordialMethod<Atomics, "and">;
declare const $AtomicsCompareExchange: PrimordialMethod<Atomics, "compareExchange">;
declare const $AtomicsExchange: PrimordialMethod<Atomics, "exchange">;
declare const $AtomicsIsLockFree: PrimordialMethod<Atomics, "isLockFree">;
declare const $AtomicsLoad: PrimordialMethod<Atomics, "load">;
declare const $AtomicsNotify: PrimordialMethod<Atomics, "notify">;
declare const $AtomicsOr: PrimordialMethod<Atomics, "or">;
declare const $AtomicsStore: PrimordialMethod<Atomics, "store">;
declare const $AtomicsSub: PrimordialMethod<Atomics, "sub">;
declare const $AtomicsWait: PrimordialMethod<Atomics, "wait">;
declare const $AtomicsXor: PrimordialMethod<Atomics, "xor">;
declare const $AtomicsPause: PrimordialMethod<Atomics, "pause">;
declare const $AtomicsWaitAsync: PrimordialMethod<Atomics, "waitAsync">;
declare const $JSONParse: PrimordialMethod<JSON, "parse">;
declare const $JSONStringify: PrimordialMethod<JSON, "stringify">;
declare const $JSONIsRawJSON: PrimordialMethod<JSON, "isRawJSON">;
declare const $JSONRawJSON: PrimordialMethod<JSON, "rawJSON">;
declare const $MathAbs: PrimordialMethod<Math, "abs">;
declare const $MathAcos: PrimordialMethod<Math, "acos">;
declare const $MathAsin: PrimordialMethod<Math, "asin">;
declare const $MathAtan: PrimordialMethod<Math, "atan">;
declare const $MathAcosh: PrimordialMethod<Math, "acosh">;
declare const $MathAsinh: PrimordialMethod<Math, "asinh">;
declare const $MathAtanh: PrimordialMethod<Math, "atanh">;
declare const $MathAtan2: PrimordialMethod<Math, "atan2">;
declare const $MathCbrt: PrimordialMethod<Math, "cbrt">;
declare const $MathCeil: PrimordialMethod<Math, "ceil">;
declare const $MathClz32: PrimordialMethod<Math, "clz32">;
declare const $MathCos: PrimordialMethod<Math, "cos">;
declare const $MathCosh: PrimordialMethod<Math, "cosh">;
declare const $MathExp: PrimordialMethod<Math, "exp">;
declare const $MathExpm1: PrimordialMethod<Math, "expm1">;
declare const $MathFloor: PrimordialMethod<Math, "floor">;
declare const $MathFround: PrimordialMethod<Math, "fround">;
declare const $MathHypot: PrimordialMethod<Math, "hypot">;
declare const $MathLog: PrimordialMethod<Math, "log">;
declare const $MathLog10: PrimordialMethod<Math, "log10">;
declare const $MathLog1p: PrimordialMethod<Math, "log1p">;
declare const $MathLog2: PrimordialMethod<Math, "log2">;
declare const $MathMax: PrimordialMethod<Math, "max">;
declare const $MathMin: PrimordialMethod<Math, "min">;
declare const $MathPow: PrimordialMethod<Math, "pow">;
declare const $MathRandom: PrimordialMethod<Math, "random">;
declare const $MathRound: PrimordialMethod<Math, "round">;
declare const $MathSign: PrimordialMethod<Math, "sign">;
declare const $MathSin: PrimordialMethod<Math, "sin">;
declare const $MathSinh: PrimordialMethod<Math, "sinh">;
declare const $MathSqrt: PrimordialMethod<Math, "sqrt">;
declare const $MathTan: PrimordialMethod<Math, "tan">;
declare const $MathTanh: PrimordialMethod<Math, "tanh">;
declare const $MathTrunc: PrimordialMethod<Math, "trunc">;
declare const $MathImul: PrimordialMethod<Math, "imul">;
declare const $MathF16round: PrimordialMethod<Math, "f16round">;
declare const $MathSumPrecise: PrimordialMethod<Math, "sumPrecise">;
declare const $ReflectApply: PrimordialMethod<typeof Reflect, "apply">;
declare const $ReflectConstruct: PrimordialMethod<typeof Reflect, "construct">;
declare const $ReflectDefineProperty: PrimordialMethod<typeof Reflect, "defineProperty">;
declare const $ReflectDeleteProperty: PrimordialMethod<typeof Reflect, "deleteProperty">;
declare const $ReflectGet: PrimordialMethod<typeof Reflect, "get">;
declare const $ReflectGetOwnPropertyDescriptor: PrimordialMethod<typeof Reflect, "getOwnPropertyDescriptor">;
declare const $ReflectGetPrototypeOf: PrimordialMethod<typeof Reflect, "getPrototypeOf">;
declare const $ReflectHas: PrimordialMethod<typeof Reflect, "has">;
declare const $ReflectIsExtensible: PrimordialMethod<typeof Reflect, "isExtensible">;
declare const $ReflectOwnKeys: PrimordialMethod<typeof Reflect, "ownKeys">;
declare const $ReflectPreventExtensions: PrimordialMethod<typeof Reflect, "preventExtensions">;
declare const $ReflectSet: PrimordialMethod<typeof Reflect, "set">;
declare const $ReflectSetPrototypeOf: PrimordialMethod<typeof Reflect, "setPrototypeOf">;
declare const $ProxyRevocable: PrimordialMethod<ProxyConstructor, "revocable">;
declare const $AggregateErrorPrototype: ErrorConstructor;
declare const $AggregateErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $ArrayFrom: PrimordialMethod<ArrayConstructor, "from">;
declare const $ArrayPrototype: Array<any>;
declare const $ArrayOf: PrimordialMethod<ArrayConstructor, "of">;
declare const $ArrayIsArray: PrimordialMethod<ArrayConstructor, "isArray">;
declare const $ArrayFromAsync: PrimordialMethod<ArrayConstructor, "fromAsync">;
declare const $ArrayGetSymbolSpecies: PrimordialGetter<ArrayConstructor, typeof Symbol.species>;
declare const $ArrayPrototypeToString: PrimordialMethod<Array<any>, "toString">;
declare const $ArrayPrototypeValues: PrimordialMethod<Array<any>, "values">;
declare const $ArrayPrototypeToLocaleString: PrimordialMethod<Array<any>, "toLocaleString">;
declare const $ArrayPrototypeConcat: PrimordialMethod<Array<any>, "concat">;
declare const $ArrayPrototypeFill: PrimordialMethod<Array<any>, "fill">;
declare const $ArrayPrototypeJoin: PrimordialMethod<Array<any>, "join">;
declare const $ArrayPrototypePop: PrimordialMethod<Array<any>, "pop">;
declare const $ArrayPrototypePush: PrimordialMethod<Array<any>, "push">;
declare const $ArrayPrototypeReverse: PrimordialMethod<Array<any>, "reverse">;
declare const $ArrayPrototypeShift: PrimordialMethod<Array<any>, "shift">;
declare const $ArrayPrototypeSlice: PrimordialMethod<Array<any>, "slice">;
declare const $ArrayPrototypeSort: PrimordialMethod<Array<any>, "sort">;
declare const $ArrayPrototypeSplice: PrimordialMethod<Array<any>, "splice">;
declare const $ArrayPrototypeUnshift: PrimordialMethod<Array<any>, "unshift">;
declare const $ArrayPrototypeEvery: PrimordialMethod<Array<any>, "every">;
declare const $ArrayPrototypeForEach: PrimordialMethod<Array<any>, "forEach">;
declare const $ArrayPrototypeSome: PrimordialMethod<Array<any>, "some">;
declare const $ArrayPrototypeIndexOf: PrimordialMethod<Array<any>, "indexOf">;
declare const $ArrayPrototypeLastIndexOf: PrimordialMethod<Array<any>, "lastIndexOf">;
declare const $ArrayPrototypeFilter: PrimordialMethod<Array<any>, "filter">;
declare const $ArrayPrototypeFlat: PrimordialMethod<Array<any>, "flat">;
declare const $ArrayPrototypeFlatMap: PrimordialMethod<Array<any>, "flatMap">;
declare const $ArrayPrototypeReduce: PrimordialMethod<Array<any>, "reduce">;
declare const $ArrayPrototypeReduceRight: PrimordialMethod<Array<any>, "reduceRight">;
declare const $ArrayPrototypeMap: PrimordialMethod<Array<any>, "map">;
declare const $ArrayPrototypeKeys: PrimordialMethod<Array<any>, "keys">;
declare const $ArrayPrototypeEntries: PrimordialMethod<Array<any>, "entries">;
declare const $ArrayPrototypeFind: PrimordialMethod<Array<any>, "find">;
declare const $ArrayPrototypeFindLast: PrimordialMethod<Array<any>, "findLast">;
declare const $ArrayPrototypeFindIndex: PrimordialMethod<Array<any>, "findIndex">;
declare const $ArrayPrototypeFindLastIndex: PrimordialMethod<Array<any>, "findLastIndex">;
declare const $ArrayPrototypeIncludes: PrimordialMethod<Array<any>, "includes">;
declare const $ArrayPrototypeCopyWithin: PrimordialMethod<Array<any>, "copyWithin">;
declare const $ArrayPrototypeAt: PrimordialMethod<Array<any>, "at">;
declare const $ArrayPrototypeToReversed: PrimordialMethod<Array<any>, "toReversed">;
declare const $ArrayPrototypeToSorted: PrimordialMethod<Array<any>, "toSorted">;
declare const $ArrayPrototypeToSpliced: PrimordialMethod<Array<any>, "toSpliced">;
declare const $ArrayPrototypeWith: PrimordialMethod<Array<any>, "with">;
declare const $ArrayPrototypeConstructor: PrimordialMethod<Array<any>, "constructor">;
declare const $ArrayPrototypeSymbolIterator: PrimordialMethod<Array<any>, typeof Symbol.iterator>;
declare const $ArrayPrototypeSymbolUnscopables: PrimordialValue<Array<any>, typeof Symbol.unscopables>;
declare const $ArrayBufferPrimordial: ArrayBufferConstructor;
declare const $ArrayBufferPrototype: ArrayBuffer;
declare const $ArrayBufferIsView: PrimordialMethod<ArrayBufferConstructor, "isView">;
declare const $ArrayBufferGetSymbolSpecies: PrimordialGetter<ArrayBufferConstructor, typeof Symbol.species>;
declare const $ArrayBufferPrototypeSlice: PrimordialMethod<ArrayBuffer, "slice">;
declare const $ArrayBufferPrototypeGetByteLength: PrimordialGetter<ArrayBuffer, "byteLength">;
declare const $ArrayBufferPrototypeResize: PrimordialMethod<ArrayBuffer, "resize">;
declare const $ArrayBufferPrototypeTransfer: PrimordialMethod<ArrayBuffer, "transfer">;
declare const $ArrayBufferPrototypeTransferToFixedLength: PrimordialMethod<ArrayBuffer, "transferToFixedLength">;
declare const $ArrayBufferPrototypeGetResizable: PrimordialGetter<ArrayBuffer, "resizable">;
declare const $ArrayBufferPrototypeGetMaxByteLength: PrimordialGetter<ArrayBuffer, "maxByteLength">;
declare const $ArrayBufferPrototypeGetDetached: PrimordialGetter<ArrayBuffer, "detached">;
declare const $ArrayBufferPrototypeConstructor: PrimordialMethod<ArrayBuffer, "constructor">;
declare const $BigInt: BigIntConstructor;
declare const $BigIntAsUintN: PrimordialMethod<BigIntConstructor, "asUintN">;
declare const $BigIntAsIntN: PrimordialMethod<BigIntConstructor, "asIntN">;
declare const $BigIntPrototype: BigInt;
declare const $BigIntPrototypeToString: PrimordialMethod<BigInt, "toString">;
declare const $BigIntPrototypeToLocaleString: PrimordialMethod<BigInt, "toLocaleString">;
declare const $BigIntPrototypeValueOf: PrimordialMethod<BigInt, "valueOf">;
declare const $BigIntPrototypeConstructor: PrimordialMethod<BigInt, "constructor">;
declare const $BigInt64ArrayPrototype: BigInt64Array;
declare const $BigInt64ArrayPrototypeConstructor: PrimordialMethod<BigInt64Array, "constructor">;
declare const $BigUint64ArrayPrototype: BigUint64Array;
declare const $BigUint64ArrayPrototypeConstructor: PrimordialMethod<BigUint64Array, "constructor">;
declare const $Boolean: BooleanConstructor;
declare const $BooleanPrototype: Boolean;
declare const $BooleanPrototypeToString: PrimordialMethod<Boolean, "toString">;
declare const $BooleanPrototypeValueOf: PrimordialMethod<Boolean, "valueOf">;
declare const $BooleanPrototypeConstructor: PrimordialMethod<Boolean, "constructor">;
declare const $DataView: DataViewConstructor;
declare const $DataViewPrototype: DataView;
declare const $DataViewPrototypeGetInt8: PrimordialMethod<DataView, "getInt8">;
declare const $DataViewPrototypeGetUint8: PrimordialMethod<DataView, "getUint8">;
declare const $DataViewPrototypeGetInt16: PrimordialMethod<DataView, "getInt16">;
declare const $DataViewPrototypeGetUint16: PrimordialMethod<DataView, "getUint16">;
declare const $DataViewPrototypeGetInt32: PrimordialMethod<DataView, "getInt32">;
declare const $DataViewPrototypeGetUint32: PrimordialMethod<DataView, "getUint32">;
declare const $DataViewPrototypeGetFloat16: PrimordialMethod<DataView, "getFloat16">;
declare const $DataViewPrototypeGetFloat32: PrimordialMethod<DataView, "getFloat32">;
declare const $DataViewPrototypeGetFloat64: PrimordialMethod<DataView, "getFloat64">;
declare const $DataViewPrototypeGetBigInt64: PrimordialMethod<DataView, "getBigInt64">;
declare const $DataViewPrototypeGetBigUint64: PrimordialMethod<DataView, "getBigUint64">;
declare const $DataViewPrototypeSetInt8: PrimordialMethod<DataView, "setInt8">;
declare const $DataViewPrototypeSetUint8: PrimordialMethod<DataView, "setUint8">;
declare const $DataViewPrototypeSetInt16: PrimordialMethod<DataView, "setInt16">;
declare const $DataViewPrototypeSetUint16: PrimordialMethod<DataView, "setUint16">;
declare const $DataViewPrototypeSetInt32: PrimordialMethod<DataView, "setInt32">;
declare const $DataViewPrototypeSetUint32: PrimordialMethod<DataView, "setUint32">;
declare const $DataViewPrototypeSetFloat16: PrimordialMethod<DataView, "setFloat16">;
declare const $DataViewPrototypeSetFloat32: PrimordialMethod<DataView, "setFloat32">;
declare const $DataViewPrototypeSetFloat64: PrimordialMethod<DataView, "setFloat64">;
declare const $DataViewPrototypeSetBigInt64: PrimordialMethod<DataView, "setBigInt64">;
declare const $DataViewPrototypeSetBigUint64: PrimordialMethod<DataView, "setBigUint64">;
declare const $DataViewPrototypeGetBuffer: PrimordialGetter<DataView, "buffer">;
declare const $DataViewPrototypeGetByteOffset: PrimordialGetter<DataView, "byteOffset">;
declare const $DataViewPrototypeGetByteLength: PrimordialGetter<DataView, "byteLength">;
declare const $DataViewPrototypeConstructor: PrimordialMethod<DataView, "constructor">;
declare const $Date: DateConstructor;
declare const $DateParse: PrimordialMethod<DateConstructor, "parse">;
declare const $DateUTC: PrimordialMethod<DateConstructor, "UTC">;
declare const $DateNow: PrimordialMethod<DateConstructor, "now">;
declare const $DatePrototype: Date;
declare const $DatePrototypeToString: PrimordialMethod<Date, "toString">;
declare const $DatePrototypeToISOString: PrimordialMethod<Date, "toISOString">;
declare const $DatePrototypeToDateString: PrimordialMethod<Date, "toDateString">;
declare const $DatePrototypeToTimeString: PrimordialMethod<Date, "toTimeString">;
declare const $DatePrototypeToLocaleString: PrimordialMethod<Date, "toLocaleString">;
declare const $DatePrototypeToLocaleDateString: PrimordialMethod<Date, "toLocaleDateString">;
declare const $DatePrototypeToLocaleTimeString: PrimordialMethod<Date, "toLocaleTimeString">;
declare const $DatePrototypeValueOf: PrimordialMethod<Date, "valueOf">;
declare const $DatePrototypeGetTime: PrimordialMethod<Date, "getTime">;
declare const $DatePrototypeGetFullYear: PrimordialMethod<Date, "getFullYear">;
declare const $DatePrototypeGetUTCFullYear: PrimordialMethod<Date, "getUTCFullYear">;
declare const $DatePrototypeGetMonth: PrimordialMethod<Date, "getMonth">;
declare const $DatePrototypeGetUTCMonth: PrimordialMethod<Date, "getUTCMonth">;
declare const $DatePrototypeGetDate: PrimordialMethod<Date, "getDate">;
declare const $DatePrototypeGetUTCDate: PrimordialMethod<Date, "getUTCDate">;
declare const $DatePrototypeGetDay: PrimordialMethod<Date, "getDay">;
declare const $DatePrototypeGetUTCDay: PrimordialMethod<Date, "getUTCDay">;
declare const $DatePrototypeGetHours: PrimordialMethod<Date, "getHours">;
declare const $DatePrototypeGetUTCHours: PrimordialMethod<Date, "getUTCHours">;
declare const $DatePrototypeGetMinutes: PrimordialMethod<Date, "getMinutes">;
declare const $DatePrototypeGetUTCMinutes: PrimordialMethod<Date, "getUTCMinutes">;
declare const $DatePrototypeGetSeconds: PrimordialMethod<Date, "getSeconds">;
declare const $DatePrototypeGetUTCSeconds: PrimordialMethod<Date, "getUTCSeconds">;
declare const $DatePrototypeGetMilliseconds: PrimordialMethod<Date, "getMilliseconds">;
declare const $DatePrototypeGetUTCMilliseconds: PrimordialMethod<Date, "getUTCMilliseconds">;
declare const $DatePrototypeGetTimezoneOffset: PrimordialMethod<Date, "getTimezoneOffset">;
declare const $DatePrototypeGetYear: PrimordialMethod<Date, "getYear">;
declare const $DatePrototypeSetTime: PrimordialMethod<Date, "setTime">;
declare const $DatePrototypeSetMilliseconds: PrimordialMethod<Date, "setMilliseconds">;
declare const $DatePrototypeSetUTCMilliseconds: PrimordialMethod<Date, "setUTCMilliseconds">;
declare const $DatePrototypeSetSeconds: PrimordialMethod<Date, "setSeconds">;
declare const $DatePrototypeSetUTCSeconds: PrimordialMethod<Date, "setUTCSeconds">;
declare const $DatePrototypeSetMinutes: PrimordialMethod<Date, "setMinutes">;
declare const $DatePrototypeSetUTCMinutes: PrimordialMethod<Date, "setUTCMinutes">;
declare const $DatePrototypeSetHours: PrimordialMethod<Date, "setHours">;
declare const $DatePrototypeSetUTCHours: PrimordialMethod<Date, "setUTCHours">;
declare const $DatePrototypeSetDate: PrimordialMethod<Date, "setDate">;
declare const $DatePrototypeSetUTCDate: PrimordialMethod<Date, "setUTCDate">;
declare const $DatePrototypeSetMonth: PrimordialMethod<Date, "setMonth">;
declare const $DatePrototypeSetUTCMonth: PrimordialMethod<Date, "setUTCMonth">;
declare const $DatePrototypeSetFullYear: PrimordialMethod<Date, "setFullYear">;
declare const $DatePrototypeSetUTCFullYear: PrimordialMethod<Date, "setUTCFullYear">;
declare const $DatePrototypeSetYear: PrimordialMethod<Date, "setYear">;
declare const $DatePrototypeToJSON: PrimordialMethod<Date, "toJSON">;
declare const $DatePrototypeToUTCString: PrimordialMethod<Date, "toUTCString">;
declare const $DatePrototypeToGMTString: PrimordialMethod<Date, "toGMTString">;
declare const $DatePrototypeConstructor: PrimordialMethod<Date, "constructor">;
declare const $DatePrototypeSymbolToPrimitive: PrimordialMethod<Date, typeof Symbol.toPrimitive>;
declare const $Error: ErrorConstructor;
declare const $ErrorPrototype: Error;
declare const $ErrorCaptureStackTrace: PrimordialMethod<ErrorConstructor, "captureStackTrace">;
declare const $ErrorIsError: PrimordialMethod<ErrorConstructor, "isError">;
declare const $ErrorAppendStackTrace: PrimordialMethod<ErrorConstructor, "appendStackTrace">;
declare const $ErrorPrepareStackTrace: PrimordialMethod<ErrorConstructor, "prepareStackTrace">;
declare const $ErrorPrototypeToString: PrimordialMethod<Error, "toString">;
declare const $ErrorPrototypeConstructor: PrimordialMethod<Error, "constructor">;
declare const $EvalError: ErrorConstructor;
declare const $EvalErrorPrototype: ErrorConstructor;
declare const $EvalErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $FinalizationRegistry: FinalizationRegistryConstructor;
declare const $FinalizationRegistryPrototype: FinalizationRegistry<any>;
declare const $FinalizationRegistryPrototypeRegister: PrimordialMethod<FinalizationRegistry<any>, "register">;
declare const $FinalizationRegistryPrototypeUnregister: PrimordialMethod<FinalizationRegistry<any>, "unregister">;
declare const $FinalizationRegistryPrototypeConstructor: PrimordialMethod<FinalizationRegistry<any>, "constructor">;
declare const $Float32ArrayPrototype: Float32Array;
declare const $Float32ArrayPrototypeConstructor: PrimordialMethod<Float32Array, "constructor">;
declare const $Float64ArrayPrototype: Float64Array;
declare const $Float64ArrayPrototypeConstructor: PrimordialMethod<Float64Array, "constructor">;
declare const $Function: FunctionConstructor;
declare const $FunctionPrototype: PrimordialMethod<FunctionConstructor, "prototype">;
declare const $FunctionPrototypeToString: PrimordialMethod<Function, "toString">;
declare const $FunctionPrototypeApply: PrimordialMethod<Function, "apply">;
declare const $FunctionPrototypeCall: PrimordialMethod<Function, "call">;
declare const $FunctionPrototypeBind: PrimordialMethod<Function, "bind">;
declare const $FunctionPrototypeGetArguments: PrimordialGetter<Function, "arguments">;
declare const $FunctionPrototypeSetArguments: PrimordialSetter<Function, "arguments">;
declare const $FunctionPrototypeGetCaller: PrimordialGetter<Function, "caller">;
declare const $FunctionPrototypeSetCaller: PrimordialSetter<Function, "caller">;
declare const $FunctionPrototypeConstructor: PrimordialMethod<Function, "constructor">;
declare const $FunctionPrototypeSymbolHasInstance: PrimordialMethod<Function, typeof Symbol.hasInstance>;
declare const $Int16ArrayPrototype: Int16Array;
declare const $Int16ArrayPrototypeConstructor: PrimordialMethod<Int16Array, "constructor">;
declare const $Int32ArrayPrototype: Int32Array;
declare const $Int32ArrayPrototypeConstructor: PrimordialMethod<Int32Array, "constructor">;
declare const $Int8ArrayPrototype: Int8Array;
declare const $Int8ArrayPrototypeConstructor: PrimordialMethod<Int8Array, "constructor">;
declare const $IteratorPrototype: IteratorObject<any>;
declare const $IteratorFrom: PrimordialMethod<typeof Iterator, "from">;
declare const $IteratorConcat: PrimordialMethod<typeof Iterator, "concat">;
declare const $IteratorPrototypeGetConstructor: PrimordialGetter<IteratorObject<any>, "constructor">;
declare const $IteratorPrototypeSetConstructor: PrimordialSetter<IteratorObject<any>, "constructor">;
declare const $IteratorPrototypeToArray: PrimordialMethod<IteratorObject<any>, "toArray">;
declare const $IteratorPrototypeForEach: PrimordialMethod<IteratorObject<any>, "forEach">;
declare const $IteratorPrototypeSome: PrimordialMethod<IteratorObject<any>, "some">;
declare const $IteratorPrototypeEvery: PrimordialMethod<IteratorObject<any>, "every">;
declare const $IteratorPrototypeFind: PrimordialMethod<IteratorObject<any>, "find">;
declare const $IteratorPrototypeReduce: PrimordialMethod<IteratorObject<any>, "reduce">;
declare const $IteratorPrototypeMap: PrimordialMethod<IteratorObject<any>, "map">;
declare const $IteratorPrototypeFilter: PrimordialMethod<IteratorObject<any>, "filter">;
declare const $IteratorPrototypeTake: PrimordialMethod<IteratorObject<any>, "take">;
declare const $IteratorPrototypeDrop: PrimordialMethod<IteratorObject<any>, "drop">;
declare const $IteratorPrototypeFlatMap: PrimordialMethod<IteratorObject<any>, "flatMap">;
declare const $IteratorPrototypeSymbolIterator: PrimordialMethod<IteratorObject<any>, typeof Symbol.iterator>;
declare const $IteratorPrototypeGetSymbolToStringTag: PrimordialGetter<IteratorObject<any>, typeof Symbol.toStringTag>;
declare const $IteratorPrototypeSetSymbolToStringTag: PrimordialSetter<IteratorObject<any>, typeof Symbol.toStringTag>;
declare const $IteratorPrototypeSymbolDispose: PrimordialMethod<IteratorObject<any>, typeof Symbol.dispose>;
declare const $MapPrototype: Map<any, any>;
declare const $MapGroupBy: PrimordialMethod<MapConstructor, "groupBy">;
declare const $MapGetSymbolSpecies: PrimordialGetter<MapConstructor, typeof Symbol.species>;
declare const $MapPrototypeClear: PrimordialMethod<Map<any, any>, "clear">;
declare const $MapPrototypeDelete: PrimordialMethod<Map<any, any>, "delete">;
declare const $MapPrototypeEntries: PrimordialMethod<Map<any, any>, "entries">;
declare const $MapPrototypeForEach: PrimordialMethod<Map<any, any>, "forEach">;
declare const $MapPrototypeGet: PrimordialMethod<Map<any, any>, "get">;
declare const $MapPrototypeHas: PrimordialMethod<Map<any, any>, "has">;
declare const $MapPrototypeKeys: PrimordialMethod<Map<any, any>, "keys">;
declare const $MapPrototypeSet: PrimordialMethod<Map<any, any>, "set">;
declare const $MapPrototypeGetOrInsert: PrimordialMethod<Map<any, any>, "getOrInsert">;
declare const $MapPrototypeGetOrInsertComputed: PrimordialMethod<Map<any, any>, "getOrInsertComputed">;
declare const $MapPrototypeGetSize: PrimordialGetter<Map<any, any>, "size">;
declare const $MapPrototypeValues: PrimordialMethod<Map<any, any>, "values">;
declare const $MapPrototypeConstructor: PrimordialMethod<Map<any, any>, "constructor">;
declare const $MapPrototypeSymbolIterator: PrimordialMethod<Map<any, any>, typeof Symbol.iterator>;
declare const $NumberPrimordial: NumberConstructor;
declare const $NumberIsFinite: PrimordialMethod<NumberConstructor, "isFinite">;
declare const $NumberIsNaN: PrimordialMethod<NumberConstructor, "isNaN">;
declare const $NumberIsSafeInteger: PrimordialMethod<NumberConstructor, "isSafeInteger">;
declare const $NumberPrototype: Number;
declare const $NumberParseInt: PrimordialMethod<NumberConstructor, "parseInt">;
declare const $NumberParseFloat: PrimordialMethod<NumberConstructor, "parseFloat">;
declare const $NumberIsInteger: PrimordialMethod<NumberConstructor, "isInteger">;
declare const $NumberPrototypeToLocaleString: PrimordialMethod<Number, "toLocaleString">;
declare const $NumberPrototypeValueOf: PrimordialMethod<Number, "valueOf">;
declare const $NumberPrototypeToFixed: PrimordialMethod<Number, "toFixed">;
declare const $NumberPrototypeToExponential: PrimordialMethod<Number, "toExponential">;
declare const $NumberPrototypeToPrecision: PrimordialMethod<Number, "toPrecision">;
declare const $NumberPrototypeToString: PrimordialMethod<Number, "toString">;
declare const $NumberPrototypeConstructor: PrimordialMethod<Number, "constructor">;
declare const $ObjectGetPrototypeOf: PrimordialMethod<ObjectConstructor, "getPrototypeOf">;
declare const $ObjectSetPrototypeOf: PrimordialMethod<ObjectConstructor, "setPrototypeOf">;
declare const $ObjectGetOwnPropertyDescriptor: PrimordialMethod<ObjectConstructor, "getOwnPropertyDescriptor">;
declare const $ObjectGetOwnPropertyDescriptors: PrimordialMethod<ObjectConstructor, "getOwnPropertyDescriptors">;
declare const $ObjectGetOwnPropertyNames: PrimordialMethod<ObjectConstructor, "getOwnPropertyNames">;
declare const $ObjectGetOwnPropertySymbols: PrimordialMethod<ObjectConstructor, "getOwnPropertySymbols">;
declare const $ObjectKeys: PrimordialMethod<ObjectConstructor, "keys">;
declare const $ObjectDefineProperty: PrimordialMethod<ObjectConstructor, "defineProperty">;
declare const $ObjectDefineProperties: PrimordialMethod<ObjectConstructor, "defineProperties">;
declare const $ObjectCreate: PrimordialMethod<ObjectConstructor, "create">;
declare const $ObjectSeal: PrimordialMethod<ObjectConstructor, "seal">;
declare const $ObjectFreeze: PrimordialMethod<ObjectConstructor, "freeze">;
declare const $ObjectPreventExtensions: PrimordialMethod<ObjectConstructor, "preventExtensions">;
declare const $ObjectIsSealed: PrimordialMethod<ObjectConstructor, "isSealed">;
declare const $ObjectIsFrozen: PrimordialMethod<ObjectConstructor, "isFrozen">;
declare const $ObjectIsExtensible: PrimordialMethod<ObjectConstructor, "isExtensible">;
declare const $ObjectIs: PrimordialMethod<ObjectConstructor, "is">;
declare const $ObjectAssign: PrimordialMethod<ObjectConstructor, "assign">;
declare const $ObjectValues: PrimordialMethod<ObjectConstructor, "values">;
declare const $ObjectEntries: PrimordialMethod<ObjectConstructor, "entries">;
declare const $ObjectFromEntries: PrimordialMethod<ObjectConstructor, "fromEntries">;
declare const $ObjectPrototype: Object;
declare const $ObjectHasOwn: PrimordialMethod<ObjectConstructor, "hasOwn">;
declare const $ObjectGroupBy: PrimordialMethod<ObjectConstructor, "groupBy">;
declare const $ObjectPrototypeToString: PrimordialMethod<Object, "toString">;
declare const $ObjectPrototypeToLocaleString: PrimordialMethod<Object, "toLocaleString">;
declare const $ObjectPrototypeValueOf: PrimordialMethod<Object, "valueOf">;
declare const $ObjectPrototypeHasOwnProperty: PrimordialMethod<Object, "hasOwnProperty">;
declare const $ObjectPrototypePropertyIsEnumerable: PrimordialMethod<Object, "propertyIsEnumerable">;
declare const $ObjectPrototypeIsPrototypeOf: PrimordialMethod<Object, "isPrototypeOf">;
declare const $ObjectPrototype__defineGetter__: PrimordialMethod<Object, "__defineGetter__">;
declare const $ObjectPrototype__defineSetter__: PrimordialMethod<Object, "__defineSetter__">;
declare const $ObjectPrototype__lookupGetter__: PrimordialMethod<Object, "__lookupGetter__">;
declare const $ObjectPrototype__lookupSetter__: PrimordialMethod<Object, "__lookupSetter__">;
declare const $ObjectPrototypeGet__proto__: PrimordialGetter<Object, "__proto__">;
declare const $ObjectPrototypeSet__proto__: PrimordialSetter<Object, "__proto__">;
declare const $ObjectPrototypeConstructor: PrimordialMethod<Object, "constructor">;
declare const $RangeError: ErrorConstructor;
declare const $RangeErrorPrototype: ErrorConstructor;
declare const $RangeErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $ReferenceErrorPrototype: ErrorConstructor;
declare const $ReferenceErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $RegExpGetInput: PrimordialGetter<RegExpConstructor, "input">;
declare const $RegExpSetInput: PrimordialSetter<RegExpConstructor, "input">;
declare const $RegExpGetDollarUnderscore: PrimordialGetter<RegExpConstructor, "$_">;
declare const $RegExpSetDollarUnderscore: PrimordialSetter<RegExpConstructor, "$_">;
declare const $RegExpGetMultiline: PrimordialGetter<RegExpConstructor, "multiline">;
declare const $RegExpSetMultiline: PrimordialSetter<RegExpConstructor, "multiline">;
declare const $RegExpGetDollarAsterisk: PrimordialGetter<RegExpConstructor, "$*">;
declare const $RegExpSetDollarAsterisk: PrimordialSetter<RegExpConstructor, "$*">;
declare const $RegExpGetLastMatch: PrimordialGetter<RegExpConstructor, "lastMatch">;
declare const $RegExpGetDollarAmpersand: PrimordialGetter<RegExpConstructor, "$&">;
declare const $RegExpGetLastParen: PrimordialGetter<RegExpConstructor, "lastParen">;
declare const $RegExpGetDollarPlus: PrimordialGetter<RegExpConstructor, "$+">;
declare const $RegExpGetLeftContext: PrimordialGetter<RegExpConstructor, "leftContext">;
declare const $RegExpGetDollarBacktick: PrimordialGetter<RegExpConstructor, "$`">;
declare const $RegExpGetRightContext: PrimordialGetter<RegExpConstructor, "rightContext">;
declare const $RegExpGetDollarApostrophe: PrimordialGetter<RegExpConstructor, "$'">;
declare const $RegExpGetDollar1: PrimordialGetter<RegExpConstructor, "$1">;
declare const $RegExpGetDollar2: PrimordialGetter<RegExpConstructor, "$2">;
declare const $RegExpGetDollar3: PrimordialGetter<RegExpConstructor, "$3">;
declare const $RegExpGetDollar4: PrimordialGetter<RegExpConstructor, "$4">;
declare const $RegExpGetDollar5: PrimordialGetter<RegExpConstructor, "$5">;
declare const $RegExpGetDollar6: PrimordialGetter<RegExpConstructor, "$6">;
declare const $RegExpGetDollar7: PrimordialGetter<RegExpConstructor, "$7">;
declare const $RegExpGetDollar8: PrimordialGetter<RegExpConstructor, "$8">;
declare const $RegExpGetDollar9: PrimordialGetter<RegExpConstructor, "$9">;
declare const $RegExpPrototype: RegExp;
declare const $RegExpEscape: PrimordialMethod<RegExpConstructor, "escape">;
declare const $RegExpGetSymbolSpecies: PrimordialGetter<RegExpConstructor, typeof Symbol.species>;
declare const $RegExpPrototypeCompile: PrimordialMethod<RegExp, "compile">;
declare const $RegExpPrototypeExec: PrimordialMethod<RegExp, "exec">;
declare const $RegExpPrototypeToString: PrimordialMethod<RegExp, "toString">;
declare const $RegExpPrototypeGetGlobal: PrimordialGetter<RegExp, "global">;
declare const $RegExpPrototypeGetDotAll: PrimordialGetter<RegExp, "dotAll">;
declare const $RegExpPrototypeGetHasIndices: PrimordialGetter<RegExp, "hasIndices">;
declare const $RegExpPrototypeGetIgnoreCase: PrimordialGetter<RegExp, "ignoreCase">;
declare const $RegExpPrototypeGetMultiline: PrimordialGetter<RegExp, "multiline">;
declare const $RegExpPrototypeGetSticky: PrimordialGetter<RegExp, "sticky">;
declare const $RegExpPrototypeGetUnicode: PrimordialGetter<RegExp, "unicode">;
declare const $RegExpPrototypeGetUnicodeSets: PrimordialGetter<RegExp, "unicodeSets">;
declare const $RegExpPrototypeGetSource: PrimordialGetter<RegExp, "source">;
declare const $RegExpPrototypeGetFlags: PrimordialGetter<RegExp, "flags">;
declare const $RegExpPrototypeTest: PrimordialMethod<RegExp, "test">;
declare const $RegExpPrototypeConstructor: PrimordialMethod<RegExp, "constructor">;
declare const $RegExpPrototypeSymbolMatch: PrimordialMethod<RegExp, typeof Symbol.match>;
declare const $RegExpPrototypeSymbolMatchAll: PrimordialMethod<RegExp, typeof Symbol.matchAll>;
declare const $RegExpPrototypeSymbolReplace: PrimordialMethod<RegExp, typeof Symbol.replace>;
declare const $RegExpPrototypeSymbolSearch: PrimordialMethod<RegExp, typeof Symbol.search>;
declare const $RegExpPrototypeSymbolSplit: PrimordialMethod<RegExp, typeof Symbol.split>;
declare const $SetPrototype: Set<any>;
declare const $SetGetSymbolSpecies: PrimordialGetter<SetConstructor, typeof Symbol.species>;
declare const $SetPrototypeAdd: PrimordialMethod<Set<any>, "add">;
declare const $SetPrototypeClear: PrimordialMethod<Set<any>, "clear">;
declare const $SetPrototypeDelete: PrimordialMethod<Set<any>, "delete">;
declare const $SetPrototypeEntries: PrimordialMethod<Set<any>, "entries">;
declare const $SetPrototypeForEach: PrimordialMethod<Set<any>, "forEach">;
declare const $SetPrototypeHas: PrimordialMethod<Set<any>, "has">;
declare const $SetPrototypeKeys: PrimordialMethod<Set<any>, "keys">;
declare const $SetPrototypeGetSize: PrimordialGetter<Set<any>, "size">;
declare const $SetPrototypeValues: PrimordialMethod<Set<any>, "values">;
declare const $SetPrototypeUnion: PrimordialMethod<Set<any>, "union">;
declare const $SetPrototypeIntersection: PrimordialMethod<Set<any>, "intersection">;
declare const $SetPrototypeDifference: PrimordialMethod<Set<any>, "difference">;
declare const $SetPrototypeSymmetricDifference: PrimordialMethod<Set<any>, "symmetricDifference">;
declare const $SetPrototypeIsSubsetOf: PrimordialMethod<Set<any>, "isSubsetOf">;
declare const $SetPrototypeIsSupersetOf: PrimordialMethod<Set<any>, "isSupersetOf">;
declare const $SetPrototypeIsDisjointFrom: PrimordialMethod<Set<any>, "isDisjointFrom">;
declare const $SetPrototypeConstructor: PrimordialMethod<Set<any>, "constructor">;
declare const $SetPrototypeSymbolIterator: PrimordialMethod<Set<any>, typeof Symbol.iterator>;
declare const $StringFromCharCode: PrimordialMethod<StringConstructor, "fromCharCode">;
declare const $StringFromCodePoint: PrimordialMethod<StringConstructor, "fromCodePoint">;
declare const $StringRaw: PrimordialMethod<StringConstructor, "raw">;
declare const $StringPrototype: String;
declare const $StringPrototypeAnchor: PrimordialMethod<String, "anchor">;
declare const $StringPrototypeBig: PrimordialMethod<String, "big">;
declare const $StringPrototypeBold: PrimordialMethod<String, "bold">;
declare const $StringPrototypeBlink: PrimordialMethod<String, "blink">;
declare const $StringPrototypeFixed: PrimordialMethod<String, "fixed">;
declare const $StringPrototypeFontcolor: PrimordialMethod<String, "fontcolor">;
declare const $StringPrototypeFontsize: PrimordialMethod<String, "fontsize">;
declare const $StringPrototypeItalics: PrimordialMethod<String, "italics">;
declare const $StringPrototypeLink: PrimordialMethod<String, "link">;
declare const $StringPrototypeSmall: PrimordialMethod<String, "small">;
declare const $StringPrototypeStrike: PrimordialMethod<String, "strike">;
declare const $StringPrototypeSub: PrimordialMethod<String, "sub">;
declare const $StringPrototypeSup: PrimordialMethod<String, "sup">;
declare const $StringPrototypeToString: PrimordialMethod<String, "toString">;
declare const $StringPrototypeValueOf: PrimordialMethod<String, "valueOf">;
declare const $StringPrototypeCharAt: PrimordialMethod<String, "charAt">;
declare const $StringPrototypeCharCodeAt: PrimordialMethod<String, "charCodeAt">;
declare const $StringPrototypeCodePointAt: PrimordialMethod<String, "codePointAt">;
declare const $StringPrototypeConcat: PrimordialMethod<String, "concat">;
declare const $StringPrototypeIndexOf: PrimordialMethod<String, "indexOf">;
declare const $StringPrototypeLastIndexOf: PrimordialMethod<String, "lastIndexOf">;
declare const $StringPrototypeReplace: PrimordialMethod<String, "replace">;
declare const $StringPrototypeReplaceAll: PrimordialMethod<String, "replaceAll">;
declare const $StringPrototypeRepeat: PrimordialMethod<String, "repeat">;
declare const $StringPrototypePadStart: PrimordialMethod<String, "padStart">;
declare const $StringPrototypePadEnd: PrimordialMethod<String, "padEnd">;
declare const $StringPrototypeSlice: PrimordialMethod<String, "slice">;
declare const $StringPrototypeSubstr: PrimordialMethod<String, "substr">;
declare const $StringPrototypeAt: PrimordialMethod<String, "at">;
declare const $StringPrototypeSubstring: PrimordialMethod<String, "substring">;
declare const $StringPrototypeToLowerCase: PrimordialMethod<String, "toLowerCase">;
declare const $StringPrototypeToUpperCase: PrimordialMethod<String, "toUpperCase">;
declare const $StringPrototypeLocaleCompare: PrimordialMethod<String, "localeCompare">;
declare const $StringPrototypeToLocaleLowerCase: PrimordialMethod<String, "toLocaleLowerCase">;
declare const $StringPrototypeToLocaleUpperCase: PrimordialMethod<String, "toLocaleUpperCase">;
declare const $StringPrototypeTrim: PrimordialMethod<String, "trim">;
declare const $StringPrototypeStartsWith: PrimordialMethod<String, "startsWith">;
declare const $StringPrototypeEndsWith: PrimordialMethod<String, "endsWith">;
declare const $StringPrototypeIncludes: PrimordialMethod<String, "includes">;
declare const $StringPrototypeMatch: PrimordialMethod<String, "match">;
declare const $StringPrototypeSearch: PrimordialMethod<String, "search">;
declare const $StringPrototypeMatchAll: PrimordialMethod<String, "matchAll">;
declare const $StringPrototypeSplit: PrimordialMethod<String, "split">;
declare const $StringPrototypeNormalize: PrimordialMethod<String, "normalize">;
declare const $StringPrototypeTrimStart: PrimordialMethod<String, "trimStart">;
declare const $StringPrototypeTrimLeft: PrimordialMethod<String, "trimLeft">;
declare const $StringPrototypeTrimEnd: PrimordialMethod<String, "trimEnd">;
declare const $StringPrototypeTrimRight: PrimordialMethod<String, "trimRight">;
declare const $StringPrototypeIsWellFormed: PrimordialMethod<String, "isWellFormed">;
declare const $StringPrototypeToWellFormed: PrimordialMethod<String, "toWellFormed">;
declare const $StringPrototypeConstructor: PrimordialMethod<String, "constructor">;
declare const $StringPrototypeSymbolIterator: PrimordialMethod<String, typeof Symbol.iterator>;
declare const $Symbol: SymbolConstructor;
declare const $SymbolFor: PrimordialMethod<SymbolConstructor, "for">;
declare const $SymbolKeyFor: PrimordialMethod<SymbolConstructor, "keyFor">;
declare const $SymbolPrototype: Symbol;
declare const $SymbolHasInstance: PrimordialValue<SymbolConstructor, "hasInstance">;
declare const $SymbolIsConcatSpreadable: PrimordialValue<SymbolConstructor, "isConcatSpreadable">;
declare const $SymbolAsyncIterator: PrimordialValue<SymbolConstructor, "asyncIterator">;
declare const $SymbolIterator: PrimordialValue<SymbolConstructor, "iterator">;
declare const $SymbolMatch: PrimordialValue<SymbolConstructor, "match">;
declare const $SymbolMatchAll: PrimordialValue<SymbolConstructor, "matchAll">;
declare const $SymbolReplace: PrimordialValue<SymbolConstructor, "replace">;
declare const $SymbolSearch: PrimordialValue<SymbolConstructor, "search">;
declare const $SymbolSpecies: PrimordialValue<SymbolConstructor, "species">;
declare const $SymbolSplit: PrimordialValue<SymbolConstructor, "split">;
declare const $SymbolToPrimitive: PrimordialValue<SymbolConstructor, "toPrimitive">;
declare const $SymbolToStringTag: PrimordialValue<SymbolConstructor, "toStringTag">;
declare const $SymbolUnscopables: PrimordialValue<SymbolConstructor, "unscopables">;
declare const $SymbolDispose: PrimordialValue<SymbolConstructor, "dispose">;
declare const $SymbolAsyncDispose: PrimordialValue<SymbolConstructor, "asyncDispose">;
declare const $SymbolPrototypeGetDescription: PrimordialGetter<Symbol, "description">;
declare const $SymbolPrototypeToString: PrimordialMethod<Symbol, "toString">;
declare const $SymbolPrototypeValueOf: PrimordialMethod<Symbol, "valueOf">;
declare const $SymbolPrototypeConstructor: PrimordialMethod<Symbol, "constructor">;
declare const $SymbolPrototypeSymbolToPrimitive: PrimordialMethod<Symbol, typeof Symbol.toPrimitive>;
declare const $SyntaxError: ErrorConstructor;
declare const $SyntaxErrorPrototype: ErrorConstructor;
declare const $SyntaxErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $TypeError: ErrorConstructor;
declare const $TypeErrorPrototype: ErrorConstructor;
declare const $TypeErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $URIError: ErrorConstructor;
declare const $URIErrorPrototype: ErrorConstructor;
declare const $URIErrorPrototypeConstructor: PrimordialMethod<ErrorConstructor, "constructor">;
declare const $Uint16ArrayPrototype: Uint16Array;
declare const $Uint16ArrayPrototypeConstructor: PrimordialMethod<Uint16Array, "constructor">;
declare const $Uint32ArrayPrototype: Uint32Array;
declare const $Uint32ArrayPrototypeConstructor: PrimordialMethod<Uint32Array, "constructor">;
declare const $Uint8ArrayPrototype: Uint8Array;
declare const $Uint8ArrayFromBase64: PrimordialMethod<Uint8ArrayConstructor, "fromBase64">;
declare const $Uint8ArrayFromHex: PrimordialMethod<Uint8ArrayConstructor, "fromHex">;
declare const $Uint8ArrayPrototypeSetFromBase64: PrimordialMethod<Uint8Array, "setFromBase64">;
declare const $Uint8ArrayPrototypeSetFromHex: PrimordialMethod<Uint8Array, "setFromHex">;
declare const $Uint8ArrayPrototypeToBase64: PrimordialMethod<Uint8Array, "toBase64">;
declare const $Uint8ArrayPrototypeToHex: PrimordialMethod<Uint8Array, "toHex">;
declare const $Uint8ArrayPrototypeConstructor: PrimordialMethod<Uint8Array, "constructor">;
declare const $Uint8ClampedArrayPrototype: Uint8ClampedArray;
declare const $Uint8ClampedArrayPrototypeConstructor: PrimordialMethod<Uint8ClampedArray, "constructor">;
declare const $WeakMap: WeakMapConstructor;
declare const $WeakMapPrototype: WeakMap<any, any>;
declare const $WeakMapPrototypeDelete: PrimordialMethod<WeakMap<any, any>, "delete">;
declare const $WeakMapPrototypeGet: PrimordialMethod<WeakMap<any, any>, "get">;
declare const $WeakMapPrototypeHas: PrimordialMethod<WeakMap<any, any>, "has">;
declare const $WeakMapPrototypeSet: PrimordialMethod<WeakMap<any, any>, "set">;
declare const $WeakMapPrototypeGetOrInsert: PrimordialMethod<WeakMap<any, any>, "getOrInsert">;
declare const $WeakMapPrototypeGetOrInsertComputed: PrimordialMethod<WeakMap<any, any>, "getOrInsertComputed">;
declare const $WeakMapPrototypeConstructor: PrimordialMethod<WeakMap<any, any>, "constructor">;
declare const $WeakRef: WeakRefConstructor;
declare const $WeakRefPrototype: WeakRef<any>;
declare const $WeakRefPrototypeDeref: PrimordialMethod<WeakRef<any>, "deref">;
declare const $WeakRefPrototypeConstructor: PrimordialMethod<WeakRef<any>, "constructor">;
declare const $WeakSet: WeakSetConstructor;
declare const $WeakSetPrototype: WeakSet<any>;
declare const $WeakSetPrototypeDelete: PrimordialMethod<WeakSet<any>, "delete">;
declare const $WeakSetPrototypeHas: PrimordialMethod<WeakSet<any>, "has">;
declare const $WeakSetPrototypeAdd: PrimordialMethod<WeakSet<any>, "add">;
declare const $WeakSetPrototypeConstructor: PrimordialMethod<WeakSet<any>, "constructor">;
declare const $PromiseResolve: PrimordialMethod<PromiseConstructor, "resolve">;
declare const $PromiseReject: PrimordialMethod<PromiseConstructor, "reject">;
declare const $PromiseRace: PrimordialMethod<PromiseConstructor, "race">;
declare const $PromiseAll: PrimordialMethod<PromiseConstructor, "all">;
declare const $PromiseAllSettled: PrimordialMethod<PromiseConstructor, "allSettled">;
declare const $PromiseAny: PrimordialMethod<PromiseConstructor, "any">;
declare const $PromiseWithResolvers: PrimordialMethod<PromiseConstructor, "withResolvers">;
declare const $PromisePrototype: Promise<any>;
declare const $PromiseTry: PrimordialMethod<PromiseConstructor, "try">;
declare const $PromiseGetSymbolSpecies: PrimordialGetter<PromiseConstructor, typeof Symbol.species>;
declare const $PromisePrototypeFinally: PrimordialMethod<Promise<any>, "finally">;
declare const $PromisePrototypeThen: PrimordialMethod<Promise<any>, "then">;
declare const $PromisePrototypeCatch: PrimordialMethod<Promise<any>, "catch">;
declare const $PromisePrototypeConstructor: PrimordialMethod<Promise<any>, "constructor">;
declare const $TypedArray: Uint8ArrayConstructor;
declare const $TypedArrayPrototype: Uint8Array;
declare const $TypedArrayOf: PrimordialMethod<Uint8ArrayConstructor, "of">;
declare const $TypedArrayFrom: PrimordialMethod<Uint8ArrayConstructor, "from">;
declare const $TypedArrayGetSymbolSpecies: PrimordialGetter<Uint8ArrayConstructor, typeof Symbol.species>;
declare const $TypedArrayPrototypeToString: PrimordialMethod<Uint8Array, "toString">;
declare const $TypedArrayPrototypeGetBuffer: PrimordialGetter<Uint8Array, "buffer">;
declare const $TypedArrayPrototypeGetByteLength: PrimordialGetter<Uint8Array, "byteLength">;
declare const $TypedArrayPrototypeGetByteOffset: PrimordialGetter<Uint8Array, "byteOffset">;
declare const $TypedArrayPrototypeCopyWithin: PrimordialMethod<Uint8Array, "copyWithin">;
declare const $TypedArrayPrototypeSort: PrimordialMethod<Uint8Array, "sort">;
declare const $TypedArrayPrototypeEvery: PrimordialMethod<Uint8Array, "every">;
declare const $TypedArrayPrototypeFilter: PrimordialMethod<Uint8Array, "filter">;
declare const $TypedArrayPrototypeEntries: PrimordialMethod<Uint8Array, "entries">;
declare const $TypedArrayPrototypeIncludes: PrimordialMethod<Uint8Array, "includes">;
declare const $TypedArrayPrototypeFill: PrimordialMethod<Uint8Array, "fill">;
declare const $TypedArrayPrototypeFind: PrimordialMethod<Uint8Array, "find">;
declare const $TypedArrayPrototypeFindLast: PrimordialMethod<Uint8Array, "findLast">;
declare const $TypedArrayPrototypeFindIndex: PrimordialMethod<Uint8Array, "findIndex">;
declare const $TypedArrayPrototypeFindLastIndex: PrimordialMethod<Uint8Array, "findLastIndex">;
declare const $TypedArrayPrototypeForEach: PrimordialMethod<Uint8Array, "forEach">;
declare const $TypedArrayPrototypeIndexOf: PrimordialMethod<Uint8Array, "indexOf">;
declare const $TypedArrayPrototypeJoin: PrimordialMethod<Uint8Array, "join">;
declare const $TypedArrayPrototypeKeys: PrimordialMethod<Uint8Array, "keys">;
declare const $TypedArrayPrototypeLastIndexOf: PrimordialMethod<Uint8Array, "lastIndexOf">;
declare const $TypedArrayPrototypeGetLength: PrimordialGetter<Uint8Array, "length">;
declare const $TypedArrayPrototypeMap: PrimordialMethod<Uint8Array, "map">;
declare const $TypedArrayPrototypeReduce: PrimordialMethod<Uint8Array, "reduce">;
declare const $TypedArrayPrototypeReduceRight: PrimordialMethod<Uint8Array, "reduceRight">;
declare const $TypedArrayPrototypeReverse: PrimordialMethod<Uint8Array, "reverse">;
declare const $TypedArrayPrototypeSet: PrimordialMethod<Uint8Array, "set">;
declare const $TypedArrayPrototypeSlice: PrimordialMethod<Uint8Array, "slice">;
declare const $TypedArrayPrototypeSome: PrimordialMethod<Uint8Array, "some">;
declare const $TypedArrayPrototypeSubarray: PrimordialMethod<Uint8Array, "subarray">;
declare const $TypedArrayPrototypeToLocaleString: PrimordialMethod<Uint8Array, "toLocaleString">;
declare const $TypedArrayPrototypeToReversed: PrimordialMethod<Uint8Array, "toReversed">;
declare const $TypedArrayPrototypeToSorted: PrimordialMethod<Uint8Array, "toSorted">;
declare const $TypedArrayPrototypeWith: PrimordialMethod<Uint8Array, "with">;
declare const $TypedArrayPrototypeAt: PrimordialMethod<Uint8Array, "at">;
declare const $TypedArrayPrototypeValues: PrimordialMethod<Uint8Array, "values">;
declare const $TypedArrayPrototypeConstructor: PrimordialMethod<Uint8Array, "constructor">;
declare const $TypedArrayPrototypeGetSymbolToStringTag: PrimordialGetter<Uint8Array, typeof Symbol.toStringTag>;
declare const $TypedArrayPrototypeSymbolIterator: PrimordialMethod<Uint8Array, typeof Symbol.iterator>;
declare const $ArrayIteratorPrototype: ArrayIterator<any>;
declare const $ArrayIteratorPrototypeNext: PrimordialMethod<ArrayIterator<any>, "next">;
declare const $AsyncFunctionPrototype: Function;
declare const $AsyncFunctionPrototypeConstructor: PrimordialMethod<Function, "constructor">;
declare const $AsyncGeneratorFunctionPrototype: AsyncGeneratorFunction;
declare const $AsyncGeneratorFunctionPrototypeConstructor: PrimordialMethod<AsyncGeneratorFunction, "constructor">;
declare const $AsyncGeneratorFunctionPrototypePrototype: PrimordialValue<AsyncGeneratorFunction, "prototype">;
declare const $AsyncIteratorPrototype: AsyncIteratorObject<any>;
declare const $AsyncIteratorPrototypeSymbolAsyncIterator: PrimordialMethod<
  AsyncIteratorObject<any>,
  typeof Symbol.asyncIterator
>;
declare const $AsyncIteratorPrototypeSymbolAsyncDispose: PrimordialMethod<
  AsyncIteratorObject<any>,
  typeof Symbol.asyncDispose
>;
declare const $GeneratorFunctionPrototype: GeneratorFunction;
declare const $GeneratorFunctionPrototypeConstructor: PrimordialMethod<GeneratorFunction, "constructor">;
declare const $GeneratorFunctionPrototypePrototype: PrimordialValue<GeneratorFunction, "prototype">;
declare const $IteratorHelperPrototype: IteratorObject<any>;
declare const $IteratorHelperPrototypeNext: PrimordialMethod<IteratorObject<any>, "next">;
declare const $IteratorHelperPrototypeReturn: PrimordialMethod<IteratorObject<any>, "return">;
declare const $MapIteratorPrototype: MapIterator<any>;
declare const $MapIteratorPrototypeNext: PrimordialMethod<MapIterator<any>, "next">;
declare const $RegExpStringIteratorPrototype: RegExpStringIterator<any>;
declare const $RegExpStringIteratorPrototypeNext: PrimordialMethod<RegExpStringIterator<any>, "next">;
declare const $SetIteratorPrototype: SetIterator<any>;
declare const $SetIteratorPrototypeNext: PrimordialMethod<SetIterator<any>, "next">;
declare const $StringIteratorPrototype: StringIterator<any>;
declare const $StringIteratorPrototypeNext: PrimordialMethod<StringIterator<any>, "next">;
declare const $WrapForValidIteratorPrototype: IteratorObject<any>;
declare const $WrapForValidIteratorPrototypeNext: PrimordialMethod<IteratorObject<any>, "next">;
declare const $WrapForValidIteratorPrototypeReturn: PrimordialMethod<IteratorObject<any>, "return">;
