// GENERATED FILE — do not edit. Regenerate with: bun src/codegen/generate-primordials-dts.ts
//
// Tamper-proof references to the original ECMAScript builtins, exposed by JSC
// (JSCPrimordials.h) as link-time constants and named after Node.js's primordials.
// Prototype methods and getters take the receiver via .$call/.$apply:
//
//   $ArrayPrototypePush.$call(array, value);
//   $MapPrototypeGetSize.$call(map);
//   $ObjectDefineProperty(target, key, descriptor);

type PrimordialMethod<Holder, Key extends PropertyKey> =
  Holder extends Record<Key, infer Method>
    ? Method extends (...args: infer Args) => infer Return
      ? (this: Holder, ...args: Args) => Return
      : Function
    : Function;
type PrimordialGetter<Holder, Key extends PropertyKey> =
  Holder extends Record<Key, infer Value> ? (this: Holder) => Value : Function;

declare const $ObjectPrototypeHasOwnProperty: PrimordialMethod<Object, "hasOwnProperty">;
declare const $ObjectPrototypeIsPrototypeOf: PrimordialMethod<Object, "isPrototypeOf">;
declare const $ObjectPrototypePropertyIsEnumerable: PrimordialMethod<Object, "propertyIsEnumerable">;
declare const $ObjectPrototypeToLocaleString: PrimordialMethod<Object, "toLocaleString">;
declare const $ObjectPrototypeToString: PrimordialMethod<Object, "toString">;
declare const $ObjectPrototypeValueOf: PrimordialMethod<Object, "valueOf">;
declare const $ObjectPrototypeLookupGetter: PrimordialMethod<Object, "__lookupGetter__">;
declare const $ObjectPrototypeLookupSetter: PrimordialMethod<Object, "__lookupSetter__">;
declare const $ObjectPrototypeDefineGetter: PrimordialMethod<Object, "__defineGetter__">;
declare const $ObjectPrototypeDefineSetter: PrimordialMethod<Object, "__defineSetter__">;
declare const $ObjectAssign: PrimordialMethod<ObjectConstructor, "assign">;
declare const $ObjectCreate: PrimordialMethod<ObjectConstructor, "create">;
declare const $ObjectDefineProperties: PrimordialMethod<ObjectConstructor, "defineProperties">;
declare const $ObjectDefineProperty: PrimordialMethod<ObjectConstructor, "defineProperty">;
declare const $ObjectEntries: PrimordialMethod<ObjectConstructor, "entries">;
declare const $ObjectFreeze: PrimordialMethod<ObjectConstructor, "freeze">;
declare const $ObjectFromEntries: PrimordialMethod<ObjectConstructor, "fromEntries">;
declare const $ObjectGetOwnPropertyDescriptor: PrimordialMethod<ObjectConstructor, "getOwnPropertyDescriptor">;
declare const $ObjectGetOwnPropertyDescriptors: PrimordialMethod<ObjectConstructor, "getOwnPropertyDescriptors">;
declare const $ObjectGetOwnPropertyNames: PrimordialMethod<ObjectConstructor, "getOwnPropertyNames">;
declare const $ObjectGetOwnPropertySymbols: PrimordialMethod<ObjectConstructor, "getOwnPropertySymbols">;
declare const $ObjectGetPrototypeOf: PrimordialMethod<ObjectConstructor, "getPrototypeOf">;
declare const $ObjectGroupBy: PrimordialMethod<ObjectConstructor, "groupBy">;
declare const $ObjectHasOwn: PrimordialMethod<ObjectConstructor, "hasOwn">;
declare const $ObjectIs: PrimordialMethod<ObjectConstructor, "is">;
declare const $ObjectIsExtensible: PrimordialMethod<ObjectConstructor, "isExtensible">;
declare const $ObjectIsFrozen: PrimordialMethod<ObjectConstructor, "isFrozen">;
declare const $ObjectIsSealed: PrimordialMethod<ObjectConstructor, "isSealed">;
declare const $ObjectKeys: PrimordialMethod<ObjectConstructor, "keys">;
declare const $ObjectPreventExtensions: PrimordialMethod<ObjectConstructor, "preventExtensions">;
declare const $ObjectSeal: PrimordialMethod<ObjectConstructor, "seal">;
declare const $ObjectSetPrototypeOf: PrimordialMethod<ObjectConstructor, "setPrototypeOf">;
declare const $ObjectValues: PrimordialMethod<ObjectConstructor, "values">;
declare const $FunctionPrototypeApply: PrimordialMethod<Function, "apply">;
declare const $FunctionPrototypeBind: PrimordialMethod<Function, "bind">;
declare const $FunctionPrototypeCall: PrimordialMethod<Function, "call">;
declare const $FunctionPrototypeToString: PrimordialMethod<Function, "toString">;
declare const $FunctionPrototypeSymbolHasInstance: PrimordialMethod<Function, typeof Symbol.hasInstance>;
declare const $ArrayPrototypeAt: PrimordialMethod<Array<any>, "at">;
declare const $ArrayPrototypeConcat: PrimordialMethod<Array<any>, "concat">;
declare const $ArrayPrototypeCopyWithin: PrimordialMethod<Array<any>, "copyWithin">;
declare const $ArrayPrototypeEntries: PrimordialMethod<Array<any>, "entries">;
declare const $ArrayPrototypeEvery: PrimordialMethod<Array<any>, "every">;
declare const $ArrayPrototypeFill: PrimordialMethod<Array<any>, "fill">;
declare const $ArrayPrototypeFilter: PrimordialMethod<Array<any>, "filter">;
declare const $ArrayPrototypeFind: PrimordialMethod<Array<any>, "find">;
declare const $ArrayPrototypeFindIndex: PrimordialMethod<Array<any>, "findIndex">;
declare const $ArrayPrototypeFindLast: PrimordialMethod<Array<any>, "findLast">;
declare const $ArrayPrototypeFindLastIndex: PrimordialMethod<Array<any>, "findLastIndex">;
declare const $ArrayPrototypeFlat: PrimordialMethod<Array<any>, "flat">;
declare const $ArrayPrototypeFlatMap: PrimordialMethod<Array<any>, "flatMap">;
declare const $ArrayPrototypeForEach: PrimordialMethod<Array<any>, "forEach">;
declare const $ArrayPrototypeIncludes: PrimordialMethod<Array<any>, "includes">;
declare const $ArrayPrototypeIndexOf: PrimordialMethod<Array<any>, "indexOf">;
declare const $ArrayPrototypeJoin: PrimordialMethod<Array<any>, "join">;
declare const $ArrayPrototypeKeys: PrimordialMethod<Array<any>, "keys">;
declare const $ArrayPrototypeLastIndexOf: PrimordialMethod<Array<any>, "lastIndexOf">;
declare const $ArrayPrototypeMap: PrimordialMethod<Array<any>, "map">;
declare const $ArrayPrototypePop: PrimordialMethod<Array<any>, "pop">;
declare const $ArrayPrototypePush: PrimordialMethod<Array<any>, "push">;
declare const $ArrayPrototypeReduce: PrimordialMethod<Array<any>, "reduce">;
declare const $ArrayPrototypeReduceRight: PrimordialMethod<Array<any>, "reduceRight">;
declare const $ArrayPrototypeReverse: PrimordialMethod<Array<any>, "reverse">;
declare const $ArrayPrototypeShift: PrimordialMethod<Array<any>, "shift">;
declare const $ArrayPrototypeSlice: PrimordialMethod<Array<any>, "slice">;
declare const $ArrayPrototypeSome: PrimordialMethod<Array<any>, "some">;
declare const $ArrayPrototypeSort: PrimordialMethod<Array<any>, "sort">;
declare const $ArrayPrototypeSplice: PrimordialMethod<Array<any>, "splice">;
declare const $ArrayPrototypeToLocaleString: PrimordialMethod<Array<any>, "toLocaleString">;
declare const $ArrayPrototypeToReversed: PrimordialMethod<Array<any>, "toReversed">;
declare const $ArrayPrototypeToSorted: PrimordialMethod<Array<any>, "toSorted">;
declare const $ArrayPrototypeToSpliced: PrimordialMethod<Array<any>, "toSpliced">;
declare const $ArrayPrototypeToString: PrimordialMethod<Array<any>, "toString">;
declare const $ArrayPrototypeUnshift: PrimordialMethod<Array<any>, "unshift">;
declare const $ArrayPrototypeValues: PrimordialMethod<Array<any>, "values">;
declare const $ArrayPrototypeWith: PrimordialMethod<Array<any>, "with">;
declare const $ArrayPrototypeSymbolIterator: PrimordialMethod<Array<any>, typeof Symbol.iterator>;
declare const $ArrayFrom: PrimordialMethod<ArrayConstructor, "from">;
declare const $ArrayFromAsync: PrimordialMethod<ArrayConstructor, "fromAsync">;
declare const $ArrayIsArray: PrimordialMethod<ArrayConstructor, "isArray">;
declare const $ArrayOf: PrimordialMethod<ArrayConstructor, "of">;
declare const $StringPrototypeAt: PrimordialMethod<String, "at">;
declare const $StringPrototypeCharAt: PrimordialMethod<String, "charAt">;
declare const $StringPrototypeCharCodeAt: PrimordialMethod<String, "charCodeAt">;
declare const $StringPrototypeCodePointAt: PrimordialMethod<String, "codePointAt">;
declare const $StringPrototypeConcat: PrimordialMethod<String, "concat">;
declare const $StringPrototypeEndsWith: PrimordialMethod<String, "endsWith">;
declare const $StringPrototypeIncludes: PrimordialMethod<String, "includes">;
declare const $StringPrototypeIndexOf: PrimordialMethod<String, "indexOf">;
declare const $StringPrototypeIsWellFormed: PrimordialMethod<String, "isWellFormed">;
declare const $StringPrototypeLastIndexOf: PrimordialMethod<String, "lastIndexOf">;
declare const $StringPrototypeLocaleCompare: PrimordialMethod<String, "localeCompare">;
declare const $StringPrototypeMatch: PrimordialMethod<String, "match">;
declare const $StringPrototypeMatchAll: PrimordialMethod<String, "matchAll">;
declare const $StringPrototypeNormalize: PrimordialMethod<String, "normalize">;
declare const $StringPrototypePadEnd: PrimordialMethod<String, "padEnd">;
declare const $StringPrototypePadStart: PrimordialMethod<String, "padStart">;
declare const $StringPrototypeRepeat: PrimordialMethod<String, "repeat">;
declare const $StringPrototypeReplace: PrimordialMethod<String, "replace">;
declare const $StringPrototypeReplaceAll: PrimordialMethod<String, "replaceAll">;
declare const $StringPrototypeSearch: PrimordialMethod<String, "search">;
declare const $StringPrototypeSlice: PrimordialMethod<String, "slice">;
declare const $StringPrototypeSplit: PrimordialMethod<String, "split">;
declare const $StringPrototypeStartsWith: PrimordialMethod<String, "startsWith">;
declare const $StringPrototypeSubstr: PrimordialMethod<String, "substr">;
declare const $StringPrototypeSubstring: PrimordialMethod<String, "substring">;
declare const $StringPrototypeToLocaleLowerCase: PrimordialMethod<String, "toLocaleLowerCase">;
declare const $StringPrototypeToLocaleUpperCase: PrimordialMethod<String, "toLocaleUpperCase">;
declare const $StringPrototypeToLowerCase: PrimordialMethod<String, "toLowerCase">;
declare const $StringPrototypeToString: PrimordialMethod<String, "toString">;
declare const $StringPrototypeToUpperCase: PrimordialMethod<String, "toUpperCase">;
declare const $StringPrototypeToWellFormed: PrimordialMethod<String, "toWellFormed">;
declare const $StringPrototypeTrim: PrimordialMethod<String, "trim">;
declare const $StringPrototypeTrimEnd: PrimordialMethod<String, "trimEnd">;
declare const $StringPrototypeTrimStart: PrimordialMethod<String, "trimStart">;
declare const $StringPrototypeValueOf: PrimordialMethod<String, "valueOf">;
declare const $StringPrototypeSymbolIterator: PrimordialMethod<String, typeof Symbol.iterator>;
declare const $StringFromCharCode: PrimordialMethod<StringConstructor, "fromCharCode">;
declare const $StringFromCodePoint: PrimordialMethod<StringConstructor, "fromCodePoint">;
declare const $StringRaw: PrimordialMethod<StringConstructor, "raw">;
declare const $RegExpPrototypeCompile: PrimordialMethod<RegExp, "compile">;
declare const $RegExpPrototypeExec: PrimordialMethod<RegExp, "exec">;
declare const $RegExpPrototypeTest: PrimordialMethod<RegExp, "test">;
declare const $RegExpPrototypeToString: PrimordialMethod<RegExp, "toString">;
declare const $RegExpPrototypeGetDotAll: PrimordialGetter<RegExp, "dotAll">;
declare const $RegExpPrototypeGetFlags: PrimordialGetter<RegExp, "flags">;
declare const $RegExpPrototypeGetGlobal: PrimordialGetter<RegExp, "global">;
declare const $RegExpPrototypeGetHasIndices: PrimordialGetter<RegExp, "hasIndices">;
declare const $RegExpPrototypeGetIgnoreCase: PrimordialGetter<RegExp, "ignoreCase">;
declare const $RegExpPrototypeGetMultiline: PrimordialGetter<RegExp, "multiline">;
declare const $RegExpPrototypeGetSource: PrimordialGetter<RegExp, "source">;
declare const $RegExpPrototypeGetSticky: PrimordialGetter<RegExp, "sticky">;
declare const $RegExpPrototypeGetUnicode: PrimordialGetter<RegExp, "unicode">;
declare const $RegExpPrototypeGetUnicodeSets: PrimordialGetter<RegExp, "unicodeSets">;
declare const $RegExpPrototypeSymbolMatch: PrimordialMethod<RegExp, typeof Symbol.match>;
declare const $RegExpPrototypeSymbolMatchAll: PrimordialMethod<RegExp, typeof Symbol.matchAll>;
declare const $RegExpPrototypeSymbolReplace: PrimordialMethod<RegExp, typeof Symbol.replace>;
declare const $RegExpPrototypeSymbolSearch: PrimordialMethod<RegExp, typeof Symbol.search>;
declare const $RegExpPrototypeSymbolSplit: PrimordialMethod<RegExp, typeof Symbol.split>;
declare const $SymbolPrototypeGetDescription: PrimordialGetter<Symbol, "description">;
declare const $SymbolPrototypeToString: PrimordialMethod<Symbol, "toString">;
declare const $SymbolPrototypeValueOf: PrimordialMethod<Symbol, "valueOf">;
declare const $SymbolPrototypeSymbolToPrimitive: PrimordialMethod<Symbol, typeof Symbol.toPrimitive>;
declare const $SymbolFor: PrimordialMethod<SymbolConstructor, "for">;
declare const $SymbolKeyFor: PrimordialMethod<SymbolConstructor, "keyFor">;
declare const $BigIntPrototypeToLocaleString: PrimordialMethod<BigInt, "toLocaleString">;
declare const $BigIntPrototypeToString: PrimordialMethod<BigInt, "toString">;
declare const $BigIntPrototypeValueOf: PrimordialMethod<BigInt, "valueOf">;
declare const $BigIntAsIntN: PrimordialMethod<BigIntConstructor, "asIntN">;
declare const $BigIntAsUintN: PrimordialMethod<BigIntConstructor, "asUintN">;
declare const $PromisePrototypeCatch: PrimordialMethod<Promise<any>, "catch">;
declare const $PromisePrototypeFinally: PrimordialMethod<Promise<any>, "finally">;
declare const $PromisePrototypeThen: PrimordialMethod<Promise<any>, "then">;
declare const $PromiseAll: PrimordialMethod<PromiseConstructor, "all">;
declare const $PromiseAllSettled: PrimordialMethod<PromiseConstructor, "allSettled">;
declare const $PromiseAny: PrimordialMethod<PromiseConstructor, "any">;
declare const $PromiseRace: PrimordialMethod<PromiseConstructor, "race">;
declare const $PromiseReject: PrimordialMethod<PromiseConstructor, "reject">;
declare const $PromiseResolve: PrimordialMethod<PromiseConstructor, "resolve">;
declare const $PromiseTry: PrimordialMethod<PromiseConstructor, "try">;
declare const $PromiseWithResolvers: PrimordialMethod<PromiseConstructor, "withResolvers">;
declare const $IteratorPrototypeDrop: PrimordialMethod<IteratorObject<any>, "drop">;
declare const $IteratorPrototypeEvery: PrimordialMethod<IteratorObject<any>, "every">;
declare const $IteratorPrototypeFilter: PrimordialMethod<IteratorObject<any>, "filter">;
declare const $IteratorPrototypeFind: PrimordialMethod<IteratorObject<any>, "find">;
declare const $IteratorPrototypeFlatMap: PrimordialMethod<IteratorObject<any>, "flatMap">;
declare const $IteratorPrototypeForEach: PrimordialMethod<IteratorObject<any>, "forEach">;
declare const $IteratorPrototypeMap: PrimordialMethod<IteratorObject<any>, "map">;
declare const $IteratorPrototypeReduce: PrimordialMethod<IteratorObject<any>, "reduce">;
declare const $IteratorPrototypeSome: PrimordialMethod<IteratorObject<any>, "some">;
declare const $IteratorPrototypeTake: PrimordialMethod<IteratorObject<any>, "take">;
declare const $IteratorPrototypeToArray: PrimordialMethod<IteratorObject<any>, "toArray">;
declare const $IteratorPrototypeSymbolIterator: PrimordialMethod<IteratorObject<any>, typeof Symbol.iterator>;
declare const $IteratorFrom: PrimordialMethod<typeof Iterator, "from">;
declare const $ArrayIteratorPrototypeNext: PrimordialMethod<ArrayIterator<any>, "next">;
declare const $StringIteratorPrototypeNext: PrimordialMethod<StringIterator<any>, "next">;
declare const $MapIteratorPrototypeNext: PrimordialMethod<MapIterator<any>, "next">;
declare const $SetIteratorPrototypeNext: PrimordialMethod<SetIterator<any>, "next">;
declare const $RegExpStringIteratorPrototypeNext: PrimordialMethod<RegExpStringIterator<any>, "next">;
declare const $IteratorHelperPrototypeNext: PrimordialMethod<IteratorObject<any>, "next">;
declare const $IteratorHelperPrototypeReturn: PrimordialMethod<IteratorObject<any>, "return">;
declare const $WrapForValidIteratorPrototypeNext: PrimordialMethod<IteratorObject<any>, "next">;
declare const $WrapForValidIteratorPrototypeReturn: PrimordialMethod<IteratorObject<any>, "return">;
declare const $AsyncIteratorPrototypeSymbolAsyncIterator: PrimordialMethod<
  AsyncIteratorObject<any>,
  typeof Symbol.asyncIterator
>;
declare const $WeakRefPrototypeDeref: PrimordialMethod<WeakRef<any>, "deref">;
declare const $FinalizationRegistryPrototypeRegister: PrimordialMethod<FinalizationRegistry<any>, "register">;
declare const $FinalizationRegistryPrototypeUnregister: PrimordialMethod<FinalizationRegistry<any>, "unregister">;
declare const $globalDecodeURI: PrimordialMethod<typeof globalThis, "decodeURI">;
declare const $globalDecodeURIComponent: PrimordialMethod<typeof globalThis, "decodeURIComponent">;
declare const $globalEncodeURI: PrimordialMethod<typeof globalThis, "encodeURI">;
declare const $globalEncodeURIComponent: PrimordialMethod<typeof globalThis, "encodeURIComponent">;
declare const $globalEscape: PrimordialMethod<typeof globalThis, "escape">;
declare const $globalUnescape: PrimordialMethod<typeof globalThis, "unescape">;
declare const $BooleanPrototypeToString: PrimordialMethod<Boolean, "toString">;
declare const $BooleanPrototypeValueOf: PrimordialMethod<Boolean, "valueOf">;
declare const $DatePrototypeGetDate: PrimordialMethod<Date, "getDate">;
declare const $DatePrototypeGetDay: PrimordialMethod<Date, "getDay">;
declare const $DatePrototypeGetFullYear: PrimordialMethod<Date, "getFullYear">;
declare const $DatePrototypeGetHours: PrimordialMethod<Date, "getHours">;
declare const $DatePrototypeGetMilliseconds: PrimordialMethod<Date, "getMilliseconds">;
declare const $DatePrototypeGetMinutes: PrimordialMethod<Date, "getMinutes">;
declare const $DatePrototypeGetMonth: PrimordialMethod<Date, "getMonth">;
declare const $DatePrototypeGetSeconds: PrimordialMethod<Date, "getSeconds">;
declare const $DatePrototypeGetTime: PrimordialMethod<Date, "getTime">;
declare const $DatePrototypeGetTimezoneOffset: PrimordialMethod<Date, "getTimezoneOffset">;
declare const $DatePrototypeGetUTCDate: PrimordialMethod<Date, "getUTCDate">;
declare const $DatePrototypeGetUTCDay: PrimordialMethod<Date, "getUTCDay">;
declare const $DatePrototypeGetUTCFullYear: PrimordialMethod<Date, "getUTCFullYear">;
declare const $DatePrototypeGetUTCHours: PrimordialMethod<Date, "getUTCHours">;
declare const $DatePrototypeGetUTCMilliseconds: PrimordialMethod<Date, "getUTCMilliseconds">;
declare const $DatePrototypeGetUTCMinutes: PrimordialMethod<Date, "getUTCMinutes">;
declare const $DatePrototypeGetUTCMonth: PrimordialMethod<Date, "getUTCMonth">;
declare const $DatePrototypeGetUTCSeconds: PrimordialMethod<Date, "getUTCSeconds">;
declare const $DatePrototypeGetYear: PrimordialMethod<Date, "getYear">;
declare const $DatePrototypeSetDate: PrimordialMethod<Date, "setDate">;
declare const $DatePrototypeSetFullYear: PrimordialMethod<Date, "setFullYear">;
declare const $DatePrototypeSetHours: PrimordialMethod<Date, "setHours">;
declare const $DatePrototypeSetMilliseconds: PrimordialMethod<Date, "setMilliseconds">;
declare const $DatePrototypeSetMinutes: PrimordialMethod<Date, "setMinutes">;
declare const $DatePrototypeSetMonth: PrimordialMethod<Date, "setMonth">;
declare const $DatePrototypeSetSeconds: PrimordialMethod<Date, "setSeconds">;
declare const $DatePrototypeSetTime: PrimordialMethod<Date, "setTime">;
declare const $DatePrototypeSetUTCDate: PrimordialMethod<Date, "setUTCDate">;
declare const $DatePrototypeSetUTCFullYear: PrimordialMethod<Date, "setUTCFullYear">;
declare const $DatePrototypeSetUTCHours: PrimordialMethod<Date, "setUTCHours">;
declare const $DatePrototypeSetUTCMilliseconds: PrimordialMethod<Date, "setUTCMilliseconds">;
declare const $DatePrototypeSetUTCMinutes: PrimordialMethod<Date, "setUTCMinutes">;
declare const $DatePrototypeSetUTCMonth: PrimordialMethod<Date, "setUTCMonth">;
declare const $DatePrototypeSetUTCSeconds: PrimordialMethod<Date, "setUTCSeconds">;
declare const $DatePrototypeSetYear: PrimordialMethod<Date, "setYear">;
declare const $DatePrototypeToDateString: PrimordialMethod<Date, "toDateString">;
declare const $DatePrototypeToISOString: PrimordialMethod<Date, "toISOString">;
declare const $DatePrototypeToJSON: PrimordialMethod<Date, "toJSON">;
declare const $DatePrototypeToLocaleDateString: PrimordialMethod<Date, "toLocaleDateString">;
declare const $DatePrototypeToLocaleString: PrimordialMethod<Date, "toLocaleString">;
declare const $DatePrototypeToLocaleTimeString: PrimordialMethod<Date, "toLocaleTimeString">;
declare const $DatePrototypeToString: PrimordialMethod<Date, "toString">;
declare const $DatePrototypeToTimeString: PrimordialMethod<Date, "toTimeString">;
declare const $DatePrototypeToUTCString: PrimordialMethod<Date, "toUTCString">;
declare const $DatePrototypeValueOf: PrimordialMethod<Date, "valueOf">;
declare const $DatePrototypeSymbolToPrimitive: PrimordialMethod<Date, typeof Symbol.toPrimitive>;
declare const $DateNow: PrimordialMethod<DateConstructor, "now">;
declare const $DateParse: PrimordialMethod<DateConstructor, "parse">;
declare const $DateUTC: PrimordialMethod<DateConstructor, "UTC">;
declare const $ErrorPrototypeToString: PrimordialMethod<Error, "toString">;
declare const $ErrorCaptureStackTrace: PrimordialMethod<ErrorConstructor, "captureStackTrace">;
declare const $ErrorIsError: PrimordialMethod<ErrorConstructor, "isError">;
declare const $MapPrototypeClear: PrimordialMethod<Map<any, any>, "clear">;
declare const $MapPrototypeDelete: PrimordialMethod<Map<any, any>, "delete">;
declare const $MapPrototypeEntries: PrimordialMethod<Map<any, any>, "entries">;
declare const $MapPrototypeForEach: PrimordialMethod<Map<any, any>, "forEach">;
declare const $MapPrototypeGet: PrimordialMethod<Map<any, any>, "get">;
declare const $MapPrototypeHas: PrimordialMethod<Map<any, any>, "has">;
declare const $MapPrototypeKeys: PrimordialMethod<Map<any, any>, "keys">;
declare const $MapPrototypeSet: PrimordialMethod<Map<any, any>, "set">;
declare const $MapPrototypeValues: PrimordialMethod<Map<any, any>, "values">;
declare const $MapPrototypeGetSize: PrimordialGetter<Map<any, any>, "size">;
declare const $MapPrototypeSymbolIterator: PrimordialMethod<Map<any, any>, typeof Symbol.iterator>;
declare const $MapGroupBy: PrimordialMethod<MapConstructor, "groupBy">;
declare const $NumberPrototypeToExponential: PrimordialMethod<Number, "toExponential">;
declare const $NumberPrototypeToFixed: PrimordialMethod<Number, "toFixed">;
declare const $NumberPrototypeToLocaleString: PrimordialMethod<Number, "toLocaleString">;
declare const $NumberPrototypeToPrecision: PrimordialMethod<Number, "toPrecision">;
declare const $NumberPrototypeToString: PrimordialMethod<Number, "toString">;
declare const $NumberPrototypeValueOf: PrimordialMethod<Number, "valueOf">;
declare const $NumberIsFinite: PrimordialMethod<NumberConstructor, "isFinite">;
declare const $NumberIsInteger: PrimordialMethod<NumberConstructor, "isInteger">;
declare const $NumberIsNaN: PrimordialMethod<NumberConstructor, "isNaN">;
declare const $NumberIsSafeInteger: PrimordialMethod<NumberConstructor, "isSafeInteger">;
declare const $NumberParseFloat: PrimordialMethod<NumberConstructor, "parseFloat">;
declare const $NumberParseInt: PrimordialMethod<NumberConstructor, "parseInt">;
declare const $SetPrototypeAdd: PrimordialMethod<Set<any>, "add">;
declare const $SetPrototypeClear: PrimordialMethod<Set<any>, "clear">;
declare const $SetPrototypeDelete: PrimordialMethod<Set<any>, "delete">;
declare const $SetPrototypeDifference: PrimordialMethod<Set<any>, "difference">;
declare const $SetPrototypeEntries: PrimordialMethod<Set<any>, "entries">;
declare const $SetPrototypeForEach: PrimordialMethod<Set<any>, "forEach">;
declare const $SetPrototypeHas: PrimordialMethod<Set<any>, "has">;
declare const $SetPrototypeIntersection: PrimordialMethod<Set<any>, "intersection">;
declare const $SetPrototypeIsDisjointFrom: PrimordialMethod<Set<any>, "isDisjointFrom">;
declare const $SetPrototypeIsSubsetOf: PrimordialMethod<Set<any>, "isSubsetOf">;
declare const $SetPrototypeIsSupersetOf: PrimordialMethod<Set<any>, "isSupersetOf">;
declare const $SetPrototypeKeys: PrimordialMethod<Set<any>, "keys">;
declare const $SetPrototypeSymmetricDifference: PrimordialMethod<Set<any>, "symmetricDifference">;
declare const $SetPrototypeUnion: PrimordialMethod<Set<any>, "union">;
declare const $SetPrototypeValues: PrimordialMethod<Set<any>, "values">;
declare const $SetPrototypeGetSize: PrimordialGetter<Set<any>, "size">;
declare const $SetPrototypeSymbolIterator: PrimordialMethod<Set<any>, typeof Symbol.iterator>;
declare const $WeakMapPrototypeDelete: PrimordialMethod<WeakMap<any, any>, "delete">;
declare const $WeakMapPrototypeGet: PrimordialMethod<WeakMap<any, any>, "get">;
declare const $WeakMapPrototypeHas: PrimordialMethod<WeakMap<any, any>, "has">;
declare const $WeakMapPrototypeSet: PrimordialMethod<WeakMap<any, any>, "set">;
declare const $WeakSetPrototypeAdd: PrimordialMethod<WeakSet<any>, "add">;
declare const $WeakSetPrototypeDelete: PrimordialMethod<WeakSet<any>, "delete">;
declare const $WeakSetPrototypeHas: PrimordialMethod<WeakSet<any>, "has">;
declare const $ArrayBufferPrototypeSlice: PrimordialMethod<ArrayBuffer, "slice">;
declare const $ArrayBufferPrototypeResize: PrimordialMethod<ArrayBuffer, "resize">;
declare const $ArrayBufferPrototypeTransfer: PrimordialMethod<ArrayBuffer, "transfer">;
declare const $ArrayBufferPrototypeTransferToFixedLength: PrimordialMethod<ArrayBuffer, "transferToFixedLength">;
declare const $ArrayBufferPrototypeGetByteLength: PrimordialGetter<ArrayBuffer, "byteLength">;
declare const $ArrayBufferPrototypeGetDetached: PrimordialGetter<ArrayBuffer, "detached">;
declare const $ArrayBufferPrototypeGetMaxByteLength: PrimordialGetter<ArrayBuffer, "maxByteLength">;
declare const $ArrayBufferPrototypeGetResizable: PrimordialGetter<ArrayBuffer, "resizable">;
declare const $ArrayBufferIsView: PrimordialMethod<ArrayBufferConstructor, "isView">;
declare const $TypedArrayPrototypeAt: PrimordialMethod<Uint8Array, "at">;
declare const $TypedArrayPrototypeCopyWithin: PrimordialMethod<Uint8Array, "copyWithin">;
declare const $TypedArrayPrototypeEntries: PrimordialMethod<Uint8Array, "entries">;
declare const $TypedArrayPrototypeEvery: PrimordialMethod<Uint8Array, "every">;
declare const $TypedArrayPrototypeFill: PrimordialMethod<Uint8Array, "fill">;
declare const $TypedArrayPrototypeFilter: PrimordialMethod<Uint8Array, "filter">;
declare const $TypedArrayPrototypeFind: PrimordialMethod<Uint8Array, "find">;
declare const $TypedArrayPrototypeFindIndex: PrimordialMethod<Uint8Array, "findIndex">;
declare const $TypedArrayPrototypeFindLast: PrimordialMethod<Uint8Array, "findLast">;
declare const $TypedArrayPrototypeFindLastIndex: PrimordialMethod<Uint8Array, "findLastIndex">;
declare const $TypedArrayPrototypeForEach: PrimordialMethod<Uint8Array, "forEach">;
declare const $TypedArrayPrototypeIncludes: PrimordialMethod<Uint8Array, "includes">;
declare const $TypedArrayPrototypeIndexOf: PrimordialMethod<Uint8Array, "indexOf">;
declare const $TypedArrayPrototypeJoin: PrimordialMethod<Uint8Array, "join">;
declare const $TypedArrayPrototypeKeys: PrimordialMethod<Uint8Array, "keys">;
declare const $TypedArrayPrototypeLastIndexOf: PrimordialMethod<Uint8Array, "lastIndexOf">;
declare const $TypedArrayPrototypeMap: PrimordialMethod<Uint8Array, "map">;
declare const $TypedArrayPrototypeReduce: PrimordialMethod<Uint8Array, "reduce">;
declare const $TypedArrayPrototypeReduceRight: PrimordialMethod<Uint8Array, "reduceRight">;
declare const $TypedArrayPrototypeReverse: PrimordialMethod<Uint8Array, "reverse">;
declare const $TypedArrayPrototypeSet: PrimordialMethod<Uint8Array, "set">;
declare const $TypedArrayPrototypeSlice: PrimordialMethod<Uint8Array, "slice">;
declare const $TypedArrayPrototypeSome: PrimordialMethod<Uint8Array, "some">;
declare const $TypedArrayPrototypeSort: PrimordialMethod<Uint8Array, "sort">;
declare const $TypedArrayPrototypeSubarray: PrimordialMethod<Uint8Array, "subarray">;
declare const $TypedArrayPrototypeToLocaleString: PrimordialMethod<Uint8Array, "toLocaleString">;
declare const $TypedArrayPrototypeToReversed: PrimordialMethod<Uint8Array, "toReversed">;
declare const $TypedArrayPrototypeToSorted: PrimordialMethod<Uint8Array, "toSorted">;
declare const $TypedArrayPrototypeValues: PrimordialMethod<Uint8Array, "values">;
declare const $TypedArrayPrototypeWith: PrimordialMethod<Uint8Array, "with">;
declare const $TypedArrayPrototypeGetBuffer: PrimordialGetter<Uint8Array, "buffer">;
declare const $TypedArrayPrototypeGetByteLength: PrimordialGetter<Uint8Array, "byteLength">;
declare const $TypedArrayPrototypeGetByteOffset: PrimordialGetter<Uint8Array, "byteOffset">;
declare const $TypedArrayPrototypeGetLength: PrimordialGetter<Uint8Array, "length">;
declare const $TypedArrayPrototypeGetSymbolToStringTag: PrimordialGetter<Uint8Array, typeof Symbol.toStringTag>;
declare const $TypedArrayPrototypeSymbolIterator: PrimordialMethod<Uint8Array, typeof Symbol.iterator>;
declare const $TypedArrayFrom: PrimordialMethod<Uint8ArrayConstructor, "from">;
declare const $TypedArrayOf: PrimordialMethod<Uint8ArrayConstructor, "of">;
declare const $DataViewPrototypeGetBigInt64: PrimordialMethod<DataView, "getBigInt64">;
declare const $DataViewPrototypeGetBigUint64: PrimordialMethod<DataView, "getBigUint64">;
declare const $DataViewPrototypeGetFloat16: PrimordialMethod<DataView, "getFloat16">;
declare const $DataViewPrototypeGetFloat32: PrimordialMethod<DataView, "getFloat32">;
declare const $DataViewPrototypeGetFloat64: PrimordialMethod<DataView, "getFloat64">;
declare const $DataViewPrototypeGetInt16: PrimordialMethod<DataView, "getInt16">;
declare const $DataViewPrototypeGetInt32: PrimordialMethod<DataView, "getInt32">;
declare const $DataViewPrototypeGetInt8: PrimordialMethod<DataView, "getInt8">;
declare const $DataViewPrototypeGetUint16: PrimordialMethod<DataView, "getUint16">;
declare const $DataViewPrototypeGetUint32: PrimordialMethod<DataView, "getUint32">;
declare const $DataViewPrototypeGetUint8: PrimordialMethod<DataView, "getUint8">;
declare const $DataViewPrototypeSetBigInt64: PrimordialMethod<DataView, "setBigInt64">;
declare const $DataViewPrototypeSetBigUint64: PrimordialMethod<DataView, "setBigUint64">;
declare const $DataViewPrototypeSetFloat16: PrimordialMethod<DataView, "setFloat16">;
declare const $DataViewPrototypeSetFloat32: PrimordialMethod<DataView, "setFloat32">;
declare const $DataViewPrototypeSetFloat64: PrimordialMethod<DataView, "setFloat64">;
declare const $DataViewPrototypeSetInt16: PrimordialMethod<DataView, "setInt16">;
declare const $DataViewPrototypeSetInt32: PrimordialMethod<DataView, "setInt32">;
declare const $DataViewPrototypeSetInt8: PrimordialMethod<DataView, "setInt8">;
declare const $DataViewPrototypeSetUint16: PrimordialMethod<DataView, "setUint16">;
declare const $DataViewPrototypeSetUint32: PrimordialMethod<DataView, "setUint32">;
declare const $DataViewPrototypeSetUint8: PrimordialMethod<DataView, "setUint8">;
declare const $DataViewPrototypeGetBuffer: PrimordialGetter<DataView, "buffer">;
declare const $DataViewPrototypeGetByteLength: PrimordialGetter<DataView, "byteLength">;
declare const $DataViewPrototypeGetByteOffset: PrimordialGetter<DataView, "byteOffset">;
declare const $MathAbs: PrimordialMethod<Math, "abs">;
declare const $MathAcos: PrimordialMethod<Math, "acos">;
declare const $MathAcosh: PrimordialMethod<Math, "acosh">;
declare const $MathAsin: PrimordialMethod<Math, "asin">;
declare const $MathAsinh: PrimordialMethod<Math, "asinh">;
declare const $MathAtan: PrimordialMethod<Math, "atan">;
declare const $MathAtan2: PrimordialMethod<Math, "atan2">;
declare const $MathAtanh: PrimordialMethod<Math, "atanh">;
declare const $MathCbrt: PrimordialMethod<Math, "cbrt">;
declare const $MathCeil: PrimordialMethod<Math, "ceil">;
declare const $MathClz32: PrimordialMethod<Math, "clz32">;
declare const $MathCos: PrimordialMethod<Math, "cos">;
declare const $MathCosh: PrimordialMethod<Math, "cosh">;
declare const $MathExp: PrimordialMethod<Math, "exp">;
declare const $MathExpm1: PrimordialMethod<Math, "expm1">;
declare const $MathF16round: PrimordialMethod<Math, "f16round">;
declare const $MathFloor: PrimordialMethod<Math, "floor">;
declare const $MathFround: PrimordialMethod<Math, "fround">;
declare const $MathHypot: PrimordialMethod<Math, "hypot">;
declare const $MathImul: PrimordialMethod<Math, "imul">;
declare const $MathLog: PrimordialMethod<Math, "log">;
declare const $MathLog10: PrimordialMethod<Math, "log10">;
declare const $MathLog1p: PrimordialMethod<Math, "log1p">;
declare const $MathLog2: PrimordialMethod<Math, "log2">;
declare const $MathMax: PrimordialMethod<Math, "max">;
declare const $MathMin: PrimordialMethod<Math, "min">;
declare const $MathPow: PrimordialMethod<Math, "pow">;
declare const $MathRandom: PrimordialMethod<Math, "random">;
declare const $MathRound: PrimordialMethod<Math, "round">;
declare const $MathSign: PrimordialMethod<Math, "sign">;
declare const $MathSin: PrimordialMethod<Math, "sin">;
declare const $MathSinh: PrimordialMethod<Math, "sinh">;
declare const $MathSqrt: PrimordialMethod<Math, "sqrt">;
declare const $MathSumPrecise: PrimordialMethod<Math, "sumPrecise">;
declare const $MathTan: PrimordialMethod<Math, "tan">;
declare const $MathTanh: PrimordialMethod<Math, "tanh">;
declare const $MathTrunc: PrimordialMethod<Math, "trunc">;
declare const $JSONParse: PrimordialMethod<JSON, "parse">;
declare const $JSONStringify: PrimordialMethod<JSON, "stringify">;
declare const $JSONIsRawJSON: PrimordialMethod<JSON, "isRawJSON">;
declare const $JSONRawJSON: PrimordialMethod<JSON, "rawJSON">;
declare const $ReflectApply: PrimordialMethod<typeof Reflect, "apply">;
declare const $ReflectConstruct: PrimordialMethod<typeof Reflect, "construct">;
declare const $ReflectDefineProperty: PrimordialMethod<typeof Reflect, "defineProperty">;
declare const $ReflectDeleteProperty: PrimordialMethod<typeof Reflect, "deleteProperty">;
declare const $ReflectGet: PrimordialMethod<typeof Reflect, "get">;
declare const $ReflectGetOwnPropertyDescriptor: PrimordialMethod<typeof Reflect, "getOwnPropertyDescriptor">;
declare const $ReflectGetPrototypeOf: PrimordialMethod<typeof Reflect, "getPrototypeOf">;
declare const $ReflectHas: PrimordialMethod<typeof Reflect, "has">;
declare const $ReflectIsExtensible: PrimordialMethod<typeof Reflect, "isExtensible">;
declare const $ReflectOwnKeys: PrimordialMethod<typeof Reflect, "ownKeys">;
declare const $ReflectPreventExtensions: PrimordialMethod<typeof Reflect, "preventExtensions">;
declare const $ReflectSet: PrimordialMethod<typeof Reflect, "set">;
declare const $ReflectSetPrototypeOf: PrimordialMethod<typeof Reflect, "setPrototypeOf">;
declare const $AtomicsAdd: PrimordialMethod<Atomics, "add">;
declare const $AtomicsAnd: PrimordialMethod<Atomics, "and">;
declare const $AtomicsCompareExchange: PrimordialMethod<Atomics, "compareExchange">;
declare const $AtomicsExchange: PrimordialMethod<Atomics, "exchange">;
declare const $AtomicsIsLockFree: PrimordialMethod<Atomics, "isLockFree">;
declare const $AtomicsLoad: PrimordialMethod<Atomics, "load">;
declare const $AtomicsNotify: PrimordialMethod<Atomics, "notify">;
declare const $AtomicsOr: PrimordialMethod<Atomics, "or">;
declare const $AtomicsPause: PrimordialMethod<Atomics, "pause">;
declare const $AtomicsStore: PrimordialMethod<Atomics, "store">;
declare const $AtomicsSub: PrimordialMethod<Atomics, "sub">;
declare const $AtomicsWait: PrimordialMethod<Atomics, "wait">;
declare const $AtomicsWaitAsync: PrimordialMethod<Atomics, "waitAsync">;
declare const $AtomicsXor: PrimordialMethod<Atomics, "xor">;
