// The sources of the research "checks of the reference on expressions outside the type grammar" (round 2 of the parser, B4).
// Each group is [name, [source, ...]]. oracle.cjs prints the parse diagnostics of typescript-go and of tsc 6.0.2 for each, as .ts and as .js.
const C = body => `class C { #b = 1; m(a) { ${body} } }`;
const D = body => `class A extends B { m() { ${body} } }`;
const K = body => `class A extends B { constructor() { ${body} } }`;
module.exports = [
  ["TS1477 instantiation expression before a property access", [
    "a<b>.c;",
    "a<b>?.c;",
    "a<b>?.[c];",
    "a<b>?.();",
    "a<b>?.`x`;",
    "a<b>.c<d>.e;",
    "a<b>.c<d>(e);",
    "new A<T>.b();",
    "new A<T>.b;",
    "a<b, c>.d;",
    "a<b> .c;",
    "a<b>\n.c;",
    "a< b /*x*/ > /*y*/ .c;",
    "a<b>.;",
    "a<b>.#c;",
    C("a<b>.#b;"),
    C("a<b>?.#b;"),
    "a<b>['c'];",
    "a.b<c>.d;",
    "f()<b>.c;",
    "a<b>!.c;",
    "(a<b>).c;",
    "a?.b<c>.d;",
    "a<b>.c = 1;",
    "a<<T>(x: T) => void>.c;",
    "a<b>>.c;",
    "a<b<c>>.d;",
    "a<b<c<d>>>.e;",
    "x = a<b>.c;",
    "f(a<b>.c);",
    "a<b>.c.d;",
    "a<>.c;",
    "a<b,>.c;",
    "this<T>.x;",
    "a<b>.c<d>;",
    "a!<b>.c;",
    "a<b>\n.c\n.d;",
    "a<b>?.c<d>.e;",
    "import.meta<T>.x;",
    "a<b>.c`x`;",
    "a`x`<b>.c;",
    "a<b>`x`.c;",
    "a<b>(c).d;",
    "a<b>.then<c>(d);",
  ]],
  ["TS17007 and TS17006 operand of **", [
    "<A>x ** 2;",
    "<A>(x) ** 2;",
    "<A>x.y ** 2;",
    "<A>x++ ** 2;",
    "<A> x ** 2;",
    " <A>x ** 2;",
    "/*c*/ <A>x ** 2;",
    "<A>x /*c*/ ** 2;",
    "<A>(x) => x ** 2;",
    "<A><B>x ** 2;",
    "<A>-x ** 2;",
    "-<A>x ** 2;",
    "- <A>x ** 2;",
    "y = <A>x ** 2;",
    "f(<A>x ** 2);",
    "2 ** <A>x ** 2;",
    "(<A>x) ** 2;",
    "<A>(x ** 2);",
    "<A>x **= 2;",
    "<A>x\n** 2;",
    "<A>new X ** 2;",
    "<A>x! ** 2;",
    "<A>x as B ** 2;",
    "<A>await x ** 2;",
    "-x ** 2;",
    "+x ** 2;",
    "~x ** 2;",
    "!x ** 2;",
    "typeof x ** 2;",
    "void x ** 2;",
    "delete x ** 2;",
    "delete x.y ** 2;",
    "async function f() { await x ** 2; }",
    "async function f() { y = await x ** 2; }",
    "async function f() { await -x ** 2; }",
    "async function f() { -await x ** 2; }",
    "async function f() { (await x) ** 2; }",
    "await x ** 2;",
    "y = await x ** 2;",
    "await x ** 2; export {};",
    "await ** 2;",
    "y = await ** 2;",
    "function f() { await ** 2; }",
    "function f() { return await ** 2; }",
    "- -x ** 2;",
    "-+x ** 2;",
    "!-x ** 2;",
    "typeof -x ** 2;",
    "void typeof x ** 2;",
    "- - -x ** 2;",
    "a - -x ** 2;",
    "a-x ** 2;",
    "a > -x ** 2;",
    "(-x) ** 2;",
    "-(x ** 2);",
    "-x.y ** 2;",
    "-x() ** 2;",
    "-x++ ** 2;",
    "-++x ** 2;",
    "++x ** 2;",
    "x++ ** 2;",
    "-x /*c*/ ** 2;",
    "/*c*/ -x ** 2;",
    "- /*c*/ x ** 2;",
    "-x\n** 2;",
    "2 ** -x ** 2;",
    "2 ** -x;",
    "x = -y ** 2;",
    "f(-x ** 2);",
    "[-x ** 2];",
    "-x **= 2;",
    "-1 ** 2;",
    "- new A ** 2;",
    "- new A() ** 2;",
    "-x ** 2 ** 3;",
    "-x ** -y ** 2;",
    "-x!.y ** 2;",
    "-x as any ** 2;",
    "-(x as any) ** 2;",
    "-x[0] ** 2;",
    "-`a` ** 2;",
    "-x`a` ** 2;",
    "-x?.y ** 2;",
    "-(x) ** 2;",
    "- (x) /*c*/ ** 2;",
    "function* g() { -(yield) ** 2; }",
    "for (const k in -x ** 2) {}",
    "x ? -y ** 2 : z;",
    "-x ** 2 ? y : z;",
    "class A { m() { -super.x ** 2; } }",
    "typeof import('a') ** 2;",
    "-function(){} ** 2;",
    "-class{} ** 2;",
    "-{} ** 2;",
    "-[] ** 2;",
    "-/a/ ** 2;",
    "-a.b.c(d)[e] ** 2;",
  ]],
  ["TS1209 optional chain from new", [
    "new A?.b();",
    "new A?.b;",
    "new A.B?.c();",
    "new A<T>?.b();",
    "new (A)?.b();",
    "new A()?.b;",
    "new A()?.b();",
    "new A?.();",
    "new A?.<T>();",
    "new A?.[0];",
    "new A?.[0]();",
    "new A?.b.c();",
    "new A?.b?.c();",
    "new new A?.b()();",
    "new A!?.b();",
    "new A ?.b();",
    "new A /*c*/ ?.b();",
    "new A\n?.b();",
    "new a.b.c?.d();",
    "new A`x`?.b();",
    "new (A?.b)();",
    "new (A?.b);",
    "new this?.b();",
    "new import.meta?.x();",
    "new class {}?.b();",
    "new function () {}?.b();",
    "new A['x']?.b();",
    "new A?.b<T>();",
    "new A?.`x`;",
    "new A?.b`x`;",
    C("new a?.#b();"),
    C("new a.#b?.c();"),
    "x = new A?.b();",
    "f(new A?.b());",
    "new  A . B ?.c();",
    "new A?.b = 1;",
    "new A?.b++;",
    "new (new A)?.b();",
    "new new A?.b();",
    "new A<T>?.();",
    "new A?.3:1;",
    "new A ?.5 : 1;",
    "new a.b<c>.d?.e();",
    "new A().b?.c();",
    "(new A)?.b();",
    "new.target?.b();",
    "function f() { new.target?.b(); }",
    "new (A)!?.b();",
    "new <T>A?.b();",
    "new (a, b)?.c();",
    "new A.b?.[c]?.d();",
    "new 'a'?.b();",
    "new 1?.b();",
    "new []?.b();",
    "new {}?.b();",
    "new /a/?.b();",
    "new `a`?.b();",
    "new async?.b();",
    "new super.x?.y();",
    "class X extends Y { m() { new super.x?.y(); } }",
  ]],
  ["TS18030 private identifier in an optional chain", [
    "a?.#b;",
    "this?.#a;",
    C("a?.#b;"),
    C("a?.x.#b;"),
    C("a?.x!.#b;"),
    C("a?.[0].#b;"),
    C("a?.().#b;"),
    C("a.#b;"),
    C("a.#b?.c;"),
    C("(a?.x).#b;"),
    C("a?.#b = 1;"),
    C("a ?. #b;"),
    C("a ?. /*c*/ #b;"),
    C("a?.\n#b;"),
    C("return #b in a?.x;"),
    C("a?.#b();"),
    C("a?.x.y.#b;"),
    C("a?.x.y.#b.z;"),
    C("a?.#b.#b;"),
    C("a?.#b?.#b;"),
    C("a.x?.#b;"),
    C("a?.x!!.#b;"),
    C("a?.x.y().z[0].#b;"),
    C("(a?.x)!.#b;"),
    C("a!?.#b;"),
    C("this?.#b;"),
    C("delete a?.#b;"),
    C("a?.#b`x`;"),
    C("a?.#b++;"),
    C("x = a?.#b ?? 1;"),
    C("new a.#b();"),
    C("a?.#c;"),
    "a?.x.#b;",
    "a.#b;",
    C("a?.<T>().#b;"),
    C("a<T>?.#b;"),
    C("(a?.x as any).#b;"),
    C("a?.x as any;"),
  ]],
  ["TS2754 and TS1034 super", [
    K("super<T>();"),
    K("super <T>();"),
    K("super /*c*/ <T> /*d*/ ();"),
    K("super<T, U>();"),
    K("super<>();"),
    K("super<T,>();"),
    K("super<T>(1).x;"),
    K("super();"),
    D("super<T>.x;"),
    D("super<T>.x();"),
    D("super<T>[0];"),
    D("super;"),
    D("super<T>;"),
    D("super\n<T>();"),
    D("super + 1;"),
    D("super`x`;"),
    D("super<T>`x`;"),
    D("return super"),
    D("return super;"),
    D("super?.x;"),
    D("super?.();"),
    D("super<T"),
    D("super<T;"),
    D("super<T>x;"),
    D("super<T>1;"),
    D("super!.x;"),
    D("super.x;"),
    D("super[0];"),
    D("super.x<T>();"),
    D("x = super;"),
    D("f(super);"),
    D("super = 1;"),
    D("super++;"),
    D("new super;"),
    D("new super();"),
    D("new super.x();"),
    D("new super<T>();"),
    D("super.#x;"),
    D("(super);"),
    D("super as any;"),
    D("super\n.x;"),
    D("super < T > (x);"),
    D("super<T>>();"),
    D("super<A<B>>();"),
    D("super<<T>() => void>();"),
    D("typeof super;"),
    D("super in x;"),
    D("super instanceof A;"),
    D("[super];"),
    D("`${super}`;"),
    D("super => 1;"),
    D("super ? 1 : 2;"),
    D("super, 1;"),
    D("delete super.x;"),
    D("super /*c*/ ;"),
    "super;",
    "super();",
    "super.x;",
    "super<T>();",
    "super<T>.x;",
    "x = super;",
    "class A { m() { super(); } }",
    "class A { constructor() { super(); } }",
    "class A extends B { m() { super(); } }",
    "class A extends B { static { super(); } }",
    "class A extends B { x = super(); }",
    "class A extends B { x = super.y; }",
    "class A extends B { [super.x]() {} }",
    "function f() { super.x; }",
    "function f() { super(); }",
    "({ m() { super.x; } });",
    "({ m() { super(); } });",
    "({ m: function () { super.x; } });",
    "class A extends B { constructor() { (() => super())(); } }",
    "class A extends B { constructor() { function g() { super(); } } }",
    "class A extends B { constructor() { new super(); } }",
    "class A extends B { constructor() { super()(); } }",
    "class A extends B { constructor() { super() ** 2; } }",
    "class A extends B { constructor() { -super(); } }",
    "class A extends B { constructor() { x = super(); } }",
    "class A extends B { constructor() { super().x; } }",
    "class A extends B { constructor() { super<T>().x; } }",
    "class A extends B { constructor() { f(super()); } }",
  ]],
  ["TS1011 element access without an argument", [
    "a[];",
    "a[ ];",
    "a[\n];",
    "a[/*c*/];",
    "a[ /*c*/ ];",
    "a[ // c\n];",
    "a?.[];",
    "a?.[ ];",
    "a[][0];",
    "a[b[]];",
    "a[{ []: 1 }];",
    "({ []: 1 });",
    "({ [ ]: 1 });",
    "class C { []() {} }",
    "class C { static [] = 1 }",
    "class C { a = b\n[] }",
    "a[] = 1;",
    "new A[];",
    "new A[]();",
    "x = a[];",
    "a.b[];",
    "a()[];",
    "a![];",
    "let x: A[] = a[];",
    "a[,];",
    "a[",
    "a[;",
    "a[)",
    "a[}",
    "for (const x of y[]) {}",
    "a[].b;",
    "a[]();",
    "a[]++;",
    "a[]\n[];",
    "a[][];",
    "f(a[]);",
    "[a[]];",
    "`${a[]}`;",
    "a[]`x`;",
    "a[] as any;",
    "(a[]);",
    "a[(]",
    "a[[]];",
    "a[[]][];",
    "let [] = a[];",
    "type T = { []: number };",
    "type T = A[ ];",
    "let x: { [ ]: 1 };",
    "enum E { [] }",
    "@a[] class C {}",
    "class C { @a[] m() {} }",
    "a?.b[];",
    "super[];",
    "class A extends B { m() { super[]; } }",
    "this[];",
    "import.meta[];",
    "a<b>[];",
    "a[]<b>;",
    "async[];",
    "await[];",
    "yield[];",
    "function* g() { yield[]; }",
    "function* g() { (yield)[]; }",
    "of[];",
  ]],
  ["for head with using and of", [
    "for (using of of []) {}",
    "for (using of of [1]) {}",
    "for (using of of) {}",
    "for (using of of x) {}",
    "for (using of [1]) {}",
    "for (using of []) {}",
    "for (using of x) {}",
    "for (using x of y) {}",
    "for (using of = null;;) {}",
    "for (using of = null; false;) {}",
    "for (using of;;) {}",
    "for (using of: T = null;;) {}",
    "for (using of in x) {}",
    "for (using of of of) {}",
    "for (using of\nof []) {}",
    "for (using\nof of []) {}",
    "for (using of /*c*/ of []) {}",
    "for (using of of\n[]) {}",
    "for (using of of [ ]) {}",
    "for (using in x) {}",
    "for (using;;) {}",
    "for (using = 1;;) {}",
    "for (using.x of y) {}",
    "for (using[0] of y) {}",
    "for (using x = y;;) {}",
    "for (using x = y, z = w;;) {}",
    "for (using {} of y) {}",
    "for (using [a] of y) {}",
    "for (using of of.x) {}",
    "for (using of of()) {}",
    "for (using of of?.[0]) {}",
    "for (using of of => of) {}",
    "for (using of, x;;) {}",
    "for (using of = 1 of []) {}",
    "for (using of) {}",
    "for (using x) {}",
    "for (using x in y) {}",
    "for (using of as any of []) {}",
    "for (using of! of []) {}",
    "async function f() { for (await using of of []) {} }",
    "async function f() { for (await using of of x) {} }",
    "async function f() { for (await using x of y) {} }",
    "async function f() { for await (using of of []) {} }",
    "async function f() { for await (using of of x) {} }",
    "async function f() { for await (using x of y) {} }",
    "async function f() { for (await using of = null;;) {} }",
    "for (await using of of []) {}",
    "for await (using of of []) {}",
    "using of = null;",
    "using of of [];",
    "using x = null;",
    "{ using of = null; }",
    "{ using of of []; }",
    "for (let of of []) {}",
    "for (let of of x) {}",
    "for (const of of []) {}",
    "for (var of of []) {}",
    "for (of of []) {}",
    "for (of of of) {}",
    "for (async of []) {}",
    "for (let of []) {}",
    "for (let.x of []) {}",
  ]],
];
