(a) + b;
(a + b);
((a) + b) * c;
(a, b);
f((a), b);
(a?.b).c;
a?.b.c(d)?.[e];
a?.(x);
x = (y) => y;
x = ((y) => y);
x = async (y) => y;
x = async y => y;
x = y => { return y; };
new Foo;
new Foo(1, ...r);
new.target;
import.meta;
import("m");
[1, , ...s, ];
({ a, b: c, [d]: e, ...f, g() {}, get h() { return 1; }, set h(v) {}, async *i() {}, "s": 1, 2: 3 });
`a${b}c${d}e`;
tag`x${y}z`;
tag`plain`;
`plain`;
a ? b : c;
a++, --b;
typeof a, void 0, delete a.b, !a, ~a, -a, +a;
a ??= b || c && d;
/re/g.test(s);
x = function* named(p = 1, {q}, [r], ...rest) {};
x = class Named extends Base { static s = 1; #p; m() {} static { f(); } ; constructor() { super(); } get [k]() { return 1; } };
await 1;
this.x;
