// Generates unicode_tables.rs.
//
//   bun src/lint/regex/generate_unicode_tables.ts <regexpp>/src/unicode/properties.ts
//
// The names of the properties, and the ECMAScript version that added each, come from regexpp.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const source = readFileSync(process.argv[2], "utf8");

/** The strings given to `new DataSet(..)` for `name`: one per version, from ES2018. */
function dataSet(name: string): string[][] {
  const start = source.indexOf(`const ${name} = new DataSet(`);
  if (start < 0) throw new Error(`no ${name}`);
  const end = source.indexOf("\n)", start);
  return [...source.slice(start, end).matchAll(/"([^"]*)"/g)].map(m => m[1].split(" ").filter(Boolean));
}

function named(name: string): { name: string; version: number }[] {
  return dataSet(name)
    .flatMap((names, i) => names.map(name => ({ name, version: i })))
    .sort((a, b) => (a.name < b.name ? -1 : 1));
}

const out: string[] = ["//! Generated by generate_unicode_tables.ts. Do not edit.", ""];

function emit(doc: string, name: string, type: string, values: number[]) {
  out.push(...doc.split("\n").map(line => `/// ${line}`), "#[rustfmt::skip]");
  out.push(`pub(super) static ${name}: &[${type}] = &[`);
  let line = "   ";
  for (const value of values) {
    const text = ` ${value},`;
    if (line.length + text.length > 110) {
      out.push(line);
      line = "   ";
    }
    line += text;
  }
  if (line.trim()) out.push(line);
  out.push("];", "");
}

function emitNames(doc: string, name: string, names: string[]) {
  out.push(...doc.split("\n").map(line => `/// ${line}`));
  out.push(`pub(super) static ${name}: &[u8] = b"\\`);
  let line = "";
  names.forEach((text, i) => {
    text += i + 1 < names.length ? " " : "";
    if (line.length + text.length > 100) {
      out.push(`${line}\\`);
      line = "";
    }
    line += text;
  });
  out.push(`${line}";`, "");
}

emitNames(
  "The values of General_Category, sorted.",
  "GENERAL_CATEGORY_NAMES",
  named("gcValueSets").map(n => n.name),
);

const scripts = named("scValueSets");
emitNames(
  "The values of Script and Script_Extensions, sorted.",
  "SCRIPT_NAMES",
  scripts.map(n => n.name),
);
emit(
  "For each name in `SCRIPT_NAMES`, the version that has it. Versions count from ES2018.",
  "SCRIPT_VERSIONS",
  "u8",
  scripts.map(n => n.version),
);

const binary = named("binPropertySets");
emitNames(
  "The binary properties, sorted.",
  "BINARY_NAMES",
  binary.map(n => n.name),
);
emit(
  "For each name in `BINARY_NAMES`, the version that has it, as in `SCRIPT_VERSIONS`.",
  "BINARY_VERSIONS",
  "u8",
  binary.map(n => n.version),
);

emitNames(
  "The binary properties of strings, sorted.",
  "STRING_PROPERTY_NAMES",
  named("binPropertyOfStringsSets").map(n => n.name),
);

writeFileSync(process.argv[3] ?? join(import.meta.dir, "unicode_tables.rs"), out.join("\n"));
