//! Rules of plugins that many projects use with ESLint and oxlint. Each is a port of the rule of the same name, with the same
//! options, the same messages, at the same places:
//! - `react-hooks`: https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks (Copyright Meta Platforms,
//!   Inc. and affiliates, MIT License)
//! - `import`: https://github.com/import-js/eslint-plugin-import (Copyright Ben Mosher, MIT License)
//! - `n`: https://github.com/eslint-community/eslint-plugin-n (Copyright Toru Nagashima, MIT License)
//! - `oxc`: https://github.com/oxc-project/oxc (Copyright VoidZero Inc. and contributors, MIT License)
//! - `prettier`: https://github.com/prettier/eslint-plugin-prettier and
//!   https://github.com/prettier/prettier-linter-helpers (Copyright Andres Suarez and Teddy Katz, MIT License)
//!
//! And the rules of `bun`, which are Bun's own.

#![forbid(unsafe_code)]

mod bun;
mod import_doctrine;
mod import_export_record;
mod import_minimatch;
mod import_package_path;
mod import_resolve;
mod import_settings;
mod import_type;
mod module_visitor;
mod n;
mod oxlint;
mod prettier;
mod regexp_ast_utils;
mod regexp_char_set;
mod regexp_raa_basic;
mod regexp_replacements;
mod regexp_syntax;
mod regexp_type_builtins;

bun_lint::rules! {
    bun_consistent_directive_prefix::ConsistentDirectivePrefix,
    bun_jsx_no_forbidden_nesting::JsxNoForbiddenNesting,
    bun_no_array_just_to_count::NoArrayJustToCount,
    bun_no_cast_to_brand::NoCastToBrand,
    bun_no_console_window_flash::NoConsoleWindowFlash,
    bun_no_cwd_dependent_path::NoCwdDependentPath,
    bun_no_eager_dynamic_import::NoEagerDynamicImport,
    bun_no_eager_native_addon::NoEagerNativeAddon,
    bun_no_env_at_module_scope::NoEnvAtModuleScope,
    bun_no_literal_temp_dir::NoLiteralTempDir,
    bun_no_negative_repeat_count::NoNegativeRepeatCount,
    bun_no_redundant_catch_type::NoRedundantCatchType,
    bun_no_restricted_text::NoRestrictedText,
    bun_no_side_effects_on_import::NoSideEffectsOnImport,
    bun_no_unbounded_requests::NoUnboundedRequests,
    bun_no_unhandled_emitter_errors::NoUnhandledEmitterErrors,
    bun_no_unportable_commands::NoUnportableCommands,
    bun_no_unseeded_random_in_property_test::NoUnseededRandomInPropertyTest,
    bun_no_useless_spread_fallback::NoUselessSpreadFallback,
    bun_prefer_builtin_sleep::PreferBuiltinSleep,
    bun_prefer_lazy_schema::PreferLazySchema,
    bun_prefer_local_module::PreferLocalModule,
    bun_prefer_timeout_signal::PreferTimeoutSignal,
    bun_prefer_url_for_sibling_files::PreferUrlForSiblingFiles,
    bun_react_no_latest_value_ref::ReactNoLatestValueRef,
    bun_react_no_local_render_helpers::ReactNoLocalRenderHelpers,
    bun_react_no_namespace_hooks::ReactNoNamespaceHooks,
    bun_react_prefer_updater_function::ReactPreferUpdaterFunction,
    import_consistent_type_specifier_style::ConsistentTypeSpecifierStyle,
    import_default::Default,
    import_export::Export,
    import_exports_last::ExportsLast,
    import_extensions::Extensions,
    import_first::First,
    import_group_exports::GroupExports,
    import_max_dependencies::MaxDependencies,
    import_named::Named,
    import_namespace::Namespace,
    import_newline_after_import::NewlineAfterImport,
    import_no_absolute_path::NoAbsolutePath,
    import_no_amd::NoAmd,
    import_no_anonymous_default_export::NoAnonymousDefaultExport,
    import_no_commonjs::NoCommonjs,
    import_no_cycle::NoCycle,
    import_no_default_export::NoDefaultExport,
    import_no_duplicates::NoDuplicates,
    import_no_dynamic_require::NoDynamicRequire,
    import_no_empty_named_blocks::NoEmptyNamedBlocks,
    import_no_mutable_exports::NoMutableExports,
    import_no_named_as_default::NoNamedAsDefault,
    import_no_named_as_default_member::NoNamedAsDefaultMember,
    import_no_named_default::NoNamedDefault,
    import_no_named_export::NoNamedExport,
    import_no_namespace::NoNamespace,
    import_no_nodejs_modules::NoNodejsModules,
    import_no_relative_parent_imports::NoRelativeParentImports,
    import_no_restricted_paths::NoRestrictedPaths,
    import_no_self_import::NoSelfImport,
    import_no_unassigned_import::NoUnassignedImport,
    import_no_webpack_loader_syntax::NoWebpackLoaderSyntax,
    import_order::Order,
    import_prefer_default_export::PreferDefaultExport,
    import_unambiguous::Unambiguous,
    jsdoc_check_access::CheckAccess,
    jsdoc_check_property_names::CheckPropertyNames,
    jsdoc_check_tag_names::CheckTagNames,
    jsdoc_empty_tags::EmptyTags,
    jsdoc_implements_on_classes::ImplementsOnClasses,
    jsdoc_no_blank_blocks::NoBlankBlocks,
    jsdoc_no_defaults::NoDefaults,
    jsdoc_require_param::RequireParam,
    jsdoc_require_param_description::RequireParamDescription,
    jsdoc_require_param_name::RequireParamName,
    jsdoc_require_param_type::RequireParamType,
    jsdoc_require_property::RequireProperty,
    jsdoc_require_property_description::RequirePropertyDescription,
    jsdoc_require_property_name::RequirePropertyName,
    jsdoc_require_property_type::RequirePropertyType,
    jsdoc_require_returns::RequireReturns,
    jsdoc_require_returns_description::RequireReturnsDescription,
    jsdoc_require_returns_type::RequireReturnsType,
    jsdoc_require_throws_description::RequireThrowsDescription,
    jsdoc_require_throws_type::RequireThrowsType,
    jsdoc_require_yields::RequireYields,
    jsdoc_require_yields_description::RequireYieldsDescription,
    jsdoc_require_yields_type::RequireYieldsType,
    n_no_process_exit::NoProcessExit,
    n_no_unsupported_features_es_builtins::EsBuiltins,
    n_no_unsupported_features_es_syntax::EsSyntax,
    n_no_unsupported_features_node_builtins::NodeBuiltins,
    node_callback_return::CallbackReturn,
    node_exports_style::ExportsStyle,
    node_global_require::GlobalRequire,
    node_handle_callback_err::HandleCallbackErr,
    node_no_exports_assign::NoExportsAssign,
    node_no_mixed_requires::NoMixedRequires,
    node_no_new_require::NoNewRequire,
    node_no_path_concat::NoPathConcat,
    node_no_process_env::NoProcessEnv,
    node_no_sync::NoSync,
    node_no_top_level_await::NoTopLevelAwait,
    oxc_approx_constant::ApproxConstant,
    oxc_bad_array_method_on_arguments::BadArrayMethodOnArguments,
    oxc_bad_bitwise_operator::BadBitwiseOperator,
    oxc_bad_char_at_comparison::BadCharAtComparison,
    oxc_bad_comparison_sequence::BadComparisonSequence,
    oxc_bad_match_all_arg::BadMatchAllArg,
    oxc_bad_min_max_func::BadMinMaxFunc,
    oxc_bad_object_literal_comparison::BadObjectLiteralComparison,
    oxc_bad_replace_all_arg::BadReplaceAllArg,
    oxc_branches_sharing_code::BranchesSharingCode,
    oxc_const_comparisons::ConstComparisons,
    oxc_double_comparisons::DoubleComparisons,
    oxc_erasing_op::ErasingOp,
    oxc_misrefactored_assign_op::MisrefactoredAssignOp,
    oxc_missing_throw::MissingThrow,
    oxc_no_accumulating_spread::NoAccumulatingSpread,
    oxc_no_async_await::NoAsyncAwait,
    oxc_no_async_endpoint_handlers::NoAsyncEndpointHandlers,
    oxc_no_barrel_file::NoBarrelFile,
    oxc_no_const_enum::NoConstEnum,
    oxc_no_map_spread::NoMapSpread,
    oxc_no_optional_chaining::NoOptionalChaining,
    oxc_no_rest_spread_properties::NoRestSpreadProperties,
    oxc_no_this_in_exported_function::NoThisInExportedFunction,
    oxc_number_arg_out_of_range::NumberArgOutOfRange,
    oxc_only_used_in_recursion::OnlyUsedInRecursion,
    oxc_uninvoked_array_callback::UninvokedArrayCallback,
    prettier_prettier::Prettier,
    promise_always_return::AlwaysReturn,
    promise_avoid_new::AvoidNew,
    promise_catch_or_return::CatchOrReturn,
    promise_no_callback_in_promise::NoCallbackInPromise,
    promise_no_multiple_resolved::NoMultipleResolved,
    promise_no_nesting::NoNesting,
    promise_no_new_statics::NoNewStatics,
    promise_no_promise_in_callback::NoPromiseInCallback,
    promise_no_return_in_finally::NoReturnInFinally,
    promise_no_return_wrap::NoReturnWrap,
    promise_param_names::ParamNames,
    promise_prefer_await_to_callbacks::PreferAwaitToCallbacks,
    promise_prefer_await_to_then::PreferAwaitToThen,
    promise_prefer_catch::PreferCatch,
    promise_spec_only::SpecOnly,
    promise_valid_params::ValidParams,
    react_hooks_exhaustive_deps::ExhaustiveDeps,
    react_hooks_rules_of_hooks::RulesOfHooks,
    typescript_ban_types::BanTypes,
    vue_component_definition_name_casing::ComponentDefinitionNameCasing,
    vue_define_emits_declaration::DefineEmitsDeclaration,
    vue_define_props_declaration::DefinePropsDeclaration,
    vue_define_props_destructuring::DefinePropsDestructuring,
    vue_max_props::MaxProps,
    vue_next_tick_style::NextTickStyle,
    vue_no_arrow_functions_in_watch::NoArrowFunctionsInWatch,
    vue_no_async_in_computed_properties::NoAsyncInComputedProperties,
    vue_no_computed_properties_in_data::NoComputedPropertiesInData,
    vue_no_deprecated_data_object_declaration::NoDeprecatedDataObjectDeclaration,
    vue_no_deprecated_delete_set::NoDeprecatedDeleteSet,
    vue_no_deprecated_destroyed_lifecycle::NoDeprecatedDestroyedLifecycle,
    vue_no_deprecated_events_api::NoDeprecatedEventsApi,
    vue_no_deprecated_model_definition::NoDeprecatedModelDefinition,
    vue_no_deprecated_props_default_this::NoDeprecatedPropsDefaultThis,
    vue_no_deprecated_vue_config_keycodes::NoDeprecatedVueConfigKeycodes,
    vue_no_dupe_keys::NoDupeKeys,
    vue_no_export_in_script_setup::NoExportInScriptSetup,
    vue_no_expose_after_await::NoExposeAfterAwait,
    vue_no_import_compiler_macros::NoImportCompilerMacros,
    vue_no_lifecycle_after_await::NoLifecycleAfterAwait,
    vue_no_multiple_slot_args::NoMultipleSlotArgs,
    vue_no_required_prop_with_default::NoRequiredPropWithDefault,
    vue_no_reserved_component_names::NoReservedComponentNames,
    vue_no_reserved_keys::NoReservedKeys,
    vue_no_reserved_props::NoReservedProps,
    vue_no_shared_component_data::NoSharedComponentData,
    vue_no_side_effects_in_computed_properties::NoSideEffectsInComputedProperties,
    vue_no_this_in_before_route_enter::NoThisInBeforeRouteEnter,
    vue_no_watch_after_await::NoWatchAfterAwait,
    vue_prefer_import_from_vue::PreferImportFromVue,
    vue_prop_name_casing::PropNameCasing,
    vue_require_default_export::RequireDefaultExport,
    vue_require_default_prop::RequireDefaultProp,
    vue_require_direct_export::RequireDirectExport,
    vue_require_prop_type_constructor::RequirePropTypeConstructor,
    vue_require_prop_types::RequirePropTypes,
    vue_require_render_return::RequireRenderReturn,
    vue_require_slots_as_functions::RequireSlotsAsFunctions,
    vue_require_typed_ref::RequireTypedRef,
    vue_return_in_computed_property::ReturnInComputedProperty,
    vue_return_in_emits_validator::ReturnInEmitsValidator,
    vue_valid_define_emits::ValidDefineEmits,
    vue_valid_define_options::ValidDefineOptions,
    vue_valid_define_props::ValidDefineProps,
    vue_valid_next_tick::ValidNextTick,
}
