//! The rules of `jest` and `vitest` as oxlint has them: each is a port of the rule of the same name of oxlint 1.80, with the same
//! options, the same messages, at the same places. They exist only with a configuration of oxlint.
//! - https://github.com/oxc-project/oxc (Copyright VoidZero Inc. and contributors, MIT License)
//! - which are ports of https://github.com/jest-community/eslint-plugin-jest (Copyright Jonathan Kim, MIT License) and
//!   https://github.com/vitest-dev/eslint-plugin-vitest (Copyright Verite Mugabo, MIT License)

#![forbid(unsafe_code)]

mod jest;
mod jest_expect;
mod jest_hooks;
mod jest_matchers;
mod jest_mocks;
mod jest_tests;

bun_lint::rules! {
    jest_consistent_test_it::ConsistentTestIt,
    jest_expect_expect::ExpectExpect,
    jest_max_expects::MaxExpects,
    jest_max_nested_describe::MaxNestedDescribe,
    jest_no_alias_methods::NoAliasMethods,
    jest_no_commented_out_tests::NoCommentedOutTests,
    jest_no_conditional_expect::NoConditionalExpect,
    jest_no_conditional_in_test::NoConditionalInTest,
    jest_no_confusing_set_timeout::NoConfusingSetTimeout,
    jest_no_deprecated_functions::NoDeprecatedFunctions,
    jest_no_disabled_tests::NoDisabledTests,
    jest_no_done_callback::NoDoneCallback,
    jest_no_duplicate_hooks::NoDuplicateHooks,
    jest_no_export::NoExport,
    jest_no_focused_tests::NoFocusedTests,
    jest_no_hooks::NoHooks,
    jest_no_identical_title::NoIdenticalTitle,
    jest_no_interpolation_in_snapshots::NoInterpolationInSnapshots,
    jest_no_jasmine_globals::NoJasmineGlobals,
    jest_no_large_snapshots::NoLargeSnapshots,
    jest_no_mocks_import::NoMocksImport,
    jest_no_restricted_jest_methods::NoRestrictedJestMethods,
    jest_no_restricted_matchers::NoRestrictedMatchers,
    jest_no_standalone_expect::NoStandaloneExpect,
    jest_no_test_prefixes::NoTestPrefixes,
    jest_no_test_return_statement::NoTestReturnStatement,
    jest_no_unneeded_async_expect_function::NoUnneededAsyncExpectFunction,
    jest_no_untyped_mock_factory::NoUntypedMockFactory,
    jest_padding_around_after_all_blocks::PaddingAroundAfterAllBlocks,
    jest_padding_around_test_blocks::PaddingAroundTestBlocks,
    jest_prefer_called_with::PreferCalledWith,
    jest_prefer_comparison_matcher::PreferComparisonMatcher,
    jest_prefer_each::PreferEach,
    jest_prefer_ending_with_an_expect::PreferEndingWithAnExpect,
    jest_prefer_equality_matcher::PreferEqualityMatcher,
    jest_prefer_expect_assertions::PreferExpectAssertions,
    jest_prefer_expect_resolves::PreferExpectResolves,
    jest_prefer_hooks_in_order::PreferHooksInOrder,
    jest_prefer_hooks_on_top::PreferHooksOnTop,
    jest_prefer_importing_jest_globals::PreferImportingJestGlobals,
    jest_prefer_jest_mocked::PreferJestMocked,
    jest_prefer_lowercase_title::PreferLowercaseTitle,
    jest_prefer_mock_promise_shorthand::PreferMockPromiseShorthand,
    jest_prefer_mock_return_shorthand::PreferMockReturnShorthand,
    jest_prefer_snapshot_hint::PreferSnapshotHint,
    jest_prefer_spy_on::PreferSpyOn,
    jest_prefer_strict_equal::PreferStrictEqual,
    jest_prefer_to_be::PreferToBe,
    jest_prefer_to_contain::PreferToContain,
    jest_prefer_to_have_been_called::PreferToHaveBeenCalled,
    jest_prefer_to_have_been_called_times::PreferToHaveBeenCalledTimes,
    jest_prefer_to_have_length::PreferToHaveLength,
    jest_prefer_todo::PreferTodo,
    jest_require_hook::RequireHook,
    jest_require_to_throw_message::RequireToThrowMessage,
    jest_require_top_level_describe::RequireTopLevelDescribe,
    jest_valid_describe_callback::ValidDescribeCallback,
    jest_valid_expect::ValidExpect,
    jest_valid_expect_in_promise::ValidExpectInPromise,
    jest_valid_title::ValidTitle,
    vitest_consistent_each_for::ConsistentEachFor,
    vitest_consistent_test_filename::ConsistentTestFilename,
    vitest_consistent_test_it::ConsistentTestIt,
    vitest_consistent_vitest_vi::ConsistentVitestVi,
    vitest_expect_expect::ExpectExpect,
    vitest_hoisted_apis_on_top::HoistedApisOnTop,
    vitest_max_expects::MaxExpects,
    vitest_max_nested_describe::MaxNestedDescribe,
    vitest_no_alias_methods::NoAliasMethods,
    vitest_no_commented_out_tests::NoCommentedOutTests,
    vitest_no_conditional_expect::NoConditionalExpect,
    vitest_no_conditional_in_test::NoConditionalInTest,
    vitest_no_conditional_tests::NoConditionalTests,
    vitest_no_disabled_tests::NoDisabledTests,
    vitest_no_duplicate_hooks::NoDuplicateHooks,
    vitest_no_focused_tests::NoFocusedTests,
    vitest_no_hooks::NoHooks,
    vitest_no_identical_title::NoIdenticalTitle,
    vitest_no_import_node_test::NoImportNodeTest,
    vitest_no_importing_vitest_globals::NoImportingVitestGlobals,
    vitest_no_interpolation_in_snapshots::NoInterpolationInSnapshots,
    vitest_no_large_snapshots::NoLargeSnapshots,
    vitest_no_mocks_import::NoMocksImport,
    vitest_no_restricted_matchers::NoRestrictedMatchers,
    vitest_no_restricted_vi_methods::NoRestrictedViMethods,
    vitest_no_standalone_expect::NoStandaloneExpect,
    vitest_no_test_prefixes::NoTestPrefixes,
    vitest_no_test_return_statement::NoTestReturnStatement,
    vitest_no_unneeded_async_expect_function::NoUnneededAsyncExpectFunction,
    vitest_padding_around_after_all_blocks::PaddingAroundAfterAllBlocks,
    vitest_padding_around_test_blocks::PaddingAroundTestBlocks,
    vitest_prefer_called_exactly_once_with::PreferCalledExactlyOnceWith,
    vitest_prefer_called_once::PreferCalledOnce,
    vitest_prefer_called_times::PreferCalledTimes,
    vitest_prefer_called_with::PreferCalledWith,
    vitest_prefer_comparison_matcher::PreferComparisonMatcher,
    vitest_prefer_describe_function_title::PreferDescribeFunctionTitle,
    vitest_prefer_each::PreferEach,
    vitest_prefer_equality_matcher::PreferEqualityMatcher,
    vitest_prefer_expect_assertions::PreferExpectAssertions,
    vitest_prefer_expect_resolves::PreferExpectResolves,
    vitest_prefer_expect_type_of::PreferExpectTypeOf,
    vitest_prefer_hooks_in_order::PreferHooksInOrder,
    vitest_prefer_hooks_on_top::PreferHooksOnTop,
    vitest_prefer_import_in_mock::PreferImportInMock,
    vitest_prefer_importing_vitest_globals::PreferImportingVitestGlobals,
    vitest_prefer_lowercase_title::PreferLowercaseTitle,
    vitest_prefer_mock_promise_shorthand::PreferMockPromiseShorthand,
    vitest_prefer_mock_return_shorthand::PreferMockReturnShorthand,
    vitest_prefer_snapshot_hint::PreferSnapshotHint,
    vitest_prefer_spy_on::PreferSpyOn,
    vitest_prefer_strict_boolean_matchers::PreferStrictBooleanMatchers,
    vitest_prefer_strict_equal::PreferStrictEqual,
    vitest_prefer_to_be::PreferToBe,
    vitest_prefer_to_be_falsy::PreferToBeFalsy,
    vitest_prefer_to_be_object::PreferToBeObject,
    vitest_prefer_to_be_truthy::PreferToBeTruthy,
    vitest_prefer_to_contain::PreferToContain,
    vitest_prefer_to_have_been_called_times::PreferToHaveBeenCalledTimes,
    vitest_prefer_to_have_length::PreferToHaveLength,
    vitest_prefer_todo::PreferTodo,
    vitest_require_awaited_expect_poll::RequireAwaitedExpectPoll,
    vitest_require_hook::RequireHook,
    vitest_require_local_test_context_for_concurrent_snapshots::RequireLocalTestContextForConcurrentSnapshots,
    vitest_require_mock_type_parameters::RequireMockTypeParameters,
    vitest_require_test_timeout::RequireTestTimeout,
    vitest_require_to_throw_message::RequireToThrowMessage,
    vitest_require_top_level_describe::RequireTopLevelDescribe,
    vitest_valid_describe_callback::ValidDescribeCallback,
    vitest_valid_expect::ValidExpect,
    vitest_valid_expect_in_promise::ValidExpectInPromise,
    vitest_valid_title::ValidTitle,
    vitest_warn_todo::WarnTodo,
}
