//! Stage 1 of the XML parser: the streaming structural index — the position of every `<`, `>`,
//! `&`, `\r`, forbidden control character and encoded U+FFFE/U+FFFF (its last byte), plus `\t`
//! `\n` `"` `'` `=` between a `<` and the next `>` — produced by the Highway SIMD kernel or, off
//! native targets, the scalar indexer.

/// Generated by `scripts/build/xmlByteClass.ts`; shared with the Highway XML kernel.
pub(crate) mod byte_class {
    include!(concat!(env!("BUN_CODEGEN_DIR"), "/xml_byte_class.rs"));
}
use byte_class::{CLASS_ALWAYS, CLASS_GT, CLASS_LT, CLASS_TAG, XML_BYTE_CLASS};

pub(crate) const SENTINELS: usize = 2;

const REFILL_INPUT: usize = 8 * 1024;

const LOOKBEHIND: usize = 4;

/// The streaming structural index over one buffer of code units (`u8` for
/// UTF-8 / Latin-1, `u16` for UTF-16 — indexed by the scalar producer, whose
/// non-characters are the units 0xFFFE / 0xFFFF); ends with two `len` sentinels.
pub struct StructuralIndex<'c, U: crate::xml::Unit = u8> {
    contents: &'c [U],
    win: Vec<u32>,
    base: usize,
    done: bool,
    src_off: usize,
    kernel_state: [u64; 3],
    use_scalar: bool,
    s_in_tag: bool,
    /// Scalar producer, UTF-16: the last unit seen was a lead surrogate.
    s_pending_lead: bool,
}

impl<'c, U: crate::xml::Unit> StructuralIndex<'c, U> {
    pub fn new(contents: &'c [U]) -> Self {
        Self::with_producer(contents, !bun_core::env::IS_NATIVE)
    }

    fn with_producer(contents: &'c [U], use_scalar: bool) -> Self {
        debug_assert!(contents.len() <= i32::MAX as usize);
        let win_cap = contents.len().min(REFILL_INPUT) + 64 + SENTINELS + LOOKBEHIND;
        StructuralIndex {
            contents,
            win: Vec::with_capacity(win_cap),
            base: 0,
            done: false,
            src_off: 0,
            kernel_state: [0; 3],
            use_scalar,
            s_in_tag: false,
            s_pending_lead: false,
        }
    }

    /// Byte position of index `logical`, producing more of the index as needed.
    #[inline(always)]
    pub fn at(&mut self, logical: usize) -> usize {
        if logical.wrapping_sub(self.base) >= self.win.len() {
            self.fill_to(logical);
        }
        // SAFETY: `fill_to` returns only once `logical - base < win.len()`.
        unsafe { *self.win.get_unchecked(logical - self.base) as usize }
    }

    /// The first index `>= logical` whose position is `>= pos`, and that position.
    #[inline(always)]
    pub fn seek(&mut self, logical: usize, pos: usize) -> (usize, usize) {
        let mut rel = logical.wrapping_sub(self.base);
        let win = self.win.as_slice();
        // The window ends with the sentinels once the input is exhausted, so
        // within it this loop needs no end check beyond the length.
        while rel < win.len() {
            // SAFETY: `rel < win.len()`.
            let p = unsafe { *win.get_unchecked(rel) } as usize;
            if p >= pos {
                return (self.base + rel, p);
            }
            rel += 1;
        }
        self.seek_refill(self.base + rel.min(win.len()), pos)
    }

    #[cold]
    #[inline(never)]
    fn seek_refill(&mut self, mut logical: usize, pos: usize) -> (usize, usize) {
        loop {
            let p = self.at(logical);
            if p >= pos {
                return (logical, p);
            }
            logical += 1;
        }
    }

    #[cold]
    fn fill_to(&mut self, logical: usize) {
        while logical - self.base >= self.win.len() {
            if self.done {
                debug_assert!(false, "index requested past the sentinels");
                let last = *self.win.last().expect("sentinels present");
                self.win.push(last);
                continue;
            }
            let keep_from = logical.saturating_sub(LOOKBEHIND).max(self.base) - self.base;
            if keep_from > 0 {
                self.win.copy_within(keep_from.., 0);
                self.win.truncate(self.win.len() - keep_from);
                self.base += keep_from;
            }
            self.refill_once();
        }
    }

    fn refill_once(&mut self) {
        let len = self.contents.len();
        if self.src_off >= len {
            return self.finish();
        }
        let chunk_len = (len - self.src_off).min(REFILL_INPUT);
        let chunk = &self.contents[self.src_off..self.src_off + chunk_len];
        if bun_core::env::IS_NATIVE && !self.use_scalar {
            let filled = self.win.len();
            let out = &mut self.win.spare_capacity_mut()[..chunk_len + 64];
            let n = if U::WIDE {
                bun_highway::xml_structural_index16_chunk(
                    bytemuck::cast_slice(U::bytes(chunk)),
                    self.src_off,
                    out,
                    &mut self.kernel_state,
                )
            } else {
                bun_highway::xml_structural_index_chunk(
                    U::bytes(chunk),
                    self.src_off,
                    out,
                    &mut self.kernel_state,
                )
            };
            // SAFETY: the kernel initialized `n` entries of the spare capacity it was given.
            unsafe { self.win.set_len(filled + n) };
        } else {
            self.scalar_chunk(chunk, self.src_off);
        }
        self.src_off += chunk_len;
    }

    fn finish(&mut self) {
        let len = self.contents.len() as u32;
        // A lead surrogate as the very last unit never got its verdict.
        if U::WIDE && (self.kernel_state[1] & 1 != 0 || self.s_pending_lead) {
            self.win.push(len - 1);
        }
        self.win.push(len);
        self.win.push(len);
        self.done = true;
    }

    fn scalar_chunk(&mut self, chunk: &[U], base: usize) {
        let mut in_tag = self.s_in_tag;
        for (i, &u) in chunk.iter().enumerate() {
            let c = u.low();
            let cls = XML_BYTE_CLASS[c as usize];
            if cls == 0 {
                if U::WIDE {
                    let v = u.value();
                    let lead_before = core::mem::replace(&mut self.s_pending_lead, false);
                    match v & 0xFC00 {
                        0xD800 => {
                            if lead_before {
                                self.win.push((base + i - 1) as u32);
                            }
                            self.s_pending_lead = true;
                            continue;
                        }
                        0xDC00 => {
                            if !lead_before {
                                self.win.push((base + i) as u32);
                            }
                            continue;
                        }
                        _ => {
                            if lead_before {
                                self.win.push((base + i - 1) as u32);
                            }
                        }
                    }
                }
                let nonchar = if U::WIDE {
                    u.value() | 1 == 0xFFFF
                } else {
                    c | 1 == 0xBF
                        && base + i >= 2
                        && self.contents[base + i - 1].low() == 0xBF
                        && self.contents[base + i - 2].low() == 0xEF
                };
                if nonchar {
                    self.win.push((base + i) as u32);
                }
                continue;
            }
            if U::WIDE && core::mem::replace(&mut self.s_pending_lead, false) {
                self.win.push((base + i - 1) as u32);
            }
            if cls & CLASS_LT != 0 {
                in_tag = true;
            } else if cls & CLASS_GT != 0 {
                in_tag = false;
            } else if cls & CLASS_ALWAYS == 0 && !(in_tag && cls & CLASS_TAG != 0) {
                continue;
            }
            self.win.push((base + i) as u32);
        }
        self.s_in_tag = in_tag;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn collect(idx: &mut StructuralIndex) -> Vec<u32> {
        let len = idx.contents.len();
        let mut out = Vec::new();
        let mut i = 0;
        loop {
            let p = idx.at(i);
            if i > 0 {
                assert!(idx.at(i - 1) <= p);
            }
            if p == len && idx.at(i + 1) == len {
                break;
            }
            out.push(p as u32);
            i += 1;
        }
        out
    }

    fn build_both(contents: &[u8]) -> (Vec<u32>, Vec<u32>) {
        let mut simd = StructuralIndex::new(contents);
        let si = collect(&mut simd);
        let mut scalar = StructuralIndex::with_producer(contents, true);
        let ci = collect(&mut scalar);
        (si, ci)
    }

    #[test]
    fn positions_inside_and_outside_tags() {
        let src = "a\tb <x y=\"1 2\"\n z='>'>\r\n&amp; = \"q\" > <\u{FFFE}\u{FFFF}\u{FFFD}\u{FBFF}";
        let mut x = StructuralIndex::with_producer(src.as_bytes(), true);
        let v = collect(&mut x);
        let expected: Vec<u32> = src
            .bytes()
            .enumerate()
            .filter_map(|(i, c)| {
                let in_tag = (4..=19).contains(&i) || i >= 38;
                let hit = matches!(c, b'<' | b'>' | b'&' | b'\r')
                    || (c < 0x20 && c != b'\t' && c != b'\n')
                    || (in_tag && matches!(c, b'\t' | b'\n' | b'"' | b'\'' | b'='))
                    || (i >= 2 && c | 1 == 0xBF && &src.as_bytes()[i - 2..i] == b"\xEF\xBF");
                hit.then_some(i as u32)
            })
            .collect();
        assert_eq!(v, expected);
        let (si, ci) = build_both(src.as_bytes());
        assert_eq!(si, ci);
    }

    #[test]
    fn simd_and_scalar_indexers_agree() {
        let mut state = 0x9E3779B97F4A7C15u64;
        let mut rng = move || {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };
        let alphabet: &[u8] = b"<>&=\"' \t\n\rabc/?!-[]x01\x01\x1f\x0b\x80\xc3\xa9\xef\xbf\xbe";
        for _ in 0..20_000 {
            let len = (rng() % 300) as usize;
            let mut buf = Vec::with_capacity(len);
            for _ in 0..len {
                buf.push(alphabet[(rng() as usize) % alphabet.len()]);
            }
            let (si, ci) = build_both(&buf);
            assert_eq!(si, ci, "index mismatch for {:?}", bstr::BStr::new(&buf));
        }
        for pad in 40..=200usize {
            let doc = format!(
                "<r a=\"{}\">{}<b\n\tc='d'/>&e;\r\n</r>",
                "v ".repeat(pad / 3),
                "t\u{e9}\t".repeat(pad),
            );
            let (si, ci) = build_both(doc.as_bytes());
            assert_eq!(si, ci, "mismatch for {doc:?}");
        }
    }

    #[test]
    fn streaming_and_scalar_indexers_agree_on_large_documents() {
        let mut doc = String::with_capacity(3 * 1024 * 1024);
        doc.push_str("<root>");
        let mut i = 0;
        while doc.len() < 40 * REFILL_INPUT {
            doc.push_str(&format!(
                "<item id=\"{i}\" name='n{i}'>\r\n\t<v k=\"a=b\">text {i} &amp; more > here</v><w x=\"1\ty\"/></item>\n"
            ));
            i += 1;
        }
        doc.push_str("</root>");
        let (si, ci) = build_both(doc.as_bytes());
        assert_eq!(si.len(), ci.len(), "index count");
        assert_eq!(si, ci);
        // A tag straddling a chunk boundary.
        for cut in 1..80usize {
            let mut doc = "x".repeat(REFILL_INPUT - cut);
            doc.push_str("<abc d=\"e\tf\"\n g='h'>tail\t=\"'\n\u{FFFE}x\u{FFFF}");
            let (si, ci) = build_both(doc.as_bytes());
            assert_eq!(si, ci, "cut {cut}");
        }
    }

    fn build_both16(units: &[u16]) -> (Vec<u32>, Vec<u32>) {
        let mut simd = StructuralIndex::<u16>::new(units);
        let si = collect16(&mut simd);
        let mut scalar = StructuralIndex::<u16>::with_producer(units, true);
        let ci = collect16(&mut scalar);
        (si, ci)
    }

    fn collect16(idx: &mut StructuralIndex<u16>) -> Vec<u32> {
        let len = idx.contents.len();
        let mut out = Vec::new();
        let mut i = 0;
        loop {
            let p = idx.at(i);
            if p == len && idx.at(i + 1) == len {
                break;
            }
            out.push(p as u32);
            i += 1;
        }
        out
    }

    #[test]
    fn utf16_simd_and_scalar_indexers_agree() {
        // The byte cases, widened, index at the same positions as their bytes do…
        let src = "a\tb <x y=\"1 2\"\n z='>'>\r\n&amp; = \"q\" > <";
        let units: Vec<u16> = src.encode_utf16().collect();
        let mut narrow = StructuralIndex::<u8>::with_producer(src.as_bytes(), true);
        let expected = collect(&mut narrow);
        let (si, ci) = build_both16(&units);
        assert_eq!(ci, expected);
        assert_eq!(si, ci);
        // …units above U+00FF never classify, except the two non-characters…
        let doc: Vec<u16> = "<日本 a=\"\u{FF1D}\u{FF1C}\">\u{FFFE}x\u{FFFF}\u{1F600}&\u{3E}</日本>"
            .encode_utf16()
            .collect();
        let (si, ci) = build_both16(&doc);
        assert_eq!(si, ci);
        assert!(ci.contains(&(doc.iter().position(|&u| u == 0xFFFE).unwrap() as u32)));
        // Paired surrogates (the emoji) are not entries; lone ones are, wherever they fall.
        assert!(!ci.contains(&(doc.iter().position(|&u| u == 0xD83D).unwrap() as u32)));
        for tail in ["\u{10000}", "x"] {
            for cut in 0..130usize {
                let mut units: Vec<u16> = "z".repeat(cut).encode_utf16().collect();
                let lone_lead = units.len();
                units.push(0xD800);
                units.extend("ab".encode_utf16());
                let lone_trail = units.len();
                units.push(0xDC00);
                units.extend(tail.encode_utf16());
                units.push(0xDBFF);
                let last = units.len() - 1;
                let (si, ci) = build_both16(&units);
                assert_eq!(si, ci, "cut {cut} tail {tail:?}");
                assert!(ci.contains(&(lone_lead as u32)), "lead, cut {cut}: {ci:?}");
                assert!(ci.contains(&(lone_trail as u32)), "trail, cut {cut}");
                assert!(ci.contains(&(last as u32)), "final lead, cut {cut}");
                assert_eq!(
                    ci.iter()
                        .filter(|&&p| (units[p as usize] & 0xF800) == 0xD800)
                        .count(),
                    3,
                    "cut {cut}: {ci:?}"
                );
            }
        }
        assert!(!ci.contains(&(doc.iter().position(|&u| u == 0xFF1D).unwrap() as u32)));
        // …and random / large / block-straddling input agrees too.
        let mut state = 0x2545F4914F6CDD1Du64;
        let mut rng = move || {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };
        let alphabet: &[u16] = &[
            0x3C, 0x3E, 0x26, 0x3D, 0x22, 0x27, 0x20, 0x09, 0x0A, 0x0D, 0x61, 0x2F, 0x01, 0x1F,
            0xE9, 0xFF, 0x100, 0x13C, 0x203E, 0x3C00, 0xFFFE, 0xFFFF, 0xD83D, 0xDE00, 0xFEFF,
        ];
        for _ in 0..20_000 {
            let len = (rng() % 300) as usize;
            let buf: Vec<u16> = (0..len)
                .map(|_| alphabet[(rng() as usize) % alphabet.len()])
                .collect();
            let (si, ci) = build_both16(&buf);
            assert_eq!(si, ci, "index mismatch for {buf:x?}");
        }
        let mut big: Vec<u16> = Vec::new();
        let mut i = 0;
        while big.len() < 5 * REFILL_INPUT {
            big.extend(
                format!("<item id=\"{i}\" 名前='n'>\r\n\tテキスト {i} &amp; > z</item>\n")
                    .encode_utf16(),
            );
            i += 1;
        }
        let (si, ci) = build_both16(&big);
        assert_eq!(si, ci);
    }

    #[test]
    fn empty_and_text_only_documents() {
        let (si, ci) = build_both(b"");
        assert!(si.is_empty() && ci.is_empty());
        let (si, ci) = build_both(b"just some text\n\twith = \"quotes\" 'and' tabs");
        assert!(si.is_empty() && ci.is_empty());
    }
}
