const cases = [
  "namespace A.B { interface X {} }\nconsole.log(1)",
  "namespace A { interface X {} }\nconsole.log(1)",
  "namespace A.B { export const x = 1 }",
  "declare namespace A.B { const x: number }\nconsole.log(1)",
  "if (x) interface A {}",
  "if (x) type A = 1; else declare var y: number;",
  "switch (x) { case 1: type A = 1; interface B {} ; break }",
  "label: type A = 1",
  "while (x) declare function f(): void;",
  "export default interface A {}\nexport const x = 1",
  "export default function f(a: string): void;\nexport default function f(a: any) {}",
  "export default async function f(): Promise<void>;\nexport default async function f() {}",
  "declare module 'fs' { export function f(): void; import x from 'y'; global { interface G {} } }\nconsole.log(1)",
  "declare module '*.css';\nconsole.log(1)",
  "declare module '*.css' { const c: string; export default c }\nconsole.log(1)",
  "declare global { var x: number; interface A {} }\nconsole.log(1)",
  "export declare global { var x: number }\nconsole.log(1)",
  "declare;",
  "declare\nfoo",
  "export as namespace ns;\nconsole.log(1)",
  "import type A from 'a'; import type * as B from 'b'; import type { C, D as E } from 'c'; import { type F } from 'f'; import type G = require('g'); import type H = A.B;\nconsole.log(1)",
  "export type { A } from 'a'; export type * from 'b'; export type * as C from 'c'; export { type D } from 'd'; export { type E }; export type { F };\ntype E = 1; type F = 2;",
  "namespace N { import a = b.c; }\nconsole.log(1)",
  "namespace N { export import a = b.c; }\nconsole.log(1)",
  "declare namespace N { import a = b.c; export import d = e.f; }\nconsole.log(1)",
  "declare import a = b.c;",
  "@dec declare class A { m(): void }\nconsole.log(1)",
  "@dec export declare abstract class A { abstract m(): void }\nconsole.log(1)",
  "export @dec declare class A {}\nconsole.log(1)",
  "class C { m(): void; m(a: string): void; m(a?: string) {} abstract n(): void; declare x: number; [k: string]: any; static [k: number]: string; constructor(); constructor(a?: any) {} get g(): number; }",
  "abstract class C { abstract x: number; abstract get y(): number; abstract set y(v: number); private abstract z(): void; @dec abstract w: number; @dec declare v: number }",
  "function f(): void;\nfunction f() {}\nconsole.log(f)",
  "declare function f(): void { }\nconsole.log(1)",
  "declare const x: number, y: string; declare let z; declare var w;\nconsole.log(1)",
  "namespace N { export declare const x: number; export declare function f(): void; export declare class K {} }\nconsole.log(N)",
  "declare enum E { A = 1 } declare const enum F { B }\nconsole.log(1)",
  "declare class C<T> extends D<T> implements I { x: T; static y: number; m(): void; constructor(a: T); }\nconsole.log(1)",
  "declare namespace N { class C { m() { interface Inner {} } } }\nconsole.log(1)",
  "function g() { interface A {} type B = 1; declare const c: number; return 1 }",
  "try { type A = 1 } catch { interface B {} } finally { declare let c: number }",
  "class C { static { type A = 1; interface B {} } }",
  "const f = () => { type A = 1; return 2 }",
  "module M { export interface I {} }\nmodule M2.N3 { export const a = 1 }",
  "declare module M { }",
  "namespace A.export.C { export const x = 1 }",
  "export declare namespace N { const a: number }\nexport namespace O { export type T = 1 }\nconsole.log(1)",
  "import type from 'x'; import type, { a } from 'y'; import type T, { b } from 'z';",
  "import {} from 'x'; import { type A, b } from 'y'; export { type C, d } from 'z';",
  "export type A = 1; export interface B {} export declare const c: number; export declare function d(): void; export abstract class E {} export declare abstract class F {}",
  "declare using x: number;",
  "export = foo;",
  "declare export class A {}",
  "declare type T = 1; declare interface I {} declare abstract class C {}\nconsole.log(1)",
  "type\nFoo = 1",
  "interface\nFoo {}",
  "declare function f(...a: any[],): void;",
  "export default abstract class A { abstract m(): void }",
  "declare async function f(): Promise<void>;",
  "async function f(): Promise<void>;\nasync function f() {}",
  "export async function f(): Promise<void>;\nexport async function f() {}",
  "function* g(): Generator;\nfunction* g() {}",
  "declare const enum E {}; declare var v: number;;",
];
for (const src of cases) {
  for (const loader of ["ts"]) {
    const t = new Bun.Transpiler({ loader, target: "bun", tsconfig: { compilerOptions: { experimentalDecorators: true } } });
    let out;
    try { out = "OK   " + JSON.stringify(t.transformSync(src)); }
    catch (e) { out = "FAIL " + JSON.stringify(String(e?.errors?.[0]?.message ?? e?.message ?? e).split("\n")[0]); }
    console.log(JSON.stringify(src)); console.log("   -> " + out);
  }
}
