// Port of the flags of internal/ast/subtreefacts.go. The binder and the checker do not read them: they mark syntax for the transformers.
use crate::ast::flags::define_flags;

define_flags!(SubtreeFacts: u32 {
    CONTAINS_TYPE_SCRIPT = 1 << 0,
    CONTAINS_JSX = 1 << 1,
    CONTAINS_ES_DECORATORS = 1 << 2,
    CONTAINS_USING = 1 << 3,
    CONTAINS_CLASS_STATIC_BLOCKS = 1 << 4,
    CONTAINS_ES_CLASS_FIELDS = 1 << 5,
    CONTAINS_LOGICAL_ASSIGNMENTS = 1 << 6,
    CONTAINS_NULLISH_COALESCING = 1 << 7,
    CONTAINS_OPTIONAL_CHAINING = 1 << 8,
    CONTAINS_MISSING_CATCH_CLAUSE_VARIABLE = 1 << 9,
    CONTAINS_ES_OBJECT_REST_OR_SPREAD = 1 << 10, // subtree has a `...` somewhere inside it, never cleared
    CONTAINS_FOR_AWAIT_OR_ASYNC_GENERATOR = 1 << 11,
    CONTAINS_ANY_AWAIT = 1 << 12,
    CONTAINS_EXPONENTIATION_OPERATOR = 1 << 13,
    CONTAINS_LEXICAL_THIS = 1 << 14,
    CONTAINS_LEXICAL_SUPER = 1 << 15,
    CONTAINS_REST_OR_SPREAD = 1 << 16, // marker on any `...` - cleared on binding pattern exit
    CONTAINS_OBJECT_REST_OR_SPREAD = 1 << 17, // marker on any `{...x}` - cleared on most scope exits
    CONTAINS_AWAIT = 1 << 18,
    CONTAINS_DYNAMIC_IMPORT = 1 << 19,
    CONTAINS_CLASS_FIELDS = 1 << 20,
    CONTAINS_DECORATORS = 1 << 21,
    CONTAINS_IDENTIFIER = 1 << 22,
    CONTAINS_PRIVATE_IDENTIFIER_IN_EXPRESSION = 1 << 23,
    CONTAINS_INVALID_TEMPLATE_ESCAPE = 1 << 24,
    COMPUTED = 1 << 25, // NOTE: This should always be last
    CONTAINS_ES_NEXT = Self::CONTAINS_ES_DECORATORS.0 | Self::CONTAINS_USING.0,
    CONTAINS_ES2022 = Self::CONTAINS_CLASS_STATIC_BLOCKS.0 | Self::CONTAINS_ES_CLASS_FIELDS.0,
    CONTAINS_ES2021 = Self::CONTAINS_LOGICAL_ASSIGNMENTS.0,
    CONTAINS_ES2020 = Self::CONTAINS_NULLISH_COALESCING.0 | Self::CONTAINS_OPTIONAL_CHAINING.0,
    CONTAINS_ES2019 = Self::CONTAINS_MISSING_CATCH_CLAUSE_VARIABLE.0,
    CONTAINS_ES2018 = Self::CONTAINS_ES_OBJECT_REST_OR_SPREAD.0
        | Self::CONTAINS_FOR_AWAIT_OR_ASYNC_GENERATOR.0 | Self::CONTAINS_INVALID_TEMPLATE_ESCAPE.0,
    CONTAINS_ES2017 = Self::CONTAINS_ANY_AWAIT.0,
    CONTAINS_ES2016 = Self::CONTAINS_EXPONENTIATION_OPERATOR.0,
    EXCLUSIONS_NODE = Self::COMPUTED.0,
    EXCLUSIONS_ERASEABLE = !Self::CONTAINS_TYPE_SCRIPT.0,
    EXCLUSIONS_OUTER_EXPRESSION = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_PROPERTY_ACCESS = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_ELEMENT_ACCESS = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_ARROW_FUNCTION = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_AWAIT.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_FUNCTION = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0 | Self::CONTAINS_AWAIT.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_CONSTRUCTOR = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0 | Self::CONTAINS_AWAIT.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_METHOD = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0 | Self::CONTAINS_AWAIT.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_ACCESSOR = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0 | Self::CONTAINS_AWAIT.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_PROPERTY = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0,
    EXCLUSIONS_CLASS = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_MODULE = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_LEXICAL_THIS.0
        | Self::CONTAINS_LEXICAL_SUPER.0,
    EXCLUSIONS_OBJECT_LITERAL = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_ARRAY_LITERAL = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_CALL = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_NEW = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_VARIABLE_DECLARATION_LIST = Self::EXCLUSIONS_NODE.0
        | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_PARAMETER = Self::EXCLUSIONS_NODE.0,
    EXCLUSIONS_CATCH_CLAUSE = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_OBJECT_REST_OR_SPREAD.0,
    EXCLUSIONS_BINDING_PATTERN = Self::EXCLUSIONS_NODE.0 | Self::CONTAINS_REST_OR_SPREAD.0,
    CONTAINS_LEXICAL_THIS_OR_SUPER = Self::CONTAINS_LEXICAL_THIS.0 | Self::CONTAINS_LEXICAL_SUPER.0,
});
