import { define } from "../../codegen/class-definitions";

export default [
  define({
    name: "TelemetrySpan",
    construct: false,
    noConstructor: true,
    finalize: true,
    configurable: false,
    klass: {},
    JSType: "0b11101110",
    proto: {
      setAttribute: { fn: "setAttribute", length: 2 },
      setAttributes: { fn: "setAttributes", length: 1 },
      addEvent: { fn: "addEvent", length: 3 },
      addLink: { fn: "addLink", length: 1 },
      addLinks: { fn: "addLinks", length: 1 },
      setStatus: { fn: "setStatus", length: 1 },
      updateName: { fn: "updateName", length: 1 },
      recordException: { fn: "recordException", length: 2 },
      isRecording: { fn: "isRecording", length: 0 },
      spanContext: { fn: "spanContext", length: 0 },
      end: { fn: "end", length: 1 },
      enter: { fn: "enter", length: 0 },
      exit: { fn: "exit", length: 0 },
      "@@dispose": { fn: "dispose", length: 0 },
      traceId: { getter: "getTraceId", cache: true },
      spanId: { getter: "getSpanId", cache: true },
      parentSpanId: { getter: "getParentSpanId" },
      traceFlags: { getter: "getTraceFlags" },
      isRemote: { getter: "getIsRemote" },
      name: { getter: "getName" },
      kind: { getter: "getKind" },
      ended: { getter: "getEnded" },
    },
    values: ["restore", "context"],
  }),
];
