name: "Build for macos xx (object-files)"
description: "Build bun for macos xx (object-files)"

inputs:
  cpu:
    required: true
  arch:
    required: true
  tag:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout submodules
      run: git -c submodule."src/bun.js/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j $(nproc)
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    - name: Run
      run: |
        rm -rf ${{ runner.temp }}/release
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ghcr.io/oven-sh/bun:canary,ghcr.io/oven-sh/bun:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-bust-3--${{ inputs.cpu }}-${{ inputs.arch }}-macos
        cache-to: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-bust-3--${{ inputs.cpu }}-${{ inputs.arch }}-macos,mode=max
        build-args: |
          ARCH=${{ inputs.arch }}
          BUILDARCH=amd64
          CPU_TARGET=${{ inputs.cpu }}
          TRIPLET=${{ inputs.arch }}-macos-none
        platforms: linux/amd64
        target: build_release_obj
        outputs: type=local,dest=${{ runner.temp }}/release
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.tag }}
        path: ${{ runner.temp }}/release/bun.o