use crate::a11y::{cow_to_ascii_lowercase, is_valid_aria_property};
use bun_lint_oxlint::ast_util::get_identifier_name;
use crate::react::is_jsx;
use bun_lint_oxlint::text::contains_name;
use bun_core::strings;
use bun_lint::prelude::*;
use bun_lint::rule::Plugin;

/// Disallow usage of unknown DOM properties.
pub struct NoUnknownProperty {
    ignore: Vec<Box<[u8]>>,
    require_data_lowercase: bool,
}

const INVALID_PROP_ON_TAG: Message = Message::new("", "Invalid property found");
const DATA_LOWERCASE_REQUIRED: Message =
    Message::new("", "React does not recognize data-* props with uppercase characters on a DOM element");
const UNKNOWN_PROP: Message = Message::new("", "Unknown property found");
const USE_STANDARD_NAME: Message = Message::new("", "Use '{{x1}}' instead");

/// The elements that an attribute is for. The attributes are sorted, as all the tables are; the elements are in the order in
/// which oxlint lists them.
static ATTRIBUTE_TAGS_MAP: [(&str, &[&str]); 70] = [
    ("abbr", &["td", "th"]),
    (
        "align",
        &[
            "table", "th", "colgroup", "img", "caption", "hr", "tfoot", "thead", "tr", "col", "iframe", "td", "applet",
            "tbody",
        ],
    ),
    ("allowFullScreen", &["video", "iframe"]),
    ("as", &["link"]),
    ("autoPictureInPicture", &["video"]),
    ("charset", &["meta"]),
    ("checked", &["input"]),
    ("closedby", &["dialog"]),
    ("controls", &["audio", "video"]),
    ("controlsList", &["audio", "video"]),
    ("credentialless", &["iframe"]),
    ("crossOrigin", &["audio", "script", "link", "image", "video", "img"]),
    ("disablePictureInPicture", &["video"]),
    ("disableRemotePlayback", &["audio", "video"]),
    ("displaystyle", &["math"]),
    ("download", &["a", "area"]),
    ("fetchPriority", &["script", "img", "link"]),
    (
        "fill",
        &[
            "tspan", "set", "animateColor", "line", "svg", "path", "text", "ellipse", "use", "marker", "tref", "rect",
            "polygon", "symbol", "g", "mask", "textPath", "altGlyph", "animateMotion", "polyline", "circle",
            "animateTransform", "animate",
        ],
    ),
    ("focusable", &["svg"]),
    ("imageSizes", &["link"]),
    ("imageSrcSet", &["link"]),
    ("loop", &["audio", "video"]),
    ("mozAllowFullScreen", &["video", "iframe"]),
    ("muted", &["audio", "video"]),
    ("noModule", &["script"]),
    ("onAbort", &["audio", "video"]),
    ("onCanPlay", &["audio", "video"]),
    ("onCanPlayThrough", &["audio", "video"]),
    ("onCancel", &["dialog"]),
    ("onClose", &["dialog"]),
    ("onDurationChange", &["audio", "video"]),
    ("onEmptied", &["audio", "video"]),
    ("onEncrypted", &["audio", "video"]),
    ("onEnded", &["audio", "video"]),
    ("onError", &["img", "iframe", "video", "picture", "audio", "link", "source", "script"]),
    ("onLoad", &["iframe", "link", "body", "script", "source", "object", "img", "picture"]),
    ("onLoadStart", &["audio", "video"]),
    ("onLoadedData", &["audio", "video"]),
    ("onLoadedMetadata", &["audio", "video"]),
    ("onPause", &["audio", "video"]),
    ("onPlay", &["audio", "video"]),
    ("onPlaying", &["audio", "video"]),
    ("onProgress", &["audio", "video"]),
    ("onRateChange", &["audio", "video"]),
    ("onResize", &["audio", "video"]),
    ("onSeeked", &["audio", "video"]),
    ("onSeeking", &["audio", "video"]),
    ("onStalled", &["audio", "video"]),
    ("onSuspend", &["audio", "video"]),
    ("onTimeUpdate", &["audio", "video"]),
    ("onVolumeChange", &["audio", "video"]),
    ("onWaiting", &["audio", "video"]),
    ("playsInline", &["video"]),
    ("popoverTarget", &["input", "button"]),
    ("popoverTargetAction", &["input", "button"]),
    ("poster", &["video"]),
    ("precedence", &["link", "style"]),
    ("preload", &["audio", "video"]),
    ("property", &["meta"]),
    ("returnValue", &["dialog"]),
    ("scrolling", &["iframe"]),
    ("shadowrootclonable", &["template"]),
    ("shadowrootdelegatesfocus", &["template"]),
    ("shadowrootmode", &["template"]),
    ("shadowrootserializable", &["template"]),
    ("transform-origin", &["rect"]),
    ("valign", &["tfoot", "col", "tr", "th", "td", "colgroup", "thead", "tbody"]),
    ("viewBox", &["symbol", "svg", "marker", "pattern", "view"]),
    ("webkitAllowFullScreen", &["video", "iframe"]),
    ("webkitDirectory", &["input"]),
];

static DOM_PROPERTIES_NAMES: [&str; 575] = [
    "accentHeight",
    "accept",
    "acceptCharset",
    "accessKey",
    "accumulate",
    "action",
    "additive",
    "alignmentBaseline",
    "allow",
    "alphabetic",
    "alt",
    "amplitude",
    "arabicForm",
    "as",
    "ascent",
    "async",
    "attributeName",
    "attributeType",
    "autoCapitalize",
    "autoComplete",
    "autoCorrect",
    "autoFocus",
    "autoPictureInPicture",
    "autoPlay",
    "autoSave",
    "azimuth",
    "baseFrequency",
    "baseProfile",
    "baselineShift",
    "bbox",
    "begin",
    "bias",
    "border",
    "buffered",
    "by",
    "calcMode",
    "capHeight",
    "capture",
    "cellPadding",
    "cellSpacing",
    "challenge",
    "children",
    "cite",
    "classID",
    "className",
    "clip",
    "clipPath",
    "clipPathUnits",
    "clipRule",
    "code",
    "codeBase",
    "colSpan",
    "color",
    "colorInterpolation",
    "colorInterpolationFilters",
    "colorProfile",
    "colorRendering",
    "cols",
    "content",
    "contentEditable",
    "contentScriptType",
    "contentStyleType",
    "contextMenu",
    "controls",
    "controlsList",
    "coords",
    "crossOrigin",
    "csp",
    "cursor",
    "cx",
    "cy",
    "d",
    "dangerouslySetInnerHTML",
    "data",
    "dateTime",
    "decelerate",
    "decoding",
    "default",
    "defaultChecked",
    "defaultValue",
    "defer",
    "descent",
    "diffuseConstant",
    "dir",
    "direction",
    "disablePictureInPicture",
    "disableRemotePlayback",
    "disabled",
    "display",
    "divisor",
    "dominantBaseline",
    "draggable",
    "dur",
    "dx",
    "dy",
    "edgeMode",
    "elevation",
    "enableBackground",
    "encType",
    "end",
    "enterKeyHint",
    "exponent",
    "exportParts",
    "fill",
    "fillOpacity",
    "fillRule",
    "filter",
    "filterRes",
    "filterUnits",
    "floodColor",
    "floodOpacity",
    "fontFamily",
    "fontSize",
    "fontSizeAdjust",
    "fontStretch",
    "fontStyle",
    "fontVariant",
    "fontWeight",
    "form",
    "formAction",
    "formEncType",
    "formMethod",
    "formNoValidate",
    "formTarget",
    "format",
    "fr",
    "frameBorder",
    "from",
    "fx",
    "fy",
    "g1",
    "g2",
    "glyphName",
    "glyphOrientationHorizontal",
    "glyphOrientationVertical",
    "glyphRef",
    "gradientTransform",
    "gradientUnits",
    "hanging",
    "headers",
    "height",
    "hidden",
    "high",
    "horizAdvX",
    "horizOriginX",
    "href",
    "hrefLang",
    "hreflang",
    "htmlFor",
    "httpEquiv",
    "icon",
    "id",
    "ideographic",
    "imageRendering",
    "imageSizes",
    "imageSrcSet",
    "importance",
    "in",
    "in2",
    "inert",
    "inputMode",
    "integrity",
    "intercept",
    "isMap",
    "itemID",
    "itemProp",
    "itemRef",
    "itemScope",
    "itemType",
    "k",
    "k1",
    "k2",
    "k3",
    "k4",
    "kernelMatrix",
    "kernelUnitLength",
    "kerning",
    "key",
    "keyParams",
    "keyPoints",
    "keySplines",
    "keyTimes",
    "keyType",
    "kind",
    "label",
    "lang",
    "language",
    "lengthAdjust",
    "letterSpacing",
    "lightingColor",
    "limitingConeAngle",
    "list",
    "loading",
    "local",
    "loop",
    "low",
    "manifest",
    "marginHeight",
    "marginWidth",
    "markerEnd",
    "markerHeight",
    "markerMid",
    "markerStart",
    "markerUnits",
    "markerWidth",
    "mask",
    "maskContentUnits",
    "maskType",
    "maskUnits",
    "mathematical",
    "max",
    "maxLength",
    "media",
    "mediaGroup",
    "method",
    "min",
    "minLength",
    "mode",
    "multiple",
    "muted",
    "name",
    "noValidate",
    "nonce",
    "numOctaves",
    "offset",
    "onAbort",
    "onAbortCapture",
    "onAnimationEnd",
    "onAnimationEndCapture",
    "onAnimationIteration",
    "onAnimationStart",
    "onAnimationStartCapture",
    "onAuxClick",
    "onAuxClickCapture",
    "onBeforeInput",
    "onBeforeInputCapture",
    "onBeforeToggle",
    "onBlur",
    "onBlurCapture",
    "onCanPlay",
    "onCanPlayCapture",
    "onCanPlayThrough",
    "onCanPlayThroughCapture",
    "onChange",
    "onChangeCapture",
    "onClick",
    "onClickCapture",
    "onCompositionEnd",
    "onCompositionEndCapture",
    "onCompositionStart",
    "onCompositionStartCapture",
    "onCompositionUpdate",
    "onCompositionUpdateCapture",
    "onContextMenu",
    "onContextMenuCapture",
    "onCopy",
    "onCopyCapture",
    "onCut",
    "onCutCapture",
    "onDoubleClick",
    "onDoubleClickCapture",
    "onDrag",
    "onDragCapture",
    "onDragEnd",
    "onDragEndCapture",
    "onDragEnter",
    "onDragEnterCapture",
    "onDragExit",
    "onDragExitCapture",
    "onDragLeave",
    "onDragLeaveCapture",
    "onDragOver",
    "onDragOverCapture",
    "onDragStart",
    "onDragStartCapture",
    "onDrop",
    "onDropCapture",
    "onDurationChange",
    "onDurationChangeCapture",
    "onEmptied",
    "onEmptiedCapture",
    "onEncrypted",
    "onEncryptedCapture",
    "onEnded",
    "onEndedCapture",
    "onError",
    "onErrorCapture",
    "onFocus",
    "onFocusCapture",
    "onFullscreenChange",
    "onFullscreenChangeCapture",
    "onFullscreenError",
    "onFullscreenErrorCapture",
    "onGotPointerCaptureCapture",
    "onInput",
    "onInputCapture",
    "onInvalid",
    "onInvalidCapture",
    "onKeyDown",
    "onKeyDownCapture",
    "onKeyPress",
    "onKeyPressCapture",
    "onKeyUp",
    "onKeyUpCapture",
    "onLoad",
    "onLoadCapture",
    "onLoadStart",
    "onLoadStartCapture",
    "onLoadedData",
    "onLoadedDataCapture",
    "onLoadedMetadata",
    "onLoadedMetadataCapture",
    "onLostPointerCapture",
    "onLostPointerCaptureCapture",
    "onMouseDown",
    "onMouseDownCapture",
    "onMouseEnter",
    "onMouseLeave",
    "onMouseMove",
    "onMouseMoveCapture",
    "onMouseOut",
    "onMouseOutCapture",
    "onMouseOver",
    "onMouseOverCapture",
    "onMouseUp",
    "onMouseUpCapture",
    "onPaste",
    "onPasteCapture",
    "onPause",
    "onPauseCapture",
    "onPlay",
    "onPlayCapture",
    "onPlaying",
    "onPlayingCapture",
    "onPointerCancel",
    "onPointerCancelCapture",
    "onPointerDown",
    "onPointerDownCapture",
    "onPointerEnter",
    "onPointerEnterCapture",
    "onPointerLeave",
    "onPointerLeaveCapture",
    "onPointerMove",
    "onPointerMoveCapture",
    "onPointerOut",
    "onPointerOutCapture",
    "onPointerOver",
    "onPointerOverCapture",
    "onPointerUp",
    "onPointerUpCapture",
    "onProgress",
    "onProgressCapture",
    "onRateChange",
    "onRateChangeCapture",
    "onReset",
    "onResetCapture",
    "onResize",
    "onScroll",
    "onScrollCapture",
    "onScrollEnd",
    "onScrollEndCapture",
    "onSeeked",
    "onSeekedCapture",
    "onSeeking",
    "onSeekingCapture",
    "onSelect",
    "onSelectCapture",
    "onStalled",
    "onStalledCapture",
    "onSubmit",
    "onSubmitCapture",
    "onSuspend",
    "onSuspendCapture",
    "onTimeUpdate",
    "onTimeUpdateCapture",
    "onToggle",
    "onTouchCancel",
    "onTouchCancelCapture",
    "onTouchEnd",
    "onTouchEndCapture",
    "onTouchMove",
    "onTouchMoveCapture",
    "onTouchStart",
    "onTouchStartCapture",
    "onTransitionCancel",
    "onTransitionCancelCapture",
    "onTransitionEnd",
    "onTransitionEndCapture",
    "onTransitionRun",
    "onTransitionRunCapture",
    "onTransitionStart",
    "onTransitionStartCapture",
    "onVolumeChange",
    "onVolumeChangeCapture",
    "onWaiting",
    "onWaitingCapture",
    "onWheel",
    "onWheelCapture",
    "opacity",
    "open",
    "operator",
    "optimum",
    "order",
    "orient",
    "orientation",
    "origin",
    "overflow",
    "overlinePosition",
    "overlineThickness",
    "paintOrder",
    "panose1",
    "part",
    "path",
    "pathLength",
    "pattern",
    "patternContentUnits",
    "patternTransform",
    "patternUnits",
    "ping",
    "placeholder",
    "pointerEvents",
    "points",
    "pointsAtX",
    "pointsAtY",
    "pointsAtZ",
    "popover",
    "poster",
    "preload",
    "preserveAlpha",
    "preserveAspectRatio",
    "primitiveUnits",
    "profile",
    "property",
    "r",
    "radioGroup",
    "radius",
    "readOnly",
    "ref",
    "refX",
    "refY",
    "referrerPolicy",
    "rel",
    "rendering-intent",
    "repeatCount",
    "repeatDur",
    "required",
    "requiredExtensions",
    "requiredFeatures",
    "restart",
    "result",
    "results",
    "reversed",
    "role",
    "rotate",
    "rowSpan",
    "rows",
    "rx",
    "ry",
    "sandbox",
    "scale",
    "scope",
    "seamless",
    "security",
    "seed",
    "selected",
    "shape",
    "shapeRendering",
    "size",
    "sizes",
    "slope",
    "slot",
    "spacing",
    "span",
    "specularConstant",
    "specularExponent",
    "speed",
    "spellCheck",
    "spreadMethod",
    "src",
    "srcDoc",
    "srcLang",
    "srcSet",
    "start",
    "startOffset",
    "stdDeviation",
    "stemh",
    "stemv",
    "step",
    "stitchTiles",
    "stopColor",
    "stopOpacity",
    "strikethroughPosition",
    "strikethroughThickness",
    "string",
    "stroke",
    "strokeDasharray",
    "strokeDashoffset",
    "strokeLinecap",
    "strokeLinejoin",
    "strokeMiterlimit",
    "strokeOpacity",
    "strokeWidth",
    "style",
    "summary",
    "suppressContentEditableWarning",
    "suppressHydrationWarning",
    "surfaceScale",
    "systemLanguage",
    "tabIndex",
    "tableValues",
    "target",
    "targetX",
    "targetY",
    "textAnchor",
    "textDecoration",
    "textLength",
    "textRendering",
    "title",
    "to",
    "transform",
    "transformOrigin",
    "translate",
    "type",
    "u1",
    "u2",
    "underlinePosition",
    "underlineThickness",
    "unicode",
    "unicodeBidi",
    "unicodeRange",
    "unitsPerEm",
    "useMap",
    "vAlphabetic",
    "vHanging",
    "vIdeographic",
    "vMathematical",
    "value",
    "values",
    "vectorEffect",
    "version",
    "vertAdvY",
    "vertOriginX",
    "vertOriginY",
    "viewBox",
    "viewTarget",
    "visibility",
    "width",
    "widths",
    "wmode",
    "wordSpacing",
    "wrap",
    "writingMode",
    "x",
    "x1",
    "x2",
    "xChannelSelector",
    "xHeight",
    "xlinkActuate",
    "xlinkArcrole",
    "xlinkHref",
    "xlinkRole",
    "xlinkShow",
    "xlinkTitle",
    "xlinkType",
    "xmlBase",
    "xmlLang",
    "xmlSpace",
    "xmlns",
    "xmlnsXlink",
    "y",
    "y1",
    "y2",
    "yChannelSelector",
    "z",
    "zoomAndPan",
];

/// The names of [`DOM_PROPERTIES_NAMES`] that have a capital letter, by what they are in lower case.
static DOM_PROPERTIES_LOWER_MAP: [(&str, &str); 382] = [
    ("accentheight", "accentHeight"),
    ("acceptcharset", "acceptCharset"),
    ("accesskey", "accessKey"),
    ("alignmentbaseline", "alignmentBaseline"),
    ("arabicform", "arabicForm"),
    ("attributename", "attributeName"),
    ("attributetype", "attributeType"),
    ("autocapitalize", "autoCapitalize"),
    ("autocomplete", "autoComplete"),
    ("autocorrect", "autoCorrect"),
    ("autofocus", "autoFocus"),
    ("autopictureinpicture", "autoPictureInPicture"),
    ("autoplay", "autoPlay"),
    ("autosave", "autoSave"),
    ("basefrequency", "baseFrequency"),
    ("baselineshift", "baselineShift"),
    ("baseprofile", "baseProfile"),
    ("calcmode", "calcMode"),
    ("capheight", "capHeight"),
    ("cellpadding", "cellPadding"),
    ("cellspacing", "cellSpacing"),
    ("classid", "classID"),
    ("classname", "className"),
    ("clippath", "clipPath"),
    ("clippathunits", "clipPathUnits"),
    ("cliprule", "clipRule"),
    ("codebase", "codeBase"),
    ("colorinterpolation", "colorInterpolation"),
    ("colorinterpolationfilters", "colorInterpolationFilters"),
    ("colorprofile", "colorProfile"),
    ("colorrendering", "colorRendering"),
    ("colspan", "colSpan"),
    ("contenteditable", "contentEditable"),
    ("contentscripttype", "contentScriptType"),
    ("contentstyletype", "contentStyleType"),
    ("contextmenu", "contextMenu"),
    ("controlslist", "controlsList"),
    ("crossorigin", "crossOrigin"),
    ("dangerouslysetinnerhtml", "dangerouslySetInnerHTML"),
    ("datetime", "dateTime"),
    ("defaultchecked", "defaultChecked"),
    ("defaultvalue", "defaultValue"),
    ("diffuseconstant", "diffuseConstant"),
    ("disablepictureinpicture", "disablePictureInPicture"),
    ("disableremoteplayback", "disableRemotePlayback"),
    ("dominantbaseline", "dominantBaseline"),
    ("edgemode", "edgeMode"),
    ("enablebackground", "enableBackground"),
    ("enctype", "encType"),
    ("enterkeyhint", "enterKeyHint"),
    ("exportparts", "exportParts"),
    ("fillopacity", "fillOpacity"),
    ("fillrule", "fillRule"),
    ("filterres", "filterRes"),
    ("filterunits", "filterUnits"),
    ("floodcolor", "floodColor"),
    ("floodopacity", "floodOpacity"),
    ("fontfamily", "fontFamily"),
    ("fontsize", "fontSize"),
    ("fontsizeadjust", "fontSizeAdjust"),
    ("fontstretch", "fontStretch"),
    ("fontstyle", "fontStyle"),
    ("fontvariant", "fontVariant"),
    ("fontweight", "fontWeight"),
    ("formaction", "formAction"),
    ("formenctype", "formEncType"),
    ("formmethod", "formMethod"),
    ("formnovalidate", "formNoValidate"),
    ("formtarget", "formTarget"),
    ("frameborder", "frameBorder"),
    ("glyphname", "glyphName"),
    ("glyphorientationhorizontal", "glyphOrientationHorizontal"),
    ("glyphorientationvertical", "glyphOrientationVertical"),
    ("glyphref", "glyphRef"),
    ("gradienttransform", "gradientTransform"),
    ("gradientunits", "gradientUnits"),
    ("horizadvx", "horizAdvX"),
    ("horizoriginx", "horizOriginX"),
    ("htmlfor", "htmlFor"),
    ("httpequiv", "httpEquiv"),
    ("imagerendering", "imageRendering"),
    ("imagesizes", "imageSizes"),
    ("imagesrcset", "imageSrcSet"),
    ("inputmode", "inputMode"),
    ("ismap", "isMap"),
    ("itemid", "itemID"),
    ("itemprop", "itemProp"),
    ("itemref", "itemRef"),
    ("itemscope", "itemScope"),
    ("itemtype", "itemType"),
    ("kernelmatrix", "kernelMatrix"),
    ("kernelunitlength", "kernelUnitLength"),
    ("keyparams", "keyParams"),
    ("keypoints", "keyPoints"),
    ("keysplines", "keySplines"),
    ("keytimes", "keyTimes"),
    ("keytype", "keyType"),
    ("lengthadjust", "lengthAdjust"),
    ("letterspacing", "letterSpacing"),
    ("lightingcolor", "lightingColor"),
    ("limitingconeangle", "limitingConeAngle"),
    ("marginheight", "marginHeight"),
    ("marginwidth", "marginWidth"),
    ("markerend", "markerEnd"),
    ("markerheight", "markerHeight"),
    ("markermid", "markerMid"),
    ("markerstart", "markerStart"),
    ("markerunits", "markerUnits"),
    ("markerwidth", "markerWidth"),
    ("maskcontentunits", "maskContentUnits"),
    ("masktype", "maskType"),
    ("maskunits", "maskUnits"),
    ("maxlength", "maxLength"),
    ("mediagroup", "mediaGroup"),
    ("minlength", "minLength"),
    ("novalidate", "noValidate"),
    ("numoctaves", "numOctaves"),
    ("onabort", "onAbort"),
    ("onabortcapture", "onAbortCapture"),
    ("onanimationend", "onAnimationEnd"),
    ("onanimationendcapture", "onAnimationEndCapture"),
    ("onanimationiteration", "onAnimationIteration"),
    ("onanimationstart", "onAnimationStart"),
    ("onanimationstartcapture", "onAnimationStartCapture"),
    ("onauxclick", "onAuxClick"),
    ("onauxclickcapture", "onAuxClickCapture"),
    ("onbeforeinput", "onBeforeInput"),
    ("onbeforeinputcapture", "onBeforeInputCapture"),
    ("onbeforetoggle", "onBeforeToggle"),
    ("onblur", "onBlur"),
    ("onblurcapture", "onBlurCapture"),
    ("oncanplay", "onCanPlay"),
    ("oncanplaycapture", "onCanPlayCapture"),
    ("oncanplaythrough", "onCanPlayThrough"),
    ("oncanplaythroughcapture", "onCanPlayThroughCapture"),
    ("onchange", "onChange"),
    ("onchangecapture", "onChangeCapture"),
    ("onclick", "onClick"),
    ("onclickcapture", "onClickCapture"),
    ("oncompositionend", "onCompositionEnd"),
    ("oncompositionendcapture", "onCompositionEndCapture"),
    ("oncompositionstart", "onCompositionStart"),
    ("oncompositionstartcapture", "onCompositionStartCapture"),
    ("oncompositionupdate", "onCompositionUpdate"),
    ("oncompositionupdatecapture", "onCompositionUpdateCapture"),
    ("oncontextmenu", "onContextMenu"),
    ("oncontextmenucapture", "onContextMenuCapture"),
    ("oncopy", "onCopy"),
    ("oncopycapture", "onCopyCapture"),
    ("oncut", "onCut"),
    ("oncutcapture", "onCutCapture"),
    ("ondoubleclick", "onDoubleClick"),
    ("ondoubleclickcapture", "onDoubleClickCapture"),
    ("ondrag", "onDrag"),
    ("ondragcapture", "onDragCapture"),
    ("ondragend", "onDragEnd"),
    ("ondragendcapture", "onDragEndCapture"),
    ("ondragenter", "onDragEnter"),
    ("ondragentercapture", "onDragEnterCapture"),
    ("ondragexit", "onDragExit"),
    ("ondragexitcapture", "onDragExitCapture"),
    ("ondragleave", "onDragLeave"),
    ("ondragleavecapture", "onDragLeaveCapture"),
    ("ondragover", "onDragOver"),
    ("ondragovercapture", "onDragOverCapture"),
    ("ondragstart", "onDragStart"),
    ("ondragstartcapture", "onDragStartCapture"),
    ("ondrop", "onDrop"),
    ("ondropcapture", "onDropCapture"),
    ("ondurationchange", "onDurationChange"),
    ("ondurationchangecapture", "onDurationChangeCapture"),
    ("onemptied", "onEmptied"),
    ("onemptiedcapture", "onEmptiedCapture"),
    ("onencrypted", "onEncrypted"),
    ("onencryptedcapture", "onEncryptedCapture"),
    ("onended", "onEnded"),
    ("onendedcapture", "onEndedCapture"),
    ("onerror", "onError"),
    ("onerrorcapture", "onErrorCapture"),
    ("onfocus", "onFocus"),
    ("onfocuscapture", "onFocusCapture"),
    ("onfullscreenchange", "onFullscreenChange"),
    ("onfullscreenchangecapture", "onFullscreenChangeCapture"),
    ("onfullscreenerror", "onFullscreenError"),
    ("onfullscreenerrorcapture", "onFullscreenErrorCapture"),
    ("ongotpointercapturecapture", "onGotPointerCaptureCapture"),
    ("oninput", "onInput"),
    ("oninputcapture", "onInputCapture"),
    ("oninvalid", "onInvalid"),
    ("oninvalidcapture", "onInvalidCapture"),
    ("onkeydown", "onKeyDown"),
    ("onkeydowncapture", "onKeyDownCapture"),
    ("onkeypress", "onKeyPress"),
    ("onkeypresscapture", "onKeyPressCapture"),
    ("onkeyup", "onKeyUp"),
    ("onkeyupcapture", "onKeyUpCapture"),
    ("onload", "onLoad"),
    ("onloadcapture", "onLoadCapture"),
    ("onloadeddata", "onLoadedData"),
    ("onloadeddatacapture", "onLoadedDataCapture"),
    ("onloadedmetadata", "onLoadedMetadata"),
    ("onloadedmetadatacapture", "onLoadedMetadataCapture"),
    ("onloadstart", "onLoadStart"),
    ("onloadstartcapture", "onLoadStartCapture"),
    ("onlostpointercapture", "onLostPointerCapture"),
    ("onlostpointercapturecapture", "onLostPointerCaptureCapture"),
    ("onmousedown", "onMouseDown"),
    ("onmousedowncapture", "onMouseDownCapture"),
    ("onmouseenter", "onMouseEnter"),
    ("onmouseleave", "onMouseLeave"),
    ("onmousemove", "onMouseMove"),
    ("onmousemovecapture", "onMouseMoveCapture"),
    ("onmouseout", "onMouseOut"),
    ("onmouseoutcapture", "onMouseOutCapture"),
    ("onmouseover", "onMouseOver"),
    ("onmouseovercapture", "onMouseOverCapture"),
    ("onmouseup", "onMouseUp"),
    ("onmouseupcapture", "onMouseUpCapture"),
    ("onpaste", "onPaste"),
    ("onpastecapture", "onPasteCapture"),
    ("onpause", "onPause"),
    ("onpausecapture", "onPauseCapture"),
    ("onplay", "onPlay"),
    ("onplaycapture", "onPlayCapture"),
    ("onplaying", "onPlaying"),
    ("onplayingcapture", "onPlayingCapture"),
    ("onpointercancel", "onPointerCancel"),
    ("onpointercancelcapture", "onPointerCancelCapture"),
    ("onpointerdown", "onPointerDown"),
    ("onpointerdowncapture", "onPointerDownCapture"),
    ("onpointerenter", "onPointerEnter"),
    ("onpointerentercapture", "onPointerEnterCapture"),
    ("onpointerleave", "onPointerLeave"),
    ("onpointerleavecapture", "onPointerLeaveCapture"),
    ("onpointermove", "onPointerMove"),
    ("onpointermovecapture", "onPointerMoveCapture"),
    ("onpointerout", "onPointerOut"),
    ("onpointeroutcapture", "onPointerOutCapture"),
    ("onpointerover", "onPointerOver"),
    ("onpointerovercapture", "onPointerOverCapture"),
    ("onpointerup", "onPointerUp"),
    ("onpointerupcapture", "onPointerUpCapture"),
    ("onprogress", "onProgress"),
    ("onprogresscapture", "onProgressCapture"),
    ("onratechange", "onRateChange"),
    ("onratechangecapture", "onRateChangeCapture"),
    ("onreset", "onReset"),
    ("onresetcapture", "onResetCapture"),
    ("onresize", "onResize"),
    ("onscroll", "onScroll"),
    ("onscrollcapture", "onScrollCapture"),
    ("onscrollend", "onScrollEnd"),
    ("onscrollendcapture", "onScrollEndCapture"),
    ("onseeked", "onSeeked"),
    ("onseekedcapture", "onSeekedCapture"),
    ("onseeking", "onSeeking"),
    ("onseekingcapture", "onSeekingCapture"),
    ("onselect", "onSelect"),
    ("onselectcapture", "onSelectCapture"),
    ("onstalled", "onStalled"),
    ("onstalledcapture", "onStalledCapture"),
    ("onsubmit", "onSubmit"),
    ("onsubmitcapture", "onSubmitCapture"),
    ("onsuspend", "onSuspend"),
    ("onsuspendcapture", "onSuspendCapture"),
    ("ontimeupdate", "onTimeUpdate"),
    ("ontimeupdatecapture", "onTimeUpdateCapture"),
    ("ontoggle", "onToggle"),
    ("ontouchcancel", "onTouchCancel"),
    ("ontouchcancelcapture", "onTouchCancelCapture"),
    ("ontouchend", "onTouchEnd"),
    ("ontouchendcapture", "onTouchEndCapture"),
    ("ontouchmove", "onTouchMove"),
    ("ontouchmovecapture", "onTouchMoveCapture"),
    ("ontouchstart", "onTouchStart"),
    ("ontouchstartcapture", "onTouchStartCapture"),
    ("ontransitioncancel", "onTransitionCancel"),
    ("ontransitioncancelcapture", "onTransitionCancelCapture"),
    ("ontransitionend", "onTransitionEnd"),
    ("ontransitionendcapture", "onTransitionEndCapture"),
    ("ontransitionrun", "onTransitionRun"),
    ("ontransitionruncapture", "onTransitionRunCapture"),
    ("ontransitionstart", "onTransitionStart"),
    ("ontransitionstartcapture", "onTransitionStartCapture"),
    ("onvolumechange", "onVolumeChange"),
    ("onvolumechangecapture", "onVolumeChangeCapture"),
    ("onwaiting", "onWaiting"),
    ("onwaitingcapture", "onWaitingCapture"),
    ("onwheel", "onWheel"),
    ("onwheelcapture", "onWheelCapture"),
    ("overlineposition", "overlinePosition"),
    ("overlinethickness", "overlineThickness"),
    ("paintorder", "paintOrder"),
    ("pathlength", "pathLength"),
    ("patterncontentunits", "patternContentUnits"),
    ("patterntransform", "patternTransform"),
    ("patternunits", "patternUnits"),
    ("pointerevents", "pointerEvents"),
    ("pointsatx", "pointsAtX"),
    ("pointsaty", "pointsAtY"),
    ("pointsatz", "pointsAtZ"),
    ("preservealpha", "preserveAlpha"),
    ("preserveaspectratio", "preserveAspectRatio"),
    ("primitiveunits", "primitiveUnits"),
    ("radiogroup", "radioGroup"),
    ("readonly", "readOnly"),
    ("referrerpolicy", "referrerPolicy"),
    ("refx", "refX"),
    ("refy", "refY"),
    ("repeatcount", "repeatCount"),
    ("repeatdur", "repeatDur"),
    ("requiredextensions", "requiredExtensions"),
    ("requiredfeatures", "requiredFeatures"),
    ("rowspan", "rowSpan"),
    ("shaperendering", "shapeRendering"),
    ("specularconstant", "specularConstant"),
    ("specularexponent", "specularExponent"),
    ("spellcheck", "spellCheck"),
    ("spreadmethod", "spreadMethod"),
    ("srcdoc", "srcDoc"),
    ("srclang", "srcLang"),
    ("srcset", "srcSet"),
    ("startoffset", "startOffset"),
    ("stddeviation", "stdDeviation"),
    ("stitchtiles", "stitchTiles"),
    ("stopcolor", "stopColor"),
    ("stopopacity", "stopOpacity"),
    ("strikethroughposition", "strikethroughPosition"),
    ("strikethroughthickness", "strikethroughThickness"),
    ("strokedasharray", "strokeDasharray"),
    ("strokedashoffset", "strokeDashoffset"),
    ("strokelinecap", "strokeLinecap"),
    ("strokelinejoin", "strokeLinejoin"),
    ("strokemiterlimit", "strokeMiterlimit"),
    ("strokeopacity", "strokeOpacity"),
    ("strokewidth", "strokeWidth"),
    ("suppresscontenteditablewarning", "suppressContentEditableWarning"),
    ("suppresshydrationwarning", "suppressHydrationWarning"),
    ("surfacescale", "surfaceScale"),
    ("systemlanguage", "systemLanguage"),
    ("tabindex", "tabIndex"),
    ("tablevalues", "tableValues"),
    ("targetx", "targetX"),
    ("targety", "targetY"),
    ("textanchor", "textAnchor"),
    ("textdecoration", "textDecoration"),
    ("textlength", "textLength"),
    ("textrendering", "textRendering"),
    ("transformorigin", "transformOrigin"),
    ("underlineposition", "underlinePosition"),
    ("underlinethickness", "underlineThickness"),
    ("unicodebidi", "unicodeBidi"),
    ("unicoderange", "unicodeRange"),
    ("unitsperem", "unitsPerEm"),
    ("usemap", "useMap"),
    ("valphabetic", "vAlphabetic"),
    ("vectoreffect", "vectorEffect"),
    ("vertadvy", "vertAdvY"),
    ("vertoriginx", "vertOriginX"),
    ("vertoriginy", "vertOriginY"),
    ("vhanging", "vHanging"),
    ("videographic", "vIdeographic"),
    ("viewbox", "viewBox"),
    ("viewtarget", "viewTarget"),
    ("vmathematical", "vMathematical"),
    ("wordspacing", "wordSpacing"),
    ("writingmode", "writingMode"),
    ("xchannelselector", "xChannelSelector"),
    ("xheight", "xHeight"),
    ("xlinkactuate", "xlinkActuate"),
    ("xlinkarcrole", "xlinkArcrole"),
    ("xlinkhref", "xlinkHref"),
    ("xlinkrole", "xlinkRole"),
    ("xlinkshow", "xlinkShow"),
    ("xlinktitle", "xlinkTitle"),
    ("xlinktype", "xlinkType"),
    ("xmlbase", "xmlBase"),
    ("xmllang", "xmlLang"),
    ("xmlnsxlink", "xmlnsXlink"),
    ("xmlspace", "xmlSpace"),
    ("ychannelselector", "yChannelSelector"),
    ("zoomandpan", "zoomAndPan"),
];

static DOM_ATTRIBUTES_TO_CAMEL: [(&str, &str); 92] = [
    ("accent-height", "accentHeight"),
    ("accept-charset", "acceptCharset"),
    ("alignment-baseline", "alignmentBaseline"),
    ("arabic-form", "arabicForm"),
    ("baseline-shift", "baselineShift"),
    ("cap-height", "capHeight"),
    ("class", "className"),
    ("clip-path", "clipPath"),
    ("clip-rule", "clipRule"),
    ("color-interpolation", "colorInterpolation"),
    ("color-interpolation-filters", "colorInterpolationFilters"),
    ("color-profile", "colorProfile"),
    ("color-rendering", "colorRendering"),
    ("crossorigin", "crossOrigin"),
    ("dominant-baseline", "dominantBaseline"),
    ("enable-background", "enableBackground"),
    ("fetchpriority", "fetchPriority"),
    ("fill-opacity", "fillOpacity"),
    ("fill-rule", "fillRule"),
    ("flood-color", "floodColor"),
    ("flood-opacity", "floodOpacity"),
    ("font-family", "fontFamily"),
    ("font-size", "fontSize"),
    ("font-size-adjust", "fontSizeAdjust"),
    ("font-stretch", "fontStretch"),
    ("font-style", "fontStyle"),
    ("font-variant", "fontVariant"),
    ("font-weight", "fontWeight"),
    ("for", "htmlFor"),
    ("glyph-name", "glyphName"),
    ("glyph-orientation-horizontal", "glyphOrientationHorizontal"),
    ("glyph-orientation-vertical", "glyphOrientationVertical"),
    ("horiz-adv-x", "horizAdvX"),
    ("horiz-origin-x", "horizOriginX"),
    ("http-equiv", "httpEquiv"),
    ("image-rendering", "imageRendering"),
    ("letter-spacing", "letterSpacing"),
    ("lighting-color", "lightingColor"),
    ("marker-end", "markerEnd"),
    ("marker-mid", "markerMid"),
    ("marker-start", "markerStart"),
    ("mask-type", "maskType"),
    ("nomodule", "noModule"),
    ("overline-position", "overlinePosition"),
    ("overline-thickness", "overlineThickness"),
    ("paint-order", "paintOrder"),
    ("panose-1", "panose1"),
    ("pointer-events", "pointerEvents"),
    ("popovertarget", "popoverTarget"),
    ("popovertargetaction", "popoverTargetAction"),
    ("rendering-intent", "renderingIntent"),
    ("shape-rendering", "shapeRendering"),
    ("stop-color", "stopColor"),
    ("stop-opacity", "stopOpacity"),
    ("strikethrough-position", "strikethroughPosition"),
    ("strikethrough-thickness", "strikethroughThickness"),
    ("stroke-dasharray", "strokeDasharray"),
    ("stroke-dashoffset", "strokeDashoffset"),
    ("stroke-linecap", "strokeLinecap"),
    ("stroke-linejoin", "strokeLinejoin"),
    ("stroke-miterlimit", "strokeMiterlimit"),
    ("stroke-opacity", "strokeOpacity"),
    ("stroke-width", "strokeWidth"),
    ("text-anchor", "textAnchor"),
    ("text-decoration", "textDecoration"),
    ("text-rendering", "textRendering"),
    ("underline-position", "underlinePosition"),
    ("underline-thickness", "underlineThickness"),
    ("unicode-bidi", "unicodeBidi"),
    ("unicode-range", "unicodeRange"),
    ("units-per-em", "unitsPerEm"),
    ("v-alphabetic", "vAlphabetic"),
    ("v-hanging", "vHanging"),
    ("v-ideographic", "vIdeographic"),
    ("v-mathematical", "vMathematical"),
    ("vector-effect", "vectorEffect"),
    ("vert-adv-y", "vertAdvY"),
    ("vert-origin-x", "vertOriginX"),
    ("vert-origin-y", "vertOriginY"),
    ("word-spacing", "wordSpacing"),
    ("writing-mode", "writingMode"),
    ("x-height", "xHeight"),
    ("xlink:actuate", "xlinkActuate"),
    ("xlink:arcrole", "xlinkArcrole"),
    ("xlink:href", "xlinkHref"),
    ("xlink:role", "xlinkRole"),
    ("xlink:show", "xlinkShow"),
    ("xlink:title", "xlinkTitle"),
    ("xlink:type", "xlinkType"),
    ("xml:base", "xmlBase"),
    ("xml:lang", "xmlLang"),
    ("xml:space", "xmlSpace"),
];
const DOM_PROPERTIES_IGNORE_CASE: [&str; 5] =
    ["charset", "allowFullScreen", "webkitAllowFullScreen", "mozAllowFullScreen", "webkitDirectory"];

/// What `table`, which is sorted, has for `key`.
fn get<T: Copy>(table: &[(&str, T)], key: &[u8]) -> Option<T> {
    let at = table.binary_search_by(|it| it.0.as_bytes().cmp(key)).ok()?;
    table.get(at).map(|it| it.1)
}

/// The name of [`DOM_PROPERTIES_NAMES`] that is `name` but for the case of its letters.
fn dom_property_in_other_case(name: &[u8]) -> Option<&'static str> {
    let lower = cow_to_ascii_lowercase(name);
    get(&DOM_PROPERTIES_LOWER_MAP, &lower).or_else(|| {
        let at = DOM_PROPERTIES_NAMES.binary_search_by(|it| it.as_bytes().cmp(&lower)).ok()?;
        DOM_PROPERTIES_NAMES.get(at).copied()
    })
}

/// `data-a`, `data-a-b`. Not `data-xml..` in any case, not `data-a:b`.
fn is_valid_data_attr(name: &[u8]) -> bool {
    name.strip_prefix(b"data-").is_some_and(|data_name| {
        !data_name.is_empty()
            && !data_name.get(..3).is_some_and(|it| it.eq_ignore_ascii_case(b"xml"))
            && !strings::contains_char(data_name, b':')
    })
}

/// It starts with a small letter of ASCII and has no hyphen.
fn matches_html_tag_conventions(tag: &[u8]) -> bool {
    tag.first().is_none_or(u8::is_ascii_lowercase)
        && !tag.get(1..).is_some_and(|rest| strings::contains_char(rest, b'-'))
}

fn normalize_attribute_case(name: &[u8]) -> &[u8] {
    DOM_PROPERTIES_IGNORE_CASE.iter().map(|it| it.as_bytes()).find(|it| it.eq_ignore_ascii_case(name)).unwrap_or(name)
}

fn any_char(name: &[u8], is_it: impl Fn(char) -> bool) -> bool {
    strings::wtf8_codepoints(name).filter_map(|it| char::from_u32(it.1)).any(is_it)
}

impl Rule for NoUnknownProperty {
    const META: Meta = Meta::oxlint(Plugin::React, "no-unknown-property", Kind::Suggestion).has_suggestions();
    type State<'a> = ();

    fn new(options: &Options) -> Self {
        let options = options.object(0);
        NoUnknownProperty {
            ignore: options.strings("ignore").into_iter().map(|it| it.as_bytes().into()).collect(),
            require_data_lowercase: options.bool_or("requireDataLowercase", false),
        }
    }

    fn register<'a>(&self, on: &mut Listeners<'a, Self>, file: &'a File<'a>) {
        if is_jsx(file) {
            on.exprs([ExprTag::Jsx], check);
        }
    }
}

fn check<'a>(rule: &NoUnknownProperty, e: Expr<'a>, cx: &mut Cx<'a, NoUnknownProperty>) {
    let ExprKind::Jsx(jsx) = e.kind() else {
        return;
    };
    let attributes = jsx.attrs();
    if attributes.is_empty() {
        return;
    }
    let Some(el_type) = get_identifier_name(jsx).map(Name::bytes) else {
        return;
    };
    // The name of a component. `fbt` and `fbs` are something else altogether.
    let starts_with_lowercase = match el_type.first() {
        Some(first) if first.is_ascii() => first.is_ascii_lowercase(),
        _ => {
            strings::contains_char(el_type, b'-')
                && strings::wtf8_first_codepoint(el_type).and_then(char::from_u32).is_some_and(char::is_lowercase)
        }
    };
    if !starts_with_lowercase || matches!(el_type, b"fbt" | b"fbs") {
        return;
    }
    let names = || attributes.iter().filter_map(Prop::key).filter_map(|key| Some((key, key.name()?.bytes())));
    let is_valid_html_tag = matches_html_tag_conventions(el_type) && names().all(|it| it.1 != b"is");
    for (key, actual_name) in names() {
        if rule.ignore.iter().any(|it| **it == *actual_name) {
            continue;
        }
        if is_valid_data_attr(actual_name) {
            if rule.require_data_lowercase && any_char(actual_name, char::is_uppercase) {
                cx.report(key.span(cx.file()), DATA_LOWERCASE_REQUIRED)
                    .help_with(|| format!("Use '{}' instead", bstr::BStr::new(&actual_name.to_ascii_lowercase())));
            }
            continue;
        }
        if !is_valid_html_tag || is_valid_aria_property(actual_name) {
            continue;
        }
        let name = normalize_attribute_case(actual_name);
        if let Some(tags) = get(&ATTRIBUTE_TAGS_MAP, name) {
            if !tags.iter().any(|it| it.as_bytes() == el_type) {
                cx.report(key.span(cx.file()), INVALID_PROP_ON_TAG).help_with(|| {
                    let prop = bstr::BStr::new(actual_name);
                    format!("Property '{prop}' is only allowed on: {}", tags.join(", "))
                });
            }
            continue;
        }
        if contains_name(&DOM_PROPERTIES_NAMES, name) {
            continue;
        }
        let span = key.span(cx.file());
        let report = cx.report(span, UNKNOWN_PROP);
        match dom_property_in_other_case(name).or_else(|| get(&DOM_ATTRIBUTES_TO_CAMEL, name)) {
            Some(prop) => report
                .help_with(|| format!("Use '{prop}' instead"))
                .suggest_with(USE_STANDARD_NAME, &[("x1", prop.as_bytes())], |fixer| fixer.replace(span, prop)),
            None => report.help("Remove unknown property"),
        };
    }
}
