[package]
name = "bun_sema"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
bun_core.workspace = true
bun_paths.workspace = true
bun_semver.workspace = true
bun_threading.workspace = true
bstr.workspace = true
smallvec.workspace = true
bitflags.workspace = true

[lints]
