import { define } from "../../codegen/class-definitions";

// [jsName, arity] — arity is the minimum arg count the Rust impl enforces
// (see js_valkey_functions.rs): cmd_noargs→0, cmd_key/cmd_key_varargs→1,
// cmd_key_value→2, cmd_key_value_value2→3, cmd_strings_varargs→0.
const commands: ReadonlyArray<readonly [name: string, length: number]> = [
  ["get", 1],
  ["getBuffer", 1],
  ["set", 2],
  ["del", 1],
  ["incr", 1],
  ["incrby", 2],
  ["incrbyfloat", 2],
  ["decr", 1],
  ["decrby", 2],
  ["exists", 1],
  ["expire", 2],
  ["expireat", 2],
  ["pexpire", 2],
  ["ttl", 1],
  ["hmset", 2],
  ["hset", 2],
  ["hsetnx", 3],
  ["hget", 2],
  ["hmget", 2],
  ["hdel", 2],
  ["hexists", 2],
  ["hrandfield", 1],
  ["hscan", 2],
  ["hgetdel", 2],
  ["hgetex", 2],
  ["hsetex", 3],
  ["hexpire", 3],
  ["hexpireat", 3],
  ["hexpiretime", 2],
  ["hpersist", 2],
  ["hpexpire", 3],
  ["hpexpireat", 3],
  ["hpexpiretime", 2],
  ["hpttl", 2],
  ["httl", 2],
  ["sismember", 2],
  ["sadd", 2],
  ["srem", 2],
  ["smembers", 1],
  ["srandmember", 1],
  ["spop", 1],
  ["hincrby", 3],
  ["hincrbyfloat", 3],
  ["bitcount", 1],
  ["blmove", 5],
  ["blmpop", 3],
  ["blpop", 2],
  ["brpop", 2],
  ["brpoplpush", 3],
  ["getbit", 2],
  ["setbit", 3],
  ["getrange", 3],
  ["setrange", 3],
  ["dump", 1],
  ["expiretime", 1],
  ["getdel", 1],
  ["getex", 0],
  ["hgetall", 1],
  ["hkeys", 1],
  ["hlen", 1],
  ["hvals", 1],
  ["keys", 1],
  ["lindex", 2],
  ["linsert", 4],
  ["llen", 1],
  ["lmove", 4],
  ["lmpop", 2],
  ["lpop", 1],
  ["lpos", 2],
  ["lrange", 3],
  ["lrem", 3],
  ["lset", 3],
  ["ltrim", 3],
  ["persist", 1],
  ["pexpireat", 2],
  ["pexpiretime", 1],
  ["pttl", 1],
  ["randomkey", 0],
  ["rpop", 1],
  ["rpoplpush", 2],
  ["scan", 0],
  ["scard", 1],
  ["sdiff", 1],
  ["sdiffstore", 2],
  ["sinter", 1],
  ["sintercard", 1],
  ["sinterstore", 2],
  ["smismember", 2],
  ["sscan", 2],
  ["strlen", 1],
  ["sunion", 1],
  ["sunionstore", 2],
  ["type", 1],
  ["zcard", 1],
  ["zcount", 3],
  ["zlexcount", 3],
  ["zpopmax", 1],
  ["zpopmin", 1],
  ["zrandmember", 1],
  ["zrange", 3],
  ["zrangebylex", 3],
  ["zrangebyscore", 3],
  ["zrangestore", 4],
  ["zrem", 2],
  ["zremrangebylex", 3],
  ["zremrangebyrank", 3],
  ["zremrangebyscore", 3],
  ["zrevrange", 3],
  ["zrevrangebylex", 3],
  ["zrevrangebyscore", 3],
  ["append", 2],
  ["getset", 2],
  ["lpush", 0],
  ["lpushx", 0],
  ["pfadd", 2],
  ["rpush", 0],
  ["rpushx", 0],
  ["setnx", 2],
  ["setex", 3],
  ["psetex", 3],
  ["zscore", 2],
  ["zincrby", 3],
  ["zmscore", 0],
  ["zadd", 3],
  ["zscan", 2],
  ["zdiff", 1],
  ["zdiffstore", 2],
  ["zinter", 2],
  ["zintercard", 1],
  ["zinterstore", 3],
  ["zunion", 2],
  ["zunionstore", 3],
  ["zmpop", 2],
  ["bzmpop", 3],
  ["bzpopmin", 2],
  ["bzpopmax", 2],
  ["mget", 1],
  ["mset", 0],
  ["msetnx", 0],
  ["ping", 0],
  ["publish", 2],
  ["script", 0],
  ["select", 0],
  ["spublish", 2],
  ["smove", 3],
  ["substr", 3],
  ["hstrlen", 2],
  ["zrank", 1],
  ["zrevrank", 1],
  ["subscribe", 2],
  ["psubscribe", 0],
  ["unsubscribe", 0],
  ["punsubscribe", 0],
  ["pubsub", 0],
  ["copy", 0],
  ["unlink", 1],
  ["touch", 1],
  ["rename", 2],
  ["renamenx", 2],
];

const commandProto = Object.fromEntries(commands.map(([name, length]) => [name, { fn: name, length }]));

export default [
  define({
    name: "RedisClient",
    sharedThis: true,
    construct: true,
    constructNeedsThis: true,
    call: false,
    finalize: true,
    configurable: false,
    JSType: "0b11101110",
    memoryCost: true,
    proto: {
      // Lifecycle / accessors
      connected: {
        getter: "getConnected",
      },
      onconnect: {
        getter: "getOnConnect",
        setter: "setOnConnect",
        this: true,
      },
      onclose: {
        getter: "getOnClose",
        setter: "setOnClose",
        this: true,
      },
      bufferedAmount: {
        getter: "getBufferedAmount",
      },
      connect: {
        fn: "jsConnect",
        length: 0,
      },
      close: {
        fn: "jsDisconnect",
        length: 0,
      },
      send: {
        fn: "jsSend",
        length: 2,
      },
      duplicate: {
        fn: "duplicate",
        length: 0,
      },
      // Valkey commands
      ...commandProto,
    },
    values: ["onconnect", "onclose", "connectionPromise", "hello", "subscriptionCallbackMap"],
  }),
];
