// usage: bun wholetest.ts <tree>: the body of the test of the whole corpus, step by step: CPU time of the main thread.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
const tree = process.argv[2];
const H = `${tree}/test/cli/lint/conformance`;
const cpu = () => Number(readFileSync("/proc/thread-self/schedstat", "latin1").split(" ")[0]) / 1e6;
let t = cpu();
const out: string[] = [];
const step = (label: string) => { const n = cpu(); out.push(`${String(Math.round(n - t)).padStart(5)} ms ${label}`); t = cpu(); };
const runner = await import(`${H}/runner/index.ts`);
const { compareStrings } = await import(`${H}/runner/gostrings.ts`);
step("imports");
const corpus = runner.openCorpus(`${H}/corpus`);
corpus.enumerateCase("compiler/2dArrays.ts");
step("openCorpus and the first case (the three lists and the names of the baselines)");
const instances = corpus.enumerateInstances();
step(`corpus.enumerateInstances() (${instances.length})`);
const listLines = readFileSync(`${H}/fixtures/instances.tsv`, "utf8").split("\n").slice(0, -1);
const lineOf = (i: any) => (i.status === "run" ? `${i.name}\t${i.oracle.class}` : `${i.name}\tskipped\t${i.skipReason}`);
const got = new Set(instances.map(lineOf));
const want = new Set(listLines);
const a = [...got].filter(l => !want.has(l)).length + [...want].filter(l => !got.has(l)).length;
step(`the lines against the list (${a} differ)`);
const count = (f: (i: any) => boolean) => instances.filter(f).length;
const run = (i: any) => i.status === "run";
const caseBaseName = (n: string) => { const m = /^(.*)\(([^()]*)\)(\.tsx?)$/s.exec(n); return m === null ? n : m[1] + m[3]; };
const suite = (s: string) => { const of = (f: (i: any) => boolean) => count(i => i.suite === s && f(i)); return [of(() => true), of(run), of(i => !run(i)), of(i => run(i) && i.oracle.class === "E"), of(i => run(i) && i.oracle.class === "C")]; };
const c = [count(run), count(i => !run(i)), count(i => run(i) && i.oracle.class === "E"), count(i => run(i) && i.oracle.class === "C"), new Set(instances.map((i: any) => caseBaseName(i.name))).size, suite("compiler"), suite("conformance"), count(i => run(i) && i.accepted), count(i => run(i) && i.triaged), count(i => run(i) && i.oracle.source === "typescript-go"), count(i => run(i) && i.oracle.source === "typescript")];
step(`the counts (${JSON.stringify(c)})`);
const goName = (name: string) => { const m = /^(.*)\(([^()]*)\)(\.tsx?)$/s.exec(name); return m === null ? name : `${m[1]}${m[3]}_${m[2]}`; };
const sha256 = (text: string) => createHash("sha256").update(text).digest("hex");
const subtests = instances.map((i: any) => `${run(i) ? "PASS" : "SKIP"}\t${goName(i.name)}`).sort((x: string, y: string) => compareStrings(x.slice(5), y.slice(5))).map((l: string) => l + "\n").join("");
const reasons = instances.filter((i: any) => !run(i)).map((i: any) => `${goName(i.name)}\t${i.skipReason}`).sort(compareStrings).map((l: string) => l + "\n").join("");
step(`the digests (${sha256(subtests).slice(0, 8)} ${sha256(reasons).slice(0, 8)})`);
console.log(out.join("\n"));
