// A project for each way in which oxlint's port of a rule differs from the plugin that it is a port of, and some for what is the same.

export interface Project {
  name: string;
  about: string;
  config: object;
  files: Record<string, string>;
  /** It is linted with `--type-aware`. oxlint finds tsgolint through OXLINT_TSGOLINT_PATH. */
  typed?: boolean;
}

const rules = (plugins: string[], rules: object) => ({ plugins, categories: { correctness: "off" }, rules });
const lines = (...lines: string[]) => lines.join("\n") + "\n";
const hooks = rules(["react"], { "react-hooks/rules-of-hooks": "error", "react-hooks/exhaustive-deps": "warn" });
const unused = rules(["typescript"], { "no-unused-vars": "error" });
const noCycle = (...options: object[]) => rules(["import"], { "import/no-cycle": ["warn", ...options] });

/** Two modules that import each other, the first with `first` and the second with `import { a } from "./a"`. */
const pair = (first: string, b = "b.ts", second = `import { a } from "./a";\nexport const b = a;\nexport type B = number;\n`) => ({
  "a.ts": `${first}\nexport const a = 1;\n`,
  [b]: second,
});

export const projects: Project[] = [
  {
    name: "no-cycle/place",
    about: "the specifier is reported, once for each specifier, where it is first",
    config: noCycle(),
    files: pair(`import { b } from "./b";\nimport { b as c } from "./b";\nimport { b as d } from "./b.ts";`),
  },
  {
    name: "no-cycle/every-import",
    about: "each import of a file is searched afresh",
    config: noCycle(),
    files: {
      "a.ts": `import { b } from "./b";\nimport { c } from "./c";\nexport const a = [b, c];\n`,
      "b.ts": `import { c } from "./c";\nexport const b = c;\n`,
      "c.ts": `import { a } from "./a";\nexport const c = a;\n`,
    },
  },
  {
    name: "no-cycle/dynamic-import",
    about: "Flavor::ignores_dynamic_imports",
    config: noCycle(),
    files: pair(`export const load = () => import("./b");`),
  },
  {
    name: "no-cycle/tsx-for-js",
    about: "Flavor::resolves_as_node: ./b.js is not ./b.tsx",
    config: noCycle(),
    files: pair(`import { b } from "./b.js";`, "b.tsx"),
  },
  {
    name: "no-cycle/ts-for-js",
    about: "Flavor::resolves_as_node: ./b.js is ./b.ts",
    config: noCycle(),
    files: pair(`import { b } from "./b.js";`),
  },
  {
    name: "no-cycle/tsx-for-jsx",
    about: "Flavor::resolves_as_node: ./b.jsx is not ./b.tsx",
    config: noCycle(),
    files: pair(`import { b } from "./b.jsx";`, "b.tsx"),
  },
  {
    name: "no-cycle/declaration-file",
    about: "Flavor::resolves_as_node: ./b is not ./b.d.ts",
    config: noCycle(),
    files: pair(`import { b } from "./b";`, "b.d.ts", `import { a } from "./a";\nexport declare const b: typeof a;\n`),
  },
  {
    name: "no-cycle/js-before-ts",
    about: "Flavor::resolves_as_node: ./b is ./b.js where there is a ./b.ts too",
    config: noCycle(),
    files: { ...pair(`import { b } from "./b";`), "b.js": "export const b = 1;\n" },
  },
  {
    name: "no-cycle/index",
    about: "a directory",
    config: noCycle(),
    files: pair(`import { b } from "./dir";`, "dir/index.tsx", `import { a } from "../a";\nexport const b = a;\n`),
  },
  {
    name: "no-cycle/paths",
    about: "paths and baseUrl of a tsconfig.json",
    config: noCycle(),
    files: {
      "tsconfig.json": JSON.stringify({ compilerOptions: { baseUrl: ".", paths: { "@/*": ["./src/*"] } } }),
      "src/a.ts": `import { b } from "@/b";\nexport const a = b;\n`,
      "src/b.ts": `import { a } from "src/a";\nexport const b = a;\n`,
    },
  },
  {
    name: "no-cycle/export-type-from",
    about: "export type { B } from is an import of types",
    config: noCycle(),
    files: pair(`export type { B } from "./b";`),
  },
  {
    name: "no-cycle/export-inline-type-from",
    about: "export { type B } from is an import of types",
    config: noCycle(),
    files: pair(`export { type B } from "./b";`),
  },
  {
    name: "no-cycle/export-type-star",
    about: "export type * from has no names, so it is followed",
    config: noCycle(),
    files: pair(`export type * from "./b";`),
  },
  {
    name: "no-cycle/export-type-star-as",
    about: "export type * as N from is an import of types",
    config: noCycle(),
    files: pair(`export type * as N from "./b";`),
  },
  {
    name: "no-cycle/side-effect",
    about: "import \"./b\" is followed, in the file that is linted too",
    config: noCycle(),
    files: pair(`import "./b";`, "b.ts", `import "./a";\n`),
  },
  {
    name: "no-cycle/no-names",
    about: "import {} from is followed",
    config: noCycle(),
    files: pair(`import {} from "./b";`),
  },
  {
    name: "no-cycle/types-and-star",
    about: "the statements with the same specifier count together: import type and export * are an import of types",
    config: noCycle(),
    files: pair(`import type { B } from "./b";\nexport * from "./b";\nexport type C = B;`),
  },
  {
    name: "no-cycle/types-and-values",
    about: "import type and import of a value with the same specifier",
    config: noCycle(),
    files: pair(`import type { B } from "./b";\nimport { b } from "./b";\nexport type C = [B, typeof b];`),
  },
  {
    name: "no-cycle/inline-types",
    about: "import { type B } and import { type B, b }",
    config: noCycle(),
    files: {
      ...pair(`import { type B } from "./b";\nimport { type C, c } from "./c";\nexport type D = [B, C, typeof c];`),
      "c.ts": `import { a } from "./a";\nexport const c = a;\nexport type C = number;\n`,
    },
  },
  {
    name: "no-cycle/ignore-types-off",
    about: "ignoreTypes: false",
    config: noCycle({ ignoreTypes: false }),
    files: pair(`import type { B } from "./b";\nexport type C = B;`),
  },
  {
    name: "no-cycle/self",
    about: "Flavor::counts_self_imports, and oxlint_allows_self_reference",
    config: noCycle(),
    files: {
      "a.ts": `import { a as x } from "./a";\nexport const a = x;\n`,
      "b.ts": `export * from "./b";\n`,
      "c.ts": `export * as C from "./c";\nexport const c = 1;\n`,
      "d.ts": `export { d as e } from "./d";\nexport const d = 1;\n`,
      "e.ts": `import { e as f } from "./e";\nexport { f };\nexport const e = 1;\n`,
      "f.ts": `import * as f from "./f";\nexport { f };\n`,
      "g.ts": `import type { G } from "./g";\nexport type G = number;\nexport type H = G;\n`,
      "h.ts": `import "./h";\n`,
    },
  },
  {
    name: "no-cycle/require",
    about: "require and import = require are not imports",
    config: noCycle(),
    files: {
      "a.js": `const b = require("./b");\nmodule.exports = b;\n`,
      "b.js": `const a = require("./a");\nmodule.exports = a;\n`,
      "c.ts": `import d = require("./d");\nexport const c = d;\n`,
      "d.ts": `import { c } from "./c";\nexport const d = c;\n`,
    },
  },
  {
    name: "no-cycle/syntax-error",
    about: "nothing is known of a file that cannot be parsed",
    config: noCycle(),
    files: {
      "a.ts": `import { b } from "./b";\nexport const a = b;\n`,
      "b.ts": `import { c } from "./c";\nexport const b = c;\nconst = ;\n`,
      "c.ts": `import { a } from "./a";\nexport const c = a;\n`,
    },
  },
  {
    name: "no-cycle/import-type-in-a-type",
    about: "import(\"./b\").B in a type is not an import",
    config: noCycle(),
    files: pair(`export type T = import("./b").B;`),
  },
  ...[1, 2, 3].map(maxDepth => ({
    name: `no-cycle/max-depth-${maxDepth}`,
    about: "oxlint_finds_within: depth first by the specifiers, and the search ends where it is too deep for the first time",
    config: noCycle({ maxDepth }),
    files: {
      "a.ts": `import { b } from "./b";\nimport { e } from "./e";\nexport const a = [b, e];\n`,
      "b.ts": `import { c } from "./c";\nimport { z } from "./z";\nexport const b = [c, z];\n`,
      "c.ts": `import { d } from "./d";\nexport const c = d;\n`,
      "d.ts": `import { a } from "./a";\nexport const d = a;\n`,
      "e.ts": `import { a } from "./a";\nexport const e = a;\n`,
      "z.ts": `import { a } from "./a";\nexport const z = a;\n`,
    },
  })),
  {
    name: "no-cycle/comments",
    about: "comments that disable the rule",
    config: noCycle(),
    files: pair(`// oxlint-disable-next-line import/no-cycle\nimport { b } from "./b";\n// eslint-disable-next-line import/no-cycle\nimport { b as c } from "./b.ts";`),
  },
  {
    name: "no-cycle/many-files",
    about: "far more files than threads, each directory with a tsconfig.json that includes files: nothing waits for a thread that waits",
    config: noCycle(),
    files: Object.fromEntries(
      Array.from({ length: 40 }, (_, directory) => [
        [`d${directory}/tsconfig.json`, JSON.stringify({ compilerOptions: { paths: { "~/*": ["./*"] } }, include: ["**/*"] })],
        ...Array.from({ length: 10 }, (_, file) => [
          `d${directory}/f${file}.ts`,
          `import { x as next } from "${file < 9 ? `~/f${file + 1}` : `../d${(directory + 1) % 40}/f0`}";\nexport const x = next;\n`,
        ]),
      ]).flat(),
    ),
  },
  {
    name: "rules-of-hooks/loop-in-callback",
    about: "no loops and conditions are looked for in a function that is passed to a call outside a component",
    config: hooks,
    files: {
      "a.ts": `items.forEach(item => {\n  for (const part of item) {\n    useThing(part);\n  }\n  if (item) useOther();\n});\n`,
      "b.ts": `function Component() {\n  items.forEach(item => {\n    for (const part of item) useThing(part);\n  });\n}\n`,
    },
  },
  {
    name: "rules-of-hooks/try",
    about: "a hook in a try statement is called conditionally",
    config: hooks,
    files: {
      "a.ts": `function Component() {\n  try {\n    useThing();\n  } catch {\n    useOther();\n  } finally {\n    useLast();\n  }\n  while (a) {\n    try {\n      useLoop();\n    } catch {}\n  }\n}\n`,
    },
  },
  {
    name: "rules-of-hooks/anonymous",
    about: "a function without any name counts as a component; the default of what is assigned to has no name",
    config: hooks,
    files: {
      "a.ts": `export default () => {\n  if (a) useThing();\n};\n`,
      "b.ts": `export default function () {\n  if (a) useThing();\n}\n`,
      "c.ts": `({ k = () => { useThing(); } } = {});\nconst { j = () => { useThing(); } } = {};\nconst c = () => { useThing(); };\n`,
    },
  },
  {
    name: "rules-of-hooks/one-report",
    about: "a call is reported once",
    config: hooks,
    files: {
      "a.ts": `function notComponent() {\n  while (a) useThing();\n}\nclass A {\n  m() {\n    if (a) useThing();\n  }\n  p = () => useThing();\n}\nasync function Component() {\n  if (a) useThing();\n}\nuseThing();\n`,
    },
  },
  {
    name: "exhaustive-deps/places",
    about: "a missing dependency is printed where it is used; what changes every render in the array; `ref.current` as a whole",
    config: hooks,
    files: {
      "a.tsx": `function Component({ a }) {\n  const ref = useRef();\n  const made = {};\n  const call = () => a;\n  useEffect(() => {\n    console.log(a);\n    return () => {\n      ref.current.stop();\n    };\n  }, []);\n  useCallback(() => [made, call], [made, call]);\n}\n`,
    },
  },
  {
    name: "exhaustive-deps/each-by-itself",
    about: "each dependency that is not needed, is there twice or is no dependency is a report of its own",
    config: hooks,
    files: {
      "a.tsx": `const outer = 1;\nfunction Component({ a, b }) {\n  useMemo(() => a, [a, a, b, b.c, outer, 1, a + b, ...b]);\n  useMemo(() => a);\n  useEffect(async () => {}, a);\n  useEffect(b, []);\n  useEffect();\n}\n`,
    },
  },
  {
    name: "exhaustive-deps/callee",
    about: "is_callee_of_call: what a method is called on is the dependency",
    config: hooks,
    files: {
      "a.tsx": `function Component({ a, b, c, d, e }) {\n  useEffect(() => {\n    a.b.c();\n  }, []);\n  useEffect(() => {\n    b.c[d]();\n  }, [d]);\n  useEffect(() => {\n    c[d.e]();\n  }, [c]);\n  useEffect(() => {\n    e.f.g;\n  }, []);\n}\n`,
    },
  },
  {
    name: "exhaustive-deps/order",
    about: "Found::order_of_oxlint: of several that are missing, the first in oxlint's hash table is where the report is printed",
    config: hooks,
    files: {
      "a.tsx": [
        `import React, { useEffect as effect, type FC } from "react";`,
        `import * as all from "./all";`,
        `type Alias<T> = T extends infer U ? { [K in keyof U]: (value: U[K]) => void } : never;`,
        `interface Props { a: number; call(this: Props, x: number): void }`,
        `interface Props { b: number }`,
        `enum Kind { One, Two = "two" }`,
        `namespace Space { export const inner = 1; }`,
        `declare function overloaded(a: string): void;`,
        `declare function overloaded(a: number): void;`,
        `@decorate(x => x) class Thing<T> { constructor(private field: T) {} method(p: T) { try {} catch (error) {} } }`,
        `const Expr = class Named {};`,
        `const named = function self(self) { var hoisted; { var hoisted; } };`,
        `const { first = (inner: number) => inner, second } = all;`,
        `export function Component({ a, b, c }: Props & { c: number }, ...rest: number[]) {`,
        `  const [state, setState] = useState(0);`,
        `  const local = a + b;`,
        `  const other = [c];`,
        `  function helper() { return local; }`,
        `  useEffect(() => {`,
        `    console.log(other, state, helper(), rest, a.x.y, b, c, local, first, second, Kind.One, Space.inner);`,
        `    setState(1);`,
        `  }, []);`,
        `  useCallback(() => [rest, c, b, a], []);`,
        `  useMemo(() => <Thing a={a} b={local}>{other}{state}</Thing>, []);`,
        `}`,
        ``,
      ].join("\n"),
    },
  },
  {
    name: "exhaustive-deps/comments",
    about: "comments go by the array, which is the primary label",
    config: hooks,
    files: {
      "a.tsx": `function Component({ a }) {\n  useEffect(() => {\n    console.log(a);\n    // oxlint-disable-next-line react-hooks/exhaustive-deps\n  }, []);\n  useEffect(() => {\n    // oxlint-disable-next-line react-hooks/exhaustive-deps\n    console.log(a);\n  }, []);\n}\n`,
    },
  },
  {
    name: "no-unused-vars/type-query",
    about: "oxlint_counts_type_query_as_use: typeof a in a type is a use, outside of what declares a",
    config: unused,
    files: {
      "a.ts": `const list = ["a", "b"] as const;\nexport type Item = (typeof list)[number];\nexport function f() {\n  const value = g();\n  check<typeof value>();\n}\nconst self: typeof self = 1;\nexport function h(a: number, b: typeof a) {\n  return b;\n}\nconst never = 1;\n`,
    },
  },
  {
    name: "no-unused-vars/loop",
    about: "oxlint_is_in_loop_body: a statement that updates a variable in the body of a loop is a use",
    config: unused,
    files: {
      "a.ts": `export function f(xs: number[]) {\n  let a = 0;\n  for (const x of xs) {\n    if (x) {\n      a++;\n    }\n  }\n  let b = 0;\n  while (xs.pop()) b += 1;\n  let c = 0;\n  do {\n    c = c + 1;\n  } while (xs.pop());\n  let d = 0;\n  for (let i = 0; i < 1; i++) d--;\n  let e = 0;\n  for (const k in xs) e += 1;\n  let g = 0;\n  for (const x of xs) {\n    xs.forEach(() => {\n      g++;\n    });\n  }\n  let h = 0;\n  for (const x of xs) h = 1;\n  let i = 0;\n  if (xs) {\n    i++;\n  }\n}\n`,
    },
  },
  {
    name: "no-unused-vars/returned-function",
    about: "oxlint_is_in_return_statement: the same at the top of a function that is part of what is returned",
    config: unused,
    files: {
      "a.ts": `export function f(xs: number[]) {\n  let a = 0;\n  let b = 0;\n  let c = 0;\n  let d = 0;\n  let e = 0;\n  xs.forEach(() => {\n    b++;\n  });\n  const later = () => {\n    c++;\n  };\n  later();\n  return {\n    bump: async () => {\n      a++;\n    },\n    nested() {\n      if (xs) {\n        d++;\n      }\n    },\n    add: function () {\n      e += 1;\n    },\n  };\n}\nexport const g = () => {\n  let n = 0;\n  return () => n++;\n};\nlet m = 0;\nexport const h = () => ({\n  bump() {\n    m++;\n  },\n});\n`,
    },
  },
  {
    name: "no-unused-vars/place",
    about: "oxlint_reports_the_declaration",
    config: unused,
    files: { "a.ts": `export function f() {\n  let n = 0;\n  n++;\n  let m;\n  m = 1;\n  m = 2;\n}\n` },
  },
  ...[["none"], ["string", "all"], ["object", {}], ["pattern", { varsIgnorePattern: "^ignored" }]].map(([name, ...options]) => ({
    name: `no-unused-vars/underscore-${name}`,
    about: "oxlint_ignores_underscore_by_default: unless the options are an object; a parameter that is called _ is not ignored",
    config: rules(["typescript"], { "no-unused-vars": ["error", ...options] }),
    files: {
      "a.ts": `const _a = 1;\nconst b = 2;\nconst ignored = 3;\nexport function f(_c: number, d: number, _: number) {}\ntry {\n} catch (_e) {}\nimport _g from "g";\nfunction _h() {}\ntype _I = 1;\n`,
    },
  })),
  {
    name: "no-unused-vars/options-of-oxlint",
    about: "reportVarsOnlyUsedAsTypes and fix are options",
    config: rules(["typescript"], { "no-unused-vars": ["error", { reportVarsOnlyUsedAsTypes: true, fix: { imports: "off", variables: "suggestion" } }] }),
    files: { "a.ts": `const a = 1;\nexport type T = typeof a;\nimport b from "b";\nexport function f(c: number): typeof c {\n  return 1;\n}\n` },
  },
  {
    name: "no-unused-vars/globals-in-comments",
    about: "oxlint_ignores_globals_in_comments",
    config: unused,
    files: { "a.js": `/* global a, b */\na;\n`, "b.ts": `/* globals c */\n` },
  },
  {
    name: "no-unused-vars/vars-local",
    about: "oxlint_takes_for_global: with vars: local, a var at the top of the file, of a module too, and nothing else",
    config: rules(["typescript"], { "no-unused-vars": ["error", "local"] }),
    files: {
      "a.ts": `var a = 1;\nlet b = 2;\nconst c = 3;\nfunction d() {\n  var e = 4;\n}\nclass F {}\nexport {};\n`,
      "b.cjs": `var a = 1;\nlet b = 2;\nfunction d() {}\n`,
    },
  },
  {
    name: "no-unused-vars/self-reassignment",
    about: "oxlint_is_self_reassignment, oxlint_is_discarded_read, oxlint_is_self_call: when what is read of a variable only serves itself",
    config: rules(["typescript"], { "no-unused-vars": ["error", {}] }),
    files: {
      "a.ts": [
        `export function f(cb, cc, cd, xs) {`,
        `  let a = [];`,
        `  a = a.concat(a);`,
        `  let b = null;`,
        `  b = g(b);`,
        `  cb = (function (x) {`,
        `    return cb(1 + x);`,
        `  })();`,
        `  cc = (0, function (x) {`,
        `    cc(1 + x);`,
        `  });`,
        `  cd = (function (x) {`,
        `    cd(1 + x);`,
        `  }, cd);`,
        `  let c = 0;`,
        `  c = c + 1;`,
        `  let d = 0;`,
        `  function inner() {`,
        `    d = d + 1;`,
        `  }`,
        `  inner();`,
        `  let e = 0;`,
        `  xs.map(() => e++);`,
        `  let h = 0;`,
        `  xs[h++] = 1;`,
        `  let i = 0;`,
        `  if (i++) g();`,
        `  let j = () => {`,
        `    j();`,
        `  };`,
        `  let k;`,
        `  k = function () {`,
        `    k();`,
        `  };`,
        `  let l = 0;`,
        `  for (; l++; ) g();`,
        `  let m = 0;`,
        `  m = (m, 1);`,
        `}`,
        `namespace N {`,
        `  export const o = 1;`,
        `  g(N.o);`,
        `}`,
        `enum E {`,
        `  A = 1,`,
        `  B = E.A,`,
        `}`,
        `function* gen() {`,
        `  let y = 1;`,
        `  y = yield y;`,
        `}`,
        `gen();`,
        ``,
      ].join("\n"),
    },
  },
  {
    name: "consistent-type-imports/react",
    about: "oxlint_takes_for_jsx_factory",
    config: rules(["typescript"], { "typescript/consistent-type-imports": "error" }),
    files: {
      "a.ts": `import * as React from "react";\nexport function C(x: unknown) {\n  return x as React.ReactNode;\n}\n`,
      "b.ts": `import React from "react";\nexport type N = React.ReactNode;\n`,
      "c.ts": `import * as Other from "other";\nexport type N = Other.Node;\n`,
      "d.ts": `import React, { FC } from "react";\nexport type N = [React.ReactNode, FC];\n`,
      "e.ts": `import { React } from "react";\nexport type N = React.ReactNode;\n`,
    },
  },
  {
    name: "no-accumulating-spread/places",
    about: "in a loop the accumulator is printed, and comments go by the loop",
    config: rules(["oxc"], { "oxc/no-accumulating-spread": "warn" }),
    files: {
      "a.ts": `let all = [];\nfor (const it of items) {\n  all = [...all, it];\n}\nlet more = [];\n// oxlint-disable-next-line oxc/no-accumulating-spread\nfor (const it of items) {\n  more = [...more, it];\n}\n// oxlint-disable-next-line oxc/no-accumulating-spread\nlet rest = [];\nfor (const it of items) {\n  rest = [...rest, it];\n}\nitems.reduce((acc, it) => [...acc, it], []);\n`,
    },
  },
  {
    name: "names/without-a-plugin",
    about: "a rule that oxlint has in eslint as it is in ESLint is not the rule of typescript-eslint that needs types",
    config: rules([], { "require-await": "error", "prefer-destructuring": "error", "prefer-promise-reject-errors": "error", "no-implied-eval": "error", "no-throw-literal": "error", "dot-notation": "error", "consistent-return": "error" }),
    files: {
      "a.ts": lines(
        `declare const o: { a: number }, list: number[];`,
        `const a = o.a;`,
        `const b = list[0];`,
        `async function f() {`,
        `  return [a, b];`,
        `}`,
        `Promise.reject(1);`,
        `o["a"];`,
        `function g(x: number) {`,
        `  if (x) return 1;`,
        `  else return;`,
        `}`,
        `throw 1;`,
      ),
    },
  },
  {
    name: "require-await/places",
    about: "oxlint_place; await using is not seen",
    config: rules([], { "require-await": "error" }),
    files: {
      "a.js": lines(
        `async function a() { x }`,
        `(async function () { x });`,
        `(async function b() { x });`,
        `(async () => { x });`,
        `(async () => x);`,
        `({ async c() { x }, async "d"() { x }, async [e]() { x }, f: async function () { x }, "g": async function () { x }, h: async () => x });`,
        `class A { async i() { x } static async j() { x } async #k() { x } async "l"() { x } m = async () => x; }`,
        `export default async function () { x }`,
        `async function n() { await using y = z; }`,
        `async function o() { for await (const y of z); }`,
        `async function p() {}`,
        `async function* q() { x }`,
      ),
    },
  },
  {
    name: "prefer-promise-reject-errors/what-is-promise",
    about: "is_promise; what only concerns types is seen through",
    config: rules([], { "prefer-promise-reject-errors": "error" }),
    files: {
      "a.ts": lines(
        `Promise.reject(e as Error);`,
        `Promise.reject(e!);`,
        `Promise.reject(<Error>e);`,
        `Promise.reject(e satisfies Error);`,
        `Promise.reject("a" as unknown as Error);`,
        `Promise.reject(1);`,
        `new Promise((resolve, reject) => reject(1));`,
        `new Promise((resolve, reject) => reject(e as Error));`,
      ),
      "b.js": lines(`import Promise from "bluebird";`, `Promise.reject(1);`, `new Promise((resolve, reject) => reject(1));`),
    },
  },
  {
    name: "prefer-destructuring/place",
    about: "the value is printed",
    config: rules([], { "prefer-destructuring": "error" }),
    files: { "a.js": lines(`var a = b.a;`, `var c = d[0], e = f.e;`, `var g =`, `  h.g;`, `g = h.g;`, `var i = (j, k).i;`) },
  },
  {
    name: "no-throw-literal/place",
    about: "what is thrown is printed",
    config: rules([], { "no-throw-literal": "error" }),
    files: { "a.ts": lines(`function a() { throw 1; }`, `function b() { throw ("a"); }`, `function c() { throw undefined; }`, `function d() {`, `  throw (`, `    1`, `  );`, `}`, `function e() { throw (1 as any); }`, `function f() { throw (g as any); }`) },
  },
  {
    name: "no-restricted-imports/globs",
    about: "Globs: the patterns of a group are globs for the whole specifier, and the last that matches decides",
    config: rules([], {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { group: ["@shared/*"], message: "a" },
            { group: ["scenes/**", "!scenes/urls", "!scenes/tours/utils"] },
            { group: ["nx", "nx/**"] },
            { group: ["**/dist"] },
            { group: ["Upper/*"] },
            { group: ["Exact/*"], caseSensitive: true },
          ],
        },
      ],
    }),
    files: {
      "a.js": lines(
        `import "@shared/x";`,
        `import "@shared/hooks/useShare";`,
        `import "@shared";`,
        `import "scenes/urls";`,
        `import "scenes/tours/utils";`,
        `import "scenes/tours/other";`,
        `import "scenes/other";`,
        `import "nx";`,
        `import "nx/x";`,
        `import "nx/x/y";`,
        `import "../src/utils/nx/version";`,
        `import "../nx";`,
        `import "b/dist";`,
        `import "a-plugin/dist/style.css";`,
        `import "dist";`,
        `import "upper/a";`,
        `import "exact/a";`,
        `import "Exact/a";`,
      ),
    },
  },
  {
    name: "no-restricted-imports/strings",
    about: "Globs::is_each_a_group: each string in patterns is a group, and one that takes a module out does so for all",
    config: rules([], { "no-restricted-imports": ["error", { patterns: ["!a/keep", "a/**", "b/*", "!b/keep", "c"] }] }),
    files: { "a.js": lines(`import "a/keep";`, `import "a/other";`, `import "b/keep";`, `import "b/other";`, `import "b/other/more";`, `import "c";`, `import "d/c";`, `import "c/d";`) },
  },
  {
    name: "no-restricted-imports/import-calls",
    about: "check_import_call; what is said about a * is said about the statement",
    config: rules([], {
      "no-restricted-imports": ["error", { paths: ["a", { name: "b", importNames: ["x"] }], patterns: [{ group: ["c/*"] }, { group: ["d/*"], importNames: ["x"] }] }],
    }),
    files: {
      "a.ts": lines(
        `import("a");`,
        `import("b");`,
        `import("c/e");`,
        `import("d/e");`,
        "import(`a`);",
        `import(a);`,
        `import * as b from "b";`,
        `import c, * as d from "d/e";`,
        `export * from "b";`,
        `export * as e from "d/e";`,
        `import { x } from "b";`,
        `b, c, d, x;`,
      ),
    },
  },
  {
    name: "no-unused-vars/how-it-is-declared",
    about: "oxlint_leaves_alone",
    config: unused,
    files: {
      "a.ts": lines(
        `declare class A {}`,
        `declare abstract class B {}`,
        `declare function c(): void;`,
        `declare const d: number;`,
        `class E {}`,
        `function f(): void;`,
        `function f() {}`,
        `declare enum G {}`,
        `declare namespace H {}`,
        `declare let i: number;`,
        `export {};`,
      ),
      "b.jsx": lines(`import React from "react";`, `import { h } from "preact";`, `import Other from "other";`, `export const a = <div />;`),
      "c.js": lines(`import React from "react";`, `import * as h from "h";`, `const React2 = 1;`),
      "d.ts": lines(`import React from "react";`, `import { h } from "preact";`),
      "e.tsx": lines(`import React = require("react");`, `import { h as i, j as h } from "preact";`),
      "f.ts": lines(
        `declare module "x" {`,
        `  interface A<R, T> {}`,
        `  type B<T> = 1;`,
        `  function d<T>(): void;`,
        `}`,
        `declare namespace N {`,
        `  interface A<T> {}`,
        `}`,
        `namespace M {`,
        `  export interface A<T> {}`,
        `}`,
        `declare global {`,
        `  interface A<T> {}`,
        `  type B<T> = 1;`,
        `}`,
        `export interface A<T> {}`,
      ),
      "g.ts": lines(
        `class A {`,
        `  m(a: number, b: number) {`,
        `    return a;`,
        `  }`,
        `}`,
        `export class B extends A {`,
        `  override m(a: number, b: number) {`,
        `    return 1;`,
        `  }`,
        `  override n({ c }: { c: number }, [d]: number[], ...e: number[]) {}`,
        `  o(f: number) {}`,
        `}`,
      ),
    },
  },
  {
    name: "no-unused-vars/parameters",
    about: "function_of_plain_parameter, last_used_arg: a default value changes nothing, and a rest parameter does not count",
    config: unused,
    files: {
      "a.js": lines(
        `export function a(b = [], c) {`,
        `  return c;`,
        `}`,
        `export function d(e, f) {`,
        `  return f;`,
        `}`,
        `export function g(h = 1) {}`,
        `export const i = (j, ...k) => k;`,
        `export const l = (m, n, ...o) => [n, o];`,
        `export const p = (q, { r }) => r;`,
        `export const s = ({ t }, u) => u;`,
        `export const v = (w = 1, x = 2, y = 3) => x;`,
      ),
    },
  },
  {
    name: "no-unused-vars/rest-siblings",
    about: "oxlint_has_rest_sibling",
    config: rules(["typescript"], { "no-unused-vars": ["error", { ignoreRestSiblings: true }] }),
    files: {
      "a.js": lines(
        `export function f(props) {`,
        `  const { a = true, b, ...rest } = props;`,
        `  return rest;`,
        `}`,
        `export function g({ c = false, d, ...rest }) {`,
        `  return rest;`,
        `}`,
        `export function h({ e: { i = 1 }, j: k = 2, ...rest }) {`,
        `  return rest;`,
        `}`,
        `export function l({ m = 1, n }) {}`,
      ),
    },
  },
  {
    name: "no-unused-vars/a-value-and-a-type",
    about: "oxlint_counts_as_used: a value and a type of one name are one symbol",
    config: unused,
    files: {
      "a.ts": lines(
        `const A = ["a"] as const;`,
        `export type A = (typeof A)[number];`,
        `interface B {}`,
        `const B = 0;`,
        `export type UsesB = B;`,
        `const C = 1;`,
        `interface C {}`,
        `const D = 1;`,
        `type D = D[];`,
        `namespace N {`,
        `  const E = 1;`,
        `  export type E = typeof E;`,
        `}`,
        `N;`,
      ),
    },
  },
  {
    name: "no-irregular-whitespace/each-character",
    about: "oxlint_reports_each_character, skips_by_default",
    config: rules([], { "no-irregular-whitespace": "error" }),
    files: {
      "a.js": lines(`a  = 　b;`, `// c​​d`, "`e f${ g} `;", `/h i/;`, `"j k";`),
      "b.jsx": lines(`<a b="c d">e f</a>;`),
    },
  },
  {
    name: "no-irregular-whitespace/options",
    about: "what the options say counts",
    config: rules([], { "no-irregular-whitespace": ["error", { skipTemplates: false, skipRegExps: false, skipJSXText: false, skipStrings: false, skipComments: true }] }),
    files: {
      "a.js": lines(`// c​​d`, "`e  f`;", `/h i/;`, `"j k";`),
      "b.jsx": lines(`<a b="c d">e f</a>;`),
    },
  },
  {
    name: "no-non-null-asserted-optional-chain/each-assertion",
    about: "check_as_oxlint",
    config: rules(["typescript"], { "typescript/no-non-null-asserted-optional-chain": "error" }),
    files: {
      "a.ts": lines(
        `a?.b!;`,
        `a?.b!!;`,
        `(a?.b)!;`,
        `(a?.b)!!;`,
        `(a?.b!)!;`,
        `a?.b!.c;`,
        `a?.b!!.c;`,
        `a?.b!.c!;`,
        `(a?.b)!.c;`,
        `(a?.b!).c;`,
        `(a?.b as any)!;`,
        `(a?.b satisfies any)!.c;`,
        `(<any>a?.b)!;`,
        `(a?.b).c!;`,
        `a?.b!();`,
        `(a?.b)!();`,
        `f(a?.b!, x[a?.b!]);`,
        `a!?.b;`,
        `a.b!;`,
        `(a ?? b?.c)!;`,
        `a?.b`,
        `  .c!;`,
      ),
    },
  },
  {
    name: "ambient/var",
    about: "AmbientAncestors: no-var and vars-on-top say nothing about ambient declarations; no-var prints the keyword",
    config: rules([], { "no-var": "error", "vars-on-top": "error" }),
    files: {
      "a.ts": lines(
        `f();`,
        `declare global {`,
        `  var a: number;`,
        `  namespace N {`,
        `    var b: number;`,
        `  }`,
        `}`,
        `declare module "m" {`,
        `  var c: number;`,
        `  export var d: number;`,
        `}`,
        `declare namespace O {`,
        `  var e: number;`,
        `}`,
        `namespace P {`,
        `  f();`,
        `  var g = 1;`,
        `}`,
        `declare var h: number;`,
        `export declare var i: number;`,
        `var j = 1;`,
      ),
    },
  },
  {
    name: "no-lone-blocks/the-rule-of-oxlint",
    about: "check_as_oxlint",
    config: rules([], { "no-lone-blocks": "error" }),
    files: {
      "a.js": lines(
        `function a() {`,
        `  b();`,
        `  {`,
        `    c();`,
        `  }`,
        `}`,
        `function d() {`,
        `  {`,
        `    c();`,
        `  }`,
        `}`,
        `function e() {`,
        `  {`,
        `    c();`,
        `    c();`,
        `  }`,
        `}`,
        `function f() {`,
        `  "use strict";`,
        `  {`,
        `    c();`,
        `  }`,
        `}`,
        `{`,
        `  c();`,
        `}`,
        `{`,
        `  let g;`,
        `}`,
        `{`,
        `  function h() {}`,
        `}`,
        `if (a) {`,
        `}`,
        `if (a) {`,
        `  // comment`,
        `}`,
        `while (a) {}`,
        `try {`,
        `} catch {`,
        `} finally {`,
        `}`,
        `switch (a) {`,
        `  case 1: {`,
        `  }`,
        `  case 2: {`,
        `    c();`,
        `  }`,
        `  case 3:`,
        `    c();`,
        `    {`,
        `      c();`,
        `    }`,
        `}`,
        `{`,
        `  {`,
        `    let i;`,
        `  }`,
        `}`,
        `class A {`,
        `  static {`,
        `    {`,
        `      c();`,
        `    }`,
        `  }`,
        `  static {`,
        `    c();`,
        `    {`,
        `      let j;`,
        `    }`,
        `  }`,
        `}`,
        `label: {`,
        `}`,
        `() => {};`,
      ),
    },
  },
  {
    name: "no-setter-return/accessors-only",
    about: "is_setter",
    config: rules([], { "no-setter-return": "error" }),
    files: {
      "a.js": lines(
        `Object.defineProperty(a, "b", { set: value => (a.c = value) });`,
        `Object.defineProperty(a, "d", { set(value) { return 1; } });`,
        `Object.defineProperties(a, { e: { set(value) { return 1; } } });`,
        `Reflect.defineProperty(a, "f", { set: function (value) { return 1; } });`,
        `Object.create(null, { g: { set(value) { return 1; } } });`,
        `({ set h(value) { return 1; } });`,
        `class A { set i(value) { return 1; } static set j(value) { return () => { return 1; }; } }`,
      ),
    },
  },
  {
    name: "prefer-for-of/arrays-with-a-name",
    about: "oxlint_knows_name_of; what is between the parentheses is printed",
    config: rules(["typescript"], { "typescript/prefer-for-of": "error" }),
    files: {
      "a.ts": lines(
        `for (let i = 0; i < "abc".length; i++) f();`,
        `for (let i = 0; i < a.length; i++) f();`,
        `for (let i = 0; i < a.b.length; i++) f(a.b[i]);`,
        `for (let i = 0; i < a["b"].length; i++) f();`,
        `for (let i = 0; i < a[0].length; i++) f();`,
        `for (let i = 0; i < a[b].length; i++) f();`,
        `for (let i = 0; i < g().length; i++) f();`,
        `for (let i = 0; i < [1].length; i++) f();`,
        `for (let i = 0; i < this.length; i++) f();`,
        `for (let i = 0; i < this.a.length; i++) f();`,
        `for (let i = 0; i < a!.length; i++) f();`,
        `for (let i = 0; i < (a).length; i++) f();`,
        `for (`,
        `  let i = 0;`,
        `  i < a.length;`,
        `  i++`,
        `) f();`,
      ),
    },
  },
  {
    name: "triple-slash-reference/top-level-imports",
    about: "an import in a declared module does not count",
    config: rules(["typescript"], { "typescript/triple-slash-reference": "error" }),
    files: {
      "a.d.ts": lines(`/// <reference types="react" />`, `declare module "*.md" {`, `  import type { ComponentType } from "react";`, `  const C: ComponentType;`, `  export default C;`, `}`),
      "b.ts": lines(`/// <reference types="react" />`, `import * as React from "react";`, `React;`),
      "c.ts": lines(`/// <reference types="react" />`, `import React = require("react");`, `React;`),
    },
  },
  {
    name: "no-unsafe-declaration-merging/the-first-declaration",
    about: "a declaration is compared with the first of its name, which is what is printed",
    config: rules(["typescript"], { "typescript/no-unsafe-declaration-merging": "error" }),
    files: {
      "a.ts": lines(`interface A {}`, `class A {}`, `class B {}`, `interface B {}`, `interface B {}`, `interface C {}`, `class C {}`, `interface C {}`, `namespace D {}`, `interface D {}`, `class D {}`),
      "b.ts": lines(`export interface A<P = {}> {}`, `export abstract class A<P> {}`, `export class B<T> {}`, `export interface B<T> {}`),
      "c.ts": lines(`declare namespace N {`, `  interface A {}`, `  class A {}`, `}`, `function f() {`, `  class B {}`, `  interface B {}`, `}`, `import { C } from "c";`, `class C {}`, `interface C {}`),
    },
  },
  {
    name: "no-unsafe-optional-chaining/through-types",
    about: "usage_of",
    config: rules([], { "no-unsafe-optional-chaining": "error" }),
    files: {
      "a.ts": lines(
        `(a?.b as T).c;`,
        `(a?.b)!.c;`,
        `(a?.b satisfies T).c;`,
        `(<T>a?.b).c;`,
        `(a?.b as T)();`,
        `new (a?.b as T)();`,
        `const { c } = a?.b as T;`,
        `[...(a?.b)!];`,
        `d in (a?.b as T);`,
        `((a && b?.c) as T).d;`,
        `(a?.b as T)?.c;`,
        `f(...a?.b);`,
        `new F(...a?.b);`,
        `function g({ x } = a?.b) {}`,
        `function h([{ x } = a?.b]) {}`,
        `class A { #x; m() { return #x in a?.b; } }`,
        `(a?.b).c;`,
      ),
    },
  },
  {
    name: "no-undef/names-of-types",
    about: "nothing is said about a name that can be that of a type",
    config: rules([], { "no-undef": "error" }),
    files: {
      "a.ts": lines(
        `export const a: BufferEncoding = b as NodeJS.ProcessEnv;`,
        `export type C = Unknown<D>;`,
        `export class E extends F<G> implements H {}`,
        `export let i: typeof j;`,
        `export { k };`,
        `export default l;`,
        `m satisfies N;`,
      ),
    },
  },
  {
    name: "no-var-requires/wherever-it-is-used",
    about: "it is used wherever it is not a statement",
    config: rules(["typescript"], { "typescript/no-var-requires": "error" }),
    files: {
      "a.js": lines(
        `let a = require("a");`,
        `a = require("b");`,
        `a = b ? require("c") : require("d");`,
        `require("e");`,
        `require?.("f");`,
        `(require("g"));`,
        `f(require("h"));`,
        `[require("i")];`,
        `a = require("j", "k");`,
        `a = require();`,
        `export default require("l");`,
        `() => require("m");`,
      ),
    },
  },
  {
    name: "prefer-template/in-another-concatenation",
    about: "nothing is said about what is anywhere in another concatenation",
    config: rules([], { "prefer-template": "error" }),
    files: {
      "a.js": lines(
        `("a " + b()).trim() + (c ? " d" : " e");`,
        `("a " + b()).trim();`,
        `f + g("h" + i);`,
        `f + (() => "j" + k);`,
        `f * g("l" + m);`,
        `"n" + o + p("q" + r);`,
      ),
    },
  },
  {
    name: "no-duplicate-imports/imports-without-names",
    about: "they are looked at only if the file has no others; oxlint_place",
    config: rules([], { "no-duplicate-imports": ["error", { includeExports: true }] }),
    files: {
      "a.js": lines(`import "a";`, `import A from "a";`, `import { b } from "b";`, `import { c } from "b";`, `A, b, c;`),
      "b.js": lines(`import "a";`, `import "a";`, `import {} from "a";`),
      "c.js": lines(`import a from "a";`, `export { b } from "a";`, `export { c } from "a";`, `a;`),
    },
  },
  {
    name: "unbound-method/the-symbol-of-the-member",
    about: "nothing if the parts of a union or an intersection declare the member in different places, nothing about a[b]; the name is printed",
    config: rules(["typescript"], { "typescript/unbound-method": "error" }),
    typed: true,
    files: {
      "a.ts": lines(
        `class A {`,
        `  keys() {`,
        `    return this;`,
        `  }`,
        `  prop() {`,
        `    return { a: this.keys };`,
        `  }`,
        `}`,
        `class B extends A {`,
        `  keys() {`,
        `    return this;`,
        `  }`,
        `}`,
        `class C extends A {}`,
        `declare const a: A, ab: A | B, ac: A | C, an: A | undefined, ai: A & { b: 1 };`,
        `export const u = [a.keys, ab.keys, ac.keys, an?.keys, an!.keys, ai.keys, window.print, a["keys"]];`,
        `export function f(key: "keys" | "prop") {`,
        `  return a[key];`,
        `}`,
        `export const { keys } = a;`,
      ),
    },
  },
  {
    name: "no-meaningless-void-operator/by-the-type",
    about: "whatever the operand is",
    config: rules(["typescript"], { "typescript/no-meaningless-void-operator": "error" }),
    typed: true,
    files: {
      "a.ts": lines(`declare const a: number, b: undefined, c: () => void, d: () => number;`, `void a;`, `void b;`, `void c();`, `void d();`, `void 0;`, `void undefined;`, `void (a, b);`, `let e;`, `void (e = b);`),
    },
  },
  {
    name: "no-import-assign/declarations",
    about: "a declaration assigns nothing; oxlint_place",
    config: rules([], { "no-import-assign": "error" }),
    files: {
      "a.ts": lines(`import type { A } from "a";`, `import { b } from "b";`, `import * as c from "c";`, `const A = 1;`, `b = 1;`, `[b] = d;`, `({ e: b } = d);`, `b++;`, `for (b of d);`, `c.f = 1;`, `c.f++;`, `[c.f] = d;`, `Object.assign(c, d);`, `c = 1;`, `delete c.f;`, `A;`),
    },
  },
  {
    name: "no-sparse-arrays/one-report",
    about: "one report for an array: at the first comma, or at the array if there are ten",
    config: rules([], { "no-sparse-arrays": "error" }),
    files: { "a.js": lines(`a = [1, , 2, , 3];`, `b = [, , ,];`, `c = [`, `  1,`, `  ,`, `  ,`, `];`, `d = [, , , , , , , , ,];`, `e = [, , , , , , , , , ,];`, `f = [[, 1], [, 2]];`) },
  },
  {
    name: "no-useless-catch/place",
    about: "the parameter; parentheses hide the name",
    config: rules([], { "no-useless-catch": "error" }),
    files: {
      "a.ts": lines(`try {`, `  a();`, `} catch (e) {`, `  throw e;`, `}`, `try {`, `  a();`, `} catch (e: unknown) {`, `  throw e;`, `} finally {`, `  b();`, `}`, `try {`, `  a();`, `} catch (e) {`, `  throw (e);`, `}`),
    },
  },
  {
    name: "no-cond-assign/place",
    about: "the operator",
    config: rules([], { "no-cond-assign": "error" }),
    files: { "a.js": lines(`if (a = b) c();`, `while (a   +=   b) c();`, `do c(); while (a = b);`, `for (; a = b; ) c();`, `d = (a = b) ? 1 : 2;`, `d = ((a = b)) ? 1 : 2;`, `if ((a = b)) c();`, `if (`, `  a`, `  = b`, `) c();`) },
  },
  {
    name: "no-cond-assign/always",
    about: "the operator",
    config: rules([], { "no-cond-assign": ["error", "always"] }),
    files: { "a.js": lines(`if ((a = b)) c();`, `if (a && (b = c)) d();`, `while (f(a = b)) c();`, `d = (a = b) ? 1 : 2;`) },
  },
  {
    name: "require-yield/place",
    about: "the name of the function, or the function",
    config: rules([], { "require-yield": "error" }),
    files: { "a.js": lines(`function* a() { b(); }`, `export default function* () { b(); }`, `c = function* () { b(); };`, `c = function* d() { b(); };`, `e = { *f() { b(); }, async *[g]() { b(); } };`, `class H { *i() { b(); } static *j() { b(); } }`) },
  },
  {
    name: "no-dupe-keys/place",
    about: "the key before",
    config: rules([], { "no-dupe-keys": "error" }),
    files: { "a.js": lines(`a = {`, `  b: 1,`, `  c: 2,`, `  b: 3,`, `  "b": 4,`, `};`, `d = { get e() {}, set e(f) {}, e: 1 };`) },
  },
  {
    name: "valid-typeof/literals",
    about: "only strings and templates are looked at",
    config: rules([], { "valid-typeof": "error" }),
    files: { "a.js": lines(`typeof a == null;`, `typeof a == 1;`, `typeof a == true;`, `typeof a == /b/;`, `typeof a == 1n;`, `typeof a == "nope";`, "typeof a == `nope`;", `typeof a == undefined;`, `typeof a == b;`) },
  },
  {
    name: "valid-typeof/require-string-literals",
    about: "the other literals are like any other expression",
    config: rules([], { "valid-typeof": ["error", { requireStringLiterals: true }] }),
    files: { "a.js": lines(`typeof a == null;`, `typeof a == 1;`, `typeof a == "nope";`, `typeof a == b;`, `typeof a == typeof b;`) },
  },
  {
    name: "no-control-regex/place",
    about: "the first of the characters as they are written; a tab is none",
    config: rules([], { "no-control-regex": "error" }),
    files: { "a.js": lines(String.raw`a = /b\x1bc\x1f/;`, String.raw`a = /\u001b/;`, `a = /\t/;`, String.raw`a = /\t/;`, String.raw`a = new RegExp("\t");`, `a = new RegExp("\t");`, String.raw`a = /[\x00-\x1f]/;`, String.raw`a = /\u{1b}/u;`) },
  },
  {
    name: "no-useless-escape/passed-over",
    about: "oxlint_passes_over",
    config: rules([], { "no-useless-escape": "error" }),
    files: { "a.js": lines(String.raw`a = '"\\\""';`, String.raw`a = '\"';`, String.raw`a = "\\\a";`, String.raw`a = "\a";`, "a = `\\$${b}`;", "a = `\\$`;", "a = `\\$b`;", "a = `\\${b}`;", "a = `\\#${b}`;") },
  },
  {
    name: "constructor-super/type-wrappers",
    about: "oxlint_is_possible_constructor",
    config: rules([], { "constructor-super": "error" }),
    files: {
      "a.ts": lines(
        `class A extends (B as C) { constructor() { super(); } }`,
        `class D extends (B as unknown as C) { constructor() { super(); } }`,
        `class E extends B! { constructor() { super(); } }`,
        `class F extends (B satisfies C) { constructor() { super(); } }`,
        `class G extends (1 as any) { constructor() { super(); } }`,
        `class H extends 1 { constructor() { super(); } }`,
        `class I extends (a, "b") { constructor() { super(); } }`,
        `class J extends (a ? 1 : B) { constructor() { super(); } }`,
        `class K extends (a + b) { constructor() { super(); } }`,
        `class L extends (a || 1) { constructor() { super(); } }`,
        `class M extends (() => {}) { constructor() { super(); } }`,
        `class N extends undefined { constructor() { super(); } }`,
        "class O extends `a` { constructor() { super(); } }",
        `class P extends (a += b) { constructor() { super(); } }`,
        `class Q extends (B as C) { constructor() {} }`,
      ),
    },
  },
  {
    name: "no-useless-concat/place",
    about: "the two strings",
    config: rules([], { "no-useless-concat": "error" }),
    files: { "a.js": lines(`a = "b" + "c";`, `a = b + "c" + "d" + e;`, "a = `b` + `c`;", `a = "b" +`, `  "c";`) },
  },
  {
    name: "no-duplicate-enum-values/place",
    about: "check_as_oxlint",
    config: rules(["typescript"], { "typescript/no-duplicate-enum-values": "error" }),
    files: { "a.ts": lines(`enum A {`, `  a = 1,`, `  b = 1,`, `  c = 1,`, `  d = "e",`, `  f = "e",`, `  g = "e",`, "  h = `e`,", `  i = -1,`, `  j = -1,`, `  k = (1),`, `  l = 1.0,`, `}`) },
  },
  {
    name: "no-extraneous-class/members",
    about: "check_as_oxlint",
    config: rules(["typescript"], { "typescript/no-extraneous-class": "error" }),
    files: {
      "a.ts": lines(
        `class A {}`,
        `export class B {}`,
        `export default class {}`,
        `@d class C {}`,
        `a = class {};`,
        `a = class D {};`,
        `class E { constructor() {} }`,
        `class F { constructor(private a: number) {} }`,
        `class G { static a = 1; constructor() {} }`,
        `class H { static a = 1; static b() {} }`,
        `class I { static {} }`,
        `class J { static a = 1; static {} }`,
        `class K { static [a: string]: number; }`,
        `abstract class L { static a = 1; }`,
        `class M implements N {}`,
        `class O implements N { static a = 1; constructor() {} }`,
        `a = class P { static a = 1; };`,
        `a = class { static a = 1; };`,
        `class Q extends R {}`,
        `class S { constructor(); constructor(a?: number) {} }`,
      ),
    },
  },
  {
    name: "prefer-destructuring/type-annotation",
    about: "a declaration with a type annotation is passed over",
    config: rules([], { "prefer-destructuring": "error" }),
    files: { "a.ts": lines(`const a: number = b.a;`, `const c = b.c;`, `const d: number = b[0];`, `const e = b[0];`) },
  },
  {
    name: "prefer-destructuring/enforce-for-declaration-with-type-annotation",
    about: "the option of typescript-eslint's rule",
    config: rules([], { "prefer-destructuring": ["error", { object: true, array: true }, { enforceForDeclarationWithTypeAnnotation: true }] }),
    files: { "a.ts": lines(`const a: number = b.a;`, `const c = b.c;`, `const d: number = b[0];`) },
  },
  {
    name: "options/unknown-property",
    about: "most rules of oxlint pass over a property that they do not know",
    config: rules([], { "no-unused-vars": ["error", { nope: true, args: "none" }] }),
    files: { "a.js": lines(`const a = 1;`, `function b(c) {}`, `b();`) },
  },
  {
    name: "class-methods-use-this/ignore-classes-with-implements",
    about: "the option as ESLint calls it",
    config: rules([], { "class-methods-use-this": ["error", { ignoreClassesWithImplements: "all" }] }),
    files: { "a.ts": lines(`class A implements B { c() {} }`, `class D { e() {} }`) },
  },
  {
    name: "no-this-alias/allow-names",
    about: "what oxlint called allowedNames at first",
    config: rules(["typescript"], { "typescript/no-this-alias": ["error", { allowNames: ["self"] }] }),
    files: { "a.ts": lines(`const self = this;`, `const that = this;`) },
  },
  {
    name: "class-methods-use-this/ignore-classes-with-implements-public-fields",
    about: "the option as ESLint calls it",
    config: rules([], { "class-methods-use-this": ["error", { ignoreClassesWithImplements: "public-fields" }] }),
    files: { "a.ts": lines(`class A implements B { c() {} private d() {} protected e() {} }`) },
  },
  {
    name: "max-params/count-this",
    about: "the option as ESLint calls it",
    config: rules([], { "max-params": ["error", { max: 2, countThis: "never" }] }),
    files: { "a.ts": lines(`function a(this: A, b: 1, c: 2) {}`, `function d(this: A, b: 1, c: 2, e: 3) {}`) },
  },
  {
    name: "max-params/count-this-always",
    about: "the option as ESLint calls it",
    config: rules([], { "max-params": ["error", { max: 2, countThis: "always" }] }),
    files: { "a.ts": lines(`function a(this: void, b: 1, c: 2) {}`, `function d(this: void, b: 1) {}`) },
  },
  {
    name: "no-div-regex/quantifier",
    about: "oxlint_has_quantifier_at",
    config: rules([], { "no-div-regex": "error" }),
    files: { "a.js": lines(`a = /=/;`, `a = /=b/;`, `a = /=+$/;`, `a = /=*/;`, `a = /=?/;`, `a = /={2}/;`, `a = /={2,}/;`, `a = /={2,3}/;`, `a = /={/;`, `a = /={a}/;`, `a = /={,2}/;`, `a = /=|b/;`) },
  },
  {
    name: "no-lonely-if/else-if",
    about: "nothing after an else if",
    config: rules([], { "no-lonely-if": "error" }),
    files: { "a.js": lines(`if (a) {`, `} else {`, `  if (b) {}`, `}`, `if (a) {`, `} else if (b) {`, `} else {`, `  if (c) {}`, `}`, `if (a) {`, `} else {`, `  if (b) {`, `  } else {`, `    if (c) {}`, `  }`, `}`) },
  },
  {
    name: "prefer-function-type/where",
    about: "oxlint_looks_at",
    config: rules(["typescript"], { "typescript/prefer-function-type": "error" }),
    files: {
      "a.ts": lines(
        `export const a = b as { (c: string): d };`,
        `export const e = b as unknown as { new (c: string): d };`,
        `export type F = { (c: string): d };`,
        `export type G = { (c: string): d } | string;`,
        `export type H = { (c: string): d } & string;`,
        `export type I = ({ (c: string): d });`,
        `export let j: { (c: string): d };`,
        `export let k: { (c: string): d } | string;`,
        `export let l: { (c: string): d } & string;`,
        `export function m(n: { (c: string): d }): { (c: string): d } { return n; }`,
        `export let o: Array<{ (c: string): d }>;`,
        `export let p: { (c: string): d }[];`,
        `export interface Q { (c: string): d }`,
        `export type R<T = { (c: string): d }> = T;`,
        `export class S { t: { (c: string): d }; }`,
        `export type U = { v: { (c: string): d } };`,
        `export type W = { new (c: string): d };`,
      ),
    },
  },
  {
    name: "prefer-as-const/literals",
    about: "oxlint_is_same_literal",
    config: rules(["typescript"], { "typescript/prefer-as-const": "error" }),
    files: {
      "a.ts": lines(
        `export class A { readonly b: true = true; c: "d" = "d"; e: 1 = 1; f: 1n = 1n; }`,
        `export let g: "h" = "h", i: 'j' = "j", k: 1 = 1.0, l: false = false;`,
        `export let m = "n" as "n", o = <"p">"p", q = true as true, r = 1 as 1;`,
        "export let s: `t` = `t`;",
      ),
    },
  },
  {
    name: "no-misleading-character-class/written",
    about: "oxlint_can_read",
    config: rules([], { "no-misleading-character-class": "error" }),
    files: { "a.js": lines("a = new RegExp(String.raw`[👍]`);", "a = new RegExp(`[👍]`);", `a = new RegExp("[👍]");`, `const b = "[👍]"; a = new RegExp(b);`, `a = /[👍]/;`) },
  },
  {
    name: "no-use-before-define/key-of-type",
    about: "oxlint_is_in_key_of_type",
    config: rules([], { "no-use-before-define": "error" }),
    files: {
      "a.ts": lines(
        `export type A = { readonly [a]: true };`,
        `export interface I { [b]: 1; [c.k](): void }`,
        `export class C { [d] = 1; declare [e]: 1 }`,
        `export abstract class D { abstract [f]: 1 }`,
        `declare const a: unique symbol;`,
        `declare const b: unique symbol;`,
        `declare const c: { k: symbol };`,
        `const d = "a", e = "b", f = "c";`,
      ),
    },
  },
  {
    name: "no-constant-binary-expression/relational",
    about: "checkRelationalComparisons is on unless the option says otherwise",
    config: rules([], { "no-constant-binary-expression": "error" }),
    files: { "a.js": lines(`a = 0 > 0;`, `a = (b?.c ?? 0 > 0) ? 1 : 2;`, `a = "a" < "b";`, `a = -1 <= +2;`, `a = undefined >= 5;`, `a = b > 0;`, "a = `` < ``;", `a = 1n < 2n;`) },
  },
  {
    name: "no-constant-binary-expression/relational-off",
    about: "the option",
    config: rules([], { "no-constant-binary-expression": ["error", { checkRelationalComparisons: false }] }),
    files: { "a.js": lines(`a = 0 > 0;`, `a = {} == b;`) },
  },
  {
    name: "no-shadow-restricted-names/namespace",
    about: "namespaces and the parameters of signatures",
    config: rules([], { "no-shadow-restricted-names": "error" }),
    files: {
      "a.ts": lines(`declare namespace globalThis { const a: 1; }`),
      "b.ts": lines(`namespace NaN {}`),
      "c.ts": lines(`type A = (...arguments: any[]) => void;`, `interface B { c(undefined: 1): void; (NaN: 1): void; new (NaN: 1): B }`),
      "d.d.ts": lines(`declare function d(Infinity: 1): void;`),
    },
  },
  {
    name: "explicit-function-return-type/ancestor",
    about: "oxlint_ancestor_has_return_type",
    config: rules(["typescript"], { "typescript/explicit-function-return-type": "error" }),
    files: {
      "a.ts": lines(
        `export function a(): P {`,
        `  return { b: (c?: unknown) => { return c ? 1 : 2; }, d(c) { return c; }, e: { f: () => 1 } };`,
        `}`,
        `export function g(): P {`,
        `  const h = { b: (c?: unknown) => 1, d(c: string) { return c; } };`,
        `  i(() => 1);`,
        `  j = () => 1;`,
        `  if (k) return l(() => 1);`,
        `  return h;`,
        `}`,
        `export const m: Q = n(() => 1);`,
        `export const o = n(() => 1);`,
        `export class R { s: Q = n(() => 1); t = n(() => 1); u(): P { return n(() => 1); } }`,
        `export const v = (): P => n(() => 1);`,
      ),
    },
  },
  {
    name: "no-console/computed",
    about: "nothing about console[a]",
    config: rules([], { "no-console": "error" }),
    files: { "a.js": lines(`console[a[b]]("c");`, `console["log"]("d");`, "console[`log`]('e');", `console[f];`, `console.log("g");`) },
  },
  {
    name: "default-case/comment-pattern",
    about: "the case is ignored",
    config: rules([], { "default-case": ["error", { commentPattern: "^skip default$" }] }),
    files: { "a.js": lines(`switch (a) {`, `  case 1:`, `  // Skip Default`, `}`, `switch (a) {`, `  case 1:`, `  // skip default`, `}`, `switch (a) {`, `  case 1:`, `  // no default`, `}`) },
  },
  {
    name: "no-implicit-coercion/template",
    about: "`string: false` is also about templates",
    config: rules([], { "no-implicit-coercion": ["error", { string: false, disallowTemplateShorthand: true }] }),
    files: { "a.js": lines("a = `${b}`;", `a = "" + b;`, `a = !!b;`) },
  },
  {
    name: "no-implicit-coercion/template-on",
    about: "the same with `string`",
    config: rules([], { "no-implicit-coercion": ["error", { disallowTemplateShorthand: true }] }),
    files: { "a.js": lines("a = `${b}`;", `a = "" + b;`) },
  },
  {
    name: "preserve-caught-error/place",
    about: "the statement",
    config: rules([], { "preserve-caught-error": "error" }),
    files: { "a.js": lines(`try {`, `  a();`, `} catch (b) {`, `  throw new Error(`, `    "c",`, `    { cause: d },`, `  );`, `}`, `try {`, `  a();`, `} catch (b) {`, `  throw new Error("c");`, `}`) },
  },
  {
    name: "max-lines/place",
    about: "the last byte of the file",
    config: rules([], { "max-lines": ["error", 2] }),
    files: { "a.js": lines(`a();`, `b();`, `c();`, `d();`), "b.js": "a();\nb();\nc();", "c.js": lines(`a();`, `b();`) },
  },
  {
    name: "no-regex-spaces/place",
    about: "the spaces",
    config: rules([], { "no-regex-spaces": "error" }),
    files: { "a.js": lines(`a = /^  b/;`, `a = /b   c  d/;`, `a = new RegExp("b  c");`) },
  },
  {
    name: "no-underscore-dangle/place",
    about: "the name",
    config: rules([], { "no-underscore-dangle": ["error", { enforceInMethodNames: true, enforceInClassFields: true, allowFunctionParams: false, allowInArrayDestructuring: false, allowInObjectDestructuring: false }] }),
    files: { "a.js": lines(`a = b._c;`, `a = this._d;`, `export function _e() {}`, `function f(_g, h_ = 1) {}`, `const _i = 1, j = 2;`, `const [_k] = a, { l: _m } = a;`, `class N { _o() {} _p = 1; #_q = 2; }`, `a = { _r() {} };`, `a = b[_s];`) },
  },
  {
    name: "prefer-named-capture-group/place",
    about: "the group",
    config: rules([], { "prefer-named-capture-group": "error" }),
    files: { "a.js": lines(`a = /x(ad|od)/;`, `a = /(b)(?<c>d)(e)/;`, `a = new RegExp("x(ad)");`) },
  },
  {
    name: "func-name-matching/place",
    about: "the name of the function",
    config: rules([], { "func-name-matching": "error" }),
    files: { "a.js": lines(`export const o = { a: 1, b: function c() {} };`, `const d = function e() {};`, `f = function g() {};`, `h.i = function j() {};`) },
  },
  {
    name: "no-redeclare/place",
    about: "the declaration before",
    config: rules([], { "no-redeclare": "error" }),
    files: { "a.ts": lines(`export interface A {}`, `const A = 1;`, `type B = string;`, `const B = 1;`, `export { A as C, B };`), "b.js": lines(`var a;`, `var a;`, `var a;`) },
  },
  {
    name: "no-useless-concat/parentheses",
    about: "they hide what is in them",
    config: rules([], { "no-useless-concat": "error" }),
    files: { "a.js": lines(`a = "b" + ("c" + d);`, `a = ("b") + "c";`, `a = (d + "b") + "c";`) },
  },
];
