declare function id<T>(x: T): T;
const i1 = id("a");
declare function pair<T>(a: T, b: T): T;
const i2 = pair(1, "s");
declare function cb<T>(f: (x: T) => void, v: T): T;
const i3 = cb((x: string) => {}, "a");
declare function arr<T>(x: T[]): T;
const i4 = arr([1, "a"]);
declare function un<T>(x: T | string[]): T;
const i5 = un(1); const i6 = un(["a"]);
declare function keys<T, K extends keyof T>(o: T, k: K): T[K];
const i7 = keys({ a: 1, b: "s" }, "a");
declare function mapped<T>(o: { [K in keyof T]: () => T[K] }): T;
const i8 = mapped({ a: () => 1, b: () => "s" });
declare function tpl<T extends string>(x: `a-${T}`): T;
const i9 = tpl("a-b");
declare function ret<T>(): T;
const i10: string = ret();
type ElementOf<T> = T extends (infer U)[] ? U : never;
const i11: ElementOf<string[]> = 1;
declare function con<T extends number>(x: T): T;
const i12 = con("s");
declare function two<T, U extends T>(a: T, b: U): U;
const i13 = two({ a: 1 }, { a: 1, b: 2 });
declare function tup<T extends unknown[]>(...args: T): T;
const i14 = tup(1, "a");
const i15: number = i1;
const i16: string = i8;
