declare let f1: (x: number) => string;
declare let f2: (x: string) => number;
f1 = f2;
declare let g1: { m(): { n(): string } };
declare let g2: { m(): { n(): number } };
g1 = g2;
declare let h1: new () => { a: string };
declare let h2: new () => { a: number };
h1 = h2;
declare let o1: { (x: number): void; (x: string): void };
declare let o2: { (x: boolean): void };
o1 = o2;
declare let p1: (x: number, y: number) => void;
declare let p2: (x: number) => void;
p2 = p1;
declare let q1: (x: any) => x is string;
declare let q2: (x: any) => boolean;
q1 = q2;
declare let k1: <T>(x: T) => T;
declare let k2: (x: string) => number;
k2 = k1;
