// Snippets for what the corpora have little of: where the binder of TypeScript and ESLint could disagree.
// `bun cases.ts --edge-cases` lists each with every source type, version and parser that applies.

export const javascript = [
  "function f(){ { const x = require('x'); x; } { const x = require('x'); x; } x; }",
  "if (a) { const fs = require('fs'); fs.a } else { const fs = require('fs'); fs.b }\nconst path = require('path'); path; module.exports = 1; exports.a = 2; module; exports;",
  "function f(a = g, b = h) { function g(){} var h; let i; }",
  "function f(a = arguments, b = () => arguments) { arguments; () => arguments; function g(){ arguments } }",
  "function f(a = () => b) { var b; }",
  "try {} catch (e) { var e = 1; e; } e;",
  "try {} catch ({a = 1, b: [c = d]}) { a; c; }",
  "var x = function g(g) { g; }; var y = function h() { var h; h; }; var z = function k() { k; };",
  "class A { [x]() { let x; } static [y] = y; [z] = () => z; static { var w; w; this; } }",
  "class A extends (class B { m() { B; A; } }) { m() { A; B } }",
  "with (a) { b; with (c) { d; var e; function f(){} } } e; f;",
  "a: for (;;) { break a; } a;",
  "({a, b: c, ...d} = e); [f, [g = h], ...i] = j; ({k = l} = m); [n.o, p[q]] = r;",
  "for (a in b); for ([c, d = e] of f); for (var g = 1 in h); for (let [i = j] of k) i; for (const l of l);",
  "a += b; c++; --d; e ||= f; g &&= h; i ??= j; (k) = l; [(m)] = n;",
  "var a; function a(){} var a = 1; function a(){}",
  "function f(a, a) { var a; function a(){} }",
  "let a = a; const b = () => b; var {c = c} = c;",
  "export default a; export { b, c as d }; export * from 'x'; export { e } from 'y'; var a, b, c;",
  "import a, { b as c, default as d } from 'x'; import * as e from 'y'; a; c; d; e; b;",
  "switch (a) { case b: let c; function d(){} break; default: c; d; } c; d;",
  "function f() { 'use strict'; a = 1; function g() { b = 2 } } c = 3; (function(){ d = 4 }); () => { 'use strict'; e = 5 };",
  "var f = async function* g() { yield g; await g; }; new.target; import.meta; import('x');",
  "label: { let label; label; }",
  "`${a}${`${b}`}`; tag`${c}`; a?.b?.[c]?.(d);",
  "({ get a() { return b }, set a(c) { c }, d() { arguments }, e: function(){ arguments }, f: () => arguments, [g]: h, i });",
  "/** @type {Foo} */ (a) = 1; const b = /** @type {any} */ (c); /** @typedef {number} T */ /** @template U @param {U} x */ function f(x) { f; x; }",
  "var undefined; undefined = 1; NaN; Infinity; eval('x'); globalThis;",
  "function f() { return; function g(){} } { function h(){} } h();",
  "for (var i = 0, j = i; i < j; i++) { let i; } for (let i = 0; i; i++) { var k; (() => i); }",
  "class A { static #p = 1; #q() { return #p in A } a = this.#q; }",
  "<A><a.b.c/><B.C></B.C><d e={f} {...g}>{h}</d><_x/><$y/></A>;",
];

export const typescript = [
  "namespace N { export type T = 1 } N; namespace M { export const a = 1 } M; declare namespace D { const x: number } D;",
  "const N = 1; function f() { namespace N { export type T = 1 } N; }",
  "enum E { A, B = A } enum E { C = A, D = C }  E.A;",
  "namespace N { export const a = 1; export interface I {} function h(){} } namespace N { a; let x: I; h; export const b = a; }",
  "interface I<T> { a: T } interface I<T> { b: T } class C<T> { a: T } interface C<T> { b: T }",
  "function f<T>(a: T, b: typeof a, c = a): typeof c { var d; let e: typeof d; return c }",
  "function f(a: typeof b): typeof b { var b; }",
  "type A<T> = T extends (infer U)[] ? U : T extends (a: infer V) => infer W ? [V, W] : U;",
  "type A<T> = T extends { [K in keyof T]: infer U } ? U : never; type B = { [K in 'a' as `x${K}`]: K };",
  "type F = <T>(a: T, b: typeof a) => T; type G = new <T>(a: T) => T; interface H { <T>(a: T): T; new <T>(a: T): T; m<T>(a: T): T; [k: string]: any; get x(): T; set x(v: T) }",
  "function isA(x: any): x is A {} function assertA(x: any): asserts x is A {} function assertB(x): asserts x {} class K { is(): this is K {} }",
  "import type A from 'a'; import { type B, C } from 'b'; import D = require('d'); import E = A.B.C; export import F = C.D; let a: A, b: B, c: C, d: D; A; B; E; F;",
  "export type { A }; export { type B, C }; export default D; type A = 1; type B = 1; const C = 1; interface D {}",
  "export = A; interface A {} ",
  "class A<T> extends B<T> implements C<T>, D.E { constructor(private a: T, public b = a) {} m<U>(this: A<T>, x: U): x is U {} }",
  "@dec(a) class A { @dec(b) m(@dec(c) p) {} @dec(d) f = e; @dec(() => A) static s; constructor(@dec(f) q) {} }",
  "const C = @dec(C) class C { static x = @dec class D {} }",
  "abstract class A { abstract m(a: number): void; abstract p: string; declare q: number; accessor r = s; m2(a); m2(a, b?) {} }",
  "declare function f(a: number): void; declare function f(a: string): void; function g(a); function g(a, b?) {}",
  "declare global { var x: number; interface Window {} } x; declare module 'm' { export const y: number; y } declare module 'n';",
  "namespace A.B.C { export const d = 1; d } A; namespace A {} ",
  "let a = <T,>(x: T) => x; let b = x as T; let c = <T>x; let d = x satisfies T; let e = x!; let f = x as const; let g = f<T>; new H<T>(); i<T>(); j<T>``;",
  "(a as any) = 1; (<any>b) = 2; c! = 3; (d satisfies any) = 4; (e as any)++; f!--; [g!, h as any] = i; ({ j: k! } = l); (m as any)! = 1;",
  "function f(this: Window, a) { this; } function g({a, b: [c]}: T, ...d: U[]) {}",
  "type T = typeof import('x'); type U = import('y').Z<V>; type W = typeof a.b.c; type X = typeof this; let y: unique symbol; type Y = [a: A, b?: B, ...c: C[]];",
  "enum E { 'a' = 1, b = a, ['c'] = 2, d = c, 'e-f' = 3 } const enum F { x = E.a } declare enum G { y }",
  "class A { x = () => { var y; arguments; }; static z = function() { arguments }; w = class { v = A } }",
  "for (const x of [] as T[]) {} for (let i: number = 0;;) {} try {} catch (e: unknown) {} ",
  "function f() { type T = 1; interface I {} enum E {} namespace N {} class C {} let x: T | I | E | N.X | C; }",
  "let x: Array<string>; let y: Promise<T>; Symbol; let z: Symbol; undefined; let w: undefined;",
  "export default function f<T>() {} export default class {} ",
  "export default interface I {} let i: I;",
  "export declare const a: number; export declare function b(): void; export abstract class C {} export namespace D {} export enum E {} export type F = 1; a; b; C; D; E; let f: F;",
  "function overload(): void; function overload(a?) {} export function ex(): void; export function ex(a?) {}",
  "const a = { b<T>(c: T) {}, get d(): T { return 1 }, async *e() {} };",
  "type R<T> = { [P in keyof T]-?: T[P] } & Record<string, R<T>>;",
  "let v = function <T>(this: T) {}; let u = async <T,>(a: T): Promise<T> => a;",
  "class P { constructor(readonly a = 1, protected b?: typeof a) { a; b } }",
  "interface J extends K.L<M>, N {} class O implements K.L<M> {} class Q extends K.L<M> {}",
];

export const tsx = [
  "import React from 'react'; const a = <div/>;",
  "import { h, Fragment } from 'preact'; const a = <><b:c/></>;",
  "function f() { const React = 1; return <A<T> b={c}>{d}</A>; } import React from 'r';",
  "type React = 1; <a/>;",
];
