name: Setup Bun
description: An internal version of the 'oven-sh/setup-bun' action.

inputs:
  bun-version:
    type: string
    description: "The version of bun to install: 'latest', 'canary', 'bun-v1.2.0', etc."
    default: latest
    required: false

runs:
  using: composite
  steps:
    - name: Setup Bun
      shell: bash
      run: |
        proto='https'
        hostname='github.com'
        owner='oven-sh'
        repo='bun'
        branch='main'
        filepath='src/cli/install.sh'
        base_url="${proto}://${hostname}${port:+:${port-}}/${owner}/${repo}"

        release_args=()
        case "${{ inputs.bun-version }}" in
          latest) ;;
          canary) release_args=("canary");;
          bun-v*) release_args=("${{ inputs.bun-version }}");;
          *)      release_args=("bun-v${{ inputs.bun-version }}");;
        esac

        case "${tag-}${branch-}${commit-}" in
          [a-f0-9]*[a-f0-9]) specifier="${commit}";;
          bun-v*) specifier="refs/tags/${tag}";;
          *) specifier="refs/heads/${branch}";;
        esac

        install_script_url="${base_url}/raw/${specifier}/${filepath}"

        curl -fsSLo "${{ runner.temp }}/install.sh" "${install_script_url}"
        SHELL=sh BUN_INSTALL=/usr/local bash "${{ runner.temp }}/install.sh" "${release_args[@]}"
        rm -v -f "${{ runner.temp }}/install.sh"
