// GENERATED: re-run build-prefixes.js with .rs output
// source: src/css/compat.zig (5397 lines) — autogenerated browser feature compat tables
// exports: pub enum Feature { ... } with is_compatible(&self, Browsers) / is_partially_compatible(&self, Browsers); uses bun_css::targets::Browsers
