// Scratch wrapper: the real internal/ast files plus the diagnostic names that the tree expects under crate::ast.
#[path = "/workspace/wt/typecheck/src/typecheck/ast/ast.rs"]
pub mod ast;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/ast_generated.rs"]
pub mod ast_generated;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/builder.rs"]
pub mod builder;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/checkflags.rs"]
pub mod checkflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/factory.rs"]
pub mod factory;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/file.rs"]
pub mod file;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/flags.rs"]
pub mod flags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/flow.rs"]
pub mod flow;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/functionflags.rs"]
pub mod functionflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/ids.rs"]
pub mod ids;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/kind_generated.rs"]
pub mod kind_generated;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/layout.rs"]
pub mod layout;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/modifierflags.rs"]
pub mod modifierflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/node_methods.rs"]
pub mod node_methods;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/nodeflags.rs"]
pub mod nodeflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/open.rs"]
pub mod open;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/precedence.rs"]
pub mod precedence;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/publish.rs"]
pub mod publish;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/reader.rs"]
pub mod reader;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/stable.rs"]
pub mod stable;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/subtreefacts.rs"]
pub mod subtreefacts;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/symbol.rs"]
pub mod symbol;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/symbolflags.rs"]
pub mod symbolflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/tokenflags.rs"]
pub mod tokenflags;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/utilities.rs"]
pub mod utilities;
#[path = "/workspace/wt/typecheck/src/typecheck/ast/visitor.rs"]
pub mod visitor;
pub use ast::*;
pub use ast_generated::*;
pub use builder::*;
pub use checkflags::*;
pub use factory::*;
pub use file::*;
pub use flow::*;
pub use functionflags::*;
pub use ids::*;
pub use kind_generated::*;
pub use layout::*;
pub use modifierflags::*;
pub use node_methods::*;
pub use nodeflags::*;
pub use open::*;
pub use precedence::*;
pub use publish::*;
pub use reader::*;
pub use subtreefacts::*;
pub use symbol::*;
pub use symbolflags::*;
pub use tokenflags::*;
pub use utilities::*;
pub use visitor::*;
pub use crate::ast_extra::{Arg, DiagnosticId, DiagnosticStore};
