// Inputs of the probe, part 3: where an escaped reserved word is no keyword of the place it stands in, and leftovers of parts 1 and 2.
// usage: node make-inputs3.cjs > inputs3.json
const out = [];
let group = "";
const g = name => { group = name; };
const t = (s, l) => out.push({ g: group, s, l: l || "ts" });
const esc = w => "\\u00" + w.charCodeAt(0).toString(16).padStart(2, "0") + w.slice(1);

g("K3 an escaped reserved word where the word itself is an error or stands after an expression");
t(`${esc("default")}`);
t(`${esc("default")}: x;`);
t(`${esc("catch")} (e) {}`);
t(`${esc("finally")} {}`);
t(`${esc("case")} 1:`);
t(`${esc("extends")} A`);
t(`${esc("in")} x`);
t(`${esc("instanceof")} x`);
t(`x ${esc("extends")} y;`);
t(`x ${esc("if")} y;`);
t(`x ${esc("var")} y;`);
t(`x ${esc("else")} y;`);
t(`x ${esc("typeof")} y;`);
t(`x ${esc("new")} y;`);
t(`x ${esc("this")};`);
t(`x ${esc("class")} {}`);
t(`var x ${esc("in")} y;`);
t(`for (var x ${esc("in")} y) {}`);
t(`for (x ${esc("in")} y) {}`);
t(`for (var x = 1 ${esc("in")} y;;) {}`);
t(`[x ${esc("in")} y];`);
t(`f(x ${esc("in")} y);`);
t(`f(x ${esc("instanceof")} y);`);
t(`x ? a ${esc("in")} b : c;`);
t(`({ a: x ${esc("in")} y });`);
t(`(x ${esc("in")} y);`);
t(`x = y ${esc("in")} z;`);
t(`if (x ${esc("in")} y) {}`);
t(`let x: ${esc("var")};`);
t(`let x: ${esc("if")};`);
t(`let x: ${esc("class")};`);
t(`let x: ${esc("function")};`);
t(`let x: ${esc("new")} () => void;`);
t(`let x: ${esc("import")}("a");`);
t(`let x: ${esc("true")};`);
t(`let x: A ${esc("extends")} B ? 1 : 2;`);
t(`let x: A ${esc("in")} B;`);
t(`let x: [A ${esc("in")} B];`);
t(`function f(): ${esc("void")} {}`);
t(`class C { m(): ${esc("this")} { return this } }`);
t(`x as ${esc("null")};`);
t(`if (x) ${esc("return")};`);
t(`if (x) ${esc("var")} y;`);
t(`l: ${esc("break")} l;`);
t(`function f() { ${esc("export")} {} }`);
t(`x = ${esc("void")} 0;`);
t(`x = !${esc("delete")} a.b;`);
t(`x = a + ${esc("typeof")} b;`);
t(`x = (${esc("this")});`);
t(`x = [${esc("null")}];`);
t(`x = { a: ${esc("true")} };`);
t(`f(${esc("this")});`);
t(`f(${esc("new")} A);`);
t(`x = a ? ${esc("this")} : b;`);
t(`return ${esc("this")};`);
t(`() => ${esc("this")};`);
t(`\`\${${esc("this")}}\`;`);
t(`x = ${esc("if")};`);
t(`x = ${esc("else")};`);
t(`x = ${esc("in")};`);
t(`x = ${esc("case")};`);
t(`(${esc("var")});`);
t(`${esc("var")} ${esc("var")};`);
t(`${esc("if")} (${esc("true")}) ${esc("return")};`);
t(`class ${esc("extends")} {}`);
t(`class C { ${esc("var")} }`);
t(`class C { ${esc("var")} x }`);
t(`enum E { ${esc("if")} b }`);
t(`import ${esc("default")} from "a";`);
t(`import { ${esc("default")} } from "a";`);
t(`export { ${esc("default")} };`);
t(`export ${esc("default")} class {}`);
t(`export ${esc("default")}`);
t(`export ${esc("var")} x = 1;`);
t(`export ${esc("const")} x = 1;`);
t(`export ${esc("class")} C {}`);
t(`export ${esc("function")} f() {}`);
t(`declare ${esc("var")} x;`);
t(`declare ${esc("class")} C {}`);
t(`async ${esc("function")} f() {}`);
t(`abstract ${esc("class")} C {}`);
t(`const ${esc("enum")} E {}`);
t(`@d ${esc("class")} C {}`);
t(`try {} ${esc("catch")} (e) {} ${esc("finally")} {}`);
t(`do x; ${esc("while")} (y);`);
t(`if (x) y; ${esc("else")} z;`);
t(`switch (x) { case 1: ${esc("default")}: }`);
t(`switch (x) { ${esc("default")}: ${esc("case")} 1: }`);
t(`new ${esc("class")} {};`);
t(`typeof ${esc("this")};`);
t(`x = ${esc("function")}*() {};`);
t(`(${esc("function")}() {})();`);
t(`x.y = ${esc("null")};`);
t(`for (${esc("var")} i = 0;;) {}`);
t(`for (${esc("const")} x of y) {}`);
t(`for (;;) ${esc("break")};`);
t(`label: for (;;) ${esc("continue")} label;`);
t(`${esc("throw")} new Error();`);
t(`x = ${esc("super")};`);
t(`${esc("var")} x = 1;`, "tsx");
t(`${esc("var")} x = 1;`, "dts");

g("X leftovers: import attributes, enum names, class names");
t('import a from "a" with { type: 1 };');
t('import a from "a" with { type: "json" "b": "c" };');
t('import a from "a" with { type: "json"; };');
t('import a from "a" with { type };');
t('import a from "a" with { "a b": "c" };');
t('import a from "a" with { if: "c" };');
t('import a from "a" with { , };');
t('import a from "a" with { type: "json",, };');
t('import a from "a" with { type: f() };');
t('export * from "a" with { type: "json" }\nwith (x) {}');
t('import a from "a"\nwith (x) {}');
t('export * from "a"\nwith (x) {}');
t("class {}");
t("class 1 {}");
t("class enum {}");
t("class extends A {}");
t("class implements I {}");
t("class implements {}");
t("class if {}");
t("class { x }");
t("class ;");
t("class C");
t("class C ;");
t("class C 1 {}");
t("class C D {}");
t("class C<T> D {}");
t("class C {");
t("class C { x");
t("class C { m() {");
t("export default class {}");
t("export default class implements I {}");
t("(class {});");
t("(class implements I {});");
t("(class implements {});");
t("(class 1 {});");
t("x = class extends A {};");
t("class await {}");
t("class yield {}");
t("class let {}");
t("class static {}");
t("class implements implements I {}");
t("class {}", "js");
t("class 1 {}", "js");
process.stdout.write(JSON.stringify(out, null, 0) + "\n");
