// Corpus generator of the differential harness (regression guard for parses without lint).
//
//   bun gen.mjs small      valid type forms and every one-token deletion            -> corpus.small.json
//   bun gen.mjs medium     small, plus replacements and insertions from MUT_TOKENS  -> corpus.medium.json
//   bun gen.mjs targeted   whole programs: statement-level TypeScript productions   -> corpus.targeted.json
//
// A form is one piece of type syntax. The harness puts every form into every context of CONTEXTS.
// A source is a whole program and is used as it is. Validity is not decided here: oracle.mjs asks tsc.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

export const CONTEXTS = {
  alias: "type X = %T%;",
  var: "let x: %T%;",
  field: "class C { @d x: %T%; }",
  param: "class C { @d m(a: %T%) {} }",
  ctor: "@d class C { constructor(a: %T%) {} }",
  ret: "class C { @d m(): %T% { return x; } }",
  fnparam: "function f(a: %T%) {}",
  fnret: "function f(): %T% { return x; }",
  arrowparam: "let f = (a: %T%) => a;",
  arrowret: "let f = (a): %T% => a;",
  ternary: "let v = a ? (b): %T% => c : d;",
  as: "let v = x as %T%;",
  satisfies: "let v = x satisfies %T%;",
  angle: "let v = <%T%>x;",
  targ: "f<%T%>(x);",
  tparam: "function f<U extends %T%>() {}",
  heritage: "class C implements %T% {}",
  iextends: "interface I extends %T% {}",
};

const kw = list => list.split(" ");
const CONTEXTUAL = kw(
  "type as is asserts infer keyof readonly unique abstract declare namespace module global out satisfies accessor override get set async await of from using defer static public private protected constructor require intrinsic",
);
const RESERVED = kw("in new function void this typeof import null true false class delete var let const enum extends");

const F = [];
const add = (prod, ...texts) => texts.forEach(t => F.push({ prod, t }));

add("keyword", ...kw("any unknown never void null undefined string number boolean bigint symbol object intrinsic"));
add("literal", "'a'", '"a"', "1", "-1", "- 1", "+1", "1n", "-1n", "0x10", "-0x10", "1e3", "0b1", "0o7", ".5", "1_000", "true", "false", "-a", "-true");
add("template", "`a`", "`a${string}b`", "`${A}${B}`", "`a${`b${C}`}d`", "`${A | B}`", "`${infer U}`", "`${number}px`");
add(
  "reference",
  "A",
  "A.B",
  "A.B.C",
  "A<B>",
  "A<B, C>",
  "A<B,>",
  "A<>",
  "A<B<C>>",
  "A<B<C<D>>>",
  "A<B<C>, D<E>>",
  "A.B<C>",
  "A.B.C<D>[]",
  "A<B>.C",
  "A<B>[]",
  "A<B[]>",
  "A<() => void>",
  "A<(B)>",
  "A<B | C>",
  "A<typeof b>",
  "A<B extends C ? D : E>",
  "A\n<B>",
  "A<\nB\n>",
  "A.\nB",
  "A\n.B",
  "Function",
  "Object",
  "Array<A>",
  "Promise<A>",
);
add("contextual", ...CONTEXTUAL, ...CONTEXTUAL.map(k => `A.${k}`), ...CONTEXTUAL.map(k => `${k}.A`), ...CONTEXTUAL.map(k => `${k}<A>`));
add("reserved-name", ...RESERVED.map(k => `A.${k}`));
add("array", "A[]", "A[][]", "A []", "A\n[]", "A[", "A[]]", "void[]", "null[]", "'a'[]", "1[]", "this[]", "(A)[]", "A<B>[][]");
add(
  "tuple",
  "[]",
  "[A]",
  "[A, B]",
  "[A,]",
  "[,]",
  "[A,,B]",
  "[a: A]",
  "[a?: A]",
  "[a: A, b: B]",
  "[a: A, B]",
  "[...A]",
  "[...A[]]",
  "[...a: A[]]",
  "[...a?: A[]]",
  "[A?]",
  "[A?, B?]",
  "[A?, B]",
  "[a: A?]",
  "[a?: A?]",
  "[a: A, b?: B, ...c: C[]]",
  "[A, ...B[], C]",
  "[...A, B]",
  "[...A, ...B]",
  "[string]",
  "[string?]",
  "[...string[]]",
  "[a: string]",
  "['a']",
  "[1]",
  "[-1]",
  "[`a`]",
  "[A | B]",
  "[A, B | C]",
  "[() => void]",
  "[(a: A) => B]",
  "[a: () => void]",
  "[a: (b: B) => C]",
  "[new () => A]",
  "[a: new () => A]",
  "[[A]]",
  "[[a: A]]",
  "[A[]]",
  "[A.B]",
  "[A<B>]",
  "[A<B<C>>]",
  "[typeof a]",
  "[keyof A]",
  "[a: keyof A]",
  "[A extends B ? C : D]",
  "[a: A extends B ? C : D]",
  "[a?: A extends B ? C : D]",
  "[{ a: A }]",
  "[a: { a: A }]",
  "[a.b: A]",
  "[a<B>: A]",
  "[this]",
  "[a: this]",
  "[A?: B]",
  "[a: A | B]",
  "[a: infer U]",
  "[infer U]",
  "[infer U extends A]",
  "[...infer U]",
  "[a: A, ...b: infer U]",
  "readonly [A, B]",
  "readonly [a: A]",
  "readonly []",
  "[readonly A[]]",
  "[a: readonly A[]]",
  "[unique symbol]",
  "[a: unique symbol]",
  "[asserts a]",
  "[a is A]",
  ...[...CONTEXTUAL, ...RESERVED].flatMap(k => [`[${k}: A]`, `[${k}?: A]`, `[...${k}: A[]]`, `[${k}]`]),
);
add(
  "union",
  "A | B",
  "A & B",
  "A | B | C",
  "A & B & C",
  "| A",
  "& A",
  "| A | B",
  "& A & B",
  "A | B & C",
  "A & B | C",
  "A | (B & C)",
  "(A | B) & C",
  "| A & B",
  "& A | B",
  "A | | B",
  "A & & B",
  "A |",
  "A &",
  "|",
  "A | & B",
  "A\n| B",
  "A |\nB",
  "A | B[]",
  "A[] | B",
  "A | keyof B",
  "A | typeof b",
  "A | () => void",
  "A | (() => void)",
  "A | new () => B",
  "(() => void) | A",
  "() => void | A",
  "() => A & B",
  "A | 'a' | 1 | -1 | true | null | undefined",
  "string | number",
  "A | null",
  "A | undefined",
  "null | undefined",
  "A | void",
  "A | never",
  "A | any",
  "A | unknown",
  "A & never",
  "string & {}",
  "'a' | 'b'",
  "1 | 2",
  "true | false",
  "1n | 2n",
  "A | B<C>",
  "A<B> | C<D>",
  "A | infer U",
);
add(
  "conditional",
  "A extends B ? C : D",
  "A extends B ? C : D extends E ? F : G",
  "A extends B ? C extends D ? E : F : G",
  "A extends (B extends C ? D : E) ? F : G",
  "(A extends B ? C : D) extends E ? F : G",
  "A | B extends C ? D : E",
  "A & B extends C ? D : E",
  "A | B & C extends D ? E : F",
  "keyof A extends B ? C : D",
  "readonly A[] extends B ? C : D",
  "unique symbol extends B ? C : D",
  "typeof a extends B ? C : D",
  "A[] extends B ? C : D",
  "A[B] extends C ? D : E",
  "A<B> extends C ? D : E",
  "A extends B[] ? C : D",
  "A extends B | C ? D : E",
  "A extends B & C ? D : E",
  "A extends keyof B ? C : D",
  "A extends B ? C | D : E | F",
  "A extends B ? C : D | E",
  "A extends B ? keyof C : readonly D[]",
  "A extends B ? () => C : D",
  "A extends B ? C : () => D",
  "A extends () => B ? C : D",
  "A extends new () => B ? C : D",
  "() => A extends B ? C : D",
  "new () => A extends B ? C : D",
  "(a: A) => a is B extends C ? D : E",
  "A extends B\n? C\n: D",
  "A\nextends B ? C : D",
  "A extends B ? C",
  "A extends B ?",
  "A extends B",
  "A extends",
  "A extends B : C",
  "A extends B ? C : ",
  "A extends B ? : D",
  "A ? B : C",
  "A extends B ? C : D : E",
  "A extends B extends C ? D : E",
  "A extends B extends C ? D : E ? F : G",
  "[A] extends [B] ? C : D",
  "{ a: A } extends B ? C : D",
  "'a' extends A ? B : C",
  "1 extends A ? B : C",
  "-1 extends A ? B : C",
  "`a` extends A ? B : C",
  "this extends A ? B : C",
  "any extends A ? B : C",
  "void extends A ? B : C",
  "import('a') extends A ? B : C",
  "A extends B ? C : D[]",
  "(A extends B ? C : D)[]",
  "A extends B ? [C] : [D]",
  "A extends B ? { a: C } : { a: D }",
);
add(
  "infer",
  "infer U",
  "infer",
  "infer U extends A",
  "A extends infer U ? U : never",
  "A extends (infer U)[] ? U : never",
  "A extends infer U[] ? U : never",
  "A extends infer U extends B ? U : never",
  "A extends (infer U extends B) ? U : never",
  "A extends [infer U extends B] ? U : never",
  "A extends [infer U, ...infer R] ? U : R",
  "A extends [infer U extends B, ...infer R extends C[]] ? U : R",
  "A extends (infer U extends B ? C : D) ? E : F",
  "A extends infer U extends B ? C : D ? E : F",
  "A extends (...a: infer P) => infer R ? [P, R] : never",
  "A extends (...a: infer P) => infer R extends B ? P : R",
  "A extends new (...a: infer P) => infer R ? P : R",
  "A extends { a: infer U } ? U : never",
  "A extends { a: infer U extends B } ? U : never",
  "A extends { [K in infer U]: V } ? U : never",
  "A extends `${infer H}${infer T}` ? H : T",
  "A extends `${infer H extends number}` ? H : never",
  "A extends B<infer U> ? U : never",
  "A extends B<infer U extends C> ? U : never",
  "A extends B<infer U, infer V> ? U | V : never",
  "A extends () => infer R extends B ? R : never",
  "A extends Promise<infer U> ? U : A",
  "A extends infer U | infer V ? U : V",
  "A extends infer U & B ? U : never",
  "A extends keyof infer U ? U : never",
  "A extends (infer U)[keyof B] ? U : never",
  "A extends infer infer ? infer : never",
  "A extends infer extends ? 1 : 2",
  "A extends infer in ? 1 : 2",
);
add(
  "mapped",
  "{ [K in T]: V }",
  "{ [K in T]?: V }",
  "{ [K in T]+?: V }",
  "{ [K in T]-?: V }",
  "{ readonly [K in T]: V }",
  "{ +readonly [K in T]: V }",
  "{ -readonly [K in T]: V }",
  "{ -readonly [K in keyof T]-?: T[K] }",
  "{ +readonly [K in keyof T]+?: T[K] }",
  "{ [K in T as U]: V }",
  "{ [K in keyof T as `a${K}`]: T[K] }",
  "{ [K in keyof T as K extends A ? B : never]: T[K] }",
  "{ readonly [K in T as U]?: V }",
  "{ [K in T] }",
  "{ [K in T]; }",
  "{ [K in T]: V; }",
  "{ [K in T]: V, }",
  "{ [K in T]?: V; }",
  "{ [K in T]: V; a: A }",
  "{ a: A; [K in T]: V }",
  "{ [K in T]: V; [L in U]: W }",
  "{ [K in A | B]: V }",
  "{ [K in A extends B ? C : D]: V }",
  "{ [K in T]: A extends B ? C : D }",
  "{ [K in T]: () => void }",
  "{ [K in T]: { [L in K]: V } }",
  "{ [K in T as]: V }",
  "{ [K in]: V }",
  "{ [K in T]- : V }",
  "{ [K in T]+: V }",
  "{ [K in T]-: V }",
  "{ + [K in T]: V }",
  "{ - [K in T]: V }",
  "{ -readonly a: A }",
  "{ +readonly a: A }",
  "{ readonly +[K in T]: V }",
  "{ [in in T]: V }",
  "{ [K in in T]: V }",
  "{ [as in T as as]: V }",
  "{ [readonly in T]: V }",
  "{ [K extends T]: V }",
  "{ [K of T]: V }",
  "{\n[K in T]: V\n}",
  "{ [K in T]: V } | A",
  "{ [K in T]: V }[]",
  "{ [K in T]: V }[K]",
);
add("indexed", "A[B]", "A['b']", "A[number]", "A[B][C]", "A[B[C]]", "A[keyof A]", "A[][B]", "A[B][]", "A[\nB]", "A\n[B]", "A[B | C]", "A[B extends C ? D : E]", "A[]", "A[B", "A[B]]", "A[B, C]", "A[...B]", "A.B[C]", "A<B>[C]", "typeof a[B]", "keyof A[B]", "(keyof A)[B]", "A[typeof b]", "A[-1]", "A[`a`]", "'a'[number]", "this['a']", "any[]['a']");
add(
  "operator",
  "keyof A",
  "keyof A[]",
  "keyof A | B",
  "keyof (A | B)",
  "keyof typeof a",
  "keyof keyof A",
  "keyof readonly A[]",
  "keyof A.B",
  "keyof A<B>",
  "keyof A[B]",
  "keyof { a: A }",
  "keyof [A]",
  "keyof 'a'",
  "keyof any",
  "keyof this",
  "keyof () => void",
  "keyof (() => void)",
  "keyof new () => A",
  "keyof",
  "keyof\nA",
  "unique symbol",
  "unique symbol[]",
  "unique\nsymbol",
  "unique A",
  "unique symbol | A",
  "unique unique symbol",
  "keyof unique symbol",
  "readonly A[]",
  "readonly [A]",
  "readonly A",
  "readonly A[][]",
  "readonly readonly A[]",
  "readonly (A[])",
  "readonly Array<A>",
  "readonly string[]",
  "readonly A[] | B",
  "readonly keyof A",
  "readonly unique symbol",
  "readonly\nA[]",
  "readonly () => void",
  "readonly { a: A }",
  "readonly typeof a",
  "readonly 'a'[]",
);
add(
  "query",
  "typeof a",
  "typeof a.b",
  "typeof a.b.c",
  "typeof a<B>",
  "typeof a.b<C>",
  "typeof a<B>[]",
  "typeof a<B<C>>",
  "typeof a<B>.c",
  "typeof a[]",
  "typeof a[number]",
  "typeof a['b']",
  "typeof this",
  "typeof this.a",
  "typeof this.a.b",
  "typeof import('x')",
  "typeof import('x').a",
  "typeof import('x').a<B>",
  "typeof a.#b",
  "typeof a | B",
  "typeof a & B",
  "typeof globalThis",
  "typeof",
  "typeof new",
  "typeof a\n<B>",
  "typeof a\n.b",
  "typeof a.\nb",
  "typeof\na",
  "typeof typeof a",
  "typeof keyof a",
  "typeof a.b()",
  "typeof a()",
  "typeof 'a'",
  "typeof 1",
  "typeof a?.b",
  "typeof a!",
  "typeof (a)",
  "typeof a.class",
  "typeof a.new",
  "typeof a.in",
  ...CONTEXTUAL.map(k => `typeof ${k}`),
  ...RESERVED.map(k => `typeof ${k}`),
);
add(
  "import-type",
  "import('x')",
  'import("x")',
  "import('x').A",
  "import('x').A.B",
  "import('x').A<B>",
  "import('x').A.B<C, D>",
  "import('x')<A>",
  "import('x')[]",
  "import('x')['a']",
  "import('x').A[]",
  "import('x') | A",
  "import('x', { with: { 'resolution-mode': 'import' } })",
  "import('x', { with: { 'resolution-mode': 'require' } }).A",
  "import('x', { with: { 'resolution-mode': 'import' } }).A<B>",
  "import('x', { assert: { 'resolution-mode': 'import' } })",
  "import('x', { with: { 'resolution-mode': 'import', } })",
  "import('x', { with: { 'resolution-mode': 'import' }, })",
  "import('x', { with: { 'resolution-mode': 'import' } },)",
  "import('x', { with: {} })",
  "import('x', {})",
  "import('x', { with: { a: 'b', c: 'd' } })",
  "import('x', { with: { a: 1 } })",
  "import('x', { a: { b: 'c' } })",
  "import('x', A)",
  "import('x',)",
  "import(`x`)",
  "import(x)",
  "import(A.B)",
  "import('x' | 'y')",
  "import()",
  "import",
  "import.meta",
  "import('x').default",
  "import('x').new",
  "import('x').#a",
  "import\n('x')",
  "import('x')\n.A",
  "import('x').\nA",
);
add(
  "function-type",
  "() => void",
  "(a: A) => B",
  "(a) => B",
  "(a, b) => C",
  "(a: A, b: B) => C",
  "(a?: A) => B",
  "(a?) => B",
  "(a?, b?) => C",
  "(...a: A[]) => B",
  "(...a) => B",
  "(a: A, ...b: B[]) => C",
  "(...a: A[], b: B) => C",
  "(...a?: A[]) => B",
  "(a = 1) => void",
  "(a: A = 1) => void",
  "(a?: A = 1) => void",
  "(a = 1, b = 2) => void",
  "(a = () => 1) => void",
  "(a = b as C) => void",
  "(this: A) => void",
  "(this: A, b: B) => void",
  "(this) => void",
  "(this?: A) => void",
  "(a: A, this: B) => void",
  "({ a, b }: A) => void",
  "({ a, b }) => void",
  "({ a, b }?: A) => void",
  "([a, b]: A) => void",
  "([a, b]) => void",
  "([a, b]?: A) => void",
  "({ a: { b } }: A) => void",
  "({ a: [b] }: A) => void",
  "({ a: b }: A) => void",
  "({ a = 1 }: A) => void",
  "({ a: b = 1 }: A) => void",
  "([a = 1]: A) => void",
  "({ ...a }: A) => void",
  "([...a]: A) => void",
  "([, a]: A) => void",
  "([a, , b]: A) => void",
  "({ 'a': b }: A) => void",
  "({ 1: b }: A) => void",
  "({ [a]: b }: A) => void",
  "({}: A) => void",
  "([]: A) => void",
  "({ a, b } = c) => void",
  "(...{ a }: A) => void",
  "(...[a]: A) => void",
  "<T>(a: T) => T",
  "<T extends A>(a: T) => T",
  "<T = A>(a: T) => T",
  "<T extends A = B>() => T",
  "<T, U>(a: T, b: U) => [T, U]",
  "<T, U extends T>() => void",
  "<const T>() => T",
  "<in T>() => T",
  "<out T>() => T",
  "<in out T>() => T",
  "<T,>() => void",
  "<>() => void",
  "<T extends A<B>>() => void",
  "<T extends A<B<C>>>() => void",
  "<T = A<B>>() => void",
  "<T extends keyof A>() => T",
  "<T extends A extends B ? C : D>() => T",
  "<T>\n(a: T) => T",
  "(a: A,) => B",
  "(a,) => B",
  "(,) => B",
  "(a: A) => (b: B) => C",
  "(a: A) => a is B",
  "(a: A) => asserts a",
  "(a: A) => asserts a is B",
  "(this: A) => this is B",
  "() => asserts this",
  "() => asserts this is A",
  "() => this",
  "() => asserts",
  "() => is",
  "(asserts: A) => asserts asserts",
  "(is: A) => is is B",
  "(a: A) => a\nis B",
  "(a: A) => asserts\na",
  "(public a: A) => void",
  "(private a: A) => void",
  "(readonly a: A) => void",
  "(static a: A) => void",
  "(a!: A) => void",
  "(a: A) => ",
  "(a: A) =>",
  "(a: A)",
  "(a: ) => void",
  "(a:) => void",
  "(: A) => void",
  "(a: A b: B) => void",
  "(a: A;) => void",
  "(a: A) = > B",
  "(a: A) >= B",
  "(a: A): B",
  "(a.b: A) => void",
  "(a<B>) => void",
  "('a') => void",
  "(1) => void",
  "(a | b) => void",
  "(A[]) => void",
  "(a: A) => B | C",
  "(a: A) => B[]",
  "(a: A) => B extends C ? D : E",
  "(a: A) => keyof B",
  "(a: A) => typeof b",
  "(a: A) => { a: A }",
  "(a: A) => [A]",
  "(a: (b: B) => C) => D",
  "(a: new () => A) => B",
  "(a: A | B, c: C & D) => void",
  "(a: A extends B ? C : D) => void",
  "(\na: A,\nb: B\n) => C",
  "(a: A)\n=> B",
  "async () => void",
  "function (a: A): B",
  "function",
  ...[...CONTEXTUAL, ...RESERVED].flatMap(k => [`(${k}: A) => void`, `(${k}) => void`, `(${k}?: A) => void`, `(...${k}: A[]) => void`]),
  ...CONTEXTUAL.map(k => `<${k}>() => ${k}`),
);
add(
  "constructor-type",
  "new () => A",
  "new (a: A) => B",
  "new (a?: A, ...b: B[]) => C",
  "new <T>(a: T) => A",
  "new <T extends A = B>() => T",
  "abstract new () => A",
  "abstract new <T>() => A",
  "abstract new (a: A) => B",
  "new () => new () => A",
  "new () => () => A",
  "() => new () => A",
  "new () => A | B",
  "new () => A[]",
  "new",
  "new A",
  "new A()",
  "new ()",
  "new () =>",
  "new (a) => A",
  "new ({ a }: A) => B",
  "new (a = 1) => A",
  "new (this: A) => B",
  "abstract",
  "abstract new",
  "abstract A",
  "abstract () => A",
  "abstract\nnew () => A",
  "new\n() => A",
  "abstract abstract new () => A",
  "new abstract () => A",
  "new () => asserts a",
  "new (a: A) => a is B",
);
add("parenthesized", "(A)", "((A))", "(A | B)[]", "(A & B) | C", "(() => void)[]", "(new () => A)[]", "(typeof a)[]", "(keyof A)[]", "(A extends B ? C : D)[]", "(A)[B]", "(A)<B>", "(A).B", "()", "(A", "A)", "(A, B)", "(A,)", "('a')", "(1)", "(-1)", "(a: A)", "(this)", "(infer U)", "(\nA\n)", "(A)\n[]", "({ a: A })", "([A])", "(A | B)", "(| A)", "(A?)", "(...A)", "(a)", "(a.b)", "(a<B>)", "(a?.b)", "(asserts a)", "(a is A)", "(unique symbol)", "(readonly A[])");
add(
  "type-literal",
  "{}",
  "{ a: A }",
  "{ a: A; b: B }",
  "{ a: A, b: B }",
  "{ a: A\n b: B }",
  "{ a: A; }",
  "{ a: A, }",
  "{ a: A;; }",
  "{ a: A,, }",
  "{ ; }",
  "{ , }",
  "{ a: A b: B }",
  "{ a?: A }",
  "{ a?: A; b?: B }",
  "{ a!: A }",
  "{ readonly a: A }",
  "{ readonly a?: A }",
  "{ readonly readonly: A }",
  "{ readonly readonly a: A }",
  "{ readonly: A }",
  "{ readonly?: A }",
  "{ readonly }",
  "{ readonly; }",
  "{ readonly(): A }",
  "{ readonly<T>(): A }",
  "{ readonly\na: A }",
  "{ a }",
  "{ a; b }",
  "{ a, b }",
  "{ a\n b }",
  "{ a?; }",
  "{ a? }",
  "{ a(): void }",
  "{ a?(): void }",
  "{ a(b: B): C }",
  "{ a<T>(x: T): T }",
  "{ a?<T>(x: T): T }",
  "{ a() }",
  "{ a(); }",
  "{ a(b) }",
  "{ a(b, c?) }",
  "{ a(): void; b(): void }",
  "{ a(): void\n b(): void }",
  "{ a(): void, b(): void }",
  "{ a(): void b(): void }",
  "{ a(this: A): void }",
  "{ a({ b }: B): void }",
  "{ a(b = 1): void }",
  "{ a(...b: B[]): void }",
  "{ a(b: B): b is C }",
  "{ a(b: B): asserts b }",
  "{ a(): this }",
  "{ a(): this is B }",
  "{ (): void }",
  "{ (a: A): B }",
  "{ <T>(x: T): T }",
  "{ () }",
  "{ (); }",
  "{ (): void; (a: A): void }",
  "{ (): void\n(a: A): void }",
  "{ new (): A }",
  "{ new (a: A): B }",
  "{ new <T>(x: T): A }",
  "{ new () }",
  "{ new (); }",
  "{ new: A }",
  "{ new?: A }",
  "{ new }",
  "{ new(): A }",
  "{ new<T>(): A }",
  "{ new\n(): A }",
  "{ new?(): A }",
  "{ abstract new (): A }",
  "{ [k: string]: A }",
  "{ [k: number]: A }",
  "{ [k: symbol]: A }",
  "{ [k: `a${string}`]: A }",
  "{ [k: string | number]: A }",
  "{ [k: K]: A }",
  "{ readonly [k: string]: A }",
  "{ [k: string]: A; [k: number]: B }",
  "{ [k: string]: A, a: B }",
  "{ [k: string] }",
  "{ [k: string]; }",
  "{ [k: string]?: A }",
  "{ [k?: string]: A }",
  "{ [...k: string[]]: A }",
  "{ [k: string, l: number]: A }",
  "{ [k: string,]: A }",
  "{ [k]: A }",
  "{ [k = 1]: A }",
  "{ [public k: string]: A }",
  "{ static [k: string]: A }",
  "{ [k: string](): A }",
  "{ get a(): A }",
  "{ set a(v: A) }",
  "{ get a(): A; set a(v: A) }",
  "{ get a(): A, set a(v: A) }",
  "{ get a(): A\nset a(v: A) }",
  "{ get a() }",
  "{ set a(v) }",
  "{ set a(v: A): void }",
  "{ get a(b: B): A }",
  "{ set a() }",
  "{ get: A }",
  "{ set: A }",
  "{ get?: A }",
  "{ get }",
  "{ set }",
  "{ get; set }",
  "{ get(): A }",
  "{ set(v: A): void }",
  "{ get<T>(): T }",
  "{ set<T>(v: T): void }",
  "{ get?(): A }",
  "{ get\na(): A }",
  "{ get 'a'(): A }",
  "{ get 1(): A }",
  "{ get [a](): A }",
  "{ get get(): A }",
  "{ set set(v: A) }",
  "{ get readonly(): A }",
  "{ readonly get a(): A }",
  "{ get a?(): A }",
  "{ get a<T>(): A }",
  "{ 'a': A }",
  '{ "a": A }',
  "{ 1: A }",
  "{ 1n: A }",
  "{ 0x10: A }",
  "{ -1: A }",
  "{ `a`: A }",
  "{ [a]: A }",
  "{ [a.b]: A }",
  "{ [Symbol.iterator](): A }",
  "{ ['a']: A }",
  "{ [1]: A }",
  "{ [a]?: A }",
  "{ [a]?(): A }",
  "{ readonly [a]: A }",
  "{ [a + b]: A }",
  "{ [a as B]: A }",
  "{ 'a'(): A }",
  "{ 1(): A }",
  "{ 'a'?: A }",
  "{ #a: A }",
  "{ static a: A }",
  "{ public a: A }",
  "{ private a: A }",
  "{ protected a: A }",
  "{ declare a: A }",
  "{ abstract a: A }",
  "{ override a: A }",
  "{ accessor a: A }",
  "{ async a(): void }",
  "{ export a: A }",
  "{ const a: A }",
  "{ in a: A }",
  "{ out a: A }",
  "{ static: A }",
  "{ public: A }",
  "{ async: A }",
  "{ async(): A }",
  "{ *a(): A }",
  "{ a: A = 1 }",
  "{ a = 1 }",
  "{ a: }",
  "{ : A }",
  "{ a: A",
  "a: A }",
  "{ a: { b: B } }",
  "{ a: { b: { c: C } } }",
  "{ a: [A]; b: () => void; c: new () => A }",
  "{ a: A extends B ? C : D }",
  "{ a: A | B; }",
  "{\na: A;\nb: B;\n}",
  "{\na: A,\nb: B,\n}",
  "{\na\nb\n}",
  "{\na()\nb()\n}",
  "{\n(): A\nnew (): B\n[k: string]: C\n}",
  "{ a: () => void\n b: B }",
  "{ a: A\n(): void }",
  "{ a: A\n[k: string]: B }",
  "{ a: A\n<T>(): void }",
  "{ a: typeof b\n<T>(): void }",
  "{ a\n?: A }",
  "{ a?\n: A }",
  "{ a:\nA }",
  ...[...CONTEXTUAL, ...RESERVED].flatMap(k => [`{ ${k}: A }`, `{ ${k}?: A }`, `{ ${k}(): A }`, `{ ${k} }`, `{ readonly ${k}: A }`, `{ get ${k}(): A }`, `{ ${k} a: A }`]),
);
add("this-type", "this", "this | A", "this.a", "this<A>", "this is A", "this is", "this\nis A", "this is A | B", "this is A extends B ? C : D", "this is this");
add("predicate", "a is A", "x is A", "a is", "is A", "a is A | B", "a is A[]", "a is A extends B ? C : D", "a is a is A", "asserts a", "asserts x", "asserts a is A", "asserts a is", "asserts this", "asserts this is A", "asserts is A", "asserts is", "asserts is is A", "asserts asserts", "asserts asserts is A", "asserts a.b", "asserts a is A | B", "asserts\na", "asserts a\nis A", "asserts 'a'", "asserts a[]", "asserts[]", "asserts.a", "asserts<A>", "asserts | A", "is", "is | A", "a.b is A", "'a' is A", "a! is A", "a? is A");
add("jsdoc", "A!", "!A", "?A", "A?", "*", "?", "...A", "A=", "function(): void", "function(a: A): B", "function(new: A)", "A.<B>", "A?[]", "?A[]", "A!.B", "A | ?B", "Array.<A>");
add("junk", "", ";", ",", ")", "]", "}", ">", "=", "=>", ".", "...", "?", ":", "@", "#a", "a b", "A B", "A = B", "A => B", "A, B", "A; B", "A: B", "A ? B", "A?.B", "A!.B", "A++", "A as B", "A satisfies B", "A instanceof B", "A in B", "A of B", "A ?? B", "A || B", "A && B", "A == B", "A + B", "A - B", "A * B", "A / B", "A ** B", "/a/", "/a/g", "class {}", "function () {}", "async () => {}", "await A", "yield A", "new A", "delete A", "void A", "!A", "~A", "super", "super.a", "1.5e-3", "0xg", "1a", "'a", '"a', "`a", "`a${", "`a${A", "\\u0041", "A\\u0042", "é", "日本", "𝒜", "A/*c*/", "/*c*/A", "A//c\n", "//c\nA", "A /* c */ | /* d */ B", "A<!--B", "<!--A", "-->A");

const TOKEN = /`(?:[^`\\]|\\[\s\S])*`|'(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*"|\d[\w.]*|[A-Za-z_$#][\w$]*|=>|\.\.\.|\?\.|\S/g;
function tokenize(text) {
  const out = [];
  let last = 0;
  let lead = "";
  for (const m of text.matchAll(TOKEN)) {
    const gap = text.slice(last, m.index);
    if (out.length) out[out.length - 1].ws = gap;
    else lead = gap;
    out.push({ text: m[0], ws: "" });
    last = m.index + m[0].length;
  }
  if (out.length) out[out.length - 1].ws = text.slice(last);
  else lead = text;
  return { lead, tokens: out };
}
const untokenize = ({ lead, tokens }) => lead + tokens.map(t => t.text + t.ws).join("");

export const MUT_TOKENS = kw(", | & ? : => = ( ) [ ] < > { } . ... ! ; - + extends readonly keyof typeof infer new in out is asserts unique abstract const as A 1 'a'");

function mutations(form, level) {
  const out = [];
  const tk = tokenize(form.t);
  if (untokenize(tk) !== form.t) throw new Error("tokenizer does not round-trip: " + JSON.stringify(form.t));
  const n = tk.tokens.length;
  for (let i = 0; i < n; i++) {
    const copy = { lead: tk.lead, tokens: tk.tokens.map(t => ({ ...t })) };
    copy.tokens[i].text = "";
    out.push({ prod: form.prod, t: untokenize(copy), mut: `del ${i} ${tk.tokens[i].text}`, from: form.t });
  }
  if (level !== "medium") return out;
  for (let i = 0; i < n; i++) {
    for (const tok of MUT_TOKENS) {
      if (tok === tk.tokens[i].text) continue;
      const copy = { lead: tk.lead, tokens: tk.tokens.map(t => ({ ...t })) };
      copy.tokens[i].text = tok;
      if (copy.tokens[i].ws === "" && i + 1 < n) copy.tokens[i].ws = " ";
      if (i > 0 && copy.tokens[i - 1].ws === "") copy.tokens[i - 1].ws = " ";
      out.push({ prod: form.prod, t: untokenize(copy), mut: `rep ${i} ${tk.tokens[i].text} -> ${tok}`, from: form.t });
    }
  }
  for (let i = 0; i <= n; i++) {
    for (const tok of MUT_TOKENS) {
      const copy = { lead: tk.lead, tokens: tk.tokens.map(t => ({ ...t })) };
      copy.tokens.splice(i, 0, { text: tok, ws: " " });
      if (i > 0 && copy.tokens[i - 1].ws === "") copy.tokens[i - 1].ws = " ";
      out.push({ prod: form.prod, t: untokenize(copy), mut: `ins ${i} ${tok}`, from: form.t });
    }
  }
  return out;
}

function buildForms(level) {
  const seen = new Set();
  const forms = [];
  const push = f => {
    if (seen.has(f.t)) return;
    seen.add(f.t);
    forms.push(f);
  };
  for (const f of F) push({ prod: f.prod, t: f.t, mut: null });
  const valid = forms.slice();
  for (const f of valid) {
    if (f.prod === "junk" || f.prod === "jsdoc") continue;
    for (const m of mutations(f, level)) push(m);
  }
  return forms;
}

if (import.meta.main ?? process.argv[1] === fileURLToPath(import.meta.url)) {
  const level = process.argv[2] ?? "small";
  if (level === "small" || level === "medium") {
    const forms = buildForms(level);
    const corpus = { name: level, contexts: CONTEXTS, forms, sources: [] };
    const path = join(HERE, `corpus.${level}.json`);
    writeFileSync(path, JSON.stringify(corpus));
    const base = forms.filter(f => f.mut === null).length;
    console.log(`${path}: ${base} forms, ${forms.length - base} mutations, ${Object.keys(CONTEXTS).length} contexts, ${forms.length * Object.keys(CONTEXTS).length} sources`);
  } else if (level === "targeted") {
    const { SOURCES } = await import("./targeted.mjs");
    const seen = new Set();
    const sources = [];
    for (const [prod, list] of Object.entries(SOURCES)) {
      for (const src of list) {
        if (seen.has(src)) continue;
        seen.add(src);
        sources.push({ prod, src });
      }
    }
    const corpus = { name: level, contexts: {}, forms: [], sources };
    const path = join(HERE, `corpus.${level}.json`);
    writeFileSync(path, JSON.stringify(corpus));
    console.log(`${path}: ${sources.length} sources`);
  } else {
    console.error("usage: bun gen.mjs small|medium|targeted");
    process.exit(1);
  }
}
