// Sources for the sites outside the type grammar that round 1 changed for a parse without lint: rest comma, parameter
// modifiers, implements entries, accessor, class index signatures, enum names in brackets, ":" after an operand, arrow bodies
// and type lists between "?" and ":", declarations that as or satisfies names, abstract declare, import in a namespace,
// with on the next line, dotted names in decorator metadata. One source per branch of each site, valid and broken.
// usage: bun seams.mjs [out, default corpus.seams.json beside this file]
import { writeFileSync } from "node:fs";
const S = {};
const add = (seam, ...srcs) => (S[seam] ??= []).push(...srcs);

// parse_fn.rs: a modifier before a parameter outside a constructor
add("fn.param-modifier",
  "function f(public a) {}",
  "function f(private a: A, protected b?: B, readonly c = 1, override d) {}",
  "function f(public readonly a: A) {}",
  "function f(readonly public a: A) {}",
  "(function (public a) {});",
  "x = function (private a) {};",
  "x = async function (protected a) {};",
  "x = function* (readonly a) {};",
  "export default function (public a) {}",
  "export function f(public a) {}",
  "async function f(public a) {}",
  "function* f(public a) {}",
  "class C { m(public a: A) {} }",
  "class C { static m(readonly a) {} }",
  "class C { async m(public a) {} *g(private a) {} async *h(protected a) {} }",
  "class C { #m(public a) {} }",
  "class C { [k](public a) {} }",
  "class C { set v(public a) {} }",
  "class C { get v(public a) { return 1; } }",
  "class C { constructor(public a: A) {} }",
  "class C { constructor(public a: A); constructor(a) {} }",
  "class C { m(public a: A): void; m(a) {} }",
  "abstract class C { abstract m(public a: A): void; }",
  "declare class C { m(public a: A): void; }",
  "({ m(public a) {} });",
  "({ set v(public a) {} });",
  "({ async m(public a) {} });",
  "declare function f(public a: A): void;",
  "function f(public a: A): void; function f(a) {}",
  "class C { @d m(@e public a: A) {} }",
  "class C { m(@e public a: A) {} }",
  "function f(public) {}",
  "function f(public, a) {}",
  "function f(public = 1) {}",
  "function f(public: A) {}",
  "function f(public?: A) {}",
  "function f(public\na) {}",
  "function f(public {a}) {}",
  "function f(public [a]) {}",
  "function f(public ...a) {}",
  "function f(...public a) {}",
  "function f(...public) {}",
  "function f(public this) {}",
  "function f(this: A, public a) {}",
  "function f(public public a) {}",
  "function f(public static a) {}",
  "function f(readonly async a) {}",
  "function f(declare a) {}",
  "function f(abstract a) {}",
  "function f(static a) {}",
  "function f(accessor a) {}",
  "function f(export a) {}",
  "function f(in a) {}",
  "function f(out a) {}",
  "function f(public a, private b, c) { return a + b + c; }",
  "function f(public a = b, private c = a) {}",
  "async function f(public await) {}",
  "function* g(public yield) {}",
  "function f(public a: A,) {}",
  "function f(a, public b?: B) {}",
  "function f(public a!: A) {}",
  "function f(public a?) {}",
  "function f(override readonly a) {}",
  "function f(public override readonly a) {}",
  "namespace N { export function f(public a) {} }",
  "function f(public /* c */ a) {}",
  "function f(public // c\na) {}",
  "function f(public a) { 'use strict'; }",
  "let f = (public a) => a;",
  "let f = async (public a) => a;",
);

// parse_fn.rs, parse/mod.rs, parse_property.rs: a comma after a rest parameter
add("fn.rest-comma",
  "declare class C { m(...a: A[],): void }",
  "declare class C { m(...a,); }",
  "declare class C { constructor(...a: A[],); }",
  "declare class C { static m(...a,): void; get x(): A }",
  "declare class C { set v(...a,); }",
  "declare class C { m(...a,) }",
  "declare class C { m(...a, b): void }",
  "declare class C { m(...a,,): void }",
  "declare class C { m(...a,) {} }",
  "declare class C { m(a = function (...b,) {}): void }",
  "declare class C { m(a = class { n(...b,) {} }): void }",
  "declare class C { m(a = { n(...b,) {} }): void }",
  "declare class C { m(a = (...b,) => 0): void }",
  "declare class C { [class { n(...b,) {} }.k]: A }",
  "declare class C { x = class { n(...b,) {} } }",
  "declare class C { static { function g(...b,) {} } }",
  "export declare class C { m(...a,): void }",
  "export default class C { m(...a,): void; m() {} }",
  "declare namespace N { class C { m(...a,): void } }",
  "declare namespace N { function f(...a,): void }",
  "declare namespace N { export class C { m(...a,): void } }",
  "declare module 'm' { class C { m(...a,): void } }",
  "declare global { class C { m(...a,): void } }",
  "declare function f(...a: A[],): void;",
  "declare const x: A; class C { m(...a,): void; m() {} }",
  "class C { m(...a: A[],): void; m(...a: A[]) {} }",
  "class C { m(...a,); m() {} }",
  "class C { m(...a,)\nm() {} }",
  "class C { constructor(...a,); constructor() {} }",
  "class C { static m(...a,): void; static m() {} }",
  "class C { #m(...a,): void; #m() {} }",
  "class C { get x(...a,); }",
  "class C { async m(...a,): Promise<void>; async m() {} }",
  "abstract class C { abstract m(...a: A[],): void }",
  "abstract class C { abstract m(...a,) }",
  "abstract class C { abstract m(...a,): void; n() {} }",
  "function f(...a: A[],): void; function f(...a: A[]) {}",
  "function f(...a,); function f() {}",
  "function f(...a,)\nfunction f() {}",
  "export function f(...a,): void; export function f() {}",
  "export default function f(...a,): void; export default function f() {}",
  "async function f(...a,): Promise<void>; async function f() {}",
  "namespace N { function f(...a,): void; function f() {} }",
  "function g() { function f(...a,): void; function f() {} }",
  "function f(...a,) {}",
  "function f(...a,) {} let x = ;",
  "function f(...a,) { ) }",
  "function f(...a,) {} function g(...b,) {}",
  "function f(...a,): void {}",
  "class C { m(...a,) {} }",
  "class C { m(...a,) { ) } }",
  "class C { m(...a,) {} n(...b,) {} }",
  "class C { m(...a,): void {} }",
  "class C { m(...a, b) {} }",
  "class C { m(...a,,) {} }",
  "class C { m(...a,\n): void; m() {} }",
  "class C { m(...a, /* c */ ): void; m() {} }",
  "class C { m(...a = [],): void; m() {} }",
  "class C { m(...[a],): void; m() {} }",
  "class C { m(...{ a },): void; m() {} }",
  "class C { m(b, ...a,): void; m() {} }",
  "class C { m(this: A, ...a,): void; m() {} }",
  "class C { m(...a?,): void; m() {} }",
  "class C { m(@d ...a,): void; m() {} }",
  "class C { constructor(...a,) {} }",
  "class C { set v(...a,) {} }",
  "({ m(...a,) {} });",
  "(function (...a,) {});",
  "x = function f(...a,): void {};",
  "let f = (...a,) => 0;",
  "let f = (...a,): void => 0;",
  "interface I { m(...a,): void }",
  "type X = (...a: A[],) => void;",
  "function f(...a,): asserts a is A; function f() {}",
  "declare function f(a = class { m(...b,) {} }): void;",
  "declare function f(a = class { m(...b,): void }): void;",
  "declare function f(a = { m(...b,) {} }): void;",
  "declare namespace N { function f(a = class { m(...b,) {} }): void }",
  "declare class C { m(a = class { n(b = class { o(...c,) {} }) {} }): void }",
  "class C { m(a = class { n(...b,) {} }): void; m() {} }",
  "class C { m(a = class { n(...b,) {} }) {} }",
  "function f(a = class { m(...b,) {} }) {}",
  "function f(a = class { m(...b,): void; m() {} }) {}",
);

// parse/mod.rs: an entry of implements that is no type
add("class.implements",
  "class C implements A {}",
  "class C implements A, B<T> {}",
  "class C implements a.b<T> {}",
  "class C implements a() {}",
  "class C implements a.b() {}",
  "class C implements a<T>() {}",
  "class C implements a[0] {}",
  "class C implements a['b'] {}",
  "class C implements (A) {}",
  "class C implements (a, b) {}",
  "class C implements new A {}",
  "class C implements new A() {}",
  "class C implements A! {}",
  "class C implements typeof a {}",
  "class C implements this {}",
  "class C implements this.a {}",
  "class C implements super.a {}",
  "class C implements super() {}",
  "class C implements #a {}",
  "class C implements a.#b {}",
  "class C implements a?.b {}",
  "class C implements a?.() {}",
  "class C implements a`x` {}",
  "class C implements `x` {}",
  "class C implements import.meta {}",
  "class C implements import('x') {}",
  "class C implements await a {}",
  "class C implements yield {}",
  "class C implements function () {} {}",
  "class C implements class {} {}",
  "class C implements <T>(x) {}",
  "class C implements <T>x {}",
  "class C implements a++ {}",
  "class C implements -a {}",
  "class C implements a + b {}",
  "class C implements a = b {}",
  "class C implements a ? b : c {}",
  "class C implements a as B {}",
  "class C implements 1 {}",
  "class C implements 'a' {}",
  "class C implements null {}",
  "class C implements true {}",
  "class C implements [] {}",
  "class C implements [a] {}",
  "class C implements {} {}",
  "class C implements { a: 1 } {}",
  "class C implements /re/ {}",
  "class C implements A, {}",
  "class C implements {}",
  "class C implements , A {}",
  "class C implements A B {}",
  "class C implements a() b() {}",
  "class C implements a(), b.c<T>() {}",
  "class C implements A, b() {}",
  "class C implements a(), B {}",
  "class C implements a(\n) {}",
  "class C implements a(",
  "class C implements a() {",
  "class C implements a(b => { let x = 1; }) {}",
  "class C implements a(function () { return import.meta; }) {}",
  "class C implements a(await 1) {}",
  "class C implements a(<div/>) {}",
  "class C implements a(1 +) {}",
  "class C implements a(x as) {}",
  "class C implements a(class { #p; m() { return this.#p; } }) {}",
  "class C extends B implements a() {}",
  "class C<T> extends B<T> implements a<T>() {}",
  "class C implements a() extends B {}",
  "x = class implements a() {};",
  "x = class C implements a() {};",
  "export default class implements a() {}",
  "export class C implements a() {}",
  "declare class C implements a() {}",
  "abstract class C implements a() {}",
  "@d class C implements a() {}",
  "import { a } from 'x'; class C implements a() {}",
  "import { a, A } from 'x'; class C implements A, a() {} new C();",
  "import a from 'x'; export class C implements a.b<T>() {}",
  "class C implements a() { static x = 1; }",
  "async function f() { class C implements a(await 1) {} }",
  "function* g() { class C implements a(yield) {} }",
  "class C implements A<B>> {}",
  "class C implements A<B<D>>() {}",
  "class C implements a()<T> {}",
  "class C implements a<T> {}",
  "class C implements a<T>.b {}",
  "class C implements a.b<T>.c {}",
  "interface I extends a() {}",
  "class C implements void {}",
  "class C implements any {}",
  "class C implements A | B {}",
  "class C implements A & B {}",
  "class C implements A[] {}",
  "class C implements A extends B ? D : E {}",
  "class C implements () => void {}",
  "class C implements new () => A {}",
  "class C implements keyof A {}",
  "class C implements { a: A }, B {}",
  "class C implements [A, B] {}",
  "class C implements a.b.c {}",
  "class C implements import('x').A {}",
  "class C implements typeof import('x') {}",
);

// parse_property.rs, parse/mod.rs: accessor, with either kind of decorators
add("class.accessor",
  "class C { accessor x = 1 }",
  "class C { accessor x }",
  "class C { accessor x: number = 1 }",
  "class C { static accessor x = 1 }",
  "class C { accessor static x }",
  "class C { accessor #x = 1 }",
  "class C { accessor 'a' = 1 }",
  "class C { accessor [a] = 1 }",
  "class C { accessor 1 = 1 }",
  "class C { accessor\nx }",
  "class C { accessor\nx = 1; y = 2 }",
  "class C { accessor }",
  "class C { accessor; x }",
  "class C { accessor = 1 }",
  "class C { accessor() {} }",
  "class C { accessor: number }",
  "class C { accessor?: number }",
  "class C { accessor!: number }",
  "class C { accessor<T>() {} }",
  "class C { accessor x() {} }",
  "class C { accessor x?: number }",
  "class C { accessor x!: number }",
  "class C { accessor accessor }",
  "class C { accessor accessor = 1 }",
  "class C { accessor get x() { return 1; } }",
  "class C { accessor get }",
  "class C { accessor async x() {} }",
  "class C { accessor *x() {} }",
  "class C { accessor constructor }",
  "class C { get accessor() { return 1; } }",
  "class C { static accessor }",
  "class C { static accessor = 1 }",
  "class C { static accessor() {} }",
  "class C { static accessor static }",
  "class C { @d accessor x = 1 }",
  "class C { @d static accessor x = 1 }",
  "class C { @d accessor #x = 1 }",
  "class C { @d accessor x: A }",
  "class C { @d accessor\nx }",
  "class C { @d accessor }",
  "class C { @d accessor = 1 }",
  "class C { @d accessor() {} }",
  "@d class C { accessor x = 1 }",
  "@d class C { static accessor x = 1 }",
  "@d class C { accessor }",
  "@d class C { accessor\nx }",
  "@d class C { @e accessor x = 1 }",
  "@d class C { accessor x = 1; accessor y = 2 }",
  "@d class C { [k] = 1; accessor x = 1 }",
  "@d class C { @e y; accessor #x }",
  "declare class C { accessor x: number }",
  "@d declare class C { accessor x: number }",
  "declare class C { @d accessor x: number }",
  "abstract class C { abstract accessor x: number }",
  "@d abstract class C { abstract accessor x: number }",
  "class C { declare accessor x: number }",
  "@d class C { declare accessor x: number }",
  "class C { public accessor x = 1 }",
  "class C { private static accessor x = 1 }",
  "class C { readonly accessor x = 1 }",
  "class C { override accessor x = 1 }",
  "class C { accessor public x = 1 }",
  "class C { accessor readonly x = 1 }",
  "class C { accessor declare x }",
  "x = class { accessor x = 1 };",
  "x = @d class { accessor x = 1 };",
  "x = class { @d accessor x = 1 };",
  "export default class { accessor x = 1 }",
  "export default @d class { accessor x = 1 }",
  "export class C { accessor x = 1 }",
  "class C { @d m() {} accessor x = 1 }",
  "class C { accessor x = 1; @d y }",
  "class C { constructor(@d a) {} accessor x }",
  "class C { m(@d a) {} accessor x }",
  "class C extends B { accessor x = super.y }",
  "class C { accessor x = 1 } class D { @d y }",
  "class C { accessor x = 1; static { C.y = 1; } }",
  "class C { accessor x = this.y; y = 1 }",
  "class C { accessor x = 1; constructor() { this.x = 2; } }",
  "class C { accessor x = 1; get y() { return this.x; } set y(v) { this.x = v; } }",
  "class C { accessor x = () => this }",
  "class C<T> { accessor x: T }",
  "namespace N { export class C { accessor x = 1 } }",
  "function f() { return class { accessor x = 1 }; }",
  "({ accessor x: 1 });",
  "({ accessor: 1, accessor() {} });",
  "let accessor = 1; class C { [accessor] = 1 }",
  "interface I { accessor x: A }",
  "type X = { accessor x: A };",
);

// parse_property.rs: an index signature of a class
add("class.index-signature",
  "class C { [a: string]: any }",
  "class C { [a: string]: any; }",
  "class C { [a: string] }",
  "class C { [a: string]; }",
  "class C { [a: string], }",
  "class C { [a: string]: any, }",
  "class C { [a: string]: any, x = 1 }",
  "class C { [a: string]: any\nx = 1 }",
  "class C { [a: string]: any x }",
  "class C { [a: string]?: any }",
  "class C { [a: string]!: any }",
  "class C { [a: string](): any }",
  "class C { [a: string] = 1 }",
  "class C { [a: string]: any = 1 }",
  "class C { [a: string]: any {} }",
  "class C { [a?: string]: any }",
  "class C { [a?]: any }",
  "class C { [a?,]: any }",
  "class C { [a ? b : c]: any }",
  "class C { [a ? b : c] = 1 }",
  "class C { [a ?: string] }",
  "class C { [...a: string[]]: any }",
  "class C { [...a]: any }",
  "class C { [...a] = 1 }",
  "class C { []: any }",
  "class C { [] }",
  "class C { [] = 1 }",
  "class C { []() {} }",
  "class C { [a, b: string]: any }",
  "class C { [a: string, b: number]: any }",
  "class C { [a, b]: any }",
  "class C { [a, b] = 1 }",
  "class C { [a,]: any }",
  "class C { [a: string,]: any }",
  "class C { [a: string = 'x']: any }",
  "class C { [a = 1]: any }",
  "class C { [a = 1] = 2 }",
  "class C { [a: string = ]: any }",
  "class C { [a: string = b => { let c; }]: any }",
  "class C { [a: string = import.meta]: any }",
  "class C { [a: string = await 1]: any }",
  "class C { [a: string = class { #p }]: any }",
  "class C { [a: string = <T>(x)]: any }",
  "class C { [a: string = super.x]: any }",
  "class C { [a: string = this.#p]: any }",
  "class C { [a: string = b, c]: any }",
  "class C { [a: string: any }",
  "class C { [a: ]: any }",
  "class C { [a: string]: }",
  "class C { [a:",
  "class C { [a: string",
  "class C { [a: string]",
  "class C { [a: string]:",
  "class C { [await: string]: any }",
  "class C { [yield: string]: any }",
  "async function f() { class C { [await: string]: any } }",
  "function* g() { class C { [yield: string]: any } }",
  "async function f() { class C { [await x]: any } }",
  "class C { [await x] = 1 }",
  "class C { [async: string]: any }",
  "class C { [async x => x]: any }",
  "class C { [async x => x] = 1 }",
  "class C { [public a: string]: any }",
  "class C { [readonly a: string]: any }",
  "class C { [static: string]: any }",
  "class C { [this: string]: any }",
  "class C { [let: string]: any }",
  "class C { [type: string]: any }",
  "class C { [of: string]: any }",
  "class C { [a: string]: any; [b: number]: any }",
  "class C { static [a: string]: any }",
  "class C { static [a: string] }",
  "class C { readonly [a: string]: any }",
  "class C { readonly [a: string] }",
  "class C { static readonly [a?: string]: any }",
  "class C { public [a: string]: any }",
  "class C { declare [a: string]: any }",
  "class C { abstract [a: string]: any }",
  "class C { override [a: string]: any }",
  "class C { accessor [a: string]: any }",
  "class C { async [a: string]: any }",
  "class C { get [a: string]() {} }",
  "class C { *[a: string]() {} }",
  "class C { @d [a: string]: any }",
  "class C { @d [a?: string]: any }",
  "@d class C { [a: string]: any }",
  "declare class C { [a: string]: any }",
  "declare class C { [a?: string] }",
  "abstract class C { [a: string]: any; abstract m(): void }",
  "x = class { [a: string]: any };",
  "x = class { [a?: string] };",
  "class C { [a]: any }",
  "class C { [a] }",
  "class C { [a]() {} }",
  "class C { [a] = 1 }",
  "class C { [a.b]: any }",
  "class C { ['a']: any }",
  "class C { [1]: any }",
  "class C { [a as B]: any }",
  "class C { [a!]: any }",
  "class C { [<T>a]: any }",
  "class C { [a: string]: any; x = 1; [b] = 2; m() {} }",
  "import { a } from 'x'; class C { [a: string]: any }",
  "import { a } from 'x'; class C { [a?: string]: any }",
  "import { a } from 'x'; class C { [a, b: string]: any }",
  "import { a } from 'x'; class C { [...a: string[]]: any }",
  "import { a, b } from 'x'; class C { [a: string = b]: any }",
  "import { a, T } from 'x'; class C { [a: T]: T }",
  "import { a } from 'x'; export class C { [a: string]: any }",
  "import { a } from 'x'; class C { [a]: any }",
  "let a = 1; class C { [a: string]: any } a;",
  "class C { [a: string]: any /* c */ ; }",
  "class C { [ /* c */ a /* d */ : string ] : any }",
  "class C { [a // c\n: string]: any }",
  "class C { [a\n: string]: any }",
  "class C { [\na: string\n]: any }",
  "class C { [a: string]\n: any }",
  "class C { [a: string]: any\n[b: number]: any }",
  "class C { [a: string]\n[b] = 1 }",
  "class C { [a: string]\nx = 1 }",
  "class C { [a: string] x = 1 }",
  "class C { [a: string]: any, [b: number]: any }",
  "class C { [a: string], [b: number] }",
  "class C { [a: string]: any;; }",
  "class C { [a: string]: (typeof x)[0] }",
  "({ [a: string]: 1 });",
  "interface I { [a: string]: any }",
  "type X = { [a?: string]: any };",
);

// parse_typescript.rs: a string in brackets as the name of an enum member
add("enum.bracket-name",
  "enum E { ['a'] }",
  "enum E { ['a'] = 1 }",
  'enum E { ["a"] = 1, b }',
  "enum E { [`a`] }",
  "enum E { [`a`] = 1, ['b'] = 2, c }",
  "enum E { ['a'], ['b'], }",
  "const enum E { ['a'] = 1 } x = E['a'];",
  "const enum E { ['a'] = 1 } x = E.a;",
  "enum E { ['a'] = 1, b = E['a'] + 1 }",
  "enum E { ['a'] = 1, b = a + 1 }",
  "enum E { ['a-b'] = 1, c = E['a-b'] }",
  "declare enum E { ['a'] }",
  "declare const enum E { ['a'] = 1 }",
  "export enum E { ['a'] = 1 }",
  "export const enum E { [`a`] = 1 }",
  "namespace N { export enum E { ['a'] } }",
  "enum E { [ 'a' ] }",
  "enum E { [\n'a'\n] }",
  "enum E { [/* c */ 'a' /* d */] }",
  "enum E { ['a' ] = 'x' }",
  "enum E { [''] }",
  "enum E { ['\\u0061'] }",
  "enum E { ['a'] = 1, ['a'] = 2 }",
  "enum E { [a] }",
  "enum E { [1] }",
  "enum E { ['a' + 'b'] }",
  "enum E { [`a${1}`] }",
  "enum E { ['a', 'b'] }",
  "enum E { ['a'] ['b'] }",
  "enum E { ['a' }",
  "enum E { ['a'",
  "enum E { [ }",
  "enum E { [] }",
  "enum E { [['a']] }",
  "enum E { ('a') }",
  "enum E { ['a']: 1 }",
  "enum E { ['a']() {} }",
  "enum E { 'a' }",
  "enum E { `a` }",
  "enum E { a, ['b'] = a }",
  "enum E { ['__proto__'] = 1 }",
  "enum E { ['a'] = 1 } enum E { ['b'] = 2 }",
);

// parse/mod.rs, parse_prefix.rs: a ":" after an operand that ends with parentheses
add("paren.colon-after-operand",
  "x = a ? -<T>(b) : c;",
  "x = a ? !<T>(b) : c;",
  "x = a ? ~<T>(b) : c;",
  "x = a ? +<T>(b) : c;",
  "x = a ? typeof <T>(b) : c;",
  "x = a ? void <T>(b) : c;",
  "x = a ? delete <T>(b) : c;",
  "x = a ? await <T>(b) : c;",
  "x = a ? ++<T>(b) : c;",
  "x = a ? --<T>(b) : c;",
  "x = a ? 1 + <T>(b) : c;",
  "x = a ? d || <T>(b) : c;",
  "x = a ? d && <T>(b) : c;",
  "x = a ? d ?? <T>(b) : c;",
  "x = a ? d == <T>(b) : c;",
  "x = a ? d in <T>(b) : c;",
  "x = a ? d instanceof <T>(b) : c;",
  "x = a ? d ** <T>(b) : c;",
  "x = a ? d = <T>(b) : c;",
  "x = a ? d += <T>(b) : c;",
  "x = a ? d, <T>(b) : c;",
  "x = a ? [<T>(b)] : c;",
  "x = a ? new <T>(b) : c;",
  "x = a ? -async<T>(b) : c;",
  "x = a ? -async(b) : c;",
  "x = a ? 1 + async(b) : c;",
  "x = a ? 1 + async<T>(b) : c;",
  "x = a ? -(b) : c;",
  "x = a ? -<T>(b) : c => d;",
  "x = a ? -<T>(b): c => d : e;",
  "x = a ? <T>(b) : c;",
  "x = a ? -<T,>(b) : c;",
  "x = a ? -<T extends U>(b) : c;",
  "x = a ? -<T>(b, c) : d;",
  "x = a ? -<T>() : c;",
  "x = a ? -<const T>(b) : c;",
  "x = a ? -<T>(b)! : c;",
  "x = a ? -<T>(b).c : d;",
  "x = a ? -<T>(b)() : d;",
  "x = a ? -<T>(b)<U>() : d;",
  "x = a ? (-<T>(b)) : c;",
  "x = a ? -<T>(b) as U : c;",
  "x = a ? -<T><U>(b) : c;",
  "x = a ? - <T> (b) : c;",
  "x = a ? -<T>(b)\n: c;",
  "x = a ? -<T>(b) /* c */ : c;",
  "x = a ? -<T>({ b }) : c;",
  "x = a ? -<T>([b]) : c;",
  "x = a ? -<T>(...b) : c;",
  "x = a ? -<T>(b = 1) : c;",
  "x = a ? -<T>(b: B) : c;",
  "x = a ? -<T>(b?) : c;",
  "x = a ? e ? -<T>(b) : c : d;",
  "x = a ? -<T>(b) ? c : d : e;",
  "x = -<T>(b) ? 1 : 2;",
  "x = a ? b : -<T>(c);",
  "switch (x) { case -<T>(b): break; }",
  "switch (x) { case 1 + <T>(b): }",
  "switch (x) { case <T>(b): }",
  "switch (x) { case -async(b): }",
  "switch (x) { case -async<T>(b): }",
  "switch (x) { case -<T>(b): c => d; }",
  "x = { [a ? -<T>(b) : c]: 1 };",
  "for (const k of a ? -<T>(b) : c) {}",
  "label: -<T>(b);",
  "let o = { k: -<T>(b) };",
  "f(a ? -<T>(b) : c);",
  "x = a ? -<T>(b) : c, d;",
  "x = (a ? -<T>(b) : c);",
  "x = a ? () => -<T>(b) : c;",
  "x = a ? yield -<T>(b) : c;",
  "function* g() { x = a ? yield <T>(b) : c; }",
  "async function f() { x = a ? await <T>(b) : c; }",
  "x = a ? -<T>(b):c;",
  "x = a ? -function(){}<T>(b) : c;",
);

// parse_prefix.rs, parse/mod.rs: "<T>(" and "async<T>(" between "?" and ":"
add("paren.type-list-before-colon",
  "x = a ? <T>(b) : c => d;",
  "x = a ? async<T>(b) : c => d;",
  "x = a ? async(b) : c => d;",
  "x = a ? (b) : c => d;",
  "x = a ? <T>(b): c => d : e;",
  "x = a ? async<T>(b): c => d : e;",
  "x = a ? async(b): c => d : e;",
  "x = a ? <T,>(b) : c => d;",
  "x = a ? <T,>(b): c => d : e;",
  "x = a ? <T extends U>(b) : c => d;",
  "x = a ? <T extends U>(b): c => d : e;",
  "x = a ? async<T,>(b) : c => d;",
  "x = a ? async <T,>(b): c => d : e;",
  "x = a ? async <T extends U>(b) : c => d;",
  "x = a ? <T>(b) : c;",
  "x = a ? async<T>(b) : c;",
  "x = a ? <T>(b) => c : d;",
  "x = a ? async<T>(b) => c : d;",
  "x = a ? <T>(b) : (c) => d;",
  "x = a ? <T>(b) : c => d => e;",
  "x = a ? <T>(b) : c ? d : e => f;",
  "x = a ? <T>(b) : async c => d;",
  "x = a ? <T>(b) : <U>(c) => d;",
  "x = a ? <T>(b, c) : d => e;",
  "x = a ? <T>() : c => d;",
  "x = a ? <T>({ b }) : c => d;",
  "x = a ? <T>([b]) : c => d;",
  "x = a ? <T>(...b) : c => d;",
  "x = a ? <T>(b: B) : c => d;",
  "x = a ? <T>(b = 1) : c => d;",
  "x = a ? <T>(b)\n: c => d;",
  "x = a ? <T><U>(b) : c => d;",
  "x = a ? <const T>(b) : c => d;",
  "x = a ? <in T>(b) : c => d;",
  "x = a ? <T = U>(b) : c => d;",
  "x = a ? <T>(b) : c => d : e;",
  "x = a ? e ? <T>(b) : c => d : f;",
  "x = a ? (<T>(b)) : c => d;",
  "for (const k of a ? <T>(b) : c => d) {}",
  "x = { [a ? <T>(b) : c => d]: 1 };",
  "f(a ? <T>(b) : c => d, e);",
  "x = a ? async<T>(b) : async c => d;",
  "x = a ? async<T>(b)\n: c => d;",
  "x = a ? async <T>(b: B): C => d : e;",
  "x = a ? async <T>(b) => c : d => e;",
  "x = a ? async<T>\n(b) : c => d;",
  "x = a ? async\n<T>(b) : c => d;",
  "x = a ? async<T>(b)<U>(c) : d => e;",
  "x = a ? async<T>(b).c : d => e;",
);

// parse_fn.rs, parse/mod.rs, parse_prefix.rs: the body of an arrow function between "?" and ":"
add("arrow.body-before-colon",
  "x = a ? (b) => (c) : d => e;",
  "x = a ? b => (c) : d => e;",
  "x = a ? async b => (c) : d => e;",
  "x = a ? async (b) => (c) : d => e;",
  "x = a ? (b, c) => (d) : e => f;",
  "x = a ? ({ b }) => (c) : d => e;",
  "x = a ? ([b]) => (c) : d => e;",
  "x = a ? ({ b }: B) => (c) : d => e;",
  "x = a ? ([b]: B) => (c) : d => e;",
  "x = a ? (b = 1) => (c) : d => e;",
  "x = a ? (...b) => (c) : d => e;",
  "x = a ? (b, ...c) => (d) : e => f;",
  "x = a ? () => (c) : d => e;",
  "x = a ? (b: B) => (c) : d => e;",
  "x = a ? (b?) => (c) : d => e;",
  "x = a ? (b?: B) => (c) : d => e;",
  "x = a ? (b, c: C) => (d) : e => f;",
  "x = a ? (b, c?) => (d) : e => f;",
  "x = a ? (b): B => (c) : d => e;",
  "x = a ? <T>(b) => (c) : d => e;",
  "x = a ? <T,>(b) => (c) : d => e;",
  "x = a ? <T>(b: B) => (c) : d => e;",
  "x = a ? <T>() => (c) : d => e;",
  "x = a ? async <T>(b) => (c) : d => e;",
  "x = a ? async <T>(b: B) => (c) : d => e;",
  "x = a ? async () => (c) : d => e;",
  "x = a ? async (b: B) => (c) : d => e;",
  "x = a ? async ({ b }) => (c) : d => e;",
  "x = a ? (b) => c ? (d) : e => f : g;",
  "x = a ? (b) => (c) => (d) : e => f;",
  "x = a ? b => c => (d) : e => f;",
  "x = a ? (b) => (c): d => e : f;",
  "x = a ? b => (c): d => e : f;",
  "x = a ? b => c ? (d) : e : f;",
  "x = a ? (b) => { return (c); } : d => e;",
  "x = a ? function () { return (c); } : d => e;",
  "x = a ? (b) => (c), d : e;",
  "x = a ? (b) => (c) : d;",
  "x = a ? (b) => (c);",
  "x = (b) => (c);",
  "x = (b) => (c) : d => e;",
  "x = a ? (b) => <T>(c) : d => e;",
  "x = a ? (b) => async (c) : d => e;",
  "x = a ? (b) => async <T>(c) : d => e;",
  "x = a ? (b) => -(c) : d => e;",
  "x = a ? (b) => -<T>(c) : d => e;",
  "x = a ? (b) => c + (d) : e => f;",
  "x = a ? (b) => c = (d) : e => f;",
  "x = a ? (b) => [c, (d)] : e => f;",
  "x = a ? (b) => (c)\n: d => e;",
  "x = a ? (b) => (c, d) : e => f;",
  "x = a ? (b) => ({ c }) : d => e;",
  "x = a ? (b) => ([c]) : d => e;",
  "x = a ? (b) => (c = 1) : d => e;",
  "x = a ? (b) => (...c) : d => e;",
  "x = a ? (b) => () : d => e;",
  "x = a ? (b) => (c: C) : d => e;",
  "x = a ? (b) => (c?) : d => e;",
  "x = a ? (b) => f(c) : d => e;",
  "x = a ? (b) => new F(c) : d => e;",
  "x = a ? (b) => (c)(d) : e => f;",
  "x = a ? (b) => (c)! : d => e;",
  "x = a ? (b) => (c) as C : d => e;",
  "x = a ? b => (c) : d;",
  "x = a ? async b => (c) : d;",
  "x = a ? b => async (c) : d => e;",
  "x = a ? async b => async (c) : d => e;",
  "x = a ? b => <T>(c) : d => e;",
  "x = a ? async b => <T>(c) : d => e;",
  "x = a ? b => (c): D => e : f => g;",
  "x = a ? (b): C => (d) : e => f : g;",
  "x = a ? e ? (b) => (c) : d => f : g;",
  "for (const k of a ? (b) => (c) : d => e) {}",
  "x = { [a ? (b) => (c) : d => e]: 1 };",
  "f(a ? (b) => (c) : d => e);",
  "x = a ? (b) => (c) : (d): D => e;",
  "x = a ? y ? (b) => (c) : d => e : z;",
  "x = a ? (b) => y ? (c) => (d) : e => f : g;",
);

// parse_stmt.rs: type, interface, namespace or module before "as" or "satisfies"
add("stmt.named-like-cast",
  "type as = 1;",
  "type satisfies = 1;",
  "type as<T> = T;",
  "type as = as;",
  "type as\n= 1;",
  "type\nas = 1;",
  "type as;",
  "type as any;",
  "type as any\nfoo();",
  "type as <T>(x: T) => void;",
  "type as = 1, 2;",
  "type as.b = 1;",
  "type as as as;",
  "type satisfies as = 1;",
  "interface as {}",
  "interface satisfies {}",
  "interface as<T> {}",
  "interface as extends B {}",
  "interface satisfies<T> extends B<T> { a: T }",
  "interface as { a: A }",
  "interface as { a(): void }",
  "interface as { [k: string]: A }",
  "interface as {}\nfoo();",
  "interface as {}; foo()",
  "interface as {} foo()",
  "interface as {} Foo {}",
  "interface as {} | X",
  "interface as {} | X\nfoo();",
  "interface as {}[];",
  "interface as {} as X;",
  "interface as any;",
  "interface as any\nfoo();",
  "interface as { new (): A }",
  "interface as { readonly a: A; b?: B }",
  "interface as {}`x`",
  "interface as {} + 1;",
  "interface as {} - 1;",
  "interface as {} / 1;",
  "interface as {}.x;",
  "interface as {} = 1;",
  "interface as {}, b;",
  "interface as {} ? 1 : 2;",
  "interface as {} in x;",
  "interface as {}\n[a] = b;",
  "interface as {} !",
  "interface\nas {}",
  "namespace as {}",
  "namespace satisfies {}",
  "module as {}",
  "namespace as.b {}",
  "namespace as.b { export const x = 1; }",
  "namespace as { export const a = 1 }",
  "namespace as { const a = 1 }",
  "namespace as { foo(): void }",
  "namespace as { a: A }",
  "namespace as { [K in A]: B }",
  "namespace as {}\nfoo();",
  "namespace as {} foo()",
  "namespace as {} | X;",
  "namespace as {}`x`",
  "namespace as {}.x;",
  "namespace as any;",
  "namespace as any\nfoo();",
  "namespace as;",
  "namespace as = 1;",
  "namespace as { namespace b {} }",
  "namespace as { interface as {} type as = 1 }",
  "declare namespace as {}",
  "declare namespace as { const a: A }",
  "declare module as {}",
  "declare type as = 1;",
  "declare interface as {}",
  "export type as = 1;",
  "export interface as {}",
  "export namespace as {}",
  "export declare namespace as {}",
  "function f() { type as = 1; }",
  "function f() { interface as {} }",
  "function f() { namespace as {} }",
  "function f() { namespace as any; }",
  "{ type as = 1; }",
  "{ interface as {} }",
  "{ namespace as {} }",
  "if (a) type as = 1;",
  "namespace N { type as = 1; interface as {} namespace as {} }",
  "abstract as;",
  "abstract as any;",
  "global as any;",
  "declare as any;",
  "var type, as; type as = 1;",
  "var type; type as any;",
  "var interface; interface as any;",
  "let namespace = 1; namespace as any;",
  "type as = 1; export {};",
  "type as = 1\ninterface as {}\nnamespace as {}",
  "label: type as = 1;",
  "type satisfies any;",
  "interface satisfies any;",
  "namespace satisfies any;",
  "type as /* c */ = 1;",
  "type /* c */ as = 1;",
  "interface as /* c */ {}",
  "async as = 1;",
  "type as => 1;",
  "type as: 1;",
);

// parse_stmt.rs: abstract before declare
add("stmt.abstract-declare",
  "abstract declare class C {}",
  "@d abstract declare class C {}",
  "export abstract declare class C {}",
  "abstract declare\nclass C {}",
  "abstract\ndeclare class C {}",
  "abstract declare class C { m(...a,): void }",
  "abstract declare class C { abstract m(): void; x: A }",
  "abstract declare class C { x = 1; m() {} }",
  "abstract declare class C extends B implements I {}",
  "abstract declare function f(): void;",
  "abstract declare const x: A;",
  "abstract declare abstract class C {}",
  "abstract declare;",
  "abstract declare class",
  "declare abstract class C {}",
  "declare abstract declare class C {}",
  "namespace N { abstract declare class C {} }",
  "namespace N { export abstract declare class C {} }",
  "function f() { abstract declare class C {} }",
  "abstract declare class C {} new C();",
  "abstract declare class C {} class C {}",
  "abstract declare class C {}\nexport { C };",
  "export default abstract declare class C {}",
  "abstract /* c */ declare class C {}",
);

// parse_stmt.rs: import as an expression in a namespace
add("stmt.namespace-import-expr",
  "namespace N { import('x'); }",
  "namespace N { import.meta; }",
  "namespace N { import('x').then(f); }",
  "namespace N { import.meta.url; }",
  "namespace N { import ('x'); }",
  "namespace N { import\n('x'); }",
  "namespace N { import . meta; }",
  "namespace N { import('x', { with: { type: 'json' } }); }",
  "namespace N { export import('x'); }",
  "namespace N { export import.meta; }",
  "namespace N { import a = b.c; }",
  "namespace N { export import a = b.c; }",
  "namespace N { import a = require('x'); }",
  "namespace N { import 'x'; }",
  "namespace N { import * as a from 'x'; }",
  "namespace N { import { a } from 'x'; }",
  "namespace N { import a from 'x'; }",
  "namespace N { import type a = b.c; }",
  "namespace N { import; }",
  "namespace N { import }",
  "namespace N { import( }",
  "namespace N { import.x; }",
  "namespace N { import() }",
  "namespace N { import<T>('x'); }",
  "namespace N { function f() { import('x'); } }",
  "namespace N { { import('x'); } }",
  "namespace N { if (a) import('x'); }",
  "namespace N { namespace M { import('x'); import.meta; } }",
  "namespace N { x = import('x'); }",
  "namespace N { export const x = import('x'); }",
  "declare namespace N { import('x'); }",
  "declare namespace N { import.meta; }",
  "declare namespace N { import a = b.c; }",
  "module N { import('x'); }",
  "declare module 'm' { import('x'); }",
  "declare global { import('x'); }",
  "export namespace N { import('x'); }",
  "enum E { a } namespace E { import('x'); }",
);

// parse/mod.rs: with after a module path, on the next line
add("module.with-on-next-line",
  "import a from 'x'\nwith { type: 'json' };",
  "import 'x'\nwith { type: 'json' };",
  "import * as a from 'x'\nwith { type: 'json' };",
  "import { a } from 'x'\nwith { type: 'json' };",
  "import a, { b } from 'x'\nwith { type: 'json' };",
  "import a from 'x'\nwith {};",
  "import a from 'x'\nwith { type: 'json' }\nfoo();",
  "import a from 'x'\nwith (b) {}",
  "import a from 'x'\nwith(b) c;",
  "import a from 'x'\nwith",
  "import a from 'x'\nwith;",
  "import a from 'x'\nwith\n{ type: 'json' };",
  "import a from 'x'\n\n// c\nwith { type: 'json' };",
  "import a from 'x' /* c */\nwith { type: 'json' };",
  "import a from 'x'; with { type: 'json' };",
  "import a from 'x' with { type: 'json' };",
  "import a from 'x' with\n{ type: 'json' };",
  "import a from 'x'\nassert { type: 'json' };",
  "import a from 'x' assert { type: 'json' };",
  "import a from 'x'\nwith { type: 'text' }; a;",
  "import a from 'x'\nwith { type: 'file' }; a;",
  "import a from 'x'\nwith { type: 'toml' }; a;",
  "import a from 'x'\nwith { 'type': 'json', };",
  "import a from 'x'\nwith { type: 'json', other: 'y' };",
  "import a from 'x'\nwith { type };",
  "import a from 'x'\nwith { type: 1 };",
  "import a from 'x'\nwith { [type]: 'json' };",
  "import a from 'x'\nwith { type: 'json' ",
  "export * from 'x'\nwith { type: 'json' };",
  "export * as a from 'x'\nwith { type: 'json' };",
  "export { a } from 'x'\nwith { type: 'json' };",
  "export { a } from 'x'\nwith (b) {}",
  "export * from 'x'\nwith (b) {}",
  "import type a from 'x'\nwith { type: 'json' };",
  "import type { a } from 'x'\nwith { type: 'json' };",
  "import { type a } from 'x'\nwith { type: 'json' };",
  "export type { a } from 'x'\nwith { type: 'json' };",
  "export type * from 'x'\nwith { type: 'json' };",
  "import a = require('x')\nwith { type: 'json' };",
  "import('x')\nwith { type: 'json' };",
  "x = import('x'\n, { with: { type: 'json' } });",
  "import a from 'x'\nwith { type: 'json' } import b from 'y'\nwith { type: 'text' };",
  "import a from 'x'\nwith { type: 'macro' }; a();",
  "import { a } from 'x'\nwith { type: 'macro' };",
  "import a from 'x'\nwith { type: 'json' }; export { a };",
  "import a from 'x'\nwith { type: 'sqlite', embed: 'true' };",
  "import a from 'x'\r\nwith { type: 'json' };",
  "import a from 'x'\u2028with { type: 'json' };",
  "declare module 'm' { import a from 'x'\nwith { type: 'json' }; }",
);

// ast/ts.rs: dotted names where decorator metadata merges operands
add("metadata.dotted-merge",
  "class C { @d p: A.B | C.D; }",
  "class C { @d p: A.B | A.B; }",
  "class C { @d p: A.B | A.C; }",
  "class C { @d p: A.B | A.B.C; }",
  "class C { @d p: A.B.C | A.B.C; }",
  "class C { @d p: A.B.C | A.B.D; }",
  "class C { @d p: A.B | C.D | E.F; }",
  "class C { @d p: A.B | C.D | A.B; }",
  "class C { @d p: A.B | null; }",
  "class C { @d p: null | A.B; }",
  "class C { @d p: A.B | undefined | C.D; }",
  "class C { @d p: A.B | never; }",
  "class C { @d p: A.B | A; }",
  "class C { @d p: A | A.B; }",
  "class C { @d p: A | A; }",
  "class C { @d p: A | B; }",
  "class C { @d p: A.B | string; }",
  "class C { @d p: string | A.B; }",
  "class C { @d p: A.B | any; }",
  "class C { @d p: A.B | unknown; }",
  "class C { @d p: A.B | Object; }",
  "class C { @d p: (A.B) | (C.D); }",
  "class C { @d p: A.B<T> | C.D<T>; }",
  "class C { @d p: A.B & C.D; }",
  "class C { @d p: A.B & A.B; }",
  "class C { @d p: A.B & A.C; }",
  "class C { @d p: A.B & C.D & E.F; }",
  "class C { @d p: A.B & unknown; }",
  "class C { @d p: unknown & A.B; }",
  "class C { @d p: A.B & never; }",
  "class C { @d p: A.B & null; }",
  "class C { @d p: A.B & A; }",
  "class C { @d p: A & A.B; }",
  "class C { @d p: A.B | C.D & E.F; }",
  "class C { @d p: A.B & C.D | E.F; }",
  "class C { @d p: | A.B | C.D; }",
  "class C { @d p: & A.B & C.D; }",
  "class C { @d m(a: A.B | C.D) {} }",
  "class C { @d m(a: A.B & A.C) {} }",
  "class C { @d m(): A.B | C.D { return x; } }",
  "class C { @d m(): A.B & C.D { return x; } }",
  "class C { @d m(a: A.B | C.D, b: E.F | E.F): G.H | G.I {} }",
  "@d class C { constructor(a: A.B | C.D, b: A.B & A.B) {} }",
  "class C { m(@d a: A.B | C.D) {} }",
  "class C { @d set v(a: A.B | C.D) {} }",
  "class C { @d get v(): A.B | C.D { return x; } }",
  "class C { @d static p: A.B | C.D; }",
  "class C { @d p?: A.B | C.D; }",
  "class C { @d p!: A.B | C.D; }",
  "class C { @d p: A.B | C.D = x; }",
  "import * as A from 'a'; import * as C from 'c'; class K { @d p: A.B | C.D; }",
  "import { A } from 'a'; class K { @d p: A.B | A.C; }",
  "import type { A } from 'a'; class K { @d p: A.B | A.C; }",
  "namespace A { export class B {} export class C {} } class K { @d p: A.B | A.C; }",
  "class C { @d p: T extends U ? A.B : C.D; }",
  "class C { @d p: T extends U ? A.B : A.B; }",
  "class C { @d p: T extends U ? A : A; }",
  "class C { @d p: T extends U ? A : B; }",
  "class C { @d p: T extends U ? string : string; }",
  "class C { @d p: T extends U ? null : A.B; }",
  "class C { @d p: T extends U ? any : any; }",
  "class C { @d p: T extends U ? never : never; }",
  "class C { @d p: null | undefined; }",
  "class C { @d p: never | never; }",
  "class C { @d p: any | any; }",
  "class C { @d p: unknown & unknown; }",
  "class C { @d p: null & undefined; }",
  "class C { @d p: void | A.B; }",
  "class C { @d p: typeof A.B | typeof C.D; }",
  "class C { @d p: A.B[] | C.D[]; }",
  "class C { @d p: Promise<A.B> | Promise<C.D>; }",
  "class C { @d p: this | A.B; }",
);

// Sites that round 1 edited and that a parse without lint reads as before: type lists, erased statements, wrappers
add("site.unchanged",
  "function f<T>() {}",
  "function f<const T, U extends T = T>(a: T): U { return a; }",
  "(function <T>() {});",
  "x = function g<T>(a: T): T { return a; };",
  "export default function <T>(a: T) {}",
  "class C<T> {}",
  "class C<in T, out U, in out V> {}",
  "x = class <T> {};",
  "x = class D<T> extends B<T> {};",
  "export default class <T> {}",
  "class C extends B<T> {}",
  "class C extends a.b<T>.c {}",
  "class C extends (B as any)<T> {}",
  "class C { m<T>(a: T): T { return a; } }",
  "class C { m?<T>(): T }",
  "class C { static m<const T>() {} }",
  "class C { m!<T>() {} }",
  "({ m<T>() {} });",
  "let f = <T,>(a: T) => a;",
  "let f = async <T,>(a: T) => a;",
  "let f = <T extends U>(a: T): T => a;",
  "new A<T>();",
  "new A<T>;",
  "f<T>();",
  "f?.<T>();",
  "a?.b<T>();",
  "f<T>`x`;",
  "a = f<T>, g;",
  "a = f<T>\ng();",
  "a = f<T>;",
  "a = f < T > (b);",
  "a = f<T>>(b);",
  "a = f<<T>() => void>();",
  "@d<T>() class C {}",
  "@a.b<T>() class C {}",
  "class C { @d<T>() m() {} }",
  "@(d as any) class C {}",
  "@d! class C {}",
  "x = <Foo<T> />;",
  "x = <Foo<T>>y</Foo>;",
  "x = <a.b<T> c=\"d\" />;",
  "x = <Foo<<U>() => void> />;",
  "x = <Foo<T,> />;",
  "let x!: T;",
  "let x: T = 1, y!: U, z;",
  "try {} catch (e: unknown) {}",
  "try {} catch (e: any) {}",
  "for (let a: T = 0; ; ) {}",
  "for (const a: T of b) {}",
  "function f(this: T) {}",
  "function f(this) {}",
  "function f(this: T, a) {}",
  "function f(this, a: T) {}",
  "class C { get x(): T { return 1; } set x(v: T) {} }",
  "class C { x: T; y?: T; z!: T; static s: T = 1; readonly r: T }",
  "class C { declare x: T; }",
  "abstract class C { abstract m(): void; abstract x: T; abstract get y(): T }",
  "class C { m(): void; m(a?: T): void; m() {} }",
  "class C { constructor(); constructor(a?: T) {} }",
  "function f(): void; function f(a?: T): void; function f() {}",
  "export as namespace N;",
  "import type A from 'x'; import type { B } from 'x'; import type * as D from 'x'; import { type E } from 'x';",
  "export type { A }; export type { B } from 'x'; export type * from 'x'; export { type F } from 'x';",
  "import a = require('x'); import b = a.c; export import d = a.e; import type t = require('x');",
  "export = a;",
  "declare global { var g: T }",
  "declare module 'm' { export const a: T }",
  "declare module '*.css';",
  "declare var v: T; declare let l: T; declare const c: T; declare function f(): T; declare class K {} declare enum E { a } declare namespace N {}",
  "enum E { a, b = 1, 'c' = 2 } const enum F { a }",
  "namespace N { export const a = 1 } namespace N.M {}",
  "let v = a as T; let w = a satisfies T; let x = a!; let y = <T>a; let z = a as const;",
  "let v = a! as T satisfies U;",
  "x = a?.b!.c;",
  "x = a!++;",
  "x = (a as T) = b;",
  "x = (<T>a).b;",
  "type A = 1; interface B {} type C<T> = T; interface D<T> extends B {}",
  "abstract class C {} declare abstract class D {}",
  "let f = (a: T, b?: U, ...c: V[]): W => a;",
  "let f = async (a: T): Promise<T> => a;",
  "let f = (a): a is T => true;",
  "let f = function (a: T): asserts a is T {};",
  "x = a ? (b): T => c : d;",
  "x = a ? (b) : c;",
  "x = a ? b : (c): T => d;",
);

const sources = [];
const seen = new Set();
for (const [prod, list] of Object.entries(S)) {
  for (const src of list) {
    if (seen.has(src)) continue;
    seen.add(src);
    sources.push({ src, prod });
  }
}
writeFileSync(process.argv[2] ?? new URL("corpus.seams.json", import.meta.url).pathname, JSON.stringify({ name: "seams", contexts: {}, forms: [], sources }));
console.log(`${sources.length} sources: ` + Object.entries(S).map(([k, v]) => `${k}=${v.length}`).join(" "));
