// Sources for the sites OUTSIDE the type grammar whose behaviour without lint round 1 changed (diff of
// f4d755a9cf..23a20afa7e under src/js_parser, every file but parse_skip_typescript.rs and type_sink.rs).
// One group per site. Every source runs under every configuration of harness.all.mjs, so a group that only
// TypeScript reaches also shows that JavaScript stays as it is.
//
//   bun seams.mjs [out, default corpus.seams.json beside this file]
//
// The key of a group is the `prod` of its sources: diff.mjs and seams-seen.mjs group by it.
import { writeFileSync } from "node:fs";
import { join } from "node:path";

export const SEAMS = {
  // parse_fn.rs parse_fn: a comma after a rest argument in a signature that has no body
  // (`allow_missing_body_for_type_script && next_token_is_close_paren()`), and mod.rs parse_class +
  // parse_property.rs parse_fn_body_for_property: a `declare class` hands `is_typescript_declare` to its members.
  "fn.rest-comma": [
    "function f(...a,): void;\nfunction f(...a: any[]) {}",
    "function f(...a,);",
    "function f(...a,)",
    "export function f(...a,): void;\nexport function f() {}",
    "export default function (...a,): void;",
    "class C { m(...a,): void; m(...a: any[]) {} }",
    "class C { m(...a,): void }",
    "class C { m?(...a,): void }",
    "class C { static m(...a,): void; static m() {} }",
    "class C { constructor(...a,); constructor(...a: any[]) {} }",
    "class C { get x(...a,): number }",
    "declare class C { m(...a,): void }",
    "declare class C { constructor(...a,) }",
    "declare class C { m(...a,): void; n(...b,): void }",
    "export declare class C { static m(...a,): void }",
    "abstract class C { abstract m(...a,): void }",
    "declare abstract class C { abstract m(...a,): void }",
    "declare function f(...a,): void",
    "declare namespace N { function f(...a,): void; class C { m(...a,): void } }",
    'declare module "m" { export function f(...a,): void }',
    "namespace N { export declare function f(...a,): void }",
    "function f(...a,) {}",
    "function f(...a,) {}\nfunction g(...b,) {}",
    "function f(...a,) {}\nlet x: = 1",
    "class C { m(...a,) {} }",
    "class C { m(...a,) {} }\nlet x: = 1",
    "class C { m(...a,): void {} }",
    "class C { constructor(...a,) {} }",
    "function f(...a, b) {}",
    "function f(...a, b): void;",
    "function f(...a,,): void;",
    "function f(...a, ): void;",
    "class C { m(...a, b): void }",
    "declare class C { m(...a, b): void }",
    "declare class C { m(...a,,): void }",
    "(function (...a,) {})",
    "({ m(...a,) {} })",
    "(...a,) => 1",
    "async (...a,) => 1",
    "let f: (...a,) => void",
    "declare class C { m(...a,): void }\nclass D { m(...a,) {} }",
    "declare class C { m = (...a,) => 1 }",
    "declare class C { m(x = function (...a,) {}): void }",
    "declare class C { m(x = class { n(...a,) {} }): void }",
    "class C { m(x = class { n(...a,): void }): void {} }",
    "declare class C { [k: string]: any; m(...a,): void }",
  ],
  // parse_fn.rs parse_fn: an accessibility modifier before a parameter outside a constructor
  // (`is_identifier && (opts.is_constructor || !rest_arg)`, then "a modifier stands before a name on its line").
  "fn.param-modifier": [
    "function f(public x) {}",
    "function f(private x: number, protected y?: string, readonly z = 1, override w) {}",
    "function f(public x): void;",
    "declare function f(public x): void",
    "export default function (private x) {}",
    "const f = function (public x) {}",
    "class C { m(public x) {} }",
    "class C { static m(readonly x: number) {} }",
    "class C { set x(public v) {} }",
    "class C { m(public x): void }",
    "abstract class C { abstract m(public x): void }",
    "declare class C { m(public x): void }",
    "({ m(public x) {} })",
    "({ set x(public v) {} })",
    "function f(public) {}",
    "function f(public, x) {}",
    "function f(public = 1) {}",
    "function f(public: number) {}",
    "function f(public?) {}",
    "function f(public?: number) {}",
    "function f(public\nx) {}",
    "function f(public ...x) {}",
    "function f(...public) {}",
    "function f(...public x) {}",
    "function f(public {a}) {}",
    "function f(public [a]) {}",
    "function f(public readonly x) {}",
    "function f(readonly public x) {}",
    "function f(public public) {}",
    "function f(public public x) {}",
    "function f(public x, private y) {}",
    "function f(this: any, public x) {}",
    "function f(public this) {}",
    "function f(declare x) {}",
    "function f(static x) {}",
    "function f(abstract x) {}",
    "function f(accessor x) {}",
    "function f(async x) {}",
    "function f(override x) {}",
    "function f(in x) {}",
    "function f(out x) {}",
    "function f(public x = 1, y = x) { return x + y }",
    "function f(public x) { return x }\nf(1)",
    "function f(public await) {}",
    "async function f(public await) {}",
    "function* f(public yield) {}",
    "function f(public x?) {}",
    "function f(public x!) {}",
    "function f(public x: number = 1) {}",
    "class C { m(@d public x) {} }",
    "class C { m(public @d x) {} }",
    "class C { @d m(public x: number) {} }",
    "class C { constructor(public x) {} }",
    "class C { constructor(public x, private readonly y = 1) {} }",
    "class C { constructor(public ...x) {} }",
    "class C { constructor(...public) {} }",
    "class C { constructor(...public x) {} }",
    "class C { constructor(public {a}) {} }",
    "class C { constructor(public\nx) {} }",
    "class C { constructor(public) {} }",
    "class C { constructor(@d public x) {} }",
    "class C { constructor(public x); constructor(public x) {} }",
    "declare class C { constructor(public x) }",
    "(public x) => 1",
    "async (public x) => 1",
    "let f: (public x) => void",
    "interface I { m(public x): void }",
  ],
  // parse_property.rs parse_property: `[` in a class body is an index signature by isIndexSignature
  // (`is_class_index_signature` / `skip_class_index_signature`), where main read an expression and then `:`.
  "class.index-signature": [
    "class C { [k: string]: any }",
    "class C { [k: string]: any; }",
    "class C { [k: string]: any, }",
    "class C { [k: string]: any, [n: number]: any }",
    "class C { [k: string]: any; [n: number]: string }",
    "class C { [k: string]: any\n[n: number]: any }",
    "class C { [k: string]: any [n: number]: any }",
    "class C { static [k: string]: any }",
    "class C { readonly [k: string]: any }",
    "class C { static readonly [k: string]: any }",
    "class C { public [k: string]: any }",
    "class C { declare [k: string]: any }",
    "class C { abstract [k: string]: any }",
    "abstract class C { abstract [k: string]: any }",
    "class C { override [k: string]: any }",
    "class C { accessor [k: string]: any }",
    "class C { async [k: string]: any }",
    "class C { get [k: string]: any }",
    "class C { *[k: string]: any }",
    "class C { @d [k: string]: any }",
    "declare class C { [k: string]: any }",
    "class C { [...k: string[]]: any }",
    "class C { []: any }",
    "class C { [] }",
    "class C { [k?: string]: any }",
    "class C { [k?]: any }",
    "class C { [k?] = 1 }",
    "class C { [k, l: string]: any }",
    "class C { [k: string, l: number]: any }",
    "class C { [k: string,]: any }",
    "class C { [k,]: any }",
    "class C { [k]: any }",
    "class C { [k] = 1 }",
    "class C { [k]() {} }",
    "class C { [k]; }",
    "class C { [k: string] }",
    "class C { [k: string]; }",
    "class C { [k: string] = 1 }",
    "class C { [k: string]: any = 1 }",
    'class C { [k: string = "a"]: any }',
    "class C { [k = 1]: any }",
    "class C { [k = 1] = 2 }",
    "class C { [k: string = ]: any }",
    "class C { [public k: string]: any }",
    "class C { [k ? 1 : 2] = 1 }",
    "class C { [k ? a : b]() {} }",
    "class C { [k ?? l] = 1 }",
    "class C { [k?.l] = 1 }",
    "class C { [k ? : 1] = 1 }",
    "class C { [k: string]?: any }",
    "class C { [k: string]!: any }",
    "class C { [k: string](): void }",
    "class C { [k: string]: any\nm() {} }",
    "class C { [k: string]: any m() {} }",
    "class C { [k: string]\nm() {} }",
    'class C { ["k"]: string }',
    "class C { [`k`]: string }",
    "class C { [1]: string }",
    "class C { [k.l]: string }",
    "class C { [k as any]: string }",
    "class C { [<any>k]: string }",
    "class C { [k!]: string }",
    "class C { [async x => x]() {} }",
    "class C { [async]: any }",
    "class C { [async: string]: any }",
    "class C { [await: string]: any }",
    "class C { [yield: string]: any }",
    "async function f() { class C { [await: string]: any } }",
    "async function f() { class C { [await x]: any } }",
    "function* g() { class C { [yield: string]: any } }",
    "function* g() { class C { [yield]: any } }",
    "class C { [this: string]: any }",
    "class C { [new.target]: any }",
    "class C { [{ a }: string]: any }",
    "class C { [[a]: string]: any }",
    "class C { [k: string]: any; [Symbol.iterator]() {} }",
    'import { k } from "m";\nclass C { [k: string]: any }',
    'import { k } from "m";\nclass C { [...k: string[]]: any }',
    'import { k } from "m";\nclass C { [k?: string]: any }',
    'import { k, T } from "m";\nclass C { [k: T]: any }',
    'import { k } from "m";\nexport class C { [k]: any }',
    'import { k, v } from "m";\nclass C { [k: string = v]: any }',
    'import { k } from "m";\nclass C { static [k: string]: any }',
    'import k from "m";\nclass C { [k: string]: any }\nexport { C }',
    "({ [k: string]: 1 })",
    "({ [k]: 1 })",
    "(class { [k: string]: any })",
    "export default class { [k: string]: any }",
  ],
  // parse_typescript.rs parse_typescript_enum_stmt: a string or a template without substitutions in brackets names a member.
  "enum.bracket-name": [
    "enum E { ['a'] = 1 }",
    'enum E { ["a"], ["b"] = 2 }',
    "enum E { [`a`] = 1 }",
    "enum E { [`a`] }",
    "enum E { ['a'] }",
    "enum E { ['a'] = 1, b = E['a'] }",
    "enum E { ['a'] = 1, b = a }",
    "enum E { ['a-b'] = 1, c = E['a-b'] }",
    "const enum E { ['a'] = 1 }\nconsole.log(E.a)",
    "declare enum E { ['a'] = 1 }",
    "export enum E { ['a'] = 'x', ['b'] = 'y' }",
    "namespace N { export enum E { ['a'] } }",
    "enum E { [ 'a' ] = 1 }",
    "enum E { [\n'a'\n] = 1 }",
    "enum E { [/* c */ 'a' /* d */] = 1 }",
    "enum E { [`a${1}`] = 1 }",
    "enum E { [a] = 1 }",
    "enum E { [1] = 1 }",
    "enum E { ['a' + 'b'] = 1 }",
    "enum E { ['a',] = 1 }",
    "enum E { [] = 1 }",
    "enum E { ['a' = 1 }",
    "enum E { ['a']: 1 }",
    "enum E { [('a')] = 1 }",
    "enum E { [['a']] = 1 }",
    "enum E { 'a' = 1 }",
    "enum E { `a` = 1 }",
    "enum E { ['__proto__'] = 1 }",
    "enum E { ['a'] = 1, ['a'] = 2 }",
  ],
  // mod.rs parse_class + parse_property.rs: `accessor` is a modifier whatever the kind of decorators
  // (main: only with standard decorators), a class with experimental decorators rejects it, and without
  // decorators it is lowered. `scanImports` never sets `standard_decorators`, so JavaScript reaches it there.
  "class.accessor": [
    "class C { accessor x = 1 }",
    "class C { accessor x }",
    "class C { static accessor x = 1 }",
    "class C { accessor static x }",
    "class C { accessor\nx }",
    "class C { accessor = 1 }",
    "class C { accessor }",
    "class C { accessor; x }",
    "class C { accessor() {} }",
    "class C { accessor accessor }",
    "class C { accessor #x = 1 }",
    "class C { accessor [k] = 1 }",
    'class C { accessor "x" = 1 }',
    "class C { accessor 1 = 1 }",
    "class C { accessor x() {} }",
    "class C { accessor get x() { return 1 } }",
    "class C { get accessor() { return 1 } }",
    "class C { async accessor() {} }",
    "class C { accessor async x() {} }",
    "class C { accessor *x() {} }",
    "class C { accessor constructor }",
    "class C { accessor x = 1; accessor y = 2; m() { return this.x + this.y } }",
    "class C extends B { accessor x = super.y }",
    "(class { accessor x = 1 })",
    "export default class { accessor x = 1 }",
    "export class C { accessor x = 1 }",
    "({ accessor: 1 })",
    "({ accessor x() {} })",
    "class C { accessor x: number = 1 }",
    "class C { accessor x?: number }",
    "class C { accessor x!: number }",
    "class C { declare accessor x: number }",
    "class C { accessor declare x }",
    "class C { public accessor x = 1 }",
    "class C { private static accessor x = 1 }",
    "class C { readonly accessor x = 1 }",
    "class C { override accessor x = 1 }",
    "abstract class C { abstract accessor x: number }",
    "declare class C { accessor x: number }",
    "declare class C { @d accessor x: number }",
    "@d class C { accessor x = 1 }",
    "@d class C { static accessor x = 1 }",
    "class C { @d accessor x = 1 }",
    "class C { @d static accessor x = 1 }",
    "class C { @d accessor x: number }",
    "class C { @d m() {} accessor x = 1 }",
    "class C { accessor x = 1; @d m() {} }",
    "class C { m(@d p) {} accessor x = 1 }",
    "class C { constructor(@d p) {} accessor x = 1 }",
    "(class { @d accessor x = 1 })",
    "export default class { @d accessor x }",
    "@d export class C { accessor x }",
    "export @d class C { accessor x }",
    "const C = @d class { accessor x = 1 }",
    "@d class C { accessor x = 1 }\n@d class D { y = 1 }",
    "class C { accessor x = 1 }\n@d class D { y = 1 }",
    "@d class C { static { class D { accessor x = 1 } } }",
    "class C { @d accessor }",
    "class C { @d accessor = 1 }",
    "class C { @d accessor() {} }",
    "@d class C { accessor\nx }",
  ],
  // mod.rs parse_paren_expr (`level.lte(Level::Assign)`), parse_prefix.rs pfx_t_less_than and
  // mod.rs parse_async_prefix_expr (`is_after_question_and_before_colon`): a ":" after what stands in parentheses.
  "expr.colon-after-parens": [
    "a ? -<T>(b) : c",
    "a ? <T>(b) : c",
    "a ? !<T>(b) : c",
    "a ? typeof <T>(b) : c",
    "a ? void <T>(b) : c",
    "a ? ~<T>(b) : c",
    "a ? +<T>(b) : c",
    "a ? delete <T>(b) : c",
    "a ? await <T>(b) : c",
    "async function f() { return a ? await <T>(b) : c }",
    "a ? 1 + <T>(b) : c",
    "a ? b * <T>(c) : d",
    "a ? b || <T>(c) : d",
    "a ? b ?? <T>(c) : d",
    "a ? <T>(b).c : d",
    "a ? <T>(b)() : d",
    "a ? <T><U>(b) : c",
    "a ? <T>-<U>(b) : c",
    "a ? x = <T>(b) : c",
    "a ? [<T>(b)] : c",
    "a ? (<T>(b)) : c",
    "a ? <T>(b) : c => d",
    "a ? <T>(b): c => d : e",
    "a ? <T>(b) => c : d",
    "a ? <T>(b): U => c : d",
    "a ? <T,>(b) : c",
    "a ? <T,>(b) => c : d",
    "a ? <T extends U>(b) : c",
    "a ? <T extends U>(b) => c : d",
    "a ? <T>(b, c) : d",
    "a ? <T>() : d",
    "a ? <T>(...b) : c",
    "a ? <T>(b = 1) : c",
    "a ? <T>(b: U) : c",
    "a ? <T>({ b }) : c",
    "a ? b : <T>(c)",
    "a ? <T>(b) : <U>(c)",
    "a ? <T>(b) ? <U>(c) : d : e",
    "a ? b ? <T>(c) : d : e",
    "x = a ? <T>(b) : c",
    "f(a ? <T>(b) : c)",
    "switch (x) { case <T>(b): break }",
    "switch (x) { case -<T>(b): break }",
    "switch (x) { case !<T>(b): case 1 + <U>(c): break }",
    "switch (x) { case (b): break }",
    "switch (x) { case (b): T => c: break }",
    "({ [<T>(b)]: c })",
    "x = { k: <T>(b) }",
    "x = { k: -<T>(b) }",
    "for (const k in <T>(b)) {}",
    "(x = <T>(b)) => x",
    "a ? -(b) : c",
    "a ? (b) : c",
    "a ? (b) : c => d",
    "a ? (b): c => d : e",
    "a ? -(b): c => d : e",
    "a ? async <T>(b) : c",
    "a ? async <T>(b) => c : d",
    "a ? async <T>(b): c => d : e",
    "a ? async <T,>(b) : c",
    "a ? async (b) : c",
    "a ? async (b) : c => d",
    "a ? async (b): c => d : e",
    "a ? -async <T>(b) : c",
    "a ? await async <T>(b) : c",
    "a ? new <T>(b) : c",
    "a ? new C<T>(b) : c",
    "a ? f<T>(b) : c",
    "a ? f<T>(b): c => d : e",
    "a ? <T>b : c",
    "a ? -<T>b : c",
    "a ? <T>b.c(d) : e",
    "label: <T>(b)",
    "a ? { k: <T>(b) } : c",
    "a ? `${<T>(b)}` : c",
  ],
  // parse_fn.rs parse_arrow_body_with_flags, called from mod.rs parse_paren_expr (`is_body_before_colon`),
  // mod.rs parse_async_prefix_expr and parse_prefix.rs pfx_t_identifier (`arrow_body_flags`):
  // the body of an arrow function between "?" and ":" is read with the flag of its arrow function.
  "expr.arrow-body-before-colon": [
    "a ? (b) => (c) : d => e",
    "a ? b => (c) : d => e",
    "a ? async b => (c) : d => e",
    "a ? async (b) => (c) : d => e",
    "a ? async => (c) : d => e",
    "a ? (b) => (c) : d",
    "a ? b => (c) : d",
    "a ? (b) => (c): d => e : f",
    "a ? b => (c): d => e : f",
    "a ? async b => (c): d => e : f",
    "a ? (b: T) => (c) : d => e",
    "a ? (b: T) => (c): d => e : f",
    "a ? (b?) => (c) : d => e",
    "a ? (b?: T) => (c) : d => e",
    "a ? ({ b }) => (c) : d => e",
    "a ? ([b]) => (c) : d => e",
    "a ? ({ b }: T) => (c) : d => e",
    "a ? (...b) => (c) : d => e",
    "a ? (b, ...c) => (d) : e => f",
    "a ? (b, c) => (d) : e => f",
    "a ? (b = 1) => (c) : d => e",
    "a ? () => (c) : d => e",
    "a ? (): T => (c) : d => e",
    "a ? (b): T => (c) : d => e",
    "a ? <T>(b) => (c) : d => e",
    "a ? <T,>(b) => (c) : d => e",
    "a ? <T>(b: T) => (c) : d => e",
    "a ? async <T>(b) => (c) : d => e",
    "a ? async <T>(b) => (c): d => e : f",
    "a ? (b) => c ? (d) : e => f : g",
    "a ? (b) => (c, d) : e => f",
    "a ? (b) => async (c) : d => e",
    "a ? b => async (c) : d => e",
    "a ? async b => async (c) : d",
    "a ? (b) => (c) => (d) : e => f",
    "a ? b => c => (d) : e => f",
    "a ? (b) => { return (c) } : d => e",
    "a ? (b = (c) => (d)) => (e) : f => g",
    "a ? (b) => <T>(c) : d => e",
    "a ? (b) => -<T>(c) : d => e",
    "a ? b => <T>(c) : d",
    "a ? b => -(c) : d",
    "a ? b => (c).d : e => f",
    "a ? b => (c)() : e => f",
    "a ? b => (c) + 1 : e => f",
    "a ? b => 1 + (c) : e => f",
    "a ? b => [(c)] : e => f",
    "a ? b => ({ c }) : e => f",
    "a ? b => (c) as T : e => f",
    "a ? b => (c)! : e => f",
    "x = a ? (b) => (c) : d => e",
    "f(a ? (b) => (c) : d => e)",
    "a ? (b) => (c) : d => e ? (f) => (g) : h => i",
    "a ? (b) => a2 ? (c) => (d) : e => f : g => h",
    "a ? function () { return b => (c) } : d => e",
    "b => (c) : d => e",
    "(b) => (c): d => e",
    "x = (b) => (c): d => e",
    "a ? (b) : c => (d) : e",
    "a ? b => (c) : (d): e => f",
  ],
  // mod.rs parse_class skip_class_implements_entry: an entry that is no type, or does not end as one, is read again as an expression with type arguments.
  "class.implements-entry": [
    "class C implements A {}",
    "class C implements A<B>, C<D> {}",
    "class C implements a() {}",
    "class C implements a.b() {}",
    "class C implements a<T>() {}",
    "class C implements A, b() {}",
    "class C implements a(), B {}",
    "class C implements (a) {}",
    "class C implements (a)() {}",
    "class C implements a[0] {}",
    "class C implements a[0]() {}",
    "class C implements a.b<T>.c {}",
    "class C implements new A {}",
    "class C implements new A() {}",
    "class C implements typeof a {}",
    "class C implements a! {}",
    "class C implements {} {}",
    "class C implements { a: 1 } {}",
    "class C implements A & B {}",
    "class C implements A | B {}",
    "class C implements a`b` {}",
    "class C implements a?.b {}",
    "class C implements a?.() {}",
    "class C implements this {}",
    "class C implements this.a() {}",
    "class C implements void 0 {}",
    "class C implements await a {}",
    'class C implements import("m") {}',
    'class C implements import("m").A {}',
    "class C implements import.meta {}",
    "class C implements super.x {}",
    "class C implements super() {}",
    "class C { #x; static D = class implements this.#x() {} }",
    "class C implements #x {}",
    "class C implements 1 {}",
    'class C implements "a" {}',
    "class C implements function () {} {}",
    "class C implements class {} {}",
    "class C implements a = b {}",
    "class C implements a, {}",
    "class C implements {}",
    "class C implements , A {}",
    "class C implements",
    "class C implements a() extends B {}",
    "class C extends B implements a() {}",
    "const C = class implements a() {}",
    "class C implements a.b.c, d.e() {}",
    "class C implements a() { m() {} }",
    "class C implements a()\n{}",
    "class C implements a(b => { let x: = 1 }) {}",
    "class C implements a(class { m(): = 1 }) {}",
    "class C implements a(<T>(x)) {}",
    "class C implements a(/* c */) {}",
    "class C implements a(import.meta) {}",
    "class C implements a(await b) {}",
    "class C implements a(function* () { yield }) {}",
    "class C implements a(b = 1) {}",
    "class C implements a(b, c)<T> {}",
    "class C implements a<T>(b)<U> {}",
    'import x from "m";\nclass C implements x() {}',
    'import { x, y } from "m";\nclass C implements x.z<y>() {}',
    'import x from "m";\nexport class C implements x(x) {}',
    "declare class C implements a() {}",
    "abstract class C implements a() {}",
    "@d class C implements a() {}",
    "interface I extends a() {}",
  ],
  // parse_stmt.rs parse_stmt_fallthrough parse_stmt_named_like_cast: `type`, `interface`, `namespace` and `module` before `as` or `satisfies`.
  "stmt.named-like-cast": [
    "type as = 1",
    "type as<T> = T",
    "type satisfies = 1",
    "type as = 1; type b = as",
    "type as any",
    "type as <T>(x: T) => void",
    "type as\n= 1",
    "type\nas = 1",
    "let type: any; type as any",
    "let type: any; type as = 1",
    "type as {} Foo {}",
    "export type as = 1",
    "declare type as = 1",
    "{ type as = 1 }",
    "function f() { type as = 1 }",
    "if (a) type as = 1",
    "interface as {}",
    "interface as {}\nfoo()",
    "interface as<T> {}",
    "interface as extends B {}",
    "interface satisfies<T> extends B<T> { a: T }",
    "interface as any",
    "interface as any\nfoo()",
    "interface as {} | X",
    "interface as {} | X\nfoo()",
    "interface as {} + 1",
    "interface as {} Foo {}",
    "interface as { a: 1 }",
    "interface as { [K in T]: 1 }",
    "interface as {}.a",
    "interface as {} as any",
    "interface as {};",
    "export interface as {}",
    "declare interface as {}",
    "function f() { interface as {} }",
    "namespace as {}",
    "namespace as { export const a = 1 }",
    "namespace as { foo(): void }",
    "namespace as { a: 1 }",
    "namespace as.b {}",
    "namespace as any",
    "namespace as {} + 1",
    "namespace as {} Foo {}",
    "namespace satisfies {}",
    "declare namespace as {}",
    "declare namespace as { foo(): void }",
    "export namespace as {}",
    "function f() { namespace as {} }",
    "{ namespace as {} }",
    "module as {}",
    "module as.b {}",
    "module as any",
    "module as { export const a = 1 }",
    "declare module as {}",
    "abstract as any",
    "global as any",
    "declare as any",
    "type as = 1\ninterface as {}\nnamespace as {}",
    "var type, as; type\nas\n= 1",
    "var interface, as; interface\nas\n{}",
  ],
  // parse_stmt.rs parse_stmt_fallthrough_ts_keyword: "abstract declare class".
  "stmt.abstract-declare-class": [
    "abstract declare class C {}",
    "abstract declare class C { m(): void }",
    "abstract declare class C { abstract m(): void }",
    "export abstract declare class C {}",
    "abstract declare class C {}\nnew C()",
    "abstract\ndeclare class C {}",
    "abstract declare\nclass C {}",
    "abstract declare function f(): void",
    "abstract declare const x: number",
    "abstract declare",
    "@d abstract declare class C {}",
    "declare abstract class C {}",
    "declare abstract declare class C {}",
    "namespace N { abstract declare class C {} }",
    "abstract declare class C { m(...a,): void }",
    "abstract class declare {}",
  ],
  // parse_stmt.rs parse_stmt t_import: inside a namespace that is not declared, "import(" and "import." start an expression.
  "stmt.import-in-namespace": [
    'namespace N { import("m") }',
    "namespace N { import.meta.url }",
    'namespace N { import("m").then(x => x) }',
    'namespace N { const x = import("m") }',
    'namespace N { export const x = import("m") }',
    'namespace N { namespace M { import("m") } }',
    'namespace N { { import("m") } }',
    'namespace N { function f() { import("m") } }',
    'declare namespace N { import("m") }',
    "namespace N { import }",
    "namespace N { import a = b.c }",
    "namespace N { export import a = b.c }",
    'namespace N { import a = require("m") }',
    'namespace N { import x from "m" }',
    'namespace N { import * as x from "m" }',
    'namespace N { import "m" }',
    'namespace N { import { a } from "m" }',
    'namespace N { import type { a } from "m" }',
    "namespace N { import = 1 }",
    "namespace N { import<T>() }",
    'module N { import("m") }',
    'export namespace N { import("m") }',
  ],
  // mod.rs parse_path: "with" on the line after the path starts the import attributes when "{" follows. JavaScript reaches it.
  "path.with-on-next-line": [
    'import a from "b"\nwith { type: "json" }',
    'import "b"\nwith { type: "json" }',
    'import * as a from "b"\nwith { type: "text" }',
    'import a, { b } from "c"\nwith { type: "json" };\nfoo()',
    'import { a } from "b"\nwith { type: "json" }\nfoo(a)',
    'export * from "b"\nwith { type: "json" }',
    'export * as ns from "b"\nwith { type: "json" }',
    'export { a } from "b"\nwith { type: "json" }',
    'import a from "b"\nwith {}',
    'import a from "b"\nwith { type: "macro" }',
    'import a from "b"\n\n\nwith { type: "json" }',
    'import a from "b" // c\nwith { type: "json" }',
    'import a from "b"\nwith\n{ type: "json" }',
    'import a from "b" with\n{ type: "json" }',
    'import a from "b" with { type: "json" }',
    'import a from "b"\nwith { type: "json" }\nwith { type: "json" }',
    'import a from "b"\nwith (x) {}',
    'import a from "b"\nwith (x) { y }',
    'import a from "b";\nwith { type: "json" }',
    'import a from "b"\nwith',
    'import a from "b"\nwith x',
    'import a from "b"\nwith [x]',
    'import a from "b"\nassert { type: "json" }',
    'import a from "b" assert { type: "json" }',
    'import("b")\nwith { type: "json" }',
    'import type a from "b"\nwith { type: "json" }',
    'import type { a } from "b"\nwith { "resolution-mode": "import" }',
    'import { type a } from "b"\nwith { type: "json" }',
    'export type { a } from "b"\nwith { type: "json" }',
    'export type * from "b"\nwith { type: "json" }',
    'import a = require("b")\nwith { type: "json" }',
  ],
  // Sites where round 1 put a token test before a call of the skipper, or another call in its place: the behaviour must stay.
  "guard.type-parameters-and-arguments": [
    "function f<T>() {}",
    "function f<const T>() {}",
    "function f<>() {}",
    "function f<T,>() {}",
    "function f<T = >() {}",
    "function f<in T>() {}",
    "function f\n<T>() {}",
    "(function <T>() {})",
    "(function f<T>() {})",
    "(function <>() {})",
    "export default function <T>() {}",
    "export default async function* <T>() {}",
    "class C<T> {}",
    "class C<in T, out U, const V> {}",
    "class C<> {}",
    "(class <T> {})",
    "(class C<in out T> {})",
    "export default class <T> {}",
    "@d class C<T> {}",
    "class C { m<T>() {} }",
    "class C { m?<T>(): void }",
    "class C { m<>() {} }",
    "class C { m!<T>() {} }",
    "class C { 'm'<T>() {} }",
    "class C { [k]<T>() {} }",
    "class C { get x<T>() { return 1 } }",
    "class C { constructor<T>() {} }",
    "class C { x<T> = 1 }",
    "({ m<T>() {} })",
    "({ m<const T>(x: T) {} })",
    "({ async *m<T>() {} })",
    "({ m<T> })",
    "@x<y> class C {}",
    "@x<y>() class C {}",
    "@x.y<z> class C {}",
    "@x<<T>() => void> class C {}",
    "@x<<T>() => void>() class C {}",
    "@(x)<y> class C {}",
    "@x<y class C {}",
    "class C { @x<y> m() {} }",
    "class C { @x<y>() m() {} }",
    "class C { @x << 1 m() {} }",
    "@x< class C {}",
    "<Foo<T> />",
    '<Foo<T> a="b"></Foo>',
    "<Foo<<T>() => void> />",
    "<Foo<T, U> {...a} />",
    "<Foo<> />",
    "<Foo < T > />",
    "<a.b<T> />",
    "<Foo<T>></Foo>",
    "<Foo<T",
    "function f(this: T) {}",
    "function f(this) {}",
    "function f(this, a) {}",
    "function f(this: T, ...a) {}",
    "function f(this?: T) {}",
    "function f(a, this: T) {}",
    "function f(this: ) {}",
    "function f(this = 1) {}",
    "class C { m(this: this) {} }",
    "a?.<T>()",
    "a?.<T>b",
    "a?.<T>",
    "a?.b<T>()",
    "new A<T>",
    "new A<T>()",
    "new A<T>.b",
    "class C extends B<T> {}",
    "class C extends B<T>() {}",
    "class C extends B<> {}",
    "class C extends a.b<T> implements D {}",
    "class C extends (B)<T> {}",
    "x as T",
    "x satisfies T",
    "x as\nT",
    "x as const",
    "x! as T",
    "x!",
    "x!.y!()",
    "x\n!y",
    "try {} catch (e: any) {}",
    "try {} catch (e: ) {}",
    "try {} catch ({ a }: any) {}",
    "let x!: T",
    "let x: T = 1, y!: U",
    "let x!",
    "for (let x: T of y) {}",
    "for (let x: T in y) {}",
    "for (let x: T = 0;;) {}",
    "@(a) class C {}",
    "@(a!) class C {}",
    "@a! class C {}",
    "@a.b! class C {}",
    "@a!.b class C {}",
  ],
};

export const sources = Object.entries(SEAMS).flatMap(([prod, list]) => list.map(src => ({ src, prod })));

if (import.meta.main) {
  const out = process.argv[2] ?? join(import.meta.dirname, "corpus.seams.json");
  const seen = new Set();
  for (const { src, prod } of sources) {
    if (seen.has(src)) throw new Error(`the source is there twice: ${prod} ${JSON.stringify(src)}`);
    seen.add(src);
  }
  writeFileSync(out, JSON.stringify({ name: "seams", contexts: {}, forms: [], sources }));
  for (const [prod, list] of Object.entries(SEAMS)) console.log(`${String(list.length).padStart(5)}  ${prod}`);
  console.log(`${out}: ${sources.length} sources in ${Object.keys(SEAMS).length} groups`);
}
