// Which rule of the skip test fires, which rules it masks, and the spellings behind each reason (research probe).
import { readFileSync } from "node:fs";
import { enumerateInstances, getStatus, skippedTests } from "./compiler_runner";
import { TSFalse } from "./harnessutil";
import { readFile } from "./vfs";
const root = "/workspace/ref/typescript-go/_submodules/TypeScript/tests/cases";
const e = enumerateInstances({ casesRoot: root });
const masked = new Map<string, number>();
const spell = new Map<string, Map<string, number>>();
const fromConfigUnit: string[] = [];
const emptyPath: string[] = [];
const pathReasons = new Map<string, number>();
for (const i of e.instances) {
  const content = readFile(root + "/" + i.casePath).contents;
  const cfg = i.config === undefined ? undefined : new Map(i.config);
  const st = getStatus(content, root + "/" + i.casePath, cfg);
  const o = st.options;
  const all: string[] = [];
  if (o.module === 2 || o.module === 3 || o.module === 4) all.push("module");
  if (o.moduleResolution === 1 || o.moduleResolution === 2) all.push("moduleResolution");
  if (o.esModuleInterop === TSFalse) all.push("esModuleInterop");
  if (o.allowSyntheticDefaultImports === TSFalse) all.push("allowSyntheticDefaultImports");
  if (o.baseUrl !== "") all.push("baseUrl");
  if (o.outFile !== "") all.push("outFile");
  if (o.target === 1) all.push("target");
  if (o.alwaysStrict === TSFalse) all.push("alwaysStrict");
  if (all.length === 0) continue;
  const key = all.join("+");
  masked.set(key, (masked.get(key) ?? 0) + 1);
  const first = all[0];
  const directive = i.config?.get(first.toLowerCase());
  const src = directive !== undefined ? "directive:" + directive : "config-unit";
  if (!spell.has(first)) spell.set(first, new Map());
  const m = spell.get(first)!;
  const k = first === "baseUrl" || first === "outFile" ? (directive !== undefined ? "directive" : "config-unit") : src;
  m.set(k, (m.get(k) ?? 0) + 1);
  if (directive === undefined) fromConfigUnit.push(`${i.name}\t${i.reason}`);
  if ((first === "baseUrl" || first === "outFile") && directive !== undefined && directive.trim() === "") emptyPath.push(`${i.name}\t${JSON.stringify(directive)}\t${i.reason}`);
  if (first === "baseUrl" || first === "outFile") pathReasons.set(i.reason, (pathReasons.get(i.reason) ?? 0) + 1);
}
console.log("rule sets (first is the reason):");
for (const [k, v] of [...masked].sort((a, b) => b[1] - a[1])) console.log(String(v).padStart(6), k);
console.log("spellings of the deciding value:");
for (const [k, m] of spell) console.log(" ", k, JSON.stringify([...m].sort((a, b) => b[1] - a[1])));
console.log("decided by the config unit alone:", fromConfigUnit.length);
for (const x of fromConfigUnit) console.log("  ", x);
console.log("empty outFile or baseUrl directive:", emptyPath.length);
for (const x of emptyPath) console.log("  ", x);
console.log("distinct path reasons:", pathReasons.size);
for (const [k, v] of [...pathReasons].sort((a, b) => b[1] - a[1]).slice(0, 25)) console.log(String(v).padStart(6), k);
