const fs = require("fs");
const inputs = [
  ["ts", "\"abc"],
  ["ts", "'abc\n x"],
  ["ts", "`abc "],
  ["ts", "`abc ${x"],
  ["ts", "/* abc"],
  ["ts", "// c\n/* abc"],
  ["ts", "\u0001"],
  ["ts", "#!/usr/bin/env bun\n\"abc"],
  ["ts", "#!/usr/bin/env bun\n/* abc"],
  ["ts", "0b2"],
  ["ts", "1_"],
  ["ts", "'\\"],
  ["ts", "\\u{110000}"],
  ["ts", "\\x"],
  ["ts", "08n"],
  ["ts", "1e"],
  ["ts", "@"],
  ["ts", "#"],
  ["ts", "-->\n\"abc"],
  ["ts", "<!-- x\n\"abc"],
  ["js", "\"abc"],
  ["tsx", "\"abc"],
  ["ts", "\"abc\\\n"],
  ["ts", "  \"abc\r\nx"],
  ["ts", "'a\\\r\nb"],
  ["ts", "x = \"abc"],
  ["ts", "x = `abc"],
  ["ts", "x = /* abc"],
  ["ts", "let x = 1 1;"],
  ["ts", ")"],
  ["ts", "default"],
  ["ts", "let x: ;"],
  ["ts", "x as A | () => void;"],
  ["ts", "import * ass x from 'y'"],
  ["ts", "\u00a0\"abc"],
  ["ts", "\ufeff\"abc"],
  ["ts", "1a"],
  ["ts", "0x"],
  ["ts", "'\\u{zz}'"],
  ["ts", "`\\u{zz}`"],
  ["ts", "\u2028\"abc"],
];
fs.writeFileSync("inputs.json", JSON.stringify(inputs, null, 1));
fs.writeFileSync("inputs.hex", inputs.map(([k, s], i) => `${i} ${k} ${Buffer.from(s, "utf8").toString("hex")}`).join("\n") + "\n");
