// More shapes, for the rules of ESLint from no-multi-assign to no-useless-assignment. In the form of shapes.ts.
const seq = (n: number, f: (i: number) => string, sep = "") => Array.from({ length: n }, (_, i) => f(i)).join(sep);
const rep = (text: string, n: number) => text.repeat(n);

/** A shape is made when it is asked for. */
function lazily(shapes: Record<string, () => string>): Record<string, string> {
  const made: Record<string, string> = {};
  for (const [name, make] of Object.entries(shapes)) Object.defineProperty(made, name, { get: make, enumerable: true });
  return made;
}

export function wide(n: number): Record<string, string> {
  const fn = (body: string) => `function f(a, b) {\n${body}\n}\n`;
  return lazily({
    // no-useless-assignment: many variables, a long way from the assignment to where it is read, or to the end
    "assign-far-reads.js": () => fn(seq(n, i => `let v${i} = 0;\n`) + rep("if (a) b();\n", n) + seq(n, i => `b(v${i});\n`)),
    "assign-far-reads-returns.js": () => fn(seq(n, i => `let v${i} = 0;\n`) + rep("if (a) return;\n", n) + seq(n, i => `b(v${i});\n`)),
    "assign-far-maybe.js": () => fn(seq(n, i => `let v${i} = 0; if (a) v${i} = 1;\n`) + rep("if (a) b();\n", n) + seq(n, i => `b(v${i});\n`)),
    "assign-dead-ends.js": () => fn(seq(n, i => `let v${i} = b(); if (a) { b(v${i}); v${i} = 2; }\n`)),
    "assign-dead-ends-loop.js": () => fn("for (;;) {\n" + seq(n, i => `let v${i} = b(); if (a) { b(v${i}); v${i} = 2; }\n`) + "}"),
    "assign-dead-ends-continues.js": () => fn("for (;;) {\n" + seq(n, i => `let v${i} = b(); if (a) { b(v${i}); v${i} = 2; }\nif (b) continue;\n`) + "}"),
    "assign-dead-ends-breaks.js": () => fn("for (;;) {\n" + seq(n, i => `let v${i} = b(); if (a) { b(v${i}); v${i} = 2; }\nif (b) break;\n`) + "}"),
    "assign-dead-ends-outer.js": () => fn(seq(n, i => `let v${i} = 0;\n`) + "for (;;) {\n" + seq(n, i => `if (a) { b(v${i}); v${i} = 2; }\nif (b) continue;\n`) + "}"),
    "assign-cases-fallthrough.js": () => fn("let v = 0;\nswitch (a) {\n" + seq(n, i => `case ${i}: v = ${i};\n`) + "}\nreturn v;"),
    "assign-cases-break.js": () => fn("let v = 0;\nswitch (a) {\n" + seq(n, i => `case ${i}: v = ${i}; break;\n`) + "}\nreturn v;"),
    "assign-cases-empty.js": () => fn("let v = 0;\nswitch (a) {\n" + seq(n, i => `case ${i}: v = ${i};\n`) + seq(n, i => `case ${n + i}:\n`) + "}\nreturn v;"),
    "assign-cases-many-variables.js": () => fn(seq(n, i => `let v${i} = 0;\n`) + "switch (a) {\ncase -1:\n" + seq(n, i => `v${i} = 1;\n`) + seq(n, i => `case ${i}: b();\n`) + "}\n" + seq(n, i => `b(v${i});\n`)),
    "assign-before-switch.js": () => fn("let v = 0;\n" + rep("if (a) v = 1;\n", n) + "switch (a) {\n" + seq(n, i => `case ${i}: b(); break;\n`) + "}\nreturn v;"),
    "assign-in-tries.js": () => fn("let v = 0;\n" + rep("try { v = 1; } catch (e) { v = 2; }\n", n) + "return v;"),
    "assign-between-tries.js": () => fn("let v = 0;\n" + rep("try { b(); } catch (e) {}\nif (a) v = 1;\n", n) + "return v;"),
    "assign-try-long.js": () => fn("let v = 0;\n" + rep("if (a) v = 1;\n", n) + "try {\n" + rep("b();\n", n) + "v = 2; } catch (e) { b(v); }\nreturn v;"),
    "assign-finally.js": () => fn("let v = 0;\n" + rep("try { if (a) return; } finally { v = 1; }\n", n) + "return v;"),
    "assign-pattern-defaults.js": () => fn("let x = 0, y;\n[x, y = (" + seq(n, i => `a && (x = ${i})`, ", ") + ")] = b;\nreturn x;"),
    "assign-pattern-defaults-each.js": () => fn("let x = 0, y;\n[" + seq(n, i => `x, y = (x = ${i})`, ", ") + "] = b;\nreturn x;"),
    "assign-pattern-same.js": () => fn("let x = 0;\n[" + rep("x, ", n) + "] = (" + seq(n, i => `x = ${i}`, ", ") + ");\nreturn x;"),
    "assign-pattern-stmts.js": () => fn("let x = 0, y;\n" + rep("[x, y = (x = 1)] = b;\n", n) + "return x;"),
    "assign-declarators-read.js": () => fn(seq(n, i => `let v${i} = 0;\n`) + "let " + seq(n, i => `w${i} = v${i}`, ", ") + ";\nreturn w0;"),
    "assign-sequence.js": () => fn("let v = 0;\n" + seq(n, i => `v = ${i}`, ", ") + ";\nreturn v;"),
    "assign-logical.js": () => fn("let v = 0;\n" + rep("a && (v = 1);\n", n) + "return v;"),
    "assign-cond.js": () => fn("let v = 0;\n" + rep("v = a ? 1 : v;\n", n) + "return v;"),
    "assign-module-exported.js": () => "let v = 0;\n" + rep("v = 1;\n", n) + "export { v };",
    "assign-module.js": () => "let v = 0;\n" + rep("if (a) v = 1;\n", n) + "f(v); export {};",
    "assign-loops-each.js": () => fn(seq(n, i => `let v${i} = 0; while (a) { v${i} = v${i} + 1; }\n`)),
    "assign-labels-breaks.js": () => fn("let v = 0;\n" + seq(n, i => `l${i}: { if (a) break l${i}; v = ${i}; }\n`) + "return v;"),
    // no-unused-vars
    "unused-same-function-self.js": () => rep("function g() { g(); }\n", n),
    "unused-same-var-function-self.js": () => rep("var g = function () { g(); };\n", n),
    "unused-same-class-self.js": () => rep("class A { m() { return A; } }\n", n),
    "unused-self-plus.js": () => fn("let v = 0;\nv = " + rep("v + ", n) + "v;"),
    "unused-self-sequence.js": () => fn("let v = 0;\n" + seq(n, i => `v = ${i}`, ", ") + ";"),
    "unused-self-functions.js": () => fn("let v = 0;\nv = " + rep("function () { return v; } + ", n) + "1;"),
    "unused-same-interface-self.ts": () => rep("interface I { a: I; }\n", n),
    "unused-same-namespace-self.ts": () => rep("namespace N { N; }\n", n),
    "unused-same-enum-self.ts": () => seq(n, i => `enum E { a${i} = E.b }\n`),
    "unused-mapped-types.ts": () => seq(n, i => `type A${i} = { [K in B]: K };\n`),
    "unused-self-updates.js": () => fn("let v = 0;\n" + rep("v = v + 1;\n", n)),
    "unused-rest-sibling.js": () => "const {" + seq(n, i => `v${i}`, ", ") + ", ...rest} = a; f(rest);",
    "unused-array-holes.js": () => "const [" + rep(",", n) + seq(n, i => `v${i}`, ", ") + "] = a;",
    "unused-nested-single.js": () => seq(n, i => `const {a: {b: [v${i}]}} = a;\n`),
    "unused-params-patterns.js": () => "function f(" + seq(n, i => `{p${i}}, q${i}`, ", ") + ") { return q0; }",
    "unused-params-same.js": () => "function f(" + rep("p, ", n) + "p) {}",
    "unused-fns-params.js": () => seq(n, i => `function f${i}(a, b, c, d, e, g) { return c; }\n`),
    "unused-imports.js": () => "import {" + seq(n, i => `v${i}`, ", ") + '} from "a";',
    "unused-catch.js": () => rep("try { f(); } catch (e) {}\n", n),
    // no-unmodified-loop-condition
    "loop-test-plus.js": () => fn("while (" + rep("a + ", n) + "a) { b(); }"),
    "loop-test-and.js": () => fn("while (" + rep("a && ", n) + "a) { b(); }"),
    "loop-test-plus-modified.js": () => fn("while (" + rep("a + ", n) + "a) { a++; }"),
    "loop-test-functions.js": () => fn("while (" + rep("a + function () { while (a + b) {} } + ", n) + "a) { b(); }"),
    "loop-same-modified.js": () => fn(rep("while (a) { a = b(); }\n", n)),
    "loop-modified-in-functions.js": () => "let v = 0;\n" + seq(n, i => `function g${i}() { v++; }\n`) + seq(n, i => `while (v) { g${i}(); }\n`),
    "loop-modified-in-function-calls.js": () => "let v = 0;\nfunction g() { v++; }\n" + rep("while (v) { g(); }\n", n),
    "loop-not-modified-in-functions.js": () => "let v = 0;\n" + seq(n, i => `function g${i}() { v++; }\n`) + rep("while (v) { f(); }\n", n),
    // other rules
    "self-assign-objects.js": () => "({" + seq(n, i => `a${i}`, ", ") + "} = {" + seq(n, i => `a${i}`, ", ") + "});",
    "self-assign-objects-same.js": () => "({" + rep("a, ", n) + "} = {b, c, d, e, f, g, h, i, j, a});",
    "self-assign-chain.js": () => "a" + rep(".b", n) + " = a" + rep(".b", n) + ";",
    "regex-spaces-classes.js": () => "x = /" + rep("[  ]", n) + "  /;",
    "underscore-chain.js": () => "a" + rep("._b", n) + ";",
    "underscore-destructure.js": () => "const {" + seq(n, i => `_a${i}`, ", ") + "} = x;",
    "underscore-implements.ts": () => "class A implements " + seq(n, i => `B._a${i}`, ", ") + " {}",
    "before-define-static.js": () => "class A {\n" + seq(n, i => `static a${i} = A;\n`) + "}",
    "before-define-static-blocks.js": () => "class A {\n" + rep("static { A; }\n", n) + "}",
    "before-define-fields.js": () => "class A {\n" + seq(n, i => `a${i} = A;\n`) + "}",
    "before-define-implements.ts": () => "class A implements " + seq(n, i => `B${i}`, ", ") + " {}\n" + seq(n, i => `interface B${i} {}\n`),
    "before-define-extends.ts": () => "interface A extends " + seq(n, i => `B${i}`, ", ") + " {}\n" + seq(n, i => `interface B${i} {}\n`),
    "restricted-names-vars.js": () => rep("var NaN = 1;\n", n),
    "restricted-names-undefined.js": () => rep("var undefined;\n", n),
    "restricted-names-params.js": () => rep("function f(undefined) {}\n", n),
    "multi-str.js": () => rep('x = "a\\\nb";\n', n),
    "multi-str-keys.js": () => "x = {\n" + rep('"a\\\nb": 1,\n', n) + "};",
    "nonoctal.js": () => rep('x = "\\8";\n', n),
    "nonoctal-keys.js": () => "x = {\n" + rep('"\\8": 1,\n', n) + "};",
    "self-compare-chain.js": () => "x = a" + rep(" < (b < c)", n) + ";",
    "self-compare-chain-escape.js": () => 'y = "\\n"; x = a' + rep(" < (b < c)", n) + ";",
    "proto-builtins-chain.js": () => "a" + rep(".hasOwnProperty(b)", n) + ";",
    "proto-builtins-optional-chain.js": () => "a?.c" + rep(".hasOwnProperty(b)", n) + ";",
    "tabs-after-indent.js": () => rep(" ", n) + rep("x;\t", n),
    "restricted-exports-pattern.js": () => "export const {" + seq(n, i => `a${i}`, ", ") + "} = x;",
    "plusplus-for.js": () => "for (;; " + rep("a++, ", n) + "a++) {}",
    "sync-chain.js": () => "a" + rep(".bSync", n) + ";",
    "unassigned-same.js": () => rep("var v; f(v);\n", n),
    "param-props-plus.js": () => "function f(a) { x = " + rep("a + ", n) + "a; }",
    "param-props-chain.js": () => "function f(a) { a" + rep(".b", n) + " = 1; }",
    "param-redeclared.js": () => "function f(a) {\n" + rep("function a() {}\n", n) + "a = 1; }",
    "private-chain.js": () => "class A { #x; m() { return this" + rep(".#x", n) + "; } }",
    "private-uses.js": () => "class A { #x; m() {\n" + rep("this.#x;\n", n) + "} }",
    "ctor-loops.js": () => "class A extends B { constructor() {\n" + rep("while (a) { b(); }\n", n) + "super(); } }",
    "ctor-ifs-this.js": () => "class A extends B { constructor() {\n" + rep("if (a) { this.b; }\n", n) + "super(); } }",
    "ctor-ifs-super.js": () => "class A extends B { constructor() {\n" + rep("if (a) { super(); }\n", n) + "this.a; } }",
    "ctor-loop-ifs.js": () => "class A extends B { constructor() {\nfor (;;) {\n" + rep("if (a) { this.b; continue; }\n", n) + "}\nsuper(); } }",
    "class-constructors-nosuper.js": () => rep("class A extends B { a = 1; constructor() {} }\n", n),
    "class-nosuper-fields.js": () => "class A extends B {\n" + seq(n, i => `a${i} = 1;\n`) + "constructor() {} }",
    "directives-parens.js": () => rep('("use strict");\n', n),
    "unused-expr-as.ts": () => "x" + rep(" as any", n) + ";",
    "unused-expr-nonnull.ts": () => "(" .repeat(0) + "x" + rep("!.a", n) + ";",
    "unused-expr-logical.js": () => rep("a && ", n) + "b();",
    "sequences.js": () => rep("a, ", n) + "a;",
    "return-await.js": () => "async function f(a) {\n" + rep("if (a) return await a;\n", n) + "}",
    "return-await-logical.js": () => "async function f(a) { return " + rep("a && ", n) + "await a; }",
    "unsafe-finally.js": () => "function f(a) {\n" + rep("try {} finally { if (a) return; }\n", n) + "}",
    // no-unsafe-finally: an else-if chain with a jump in each branch, in a finally block or beside one
    "finally-else-if-returns.js": () => fn("try {} finally {\n" + rep("if (a) { return; } else ", n) + "{}" + "\n}"),
    "finally-else-if-throws.js": () => fn("try {} finally {\n" + rep("if (a) { throw a; } else ", n) + "{}" + "\n}"),
    "finally-else-if-breaks-out.js": () => fn("for (;;) { try {} finally {\n" + rep("if (a) { break; } else ", n) + "{}" + "\n} }"),
    "finally-else-if-breaks-in.js": () => fn("try {} finally { for (;;) {\n" + rep("if (a) { break; } else ", n) + "{}" + "\n} }"),
    "finally-else-if-continues-out.js": () => fn("for (;;) { try {} finally {\n" + rep("if (a) { continue; } else ", n) + "{}" + "\n} }"),
    "finally-else-if-continues-in.js": () => fn("try {} finally { for (;;) {\n" + rep("if (a) { continue; } else ", n) + "{}" + "\n} }"),
    "finally-else-if-switch.js": () => fn("try {} finally { switch (a) { case 1:\n" + rep("if (a) { break; } else ", n) + "{}" + "\n} }"),
    "finally-else-if-label-out.js": () => fn("l: try {} finally {\n" + rep("if (a) { break l; } else ", n) + "{}" + "\n}"),
    "finally-else-if-label-in.js": () => fn("try {} finally { l: {\n" + rep("if (a) { break l; } else ", n) + "{}" + "\n} }"),
    "finally-labels-each-in.js": () => fn("try {} finally {\n" + seq(n, i => `l${i}: { if (a) break l${i}; }\n`) + "}"),
    "finally-labels-same-in.js": () => fn("try {} finally {\n" + rep("l: { if (a) break l; }\n", n) + "}"),
    "try-else-if-returns.js": () => fn("try {\n" + rep("if (a) { return; } else ", n) + "{}" + "\n} finally {}"),
    "shadow-catch-var.js": () => "function f() {\n" + rep("try {} catch (e) { var e; }\n", n) + "}",
    "shadow-params.js": () => "let v = 1;\n" + rep("function f(v) {}\n", n),
    "shadow-many.js": () => seq(n, i => `let v${i} = 1;\n`) + "function f() {\n" + seq(n, i => `let v${i} = 1;\n`) + "}",
    "restricted-globals.js": () => rep("event;\n", n),
    "restricted-window-chain.js": () => "window" + rep(".window", n) + ".event;",
    "restricted-props.js": () => rep("a.b;\n", n),
    "restricted-props-pattern.js": () => "const {" + rep("b, ", n) + "} = a;",
    "restricted-imports.js": () => seq(n, i => `import a${i} from "foo";\n`),
    "restricted-imports-names.js": () => "import {" + seq(n, i => `a${i}`, ", ") + '} from "foo";',
    "restricted-exports.js": () => seq(n, i => `export const a${i} = 1;\n`),
    "restricted-exports-names.js": () => seq(n, i => `const a${i} = 1;\n`) + "export {" + seq(n, i => `a${i}`, ", ") + "};",
    "restricted-modules.js": () => rep('require("foo");\n', n),
    "restricted-syntax.js": () => rep("a in b;\n", n),
    "assign-reads-blocks.js": () => fn("let v = 0;\nif (a) v = 1;\n" + rep("{ b(v); }\n", n)),
  });
}

export function deep(n: number): Record<string, string> {
  const fn = (body: string) => `function f(a, b) {\n${body}\n}\n`;
  const nest = (open: string, inner: string, close: string) => rep(open, n) + inner + rep(close, n);
  return lazily({
    "deep-namespaces.ts": () => nest("namespace A { ", "", " }"),
    "deep-namespaces-declare.ts": () => "declare " + nest("namespace A { ", "const a: number;", " }"),
    "deep-self-assign-arrays.js": () => nest("[", "a", "]") + " = " + nest("[", "a", "]") + ";",
    "deep-self-assign-objects.js": () => "(" + nest("{a: ", "a", "}") + " = " + nest("{a: ", "a", "}") + ");",
    "deep-unused-cond.js": () => nest("a ? (", "b()", ") : c()") + ";",
    "deep-unused-patterns.js": () => "const " + nest("[", "a", "]") + " = b;",
    "deep-unused-patterns-objects.js": () => "const " + nest("{a: ", "b", "}") + " = c;",
    "deep-labels-unused.js": () => Array.from({ length: n }, (_, i) => `l${i}: `).join("") + "a();",
    "deep-finally-labels-jumps-in.js": () => "try {} finally {\n" + Array.from({ length: n }, (_, i) => `l${i}: `).join("") + "for (;;) {\n" + Array.from({ length: n }, (_, i) => `if (a) break l${i};\n`).join("") + "} }",
    "deep-finally-labels-jumps-out.js": () => Array.from({ length: n }, (_, i) => `l${i}: `).join("") + "for (;;) { try {} finally {\n" + Array.from({ length: n }, (_, i) => `if (a) break l${i};\n`).join("") + "} }",
    "deep-finally-blocks-return.js": () => "function f(a) { try {} finally { " + nest("{ if (a) return; ", "", " }") + " } }",
    "deep-labels-jumps.js": () => Array.from({ length: n }, (_, i) => `l${i}: `).join("") + "for (;;) {\n" + Array.from({ length: n }, (_, i) => `if (a) break l${i};\n`).join("") + "}",
    "deep-classes-private.js": () => nest("class A { #x; m() { this.#x; ", "", " } }"),
    "deep-ctor-loops.js": () => "class A extends B { constructor() { " + nest("while (a) { ", "this.b;", " }") + " super(); } }",
    "deep-shadow-fns.js": () => nest("function f(v) { ", "", " }"),
    "deep-blocks-shadow.js": () => nest("{ let v = 1; ", "", " }"),
    "deep-finally-returns.js": () => "function f(a) { " + nest("try {} finally { if (a) return; ", "", " }") + " }",
    "deep-assign-do-whiles.js": () => fn("let v = 0;\n" + nest("do { ", "if (a) v = 1; b(v); v = 2;", " } while (a);")),
    "deep-assign-whiles.js": () => fn("let v = 0;\n" + nest("while (a) { ", "if (a) v = 1; b(v); v = 2;", " }")),
    "deep-assign-ifs.js": () => fn("let v = 0;\n" + nest("if (a) { v = 1; ", "b(v);", " }") + "return v;"),
    "deep-assign-ifs-after.js": () => fn("let v = 0;\n" + nest("if (a) { ", "b(v);", " v = 1; }") + "return v;"),
    "deep-assign-blocks-reads.js": () => fn("let v = 0;\nif (a) v = 1;\n" + nest("{ b(v); ", "", " }")),
    "deep-assign-blocks-writes.js": () => fn("let v = 0;\n" + nest("{ if (a) v = 1; ", "", " }") + "return v;"),
    "deep-assign-labels.js": () => fn("let v = 0;\n" + Array.from({ length: n }, (_, i) => `l${i}: { `).join("") + Array.from({ length: n }, (_, i) => `if (a) break l${i}; v = ${i};\n`).join("") + rep("}", n) + "return v;"),
    "deep-assign-chain.js": () => fn("let v = 0;\n" + rep("v = ", n) + "1;\nreturn v;"),
    "deep-assign-patterns.js": () => fn("let v = 0;\n" + nest("[v, ", "v", "]") + " = b;\nreturn v;"),
    "deep-assign-pattern-defaults.js": () => fn("let v = 0, w;\n" + nest("[v, w = (", "v = 1", ")] = b") + ";\nreturn v;"),
    "deep-assign-tries.js": () => fn("let v = 0;\n" + nest("try { b(); } finally { if (a) v = 1; ", "", " }") + "return v;"),
  });
}
