// More shapes, for the rules that need types. In the form of shapes.ts.

const seq = (n: number, f: (i: number) => string, sep = "") => Array.from({ length: n }, (_, i) => f(i)).join(sep);
const rep = (text: string, n: number) => text.repeat(n);

/** A shape is made when it is asked for. */
function lazily(shapes: Record<string, () => string>): Record<string, string> {
  const made: Record<string, string> = {};
  for (const [name, make] of Object.entries(shapes)) Object.defineProperty(made, name, { get: make, enumerable: true });
  return made;
}

export function wide(n: number): Record<string, string> {
  const afn = (head: string, body: string) => `${head}\nasync function f() {\n${body}\n}\n`;
  const fn = (head: string, body: string) => `${head}\nfunction f() {\n${body}\n}\n`;
  return lazily({
    // promises
    "ty-awaits-promise.ts": () => afn("declare const p: Promise<number>;", rep("await p;\n", n)),
    "ty-awaits-number.ts": () => afn("declare const p: number;", rep("await p;\n", n)),
    "ty-floating.ts": () => afn("declare const p: Promise<number>;", rep("p;\n", n)),
    "ty-floating-calls.ts": () => afn("declare function g(): Promise<number>;", rep("g();\n", n)),
    "ty-floating-then.ts": () => afn("declare const p: Promise<number>;", "p" + rep(".then(() => 1)", n) + ";"),
    "ty-floating-then-stmts.ts": () => afn("declare const p: Promise<number>;", rep("p.then(() => 1);\n", n)),
    "ty-floating-catch.ts": () => afn("declare const p: Promise<number>;", "p" + rep(".catch(() => 1)", n) + ";"),
    "ty-floating-finally.ts": () => afn("declare const p: Promise<number>;", "p" + rep(".finally(() => {})", n) + ";"),
    "ty-floating-comma.ts": () => afn("declare const p: Promise<number>;", seq(n, () => "p", ", ") + ";"),
    "ty-floating-and.ts": () => afn("declare const p: Promise<number>; declare const b: boolean;", rep("b && ", n) + "p;"),
    "ty-floating-or.ts": () => afn("declare const p: Promise<number> | undefined;", seq(n, () => "p", " || ") + ";"),
    "ty-floating-nullish.ts": () => afn("declare const p: Promise<number> | undefined;", seq(n, () => "p", " ?? ") + ";"),
    "ty-floating-cond.ts": () => afn("declare const p: Promise<number>; declare const b: boolean;", rep("b ? p : ", n) + "p;"),
    "ty-floating-array.ts": () => afn("declare const p: Promise<number>;", "[" + seq(n, () => "p", ", ") + "];"),
    "ty-floating-void.ts": () => afn("declare const p: Promise<number>;", rep("void p;\n", n)),
    "ty-promise-all.ts": () => afn("declare const p: Promise<number>;", "await Promise.all([" + seq(n, () => "p", ", ") + "]);"),
    "ty-misused-if.ts": () => afn("declare const p: Promise<number>;", rep("if (p) {}\n", n)),
    "ty-misused-and.ts": () => afn("declare const p: Promise<number>;", "if (" + seq(n, () => "p", " && ") + ") {}"),
    "ty-misused-void-args.ts": () => fn("declare function g(cb: () => void): void;", rep("g(async () => {});\n", n)),
    "ty-misused-void-many-args.ts": () => fn(
      "declare function g(...cb: (() => void)[]): void;",
      "g(" + seq(n, () => "async () => {}", ", ") + ");",
    ),
    "ty-misused-void-props.ts": () =>
      "type O = {" + seq(n, i => `p${i}: () => void`, "; ") + "};\nconst o: O = {" + seq(n, i => `p${i}: async () => {}`, ", ") + "};",
    "ty-misused-void-methods.ts": () =>
      "type O = {" + seq(n, i => `p${i}(): void`, "; ") + "};\nconst o: O = {" + seq(n, i => `async p${i}() {}`, ", ") + "};",
    "ty-misused-spread.ts": () => afn("declare const p: Promise<{a: 1}>;", "const o = {" + rep("...p, ", n) + "};"),
    "ty-misused-inherited.ts": () =>
      "interface I {" + seq(n, i => `m${i}(): void`, "; ") + "}\nclass A implements I {\n" + seq(n, i => `async m${i}() {}\n`) + "}",
    "ty-misused-heritage.ts": () =>
      seq(n, i => `interface I${i} { m(): void }\n`) + "class A implements " + seq(n, i => `I${i}`, ", ") + " { async m() {} }",
    "ty-async-fns.ts": () => seq(n, i => `function f${i}() { return Promise.resolve(${i}); }\n`),
    "ty-async-returns.ts": () => fn(
      "declare const p: Promise<number>; declare const b: boolean;",
      rep("if (b) return p;\n", n) + "return p;",
    ),
    "ty-return-await.ts": () => afn("declare const p: Promise<number>; declare const b: boolean;", rep("if (b) return p;\n", n)),
    "ty-return-await-try.ts": () => afn(
      "declare const p: Promise<number>; declare const b: boolean;",
      "try {\n" + rep("if (b) return p;\n", n) + "} catch {}",
    ),
    "ty-return-await-tries.ts": () => afn("declare const p: Promise<number>;", rep("try { return p; } catch {}\n", n)),
    "ty-return-await-cond.ts": () => afn("declare const p: Promise<number>; declare const b: boolean;", "return " + rep("b ? p : ", n) + "p;"),
    "ty-return-await-comma.ts": () => afn("declare const p: Promise<number>;", "return (" + seq(n, () => "p", ", ") + ");"),
    "ty-return-await-or.ts": () => afn("declare const p: Promise<number> | undefined;", "return " + seq(n, () => "p", " ?? ") + ";"),
    "ty-require-await.ts": () => seq(n, i => `async function f${i}() { return ${i}; }\n`),
    "ty-require-await-returns.ts": () => afn("declare const b: boolean;", rep("if (b) return 1;\n", n)),
    "ty-require-await-gen.ts": () => "async function* f() {\n" + rep("yield 1;\n", n) + "}",
    "ty-require-await-yield-star.ts": () => "declare const g: AsyncGenerator<number>;\nasync function* f() {\n" + rep("yield* g;\n", n) + "}",
    "ty-reject.ts": () => fn("", rep("Promise.reject(1);\n", n)),
    "ty-reject-new.ts": () => fn("", "new Promise((_, reject) => {\n" + rep("reject(1);\n", n) + "});"),
    "ty-catch-callback.ts": () => fn("declare const p: Promise<number>;", rep("p.catch((e) => {});\n", n)),
    "ty-throws.ts": () => fn("declare const b: boolean;", rep("if (b) throw 1;\n", n)),
    "ty-for-await.ts": () => afn("declare const a: number[];", rep("for await (const x of a) {}\n", n)),
    "ty-await-using.ts": () => afn("declare const a: Disposable;", rep("{ await using x = a; }\n", n)),

    // switch
    "ty-switch-union.ts": () =>
      "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U;\nswitch (u) {\n" + seq(n, i => `case "s${i}": break;\n`) + "}",
    "ty-switch-union-half.ts": () =>
      "type U = " +
      seq(n, i => `"s${i}"`, " | ") +
      ";\ndeclare const u: U;\nswitch (u) {\n" +
      seq(n >> 1, i => `case "s${i}": break;\n`) +
      "}",
    "ty-switch-union-none.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U;\nswitch (u) {\n}",
    "ty-switch-union-default.ts": () =>
      "type U = " +
      seq(n, i => `"s${i}"`, " | ") +
      ";\ndeclare const u: U;\nswitch (u) {\n" +
      seq(n, i => `case "s${i}": break;\n`) +
      "default: break;\n}",
    "ty-switch-enum.ts": () =>
      "enum E {" + seq(n, i => `M${i}`, ", ") + "}\ndeclare const u: E;\nswitch (u) {\n" + seq(n, i => `case E.M${i}: break;\n`) + "}",
    "ty-switch-enum-half.ts": () =>
      "enum E {" + seq(n, i => `M${i}`, ", ") + "}\ndeclare const u: E;\nswitch (u) {\n" + seq(n >> 1, i => `case E.M${i}: break;\n`) + "}",
    "ty-switch-numbers.ts": () =>
      "type U = " + seq(n, i => `${i}`, " | ") + ";\ndeclare const u: U;\nswitch (u) {\n" + seq(n, i => `case ${i}: break;\n`) + "}",
    "ty-switch-string.ts": () => "declare const u: string;\nswitch (u) {\n" + seq(n, i => `case "s${i}": break;\n`) + "}",
    "ty-switch-true.ts": () => "declare const u: number;\nswitch (true) {\n" + seq(n, i => `case u === ${i}: break;\n`) + "}",
    "ty-switches.ts": () => 'declare const u: "a" | "b";\n' + rep('switch (u) { case "a": break; }\n', n),
    "ty-switch-discriminant.ts": () =>
      "type U = " +
      seq(n, i => `{k: "s${i}"; v${i}: 1}`, " | ") +
      ";\ndeclare const u: U;\nswitch (u.k) {\n" +
      seq(n, i => `case "s${i}": u.v${i}; break;\n`) +
      "}",

    // unions and intersections
    "ty-union-redundant-literals.ts": () => "type A = string | " + seq(n, i => `"s${i}"`, " | ") + ";",
    "ty-union-redundant-numbers.ts": () => "type A = number | " + seq(n, i => `${i}`, " | ") + ";",
    "ty-union-redundant-aliases.ts": () => seq(n, i => `type T${i} = "s${i}";\n`) + "type A = string | " + seq(n, i => `T${i}`, " | ") + ";",
    "ty-union-alias-unions.ts": () =>
      "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\n" + "type A = string | " + rep("U | ", 50) + "U;",
    "ty-union-alias-unions-stmts.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\n" + rep("type A = string | U;\n", n >> 4),
    "ty-union-declared.ts": () => seq(n, i => `interface T${i} { a${i}: 1 }\n`) + "type A = " + seq(n, i => `T${i}`, " | ") + ";",
    "ty-union-declared-same.ts": () => "interface B { a: 1 }\ntype A = " + rep("B | ", n) + "B;",
    "ty-union-same-structure.ts": () => "type A = " + rep("{a: 1} | ", n) + "{a: 1};",
    "ty-union-templates.ts": () => "type A = string | " + seq(n, i => "`a${number}b" + i + "`", " | ") + ";",
    "ty-intersection-declared.ts": () => seq(n, i => `interface T${i} { a${i}: 1 }\n`) + "type A = " + seq(n, i => `T${i}`, " & ") + ";",
    "ty-intersection-literals.ts": () => "type A = string & " + seq(n, i => `"s${i}"`, " & ") + ";",
    "ty-intersection-same-literal.ts": () => "type A = string & " + rep('"s" & ', n) + '"s";',
    "ty-union-param-undefined.ts": () => "function f(" + seq(n, i => `p${i}?: string | undefined`, ", ") + ") {}",
    "ty-union-nested-parens.ts": () => "type A = " + seq(n, i => `(T | "s${i}")`, " | ") + ";\ntype T = 1;",
    "ty-union-var-uses.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U;\n" + rep("if (u) {}\n", n >> 4),
    "ty-union-var-eq.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U, v: U;\n" + rep("if (u === v) {}\n", n >> 4),
    "ty-union-objects-access.ts": () =>
      "type U = " + seq(n, i => `{k: ${i}; v?: string}`, " | ") + ";\ndeclare const u: U;\n" + rep("u.v?.length;\n", n >> 4),
    "ty-union-template-uses.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U;\n" + rep("`${u}`;\n", n >> 4),
    "ty-union-plus-uses.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U;\n" + rep("u + u;\n", n >> 4),
    "ty-union-objects-tostring.ts": () =>
      seq(n, i => `interface T${i} { a${i}: 1 }\n`) +
      "type U = " +
      seq(n, i => `T${i}`, " | ") +
      ";\ndeclare const u: U;\n" +
      rep("`${u}`; u + ''; String(u); u.toString();\n", n >> 4),
    "ty-union-fns-call.ts": () =>
      "type U = " + seq(n, i => `((a: ${i}) => Promise<${i}>)`, " | ") + ";\ndeclare const u: U;\n" + rep("u;\n", n >> 4),
    "ty-union-promises.ts": () =>
      "type U = " + seq(n, i => `Promise<${i}>`, " | ") + ";\ndeclare const u: U;\nasync function f() {\n" + rep("u; await u;\n", n >> 4) + "}",

    // chains
    "ty-chain-and-grow.ts": () =>
      "type R = {b: R | null};\ndeclare const a: R | null;\n" + "a" + seq(Math.floor(Math.sqrt(n)), i => " && a" + rep(".b", i + 1)) + ";",
    "ty-chain-and-same.ts": () => "declare const a: {b: number} | null;\nconst x = " + seq(n, () => "a", " && ") + ";",
    "ty-chain-and-props.ts": () => "declare const a: {b: number | null} | null;\nconst x = " + seq(n, () => "a && a.b", " && ") + ";",
    "ty-chain-and-distinct.ts": () =>
      seq(n, i => `declare const a${i}: {b: number} | null;\n`) + "const x = " + seq(n, i => `a${i} && a${i}.b`, " && ") + ";",
    "ty-chain-and-neq-null.ts": () => "declare const a: {b: number | null} | null;\nconst x = " + seq(n, () => "a != null && a.b != null", " && ") + ";",
    "ty-chain-or-not.ts": () => "declare const a: {b: number | null} | null;\nconst x = " + seq(n, () => "!a || !a.b", " || ") + ";",
    "ty-chain-or.ts": () => "declare const a: string | null;\nconst x = " + seq(n, () => "a", " || ") + ";",
    "ty-chain-or-distinct.ts": () => seq(n, i => `declare const a${i}: string | null;\n`) + "const x = " + seq(n, i => `a${i}`, " || ") + ";",
    "ty-chain-nullish.ts": () => "declare const a: string | null;\nconst x = " + seq(n, () => "a", " ?? ") + ";",
    "ty-chain-nullish-nonnull.ts": () => "declare const a: string;\nconst x = " + seq(n, () => "a", " ?? ") + ";",
    "ty-chain-or-if.ts": () => "declare const a: string | null;\nif (" + seq(n, () => "a", " || ") + ") {}",
    "ty-chain-and-if.ts": () => "declare const a: string | null;\nif (" + seq(n, () => "a", " && ") + ") {}",
    "ty-chain-and-or-mixed.ts": () => "declare const a: string | null;\nconst x = " + seq(n, () => "a && a", " || ") + ";",
    "ty-chain-or-empty-object.ts": () => "declare const a: {b?: {c: 1}} | undefined;\n" + rep("(a || {}).b;\n", n),
    "ty-chain-or-empty-object-deep.ts": () => "type R = {b?: R};\ndeclare const a: R | undefined;\n" + rep("(", n) + "a" + rep(" || {}).b", n) + ";",
    "ty-chain-optional.ts": () => "type R = {b?: R};\ndeclare const a: R;\na" + rep("?.b", n) + ";",
    "ty-chain-optional-unneeded.ts": () => "type R = {b: R};\ndeclare const a: R;\na" + rep("?.b", n) + ";",
    "ty-chain-optional-calls.ts": () => "type R = {b?: () => R};\ndeclare const a: R;\na" + rep(".b?.()", n) + ";",
    "ty-chain-optional-index.ts": () => "type R = {[k: string]: R | undefined};\ndeclare const a: R;\na" + rep("?.['b']", n) + ";",
    "ty-chain-dots.ts": () => "type R = {b: R};\ndeclare const a: R;\na" + rep(".b", n) + ";",
    "ty-chain-dots-any.ts": () => "declare const a: any;\na" + rep(".b", n) + ";",
    "ty-chain-calls-any.ts": () => "declare const a: any;\na" + rep("()", n) + ";",
    "ty-chain-calls.ts": () => "type R = () => R;\ndeclare const a: R;\na" + rep("()", n) + ";",
    "ty-chain-method-calls.ts": () => "type R = {b(): R};\ndeclare const a: R;\na" + rep(".b()", n) + ";",
    "ty-chain-index-any.ts": () => "declare const a: any;\na" + rep("[0]", n) + ";",
    "ty-chain-index-string.ts": () => "type R = {b: R};\ndeclare const a: R;\na" + rep('["b"]', n) + ";",
    "ty-chain-non-null.ts": () => "type R = {b: R};\ndeclare const a: R;\na" + rep("!.b", n) + ";",
    "ty-chain-non-null-nullable.ts": () => "type R = {b: R | null};\ndeclare const a: R | null;\na" + rep("!.b", n) + ";",
    "ty-chain-as.ts": () => "declare const a: string;\nconst x = a" + rep(" as string", n) + ";",
    "ty-chain-ternary-nullish.ts": () => "declare const a: string | null;\nconst x = " + rep("a != null ? a : ", n) + "a;",
    "ty-chain-ternary-stmts.ts": () => "declare const a: string | null, b: string;\n" + rep("a != null ? a : b;\n", n),
    "ty-chain-not.ts": () => "declare const a: string | null;\nconst x = " + rep("!", n) + "a;",
    "ty-chain-eq-bool.ts": () => "declare const a: boolean;\nconst x = a" + rep(" === true", n) + ";",
    "ty-chain-assign-or.ts": () => "declare let a: string | null;\n" + rep("a = a || 'x';\n", n),
    "ty-chain-if-assign.ts": () => "declare let a: string | null;\n" + rep("if (!a) { a = 'x'; }\n", n),
    "ty-chain-logical-assign.ts": () => "declare let a: string | null;\n" + rep("a ||= 'x';\n", n),

    // strings
    "ty-plus-strings.ts": () => "declare const s: string;\nconst x = " + seq(n, () => "s", " + ") + ";",
    "ty-plus-mixed.ts": () => "declare const s: string, k: number;\nconst x = " + seq(n, () => "s + k", " + ") + ";",
    "ty-plus-numbers.ts": () => "declare const k: number;\nconst x = " + seq(n, () => "k", " + ") + ";",
    "ty-plus-objects.ts": () => "declare const s: string, o: {};\nconst x = s" + rep(" + o", n) + ";",
    "ty-plus-any.ts": () => "declare const s: any;\nconst x = " + seq(n, () => "s", " + ") + ";",
    "ty-plus-literals.ts": () => "const x = " + seq(n, i => `"s${i}"`, " + ") + ";",
    "ty-plus-assign.ts": () => "declare const o: {};\nlet x = '';\n" + rep("x += o;\n", n),
    "ty-template-strings.ts": () => "declare const s: string;\nconst x = `" + rep("${s}", n) + "`;",
    "ty-template-numbers.ts": () => "declare const s: number;\nconst x = `" + rep("${s} ", n) + "`;",
    "ty-template-objects.ts": () => "declare const s: {};\nconst x = `" + rep("${s} ", n) + "`;",
    "ty-template-literals.ts": () => "const x = `" + seq(n, i => "${'s" + i + "'}") + "`;",
    "ty-template-number-literals.ts": () => "const x = `" + seq(n, i => "${" + i + "} ") + "`;",
    "ty-template-stmts.ts": () => "declare const s: string;\n" + rep("`${s}`;\n", n),
    "ty-template-literal-lines.ts": () => "const x = `" + seq(n, i => "${'s" + i + "'}\n") + "`;",
    "ty-template-undefined.ts": () => "const x = `" + rep("${undefined}${null}", n) + "`;",
    "ty-tostring-calls.ts": () => "declare const o: {};\n" + rep("o.toString();\n", n),
    "ty-string-calls.ts": () => "declare const o: {};\n" + rep("String(o);\n", n),
    "ty-join-tuple.ts": () => "declare const o: [" + seq(n, () => "{}", ", ") + "];\no.join();",
    "ty-join-stmts.ts": () => "declare const o: {}[];\n" + rep("o.join();\n", n),
    "ty-conversion.ts": () => "declare const s: string, k: number, b: boolean;\n" + rep("String(s); s.toString(); '' + s; +k; !!b; ~~k; Number(k); Boolean(b);\n", n),
    "ty-starts-with.ts": () => "declare const s: string;\n" + rep("s[0] === 'a'; s.charAt(0) === 'a'; s.indexOf('a') === 0; s.slice(0, 1) === 'a'; /^a/.test(s); s.match(/a$/);\n", n),
    "ty-includes.ts": () => "declare const s: string, a: number[];\n" + rep("s.indexOf('a') !== -1; a.indexOf(1) >= 0; /a/.test(s);\n", n),
    "ty-regexp-exec.ts": () => "declare const s: string;\n" + rep("s.match(/a/);\n", n),
    "ty-regexp-exec-var.ts": () => "declare const s: string;\nconst r = /a/;\n" + rep("s.match(r);\n", n),

    // any
    "ty-any-members.ts": () => "declare const a: any;\n" + rep("a.b;\n", n),
    "ty-any-members-distinct.ts": () => "declare const a: any;\n" + seq(n, i => `a.p${i};\n`),
    "ty-any-calls.ts": () => "declare const a: any;\n" + rep("a();\n", n),
    "ty-any-new.ts": () => "declare const a: any;\n" + rep("new a();\n", n),
    "ty-any-tagged.ts": () => "declare const a: any;\n" + rep("a``;\n", n),
    "ty-any-args.ts": () => "declare const a: any;\ndeclare function g(x: string): void;\n" + rep("g(a);\n", n),
    "ty-any-many-args.ts": () => "declare const a: any;\ndeclare function g(...x: string[]): void;\ng(" + seq(n, () => "a", ", ") + ");",
    "ty-any-many-params.ts": () =>
      "declare const a: any;\ndeclare function g(" + seq(n, i => `p${i}: string`, ", ") + "): void;\ng(" + seq(n, () => "a", ", ") + ");",
    "ty-any-spread-args.ts": () => "declare const a: any[];\ndeclare function g(...x: string[]): void;\ng(" + seq(n, () => "...a", ", ") + ");",
    "ty-any-tuple-spread-args.ts": () =>
      "declare const a: [" + seq(n, () => "any", ", ") + "];\ndeclare function g(...x: string[]): void;\ng(...a);",
    "ty-any-assign.ts": () => "declare const a: any;\n" + seq(n, i => `const v${i} = a;\n`),
    "ty-any-assign-typed.ts": () => "declare const a: any;\n" + seq(n, i => `const v${i}: string = a;\n`),
    "ty-any-reassign.ts": () => "declare const a: any;\nlet v: string;\n" + rep("v = a;\n", n),
    "ty-any-destructure-object.ts": () => "declare const a: {" + seq(n, i => `p${i}: any`, "; ") + "};\nconst {" + seq(n, i => `p${i}`, ", ") + "} = a;",
    "ty-any-destructure-array.ts": () => "declare const a: [" + seq(n, () => "any", ", ") + "];\nconst [" + seq(n, i => `p${i}`, ", ") + "] = a;",
    "ty-any-destructure-any-array.ts": () => "declare const a: any[];\nconst [" + seq(n, i => `p${i}`, ", ") + "] = a;",
    "ty-any-destructure-stmts.ts": () => "declare const a: {p: any};\n" + rep("{ const {p} = a; }\n", n),
    "ty-any-object-props.ts": () => "declare const a: any;\nconst o: {" + seq(n, i => `p${i}: string`, "; ") + "} = {" + seq(n, i => `p${i}: a`, ", ") + "};",
    "ty-any-array-elems.ts": () => "declare const a: any;\nconst o: string[] = [" + seq(n, () => "a", ", ") + "];",
    "ty-any-array-spread.ts": () => "declare const a: any[];\nconst o: string[] = [" + seq(n, () => "...a", ", ") + "];",
    "ty-any-returns.ts": () => fn("declare const a: any; declare const b: boolean;", rep("if (b) return a;\n", n)),
    "ty-any-returns-typed.ts": () => "declare const a: any; declare const b: boolean;\nfunction f(): string {\n" + rep("if (b) return a;\n", n) + "return '';\n}",
    "ty-any-arrows.ts": () => "declare const a: any;\n" + seq(n, i => `const f${i} = () => a;\n`),
    "ty-any-as.ts": () => "declare const a: any;\n" + rep("a as string;\n", n),
    "ty-any-unary-minus.ts": () => "declare const a: any;\n" + rep("-a;\n", n),
    "ty-any-computed.ts": () => "declare const a: any; declare const o: Record<string, number>;\n" + rep("o[a];\n", n),
    "ty-any-class-props.ts": () => "declare const a: any;\nclass A {\n" + seq(n, i => `p${i} = a;\n`) + "}",
    "ty-any-defaults.ts": () => "declare const a: any;\nfunction f(" + seq(n, i => `p${i} = a`, ", ") + ") {}",
    "ty-any-generic-assign.ts": () => "declare const a: Set<any>;\n" + seq(n, i => `const v${i}: Set<string> = a;\n`),
    "ty-any-jsx.tsx": () => "declare const a: any;\ndeclare function C(p: Record<string, string>): null;\nconst x = <C " + seq(n, i => `p${i}={a}`, " ") + " />;",

    // overloads, generics
    "ty-overloads-calls.ts": () => seq(n, i => `declare function g(a: ${i}): ${i};\n`) + seq(n >> 4, i => `g(${n - 1 - i});\n`),
    "ty-overloads-promise.ts": () => seq(n, i => `declare function g(a: ${i}): Promise<${i}>;\n`) + "g;\n",
    "ty-overloads-impl-promise.ts": () => seq(n, i => `function g(a: ${i}): Promise<${i}>;\n`) + "function g(a: number): Promise<any> { return Promise.resolve(a); }",
    "ty-overloads-callback.ts": () => seq(n, i => `declare function g(a: ${i}, cb: () => void): void;\n`) + rep("g(0, async () => {});\n", n >> 4),
    "ty-type-args-default.ts": () => "type G<T = string> = T;\n" + rep("let a: G<string>;\n", n),
    // The declaration has n members, and its type parameters are looked for at each of n / 4 uses.
    "ty-type-args-default-big-interface.ts": () =>
      "interface G<T = string> {" + seq(n, i => `p${i}: T`, "; ") + "}\n" + rep("let a: G<string>;\n", n >> 2),
    "ty-type-args-default-big-class.ts": () =>
      "declare class G<T = string> {" + seq(n, i => `p${i}: T`, "; ") + "}\n" + rep("new G<string>();\n", n >> 2),
    // The statements of the shapes on which TS2563 fires (the body is too large for control flow analysis, and the rules see error
    // types), each in a function of its own.
    "tyf-cond-always.ts": () => 'declare const o: {};\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (o) {} }\n`),
    "tyf-cond-assert.ts": () => 'declare function assert(x: unknown): asserts x;\\ndeclare const s: string;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { assert(s); }\n`),
    "tyf-cond-bool-compare.ts": () => 'declare const b: boolean;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (b === true) {} }\n`),
    "tyf-cond-index-access.ts": () => 'declare const a: string[];\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (a[0]) {} a[0]?.length; }\n`),
    "tyf-cond-narrowing-nested-use.ts": () => 'declare let s: string | number | null;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (typeof s === 'string') { s.length; } }\n`),
    "tyf-cond-narrowing.ts": () => 'declare let s: string | null;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (s) { s; } }\n`),
    "tyf-cond-narrowing-reassign.ts": () => 'declare function g(): string | null;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { let s = g(); if (s) { s = g(); } return s; }\n`),
    "tyf-cond-strict-bool.ts": () => 'declare const s: string, k: number, o: {} | null, y: any;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { if (s) {} if (k) {} if (o) {} if (y) {} }\n`),
    "tyf-cond-while.ts": () => 'declare const o: {};\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { while (o) { break; } }\n`),
    "tyf-chain-if-assign.ts": () => 'declare function g(): string | null;\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { let a = g(); if (!a) { a = 'x'; } return a; }\n`),
    "tyf-misused-if.ts": () => 'declare const p: Promise<number>;\\n'.replace(/\\n/g, "\n") + seq(n, i => `async function f${i}() { if (p) {} }\n`),
    "tyf-plus-assign.ts": () => 'declare const o: {};\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { let x = ''; x += o; return x; }\n`),
    "tyf-switches.ts": () => 'declare const u: "a" | "b";\\n'.replace(/\\n/g, "\n") + seq(n, i => `function f${i}() { switch (u) { case "a": break; } }\n`),
    // Many returns in ONE function, without a chain of branches: one for each case of a switch.
    "tyf-any-returns.ts": () => 'declare const a: any, k: number;\\n'.replace(/\\n/g, "\n") + 'function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return a;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-any-returns-typed.ts": () => 'declare const a: any, k: number;\\n'.replace(/\\n/g, "\n") + 'function f(): string {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return a;\n`) + "}\\nreturn '';\\n}".replace(/\\n/g, "\n"),
    "tyf-async-returns.ts": () => 'declare const p: Promise<number>, k: number;\\n'.replace(/\\n/g, "\n") + 'function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return p;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-cond-void-return.ts": () => 'declare function v(): void; declare const k: number;\\n'.replace(/\\n/g, "\n") + 'function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return v();\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-consistent-return.ts": () => 'declare const k: number;\\n'.replace(/\\n/g, "\n") + 'function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return ${i % 2 ? "1" : ""};\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-class-return-this-returns.ts": () => 'declare const k: number;\\n'.replace(/\\n/g, "\n") + 'class A {\\nm(): A {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return this;\n`) + '}\\nreturn this;\\n}\\n}'.replace(/\\n/g, "\n"),
    "tyf-require-await-returns.ts": () => 'declare const k: number;\\n'.replace(/\\n/g, "\n") + 'async function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return 1;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-return-await.ts": () => 'declare const p: Promise<number>, k: number;\\n'.replace(/\\n/g, "\n") + 'async function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return p;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-return-await-try.ts": () => 'declare const p: Promise<number>, k: number;\\n'.replace(/\\n/g, "\n") + 'async function f() {\\ntry {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return p;\n`) + '}\\n} catch {}\\n}'.replace(/\\n/g, "\n"),
    "tyf-return-await-using.ts": () => 'declare const p: Promise<number>, k: number, d: Disposable;\\n'.replace(/\\n/g, "\n") + 'async function f() {\\nusing x = d;\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return p;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "tyf-strict-void-return-returns.ts": () => 'declare function g(cb: () => void): void; declare const k: number;\\n'.replace(/\\n/g, "\n") + 'g(() => {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: return 1;\n`) + '}\\n});'.replace(/\\n/g, "\n"),
    "tyf-throws.ts": () => 'declare const k: number;\\n'.replace(/\\n/g, "\n") + 'function f() {\\n'.replace(/\\n/g, "\n") + "switch (k) {\n" + seq(n, i => `case ${i}: throw 1;\n`) + '}\\n}'.replace(/\\n/g, "\n"),
    "ty-type-args-default-calls.ts": () => "declare function g<T = string>(): T;\n" + rep("g<string>();\n", n),
    "ty-type-args-many.ts": () =>
      "type G<" + seq(n, i => `T${i} = string`, ", ") + "> = 1;\nlet a: G<" + seq(n, () => "string", ", ") + ">;",
    "ty-type-args-many-uses.ts": () =>
      "type G<" + seq(n >> 4, i => `T${i} = string`, ", ") + "> = 1;\n" + rep("let a: G<" + seq(n >> 4, () => "string", ", ") + ">;\n", 16),
    "ty-type-args-inferred.ts": () => "declare function g<T>(a: T): T;\n" + rep("g<string>('a');\n", n),
    "ty-type-params-once.ts": () => seq(n, i => `function f${i}<T>(a: T) {}\n`),
    "ty-type-params-many.ts": () => "function f<" + seq(n, i => `T${i}`, ", ") + ">(" + seq(n, i => `p${i}: T${i}`, ", ") + ") {}",
    "ty-type-params-many-twice.ts": () => "function f<" + seq(n, i => `T${i}`, ", ") + ">(" + seq(n, i => `p${i}: T${i}, q${i}: T${i}`, ", ") + ") {}",
    "ty-type-params-many-return.ts": () =>
      "function f<" + seq(n, i => `T${i}`, ", ") + ">(" + seq(n, i => `p${i}: T${i}`, ", ") + "): [" + seq(n, i => `T${i}`, ", ") + "] { return null!; }",
    "ty-type-params-inferred-return.ts": () =>
      "function f<" + seq(n, i => `T${i}`, ", ") + ">(" + seq(n, i => `p${i}: T${i}`, ", ") + ") { return [" + seq(n, i => `p${i}`, ", ") + "] as const; }",
    "ty-type-params-class.ts": () => "class A<" + seq(n, i => `T${i}`, ", ") + "> {\n" + seq(n, i => `p${i}!: T${i};\n`) + "}",
    "ty-type-params-class-methods.ts": () => "class A {\n" + seq(n, i => `m${i}<T>(a: T) {}\n`) + "}",
    "ty-type-params-big-param.ts": () => "function f<T>(a: {" + seq(n, i => `p${i}: T`, "; ") + "}) {}",
    "ty-type-params-big-type-fns.ts": () => "type Big = {" + seq(n, i => `p${i}: string`, "; ") + "};\n" + seq(n >> 4, i => `function f${i}<T>(a: T, b: Big) {}\n`),
    "ty-reduce.ts": () => "declare const a: number[];\n" + rep("a.reduce((x, y) => x, [] as number[]);\n", n),
    "ty-sort.ts": () => "declare const a: number[];\n" + rep("a.sort();\n", n),
    "ty-find.ts": () => "declare const a: number[];\n" + rep("a.filter(x => x)[0];\n", n),
    "ty-find-cond.ts": () => "declare const a: number[]; declare const b: boolean;\n(" + rep("b ? a.filter(x => x) : ", n) + "a.filter(x => x))[0];",
    "ty-find-comma.ts": () => "declare const a: number[];\n(" + rep("a, ", n) + "a.filter(x => x))[0];",
    "ty-array-delete.ts": () => "declare const a: number[];\n" + rep("delete a[0];\n", n),
    "ty-for-in-array.ts": () => "declare const a: number[];\n" + rep("for (const k in a) {}\n", n),
    "ty-for-of-index.ts": () => "declare const a: number[];\n" + rep("for (let i = 0; i < a.length; i++) { a[i]; }\n", n),
    "ty-implied-eval.ts": () => rep("setTimeout('a', 1);\n", n),
    "ty-implied-eval-bind.ts": () => "declare const g: () => void;\nsetTimeout(g" + rep(".bind(null)", n) + ", 1);",
    "ty-spread-strings.ts": () => "declare const s: string;\nconst x = [" + rep("...s, ", n) + "];",
    "ty-spread-objects.ts": () => "declare const s: number[]; class C { m() {} }\ndeclare const c: C;\nconst x = {" + rep("...s, ...c, ", n) + "};",
    "ty-spread-union.ts": () => "declare const s: " + seq(n, i => `{a${i}: 1}`, " | ") + ";\n" + rep("({...s});\n", n >> 4),

    // classes
    "ty-class-private-props.ts": () => "class A {\n" + seq(n, i => `private p${i} = ${i};\n`) + "}",
    "ty-class-private-props-read.ts": () => "class A {\n" + seq(n, i => `private p${i} = ${i};\n`) + "m() {\n" + seq(n, i => `this.p${i};\n`) + "}\n}",
    "ty-class-private-props-written.ts": () => "class A {\n" + seq(n, i => `private p${i} = ${i};\n`) + "m() {\n" + seq(n, i => `this.p${i} = 1;\n`) + "}\n}",
    "ty-class-private-props-ctor.ts": () => "class A {\n" + seq(n, i => `private p${i}: number;\n`) + "constructor() {\n" + seq(n, i => `this.p${i} = 1;\n`) + "}\n}",
    "ty-class-private-one-many-writes.ts": () => "class A {\nprivate p = 1;\nm() {\n" + rep("this.p = 1;\n", n) + "}\n}",
    "ty-class-hash-props.ts": () => "class A {\n" + seq(n, i => `#p${i} = ${i};\n`) + "}",
    "ty-class-param-props.ts": () => "class A { constructor(" + seq(n, i => `private p${i}: number`, ", ") + ") {} }",
    "ty-class-private-destructure.ts": () => "class A {\n" + seq(n, i => `private p${i} = ${i};\n`) + "m() {\n({" + seq(n, i => `p${i}: this.p${i}`, ", ") + "} = {} as any);\n}\n}",
    "ty-classes-private.ts": () => seq(n, i => `class A${i} { private p = 1; }\n`),
    "ty-class-unbound.ts": () => "class A {\n" + seq(n, i => `m${i}() {}\n`) + "}\ndeclare const a: A;\n" + seq(n, i => `const v${i} = a.m${i};\n`),
    "ty-class-unbound-one.ts": () => "class A { m() {} }\ndeclare const a: A;\n" + rep("a.m;\n", n),
    "ty-class-unbound-destructure.ts": () => "class A {\n" + seq(n, i => `m${i}() {}\n`) + "}\ndeclare const a: A;\nconst {" + seq(n, i => `m${i}`, ", ") + "} = a;",
    "ty-class-unbound-overloads.ts": () => "declare class A {\n" + seq(n, i => `m(a: ${i}): void;\n`) + "}\ndeclare const a: A;\n" + rep("a.m;\n", n >> 4),
    "ty-class-unbound-union.ts": () => seq(n, i => `declare class A${i} { m(): void }\n`) + "declare const a: " + seq(n, i => `A${i}`, " | ") + ";\n" + rep("a.m;\n", n >> 4),
    "ty-class-unbound-and.ts": () => "class A { m() {} }\ndeclare const a: A;\nconst x = " + seq(n, () => "a.m", " && ") + ";",
    "ty-class-getters-setters.ts": () => "class A {\n" + seq(n, i => `get p${i}(): string { return ''; }\nset p${i}(v: number) {}\n`) + "}",
    "ty-interface-getters-setters.ts": () => "interface A {\n" + seq(n, i => `get p${i}(): string;\nset p${i}(v: number);\n`) + "}",
    "ty-class-return-this.ts": () => "class A {\n" + seq(n, i => `m${i}(): A { return this; }\n`) + "}",
    "ty-class-return-this-returns.ts": () => "declare const b: boolean;\nclass A {\nm(): A {\n" + rep("if (b) return this;\n", n) + "return this;\n}\n}",
    "ty-class-return-this-union.ts": () => "class A {\nm(): " + seq(n, i => `T${i}`, " | ") + " | A { return this; }\n}",
    "ty-class-extends-chain.ts": () => "class A0 { m() {} private p = 1; }\n" + seq(n, i => `class A${i + 1} extends A${i} { m() {} }\n`),
    "ty-class-extends-chain-async.ts": () => "class A0 { m(): void {} }\n" + seq(n, i => `class A${i + 1} extends A${i} { async m() {} }\n`),
    "ty-interface-extends-chain.ts": () => "interface A0 { m(): void }\n" + seq(n, i => `interface A${i + 1} extends A${i} {}\n`) + `declare const a: A${n};\na.m;\n\`\${a}\`;`,
    "ty-class-merge.ts": () => seq(n, i => `class A${i} {}\ninterface A${i} {}\n`),
    "ty-deprecated-uses.ts": () => "/** @deprecated */ declare const d: number;\n" + rep("d;\n", n),
    "ty-deprecated-members.ts": () => "declare const o: {" + seq(n, i => `/** @deprecated */ p${i}: 1`, "; ") + "};\n" + seq(n, i => `o.p${i};\n`),
    "ty-deprecated-overloads.ts": () => seq(n, i => `/** @deprecated */ declare function g(a: ${i}): void;\n`) + "declare function g(a: string): void;\n" + rep("g(0);\n", n >> 4),
    "ty-deprecated-destructure.ts": () => "declare const o: {" + seq(n, i => `/** @deprecated */ p${i}: 1`, "; ") + "};\nconst {" + seq(n, i => `p${i}`, ", ") + "} = o;",
    "ty-deprecated-props.ts": () => "type O = {" + seq(n, i => `/** @deprecated */ p${i}?: 1`, "; ") + "};\nconst o: O = {" + seq(n, i => `p${i}: 1`, ", ") + "};",
    "ty-deprecated-not.ts": () => "declare const o: {" + seq(n, i => `p${i}: 1`, "; ") + "};\n" + seq(n, i => `o.p${i};\n`),
    "ty-deprecated-imports-exports.ts": () => seq(n, i => `/** @deprecated */ const v${i} = 1;\n`) + "export {" + seq(n, i => `v${i}`, ", ") + "};",
    "ty-deprecated-jsdoc-tags.ts": () => "/**\n" + rep(" * @param a b\n", n) + " * @deprecated\n */\ndeclare function d(): void;\n" + rep("d();\n", n >> 4),
    "ty-deprecated-merged.ts": () => rep("/** @deprecated */ interface D { a: 1 }\n", n) + rep("let x: D;\n", n >> 4),

    // readonly, wide types
    "ty-readonly-params.ts": () => "function f(" + seq(n, i => `p${i}: string[]`, ", ") + ") {}",
    "ty-readonly-params-fns.ts": () => seq(n, i => `function f${i}(p: string[]) {}\n`),
    "ty-readonly-wide-object.ts": () => "type O = {" + seq(n, i => `readonly p${i}: string`, "; ") + "};\n" + seq(n >> 4, i => `function f${i}(p: O) {}\n`),
    "ty-readonly-wide-object-of-objects.ts": () => "type O = {" + seq(n, i => `readonly p${i}: {readonly a: string}`, "; ") + "};\nfunction f(p: O) {}",
    "ty-readonly-wide-union.ts": () => "type O = " + seq(n, i => `{readonly p${i}: string}`, " | ") + ";\n" + seq(n >> 4, i => `function f${i}(p: O) {}\n`),
    "ty-readonly-wide-intersection.ts": () => "type O = " + seq(n, i => `{readonly p${i}: string}`, " & ") + ";\nfunction f(p: O) {}",
    "ty-readonly-wide-tuple.ts": () => "type O = readonly [" + seq(n, () => "string", ", ") + "];\nfunction f(p: O) {}",
    "ty-readonly-cyclic.ts": () => seq(n, i => `interface T${i} { readonly next: T${(i + 1) % n}; readonly other: T${(i * 7 + 3) % n} }\n`) + "function f(p: T0) {}",
    "ty-readonly-cyclic-fns.ts": () => seq(n, i => `interface T${i} { readonly next: T${(i + 1) % n} }\nfunction f${i}(p: T${i}) {}\n`),
    "ty-readonly-methods.ts": () => "interface O {" + seq(n, i => `m${i}(): void`, "; ") + "}\nfunction f(p: O) {}",

    // destructuring, defaults
    "ty-destructure-defaults.ts": () => "declare const o: {" + seq(n, i => `p${i}: string`, "; ") + "};\nconst {" + seq(n, i => `p${i} = ''`, ", ") + "} = o;",
    "ty-destructure-defaults-optional.ts": () => "declare const o: {" + seq(n, i => `p${i}?: string`, "; ") + "};\nconst {" + seq(n, i => `p${i} = undefined`, ", ") + "} = o;",
    "ty-destructure-defaults-array.ts": () => "declare const o: [" + seq(n, () => "string", ", ") + "];\nconst [" + seq(n, i => `p${i} = ''`, ", ") + "] = o;",
    "ty-destructure-defaults-params.ts": () => "function f({" + seq(n, i => `p${i} = ''`, ", ") + "}: {" + seq(n, i => `p${i}: string`, "; ") + "}) {}",
    "ty-destructure-defaults-union.ts": () => "declare const o: " + seq(n, i => `{p: string; k: ${i}}`, " | ") + ";\n" + rep("{ const {p = ''} = o; }\n", n >> 4),
    "ty-destructure-prefer.ts": () => "declare const o: {a: number}; declare const r: number[];\n" + rep("{ const a = o.a; const b = r[0]; }\n", n),
    "ty-params-default-undefined.ts": () => "function f(" + seq(n, i => `p${i}: string | undefined = undefined`, ", ") + ") {}",
    "ty-callback-params-default.ts": () => "declare function g(cb: (" + seq(n, i => `p${i}: string`, ", ") + ") => void): void;\ng((" + seq(n, i => `p${i} = ''`, ", ") + ") => {});",

    // enums
    "ty-enum-compare.ts": () => "enum E { A, B }\ndeclare const e: E;\n" + rep("e === 0;\n", n),
    "ty-enum-compare-big.ts": () => "enum E {" + seq(n, i => `M${i}`, ", ") + "}\ndeclare const e: E;\n" + rep("e === 0; e === E.M0;\n", n >> 4),
    "ty-enum-compare-strings.ts": () => "enum E {" + seq(n, i => `M${i} = "s${i}"`, ", ") + "}\ndeclare const e: E;\n" + rep("e === 's0';\n", n >> 4),
    "ty-enum-compare-two-big.ts": () =>
      "enum E {" + seq(n, i => `M${i}`, ", ") + "}\nenum F {" + seq(n, i => `M${i}`, ", ") + "}\ndeclare const e: E, f: F;\n" + rep("e === (f as number);\n", n >> 4),
    "ty-enum-switch-literal.ts": () => "enum E {" + seq(n, i => `M${i}`, ", ") + "}\ndeclare const e: E;\nswitch (e) {\n" + seq(n, i => `case ${i}: break;\n`) + "}",
    "ty-enum-assign.ts": () => "enum E { A, B }\nlet e: E;\n" + rep("e = 0;\n", n),
    "ty-enum-assign-big.ts": () => "enum E {" + seq(n, i => `M${i}`, ", ") + "}\nlet e: E;\n" + rep("e = 0;\n", n >> 4),
    "ty-enum-args.ts": () => "enum E { A, B }\ndeclare function g(...e: E[]): void;\ng(" + seq(n, () => "0", ", ") + ");",
    "ty-enum-bitwise.ts": () => "enum E { A = 1, B = 2 }\nconst e: E = " + seq(n, () => "E.A", " | ") + ";",
    "ty-enum-object-props.ts": () => "enum E { A, B }\nconst o: {" + seq(n, i => `p${i}: E`, "; ") + "} = {" + seq(n, i => `p${i}: 0`, ", ") + "};",
    "ty-enum-mixed.ts": () => "enum E {" + seq(n, i => (i % 2 ? `M${i} = "s"` : `M${i} = 1`), ", ") + "}",
    "ty-enum-mixed-merged.ts": () => seq(n, i => `enum E { M${i} = ${i % 2 ? '"s"' : 1} }\n`),
    "ty-enum-mixed-refs.ts": () => "enum E {M0 = 1, " + seq(n, i => `M${i + 1} = M${i}`, ", ") + "}",
    "ty-enum-qualifier.ts": () => "enum E {M0 = 1, " + seq(n, i => `M${i + 1} = E.M${i}`, ", ") + "}",
    "ty-namespace-qualifier.ts": () => "namespace N {\nexport const a = 1;\n" + rep("N.a;\n", n) + "}",
    "ty-namespace-qualifier-members.ts": () => "namespace N {\n" + seq(n, i => `export const a${i} = 1;\n`) + seq(n, i => `N.a${i};\n`) + "}",
    "ty-namespace-qualifier-types.ts": () => "namespace N {\n" + seq(n, i => `export type T${i} = 1;\n`) + seq(n, i => `let v${i}: N.T${i};\n`) + "}",

    // conditions
    "ty-cond-always.ts": () => "declare const o: {};\n" + rep("if (o) {}\n", n),
    "ty-cond-literal-compare.ts": () => rep("if (1 === 1) {}\n", n),
    "ty-cond-bool-compare.ts": () => "declare const b: boolean;\n" + rep("if (b === true) {}\n", n),
    "ty-cond-narrowing.ts": () => "declare let s: string | null;\n" + rep("if (s) { s; }\n", n),
    "ty-cond-narrowing-reassign.ts": () => "declare function g(): string | null;\nlet s = g();\n" + rep("if (s) { s = g(); }\n", n),
    "ty-cond-narrowing-nested-use.ts": () => "declare let s: string | number | null;\n" + rep("if (typeof s === 'string') { s.length; }\n", n),
    "ty-cond-while.ts": () => "declare const o: {};\n" + rep("while (o) { break; }\n", n),
    "ty-cond-predicates.ts": () => "declare const a: {}[];\n" + rep("a.filter(x => x);\n", n),
    "ty-cond-strict-bool.ts": () => "declare const s: string, k: number, o: {} | null, y: any;\n" + rep("if (s) {} if (k) {} if (o) {} if (y) {}\n", n),
    "ty-cond-strict-bool-not.ts": () => "declare const s: string;\n" + rep("!s;\n", n),
    "ty-cond-assert.ts": () => "declare function assert(x: unknown): asserts x;\ndeclare const s: string;\n" + rep("assert(s);\n", n),
    "ty-cond-index-access.ts": () => "declare const a: string[];\n" + rep("if (a[0]) {}\na[0]?.length;\n", n),
    "ty-cond-void.ts": () => "declare function v(): void;\n" + rep("const x = v();\n() => v();\n", n).replace(/const x/g, "var x"),
    "ty-cond-void-return.ts": () => fn("declare function v(): void; declare const b: boolean;", rep("if (b) return v();\n", n)),
    "ty-cond-void-op.ts": () => "declare function v(): void;\n" + rep("void v();\n", n),
    "ty-strict-void-return.ts": () => "declare function g(cb: () => void): void;\n" + rep("g(() => 1);\n", n),
    "ty-strict-void-return-returns.ts": () => "declare function g(cb: () => void): void; declare const b: boolean;\ng(() => {\n" + rep("if (b) return 1;\n", n) + "});",
    "ty-strict-void-return-props.ts": () => "type O = {" + seq(n, i => `p${i}: () => void`, "; ") + "};\nconst o: O = {" + seq(n, i => `p${i}: () => 1`, ", ") + "};",
    "ty-strict-void-return-class.ts": () => "interface I {" + seq(n, i => `m${i}(): void`, "; ") + "}\nclass A implements I {\n" + seq(n, i => `m${i}() { return 1; }\n`) + "}",
    "ty-consistent-return.ts": () => fn("declare const b: boolean;", rep("if (b) return 1;\nif (b) return;\n", n)),
    "ty-consistent-return-fns.ts": () => "declare const b: boolean;\n" + seq(n, i => `function f${i}() { if (b) return 1; }\n`),

    // assertions
    "ty-assert-unneeded.ts": () => "declare const s: string;\n" + rep("s as string; s!; <string>s;\n", n),
    "ty-assert-non-null-style.ts": () => "declare const s: string | null;\n" + rep("s as string;\n", n),
    "ty-assert-literal.ts": () => rep("const x = 'a' as 'a';\n", n).replace(/const x/g, "var x"),
    "ty-assert-unsafe.ts": () => "declare const s: string | number;\n" + rep("s as string;\n", n),
    "ty-assert-big-union.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const u: U | null, s: string;\n" + rep("u as U; u!; s as U;\n", n >> 4),
    "ty-assert-big-object.ts": () => "type O = {" + seq(n, i => `p${i}: string`, "; ") + "};\ndeclare const u: O | null, s: {};\n" + rep("u as O; u!; s as O;\n", n >> 4),
    "ty-assert-let-uses.ts": () => "let s: string | undefined;\n" + rep("s!;\n", n),
    "ty-assert-object-props.ts": () => "const o = {" + seq(n, i => `p${i}: 'a' as const`, ", ") + "};",
    "ty-assert-tuple.ts": () => "const o = [" + seq(n, () => "1 as number", ", ") + "];",

    // exports, names
    "ty-export-types.ts": () => seq(n, i => `type T${i} = 1;\n`) + "export {" + seq(n, i => `T${i}`, ", ") + "};",
    "ty-export-types-mixed.ts": () => seq(n, i => `type T${i} = 1;\nconst v${i} = 1;\n`) + "export {" + seq(n, i => `T${i}, v${i}`, ", ") + "};",
    "ty-export-types-stmts.ts": () => seq(n, i => `type T${i} = 1;\nexport {T${i}};\n`),
    "ty-dot-notation.ts": () => "declare const o: {a: number};\n" + rep("o['a'];\n", n),
    "ty-dot-notation-index.ts": () => "declare const o: Record<string, number>;\n" + seq(n, i => `o['p${i}'];\n`),
    "ty-dot-notation-private.ts": () => "class A {\n" + seq(n, i => `private p${i} = 1;\n`) + "}\ndeclare const a: A;\n" + seq(n, i => `a['p${i}'];\n`),
    "ty-naming-vars.ts": () => seq(n, i => `const my_var${i} = () => ${i};\nconst B${i} = [${i}];\nlet c_${i} = "s";\n`),
    "ty-naming-members.ts": () => "class A {\n" + seq(n, i => `my_prop${i} = () => 1;\nOther${i}: string[] = [];\n`) + "}",
    "ty-naming-params.ts": () => "function f(" + seq(n, i => `my_p${i}: boolean`, ", ") + ") {}",
    "ty-empty-object-type.ts": () => rep("declare function g<T>(a: T): T & {};\nconst x = g(1);\n", n).replace(/const x/g, "var x"),
    "ty-unused-vars.ts": () => seq(n, i => `const v${i} = ${i};\ntype T${i} = 1;\n`),
    "ty-typedef.ts": () => seq(n, i => `const v${i} = ${i};\nconst f${i} = (a) => a;\n`),
    // added after reading the rules
    "ty-chain-and-long-members.ts": () => "type R = {b: R | null};\ndeclare const a: R;\nconst x = a" + rep(".b!", n) + " && a" + rep(".b!", n) + ".b;",
    "ty-chain-and-long-dots.ts": () => "type R = {b: R};\ndeclare const a: R;\nconst x = a" + rep(".b", n) + " && a" + rep(".b", n) + ".b;",
    "ty-chain-and-long-calls.ts": () => "type R = () => R;\ndeclare const a: R;\nconst x = a" + rep("()", n) + " && a" + rep("()", n) + "();",
    "ty-class-unbound-or.ts": () => "class A { m() {} }\ndeclare const a: A;\nconst x = " + seq(n, () => "a.m", " || ") + ";",
    "ty-class-unbound-nullish.ts": () => "class A { m() {} }\ndeclare const a: A;\nconst x = " + seq(n, () => "a.m", " ?? ") + ";",
    "ty-nullish-props.ts": () => "declare const o: {" + seq(n, i => `p${i}: string`, "; ") + "};\n" + seq(n, i => `o.p${i} ?? 1;\n`),
    "ty-misused-void-many-params.ts": () =>
      "declare function g(" + seq(n, i => `p${i}: () => void`, ", ") + "): void;\ng(" + seq(n, () => "async () => {}", ", ") + ");",
    "ty-type-params-class-extends.ts": () =>
      "declare class B<" + seq(n, i => `T${i}`, ", ") + "> {}\nclass A<" + seq(n, i => `T${i}`, ", ") + "> extends B<" + seq(n, i => `T${i}`, ", ") + "> {}",
    "ty-destructure-defaults-cond.ts": () =>
      "declare const c: boolean;\nconst {" + seq(n, i => `p${i} = 1`, ", ") + "} = c ? {" + seq(n, i => `p${i}: 1`, ", ") + "} : {" + seq(n >> 1, i => `p${i}: 1`, ", ") + "};",
    "ty-destructure-defaults-nested-arrays.ts": () =>
      "declare const o: [" + seq(n, () => "[string]", ", ") + "];\nconst [" + seq(n, i => `[p${i} = '']`, ", ") + "] = o;",
    "ty-assert-args.ts": () => "declare function g(...a: string[]): void;\ndeclare const s: string | number;\ng(" + seq(n, () => "s as string", ", ") + ");",
    "ty-assert-args-method.ts": () => "declare const o: {g(...a: string[]): void};\ndeclare const s: string | number;\no.g(" + seq(n, () => "s as string", ", ") + ");",
    "ty-assert-args-overloaded.ts": () =>
      "declare function g(...a: string[]): void;\ndeclare function g(...a: number[]): void;\ndeclare const s: string | number;\ng(" + seq(n, () => "s as string", ", ") + ");",
    "ty-chain-as-alternating.ts": () => "declare const a: string;\nconst x = a" + rep(" as unknown as string", n) + ";",
    "ty-chain-or-cond-mixed.ts": () => "declare const a: string | null;\nconst x = " + seq(n, () => "(a && a)", " || ") + ";",
    "ty-chain-or-promises-mixed.ts": () => "declare const p: Promise<number> | null;\nconst x = " + seq(n, () => "(p && p)", " || ") + ";",
    "ty-await-plus.ts": () => "declare const p: Promise<number>;\nasync function f() {\nreturn " + seq(n, () => "await p", " + ") + ";\n}",
    "ty-namespace-qualifier-long.ts": () => "namespace N {\nexport const a: any = 1;\nN.a" + rep(".a", n) + ";\n}",
    "ty-union-objects-distinct.ts": () => "type A = " + seq(n, i => `{a: ${i}}`, " | ") + ";",
    "ty-union-fns-distinct.ts": () => "type A = " + seq(n, i => `((a: ${i}) => void)`, " | ") + ";",
    "ty-intersection-primitive-literals.ts": () => "type A = " + rep('string & "s" & ', n) + "string;",
    "ty-predicate-big-union.ts": () => "type U = " + seq(n, i => `"s${i}"`, " | ") + ";\ndeclare const a: U[];\n" + rep("a.filter(x => x);\n", 16),
    "ty-heritage-wide.ts": () => seq(n, i => `interface I${i} { m${i}(): void }\n`) + "interface A extends " + seq(n, i => `I${i}`, ", ") + " {}\ndeclare const a: A;\n`${a}`; a.m0; async function f() { a; await a; }",
    "ty-tuple-sets.ts": () => "declare const a: [" + seq(n, i => `Set<"s${i}">`, ", ") + "];\nconst b: [" + seq(n, i => `Set<"s${i}">`, ", ") + "] = a;",
    "ty-return-await-using.ts": () => afn("declare const p: Promise<number>; declare const b: boolean; declare const d: Disposable;", "using x = d;\n" + rep("if (b) return p;\n", n)),
  });
}

export function deep(n: number): Record<string, string> {
  const nest = (open: string, middle: string, close: string) => rep(open, n) + middle + rep(close, n);
  return lazily({
    "tyd-object-type.ts": () => "type O = " + nest("{readonly a: ", "string", "}") + ";\nfunction f(p: O) {}\ndeclare const o: O; `${o}`;",
    "tyd-array-type.ts": () => "type O = " + nest("readonly (", "string", ")[]") + ";\nfunction f(p: O) {}\ndeclare const o: O; `${o}`; o.join();",
    "tyd-array-suffix.ts": () => "type O = string" + rep("[]", n) + ";\nfunction f(p: O) {}\ndeclare const o: O; `${o}`; o.join();",
    "tyd-array-generic.ts": () => "type O = " + nest("ReadonlyArray<", "string", ">") + ";\nfunction f(p: O) {}\ndeclare const o: O; `${o}`; o.join();",
    "tyd-tuple-type.ts": () => "type O = " + nest("readonly [", "string", "]") + ";\nfunction f(p: O) {}\ndeclare const o: O; `${o}`; o.join();",
    "tyd-promise-type.ts": () => "type O = " + nest("Promise<", "string", ">") + ";\ndeclare const o: O;\nasync function f() { o; await o; return o; }",
    "tyd-set-any.ts": () => "declare const a: " + nest("Set<", "any", ">") + ";\nconst b: " + nest("Set<", "string", ">") + " = a;\nfunction f(): " + nest("Set<", "string", ">") + " { return a; }",
    "tyd-array-any.ts": () => "declare const a: " + nest("Array<", "any", ">") + ";\nconst b: " + nest("Array<", "string", ">") + " = a;",
    "tyd-alias-chain-objects.ts": () => "type T0 = {readonly a: string};\n" + seq(n, i => `type T${i + 1} = {readonly a: T${i}};\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`;`,
    "tyd-alias-chain-arrays.ts": () => "type T0 = string;\n" + seq(n, i => `type T${i + 1} = readonly T${i}[];\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; o.join();`,
    "tyd-alias-chain-tuples.ts": () => "type T0 = {};\n" + seq(n, i => `type T${i + 1} = readonly [T${i}];\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; o.join();`,
    "tyd-alias-chain-unions.ts": () => "type T0 = 'a';\n" + seq(n, i => `type T${i + 1} = T${i} | 's${i}';\n`) + `type A = string | T${n};\ndeclare const o: T${n}; \`\${o}\`; if (o) {}`,
    "tyd-alias-chain-sets-any.ts": () => "type T0 = any; type U0 = string;\n" + seq(n, i => `type T${i + 1} = Set<T${i}>; type U${i + 1} = Set<U${i}>;\n`) + `declare const a: T${n};\nconst b: U${n} = a;`,
    "tyd-alias-chain-promises.ts": () => "type T0 = string;\n" + seq(n, i => `type T${i + 1} = Promise<T${i}>;\n`) + `declare const o: T${n};\nasync function f() { o; await o; return o; }`,
    "tyd-alias-chain-generic-constraint.ts": () => seq(n, i => `function f${i}<T${i} extends ${i ? `T${i - 1}` : "string"}>(a: T${i}, b: T${i}) {\n`) + `if (a) {} \`\${a}\`; a + a;` + rep("}", n),
    "tyd-type-param-constraints.ts": () => "function f<T0 extends string | null, " + seq(n, i => `T${i + 1} extends T${i}`, ", ") + `>(a: T${n}, b: T${n}) { if (a) {} \`\${a}\`; a ?? 1; a as string; a!; }`,
    "tyd-interface-chain-cyclic.ts": () => seq(n, i => `interface T${i} { readonly next: T${(i + 1) % n} }\n`) + "function f(p: T0) {}\ndeclare const o: T0; `${o}`;",
    "tyd-object-literal-any.ts": () => "declare const a: any;\nconst o: " + nest("{a: ", "string", "}") + " = " + nest("{a: ", "a", "}") + ";",
    "tyd-array-literal-any.ts": () => "declare const a: any;\nconst o = " + nest("[", "a", "]") + ";",
    "tyd-destructure-object.ts": () => "declare const a: " + nest("{a: ", "any", "}") + ";\nconst " + nest("{a: ", "b = 1", "}") + " = a;",
    "tyd-destructure-array.ts": () => "declare const a: " + nest("[", "any", "]") + ";\nconst " + nest("[", "b = 1", "]") + " = a;",
    "tyd-destructure-assign.ts": () => "declare const a: " + nest("{a: ", "any", "}") + ";\nlet b;\n(" + nest("{a: ", "b", "}") + " = a);",
    "tyd-awaits.ts": () => "declare const p: Promise<number>;\nasync function f() { " + rep("await ", n) + "p; }",
    "tyd-voids.ts": () => "declare const p: Promise<number>;\n" + rep("void ", n) + "p;",
    "tyd-parens-and.ts": () => "declare const a: {b: number} | null;\nconst x = " + nest("(a && ", "a", ")") + ";",
    "tyd-right-and.ts": () => "declare const a: {b: number} | null;\nconst x = " + nest("a && (", "a", ")") + ";",
    "tyd-right-or.ts": () => "declare const a: string | null;\nconst x = " + nest("a || (", "a", ")") + ";",
    "tyd-right-nullish.ts": () => "declare const a: string | null;\nconst x = " + nest("a ?? (", "a", ")") + ";",
    "tyd-right-plus.ts": () => "declare const a: string, o: {};\nconst x = " + nest("a + (o + ", "a", ")") + ";",
    "tyd-templates.ts": () => "declare const a: string;\nconst x = " + nest("`${", "a", "}`") + ";",
    "tyd-templates-literal.ts": () => "const x = " + nest("`${", "'a'", "}`") + ";",
    "tyd-cond-yes.ts": () => "declare const b: boolean, p: Promise<number>;\nasync function f() { return " + rep("b ? ", n) + "p" + rep(" : p", n) + "; }",
    "tyd-calls-args.ts": () => "declare function g<T>(a: T): T;\ndeclare const a: any;\n" + nest("g(", "a", ")") + ";",
    "tyd-calls-promise-args.ts": () => "declare function g<T>(a: T): Promise<T>;\n" + nest("g(", "1", ")") + ";",
    "tyd-arrows.ts": () => "declare const p: Promise<number>;\nconst f = " + rep("() => ", n) + "p;",
    "tyd-async-arrows.ts": () => "declare const p: Promise<number>;\nconst f = " + rep("async () => ", n) + "p;",
    "tyd-fns-return.ts": () => "declare const a: any;\n" + nest("function f() { return ", "a", "; }"),
    "tyd-callbacks-void.ts": () => "declare function g(cb: () => void): void;\n" + nest("g(async () => { ", "", " });"),
    "tyd-tries.ts": () => "declare const p: Promise<number>;\nasync function f() { " + nest("try { ", "return p;", " } catch {}") + " }",
    "tyd-tries-finally.ts": () => "declare const p: Promise<number>;\nasync function f() { " + nest("try {} finally { ", "return p;", " }") + " }",
    "tyd-ifs-narrow.ts": () => "declare const s: string | null;\n" + nest("if (s) { ", "s;", " }"),
    "tyd-ifs-narrow-let.ts": () => "declare function g(): string | null;\nlet s = g();\n" + nest("if (s) { ", "s;", " }"),
    "tyd-switches.ts": () => "declare const u: 'a' | 'b';\n" + nest("switch (u) { case 'a': ", "", " }"),
    "tyd-classes.ts": () => nest("class A { private p = 1; m() { ", "", " } }"),
    "tyd-class-exprs.ts": () => "const x = " + nest("class { private p = 1; q = ", "1", " }") + ";",
    "tyd-namespaces-qualifier.ts": () => seq(n, i => `namespace N${i} { export const a = 1;\n`) + seq(n, i => `N${i}.a;\n`) + "N0" + seq(n - 1, i => `.N${i + 1}`) + ";" + rep("}", n),
    "tyd-namespaces-export-qualifier.ts": () => seq(n, i => `${i ? "export " : ""}namespace N${i} { export const a = 1;\n`) + "N0" + seq(n - 1, i => `.N${i + 1}`) + ".a;" + rep("}", n),
    "tyd-unions-parens.ts": () => "type A = " + nest("string | ('a' | ", "'b'", ")") + ";",
    "tyd-intersections-parens.ts": () => "type A = " + nest("{a: 1} & ({a: 1} & ", "{b: 1}", ")") + ";",
    "tyd-generic-fns.ts": () => nest("function f<T>(a: T) { ", "", " }"),
    "tyd-generic-fn-types.ts": () => "type A = " + nest("<T>(a: T) => ", "void", "") + ";",
    "tyd-generic-type-in-param.ts": () => "function f<T>(a: " + nest("Array<", "T", ">") + ") {}",
    "tyd-generic-object-in-param.ts": () => "function f<T>(a: " + nest("{a: ", "T", "}") + ") {}",
    "tyd-generic-alias-chain-param.ts": () => "type G0<T> = T;\n" + seq(n, i => `type G${i + 1}<T> = {a: G${i}<T>};\n`) + `function f<T>(a: G${n}<T>) {}`,
    "tyd-spread-objects.ts": () => "declare const s: number[];\nconst x = " + nest("{...", "s", "}") + ";",
    "tyd-enum-generic.ts": () => "enum E { A }\ndeclare const a: " + nest("Set<", "number", ">") + ";\nconst b: " + nest("Set<", "E", ">") + " = a as any;\nlet c: " + nest("Array<", "E", ">") + " = " + nest("[", "0", "]") + ";",
    "tyd-not-parens.ts": () => "declare const a: string | null;\nconst x = " + nest("!(", "a", ")") + ";",
    "tyd-as-parens.ts": () => "declare const a: string;\nconst x = " + nest("(", "a", " as string)") + ";",
    "tyd-non-null-parens.ts": () => "declare const a: string;\nconst x = " + nest("(", "a", ")!") + ";",
    "tyd-filter-cond.ts": () => "declare const a: number[]; declare const b: boolean;\n(" + rep("b ? ", n) + "a.filter(x => x)" + rep(" : a.filter(x => x)", n) + ")[0];",
    "tyd-bind.ts": () => "declare const g: () => void;\nsetTimeout(" + nest("(", "g", ").bind(null)") + ", 1);",
    "tyd-dag-tuples-never.ts": () => "type T0 = {};\n" + seq(n, i => `type T${i + 1} = readonly [T${i}, T${i}];\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; o.join();`,
    "tyd-dag-tuples-sometimes.ts": () => "type T0 = {} | string;\n" + seq(n, i => `type T${i + 1} = readonly [T${i}, T${i}];\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; o.join();`,
    "tyd-dag-tuples-always.ts": () => "type T0 = string;\n" + seq(n, i => `type T${i + 1} = readonly [T${i}, T${i}];\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; o.join();`,
    "tyd-dag-objects.ts": () => "type T0 = {readonly x: string};\n" + seq(n, i => `type T${i + 1} = {readonly a: T${i}; readonly b: T${i}};\n`) + `function f(p: T${n}) {}\ndeclare const o: T${n}; \`\${o}\`; function g<T>(a: T, b: T${n}) {}`,
    "tyd-dag-maps-any.ts": () => "type T0 = any; type U0 = string;\n" + seq(n, i => `type T${i + 1} = Map<T${i}, T${i}>; type U${i + 1} = Map<U${i}, U${i}>;\n`) + `declare const a: T${n};\nconst b: U${n} = a;\na as U${n};`,
    "tyd-dag-maps-safe.ts": () => "type T0 = string;\n" + seq(n, i => `type T${i + 1} = Map<T${i}, T${i}>;\n`) + `declare const a: T${n};\nconst b: T${n} = a;\na as T${n}; function f(): T${n} { return a; }`,
    "tyd-dag-generic-tuples.ts": () => "type G0<T> = T;\n" + seq(n, i => `type G${i + 1}<T> = [G${i}<T>, G${i}<T>];\n`) + `function f<T>(a: G${n}<T>) {}`,
    "tyd-dag-interfaces-diamond.ts": () => "interface T0 { m(): void }\n" + seq(n, i => `interface A${i} extends T${i} {}\ninterface B${i} extends T${i} {}\ninterface T${i + 1} extends A${i}, B${i} {}\n`) + `declare const o: T${n};\n\`\${o}\`; o; o.m; throw o; async function f() { await o; return o; }`,
    "tyd-dag-classes-promise.ts": () => "interface T0 extends Promise<number> {}\n" + seq(n, i => `interface A${i} extends T${i} {}\ninterface B${i} extends T${i} {}\ninterface T${i + 1} extends A${i}, B${i} {}\n`) + `declare const o: T${n};\no; async function f() { await o; return o; }`,
    "tyd-dag-fn-types.ts": () => "type T0 = string;\n" + seq(n, i => `type T${i + 1} = (a: T${i}) => T${i};\n`) + `declare const a: T${n};\na as T${n}; a as unknown as T${n}; function f<T>(x: T, y: T${n}) {}`,
    "tyd-array-suffix-union.ts": () => "type A = B" + rep("[]", n) + " | B " + rep("[]", n) + ";\ntype B = 1;",
    // base types and type arguments that lead back to where they came from: n copies
    "tyd-cycle-classes-generic.ts": () => seq(n, i => `interface T${i}<A> extends X${i}<A[]>, Promise<A> {}\ninterface X${i}<A> extends Z${i}, Y${i}<T${i}<A>> {}\ninterface Y${i}<A> { y: A }\ninterface Z${i} {}\ndeclare const u${i}: T${i}<number> | X${i}<string>, x${i}: X${i}<string>;\nu${i}; x${i};\n`),
    "tyd-cycle-tuples-readonly.ts": () => seq(n, i => `type T${i} = readonly [T${i}, U${i}];\ntype U${i} = readonly [T${i}, readonly string[]];\nfunction f${i}(p: T${i}, q: U${i}) {}\n`),
    "tyd-cycle-tuples-mutable.ts": () => seq(n, i => `type T${i} = readonly [T${i}, U${i}];\ntype U${i} = readonly [T${i}, string[]];\ntype V${i} = readonly [readonly [V${i}], U${i}];\nfunction f${i}(p: T${i}, q: U${i}, r: V${i}) {}\n`),
    "tyd-cycle-arrays-readonly.ts": () => seq(n, i => `interface N${i} { readonly kids: readonly N${i}[]; readonly pair: readonly [N${i}, M${i}] }\ninterface M${i} { readonly back: N${i}; items: readonly N${i}[] }\ninterface K${i} { readonly kids: ReadonlyArray<K${i}>; readonly pair: readonly [K${i}, K${i}] }\nfunction f${i}(p: N${i}, q: M${i}, r: K${i}) {}\n`),
    "tyd-cycle-tuples-tostring.ts": () => seq(n, i => `type T${i} = [T${i}, U${i}];\ntype U${i} = [T${i}, {}];\ntype V${i} = [V${i}, W${i}];\ntype W${i} = [V${i}, string];\ntype S${i} = [S${i}, R${i}, R${i}];\ntype R${i} = [S${i}, {} | string];\ndeclare const t${i}: T${i}, u${i}: U${i}, v${i}: V${i}, w${i}: W${i}, s${i}: S${i}, r${i}: R${i};\n\`\${t${i}}\${u${i}}\${v${i}}\${w${i}}\${s${i}}\${r${i}}\`; t${i}.join(); u${i}.join(); v${i}.join(); s${i}.join(); r${i}.join(); String(r${i}); '' + s${i};\n`),
  });
}
