// More shapes, for the rules of ESLint from new-parens to no-mixed-spaces-and-tabs. In the form of shapes.ts.
const seq = (n: number, f: (i: number) => string, sep = "") => Array.from({ length: n }, (_, i) => f(i)).join(sep);
const rep = (text: string, n: number) => text.repeat(n);

/** A shape is made when it is asked for. */
function lazily(shapes: Record<string, () => string>): Record<string, string> {
  const made: Record<string, string> = {};
  for (const [name, make] of Object.entries(shapes)) Object.defineProperty(made, name, { get: make, enumerable: true });
  return made;
}

export function wide(n: number): Record<string, string> {
  const fn = (body: string) => `function f(a, b) {\n${body}\n}\n`;
  return lazily({
    "await-binary-loop.js": () => `async function f() { for (;;) { x = ${rep("await a + ", n)}a; } }`,
    "await-binary.js": () => `async function f() { for (;;) {} x = ${rep("await a + ", n)}a; }`,
    "await-sequence.js": () => `async function f() { for (;;) {} ${rep("await a, ", n)}a; }`,
    "await-else-if.js": () => `async function f() { for (;;) {} ${rep("if (a) { await a; } else ", n)}{} }`,
    "assign-sequence-test.js": () => `if ((${rep("a = 1, ", n)}a)) {}`,
    "assign-sequence.js": () => `${rep("a = 1, ", n)}a;`,
    "assign-or.js": () => `x = ${rep("(a = 1) || ", n)}a;`,
    "this-binary.js": () => fn(`return ${rep("this.a + ", n)}1;`),
    "this-binary-top.js": () => `x = ${rep("this.a + ", n)}1;`,
    "this-binary-method.js": () => `class A { m() { return ${rep("this.a + ", n)}1; } }`,
    "this-params.js": () => `function f(${seq(n, i => `p${i}`, ", ")}) {\n${rep("this.a;\n", n)}}`,
    "this-or-function.js": () => `x = ${rep("a || ", n)}function () {\n${rep("this.a;\n", n)}};`,
    "this-else-if.js": () => fn(rep("if (a) { this.a; } else ", n) + "{}"),
    "this-eval-binary.js": () => fn(`return ${rep("this.eval + ", n)}1;`),
    "boolean-cast-or.js": () => `if (${rep("!!a || ", n)}a) {}`,
    "boolean-cast-call-or.js": () => `if (${rep("Boolean(a) || ", n)}a) {}`,
    "boolean-cast-sequence.js": () => `${rep("!!a, ", n)}a;`,
    "boolean-cast-sequence-test.js": () => `if ((${rep("!!a, ", n)}a)) {}`,
    "labels-else-if.js": () => `A: for (;;) { ${rep("if (a) { break A; } else ", n)}{} }`,
    "labels-else-if-block.js": () => `A: { for (;;) { ${rep("if (a) { break A; } else ", n)}{} } }`,
    "labels-breaks.js": () => `A: for (;;) {\n${rep("break A;\n", n)}}`,
    "labels-loops.js": () => rep("A: for (;;) { break A; }\n", n),
    "inner-else-if.js": () => rep("if (a) { var v; function g() {} } else ", n) + "{}",
    "inner-else-if-fn.js": () => fn(rep("if (a) { var v; function g() {} } else ", n) + "{}"),
    "iterator-dots.js": () => `a${rep(".__iterator__", n)};`,
    "iterator-dots.jsx": () => `a${rep(".__iterator__", n)};\n<a />;`,
    "caller-dots.js": () => `arguments${rep(".callee", n)};`,
    "catch-vars.js": () => seq(n, i => `var v${i};\n`) + rep("try {} catch (e) {}\n", n),
    "catch-else-if.js": () => fn(rep("if (a) { try {} catch (e) {} } else ", n) + "{}"),
    "catch-binary-fn.js": () => `x = ${rep("a + ", n)}function () {\n${rep("try {} catch (e) {}\n", n)}};`,
    "exported-comment.js": () => `/* exported ${seq(n, i => `v${i}`, ", ")} */\n` + seq(n, i => `var v${i};\n`),
    "cases-spaced.js": () => `switch (a) {\n${seq(n, i => `case a . b${i}:\n`)}}`,
    "cases-comments.js": () => `switch (a) {\n${seq(n, i => `case a /* c */ + ${i}:\n`)}}`,
    "cases-same.js": () => `switch (a) {\n${rep("case a . b:\n", n)}}`,
    "cases-calls.js": () => `switch (a) {\n${seq(n, i => `case f(${i}):\n`)}}`,
    "settimeout-concat.js": () => `setTimeout(${rep("a + ", n)}a);`,
    "settimeout-concat-right.js": () => `setTimeout(${rep("a + (", Math.min(n, 3000))}a${rep(")", Math.min(n, 3000))});`,
    "returns-comments.js": () => fn(`a(); ${rep("/* c */ ", n)}return;`),
    "returns-comment-lines.js": () => fn(`a();\n${rep("// c\n", n)}return;`),
    "var-comment-lines.js": () => rep("var a; // c\n// c\n// c\nf(); // c\n", n),
    "var-comment-lines-blank.js": () => rep("var a;\n\n// c\nf();\n", n),
    "flags-invalid-then-valid.js": () => `new RegExp("a", "${rep("q", n)}${rep("g", n)}");`,
    "imports-mixed-same.js": () => seq(n, i => `import * as a${i} from "m";\nimport { b as b${i} } from "m";\n`),
    "exports-same.js": () => seq(n, i => `export { b as b${i} } from "m";\n`),
    "class-members-computed.js": () => `class A {\n${seq(n, i => `["m${i}"]() {}\n`)}}`,
    "class-members-same.js": () => `class A {\n${rep("m() {}\n", n)}}`,
    "params-same.js": () => `function f(${rep("a, ", n)}a) {}`,
    "params-pairs.js": () => `function f(${seq(n, i => `p${i}, p${i}`, ", ")}) {}`,
    "else-if-and.js": () => fn(seq(n, i => `if (a === 1 && b === ${i}) { b(); }`, " else ")),
    "else-if-and3.js": () => fn(seq(n, i => `if (a && b${i} && c${i % 7}) { b(); }`, " else ")),
    "else-if-grid.js": () => fn(seq(n, i => `if (a === ${i % Math.ceil(Math.sqrt(n))} && b === ${Math.floor(i / Math.ceil(Math.sqrt(n)))}) { b(); }`, " else ")),
    "else-if-spaced.js": () => fn(seq(n, i => `if (a . b === ${i}) { b(); }`, " else ")),
    "else-if-dupes.js": () => fn(seq(n, i => `if (a === ${i % 100}) { b(); }`, " else ")),
    "else-if-one-big-or.js": () => fn(`if (${seq(n, i => `a === ${i}`, " || ")}) {} else if (${seq(n, i => `a === ${n - i}`, " || ")}) {}`),
    "else-if-one-big-and.js": () => fn(`if (${seq(n, i => `a${i}`, " && ")}) {} else if (${seq(n, i => `a${n - 1 - i}`, " && ")}) {}`),
    "else-if-paren-or-and.js": () => fn(`if ((${seq(n, i => `a${i}`, " || ")}) && b) {} else if ((${seq(n, i => `a${i}`, " || ")}) && b) {}`),
    "parens-binary.js": () => `for (;;) {}\nx = ${rep("(a) + ", n)}a;`,
    "parens-binary-no-for.js": () => `x = ${rep("(a) + ", n)}a;`,
    "parens-sequence.js": () => `for (a;;) {}\n${rep("(a), ", n)}a;`,
    "parens-for-init-in.js": () => `for (x = ${rep("(a in b) + ", n)}a;;) {}`,
    "parens-for-init.js": () => `for (x = ${rep("(a) + ", n)}a;;) {}`,
    "parens-for-inits.js": () => rep("for (x = (a in b);;) {}\n", n),
    "parens-for-inits-plain.js": () => rep("for (x = (a);;) {}\n", n),
    "parens-assign-sequence.js": () => fn(`return ${rep("a = (b), ", n)}a;`),
    "parens-assign-sequence-stmt.js": () => `${rep("a = (b), ", n)}a;`,
    "parens-member-chain.js": () => `(a)${rep(".b", n)};\nnew (a${rep(".b", n)})();`,
    "loop-func-binary.js": () => `for (var i = 0; ; i++) { x = ${rep("function () { return i; } + ", n)}1; }`,
    "loop-func-binary-outside.js": () => `for (;;) {}\nx = ${rep("function () { return i; } + ", n)}1;`,
    "loop-func-else-if.js": () => `for (var i = 0; ; i++) { ${rep("if (a) { (() => i); } else ", n)}{} }`,
    "loop-func-many-vars.js": () => `${seq(n, i => `var v${i} = 1;\n`)}for (;;) { (function () {\n${seq(n, i => `v${i};\n`)}});\n${seq(n, i => `v${i} = 2;\n`)}}`,
    "loop-func-globals.js": () => `for (;;) {\n${rep("(() => g);\n", n)}g = 1;\n}`,
    "loop-func-let-outside.js": () => `let v = 1;\n${rep("for (;;) { (() => v); }\n", n)}v = 2;`,
    "regex-literals-and-ctor.js": () => rep('new RegExp(/[👍]/, "u");\n/[👍]/;\n', n),
    "regex-literal-surrogates.js": () => `x = /[${rep("👍", n)}]/;`,
    "regex-literal-classes.js": () => `x = /${rep("[👍]", n)}/;`,
    "regex-ctor-classes.js": () => `x = new RegExp("${rep("[👍]", n)}");`,
    "regex-ctor-template-surrogates.js": () => "x = new RegExp(`[" + rep("👍", n) + "]`);",
    "regex-ctor-combining.js": () => `x = new RegExp("[${rep("Á", n)}]");`,
    "regex-ctor-zwj.js": () => `x = new RegExp("[${rep("👨‍👩‍👦", n)}]", "u");`,
    "lone-blocks-in-block.js": () => `{\n${rep("{}\n", n)}}`,
    "lonely-ifs-in-else.js": () => `if (a) {} else {\n${rep("if (b) {}\n", n)}}`,
    "dupe-keys-same.js": () => `x = { ${rep("a: 1, ", n)} };`,
    "dupe-keys-in-arrays.js": () => `x = ${rep("[", Math.min(n, 3000))}{ ${rep("a: 1, ", n)} }${rep("]", Math.min(n, 3000))};`,
    "dupe-keys-nested-target.js": () => `({ ${rep("a: 1, ", n)} });`,
    "func-assign-redeclared.js": () => rep("function f() {}\n", n) + "f = 1;",
    "semi-strings.js": () => rep('a;;"s";\n', n),
    "class-semis.js": () => `class A { a() {}${rep(";", n)} }`,
    "coercion-concat.js": () => `x = a${rep(' + ""', n)};`,
    "array-ctor-nested-scopes.js": () => rep("Array(1, 2);\n", n),
    "mixed-requires.js": () => `var ${seq(n, i => `a${i} = require("m${i}")`, ", ")};`,
    "mixed-requires-chain.js": () => `var a = require("m")${rep(".b", n)}, c = require("./d")${rep("()", Math.min(n, 20000))};`,
    "else-return-blocks.js": () => fn(rep("if (a) { return 1; } else { let c = 1; b(c); }\n", n)),
    "else-return-vars.js": () => fn(seq(n, i => `var v${i};\n`) + rep("if (a) { return 1; } else { let c = 1; b(c); }\n", n)),
    "case-declarations.js": () => `switch (a) { case 1:\n${seq(n, i => `let v${i};\n`)}}`,
    "import-assign-members.js": () => `import * as ns from "m";\nx = ${rep("ns.a + ", n)}1;\n${rep("ns.a = 1;\n", n)}`,
    "global-assign.js": () => rep("Object = 1;\n", n),
    "irregular-whitespace.js": () => rep("a;\u00a0\n", n),
    "irregular-whitespace-strings.js": () => rep("'\u00a0';\n", n),
  });
}

export function deep(n: number): Record<string, string> {
  const nest = (pre: string, mid: string, post: string) => rep(pre, n) + mid + rep(post, n);
  return lazily({
    "deep-labels-distinct-breaks.js": () => seq(n, i => `L${i}: `) + "{\n" + seq(n, i => `break L${i};\n`) + "}",
    "deep-labels-loops-continue.js": () => seq(n, i => `L${i}: for (;;) `) + "{\n" + seq(n, i => `continue L${i};\n`) + "}",
    "deep-labels-blocks-break-outer.js": () => "A: for (;;) " + seq(n, i => `L${i}: { `) + rep("break A;\n", n) + rep("}", n),
    "deep-awaits-loop.js": () => `async function f() { for (;;) { ${rep("await ", n)}a; } }`,
    "deep-assigns-test.js": () => `if ((${rep("a = ", n)}1)) {}`,
    "deep-parens-fn-members.js": () => rep("(", n) + "function () {}" + rep(").a", n) + ";",
    "deep-parens-members.js": () => rep("(", n) + "a" + rep(").a", n) + ";",
    "deep-parens-new-members.js": () => "new " + rep("(", n) + "a()" + rep(").a", n) + ";",
    "deep-for-init-fns.js": () => nest("for (x = function () { ", "", " };;) {}"),
    "deep-for-init-fns-parens.js": () => nest("for (x = (function () { ", "(a in b);", " });;) {}"),
    "deep-for-init-static.js": () => nest("for (x = (class { static { ", "(a in b);", " } });;) {}"),
    "deep-fors-closures-write-before.js": () => "var v = 1;\n" + nest("for (;;) { (() => v); ", "", "}"),
    "deep-fors-closures-let-before.js": () => "let v = 1; v = 2;\n" + nest("for (;;) { (() => v); ", "", "}"),
    "deep-fors-closures-write-after.js": () => "var v = 1;\n" + nest("for (;;) { (() => v); ", "", "}") + "\nv = 2;",
    "deep-iife-loops.js": () => "for (var i;;) {" + nest("(function () { ", "(() => i);", " })();") + "}",
    "deep-named-iife-loops.js": () => "for (var i;;) {" + nest("(function g() { ", "(() => i);", " })();") + "}",
    "deep-catch-same.js": () => nest("try {} catch (e) { ", "", "}"),
    "deep-catch-distinct.js": () => seq(n, i => `try {} catch (e${i}) { `) + rep("}", n),
    "deep-array-ctor.js": () => nest("Array(1, ", "2", ")") + ";",
    "deep-array-ctor-fns.js": () => nest("function f() { Array(1, 2); ", "", "}"),
    "deep-confusing-arrows.js": () => "x = " + rep("a => b ? c : ", n) + "d;",
    "deep-boolean-not-not.js": () => `if (${rep("!!", n)}a) {}`,
    "deep-bind.js": () => nest("(function () { ", "", " }.bind(a));"),
    "deep-bind-arrows-this.js": () => "(function () { " + nest("(() => { ", "this;", " });") + " }.bind(a));",
    "deep-dupe-keys-objects.js": () => "x = " + nest("{ a: 1, a: ", "1", " }") + ";",
    "deep-empty-pattern-targets.js": () => nest("[", "{}", "]") + " = a;",
    "deep-else-return.js": () => `function f() { ${nest("if (a) { return 1; } else { ", "", " }")} }`,
    "deep-lonely-if-else.js": () => nest("if (a) {} else { ", "if (a) {}", " }"),
    "deep-this-arrows.js": () => `function f() { ${rep("() => ", n)}this; }`,
    "deep-this-blocks.js": () => `function f() { ${nest("{ this.a; ", "", "}")} }`,
    "deep-inner-blocks.js": () => nest("{ var v; function g() {} ", "", "}"),
    "deep-regex-groups.js": () => `x = /${nest("(", "[👍]", ")")}/;`,
    "deep-regex-ctor-groups.js": () => `x = new RegExp("${nest("(", "[👍]", ")")}");`,
    "deep-regex-class-sets.js": () => `x = /${nest("[", "a", "]")}/v;`,
    "deep-logical-else-if.js": () => `if (${nest("(a || ", "b", ") && c")}) {} else if (${nest("(a || ", "b", ") && c")}) {}`,
    "deep-logical-else-if-swapped.js": () => `if (${nest("(a || ", "b", ") && c")}) {} else if (${nest("c && (", "b", " || a)")}) {}`,
    "deep-settimeout-right.js": () => `setTimeout(${nest("a + (", "a", ")")});`,
    "deep-pat-params-dupe.js": () => `function f(${nest("[", "a", "]")}, a) {}`,
    "deep-const-pat.js": () => `const ${nest("[", "a", "]")} = b; a = 1;`,
  });
}
