// More shapes, for the rules of ESLint from no-useless-backreference to yoda. In the form of shapes.ts.
const seq = (n: number, f: (i: number) => string, sep = "") => Array.from({ length: n }, (_, i) => f(i)).join(sep);
const rep = (text: string, n: number) => text.repeat(n);

/** A shape is made when it is asked for. */
function lazily(shapes: Record<string, () => string>): Record<string, string> {
  const made: Record<string, string> = {};
  for (const [name, make] of Object.entries(shapes)) Object.defineProperty(made, name, { get: make, enumerable: true });
  return made;
}

export function wide(n: number): Record<string, string> {
  const fn = (body: string) => `function f(a, b) {\n${body}\n}\n`;
  return lazily({
    // prefer-const
    "const-same-declarators.js": () => "let " + rep("v = 1, ", n) + "v = 1;",
    "const-same-destructure.js": () => "let " + rep("{v} = a, ", n) + "{v} = a;",
    "const-same-noinit-reads.js": () => "let " + rep("v, ", n) + "v = 1;\n" + rep("v;\n", n),
    "const-assign-patterns.js": () => seq(n, i => `let v${i};\n`) + seq(n, i => `[v${i}] = a;\n`),
    "const-assign-patterns-fn.js": () => fn(seq(n, i => `let v${i};\n`) + seq(n, i => `({v${i}} = a);\n`)),
    "const-assign-pattern-wide.js": () => "let " + seq(n, i => `v${i}`, ", ") + ";\n[" + seq(n, i => `v${i}`, ", ") + "] = a;",
    "const-assign-pattern-member.js": () => "let " + seq(n, i => `v${i}`, ", ") + ";\n[" + seq(n, i => `v${i}`, ", ") + ", a.b] = a;",
    "const-assign-pattern-outer.js": () => "let o;\n" + fn(seq(n, i => `let v${i};\n`) + seq(n, i => `[v${i}, o] = a;\n`)),
    "const-assign-pattern-shadow.js": () => seq(n, i => `let v${i} = 1;\n`) + "{\n" + seq(n, i => `let v${i};\n`) + seq(n, i => `[v${i}] = a;\n`) + "}",
    "const-destructure-let.js": () => "let {" + seq(n, i => `v${i}`, ", ") + "} = a;",
    "const-destructure-array-let.js": () => "let [" + seq(n, i => `v${i}`, ", ") + "] = a;",
    "const-read-before.js": () => seq(n, i => `let v${i};\n`) + seq(n, i => `f(v${i}); v${i} = 1;\n`),
    // prefer-template
    "template-one-string.js": () => 'x = "a"' + rep(" + b", n) + ";",
    "template-one-string-last.js": () => "x = b" + rep(" + b", n) + ' + "a";',
    "template-comments.js": () => 'x = "a"' + rep(' /* c */ + /* d */ b + "a"', n) + ";",
    "template-parens.js": () => 'x = "a"' + rep(' + (b) + ("a")', n) + ";",
    "template-minus.js": () => 'x = "a"' + rep(' + b - c + "a"', n) + ";",
    "template-minus-no-string.js": () => "x = a" + rep(" + b - c", n) + ' + "a";',
    "template-right-small.js": () => 'x = "a"' + rep(' + (b + "a")', n) + ";",
    "template-times.js": () => 'x = "a"' + rep(" + b * c * d", n) + ";",
    "template-times-long.js": () => 'x = "a" + b' + rep(" * c", n) + ' + "a";',
    "template-templates.js": () => "x = `a`" + rep(" + `${b}` + 'c'", n) + ";",
    "template-stmts.js": () => rep('x = "a" + b;\n', n),
    "template-escapes.js": () => 'x = b' + rep(' + "`${\\"\\\\"', n) + ";",
    // regular expressions
    "regex-groups-unicode.js": () => "x = /" + rep("(é👍)", n) + "/;",
    "regex-groups-temp.js": () => "x = /" + seq(n, i => `(temp${i})`) + "/;",
    "regex-ctor-groups-unicode.js": () => 'x = new RegExp("' + rep("(é👍)", n) + '");',
    "regex-backrefs-deep.js": () => "x = /" + rep("(?:", 240) + "(a)" + rep(")", 240) + rep("(?:", 240) + rep("\\1", n) + rep(")", 240) + "/;",
    "regex-backrefs-deep-forward.js": () => "x = /" + rep("(?:", 240) + rep("\\1", n) + rep(")", 240) + rep("(?:", 240) + "(a)" + rep(")", 240) + "/;",
    "regex-backrefs-forward-big-group.js": () => "x = /" + rep("\\1", n) + "(" + rep("a", n) + ")/;",
    "regex-backrefs-same-name-many.js": () => "x = /" + rep("\\k<g>", n) + "(?:" + rep("(?<g>a)|", n) + "b)/;",
    "regex-backrefs-same-name-negative.js": () => "x = /(?!" + rep("(?<g>a)|", n) + "b)" + rep("\\k<g>", n) + "/;",
    "regex-backrefs-same-name-negative-last-not.js": () => "x = /(?:(?!" + rep("(?<g>a)|", n) + "b)|(?<g>a))" + rep("\\k<g>", n) + "/;",
    "regex-backrefs-same-name-lookbehind.js": () => "x = /(?<=(?:" + rep("(?<g>a)|", n) + "b)" + rep("\\k<g>", n) + ")/;",
    "regex-backrefs-same-name-each-alternative.js": () => "x = /" + rep("(?<g>a)\\k<g>|", n) + "b/;",
    "regex-backrefs-same-name-deep.js": () => "x = /(?:" + rep("(?<g>a)|", n) + "b)" + rep("(?:", 240) + rep("\\k<g>", n) + rep(")", 240) + "/;",
    "regex-backrefs-many-names.js": () => "x = /" + seq(n >> 4, i => "(?:" + rep(`(?<g${i}>a)|`, 16) + "b)" + rep(`\\k<g${i}>`, 16)) + "/;",
    "regex-backrefs-same-name-many-after.js": () => "x = /(?:" + rep("(?<g>a)|", n) + "b)" + rep("\\k<g>", n) + "/;",
    // vars-on-top, one-var
    "var-fns-with-vars.js": () => rep("var v = function () { var w; };\n", n),
    "var-after-imports.js": () => seq(n, i => `import v${i} from "m";\n`) + rep("var w;\n", n),
    "var-after-directives.js": () => rep('"d";\n', n) + rep("var w;\n", n),
    "var-after-call.js": () => "f();\n" + rep("var w;\n", n),
    "var-namespace-exports.ts": () => "namespace N {\n" + seq(n, i => `export var v${i} = 1;\n`) + "}",
    "var-static-block.js": () => "class A { static {\n" + seq(n, i => `var v${i} = 1;\n`) + "} }",
    "var-lets-consts.js": () => seq(n, i => `let v${i} = 1;\nconst c${i} = 1;\n`),
    "var-requires.js": () => seq(n, i => `var v${i} = require("m");\n`),
    "var-block-lets.js": () => "{\n" + seq(n, i => `let v${i} = 1;\n`) + "}",
    // require-atomic-updates
    "atomic-fns.js": () => rep("async function f(a) { await a; }\n", n),
    "atomic-fns-binary.js": () => "x = a" + rep(" + (async () => { await a; })", n) + ";",
    "atomic-fns-comma.js": () => "x = (a" + rep(", async () => { await a; }", n) + ");",
    "atomic-ifs-vars.js": () => seq(n, i => `let v${i} = 0;\n`) + "async function f(a) {\n" + seq(n, i => `if (a) { v${i} += await a; }\n`) + "}",
    "atomic-ifs-reads.js": () => seq(n, i => `let v${i} = 0;\n`) + "async function f(a) {\n" + seq(n, i => `if (v${i}) { await a; }\n`) + "}",
    "atomic-reads-then-ifs.js": () => seq(n, i => `let v${i} = 0;\n`) + "async function f(a) {\n" + seq(n, i => `g(v${i});\n`) + "await a;\n" + rep("if (a) { g(); }\n", n) + "}",
    "atomic-outer-writes.js": () => "let x = 0;\nasync function f(a) {\n" + rep("x += await a;\n", n) + "}",
    "atomic-member-chain.js": () => "async function f(a) {\n" + "a" + rep(".b", n) + " = await a;\n}",
    "atomic-params.js": () => "async function f(a) {\n" + rep("a.b += await a;\n", n) + "}",
    // no-whitespace-before-property
    "dots-lines.jsx": () => "a" + rep("\n.b", n) + ";\n<a />;",
    "dots-spaces.js": () => "a" + rep(" .b", n) + ";",
    "dots-spaces.jsx": () => "a" + rep(" .b", n) + ";\n<a />;",
    "dots-spaces-stmts.js": () => rep("a .b;\n", n),
    "index-spaces.js": () => "a" + rep(" [0]", n) + ";",
    "dots-type-query.ts": () => "let x: typeof a" + rep(" .b", n) + ";",
    "dots-jsx-tag.jsx": () => "<a" + rep(" .b", n) + " />;",
    "dots-implements.ts": () => "class A implements a" + rep(" .b", n) + " {}",
    // prefer-rest-params
    "arguments-reads.js": () => fn(rep("g(arguments);\n", n)),
    "arguments-fns.js": () => rep("function g() { return arguments; }\n", n),
    "arguments-length.js": () => fn(rep("g(arguments.length);\n", n)),
    "arguments-defaults.js": () => fn(rep("[arguments = 1] = a;\n", n)),
    // walks up from each operand of a chain, from each branch of an else-if chain
    "chain-fns-or-arg.js": () => "f(" + rep("function () {} || ", n) + "a);",
    "chain-fns-cond-arg.js": () => "f(a" + rep(" || (b ? function () {} : c)", n) + ");",
    "chain-fns-plus.js": () => "x = a" + rep(" + function () {}", n) + ";",
    "chain-fns-strict-plus.js": () => "x = a" + rep(' + function () { "use strict"; }', n) + ";",
    "chain-fns-comma.js": () => "x = (a" + rep(", function () {}", n) + ");",
    "chain-awaits-plus.js": () => "async function f(a) {\nreturn a" + rep(" + await a", n) + ";\n}",
    "chain-awaits-comma.js": () => "async function f(a) {\na" + rep(", await a", n) + ";\n}",
    "chain-has-own-plus.js": () => "x = a" + rep(" + Object.prototype.hasOwnProperty.call(a, b)", n) + ";",
    "chain-nan.js": () => "x = a" + rep(" == NaN", n) + ";",
    "chain-yoda.js": () => "x = a" + rep(" == 1", n) + ";",
    "chain-call-call.js": () => "a" + rep(".call(b)", n) + ";",
    "chain-apply.js": () => "a" + rep(".apply(b, c)", n) + ";",
    "chain-binds.js": () => "f(function () {}" + rep(".bind(this)", n) + ");",
    "else-if-throws.js": () => fn("try { a(); } catch (e) {\n" + rep('if (a) { throw new Error("x"); } else ', n) + "{}\n}"),
    "else-if-throws-no-catch.js": () => fn(rep('if (a) { throw new Error("x"); } else ', n) + "{}"),
    "else-if-returns.js": () => fn(rep("if (a) { return; } else ", n) + "{}"),
    "else-if-returns-then.js": () => fn(rep("if (a) { return; } else ", n) + "{}\nb();"),
    "else-if-vars.js": () => fn(seq(n, i => `if (a) { var v${i} = 1; } else `) + "{}"),
    "else-if-awaits.js": () => "async function f(a) {\n" + rep("if (a) { await a; } else ", n) + "{}\n}",
    "else-if-fns.js": () => rep("if (a) { (function () {}); } else ", n) + "{}",
    // no-useless-return
    "returns-ifs.js": () => fn(rep("if (a) { return; }\n", n)),
    "returns-ifs-last.js": () => fn(rep("if (a) { b(); return; }\n", n) + "return;"),
    "returns-cases.js": () => fn("switch (a) {\n" + seq(n, i => `case ${i}: return;\n`) + "}"),
    "returns-cases-blocks.js": () => fn("switch (a) {\n" + seq(n, i => `case ${i}: { b(); return; }\n`) + "}"),
    "returns-tries.js": () => fn(rep("try { return; } catch (e) { return; }\n", n)),
    "returns-try-ifs.js": () => fn("try {\n" + rep("if (a) { return; }\n", n) + "} finally { b(); }"),
    "returns-labels.js": () => fn("l: {\n" + rep("if (a) { break l; }\n", n) + "return;\n}"),
    "returns-fns.js": () => rep("function g(a) { if (a) { b(); return; } }\n", n),
    // no-var
    "var-hoisted-refs.js": () => fn("var v = 1;\nfunction g() {\n" + rep("v;\n", n) + "}\n" + rep("g;\n", n)),
    "var-hoisted-vars.js": () => fn(seq(n, i => `var v${i} = 1;\n`) + "function g() {\n" + seq(n, i => `v${i};\n`) + "}\n" + rep("g;\n", n)),
    "var-loop-closures.js": () => fn("for (;;) {\n" + seq(n, i => `var v${i} = 1; (() => v${i});\n`) + "}"),
    "var-loop-vars.js": () => fn("for (;;) {\n" + seq(n, i => `var v${i} = 1;\n`) + "}"),
    "var-declarators-var.js": () => fn("var " + seq(n, i => `v${i} = ${i}`, ", ") + ";"),
    "var-tdz.js": () => fn(seq(n, i => `var v${i} = v${i};\n`)),
    // sorting
    "sort-import-members.js": () => "import {" + seq(n, i => `v${n - i}`, ", ") + '} from "m";',
    "sort-import-members-case.js": () => "import {" + seq(n, i => (i % 2 ? `V${(n - i) >> 2}x${i}` : `v${(n - i) >> 2}x${i}`), ", ") + '} from "m";',
    "sort-import-members-random.js": () => "import {" + seq(n, i => `v${(i * 7919) % n}`, ", ") + '} from "m";',
    "sort-vars-desc.js": () => "var " + seq(n, i => `v${n - i}`, ", ") + ";",
    "sort-vars-random.js": () => "var " + seq(n, i => `v${(i * 7919) % n} = 1`, ", ") + ";",
    "sort-vars-same.js": () => "var " + rep("b, a, ", n) + "a;",
    "sort-keys-desc.js": () => "x = {" + seq(n, i => `v${n - i}: 1`, ", ") + "};",
    "sort-keys-lines.js": () => "x = {\n" + seq(n, i => `v${n - i}: 1`, ",\n\n") + "\n};",
    "sort-imports-desc.js": () => seq(n, i => `import v${n - i} from "m";\n`),
    // a long run of blank lines or comments before the first statement
    "blank-lines-then-directives.js": () => rep("\n", n) + rep("'d';\n", n),
    "blank-lines-then-directives-fn.js": () => "function f() {" + rep("\n", n) + rep("'d';\n", n) + "}",
    "blank-lines-then-vars.js": () => rep("\n", n) + rep("var w;\n", n),
    "blank-lines-then-calls.js": () => rep("\n", n) + rep("f();\n", n),
    "comments-then-directives.js": () => rep("// c\n", n) + rep("'d';\n", n),
    "comments-then-calls.js": () => rep("/* c */\n", n) + rep("f(function () {});\n", n),
    "blank-lines-between-two.js": () => "a();" + rep("\n", n) + rep("b();\n", n),
    // quotes
    "directives-single.js": () => rep("'use strict';\n", n),
    "directives-fn.js": () => fn(rep("'d';\n", n)),
    "strings-after-call.js": () => "f();\n" + rep("'d';\n", n),
    // params
    "callback-params.js": () => "f(function (" + seq(n, i => `p${i}`, ", ") + ") {});",
    "callback-params-same.js": () => "f(function (" + rep("p, ", n) + "p) {});",
    // comments
    "comments-in-block-line.js": () => "{ " + rep("/* c */ ", n) + "a; " + rep("/* c */ ", n) + "}",
    "comments-todo.js": () => rep("// todo: a\n", n),
    "comment-todo-long.js": () => "/* " + rep("todo ", n) + "*/",
    "comment-spaces.js": () => "/*" + rep(" ", n) + "todo */",
    "comment-exception.js": () => "/*" + rep("-", n) + "a*/\n//" + rep("-", n) + "a",
    // objects
    "object-shorthand-arrows.js": () => "x = {" + seq(n, i => `p${i}: () => { return this; }`, ", ") + "};",
    "object-fns.js": () => "x = {" + seq(n, i => `p${i}: function () {}`, ", ") + "};",
    "object-same-names.js": () => "x = {" + seq(n, i => `p${i}: p${i}`, ", ") + "};",
    "object-assign-args.js": () => "x = Object.assign({}" + rep(", {a: 1}", n) + ");",
    "object-assign-stmts.js": () => rep("x = Object.assign({}, a);\n", n),
    "object-in-object-close.js": () => "x = {" + rep("a: {b: 1}, ", n) + "c: {d: [1]}};",
    "object-last-objects.js": () => rep("x = {a: {b: [1]}};\n", n),
    "pattern-renames.js": () => "({" + seq(n, i => `p${i}: p${i}`, ", ") + "} = a);",
    "template-substitutions-escapes.js": () => "x = `" + rep("\\a${b}", n) + "`;",
    "math-pow-stmts.js": () => rep("x = Math.pow(a, b);\n", n),
    "math-pow-plus.js": () => "x = a" + rep(" + Math.pow(a, b)", n) + ";",
    "promise-rejects.js": () => "new Promise(function (a, b) {\n" + rep("b(1);\n", n) + "});",
    "regexp-flags-merge.js": () => 'x = new RegExp(/a/g, "' + rep("i", n) + '");',
    "statements-blocks-padding.js": () => rep("{ a(); }\nb();\n", n),
    "statements-object-stmts.js": () => rep("x = {a: 1};\n", n),
    "statement-big-object.js": () => "x = {" + seq(n, i => `p${i}: 1`, ", ") + "};\ny = 1;",
    "cases-blocks.js": () => "switch (a) {\n" + seq(n, i => `case ${i}: { b(); }\n`) + "}",
    "one-line-blocks.js": () => rep("{ a(); b() }\n", n),
    "class-fields.js": () => "class A {\n" + seq(n, i => `p${i} = 1;\n`) + "}",
    "class-fields-one-line.js": () => "class A { " + seq(n, i => `p${i} = 1; `) + "}",
  });
}

export function deep(n: number): Record<string, string> {
  return lazily({
    "deep-const-patterns.js": () => "let " + seq(n, i => `v${i}`, ", ") + ";\n" + seq(n, i => `[v${i}, `) + "a" + rep("]", n) + " = a;",
    "deep-const-patterns-defaults.js": () => "let " + seq(n, i => `v${i}`, ", ") + ";\n" + seq(n, i => `[v${i}, `) + "a" + rep(" = []]", n) + " = a;",
    "deep-const-blocks-patterns.js": () => seq(n, i => `{ let v${i}; [v${i}] = a;\n`) + rep("}", n),
    "deep-const-blocks-patterns-same.js": () => rep("{ let v; [v] = a;\n", n) + rep("}", n),
    "deep-const-let-patterns.js": () => "let " + seq(n, i => `[v${i}, `) + "a" + rep("]", n) + " = a;",
    "deep-template-right.js": () => "x = " + rep('"a" + (b + ', n) + "c" + rep(")", n) + ";",
    "deep-template-right-last.js": () => "x = " + rep("b + (b + ", n) + '"a"' + rep(")", n) + ";",
    "deep-template-calls.js": () => "x = " + rep('"a" + f(', n) + "c" + rep(")", n) + ";",
    "deep-one-line-blocks.js": () => rep("{ a();", n) + rep(" b() }", n),
    "deep-strict-fns.js": () => rep('function f() { "use strict";\n', n) + rep("}", n),
    "deep-fns-plain.js": () => rep("function f() {\n", n) + rep("}", n),
    "deep-callbacks-fn.js": () => rep("f(function () {\n", n) + rep("});", n),
    "deep-returns-ifs.js": () => "function f(a) {\n" + rep("if (a) {\n", n) + "return;" + rep("}", n) + "\n}",
    "deep-returns-ifs-each.js": () => "function f(a) {\n" + rep("if (a) { if (b) { return; }\n", n) + rep("}", n) + "\n}",
    "deep-returns-else.js": () => "function f(a) {\n" + rep("if (a) { return; } else {\n", n) + rep("}", n) + "\n}",
    "deep-tries-returns.js": () => "function f(a) {\n" + rep("try { if (a) { return; }\n", n) + rep("} finally {}", n) + "\n}",
    "deep-object-shorthand.js": () => "x = " + rep("{a: function () { return ", n) + "1" + rep("; }}", n) + ";",
    "deep-object-arrows.js": () => "x = " + rep("{a: () => { return ", n) + "1" + rep("; }}", n) + ";",
    "deep-objects-one-line.js": () => "x = " + rep("{a: ", n) + "1" + rep("}", n) + ";",
    "deep-math-pow.js": () => "x = " + rep("Math.pow(a, ", n) + "1" + rep(")", n) + ";",
    "deep-object-assign.js": () => "x = " + rep("Object.assign({}, ", n) + "a" + rep(")", n) + ";",
    "deep-throws-catches.js": () => rep('try { a(); } catch (e) { throw new Error("x");\n', n) + rep("}", n),
    "deep-vars-blocks.js": () => "function f() {\n" + seq(n, i => `{ var v${i} = 1;\n`) + rep("}", n) + "\n}",
    "deep-awaits-fns.js": () => rep("async function f(a) { await a;\n", n) + rep("}", n),
    "deep-atomic-fns.js": () => rep("async function f(a) { await a;\n", n) + rep("}", n),
  });
}
