// Writes inputs.json: the sources of probe.cjs, by group. usage: node make-inputs.cjs
const rows = [];
const g = (group, list) => { for (const e of list) rows.push(typeof e === "string" ? { g: group, s: e } : { g: group, l: e[0], s: e[1] }); };
const B = "\\";
g("TS2880 assert", [
  'import x from "y" assert { type: "json" };',
  'import "y" assert { type: "json" };',
  'import * as x from "y" assert { type: "json" };',
  'import { a } from "y" assert { type: "json" };',
  'import type x from "y" assert { type: "json" };',
  'export * from "y" assert { type: "json" };',
  'export * as ns from "y" assert { type: "json" };',
  'export { a } from "y" assert { type: "json" };',
  'export type { a } from "y" assert { type: "json" };',
  'import x from "y"\nassert { type: "json" };',
  'import x from "y"\nwith { type: "json" };',
  'export * from "y"\nwith { type: "json" };',
  'export * from "y"\nassert { type: "json" };',
  'import x from "y" with { type: "json" };',
  'import x from "y" assert;',
  'import x from "y" assert {};',
  'type T = import("y", { assert: { "resolution-mode": "import" } });',
  'type T = typeof import("y", { assert: { "resolution-mode": "import" } });',
  'type T = import("y", { with: { "resolution-mode": "import" } });',
  'type T = import("y", { foo: {} });',
  'let v: import("y", { assert: { "resolution-mode": "import" } }).T;',
  'x as import("y", { assert: { "resolution-mode": "import" } }).T;',
  'import("y", { assert: { type: "json" } });',
  ["js", 'import x from "y" assert { type: "json" };'],
  ["dts", 'import x from "y" assert { type: "json" };'],
  'import x from "y" assert { type: "json" }, z;',
  'import x from "y" /* c */ assert /* d */ { type: "json" };',
]);
g("TS1357 TS1132 enum", [
  "enum E { A B }",
  "enum E { A = 1 B }",
  "enum E { A; B }",
  "enum E { A = 1; }",
  "enum E { A\nB }",
  'enum E { "a" "b" }',
  "enum E { A: 1 }",
  "enum E { A, , B }",
  "enum E { , }",
  "enum E { + }",
  "enum E { 1 }",
  "enum E { 1n }",
  "enum E { [x] }",
  "enum E { ['a'] }",
  "enum E { [`a`] }",
  "enum E { #a }",
  "enum E { A = }",
  "enum E { A, B",
  "enum E { A",
  "enum E { A = 1",
  "enum E { A, B, }",
  "const enum E { A B }",
  "declare enum E { A B }",
  "export enum E { A B }",
  "enum E { A ( }",
  "enum E { A.B }",
  "enum E { A ! }",
  "enum E { class }",
  "enum E { class = 1, var, }",
  "enum E A }",
  "enum { A }",
  "enum E { A } B",
  "enum E { A = 1 + , B }",
  "enum E { A /* c */ B }",
]);
g("TS1260 escaped keyword", [
  B + "u0076ar x = 1;",
  "v" + B + "u0061r x = 1;",
  B + "u{76}ar x = 1;",
  "var " + B + "u0076ar = 1;",
  "x = tru" + B + "u0065;",
  "x = " + B + "u0074rue;",
  "x = n" + B + "u0075ll;",
  "x = " + B + "u0074his;",
  "x = typ" + B + "u0065of y;",
  "x = n" + B + "u0065w Y();",
  "x = v" + B + "u006fid 0;",
  "x = d" + B + "u0065lete y.z;",
  B + "u0069f (x) {}",
  B + "u0066unction f() {}",
  B + "u0063lass C {}",
  B + "u0065lse",
  "x = " + B + "u0076ar;",
  "foo." + B + "u0076ar;",
  "({ " + B + "u0076ar: 1 });",
  "var " + B + "u0061sync = 1;",
  B + "u0061sync function f() {}",
  "x = " + B + "u0061sync () => 1;",
  "x " + B + "u0061s T;",
  "x " + B + "u0073atisfies T;",
  B + "u0074ype T = number;",
  B + "u0069nterface I {}",
  "n" + B + "u0061mespace N {}",
  "m" + B + "u006fdule N {}",
  "d" + B + "u0065clare const x: number;",
  B + "u0061bstract class C {}",
  "l" + B + "u0065t x = 1;",
  "c" + B + "u006fnst x = 1;",
  "class C { st" + B + "u0061tic x = 1 }",
  "class C { " + B + "u0067et x() { return 1 } }",
  "class C { publi" + B + "u0063 x = 1 }",
  "class C { r" + B + "u0065adonly x = 1 }",
  "class C { " + B + "u0063onstructor() {} }",
  "class C { " + B + "u0061sync m() {} }",
  "class C " + B + "u0065xtends D {}",
  "class C " + B + "u0069mplements D {}",
  "let x: " + B + "u0073tring;",
  "let x: " + B + "u0061ny;",
  "let x: k" + B + "u0065yof T;",
  "let x: " + B + "u0074ypeof y;",
  "let x: r" + B + "u0065adonly T[];",
  "type T<U> = U " + B + "u0065xtends V ? 1 : 2;",
  "type T<U> = U extends " + B + "u0069nfer V ? 1 : 2;",
  "function f(x: T): x " + B + "u0069s U {}",
  "for (const x " + B + "u006ff y) {}",
  "for (const x " + B + "u0069n y) {}",
  'import x fr' + B + 'u006fm "y";',
  'import ' + B + 'u0074ype X from "y";',
  'import { ' + B + 'u0074ype X } from "y";',
  'import { X ' + B + 'u0061s Y } from "y";',
  "export d" + B + "u0065fault 1;",
  B + "u0065xport const x = 1;",
  B + 'u0069mport x from "y";',
  "function f() { r" + B + "u0065turn 1 }",
  "x = y inst" + B + "u0061nceof z;",
  "x = y " + B + "u0069n z;",
  "async function f() { " + B + "u0061wait x; }",
  "function* g() { " + B + "u0079ield 1; }",
  "x = { g" + B + "u0065t a() { return 1 } };",
  "label: br" + B + "u0065ak label;",
  "d" + B + "u006f {} while (x)",
  "try {} c" + B + "u0061tch {}",
  "try {} f" + B + "u0069nally {}",
  "switch (x) { c" + B + "u0061se 1: }",
  "switch (x) { d" + B + "u0065fault: }",
  "let " + B + "u0074ype = 1;",
  "let " + B + "u0079ield = 1;",
  "var " + B + "u0061wait = 1;",
  B + "u0074hrow x;",
  B + "u0064ebugger;",
  "x = " + B + "u0073uper.y;",
  "x = " + B + "u0066alse;",
  "x = " + B + "u0066unction () {};",
  "x = " + B + "u0063lass {};",
  "x = " + B + "u0069mport('y');",
  "function f(" + B + "u0074his: T) {}",
  "class C { m(): " + B + "u0074his {} }",
  "enum E { " + B + "u0076ar }",
  "type T = { " + B + "u0076ar: 1 };",
  "type T = " + B + "u0076oid;",
  "type T = " + B + "u006eull;",
  "x = <" + B + "u0063onst>y;",
  "let x: unique " + B + "u0073ymbol;",
  "a" + B + "u0073 = 1;",
  ["js", B + "u0076ar x = 1;"],
  ["js", "var " + B + "u0061sync = 1;"],
]);
g("lists: TS1135 arguments", [
  "f(:)", "f(a, :)", "f(})", "f(]", "f(;", "f(a, ;", "f(", "f(a,", "f(a b)", "f(+)", "f(...;)", "f(a, (b, ))", "f((;))",
  "new A(:)", "new A(a, :)", "f(a, ])", "f(=)", "f(=>)", "f(a, ?)", "f(.)", "f(*)", "f(a, *)", "f(in)", "f(a, case)", "f(a, else)",
  "@f(:) class C {}", "super(:)", "f?.(:)", "f<T>(:)", "import(:)", "f`${:}`", "f(a, /* c */ :)", "f(\n:)",
  "f(var)", "f(a, var)", "f(if)", "f(a, })",
]);
g("lists: TS1137 array literal", [
  "x = [:]", "x = [a, :]", "x = [)]", "x = [a, )]", "x = [;", "x = [a, ;", "x = [", "x = [a,", "x = [a b]", "x = [+]", "x = [...;]",
  "x = [}]", "x = [a, }]", "x = [=]", "x = [.]", "x = [a, .]", "x = [,,:]", "[:] = x", "x = [a, in]", "x = [a, /* c */ )]", "x = [a, var]",
]);
g("lists: TS1136 object literal", [
  "x = {:}", "x = {a, :}", "x = {)}", "x = {a: 1, )}", "x = {;", "x = {a: 1, ;", "x = {", "x = {a: 1,", "x = {a: 1 b: 2}", "x = {+}",
  "x = {a: 1; b: 2}", "x = {,}", "x = {a: 1,, b: 2}", "x = {=}", "x = {a: 1, =}", "x = {.}", "x = {*}", "x = {a: 1, ]}", "x = {a b}", "x = {a: }",
  "x = {1: 1, +}", "x = {...}", "x = {a: 1, /* c */ )}", "({)})", "x = {a: 1, ?}", "x = {a: 1, !}", "x = {a: 1, <}",
]);
g("lists: TS1138 TS1390 parameters", [
  "function f(:) {}", "function f(a, :) {}", "function f(+) {}", "function f(a, +) {}", "function f(;", "function f(", "function f(a,", "function f(a b) {}",
  "function f(}) {}", "function f(a, }) {}", "function f(class) {}", "function f(a, class) {}", "function f(var) {}", "function f(if) {}", "function f(1) {}", "function f(a, 1) {}",
  "function f('a') {}", "function f(a, .) {}", "function f(...) {}", "function f(...1) {}", "function f(=) {}", "function f(a, =) {}",
  "x = function (:) {}", "x = (a, :) => 1", "x = async (a, :) => 1", "class C { m(:) {} }", "class C { constructor(:) {} }", "class C { m(a, :) {} }", "x = { m(:) {} }", "x = { set a(:) {} }",
  "type T = (:) => void", "type T = (a, :) => void", "type T = { m(:): void }", "type T = new (:) => void", "function f(a, /* c */ :) {}", "function f(this) {}", "function f(a, ]) {}", "function f(])",
  "function f(a, null) {}", "function f(a, true) {}", "function f(a, this) {}", "function f(a, new) {}", "function f(a, void) {}",
]);
g("lists: TS1139 type parameters", [
  "function f<:>() {}", "function f<T, :>() {}", "function f<>() {}", "function f<1>() {}", "function f<T, 1>() {}", "function f<T U>() {}", "function f<+>() {}", "function f<T, +>() {}",
  "class C<:> {}", "class C<T, :> {}", "interface I<:> {}", "type T<:> = 1", "type T<U, :> = 1", "type T<U, 1> = 1", "type T<;", "type T<U,", "type T<U, ;",
  "type T<U, class> = 1", "type T<class> = 1", "x = <T, :>() => 1", "type T = <U, :>() => void", "class C { m<T, :>() {} }", "type T<U, /* c */ :> = 1", "type T<U, )> = 1", "type T<U, ]> = 1",
  "type T<U, }> = 1", "type T<U, => = 1", "type T<'a'> = 1", "type T<U, 'a'> = 1", "type T<U, [> = 1", "type T<U, *> = 1",
]);
g("lists: TS1134 TS1389 variable declarations", [
  "var ;", "var", "let ;", "const ;", "var a, ;", "var a, ", "var :", "var a, :", "var +", "var a, +", "var 1", "var a, 1", "var class", "var a, class", "var if;", "var a, var b;",
  "var a b", "var a, )", "var )", "var a, }", "var =", "var a, = 1", "var a = 1, = 2", "for (var ; ;) {}", "for (var a, ; ;) {}", "for (var of x) {}", "for (var in x) {}", "for (var a, of x) {}",
  "export var ;", "declare var ;", "var a, /* c */ :", "var 'a'", "var a, 'a'", "var #a", "using ;", "var a, null", "var a, this", "var a, true", "var a, typeof", "var a, new",
  "let a, class", "const a = 1, +", "var a, .", "var a, ?", "var a, !", "var a, *", "var a, <", "var a, =>", "var a, enum", "var enum",
]);
g("lists: TS1180 object binding", [
  "var {:} = x", "var {a, :} = x", "var {+} = x", "var {a, +} = x", "var {)} = x", "var {a, )} = x", "var {;", "var {a, ;", "var {", "var {a,", "var {a b} = x", "var {a: } = x", "var {a: 1} = x",
  "var {,} = x", "var {a,, b} = x", "var {=} = x", "var {a, =} = x", "var {...} = x", "var {...1} = x", "function f({:}) {}", "function f({a, :}) {}", "x = ({a, :}) => 1", "for (var {a, :} of x) {}",
  "try {} catch ({a, :}) {}", "var {a, /* c */ :} = x", "var {a, ]} = x", "var {1} = x", "var {a, class} = x", "var {class} = x", "var {a, .} = x", "var {a: {:}} = x", "var {a, *} = x", "var {a, ?} = x",
]);
g("lists: TS1181 array binding", [
  "var [:] = x", "var [a, :] = x", "var [+] = x", "var [a, +] = x", "var [)] = x", "var [a, )] = x", "var [;", "var [a, ;", "var [", "var [a,", "var [a b] = x", "var [1] = x", "var [a, 1] = x",
  "var [=] = x", "var [a, =] = x", "var [...] = x", "var [...1] = x", "function f([:]) {}", "function f([a, :]) {}", "x = ([a, :]) => 1", "for (var [a, :] of x) {}", "try {} catch ([a, :]) {}",
  "var [a, /* c */ :] = x", "var [a, }] = x", "var [class] = x", "var [a, class] = x", "var [a, .] = x", "var [[:]] = x", "var [a, *] = x", "var [a, 'b'] = x", "var [a, this] = x", "var [a, null] = x",
]);
g("TS1129 TS1130 switch", [
  "switch (x) { case 1: ) }", "switch (x) { case 1: foo; ) }", "switch (x) { default: ) }", "switch (x) { case 1: { ) } }", "switch (x) { case 1: if (a) ) }", "switch (x) { case 1: a: ) }",
  "switch (x) { case 1: function f() { ) } }", "switch (x) { case 1: switch (y) { case 2: ) } }", "switch (x) { case 1: : }", "switch (x) { case 1: else }", "switch (x) { case 1: = }",
  "switch (x) { case 1: + }", "switch (x) { case 1: in }", "switch (x) { case 1: catch }", "switch (x) { case 1: ] }", "switch (x) { case 1: , }", "switch (x) { case 1: . }", "switch (x) { case 1: => }",
  "switch (x) { foo; }", "switch (x) { ) }", "switch (x) { 1: }", "switch (x) { ; }", "switch (x) { { } }", "switch (x) { var a; }", "switch (x) { case 1: break; foo }", "switch (x) { else }",
  "switch (x) { + }", "switch (x) { , }", "switch (x) {", "switch (x) { case 1:", "switch (x) { case 1: foo;", "switch (x) { case }", "switch (x) { case 1 }", "switch (x) { default }", "switch (x) { default: default: }",
  "switch (x) { /* c */ foo; }", "switch (x) { case 1: /* c */ ) }", "switch (x) { function f() {} }", "switch (x) { class C {} }", "switch (x) { if (a) b; }", "switch (x) { x }", "switch (x) { 'a' }",
  "switch (x) { case 1: case 2: ) }", "switch (x) { case 1: default }", ["js", "switch (x) { case 1: ) }"], ["js", "switch (x) { foo; }"],
]);
g("TS1472 try", [
  "try {} foo", "try {}", "try {} ;", "try {} else", "try {}\nfoo()", "try {} catch {} foo", "try {} catch (e) {} finally", "try {} finally foo", "try {} )", "try {} catch", "try {} catch (", "try {} catch (e",
  "try {} catch (e) foo", "try foo", "try", "try {} /* c */ foo", "function f() { try {} }", "{ try {} }", "try {} try {} catch {}", "try {} var a;", "try { } 1", ["js", "try {} foo"],
]);
g("missing semicolon: TS1434 TS1435 TS1440 TS1228 TS1437-1439", [
  "foo bar", "foo bar baz", "foo 1", "foo 'a'", "foo {}", "foo [", "foo +", "foo\nbar", "a.b c", "foo() bar", "(foo) bar", "foo! bar", "1 bar", "'a' bar", "foo bar;", "{ foo bar }", "function f() { foo bar }",
  "if (a) foo bar", "label: foo bar", "clas C {}", "functio f() {}", "cosnt x = 1", "asyn function f() {}", "interfac I {}", "typ T = 1", "namespac N {}", "modul N {}", "declar const x: number", "abstrac class C {}",
  "improt x from 'y'", "exprot const x = 1", "retrun 1", "thorw x", "awiat x", "yeild x", "lte x = 1", "vra x = 1", "fucntion f() {}", "classs C {}", "constx = 1", "const1 = 1", "varfoo bar", "letfoo bar", "functionfoo bar",
  "classFoo {}", "asyncfunction f() {}", "interfaceFoo {}", "typeFoo = 1", "const x", "let x y", "var x y", "x const y", "const const", "foo const", "const", "let", "var", "foo let", "foo var", "declare foo", "declare", "foo declare",
  "interface {}", "interface I", "interface", "interface 1", "foo interface", "interface foo bar", "is x", "x is y", "x is", "foo is string", "module {}", "namespace {}", "module", "namespace", "module 1", "namespace 1",
  "module foo bar", "namespace a.b c", "type", "type = 1", "type T", "type 1", "type foo bar", "foo type", "type T 1", "type `a`", "module `M1` {}", "namespace `a` {}", "throw foo bar", "throw a b", "throw",
  "throw\nfoo", "foo /* c */ bar", "/* c */ foo bar", "  foo bar", "foo bar\nbaz", "async foo", "await foo", "yield foo", "of x", "abstract foo", "static foo", "public foo", "private x", "readonly x", "enum", "accessor x", "get x", "set x",
  "global x", "require x", "from x", "as x", "satisfies x", "asserts x", "infer x", "keyof x", "unique x", "out x", "override x", "any x", "number x", "string x", "boolean x", "symbol x", "object x", "never x", "unknown x", "bigint x", "undefined x",
  "using x", "defer x", "x y = 1", "foo: bar baz", "a b c d", "x = 1 y", "x++ y", "delete x y", "typeof x y", "void 0 y", "new X y", "x ? y : z w", "x as T y", "x! y", "<T>x y", "x satisfies T y", "x\n++y z", "return x y", "break x y",
  "continue x y", "debugger x", "do x while (y) z", "export default x y", "export = x y", "import x = y z", "var x = 1 y", "let x: T y", "type T = U V", "declare var x y", ["js", "foo bar"], ["js", "cosnt x = 1"], ["tsx", "foo bar"],
  "\u00e9 bar", "foo \u00e9", "föö bar", "f\\u006fo bar", "$ bar", "_ bar", "a1 bar", "x => y z", "async x => y z", "() => {} z", "function () {} z", "class {} z", "`a` b", "a`b` c", "/a/ b", "this b", "super.a b", "null b", "true b", "new.target b", "import.meta b",
]);
g("class members: TS1442 TS1441 TS1436 TS1144 TS1068", [
  "class C { x: number y }", "class C { x: number y: string }", "class C { x: number = 1 y }", "class C { x = 1 y }", "class C { x y }", "class C { x y z }", "class C { x: number() }", "class C { x() }", "class C { x: () }",
  "class C { x @dec y }", "class C { x: number @dec y }", "class C { x = 1 @dec y }", "class C { x\n@dec y }", "class C { x @dec }", "class C { foo() bar }", "class C { foo() }", "class C { foo(): void }", "class C { foo(): void bar }",
  "class C { constructor() bar }", "class C { constructor() }", "class C { get x() }", "class C { get x() bar }", "class C { set x(v) bar }", "class C { static foo() bar }", "class C { async foo() bar }", "class C { *foo() bar }", "class C { foo?() bar }",
  "class C { foo<T>() bar }", "function f() bar", "function f()", "function f(): void", "function f(): void bar", "function f() => 1", "function f();", "function f()\nbar", "async function f() bar", "function* f() bar", "export function f() bar",
  "export default function () bar", "x = function () bar", "x = function f() bar", "x = { m() bar }", "x = { get a() bar }", "x = { async m() bar }", "x = { *m() bar }", "declare function f() bar", "declare class C { foo() bar }",
  "abstract class C { abstract foo() bar }", "class C { foo() { } bar }", "class C { : }", "class C { ) }", "class C { + }", "class C { , }", "class C { = }", "class C { . }", "class C { x; ) }", "class C { x, y }", "class C { 1 2 }", "class C { ; ; }",
  "class C { x: number; ) }", "class C { foo() {} ) }", "class C { static }", "class C { static ) }", "class C { public ) }", "class C { public static ) }", "class C { @dec ) }", "class C { @dec }", "class C { x: number = }", "class C { x = }",
  "class C { x: }", "class C { x! y }", "class C { x? y }", "class C { x!: number y }", "class C { x?: number y }", "class C { [k: string]: number y }", "class C { 'a' 'b' }", "class C { a\nb }", "class C { a: T\nb }", "class C { a = 1\nb }",
  "class C { a: number b = 1 }", "class C { a: number, b }", "class C { a: number = 1, b }", "class C { a = 1, b }", "class C { a, b }", "class C { a: number: string }", "class C { a: number = 1 = 2 }", "class C { a: number ( }", "class C { a = 1 ( }", "class C { a ( }",
  "class C { foo() =>", "class C { accessor x y }", "class C { static x y }", "class C { declare x: number y }", "class C { readonly x: number y }", "class C { x: number /* c */ y }", "class C { foo() /* c */ bar }", "class C {", "class C { x", "class C { x:",
  "class C { foo(", "class C { foo()", "class C { x: number", "class C { x = 1", "class C extends {}", "class C extends A B {}", "class C extends A, B {}", "class C implements {}", "class C implements A B {}", "class C extends A implements B C {}",
  "class C foo {}", "class C extends A foo {}", "class C extends : {}", "class C implements : {}", "class C implements A, : {}", "interface I extends : {}", "interface I extends A, : {}", "interface I extends {}", "interface I extends A B {}",
  "interface I foo {}", "class C extends A extends B {}", "class C implements A implements B {}", "class C implements A extends B {}", ["js", "class C { x y }"], ["js", "class C { foo() bar }"], ["js", "function f() bar"], ["js", "class C { ) }"],
  "x = class { x: number y }", "x = class { foo() bar }", "x = class { ) }", "class C { static { ) } }", "class C { static {} ) }", "class C { x: number\n(y) }", "class C { x\n(y) }", "class C { x = 1\n(y) }", "class C { x: number\n[y] }", "class C { x = 1\n[y] }",
  "class C { x: number y() {} }", "class C { x = y z }", "class C { x: T<U> y }", "class C { x: number } y", "class C { get }", "class C { get; }", "class C { get x }", "class C { set }", "class C { async }", "class C { async x }", "class C { async\nx() {} }",
]);
require("node:fs").writeFileSync(__dirname + "/inputs.json", JSON.stringify(rows, null, 0).replace(/\},\{/g, "},\n{"));
console.log(rows.length + " inputs");
