register_repository(
  NAME
    cares
  REPOSITORY
    c-ares/c-ares
  COMMIT
    d1722e6e8acaf10eb73fa995798a9cd421d9f85e
)

register_cmake_command(
  TARGET
    cares
  TARGETS
    c-ares
  ARGS
    -DCARES_STATIC=ON
    -DCARES_STATIC_PIC=ON
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DCARES_SHARED=OFF
    -DCARES_BUILD_TOOLS=OFF
  LIB_PATH
    lib
  LIBRARIES
    cares
)
