register_repository(
  NAME
    cares
  REPOSITORY
    c-ares/c-ares
  COMMIT
    3ac47ee46edd8ea40370222f91613fc16c434853
)

register_cmake_command(
  TARGET
    cares
  TARGETS
    c-ares
  ARGS
    -DCARES_STATIC:BOOL=ON
    -DCARES_STATIC_PIC:BOOL=ON
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DCARES_SHARED:BOOL=OFF
    -DCARES_BUILD_TOOLS:BOOL=OFF
    -DCMAKE_INSTALL_LIBDIR=lib
  LIB_PATH
    lib
  LIBRARIES
    cares
  INCLUDES
    include
)
