// p_core: in-process runtime APIs (fs, os, process, crypto, path). No network, no spawning.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import v8 from 'node:v8';
import { createRequire } from 'node:module';
import { t, ta, done } from './_h.mjs';
const require = createRequire(import.meta.url);

t('process.cwd', () => process.cwd());
t('process.execPath', () => process.execPath);
t('process.version', () => process.version + ' ' + Bun.version);
t('process.memoryUsage', () => JSON.stringify(process.memoryUsage()).slice(0, 50));
t('process.cpuUsage', () => JSON.stringify(process.cpuUsage()));
t('process.resourceUsage', () => JSON.stringify(process.resourceUsage()).slice(0, 50));
t('process.hrtime', () => String(process.hrtime.bigint() > 0n));
t('process.uptime', () => String(process.uptime() >= 0));
t('process.title.get', () => process.title);
t('process.title.set', () => { process.title = 'acprobe'; return process.title; });
t('process.kill(self,0)', () => String(process.kill(process.pid, 0)));
t('os.tmpdir', () => os.tmpdir());
t('os.homedir', () => os.homedir());
t('os.hostname', () => os.hostname());
t('os.userInfo', () => JSON.stringify(os.userInfo()).slice(0, 90));
t('os.cpus', () => 'n=' + os.cpus().length);
t('os.totalmem', () => String(os.totalmem() > 0));
t('os.freemem', () => String(os.freemem() > 0));
t('os.uptime', () => String(os.uptime() > 0));
t('os.release', () => os.release());
t('os.version', () => os.version());
t('os.machine', () => os.machine());
t('os.networkInterfaces', () => JSON.stringify(Object.keys(os.networkInterfaces())));
t('os.loadavg', () => JSON.stringify(os.loadavg()));
t('os.availableParallelism', () => String(os.availableParallelism()));
t('os.getPriority', () => String(os.getPriority()));
t('os.endianness', () => os.endianness());
t('fs.writeFileSync', () => { fs.writeFileSync('t.txt', 'hello'); return 'ok'; });
t('fs.readFileSync', () => fs.readFileSync('t.txt', 'utf8'));
t('fs.statSync', () => String(fs.statSync('t.txt').size));
t('fs.lstatSync', () => String(fs.lstatSync('t.txt').isFile()));
t('fs.accessSync', () => { fs.accessSync('t.txt'); return 'ok'; });
t('fs.mkdirSync.recursive', () => { fs.mkdirSync('d1/d2', { recursive: true }); return 'ok'; });
t('fs.readdirSync', () => String(fs.readdirSync('.').length));
t('fs.readdirSync.recursive', () => String(fs.readdirSync('.', { recursive: true }).length));
t('fs.readdirSync.withFileTypes', () => String(fs.readdirSync('.', { withFileTypes: true }).length));
t('fs.opendirSync', () => { const d = fs.opendirSync('.'); const e = d.readSync(); d.closeSync(); return String(e && e.name); });
t('fs.copyFileSync', () => { fs.copyFileSync('t.txt', 't2.txt'); return 'ok'; });
t('fs.cpSync.dir', () => { fs.cpSync('d1', 'd1copy', { recursive: true }); return 'ok'; });
t('fs.renameSync', () => { fs.renameSync('t2.txt', 't3.txt'); return 'ok'; });
t('fs.appendFileSync', () => { fs.appendFileSync('t.txt', 'x'); return 'ok'; });
t('fs.open+fstat+read+close', () => { const fd = fs.openSync('t.txt', 'r'); const s = fs.fstatSync(fd); const b = Buffer.alloc(3); fs.readSync(fd, b, 0, 3, 0); fs.closeSync(fd); return s.size + ' ' + b.toString(); });
t('fs.writevSync', () => { const fd = fs.openSync('wv.txt', 'w'); fs.writevSync(fd, [Buffer.from('a'), Buffer.from('b')]); fs.closeSync(fd); return 'ok'; });
t('fs.rmSync.recursive', () => { fs.rmSync('d1copy', { recursive: true }); return 'ok'; });
t('fs.realpathSync', () => fs.realpathSync('t.txt'));
t('fs.realpathSync.native', () => fs.realpathSync.native('t.txt'));
t('fs.statfsSync', () => JSON.stringify(fs.statfsSync('.')).slice(0, 60));
t('fs.linkSync(hardlink)', () => { try { fs.rmSync('hard.txt') } catch {}; fs.linkSync('t.txt', 'hard.txt'); return 'ok'; });
t('fs.symlinkSync.file', () => { try { fs.rmSync('sym.txt') } catch {}; fs.symlinkSync('t.txt', 'sym.txt', 'file'); return 'ok'; });
t('fs.symlinkSync.junction', () => { try { fs.rmSync('jl', { recursive: true }) } catch {}; fs.mkdirSync('jt', { recursive: true }); fs.symlinkSync(path.resolve('jt'), 'jl', 'junction'); return 'ok'; });
t('fs.readlinkSync(junction)', () => fs.readlinkSync('jl'));
t('fs.realpathSync(junction)', () => fs.realpathSync('jl'));
t('fs.utimesSync', () => { fs.utimesSync('t.txt', new Date(), new Date()); return 'ok'; });
t('fs.chmodSync', () => { fs.chmodSync('t.txt', 0o644); return 'ok'; });
t('fs.watch+close', () => { const w = fs.watch('.', () => {}); w.close(); return 'ok'; });
t('fs.watchFile+unwatch', () => { fs.watchFile('t.txt', () => {}); fs.unwatchFile('t.txt'); return 'ok'; });
t('fs.mkdtempSync(tmpdir)', () => fs.mkdtempSync(path.join(os.tmpdir(), 'acp-')));
t('fs.globSync', () => JSON.stringify(fs.globSync('*.txt')).slice(0, 60));
await ta('fsp.readFile', async () => (await import('node:fs/promises')).readFile('t.txt', 'utf8'));
await ta('fsp.realpath', async () => (await import('node:fs/promises')).realpath('t.txt'));
await ta('fsp.readdir', async () => String((await (await import('node:fs/promises')).readdir('.')).length));
await ta('Bun.write+Bun.file.text', async () => { await Bun.write('bw.txt', 'bun'); return await Bun.file('bw.txt').text(); });
await ta('Bun.file.stat', async () => String((await Bun.file('bw.txt').stat()).size));
await ta('Bun.file.writer', async () => { const w = Bun.file('bww.txt').writer(); w.write('x'); await w.end(); return 'ok'; });
t('Bun.hash', () => String(Bun.hash('abc')));
t('Bun.which(cmd)', () => String(Bun.which('cmd')));
t('Bun.resolveSync(self)', () => Bun.resolveSync('./p_core.mjs', process.cwd()));
t('Bun.resolveSync(pkg)', () => Bun.resolveSync('tiny-probe-pkg', process.cwd()));
t('import.meta.path', () => import.meta.path + '|' + import.meta.dir);
t('require(cjs pkg)', () => JSON.stringify(require('tiny-probe-pkg')));
await ta('import(cjs pkg)', async () => JSON.stringify(await import('tiny-probe-pkg')));
t('crypto.randomBytes', () => crypto.randomBytes(8).toString('hex'));
t('crypto.randomUUID', () => crypto.randomUUID().length);
t('crypto.createHash.sha256', () => crypto.createHash('sha256').update('x').digest('hex').slice(0, 16));
t('crypto.createHmac', () => crypto.createHmac('sha256', 'k').update('x').digest('hex').slice(0, 16));
t('crypto.generateKeyPairSync', () => { const { publicKey } = crypto.generateKeyPairSync('ed25519'); return typeof publicKey; });
t('crypto.createCipheriv', () => { const c = crypto.createCipheriv('aes-128-gcm', Buffer.alloc(16), Buffer.alloc(12)); c.update('x'); c.final(); return 'ok'; });
await ta('crypto.subtle.digest', async () => Buffer.from(await crypto.webcrypto.subtle.digest('SHA-256', Buffer.from('x'))).toString('hex').slice(0, 16));
await ta('Bun.password.hash+verify', async () => { const h = await Bun.password.hash('pw', { algorithm: 'bcrypt', cost: 4 }); return String(await Bun.password.verify('pw', h)); });
t('zlib.gzipSync', () => String(zlib.gzipSync(Buffer.from('hello')).length));
t('zlib.brotliCompressSync', () => String(zlib.brotliCompressSync(Buffer.from('hello')).length));
t('Bun.gzipSync', () => String(Bun.gzipSync('hello').length));
t('v8.getHeapStatistics', () => String(v8.getHeapStatistics().used_heap_size > 0));
t('structuredClone', () => JSON.stringify(structuredClone({ a: [1, 2, 3] })));
t('TextEncoder', () => String(new TextEncoder().encode('abc').length));
t('URL', () => new URL('https://x.test/a?b=c').href);
t('Intl.DateTimeFormat.TZ', () => new Intl.DateTimeFormat('en-US', { timeZone: 'America/New_York', timeStyle: 'long' }).format(0));
t('Date.toLocaleString', () => new Date(0).toLocaleString('en-US'));
t('Intl.NumberFormat', () => new Intl.NumberFormat('de-DE').format(12345.6));
t('Error.stack', () => { try { null.x } catch (e) { return e.stack.split('\n').length + ' frames'; } });
t('Bun.inspect', () => Bun.inspect({ a: 1 }).replace(/\s+/g, ''));
t('Bun.stringWidth', () => String(Bun.stringWidth('abc')));
t('Bun.escapeHTML', () => Bun.escapeHTML('<x>'));
t('Bun.fileURLToPath', () => Bun.fileURLToPath(import.meta.url));
t('Bun.randomUUIDv7', () => Bun.randomUUIDv7().length);
t('performance.now', () => String(performance.now() > 0));
t('navigator.hardwareConcurrency', () => String(navigator.hardwareConcurrency));
t('Bun.main', () => Bun.main);
t('Bun.generateHeapSnapshot', () => String(JSON.stringify(Bun.generateHeapSnapshot()).length > 0));
done('P_CORE');
