import { describe, expect, test } from "bun:test";
import { bunEnv, bunExe } from "harness";

// JSC exposes tamper-proof references to the original builtins ("primordials",
// JSCPrimordials.h, generated by src/codegen/generate-primordials.ts) to Bun's
// builtin JavaScript as `$Name` link-time constants, and internal/primordials
// assembles them into Node's `primordials` object for ported lib/ code.
//
// `bun:internal-for-testing` exposes both for tests: primordials.audit() returns
// { name, holder, kind, key, value, available } for every engine entry, straight
// from JSC, and primordials.object is the module object. Every check below iterates
// the whole manifest instead of a hand-picked subset.
//
// Everything a child script does after it starts tampering must itself be immune
// to the tampering: helpers are captured in the prelude, loops are index-based (no
// array iterators), descriptors are null-prototype objects, and reports are built
// with the captured JSON.stringify.

const prelude = /* js */ `
  const { primordials } = require("bun:internal-for-testing");
  const audit = primordials.audit;
  const write = process.stdout.write.bind(process.stdout);
  const exit = process.exit.bind(process);
  const stringify = JSON.stringify;
  const report = (obj) => write(stringify(obj) + "\\n");
  // For the tampering scenarios: Bun's own builtin JS is not primordial-hardened
  // yet, so a normal shutdown after tampering can throw; report, then exit.
  const reportAndExit = (obj) => { report(obj); exit(0); };
  const globalObject = globalThis;
  const ownDesc = Object.getOwnPropertyDescriptor;
  const getProto = Object.getPrototypeOf;
  const setProto = Object.setPrototypeOf;
  const defineProperty = Object.defineProperty;
  const seal = Object.seal;
  const freeze = Object.freeze;
  const objectKeys = Object.keys;
  const ownKeys = Reflect.ownKeys;
  const reflectSet = Reflect.set;
  const $apply = Reflect.apply;
  const protoOf = f => getProto(f());
  const TypedArray = getProto(Uint8Array);
  const holderFactories = {
    GlobalObject: () => globalObject,
    ObjectPrototype: () => Object.prototype,
    ObjectConstructor: () => Object,
    FunctionPrototype: () => Function.prototype,
    FunctionConstructor: () => Function,
    ArrayPrototype: () => Array.prototype,
    ArrayConstructor: () => Array,
    StringPrototype: () => String.prototype,
    StringConstructor: () => String,
    RegExpPrototype: () => RegExp.prototype,
    RegExpConstructor: () => RegExp,
    SymbolPrototype: () => Symbol.prototype,
    SymbolConstructor: () => Symbol,
    BigIntPrototype: () => BigInt.prototype,
    BigIntConstructor: () => BigInt,
    PromisePrototype: () => Promise.prototype,
    PromiseConstructor: () => Promise,
    IteratorPrototype: () => Iterator.prototype,
    IteratorConstructor: () => Iterator,
    ArrayIteratorPrototype: () => protoOf(() => [][Symbol.iterator]()),
    StringIteratorPrototype: () => protoOf(() => ""[Symbol.iterator]()),
    MapIteratorPrototype: () => protoOf(() => new Map()[Symbol.iterator]()),
    SetIteratorPrototype: () => protoOf(() => new Set()[Symbol.iterator]()),
    RegExpStringIteratorPrototype: () => protoOf(() => "a".matchAll(/a/g)),
    IteratorHelperPrototype: () => protoOf(() => [].values().map(x => x)),
    WrapForValidIteratorPrototype: () => protoOf(() => Iterator.from({ next() { return { done: true }; } })),
    AsyncIteratorPrototype: () => getProto(getProto(async function* () {}).prototype),
    GeneratorFunctionPrototype: () => getProto(function* () {}),
    AsyncFunctionPrototype: () => getProto(async function () {}),
    AsyncGeneratorFunctionPrototype: () => getProto(async function* () {}),
    WeakRefPrototype: () => WeakRef.prototype,
    WeakRefConstructor: () => WeakRef,
    FinalizationRegistryPrototype: () => FinalizationRegistry.prototype,
    FinalizationRegistryConstructor: () => FinalizationRegistry,
    BooleanPrototype: () => Boolean.prototype,
    BooleanConstructor: () => Boolean,
    NumberPrototype: () => Number.prototype,
    NumberConstructor: () => Number,
    DatePrototype: () => Date.prototype,
    DateConstructor: () => Date,
    ErrorPrototype: () => Error.prototype,
    ErrorConstructor: () => Error,
    MapPrototype: () => Map.prototype,
    MapConstructor: () => Map,
    SetPrototype: () => Set.prototype,
    SetConstructor: () => Set,
    WeakMapPrototype: () => WeakMap.prototype,
    WeakMapConstructor: () => WeakMap,
    WeakSetPrototype: () => WeakSet.prototype,
    WeakSetConstructor: () => WeakSet,
    ArrayBufferPrototype: () => ArrayBuffer.prototype,
    ArrayBufferConstructor: () => ArrayBuffer,
    TypedArrayPrototype: () => TypedArray.prototype,
    TypedArrayConstructor: () => TypedArray,
    DataViewPrototype: () => DataView.prototype,
    DataViewConstructor: () => DataView,
    MathObject: () => Math,
    JSONObject: () => JSON,
    ReflectObject: () => Reflect,
    AtomicsObject: () => Atomics,
    ProxyObject: () => Proxy,
  };
  const nativeErrors = ["AggregateError","EvalError","RangeError","ReferenceError","SyntaxError","TypeError","URIError"];
  const typedArrays = ["Int8Array","Uint8Array","Uint8ClampedArray","Int16Array","Uint16Array","Int32Array","Uint32Array","Float16Array","Float32Array","Float64Array","BigInt64Array","BigUint64Array"];
  for (let i = 0; i < nativeErrors.length; i++) {
    const name = nativeErrors[i], ctor = globalThis[name];
    holderFactories[name + "Constructor"] = () => ctor;
    holderFactories[name + "Prototype"] = () => ctor.prototype;
  }
  for (let i = 0; i < typedArrays.length; i++) {
    const name = typedArrays[i], ctor = globalThis[name];
    holderFactories[name + "Constructor"] = () => ctor;
    holderFactories[name + "Prototype"] = () => ctor.prototype;
  }
  const holderNames = objectKeys(holderFactories);
  // Resolved lazily (some tests must not touch holders early) and memoized.
  const holderObjects = { __proto__: null };
  function resolveHolder(name) {
    if (!(name in holderObjects)) holderObjects[name] = holderFactories[name]();
    return holderObjects[name];
  }
  function resolveAllHolders() { for (let i = 0; i < holderNames.length; i++) resolveHolder(holderNames[i]); }
  // The entry's current value read the way user code reads it.
  function liveValue(row) {
    const holder = resolveHolder(row.holder);
    if (row.kind === "Self") return holder;
    const desc = ownDesc(holder, row.key);
    if (!desc) return undefined;
    return row.kind === "Getter" ? desc.get : row.kind === "Setter" ? desc.set : desc.value;
  }
`;

// Node's per-context primordials construction algorithm, by value, for a fresh
// realm (mirrors lib/internal/per_context/primordials.js). Evaluating it in a
// pristine vm context yields a reference object built Node's way; the differential
// test compares every member of the generated module against it.
const referenceBuilderSource = /* js */ `
  "use strict";
  const primordials = { __proto__: null };
  const { defineProperty, getOwnPropertyDescriptor, ownKeys, getPrototypeOf } = Reflect;
  const { apply, bind, call } = Function.prototype;
  const uncurryThis = bind.bind(call);
  primordials.uncurryThis = uncurryThis;
  const applyBind = bind.bind(apply);
  primordials.applyBind = applyBind;
  const varargsMethods = ["ArrayOf","ArrayPrototypePush","ArrayPrototypeUnshift","MathHypot","MathMax","MathMin","StringFromCharCode","StringFromCodePoint","StringPrototypeConcat","TypedArrayOf"];
  const getNewKey = key => typeof key === "symbol"
    ? "Symbol" + key.description[7].toUpperCase() + key.description.slice(8)
    : key[0].toUpperCase() + key.slice(1);
  const copyAccessor = (dest, prefix, key, { enumerable, get, set }) => {
    defineProperty(dest, prefix + "Get" + key, { __proto__: null, value: uncurryThis(get), enumerable });
    if (set !== undefined) defineProperty(dest, prefix + "Set" + key, { __proto__: null, value: uncurryThis(set), enumerable });
  };
  const copyPropsRenamed = (src, dest, prefix) => {
    for (const key of ownKeys(src)) {
      const newKey = getNewKey(key);
      const desc = getOwnPropertyDescriptor(src, key);
      if ("get" in desc) copyAccessor(dest, prefix, newKey, desc);
      else {
        const name = prefix + newKey;
        defineProperty(dest, name, { __proto__: null, ...desc });
        if (varargsMethods.includes(name)) defineProperty(dest, name + "Apply", { __proto__: null, value: applyBind(desc.value, src) });
      }
    }
  };
  const copyPropsRenamedBound = (src, dest, prefix) => {
    for (const key of ownKeys(src)) {
      const newKey = getNewKey(key);
      const desc = getOwnPropertyDescriptor(src, key);
      if ("get" in desc) copyAccessor(dest, prefix, newKey, desc);
      else {
        const { value } = desc;
        if (typeof value === "function") desc.value = value.bind(src);
        const name = prefix + newKey;
        defineProperty(dest, name, { __proto__: null, ...desc });
        if (varargsMethods.includes(name)) defineProperty(dest, name + "Apply", { __proto__: null, value: applyBind(value, src) });
      }
    }
  };
  const copyPrototype = (src, dest, prefix) => {
    for (const key of ownKeys(src)) {
      const newKey = getNewKey(key);
      const desc = getOwnPropertyDescriptor(src, key);
      if ("get" in desc) copyAccessor(dest, prefix, newKey, desc);
      else {
        const { value } = desc;
        if (typeof value === "function") desc.value = uncurryThis(value);
        const name = prefix + newKey;
        defineProperty(dest, name, { __proto__: null, ...desc });
        if (varargsMethods.includes(name)) defineProperty(dest, name + "Apply", { __proto__: null, value: applyBind(value) });
      }
    }
  };
  ["Proxy", "globalThis"].forEach(name => { primordials[name] = globalThis[name]; });
  [decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, eval, unescape].forEach(fn => { primordials[fn.name] = fn; });
  ["Atomics", "JSON", "Math", "Proxy", "Reflect"].forEach(name => { copyPropsRenamed(globalThis[name], primordials, name); });
  ["AggregateError","Array","ArrayBuffer","BigInt","BigInt64Array","BigUint64Array","Boolean","DataView","Date","Error","EvalError","FinalizationRegistry","Float32Array","Float64Array","Function","Int16Array","Int32Array","Int8Array","Iterator","Map","Number","Object","RangeError","ReferenceError","RegExp","Set","String","Symbol","SyntaxError","TypeError","URIError","Uint16Array","Uint32Array","Uint8Array","Uint8ClampedArray","WeakMap","WeakRef","WeakSet"].forEach(name => {
    const original = globalThis[name];
    primordials[name] = original;
    copyPropsRenamed(original, primordials, name);
    copyPrototype(original.prototype, primordials, name + "Prototype");
  });
  ["Promise"].forEach(name => {
    const original = globalThis[name];
    primordials[name] = original;
    copyPropsRenamedBound(original, primordials, name);
    copyPrototype(original.prototype, primordials, name + "Prototype");
  });
  [{ name: "TypedArray", original: getPrototypeOf(Uint8Array) }].forEach(({ name, original }) => {
    primordials[name] = original;
    copyPrototype(original, primordials, name);
    copyPrototype(original.prototype, primordials, name + "Prototype");
  });
  [
    { name: "ArrayIteratorPrototype", original: getPrototypeOf(Array.prototype[Symbol.iterator]()) },
    { name: "AsyncFunctionPrototype", original: getPrototypeOf(async function () {}) },
    { name: "AsyncGeneratorFunctionPrototype", original: getPrototypeOf(async function* () {}) },
    { name: "AsyncIteratorPrototype", original: getPrototypeOf(getPrototypeOf(async function* () {}).prototype) },
    { name: "GeneratorFunctionPrototype", original: getPrototypeOf(function* () {}) },
    { name: "IteratorHelperPrototype", original: getPrototypeOf(primordials.IteratorPrototypeDrop({ __proto__: null }, null)) },
    { name: "MapIteratorPrototype", original: getPrototypeOf(new primordials.Map()[Symbol.iterator]()) },
    { name: "RegExpStringIteratorPrototype", original: getPrototypeOf(primordials.RegExp.prototype[Symbol.matchAll]()) },
    { name: "SetIteratorPrototype", original: getPrototypeOf(new primordials.Set()[Symbol.iterator]()) },
    { name: "StringIteratorPrototype", original: getPrototypeOf(String.prototype[Symbol.iterator]()) },
    { name: "WrapForValidIteratorPrototype", original: getPrototypeOf(primordials.IteratorFrom({ __proto__: null })) },
  ].forEach(({ name, original }) => {
    primordials[name] = original;
    copyPrototype(original, primordials, name);
  });
  primordials
`;

async function runChild(body: string, env: Record<string, string | undefined> = {}) {
  await using proc = Bun.spawn({
    cmd: [bunExe(), "-e", prelude + body],
    env: { ...bunEnv, ...env },
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([proc.stdout.text(), proc.stderr.text(), proc.exited]);
  return { stdout, stderr, exitCode };
}

describe.concurrent("primordials manifest", () => {
  test("engine table covers every holder, materializes every entry", async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const rows = audit();
      const unknownHolders = [], unavailable = [], missingKeys = [];
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        if (!(row.holder in holderFactories)) unknownHolders[unknownHolders.length] = row.holder;
        if (!row.available) unavailable[unavailable.length] = row.name;
        if (row.kind !== "Self" && row.key === null) missingKeys[missingKeys.length] = row.name;
      }
      report({ count: rows.length, unknownHolders, unavailable, missingKeys });
    `);
    expect(stderr).toBe("");
    const report = JSON.parse(stdout);
    expect(report).toEqual({ count: report.count, unknownHolders: [], unavailable: [], missingKeys: [] });
    expect(report.count).toBeGreaterThan(600);
    expect(exitCode).toBe(0);
  });

  test("src/js/primordials.d.ts is in sync with the engine's entries", async () => {
    // The .d.ts is generated (src/codegen/generate-primordials.ts); this catches a
    // WebKit upgrade whose builtin surface changed without a regeneration.
    const dts = await Bun.file(new URL("../../../../src/js/primordials.d.ts", import.meta.url)).text();
    const declared = [...dts.matchAll(/^declare const \$(\w+):/gm)].map(m => m[1]).sort();
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const rows = audit();
      const names = [];
      for (let i = 0; i < rows.length; i++) names[i] = rows[i].name;
      names.sort();
      report({ names });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout).names).toEqual(declared);
    expect(exitCode).toBe(0);
  });

  test("internal/primordials has exactly Node's members for this engine", async () => {
    // Run Node's construction algorithm against this engine's pristine intrinsics
    // (the generator's probe) and require the module's member set to equal it.
    const probe = await Bun.file(
      new URL("../../../../src/codegen/generate-primordials-probe.js", import.meta.url),
    ).text();
    await using probeProc = Bun.spawn({
      cmd: [bunExe(), "-e", probe],
      env: bunEnv,
      stdout: "pipe",
      stderr: "pipe",
    });
    const [probeOut, probeErr, probeExit] = await Promise.all([
      probeProc.stdout.text(),
      probeProc.stderr.text(),
      probeProc.exited,
    ]);
    expect(probeErr).toBe("");
    expect(probeExit).toBe(0);
    // The helper members are exactly the `primordials.X = ...` assignments in the
    // module epilogue; read them from source instead of a hand-maintained list.
    const epilogue = await Bun.file(
      new URL("../../../../src/codegen/primordials-module-epilogue.js", import.meta.url),
    ).text();
    const helpers = [...epilogue.matchAll(/^primordials\.(\w+) = /gm)].map(m => m[1]);
    expect(helpers.length).toBeGreaterThan(15);
    const expected = new Set([...JSON.parse(probeOut).entries.map((e: { name: string }) => e.name), ...helpers]);
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const names = ownKeys(primordials.object);
      const list = [];
      for (let i = 0; i < names.length; i++) list[i] = names[i];
      report({ list, frozen: Object.isFrozen(primordials.object), proto: getProto(primordials.object) === null });
    `);
    expect(stderr).toBe("");
    const report = JSON.parse(stdout);
    const actual = new Set<string>(report.list);
    expect({
      missing: [...expected].filter(n => !actual.has(n)),
      extra: [...actual].filter(n => !expected.has(n)),
    }).toEqual({ missing: [], extra: [] });
    expect(report.frozen).toBe(true);
    expect(report.proto).toBe(true);
    expect(exitCode).toBe(0);
  });

  test("every member matches a reference built the way Node builds it", async () => {
    // Differential oracle: run Node's construction algorithm by value in a fresh
    // realm and compare all members: presence, typeof, function .length (catches
    // receiver-binding/uncurrying mistakes everywhere at once), literal equality.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const vm = require("node:vm");
      const referenceBuilder = ${JSON.stringify(referenceBuilderSource)};
      const reference = vm.runInNewContext(referenceBuilder);
      // Bun customizes its own globals' Error statics (captureStackTrace,
      // stackTraceLimit) at bootstrap and a bare realm doesn't: re-anchor those
      // to this global's values, read here before anything runs.
      const errorKeys = ownKeys(Error);
      for (let i = 0; i < errorKeys.length; i++) {
        const key = errorKeys[i];
        if (typeof key !== "string") continue;
        const name = "Error" + key[0].toUpperCase() + key.slice(1);
        const desc = ownDesc(Error, key);
        if (name in reference && "value" in desc) reference[name] = desc.value;
      }
      const ours = primordials.object;
      const names = ownKeys(reference);
      const differences = [];
      for (let i = 0; i < names.length; i++) {
        const name = names[i];
        if (typeof name !== "string") continue;
        const ref = reference[name], own = ours[name];
        const problem =
          own === undefined && ref !== undefined ? "missing"
          : typeof own !== typeof ref ? "typeof " + typeof own + " vs " + typeof ref
          : typeof ref === "function" && own.length !== ref.length ? "length " + own.length + " vs " + ref.length
          : (typeof ref !== "function" && typeof ref !== "object" && typeof ref !== "symbol" && !(own === ref || (own !== own && ref !== ref)))
            ? "value " + String(own) + " vs " + String(ref)
          : null;
        if (problem) differences[differences.length] = name + ": " + problem;
      }
      report({ compared: names.length, differences });
    `);
    expect(stderr).toBe("");
    const report = JSON.parse(stdout);
    expect(report.differences).toEqual([]);
    expect(report.compared).toBeGreaterThan(800);
    expect(exitCode).toBe(0);
  });

  test("every engine entry is identical to the live builtin in an untouched global", async () => {
    // Materialize first (nothing touched yet), then compare: exercises the lazy
    // link-time path that reifies static properties for identity.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const rows = audit();
      const mismatched = [];
      for (let i = 0; i < rows.length; i++) if (rows[i].value !== liveValue(rows[i])) mismatched[mismatched.length] = rows[i].name;
      report({ mismatched });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({ mismatched: [] });
    expect(exitCode).toBe(0);
  });

  test("identity also holds when the builtins were touched before any primordial linked", async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      // Read every own property of every holder first, like user code that ran earlier.
      resolveAllHolders();
      for (let i = 0; i < holderNames.length; i++) {
        const holder = holderObjects[holderNames[i]];
        const keys = ownKeys(holder);
        for (let k = 0; k < keys.length; k++) ownDesc(holder, keys[k]);
      }
      const rows = audit();
      const mismatched = [];
      for (let i = 0; i < rows.length; i++) if (rows[i].value !== liveValue(rows[i])) mismatched[mismatched.length] = rows[i].name;
      report({ mismatched });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({ mismatched: [] });
    expect(exitCode).toBe(0);
  });
});

describe.concurrent("primordials survive tampering", () => {
  // Snapshot pristine values, tamper with every entry in every listed way, then
  // audit: each primordial must still be the pristine value.
  test("direct and roundabout tampering of every entry after the builtins exist", async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const rows = audit();
      resolveAllHolders();
      const pristine = { __proto__: null };
      for (let i = 0; i < rows.length; i++) pristine[rows[i].name] = rows[i].value;
      const poison = function poisoned() { return "poisoned"; };
      const canaryBefore = holderObjects.ArrayPrototype.push;

      // 1. Plain assignment, Reflect.set, and defineProperty (value + accessor) on every key.
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        if (row.kind === "Self") continue;
        const holder = holderObjects[row.holder];
        const tagged = function tampered() { return "tampered " + row.name; };
        try { holder[row.key] = tagged; } catch {}
        try { reflectSet(holder, row.key, tagged); } catch {}
        try { defineProperty(holder, row.key, { __proto__: null, value: tagged, configurable: true, writable: true }); } catch {}
        try { defineProperty(holder, row.key, { __proto__: null, get() { return "tampered getter " + row.name; }, set() {}, configurable: true }); } catch {}
      }
      // 2. Delete every key and plant the same names where a prototype-chain walk would find them.
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        if (row.kind === "Self") continue;
        try { delete holderObjects[row.holder][row.key]; } catch {}
        try { defineProperty(Object.prototype, row.key, { __proto__: null, value: poison, configurable: true, writable: true }); } catch {}
        try { defineProperty(Function.prototype, row.key, { __proto__: null, value: poison, configurable: true, writable: true }); } catch {}
      }
      // 3. Structural attacks on the holders themselves.
      for (let i = 0; i < holderNames.length; i++) {
        const holder = holderObjects[holderNames[i]];
        if (holder === globalObject) continue;
        try { setProto(holder, { __proto__: null, get poisonedProto() { return "poisoned proto"; } }); } catch {}
        try { holder.constructor = poison; } catch {}
        try { seal(holder); } catch {}
        try { freeze(holder); } catch {}
      }
      // 4. Replace the global bindings themselves.
      const globals = ["Object","Function","Array","String","RegExp","Symbol","BigInt","Promise","Iterator","WeakRef","FinalizationRegistry",
                       "Boolean","Date","Error","Map","Number","Set","WeakMap","WeakSet","ArrayBuffer","DataView","Uint8Array",
                       "Math","JSON","Reflect","Atomics","Proxy","AggregateError","TypeError","RangeError",
                       "escape","unescape","decodeURI","decodeURIComponent","encodeURI","encodeURIComponent","eval","globalThis"];
      for (let i = 0; i < globals.length; i++) {
        try { defineProperty(globalThis, globals[i], { __proto__: null, value: poison, configurable: true, writable: true }); } catch {}
      }

      const after = audit();
      // String accumulator + null-prototype report: JSON.stringify would otherwise
      // observe the toJSON planted on Object.prototype (spec-correct behavior).
      let changed = "";
      for (let i = 0; i < after.length; i++) if (after[i].value !== pristine[after[i].name]) changed += (changed ? "," : "") + after[i].name;
      reportAndExit({ __proto__: null, changed, tampered: holderObjects.ArrayPrototype.push !== canaryBefore });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({ changed: "", tampered: true });
    expect(exitCode).toBe(0);
  });

  test("pollution planted before any lazy holder exists is never captured", async () => {
    // Nothing has touched Map/Set/Date/typed arrays/Math/JSON/... yet in this
    // process, so this targets the lazy creation snapshots and the static-table
    // materialization path.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const planted = [];
      function plant(target, key, fn) {
        planted[planted.length] = fn;
        try { defineProperty(target, key, { __proto__: null, value: fn, configurable: true, writable: true }); } catch {}
      }
      // Every kind of primordial key, planted on the chain a naive lookup would walk.
      const keys = ["hasOwnProperty","toString","valueOf","assign","keys","freeze","apply","bind","call","push","map","slice",
                    "charAt","split","exec","test","get","set","has","size","now","parse","stringify","abs","max","ownKeys",
                    "add","load","then","catch","from","of","for","keyFor","asIntN","next","register","deref","drop",
                    "toArray","getBigInt64","byteLength","buffer","length","subarray","escape","decodeURI",
                    "encodeURIComponent","description","isRawJSON","rawJSON","captureStackTrace","isError","groupBy",
                    "prototype","constructor","input","lastMatch","revocable","name","message"];
      for (let i = 0; i < keys.length; i++) {
        plant(Object.prototype, keys[i], function plantedOnObject() { return "planted"; });
        plant(Function.prototype, keys[i], function plantedOnFunction() { return "planted"; });
      }
      // Replace / redefine namespace and constructor bindings before their first use.
      plant(globalThis, "Math", { max: () => "planted" });
      plant(globalThis, "Reflect", new Proxy({}, { get: () => () => "planted" }));
      delete globalThis.JSON;
      globalThis.Atomics = { load: () => "planted" };
      globalThis.Proxy = function planted() { return "planted"; };
      const ctors = ["Map","Set","WeakMap","WeakSet","Date","Error","TypeError","Number","Boolean","ArrayBuffer","DataView","WeakRef","FinalizationRegistry","Int8Array","Float32Array"];
      for (let i = 0; i < ctors.length; i++) plant(globalThis, ctors[i], function plantedCtor() { return "planted"; });

      const rows = audit();
      const captured = [], unavailable = [];
      for (let i = 0; i < rows.length; i++) {
        if (!rows[i].available) unavailable[unavailable.length] = rows[i].name;
        for (let p = 0; p < planted.length; p++) if (rows[i].value === planted[p]) captured[captured.length] = rows[i].name;
      }
      const value = { __proto__: null };
      for (let i = 0; i < rows.length; i++) value[rows[i].name] = rows[i].value;
      // Behavioral spot checks on the lazily-created holders, using receivers that
      // don't depend on the replaced globals.
      const behavior = {
        MathMax: value.MathMax(1, 5, 3),
        ReflectOwnKeys: value.ReflectOwnKeys({ a: 1 }).length,
        JSONStringify: value.JSONStringify({ a: 1 }),
        AtomicsLoad: value.AtomicsLoad(new Int32Array(1), 0),
        DateNow: typeof value.DateNow(),
        NumberIsInteger: value.NumberIsInteger(3),
        ErrorIsError: value.ErrorIsError(new (value.TypeError)("x")) === true && value.ErrorIsError({}) === false,
        ProxyRevocable: typeof value.ProxyRevocable({}, {}).revoke,
        MapRoundtrip: $apply(value.MapPrototypeGet, $apply(value.MapPrototypeSet, new (primordials.object.Map)(), ["k", "v"]), ["k"]),
      };
      reportAndExit({ captured, unavailable, behavior });
    `);
    expect(stderr).toBe("");
    const report = JSON.parse(stdout);
    expect(report.captured).toEqual([]);
    expect(report.unavailable).toEqual([]);
    expect(report.behavior).toEqual({
      MathMax: 5,
      ReflectOwnKeys: 1,
      JSONStringify: '{"a":1}',
      AtomicsLoad: 0,
      DateNow: "number",
      NumberIsInteger: true,
      ErrorIsError: true,
      ProxyRevocable: "function",
      MapRoundtrip: "v",
    });
    expect(exitCode).toBe(0);
  });

  test("primitive-valued global bindings before first use don't break materialization", async () => {
    // Namespace/constructor bindings replaced with non-objects before anything links:
    // the holders must be recreated pristine instead of downcasting a primitive.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      globalThis.Math = 5;
      globalThis.JSON = 0;
      globalThis.Reflect = undefined;
      globalThis.Atomics = "atomics";
      globalThis.Proxy = null;
      globalThis.Map = false;
      globalThis.Error = 1;
      const rows = audit();
      const unavailable = [];
      for (let i = 0; i < rows.length; i++) if (!rows[i].available) unavailable[unavailable.length] = rows[i].name;
      const value = { __proto__: null };
      for (let i = 0; i < rows.length; i++) value[rows[i].name] = rows[i].value;
      reportAndExit({
        unavailable,
        MathMax: value.MathMax(1, 5, 3),
        JSONStringify: value.JSONStringify({ a: 1 }),
        ReflectHas: value.ReflectHas({ a: 1 }, "a"),
        AtomicsLoad: value.AtomicsLoad(new Int32Array(1), 0),
        ErrorIsError: value.ErrorIsError(new (value.TypeError)("x")),
        ProxyRevocable: typeof value.ProxyRevocable,
      });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({
      unavailable: [],
      MathMax: 5,
      JSONStringify: '{"a":1}',
      ReflectHas: true,
      AtomicsLoad: 0,
      ErrorIsError: true,
      ProxyRevocable: "function",
    });
    expect(exitCode).toBe(0);
  });

  test("a foreign realm's builtin functions are never adopted, even installed before first link", async () => {
    // Same builtin pointer, different global: the identity check for a reified
    // static-table property must also compare realms.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const vm = require("node:vm");
      const foreign = vm.runInNewContext("({ push: Array.prototype.push, getTime: Date.prototype.getTime, mathMax: Math.max })");
      Array.prototype.push = foreign.push;
      Date.prototype.getTime = foreign.getTime;
      Math.max = foreign.mathMax;
      const rows = audit();
      const byName = { __proto__: null }, unavailable = [];
      for (let i = 0; i < rows.length; i++) {
        byName[rows[i].name] = rows[i].value;
        if (!rows[i].available) unavailable[unavailable.length] = rows[i].name;
      }
      const arr = [];
      $apply(byName.ArrayPrototypePush, arr, [1]);
      reportAndExit({
        unavailable,
        pushForeign: byName.ArrayPrototypePush === foreign.push,
        getTimeForeign: byName.DatePrototypeGetTime === foreign.getTime,
        mathMaxForeign: byName.MathMax === foreign.mathMax,
        pushWorks: arr.length,
        mathMax: byName.MathMax(1, 5, 3),
      });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({
      unavailable: [],
      pushForeign: false,
      getTimeForeign: false,
      mathMaxForeign: false,
      pushWorks: 1,
      mathMax: 5,
    });
    expect(exitCode).toBe(0);
  });

  test("a foreign realm's namespace objects are never adopted as this realm's holders", async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const vm = require("node:vm");
      const foreign = vm.runInNewContext("({ Math, JSON, Reflect, Atomics, Proxy })");
      globalThis.Math = foreign.Math;
      globalThis.JSON = foreign.JSON;
      globalThis.Reflect = foreign.Reflect;
      globalThis.Atomics = foreign.Atomics;
      globalThis.Proxy = foreign.Proxy;
      const rows = audit();
      const value = { __proto__: null };
      const unavailable = [];
      for (let i = 0; i < rows.length; i++) {
        value[rows[i].name] = rows[i].value;
        if (!rows[i].available) unavailable[unavailable.length] = rows[i].name;
      }
      reportAndExit({
        unavailable,
        foreign: value.MathMax === foreign.Math.max || value.JSONStringify === foreign.JSON.stringify || value.Proxy === foreign.Proxy,
        MathMax: value.MathMax(1, 5, 3),
        JSONStringify: value.JSONStringify({ a: 1 }),
        ReflectHas: value.ReflectHas({ a: 1 }, "a"),
        AtomicsLoad: value.AtomicsLoad(new Int32Array(1), 0),
        ProxyType: typeof new (value.Proxy)({}, {}),
      });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({
      unavailable: [],
      foreign: false,
      MathMax: 5,
      JSONStringify: '{"a":1}',
      ReflectHas: true,
      AtomicsLoad: 0,
      ProxyType: "object",
    });
    expect(exitCode).toBe(0);
  });

  test("tampered builtins still work through the primordials module", async () => {
    // Behavior, not just identity: use the module's uncurried methods, statics,
    // getters, values, and Safe helpers on receivers created before tampering,
    // after every primordial key on every holder has been replaced.
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const p = primordials.object;
      const map = new Map([["k", "v"]]); const set = new Set([1]); const u8 = new Uint8Array([1, 2, 3, 4]);
      const dv = new DataView(u8.buffer); const date = new Date(0); const re = /b/g; const err = new Error("e");
      const wr = new WeakRef({}); const wm = new WeakMap(); const ws = new WeakSet(); const sym = Symbol("s");
      const promise = Promise.resolve(1);
      // Safe collections take their contents up front too: constructing them from an
      // iterable observes that iterable's protocol (per spec, same as Node).
      const safeMap = new (p.SafeMap)([["a", 1]]); const safeSet = new (p.SafeSet)([1, 2]); const safeString = new (p.SafeStringIterator)("ab");
      const rows = audit();
      resolveAllHolders();
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        if (row.kind === "Self") continue;
        try { defineProperty(holderObjects[row.holder], row.key, { __proto__: null, value() { return "tampered " + row.name; }, configurable: true }); } catch {}
      }
      const results = {
        ArrayPrototypeMap: p.ArrayPrototypeJoin(p.ArrayPrototypeMap([1, 2], x => x * 2), ","),
        ArrayIteratorNext: p.ArrayIteratorPrototypeNext(p.ArrayPrototypeSymbolIterator([7])).value,
        ArrayOfApply: p.ArrayPrototypeJoin(p.ArrayOfApply([1, 2]), "-"),
        StringPrototypeSlice: p.StringPrototypeSlice("hello", 1, 3),
        StringIteratorNext: p.StringIteratorPrototypeNext(p.StringPrototypeSymbolIterator("hi")).value,
        StringPrototypeConcatApply: p.StringPrototypeConcatApply("a", ["b", "c"]),
        ObjectKeys: p.ArrayPrototypeJoin(p.ObjectKeys({ a: 1, b: 2 }), ","),
        ObjectPrototypeHasOwnProperty: p.ObjectPrototypeHasOwnProperty({ a: 1 }, "a"),
        ObjectPrototypeGet__proto__: p.ObjectPrototypeGet__proto__({}) === p.ObjectPrototype,
        FunctionPrototypeCall: p.FunctionPrototypeCall(function () { return this.x; }, { x: 42 }),
        RegExpPrototypeExec: p.RegExpPrototypeExec(re, "abc")[0],
        RegExpPrototypeGetGlobal: p.RegExpPrototypeGetGlobal(re),
        RegExpGetLegacyInput: (p.RegExpPrototypeExec(/(x)/, "ax"), p["RegExpGet$1"](RegExp)),
        SymbolPrototypeGetDescription: p.SymbolPrototypeGetDescription(sym),
        SymbolFor: typeof p.SymbolFor("k"),
        SymbolIteratorValue: typeof p.SymbolIterator,
        BigIntPrototypeToString: p.BigIntPrototypeToString(255n, 16),
        BigIntAsIntN: p.BigIntAsIntN(8, 255n) === -1n,
        PromisePrototypeThen: typeof p.PromisePrototypeThen(promise, x => x),
        PromiseResolveBound: typeof p.PromiseResolve(2),
        MapPrototypeGet: p.MapPrototypeGet(map, "k"),
        MapPrototypeGetSize: p.MapPrototypeGetSize(map),
        SetPrototypeHas: p.SetPrototypeHas(set, 1),
        WeakMapPrototypeHas: p.WeakMapPrototypeHas(wm, {}),
        WeakSetPrototypeHas: p.WeakSetPrototypeHas(ws, {}),
        WeakRefPrototypeDeref: typeof p.WeakRefPrototypeDeref(wr),
        DatePrototypeGetTime: p.DatePrototypeGetTime(date),
        DateNow: typeof p.DateNow(),
        ErrorPrototypeToString: p.ErrorPrototypeToString(err),
        ErrorCaptureStackTrace: (p.ErrorCaptureStackTrace(err), typeof err.stack),
        ErrorIsError: p.ErrorIsError(err),
        NumberPrototypeToFixed: p.NumberPrototypeToFixed(1.25, 1),
        NumberParseInt: p.NumberParseInt("42px"),
        NumberMAX_SAFE_INTEGER: p.NumberMAX_SAFE_INTEGER,
        BooleanPrototypeToString: p.BooleanPrototypeToString(true),
        TypedArrayPrototypeGetLength: p.TypedArrayPrototypeGetLength(u8),
        TypedArrayPrototypeSubarray: p.TypedArrayPrototypeGetLength(p.TypedArrayPrototypeSubarray(u8, 1, 3)),
        Uint8ArrayBYTES_PER_ELEMENT: p.Uint8ArrayBYTES_PER_ELEMENT,
        ArrayBufferPrototypeGetByteLength: p.ArrayBufferPrototypeGetByteLength(p.TypedArrayPrototypeGetBuffer(u8)),
        DataViewPrototypeGetUint8: p.DataViewPrototypeGetUint8(dv, 2),
        MathMax: p.MathMax(1, 5, 3),
        MathMaxApply: p.MathMaxApply([1, 9]),
        MathPI: p.MathPI > 3.14 && p.MathPI < 3.15,
        JSONParse: p.JSONParse("[1,2]").length,
        JSONStringify: p.JSONStringify({ a: 1 }),
        ReflectHas: p.ReflectHas({ a: 1 }, "a"),
        AtomicsAdd: p.AtomicsAdd(new (p.Int32Array)(2), 0, 5),
        encodeURIComponent: p.encodeURIComponent("a b"),
        StringFromCharCode: p.StringFromCharCode(104, 105),
        FinalizationRegistryPrototypeRegister: typeof p.FinalizationRegistryPrototypeRegister(new (p.FinalizationRegistry)(() => {}), {}, 1),
        SafeMapGet: safeMap.get("a"),
        SafeSetHas: safeSet.has(2) && safeSet.size === 2,
        // Safe collections hand out captured safe iterators (Node's intended
        // makeSafe behavior; Node master's wrap condition is dead code), so
        // iterating a SafeSet survives %SetIteratorPrototype%.next tampering.
        SafeSetIterationSurvivesTamper: (() => { try { return [...safeSet].length; } catch { return "threw"; } })(),
        SafeStringIterator: [...safeString].length,
        hardenRegExpSplit: p.ArrayPrototypeJoin(p.StringPrototypeSplit("a-b-c", p.hardenRegExp(/-/)), "|"),
        SafeStringPrototypeSearch: p.SafeStringPrototypeSearch("xyz", /z/),
        uncurryThis: p.uncurryThis(p.MapPrototypeGet.__proto__ ? Map.prototype.has : null) ? true : true,
        applyBind: p.applyBind(p.MathMax)(null, [2, 8]),
      };
      let push = 0; const big = []; for (let i = 0; i < 70000; i++) big[i] = 1;
      const dst = []; p.SafeArrayPrototypePushApply(dst, big); push = dst.length;
      results.SafeArrayPrototypePushApply = push;
      reportAndExit(results);
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({
      ArrayPrototypeMap: "2,4",
      ArrayIteratorNext: 7,
      ArrayOfApply: "1-2",
      StringPrototypeSlice: "el",
      StringIteratorNext: "h",
      StringPrototypeConcatApply: "abc",
      ObjectKeys: "a,b",
      ObjectPrototypeHasOwnProperty: true,
      ObjectPrototypeGet__proto__: true,
      FunctionPrototypeCall: 42,
      RegExpPrototypeExec: "b",
      RegExpPrototypeGetGlobal: true,
      RegExpGetLegacyInput: "x",
      SymbolPrototypeGetDescription: "s",
      SymbolFor: "symbol",
      SymbolIteratorValue: "symbol",
      BigIntPrototypeToString: "ff",
      BigIntAsIntN: true,
      PromisePrototypeThen: "object",
      PromiseResolveBound: "object",
      MapPrototypeGet: "v",
      MapPrototypeGetSize: 1,
      SetPrototypeHas: true,
      WeakMapPrototypeHas: false,
      WeakSetPrototypeHas: false,
      WeakRefPrototypeDeref: "object",
      DatePrototypeGetTime: 0,
      DateNow: "number",
      ErrorPrototypeToString: "Error: e",
      ErrorCaptureStackTrace: "string",
      ErrorIsError: true,
      NumberPrototypeToFixed: "1.3",
      NumberParseInt: 42,
      NumberMAX_SAFE_INTEGER: 9007199254740991,
      BooleanPrototypeToString: "true",
      TypedArrayPrototypeGetLength: 4,
      TypedArrayPrototypeSubarray: 2,
      Uint8ArrayBYTES_PER_ELEMENT: 1,
      ArrayBufferPrototypeGetByteLength: 4,
      DataViewPrototypeGetUint8: 3,
      MathMax: 5,
      MathMaxApply: 9,
      MathPI: true,
      JSONParse: 2,
      JSONStringify: '{"a":1}',
      ReflectHas: true,
      AtomicsAdd: 0,
      encodeURIComponent: "a%20b",
      StringFromCharCode: "hi",
      FinalizationRegistryPrototypeRegister: "undefined",
      SafeMapGet: 1,
      SafeSetHas: true,
      SafeSetIterationSurvivesTamper: 2,
      SafeStringIterator: 2,
      hardenRegExpSplit: "a|b|c",
      SafeStringPrototypeSearch: 2,
      uncurryThis: true,
      applyBind: 8,
      SafeArrayPrototypePushApply: 70000,
    });
    expect(exitCode).toBe(0);
  });
});

describe.concurrent("primordials module load timing", () => {
  // The module loads lazily (first internal require), which can be after user code.
  // Nothing in it may read live objects at load time: the Safe* classes and the
  // hardenRegExp originals must come from pristine constants, not the prototypes.
  test("tampering planted before the module has ever loaded is not captured", async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      RegExp.prototype.exec = function evilExec() { return null; };
      Reflect.defineProperty(RegExp.prototype, Symbol.split, { __proto__: null, value: () => ["evil split"], configurable: true });
      Map.prototype.get = function evilGet() { return "evil get"; };
      Map.prototype.evilExtra = function () { return "evil extra"; };
      Set.prototype.has = () => "evil has";
      WeakMap.prototype.get = () => "evil weak";
      Promise.prototype.then = function () { throw new Error("evil then"); };
      Promise.prototype.finally = function () { throw new Error("evil finally"); };
      // First load of internal/primordials happens now, after the tampering.
      const p = primordials.object;
      const results = {
        SafeMapGet: new p.SafeMap([[1, "ok"]]).get(1),
        SafeMapNoExtra: !("evilExtra" in p.SafeMap.prototype),
        SafeSetHas: new p.SafeSet([2]).has(2),
        SafeWeakMapGet: (() => { const k = {}; return new p.SafeWeakMap([[k, "ok"]]).get(k); })(),
        hardenedExec: p.hardenRegExp(/b/).exec("abc")?.[0],
        hardenedSplit: p.ArrayPrototypeJoin(p.StringPrototypeSplit("a-b", p.hardenRegExp(/-/)), "|"),
      };
      // The combinator drives its inputs and result through the pristine then,
      // never the poisoned Promise.prototype.then. (Elements must be thenables, as
      // in Node.) The result is consumed with the captured PromisePrototypeThen.
      p.PromisePrototypeThen(
        p.SafePromiseAll([p.PromiseResolve(1), p.PromiseResolve(2)]),
        v => reportAndExit({ ...results, SafePromiseAll: v }),
        e => reportAndExit({ ...results, SafePromiseAll: "threw: " + e.message }),
      );
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({
      SafeMapGet: "ok",
      SafeMapNoExtra: true,
      SafeSetHas: true,
      SafeWeakMapGet: "ok",
      hardenedExec: "b",
      hardenedSplit: "a|b",
      SafePromiseAll: [1, 2],
    });
    expect(exitCode).toBe(0);
  });
});

describe.concurrent("primordials configuration", () => {
  test("option-gated builtins that don't exist become throwing placeholders, not crashes or pollution", async () => {
    // JSON.isRawJSON / JSON.rawJSON only exist with --useJSONSourceTextAccess.
    // Turn it off, plant the names on Object.prototype, and touch JSON: the
    // primordials must be "unavailable" throwers rather than the planted functions.
    const { stdout, stderr, exitCode } = await runChild(
      /* js */ `
      const planted = function planted() { return "planted"; };
      Object.prototype.isRawJSON = planted;
      Object.prototype.rawJSON = planted;
      JSON.parse("1");
      const rows = audit();
      const unavailable = [], captured = [];
      for (let i = 0; i < rows.length; i++) {
        if (!rows[i].available) unavailable[unavailable.length] = rows[i].name;
        if (rows[i].value === planted) captured[captured.length] = rows[i].name;
      }
      unavailable.sort();
      let threw = false;
      for (let i = 0; i < rows.length; i++) {
        if (rows[i].name !== "JSONIsRawJSON") continue;
        try { rows[i].value(); } catch (e) { threw = /not available/.test(String(e)); }
      }
      report({ unavailable, captured, threw });
    `,
      { BUN_JSC_useJSONSourceTextAccess: "0" },
    );
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({ unavailable: ["JSONIsRawJSON", "JSONRawJSON"], captured: [], threw: true });
    expect(exitCode).toBe(0);
  });

  // Debug+ASAN Worker startup plus a full audit() regularly exceeds the 5 s default under describe.concurrent.
  test("each Worker global materializes its own primordials", { timeout: 30_000 }, async () => {
    const { stdout, stderr, exitCode } = await runChild(/* js */ `
      const { Worker } = require("node:worker_threads");
      const w = new Worker(
        'Array.prototype.push = () => { throw new Error("worker tampered"); };' +
        'const { primordials } = require("bun:internal-for-testing");' +
        'const rows = primordials.audit();' +
        'let push, unavailable = 0;' +
        'for (let i = 0; i < rows.length; i++) { if (rows[i].name === "ArrayPrototypePush") push = rows[i].value; if (!rows[i].available) unavailable++; }' +
        'const arr = []; push.call(arr, 1, 2);' +
        'require("node:worker_threads").parentPort.postMessage({ len: arr.length, unavailable });',
        { eval: true }
      );
      let posted = false;
      w.on("message", m => { posted = true; write(stringify(m)); w.terminate(); });
      w.on("error", e => { process.stderr.write(String(e)); process.exit(1); });
      w.on("exit", code => { if (!posted) { process.stderr.write("worker exited " + code + " without posting"); process.exit(1); } });
    `);
    expect(stderr).toBe("");
    expect(JSON.parse(stdout)).toEqual({ len: 2, unavailable: 0 });
    expect(exitCode).toBe(0);
  });
});

describe.concurrent("$Name link-time constants in builtin JavaScript", () => {
  // The bundler rewrites $Name to @Name and .$call to a direct call; drive the
  // checked-in probe through a poisoned global to make sure that path is used.
  const probeBody = /* js */ `
    const map = new Map([["k", "v"]]);
    const u8 = new Uint8Array([1, 2, 3, 4]);
    const originalPush = Array.prototype.push;
    if (process.env.TAMPER === "1") {
      Array.prototype.push = () => { throw new Error("tampered"); };
      Array.prototype.slice = () => { throw new Error("tampered"); };
      Array.prototype[Symbol.iterator] = () => { throw new Error("tampered"); };
      String.prototype.slice = () => { throw new Error("tampered"); };
      String.prototype.split = () => { throw new Error("tampered"); };
      Object.keys = () => { throw new Error("tampered"); };
      Object.defineProperty = () => { throw new Error("tampered"); };
      Function.prototype.bind = () => { throw new Error("tampered"); };
      Function.prototype.call = () => { throw new Error("tampered"); };
      Function.prototype.apply = () => { throw new Error("tampered"); };
      RegExp.prototype.test = () => { throw new Error("tampered"); };
      Map.prototype.get = () => { throw new Error("tampered"); };
      Date.now = () => { throw new Error("tampered"); };
      Number.isInteger = () => { throw new Error("tampered"); };
      Math.max = () => { throw new Error("tampered"); };
      Reflect.ownKeys = () => { throw new Error("tampered"); };
      JSON.stringify = () => { throw new Error("tampered"); };
      const TA = Reflect.getPrototypeOf(Uint8Array.prototype);
      TA.subarray = () => { throw new Error("tampered"); };
      defineProperty(Map.prototype, "size", { get() { throw new Error("tampered"); } });
      defineProperty(TA, "length", { get() { throw new Error("tampered"); } });
      defineProperty(DataView.prototype, "byteLength", { get() { throw new Error("tampered"); } });
      defineProperty(RegExp.prototype, "source", { get() { throw new Error("tampered"); } });
      Promise.resolve = () => { throw new Error("tampered"); };
    }
    const out = primordials.run([], "hello", map, u8, /ell/);
    out.tampered = Array.prototype.push !== originalPush;
    reportAndExit(out);
  `;

  const expected = {
    ArrayPrototypePush: 2,
    ArrayPrototypeSlice: [1, 2],
    ArrayPrototypeSymbolIterator: 1,
    StringPrototypeSlice: "el",
    StringPrototypeSplit: ["h", "e", "l", "l", "o"],
    ObjectKeys: ["a", "b"],
    ObjectDefineProperty: 42,
    FunctionPrototypeBind: 8,
    RegExpPrototypeTest: true,
    RegExpPrototypeGetSource: "ell",
    MapPrototypeGet: "v",
    MapPrototypeGetSize: 1,
    DateNow: "number",
    NumberIsInteger: true,
    MathMax: 5,
    ReflectOwnKeys: ["a"],
    JSONStringify: '{"a":1}',
    TypedArrayPrototypeGetLength: 4,
    TypedArrayPrototypeSubarray: 2,
    DataViewPrototypeGetByteLength: 4,
    PromiseResolve: true,
  };

  for (const tamper of [false, true]) {
    test(tamper ? "after tampering" : "untouched", async () => {
      const { stdout, stderr, exitCode } = await runChild(probeBody, { TAMPER: tamper ? "1" : "0" });
      expect(stderr).toBe("");
      expect(JSON.parse(stdout)).toEqual({ ...expected, tampered: tamper });
      expect(exitCode).toBe(0);
    });
  }
});
