const bun = @import("root").bun;
const string = bun.string;
const Output = bun.Output;
const Global = bun.Global;
const Environment = bun.Environment;
const strings = bun.strings;
const MutableString = bun.MutableString;
const stringZ = bun.stringZ;
const default_allocator = bun.default_allocator;
const C = bun.C;
const std = @import("std");
const defines = @import("./defines.zig");

// If something is in this list, then a direct identifier expression or property
// access chain matching this will be assumed to have no side effects and will
// be removed.
//
// This also means code is allowed to be reordered past things in this list. For
// example, if "console.log" is in this list, permitting reordering allows for
// "if (a) console.log(b); else console.log(c)" to be reordered and transformed
// into "console.log(a ? b : c)". Notice that "a" and "console.log" are in a
// different order, which can only happen if evaluating the "console.log"
// property access can be assumed to not change the value of "a".
//
// Note that membership in this list says nothing about whether calling any of
// these functions has any side effects. It only says something about
// referencing these function without calling them.
pub const GlobalDefinesKey = [_][]const string{
    // Object: Static methods
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#Static_methods
    &[_]string{ "Object", "assign" },
    &[_]string{ "Object", "create" },
    &[_]string{ "Object", "defineProperties" },
    &[_]string{ "Object", "defineProperty" },
    &[_]string{ "Object", "entries" },
    &[_]string{ "Object", "freeze" },
    &[_]string{ "Object", "fromEntries" },
    &[_]string{ "Object", "getOwnPropertyDescriptor" },
    &[_]string{ "Object", "getOwnPropertyDescriptors" },
    &[_]string{ "Object", "getOwnPropertyNames" },
    &[_]string{ "Object", "getOwnPropertySymbols" },
    &[_]string{ "Object", "getPrototypeOf" },
    &[_]string{ "Object", "is" },
    &[_]string{ "Object", "isExtensible" },
    &[_]string{ "Object", "isFrozen" },
    &[_]string{ "Object", "isSealed" },
    &[_]string{ "Object", "keys" },
    &[_]string{ "Object", "preventExtensions" },
    &[_]string{ "Object", "seal" },
    &[_]string{ "Object", "setPrototypeOf" },
    &[_]string{ "Object", "values" },

    // Object: Instance methods
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#Instance_methods
    &[_]string{ "Object", "prototype", "__defineGetter__" },
    &[_]string{ "Object", "prototype", "__defineSetter__" },
    &[_]string{ "Object", "prototype", "__lookupGetter__" },
    &[_]string{ "Object", "prototype", "__lookupSetter__" },
    &[_]string{ "Object", "prototype", "hasOwnProperty" },
    &[_]string{ "Object", "prototype", "isPrototypeOf" },
    &[_]string{ "Object", "prototype", "propertyIsEnumerable" },
    &[_]string{ "Object", "prototype", "toLocaleString" },
    &[_]string{ "Object", "prototype", "toString" },
    &[_]string{ "Object", "prototype", "unwatch" },
    &[_]string{ "Object", "prototype", "valueOf" },
    &[_]string{ "Object", "prototype", "watch" },

    // Math: Static properties
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math#Static_properties
    &[_]string{ "Math", "E" },
    &[_]string{ "Math", "LN10" },
    &[_]string{ "Math", "LN2" },
    &[_]string{ "Math", "LOG10E" },
    &[_]string{ "Math", "LOG2E" },
    &[_]string{ "Math", "PI" },
    &[_]string{ "Math", "SQRT1_2" },
    &[_]string{ "Math", "SQRT2" },

    // Math: Static methods
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math#Static_methods
    &[_]string{ "Math", "abs" },
    &[_]string{ "Math", "acos" },
    &[_]string{ "Math", "acosh" },
    &[_]string{ "Math", "asin" },
    &[_]string{ "Math", "asinh" },
    &[_]string{ "Math", "atan" },
    &[_]string{ "Math", "atan2" },
    &[_]string{ "Math", "atanh" },
    &[_]string{ "Math", "cbrt" },
    &[_]string{ "Math", "ceil" },
    &[_]string{ "Math", "clz32" },
    &[_]string{ "Math", "cos" },
    &[_]string{ "Math", "cosh" },
    &[_]string{ "Math", "exp" },
    &[_]string{ "Math", "expm1" },
    &[_]string{ "Math", "floor" },
    &[_]string{ "Math", "fround" },
    &[_]string{ "Math", "hypot" },
    &[_]string{ "Math", "imul" },
    &[_]string{ "Math", "log" },
    &[_]string{ "Math", "log10" },
    &[_]string{ "Math", "log1p" },
    &[_]string{ "Math", "log2" },
    &[_]string{ "Math", "max" },
    &[_]string{ "Math", "min" },
    &[_]string{ "Math", "pow" },
    &[_]string{ "Math", "random" },
    &[_]string{ "Math", "round" },
    &[_]string{ "Math", "sign" },
    &[_]string{ "Math", "sin" },
    &[_]string{ "Math", "sinh" },
    &[_]string{ "Math", "sqrt" },
    &[_]string{ "Math", "tan" },
    &[_]string{ "Math", "tanh" },
    &[_]string{ "Math", "trunc" },

    // Symbol: Static methods
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#static_methods
    &[_]string{ "Symbol", "for" },
    &[_]string{ "Symbol", "keyFor" },

    // Symbol: Static properties
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#static_properties
    &[_]string{ "Symbol", "asyncDispose" },
    &[_]string{ "Symbol", "asyncIterator" },
    &[_]string{ "Symbol", "dispose" },
    &[_]string{ "Symbol", "hasInstance" },
    &[_]string{ "Symbol", "isConcatSpreadable" },
    &[_]string{ "Symbol", "iterator" },
    &[_]string{ "Symbol", "match" },
    &[_]string{ "Symbol", "matchAll" },
    &[_]string{ "Symbol", "replace" },
    &[_]string{ "Symbol", "search" },
    &[_]string{ "Symbol", "species" },
    &[_]string{ "Symbol", "split" },
    &[_]string{ "Symbol", "toPrimitive" },
    &[_]string{ "Symbol", "toStringTag" },
    &[_]string{ "Symbol", "unscopables" },

    // Reflect: Static methods
    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect#static_methods
    &[_]string{ "Reflect", "apply" },
    &[_]string{ "Reflect", "construct" },
    &[_]string{ "Reflect", "defineProperty" },
    &[_]string{ "Reflect", "deleteProperty" },
    &[_]string{ "Reflect", "get" },
    &[_]string{ "Reflect", "getOwnPropertyDescriptor" },
    &[_]string{ "Reflect", "getPrototypeOf" },
    &[_]string{ "Reflect", "has" },
    &[_]string{ "Reflect", "isExtensible" },
    &[_]string{ "Reflect", "ownKeys" },
    &[_]string{ "Reflect", "preventExtensions" },
    &[_]string{ "Reflect", "set" },
    &[_]string{ "Reflect", "setPrototypeOf" },

    // Console method references are assumed to have no side effects
    // https://developer.mozilla.org/en-US/docs/Web/API/console
    &[_]string{ "console", "assert" },
    &[_]string{ "console", "clear" },
    &[_]string{ "console", "count" },
    &[_]string{ "console", "countReset" },
    &[_]string{ "console", "debug" },
    &[_]string{ "console", "dir" },
    &[_]string{ "console", "dirxml" },
    &[_]string{ "console", "error" },
    &[_]string{ "console", "group" },
    &[_]string{ "console", "groupCollapsed" },
    &[_]string{ "console", "groupEnd" },
    &[_]string{ "console", "info" },
    &[_]string{ "console", "log" },
    &[_]string{ "console", "table" },
    &[_]string{ "console", "time" },
    &[_]string{ "console", "timeEnd" },
    &[_]string{ "console", "timeLog" },
    &[_]string{ "console", "trace" },
    &[_]string{ "console", "warn" },

    &[_]string{ "crypto", "randomUUID" },
};

const pure = &defines.IdentifierDefine{
    .valueless = true,
    .can_be_removed_if_unused = true,
    .value = .{ .e_undefined = .{} },
};
const js_ast = bun.JSAst;

const identifiers = struct {
    const nan_val = js_ast.E.Number{ .value = std.math.nan(f64) };

    const inf_val = js_ast.E.Number{ .value = std.math.inf(f64) };

    // Step 2. Swap in certain literal values because those can be constant folded
    pub const @"undefined" = &defines.IdentifierDefine{
        .value = js_ast.Expr.Data{ .e_undefined = .{} },
        .valueless = false,
        .can_be_removed_if_unused = true,
    };
    pub const NaN = &defines.IdentifierDefine{
        .value = js_ast.Expr.Data{ .e_number = nan_val },
    };
    pub const Infinity = &defines.IdentifierDefine{
        .value = js_ast.Expr.Data{ .e_number = inf_val },
    };
};

const GlobalIdentifierDefineValue = enum {
    NaN,
    undefined,
    Infinity,
    pure,

    pub fn get(this: GlobalIdentifierDefineValue) *const defines.IdentifierDefine {
        return switch (this) {
            .NaN => identifiers.NaN,
            .undefined => identifiers.undefined,
            .Infinity => identifiers.Infinity,
            .pure => pure,
        };
    }
};

pub const pure_global_identifiers = [_]struct { []const u8, GlobalIdentifierDefineValue }{
    .{ "NaN", .NaN },
    .{ "Infinity", .Infinity },
    .{ "undefined", .undefined },

    // These global identifiers should exist in all JavaScript environments. This
    // deliberately omits "NaN", "Infinity", and "undefined" because these are
    // treated as automatically-inlined constants instead of identifiers.
    .{ "Array", .pure },
    .{ "Boolean", .pure },
    .{ "Function", .pure },
    .{ "Math", .pure },
    .{ "Number", .pure },
    .{ "Object", .pure },
    .{ "RegExp", .pure },
    .{ "String", .pure },

    // Other globals present in both the browser and node (except "eval" because
    // it has special behavior)
    .{ "AbortController", .pure },
    .{ "AbortSignal", .pure },
    .{ "AggregateError", .pure },
    .{ "ArrayBuffer", .pure },
    .{ "BigInt", .pure },
    .{ "DataView", .pure },
    .{ "Date", .pure },
    .{ "Error", .pure },
    .{ "EvalError", .pure },
    .{ "Event", .pure },
    .{ "EventTarget", .pure },
    .{ "Float16Array", .pure },
    .{ "Float32Array", .pure },
    .{ "Float64Array", .pure },
    .{ "Int16Array", .pure },
    .{ "Int32Array", .pure },
    .{ "Int8Array", .pure },
    .{ "Intl", .pure },
    .{ "JSON", .pure },
    .{ "Map", .pure },
    .{ "MessageChannel", .pure },
    .{ "MessageEvent", .pure },
    .{ "MessagePort", .pure },
    .{ "Promise", .pure },
    .{ "Proxy", .pure },
    .{ "RangeError", .pure },
    .{ "ReferenceError", .pure },
    .{ "Reflect", .pure },
    .{ "Set", .pure },
    .{ "Symbol", .pure },
    .{ "SyntaxError", .pure },
    .{ "TextDecoder", .pure },
    .{ "TextEncoder", .pure },
    .{ "TypeError", .pure },
    .{ "URIError", .pure },
    .{ "URL", .pure },
    .{ "URLSearchParams", .pure },
    .{ "Uint16Array", .pure },
    .{ "Uint32Array", .pure },
    .{ "Uint8Array", .pure },
    .{ "Uint8ClampedArray", .pure },
    .{ "WeakMap", .pure },
    .{ "WeakSet", .pure },
    .{ "WebAssembly", .pure },
    .{ "clearInterval", .pure },
    .{ "clearTimeout", .pure },
    .{ "console", .pure },
    .{ "decodeURI", .pure },
    .{ "decodeURIComponent", .pure },
    .{ "encodeURI", .pure },
    .{ "encodeURIComponent", .pure },
    .{ "escape", .pure },
    .{ "globalThis", .pure },
    .{ "isFinite", .pure },
    .{ "isNaN", .pure },
    .{ "parseFloat", .pure },
    .{ "parseInt", .pure },
    .{ "queueMicrotask", .pure },
    .{ "setInterval", .pure },
    .{ "setTimeout", .pure },
    .{ "unescape", .pure },

    // CSSOM APIs
    .{ "CSSAnimation", .pure },
    .{ "CSSFontFaceRule", .pure },
    .{ "CSSImportRule", .pure },
    .{ "CSSKeyframeRule", .pure },
    .{ "CSSKeyframesRule", .pure },
    .{ "CSSMediaRule", .pure },
    .{ "CSSNamespaceRule", .pure },
    .{ "CSSPageRule", .pure },
    .{ "CSSRule", .pure },
    .{ "CSSRuleList", .pure },
    .{ "CSSStyleDeclaration", .pure },
    .{ "CSSStyleRule", .pure },
    .{ "CSSStyleSheet", .pure },
    .{ "CSSSupportsRule", .pure },
    .{ "CSSTransition", .pure },

    // SVG DOM
    .{ "SVGAElement", .pure },
    .{ "SVGAngle", .pure },
    .{ "SVGAnimateElement", .pure },
    .{ "SVGAnimateMotionElement", .pure },
    .{ "SVGAnimateTransformElement", .pure },
    .{ "SVGAnimatedAngle", .pure },
    .{ "SVGAnimatedBoolean", .pure },
    .{ "SVGAnimatedEnumeration", .pure },
    .{ "SVGAnimatedInteger", .pure },
    .{ "SVGAnimatedLength", .pure },
    .{ "SVGAnimatedLengthList", .pure },
    .{ "SVGAnimatedNumber", .pure },
    .{ "SVGAnimatedNumberList", .pure },
    .{ "SVGAnimatedPreserveAspectRatio", .pure },
    .{ "SVGAnimatedRect", .pure },
    .{ "SVGAnimatedString", .pure },
    .{ "SVGAnimatedTransformList", .pure },
    .{ "SVGAnimationElement", .pure },
    .{ "SVGCircleElement", .pure },
    .{ "SVGClipPathElement", .pure },
    .{ "SVGComponentTransferFunctionElement", .pure },
    .{ "SVGDefsElement", .pure },
    .{ "SVGDescElement", .pure },
    .{ "SVGElement", .pure },
    .{ "SVGEllipseElement", .pure },
    .{ "SVGFEBlendElement", .pure },
    .{ "SVGFEColorMatrixElement", .pure },
    .{ "SVGFEComponentTransferElement", .pure },
    .{ "SVGFECompositeElement", .pure },
    .{ "SVGFEConvolveMatrixElement", .pure },
    .{ "SVGFEDiffuseLightingElement", .pure },
    .{ "SVGFEDisplacementMapElement", .pure },
    .{ "SVGFEDistantLightElement", .pure },
    .{ "SVGFEDropShadowElement", .pure },
    .{ "SVGFEFloodElement", .pure },
    .{ "SVGFEFuncAElement", .pure },
    .{ "SVGFEFuncBElement", .pure },
    .{ "SVGFEFuncGElement", .pure },
    .{ "SVGFEFuncRElement", .pure },
    .{ "SVGFEGaussianBlurElement", .pure },
    .{ "SVGFEImageElement", .pure },
    .{ "SVGFEMergeElement", .pure },
    .{ "SVGFEMergeNodeElement", .pure },
    .{ "SVGFEMorphologyElement", .pure },
    .{ "SVGFEOffsetElement", .pure },
    .{ "SVGFEPointLightElement", .pure },
    .{ "SVGFESpecularLightingElement", .pure },
    .{ "SVGFESpotLightElement", .pure },
    .{ "SVGFETileElement", .pure },
    .{ "SVGFETurbulenceElement", .pure },
    .{ "SVGFilterElement", .pure },
    .{ "SVGForeignObjectElement", .pure },
    .{ "SVGGElement", .pure },
    .{ "SVGGeometryElement", .pure },
    .{ "SVGGradientElement", .pure },
    .{ "SVGGraphicsElement", .pure },
    .{ "SVGImageElement", .pure },
    .{ "SVGLength", .pure },
    .{ "SVGLengthList", .pure },
    .{ "SVGLineElement", .pure },
    .{ "SVGLinearGradientElement", .pure },
    .{ "SVGMPathElement", .pure },
    .{ "SVGMarkerElement", .pure },
    .{ "SVGMaskElement", .pure },
    .{ "SVGMatrix", .pure },
    .{ "SVGMetadataElement", .pure },
    .{ "SVGNumber", .pure },
    .{ "SVGNumberList", .pure },
    .{ "SVGPathElement", .pure },
    .{ "SVGPatternElement", .pure },
    .{ "SVGPoint", .pure },
    .{ "SVGPointList", .pure },
    .{ "SVGPolygonElement", .pure },
    .{ "SVGPolylineElement", .pure },
    .{ "SVGPreserveAspectRatio", .pure },
    .{ "SVGRadialGradientElement", .pure },
    .{ "SVGRect", .pure },
    .{ "SVGRectElement", .pure },
    .{ "SVGSVGElement", .pure },
    .{ "SVGScriptElement", .pure },
    .{ "SVGSetElement", .pure },
    .{ "SVGStopElement", .pure },
    .{ "SVGStringList", .pure },
    .{ "SVGStyleElement", .pure },
    .{ "SVGSwitchElement", .pure },
    .{ "SVGSymbolElement", .pure },
    .{ "SVGTSpanElement", .pure },
    .{ "SVGTextContentElement", .pure },
    .{ "SVGTextElement", .pure },
    .{ "SVGTextPathElement", .pure },
    .{ "SVGTextPositioningElement", .pure },
    .{ "SVGTitleElement", .pure },
    .{ "SVGTransform", .pure },
    .{ "SVGTransformList", .pure },
    .{ "SVGUnitTypes", .pure },
    .{ "SVGUseElement", .pure },
    .{ "SVGViewElement", .pure },

    // Other browser APIs
    //
    // This list contains all globals present in modern versions of Chrome, Safari,
    // and Firefox except for the following properties, since they have a side effect
    // of triggering layout (https://gist.github.com/paulirish/5d52fb081b3570c81e3a):
    //
    //   - scrollX
    //   - scrollY
    //   - innerWidth
    //   - innerHeight
    //   - pageXOffset
    //   - pageYOffset
    //
    // The following globals have also been removed since they sometimes throw an
    // exception when accessed, which is a side effect (for more information see
    // https://stackoverflow.com/a/33047477):
    //
    //   - localStorage
    //   - sessionStorage
    //
    .{ "AnalyserNode", .pure },
    .{ "Animation", .pure },
    .{ "AnimationEffect", .pure },
    .{ "AnimationEvent", .pure },
    .{ "AnimationPlaybackEvent", .pure },
    .{ "AnimationTimeline", .pure },
    .{ "Attr", .pure },
    .{ "Audio", .pure },
    .{ "AudioBuffer", .pure },
    .{ "AudioBufferSourceNode", .pure },
    .{ "AudioDestinationNode", .pure },
    .{ "AudioListener", .pure },
    .{ "AudioNode", .pure },
    .{ "AudioParam", .pure },
    .{ "AudioProcessingEvent", .pure },
    .{ "AudioScheduledSourceNode", .pure },
    .{ "BarProp", .pure },
    .{ "BeforeUnloadEvent", .pure },
    .{ "BiquadFilterNode", .pure },
    .{ "Blob", .pure },
    .{ "BlobEvent", .pure },
    .{ "ByteLengthQueuingStrategy", .pure },
    .{ "CDATASection", .pure },
    .{ "CSS", .pure },
    .{ "CanvasGradient", .pure },
    .{ "CanvasPattern", .pure },
    .{ "CanvasRenderingContext2D", .pure },
    .{ "ChannelMergerNode", .pure },
    .{ "ChannelSplitterNode", .pure },
    .{ "CharacterData", .pure },
    .{ "ClipboardEvent", .pure },
    .{ "CloseEvent", .pure },
    .{ "Comment", .pure },
    .{ "CompositionEvent", .pure },
    .{ "ConvolverNode", .pure },
    .{ "CountQueuingStrategy", .pure },
    .{ "Crypto", .pure },
    .{ "CustomElementRegistry", .pure },
    .{ "CustomEvent", .pure },
    .{ "DOMException", .pure },
    .{ "DOMImplementation", .pure },
    .{ "DOMMatrix", .pure },
    .{ "DOMMatrixReadOnly", .pure },
    .{ "DOMParser", .pure },
    .{ "DOMPoint", .pure },
    .{ "DOMPointReadOnly", .pure },
    .{ "DOMQuad", .pure },
    .{ "DOMRect", .pure },
    .{ "DOMRectList", .pure },
    .{ "DOMRectReadOnly", .pure },
    .{ "DOMStringList", .pure },
    .{ "DOMStringMap", .pure },
    .{ "DOMTokenList", .pure },
    .{ "DataTransfer", .pure },
    .{ "DataTransferItem", .pure },
    .{ "DataTransferItemList", .pure },
    .{ "DelayNode", .pure },
    .{ "Document", .pure },
    .{ "DocumentFragment", .pure },
    .{ "DocumentTimeline", .pure },
    .{ "DocumentType", .pure },
    .{ "DragEvent", .pure },
    .{ "DynamicsCompressorNode", .pure },
    .{ "Element", .pure },
    .{ "ErrorEvent", .pure },
    .{ "EventSource", .pure },
    .{ "File", .pure },
    .{ "FileList", .pure },
    .{ "FileReader", .pure },
    .{ "FocusEvent", .pure },
    .{ "FontFace", .pure },
    .{ "FormData", .pure },
    .{ "GainNode", .pure },
    .{ "Gamepad", .pure },
    .{ "GamepadButton", .pure },
    .{ "GamepadEvent", .pure },
    .{ "Geolocation", .pure },
    .{ "GeolocationPositionError", .pure },
    .{ "HTMLAllCollection", .pure },
    .{ "HTMLAnchorElement", .pure },
    .{ "HTMLAreaElement", .pure },
    .{ "HTMLAudioElement", .pure },
    .{ "HTMLBRElement", .pure },
    .{ "HTMLBaseElement", .pure },
    .{ "HTMLBodyElement", .pure },
    .{ "HTMLButtonElement", .pure },
    .{ "HTMLCanvasElement", .pure },
    .{ "HTMLCollection", .pure },
    .{ "HTMLDListElement", .pure },
    .{ "HTMLDataElement", .pure },
    .{ "HTMLDataListElement", .pure },
    .{ "HTMLDetailsElement", .pure },
    .{ "HTMLDirectoryElement", .pure },
    .{ "HTMLDivElement", .pure },
    .{ "HTMLDocument", .pure },
    .{ "HTMLElement", .pure },
    .{ "HTMLEmbedElement", .pure },
    .{ "HTMLFieldSetElement", .pure },
    .{ "HTMLFontElement", .pure },
    .{ "HTMLFormControlsCollection", .pure },
    .{ "HTMLFormElement", .pure },
    .{ "HTMLFrameElement", .pure },
    .{ "HTMLFrameSetElement", .pure },
    .{ "HTMLHRElement", .pure },
    .{ "HTMLHeadElement", .pure },
    .{ "HTMLHeadingElement", .pure },
    .{ "HTMLHtmlElement", .pure },
    .{ "HTMLIFrameElement", .pure },
    .{ "HTMLImageElement", .pure },
    .{ "HTMLInputElement", .pure },
    .{ "HTMLLIElement", .pure },
    .{ "HTMLLabelElement", .pure },
    .{ "HTMLLegendElement", .pure },
    .{ "HTMLLinkElement", .pure },
    .{ "HTMLMapElement", .pure },
    .{ "HTMLMarqueeElement", .pure },
    .{ "HTMLMediaElement", .pure },
    .{ "HTMLMenuElement", .pure },
    .{ "HTMLMetaElement", .pure },
    .{ "HTMLMeterElement", .pure },
    .{ "HTMLModElement", .pure },
    .{ "HTMLOListElement", .pure },
    .{ "HTMLObjectElement", .pure },
    .{ "HTMLOptGroupElement", .pure },
    .{ "HTMLOptionElement", .pure },
    .{ "HTMLOptionsCollection", .pure },
    .{ "HTMLOutputElement", .pure },
    .{ "HTMLParagraphElement", .pure },
    .{ "HTMLParamElement", .pure },
    .{ "HTMLPictureElement", .pure },
    .{ "HTMLPreElement", .pure },
    .{ "HTMLProgressElement", .pure },
    .{ "HTMLQuoteElement", .pure },
    .{ "HTMLScriptElement", .pure },
    .{ "HTMLSelectElement", .pure },
    .{ "HTMLSlotElement", .pure },
    .{ "HTMLSourceElement", .pure },
    .{ "HTMLSpanElement", .pure },
    .{ "HTMLStyleElement", .pure },
    .{ "HTMLTableCaptionElement", .pure },
    .{ "HTMLTableCellElement", .pure },
    .{ "HTMLTableColElement", .pure },
    .{ "HTMLTableElement", .pure },
    .{ "HTMLTableRowElement", .pure },
    .{ "HTMLTableSectionElement", .pure },
    .{ "HTMLTemplateElement", .pure },
    .{ "HTMLTextAreaElement", .pure },
    .{ "HTMLTimeElement", .pure },
    .{ "HTMLTitleElement", .pure },
    .{ "HTMLTrackElement", .pure },
    .{ "HTMLUListElement", .pure },
    .{ "HTMLUnknownElement", .pure },
    .{ "HTMLVideoElement", .pure },
    .{ "HashChangeEvent", .pure },
    .{ "Headers", .pure },
    .{ "History", .pure },
    .{ "IDBCursor", .pure },
    .{ "IDBCursorWithValue", .pure },
    .{ "IDBDatabase", .pure },
    .{ "IDBFactory", .pure },
    .{ "IDBIndex", .pure },
    .{ "IDBKeyRange", .pure },
    .{ "IDBObjectStore", .pure },
    .{ "IDBOpenDBRequest", .pure },
    .{ "IDBRequest", .pure },
    .{ "IDBTransaction", .pure },
    .{ "IDBVersionChangeEvent", .pure },
    .{ "Image", .pure },
    .{ "ImageData", .pure },
    .{ "InputEvent", .pure },
    .{ "IntersectionObserver", .pure },
    .{ "IntersectionObserverEntry", .pure },
    .{ "KeyboardEvent", .pure },
    .{ "KeyframeEffect", .pure },
    .{ "Location", .pure },
    .{ "MediaCapabilities", .pure },
    .{ "MediaElementAudioSourceNode", .pure },
    .{ "MediaEncryptedEvent", .pure },
    .{ "MediaError", .pure },
    .{ "MediaList", .pure },
    .{ "MediaQueryList", .pure },
    .{ "MediaQueryListEvent", .pure },
    .{ "MediaRecorder", .pure },
    .{ "MediaSource", .pure },
    .{ "MediaStream", .pure },
    .{ "MediaStreamAudioDestinationNode", .pure },
    .{ "MediaStreamAudioSourceNode", .pure },
    .{ "MediaStreamTrack", .pure },
    .{ "MediaStreamTrackEvent", .pure },
    .{ "MimeType", .pure },
    .{ "MimeTypeArray", .pure },
    .{ "MouseEvent", .pure },
    .{ "MutationEvent", .pure },
    .{ "MutationObserver", .pure },
    .{ "MutationRecord", .pure },
    .{ "NamedNodeMap", .pure },
    .{ "Navigator", .pure },
    .{ "Node", .pure },
    .{ "NodeFilter", .pure },
    .{ "NodeIterator", .pure },
    .{ "NodeList", .pure },
    .{ "Notification", .pure },
    .{ "OfflineAudioCompletionEvent", .pure },
    .{ "Option", .pure },
    .{ "OscillatorNode", .pure },
    .{ "PageTransitionEvent", .pure },
    .{ "Path2D", .pure },
    .{ "Performance", .pure },
    .{ "PerformanceEntry", .pure },
    .{ "PerformanceMark", .pure },
    .{ "PerformanceMeasure", .pure },
    .{ "PerformanceNavigation", .pure },
    .{ "PerformanceObserver", .pure },
    .{ "PerformanceObserverEntryList", .pure },
    .{ "PerformanceResourceTiming", .pure },
    .{ "PerformanceTiming", .pure },
    .{ "PeriodicWave", .pure },
    .{ "Plugin", .pure },
    .{ "PluginArray", .pure },
    .{ "PointerEvent", .pure },
    .{ "PopStateEvent", .pure },
    .{ "ProcessingInstruction", .pure },
    .{ "ProgressEvent", .pure },
    .{ "PromiseRejectionEvent", .pure },
    .{ "RTCCertificate", .pure },
    .{ "RTCDTMFSender", .pure },
    .{ "RTCDTMFToneChangeEvent", .pure },
    .{ "RTCDataChannel", .pure },
    .{ "RTCDataChannelEvent", .pure },
    .{ "RTCIceCandidate", .pure },
    .{ "RTCPeerConnection", .pure },
    .{ "RTCPeerConnectionIceEvent", .pure },
    .{ "RTCRtpReceiver", .pure },
    .{ "RTCRtpSender", .pure },
    .{ "RTCRtpTransceiver", .pure },
    .{ "RTCSessionDescription", .pure },
    .{ "RTCStatsReport", .pure },
    .{ "RTCTrackEvent", .pure },
    .{ "RadioNodeList", .pure },
    .{ "Range", .pure },
    .{ "ReadableStream", .pure },
    .{ "Request", .pure },
    .{ "ResizeObserver", .pure },
    .{ "ResizeObserverEntry", .pure },
    .{ "Response", .pure },
    .{ "Screen", .pure },
    .{ "ScriptProcessorNode", .pure },
    .{ "SecurityPolicyViolationEvent", .pure },
    .{ "Selection", .pure },
    .{ "ShadowRoot", .pure },
    .{ "SourceBuffer", .pure },
    .{ "SourceBufferList", .pure },
    .{ "SpeechSynthesisEvent", .pure },
    .{ "SpeechSynthesisUtterance", .pure },
    .{ "StaticRange", .pure },
    .{ "Storage", .pure },
    .{ "StorageEvent", .pure },
    .{ "StyleSheet", .pure },
    .{ "StyleSheetList", .pure },
    .{ "Text", .pure },
    .{ "TextMetrics", .pure },
    .{ "TextTrack", .pure },
    .{ "TextTrackCue", .pure },
    .{ "TextTrackCueList", .pure },
    .{ "TextTrackList", .pure },
    .{ "TimeRanges", .pure },
    .{ "TrackEvent", .pure },
    .{ "TransitionEvent", .pure },
    .{ "TreeWalker", .pure },
    .{ "UIEvent", .pure },
    .{ "VTTCue", .pure },
    .{ "ValidityState", .pure },
    .{ "VisualViewport", .pure },
    .{ "WaveShaperNode", .pure },
    .{ "WebGLActiveInfo", .pure },
    .{ "WebGLBuffer", .pure },
    .{ "WebGLContextEvent", .pure },
    .{ "WebGLFramebuffer", .pure },
    .{ "WebGLProgram", .pure },
    .{ "WebGLQuery", .pure },
    .{ "WebGLRenderbuffer", .pure },
    .{ "WebGLRenderingContext", .pure },
    .{ "WebGLSampler", .pure },
    .{ "WebGLShader", .pure },
    .{ "WebGLShaderPrecisionFormat", .pure },
    .{ "WebGLSync", .pure },
    .{ "WebGLTexture", .pure },
    .{ "WebGLUniformLocation", .pure },
    .{ "WebKitCSSMatrix", .pure },
    .{ "WebSocket", .pure },
    .{ "WheelEvent", .pure },
    .{ "Window", .pure },
    .{ "Worker", .pure },
    .{ "XMLDocument", .pure },
    .{ "XMLHttpRequest", .pure },
    .{ "XMLHttpRequestEventTarget", .pure },
    .{ "XMLHttpRequestUpload", .pure },
    .{ "XMLSerializer", .pure },
    .{ "XPathEvaluator", .pure },
    .{ "XPathExpression", .pure },
    .{ "XPathResult", .pure },
    .{ "XSLTProcessor", .pure },
    .{ "alert", .pure },
    .{ "atob", .pure },
    .{ "blur", .pure },
    .{ "btoa", .pure },
    .{ "cancelAnimationFrame", .pure },
    .{ "captureEvents", .pure },
    .{ "close", .pure },
    .{ "closed", .pure },
    .{ "confirm", .pure },
    .{ "customElements", .pure },
    .{ "devicePixelRatio", .pure },
    .{ "document", .pure },
    .{ "event", .pure },
    .{ "fetch", .pure },
    .{ "find", .pure },
    .{ "focus", .pure },
    .{ "frameElement", .pure },
    .{ "frames", .pure },
    .{ "getComputedStyle", .pure },
    .{ "getSelection", .pure },
    .{ "history", .pure },
    .{ "indexedDB", .pure },
    .{ "isSecureContext", .pure },
    .{ "length", .pure },
    .{ "location", .pure },
    .{ "locationbar", .pure },
    .{ "matchMedia", .pure },
    .{ "menubar", .pure },
    .{ "moveBy", .pure },
    .{ "moveTo", .pure },
    .{ "name", .pure },
    .{ "navigator", .pure },
    .{ "onabort", .pure },
    .{ "onafterprint", .pure },
    .{ "onanimationend", .pure },
    .{ "onanimationiteration", .pure },
    .{ "onanimationstart", .pure },
    .{ "onbeforeprint", .pure },
    .{ "onbeforeunload", .pure },
    .{ "onblur", .pure },
    .{ "oncanplay", .pure },
    .{ "oncanplaythrough", .pure },
    .{ "onchange", .pure },
    .{ "onclick", .pure },
    .{ "oncontextmenu", .pure },
    .{ "oncuechange", .pure },
    .{ "ondblclick", .pure },
    .{ "ondrag", .pure },
    .{ "ondragend", .pure },
    .{ "ondragenter", .pure },
    .{ "ondragleave", .pure },
    .{ "ondragover", .pure },
    .{ "ondragstart", .pure },
    .{ "ondrop", .pure },
    .{ "ondurationchange", .pure },
    .{ "onemptied", .pure },
    .{ "onended", .pure },
    .{ "onerror", .pure },
    .{ "onfocus", .pure },
    .{ "ongotpointercapture", .pure },
    .{ "onhashchange", .pure },
    .{ "oninput", .pure },
    .{ "oninvalid", .pure },
    .{ "onkeydown", .pure },
    .{ "onkeypress", .pure },
    .{ "onkeyup", .pure },
    .{ "onlanguagechange", .pure },
    .{ "onload", .pure },
    .{ "onloadeddata", .pure },
    .{ "onloadedmetadata", .pure },
    .{ "onloadstart", .pure },
    .{ "onlostpointercapture", .pure },
    .{ "onmessage", .pure },
    .{ "onmousedown", .pure },
    .{ "onmouseenter", .pure },
    .{ "onmouseleave", .pure },
    .{ "onmousemove", .pure },
    .{ "onmouseout", .pure },
    .{ "onmouseover", .pure },
    .{ "onmouseup", .pure },
    .{ "onoffline", .pure },
    .{ "ononline", .pure },
    .{ "onpagehide", .pure },
    .{ "onpageshow", .pure },
    .{ "onpause", .pure },
    .{ "onplay", .pure },
    .{ "onplaying", .pure },
    .{ "onpointercancel", .pure },
    .{ "onpointerdown", .pure },
    .{ "onpointerenter", .pure },
    .{ "onpointerleave", .pure },
    .{ "onpointermove", .pure },
    .{ "onpointerout", .pure },
    .{ "onpointerover", .pure },
    .{ "onpointerup", .pure },
    .{ "onpopstate", .pure },
    .{ "onprogress", .pure },
    .{ "onratechange", .pure },
    .{ "onrejectionhandled", .pure },
    .{ "onreset", .pure },
    .{ "onresize", .pure },
    .{ "onscroll", .pure },
    .{ "onseeked", .pure },
    .{ "onseeking", .pure },
    .{ "onselect", .pure },
    .{ "onstalled", .pure },
    .{ "onstorage", .pure },
    .{ "onsubmit", .pure },
    .{ "onsuspend", .pure },
    .{ "ontimeupdate", .pure },
    .{ "ontoggle", .pure },
    .{ "ontransitioncancel", .pure },
    .{ "ontransitionend", .pure },
    .{ "ontransitionrun", .pure },
    .{ "ontransitionstart", .pure },
    .{ "onunhandledrejection", .pure },
    .{ "onunload", .pure },
    .{ "onvolumechange", .pure },
    .{ "onwaiting", .pure },
    .{ "onwebkitanimationend", .pure },
    .{ "onwebkitanimationiteration", .pure },
    .{ "onwebkitanimationstart", .pure },
    .{ "onwebkittransitionend", .pure },
    .{ "onwheel", .pure },
    .{ "open", .pure },
    .{ "opener", .pure },
    .{ "origin", .pure },
    .{ "outerHeight", .pure },
    .{ "outerWidth", .pure },
    .{ "parent", .pure },
    .{ "performance", .pure },
    .{ "personalbar", .pure },
    .{ "postMessage", .pure },
    .{ "print", .pure },
    .{ "prompt", .pure },
    .{ "releaseEvents", .pure },
    .{ "requestAnimationFrame", .pure },
    .{ "resizeBy", .pure },
    .{ "resizeTo", .pure },
    .{ "screen", .pure },
    .{ "screenLeft", .pure },
    .{ "screenTop", .pure },
    .{ "screenX", .pure },
    .{ "screenY", .pure },
    .{ "scroll", .pure },
    .{ "scrollBy", .pure },
    .{ "scrollTo", .pure },
    .{ "scrollbars", .pure },
    .{ "self", .pure },
    .{ "speechSynthesis", .pure },
    .{ "status", .pure },
    .{ "statusbar", .pure },
    .{ "stop", .pure },
    .{ "toolbar", .pure },
    .{ "top", .pure },
    .{ "webkitURL", .pure },
    .{ "window", .pure },
    .{ "crypto", .pure },
};

pub const pure_global_identifier_map = bun.ComptimeStringMap(GlobalIdentifierDefineValue, pure_global_identifiers);
