//! Ported from src/test_runner/harness/fixtures.zig

use phf::phf_map;

// Zig: `std.ComptimeStringMap([]u8, .{ ... })` with `@embedFile`.
// TODO(port): Zig source has a duplicate `"simple-component.tsx"` entry (lines 5-6); phf rejects
// duplicate keys at compile time so the second one is dropped here. Verify upstream intent.
pub static FIXTURES: phf::Map<&'static [u8], &'static [u8]> = phf_map! {
    b"package.json" => include_bytes!("./fixtures/package.json"),
    b"tsconfig.json" => include_bytes!("./fixtures/tsconfig.json"),
    b"simple-component.js" => include_bytes!("./fixtures/simple-component.js"),
    b"simple-component.tsx" => include_bytes!("./fixtures/simple-component.tsx"),
};

/// (route file path, file body)
///
/// Zig models these as anonymous-struct literals where each *field name* is the
/// path (`.@"pages/index.js" = "..."`). Callers iterate fields via `@typeInfo`
/// reflection, so the faithful Rust shape is a static `(key, value)` slice.
pub type RouteList = &'static [(&'static [u8], &'static [u8])];

pub static SAMPLE_ROUTE_LIST: RouteList = &[
    (b"pages/[...catch-all-at-root].js", b"//pages/[...catch-all-at-root].js"),
    (b"pages/index.js", b"//pages/index.js"),
    (b"pages/Foo.js", b"//pages/Foo.js"),
    (b"pages/[TitleCaseParam].js", b"//pages/[TitleCaseParam].js"),
    (b"pages/[TitleCaseParam]/file.js", b"//pages/[TitleCaseParam]/file.js"),
    (b"pages/[TitleCaseParam]/[snake_case_param].js", b"//pages/[TitleCaseParam]/[snake_case_param].js"),
    (b"pages/[TitleCaseParam]/[snake_case_param]/file.js", b"//pages/[TitleCaseParam]/[snake_case_param]/file.js"),
    (b"pages/[TitleCaseParam]/[snake_case_param]/bacon/index.js", b"//pages/[TitleCaseParam]/[snake_case_param]/bacon/index.js"),
];

pub static GITHUB_API_ROUTES_LIST: RouteList = &[
    (b"pages/[...catch-all-at-root].js", b"//pages/[...catch-all-at-root].js"),
    (b"pages/index.js", b"//pages/index.js"),
    (b"pages/app.js", b"//pages/app.js"),
    (b"pages/app/installations.js", b"//pages/app/installations.js"),
    (b"pages/app/installations/[installation_id].js", b"//pages/app/installations/[installation_id].js"),
    (b"pages/apps/[app_slug].js", b"//pages/apps/[app_slug].js"),
    (b"pages/codes_of_conduct.js", b"//pages/codes_of_conduct.js"),
    (b"pages/codes_of_conduct/[key].js", b"//pages/codes_of_conduct/[key].js"),
    (b"pages/emojis.js", b"//pages/emojis.js"),
    (b"pages/events.js", b"//pages/events.js"),
    (b"pages/feeds.js", b"//pages/feeds.js"),
    (b"pages/gitignore/templates.js", b"//pages/gitignore/templates.js"),
    (b"pages/gitignore/templates/[name].js", b"//pages/gitignore/templates/[name].js"),
    (b"pages/installation/repositories.js", b"//pages/installation/repositories.js"),
    (b"pages/licenses.js", b"//pages/licenses.js"),
    (b"pages/licenses/[license].js", b"//pages/licenses/[license].js"),
    (b"pages/meta.js", b"//pages/meta.js"),
    (b"pages/networks/[owner]/[repo]/events.js", b"//pages/networks/[owner]/[repo]/events.js"),
    (b"pages/octocat.js", b"//pages/octocat.js"),
    (b"pages/organizations.js", b"//pages/organizations.js"),
    (b"pages/orgs/[org]/index.js", b"//pages/orgs/[org].js"),
    (b"pages/orgs/[org]/actions/permissions.js", b"//pages/orgs/[org]/actions/permissions.js"),
    (b"pages/orgs/[org]/actions/permissions/repositories.js", b"//pages/orgs/[org]/actions/permissions/repositories.js"),
    (b"pages/orgs/[org]/actions/permissions/selected-actions.js", b"//pages/orgs/[org]/actions/permissions/selected-actions.js"),
    (b"pages/orgs/[org]/actions/runner-groups.js", b"//pages/orgs/[org]/actions/runner-groups.js"),
    (b"pages/orgs/[org]/actions/runner-groups/[runner_group_id].js", b"//pages/orgs/[org]/actions/runner-groups/[runner_group_id].js"),
    (b"pages/orgs/[org]/actions/runner-groups/[runner_group_id]/repositories.js", b"//pages/orgs/[org]/actions/runner-groups/[runner_group_id]/repositories.js"),
    (b"pages/orgs/[org]/actions/runner-groups/[runner_group_id]/runners.js", b"//pages/orgs/[org]/actions/runner-groups/[runner_group_id]/runners.js"),
    (b"pages/orgs/[org]/actions/runners.js", b"//pages/orgs/[org]/actions/runners.js"),
    (b"pages/orgs/[org]/actions/runners/[runner_id].js", b"//pages/orgs/[org]/actions/runners/[runner_id].js"),
    (b"pages/orgs/[org]/actions/runners/downloads.js", b"//pages/orgs/[org]/actions/runners/downloads.js"),
    (b"pages/orgs/[org]/actions/secrets.js", b"//pages/orgs/[org]/actions/secrets.js"),
    (b"pages/orgs/[org]/actions/secrets/[secret_name].js", b"//pages/orgs/[org]/actions/secrets/[secret_name].js"),
    (b"pages/orgs/[org]/actions/secrets/[secret_name]/repositories.js", b"//pages/orgs/[org]/actions/secrets/[secret_name]/repositories.js"),
    (b"pages/orgs/[org]/actions/secrets/public-key.js", b"//pages/orgs/[org]/actions/secrets/public-key.js"),
    (b"pages/orgs/[org]/audit-log.js", b"//pages/orgs/[org]/audit-log.js"),
    (b"pages/orgs/[org]/blocks.js", b"//pages/orgs/[org]/blocks.js"),
    (b"pages/orgs/[org]/blocks/[username].js", b"//pages/orgs/[org]/blocks/[username].js"),
    (b"pages/orgs/[org]/credential-authorizations.js", b"//pages/orgs/[org]/credential-authorizations.js"),
    (b"pages/orgs/[org]/events.js", b"//pages/orgs/[org]/events.js"),
    (b"pages/orgs/[org]/external-group/[group_id].js", b"//pages/orgs/[org]/external-group/[group_id].js"),
    (b"pages/orgs/[org]/external-groups.js", b"//pages/orgs/[org]/external-groups.js"),
    (b"pages/orgs/[org]/failed_invitations.js", b"//pages/orgs/[org]/failed_invitations.js"),
    (b"pages/orgs/[org]/hooks.js", b"//pages/orgs/[org]/hooks.js"),
    (b"pages/orgs/[org]/hooks/[hook_id].js", b"//pages/orgs/[org]/hooks/[hook_id].js"),
    (b"pages/orgs/[org]/hooks/[hook_id]/config.js", b"//pages/orgs/[org]/hooks/[hook_id]/config.js"),
    (b"pages/orgs/[org]/hooks/[hook_id]/deliveries.js", b"//pages/orgs/[org]/hooks/[hook_id]/deliveries.js"),
    (b"pages/orgs/[org]/hooks/[hook_id]/deliveries/[delivery_id].js", b"//pages/orgs/[org]/hooks/[hook_id]/deliveries/[delivery_id].js"),
    (b"pages/orgs/[org]/installations.js", b"//pages/orgs/[org]/installations.js"),
    (b"pages/orgs/[org]/interaction-limits.js", b"//pages/orgs/[org]/interaction-limits.js"),
    (b"pages/orgs/[org]/invitations.js", b"//pages/orgs/[org]/invitations.js"),
    (b"pages/orgs/[org]/invitations/[invitation_id]/teams.js", b"//pages/orgs/[org]/invitations/[invitation_id]/teams.js"),
    (b"pages/orgs/[org]/members.js", b"//pages/orgs/[org]/members.js"),
    (b"pages/orgs/[org]/members/[username].js", b"//pages/orgs/[org]/members/[username].js"),
    (b"pages/orgs/[org]/memberships/[username].js", b"//pages/orgs/[org]/memberships/[username].js"),
    (b"pages/orgs/[org]/outside_collaborators.js", b"//pages/orgs/[org]/outside_collaborators.js"),
    (b"pages/orgs/[org]/projects.js", b"//pages/orgs/[org]/projects.js"),
    (b"pages/orgs/[org]/public_members.js", b"//pages/orgs/[org]/public_members.js"),
    (b"pages/orgs/[org]/public_members/[username].js", b"//pages/orgs/[org]/public_members/[username].js"),
    (b"pages/orgs/[org]/repos.js", b"//pages/orgs/[org]/repos.js"),
    (b"pages/orgs/[org]/secret-scanning/alerts.js", b"//pages/orgs/[org]/secret-scanning/alerts.js"),
    (b"pages/orgs/[org]/team-sync/groups.js", b"//pages/orgs/[org]/team-sync/groups.js"),
    (b"pages/orgs/[org]/teams.js", b"//pages/orgs/[org]/teams.js"),
    (b"pages/orgs/[org]/teams/[team_slug].js", b"//pages/orgs/[org]/teams/[team_slug].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions.js", b"//pages/orgs/[org]/teams/[team_slug]/discussions.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number].js", b"//pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments.js", b"//pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments/[comment_number].js", b"//pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments/[comment_number].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments/[comment_number]/reactions.js", b"//pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/comments/[comment_number]/reactions.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/reactions.js", b"//pages/orgs/[org]/teams/[team_slug]/discussions/[discussion_number]/reactions.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/invitations.js", b"//pages/orgs/[org]/teams/[team_slug]/invitations.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/members.js", b"//pages/orgs/[org]/teams/[team_slug]/members.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/memberships/[username].js", b"//pages/orgs/[org]/teams/[team_slug]/memberships/[username].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/projects.js", b"//pages/orgs/[org]/teams/[team_slug]/projects.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/projects/[project_id].js", b"//pages/orgs/[org]/teams/[team_slug]/projects/[project_id].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/repos.js", b"//pages/orgs/[org]/teams/[team_slug]/repos.js"),
    (b"pages/orgs/[org]/teams/[team_slug]/repos/[owner]/[repo].js", b"//pages/orgs/[org]/teams/[team_slug]/repos/[owner]/[repo].js"),
    (b"pages/orgs/[org]/teams/[team_slug]/teams.js", b"//pages/orgs/[org]/teams/[team_slug]/teams.js"),
    (b"pages/projects/[project_id].js", b"//pages/projects/[project_id].js"),
    (b"pages/projects/[project_id]/collaborators.js", b"//pages/projects/[project_id]/collaborators.js"),
    (b"pages/projects/[project_id]/collaborators/[username]/permission.js", b"//pages/projects/[project_id]/collaborators/[username]/permission.js"),
    (b"pages/projects/[project_id]/columns.js", b"//pages/projects/[project_id]/columns.js"),
    (b"pages/projects/columns/[column_id].js", b"//pages/projects/columns/[column_id].js"),
    (b"pages/projects/columns/[column_id]/cards.js", b"//pages/projects/columns/[column_id]/cards.js"),
    (b"pages/projects/columns/cards/[card_id].js", b"//pages/projects/columns/cards/[card_id].js"),
    (b"pages/rate_limit.js", b"//pages/rate_limit.js"),
    (b"pages/repos/[owner]/[repo].js", b"//pages/repos/[owner]/[repo].js"),
    (b"pages/repos/[owner]/[repo]/actions/artifacts.js", b"//pages/repos/[owner]/[repo]/actions/artifacts.js"),
    (b"pages/repos/[owner]/[repo]/actions/artifacts/[artifact_id].js", b"//pages/repos/[owner]/[repo]/actions/artifacts/[artifact_id].js"),
    (b"pages/repos/[owner]/[repo]/actions/artifacts/[artifact_id]/[archive_format].js", b"//pages/repos/[owner]/[repo]/actions/artifacts/[artifact_id]/[archive_format].js"),
    (b"pages/repos/[owner]/[repo]/actions/jobs/[job_id].js", b"//pages/repos/[owner]/[repo]/actions/jobs/[job_id].js"),
    (b"pages/repos/[owner]/[repo]/actions/jobs/[job_id]/logs.js", b"//pages/repos/[owner]/[repo]/actions/jobs/[job_id]/logs.js"),
    (b"pages/repos/[owner]/[repo]/actions/permissions.js", b"//pages/repos/[owner]/[repo]/actions/permissions.js"),
    (b"pages/repos/[owner]/[repo]/actions/permissions/selected-actions.js", b"//pages/repos/[owner]/[repo]/actions/permissions/selected-actions.js"),
    (b"pages/repos/[owner]/[repo]/actions/runners.js", b"//pages/repos/[owner]/[repo]/actions/runners.js"),
    (b"pages/repos/[owner]/[repo]/actions/runners/[runner_id].js", b"//pages/repos/[owner]/[repo]/actions/runners/[runner_id].js"),
    (b"pages/repos/[owner]/[repo]/actions/runners/downloads.js", b"//pages/repos/[owner]/[repo]/actions/runners/downloads.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs.js", b"//pages/repos/[owner]/[repo]/actions/runs.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id].js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id].js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/approvals.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/approvals.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/artifacts.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/artifacts.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number].js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number].js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number]/jobs.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number]/jobs.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number]/logs.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/attempts/[attempt_number]/logs.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/jobs.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/jobs.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/logs.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/logs.js"),
    (b"pages/repos/[owner]/[repo]/actions/runs/[run_id]/pending_deployments.js", b"//pages/repos/[owner]/[repo]/actions/runs/[run_id]/pending_deployments.js"),
    (b"pages/repos/[owner]/[repo]/actions/secrets.js", b"//pages/repos/[owner]/[repo]/actions/secrets.js"),
    (b"pages/repos/[owner]/[repo]/actions/secrets/[secret_name].js", b"//pages/repos/[owner]/[repo]/actions/secrets/[secret_name].js"),
    (b"pages/repos/[owner]/[repo]/actions/secrets/public-key.js", b"//pages/repos/[owner]/[repo]/actions/secrets/public-key.js"),
    (b"pages/repos/[owner]/[repo]/actions/workflows.js", b"//pages/repos/[owner]/[repo]/actions/workflows.js"),
    (b"pages/repos/[owner]/[repo]/actions/workflows/[workflow_id].js", b"//pages/repos/[owner]/[repo]/actions/workflows/[workflow_id].js"),
    (b"pages/repos/[owner]/[repo]/actions/workflows/[workflow_id]/runs.js", b"//pages/repos/[owner]/[repo]/actions/workflows/[workflow_id]/runs.js"),
    (b"pages/repos/[owner]/[repo]/assignees.js", b"//pages/repos/[owner]/[repo]/assignees.js"),
    (b"pages/repos/[owner]/[repo]/assignees/[assignee].js", b"//pages/repos/[owner]/[repo]/assignees/[assignee].js"),
    (b"pages/repos/[owner]/[repo]/autolinks.js", b"//pages/repos/[owner]/[repo]/autolinks.js"),
    (b"pages/repos/[owner]/[repo]/autolinks/[autolink_id].js", b"//pages/repos/[owner]/[repo]/autolinks/[autolink_id].js"),
    (b"pages/repos/[owner]/[repo]/branches.js", b"//pages/repos/[owner]/[repo]/branches.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch].js", b"//pages/repos/[owner]/[repo]/branches/[branch].js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/enforce_admins.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/enforce_admins.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/required_pull_request_reviews.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/required_pull_request_reviews.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/required_signatures.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/required_signatures.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/required_status_checks.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/required_status_checks.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/required_status_checks/contexts.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/required_status_checks/contexts.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/apps.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/apps.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/teams.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/teams.js"),
    (b"pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/users.js", b"//pages/repos/[owner]/[repo]/branches/[branch]/protection/restrictions/users.js"),
    (b"pages/repos/[owner]/[repo]/check-runs/[check_run_id].js", b"//pages/repos/[owner]/[repo]/check-runs/[check_run_id].js"),
    (b"pages/repos/[owner]/[repo]/check-runs/[check_run_id]/annotations.js", b"//pages/repos/[owner]/[repo]/check-runs/[check_run_id]/annotations.js"),
    (b"pages/repos/[owner]/[repo]/check-suites/[check_suite_id].js", b"//pages/repos/[owner]/[repo]/check-suites/[check_suite_id].js"),
    (b"pages/repos/[owner]/[repo]/check-suites/[check_suite_id]/check-runs.js", b"//pages/repos/[owner]/[repo]/check-suites/[check_suite_id]/check-runs.js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/alerts.js", b"//pages/repos/[owner]/[repo]/code-scanning/alerts.js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/alerts/[alert_number].js", b"//pages/repos/[owner]/[repo]/code-scanning/alerts/[alert_number].js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/alerts/[alert_number]/instances.js", b"//pages/repos/[owner]/[repo]/code-scanning/alerts/[alert_number]/instances.js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/analyses.js", b"//pages/repos/[owner]/[repo]/code-scanning/analyses.js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/analyses/[analysis_id].js", b"//pages/repos/[owner]/[repo]/code-scanning/analyses/[analysis_id].js"),
    (b"pages/repos/[owner]/[repo]/code-scanning/sarifs/[sarif_id].js", b"//pages/repos/[owner]/[repo]/code-scanning/sarifs/[sarif_id].js"),
    (b"pages/repos/[owner]/[repo]/collaborators.js", b"//pages/repos/[owner]/[repo]/collaborators.js"),
    (b"pages/repos/[owner]/[repo]/collaborators/[username].js", b"//pages/repos/[owner]/[repo]/collaborators/[username].js"),
    (b"pages/repos/[owner]/[repo]/collaborators/[username]/permission.js", b"//pages/repos/[owner]/[repo]/collaborators/[username]/permission.js"),
    (b"pages/repos/[owner]/[repo]/comments.js", b"//pages/repos/[owner]/[repo]/comments.js"),
    (b"pages/repos/[owner]/[repo]/comments/[comment_id].js", b"//pages/repos/[owner]/[repo]/comments/[comment_id].js"),
    (b"pages/repos/[owner]/[repo]/comments/[comment_id]/reactions.js", b"//pages/repos/[owner]/[repo]/comments/[comment_id]/reactions.js"),
    (b"pages/repos/[owner]/[repo]/commits.js", b"//pages/repos/[owner]/[repo]/commits.js"),
    (b"pages/repos/[owner]/[repo]/commits/[commit_sha]/branches-where-head.js", b"//pages/repos/[owner]/[repo]/commits/[commit_sha]/branches-where-head.js"),
    (b"pages/repos/[owner]/[repo]/commits/[commit_sha]/comments.js", b"//pages/repos/[owner]/[repo]/commits/[commit_sha]/comments.js"),
    (b"pages/repos/[owner]/[repo]/commits/[commit_sha]/pulls.js", b"//pages/repos/[owner]/[repo]/commits/[commit_sha]/pulls.js"),
    (b"pages/repos/[owner]/[repo]/commits/[ref].js", b"//pages/repos/[owner]/[repo]/commits/[ref].js"),
    (b"pages/repos/[owner]/[repo]/commits/[ref]/check-runs.js", b"//pages/repos/[owner]/[repo]/commits/[ref]/check-runs.js"),
    (b"pages/repos/[owner]/[repo]/commits/[ref]/check-suites.js", b"//pages/repos/[owner]/[repo]/commits/[ref]/check-suites.js"),
    (b"pages/repos/[owner]/[repo]/commits/[ref]/status.js", b"//pages/repos/[owner]/[repo]/commits/[ref]/status.js"),
    (b"pages/repos/[owner]/[repo]/commits/[ref]/statuses.js", b"//pages/repos/[owner]/[repo]/commits/[ref]/statuses.js"),
    (b"pages/repos/[owner]/[repo]/community/profile.js", b"//pages/repos/[owner]/[repo]/community/profile.js"),
    (b"pages/repos/[owner]/[repo]/compare/[basehead].js", b"//pages/repos/[owner]/[repo]/compare/[basehead].js"),
    (b"pages/repos/[owner]/[repo]/contents/[path].js", b"//pages/repos/[owner]/[repo]/contents/[path].js"),
    (b"pages/repos/[owner]/[repo]/contributors.js", b"//pages/repos/[owner]/[repo]/contributors.js"),
    (b"pages/repos/[owner]/[repo]/deployments.js", b"//pages/repos/[owner]/[repo]/deployments.js"),
    (b"pages/repos/[owner]/[repo]/deployments/[deployment_id].js", b"//pages/repos/[owner]/[repo]/deployments/[deployment_id].js"),
    (b"pages/repos/[owner]/[repo]/deployments/[deployment_id]/statuses.js", b"//pages/repos/[owner]/[repo]/deployments/[deployment_id]/statuses.js"),
    (b"pages/repos/[owner]/[repo]/deployments/[deployment_id]/statuses/[status_id].js", b"//pages/repos/[owner]/[repo]/deployments/[deployment_id]/statuses/[status_id].js"),
    (b"pages/repos/[owner]/[repo]/environments.js", b"//pages/repos/[owner]/[repo]/environments.js"),
    (b"pages/repos/[owner]/[repo]/environments/[environment_name].js", b"//pages/repos/[owner]/[repo]/environments/[environment_name].js"),
    (b"pages/repos/[owner]/[repo]/events.js", b"//pages/repos/[owner]/[repo]/events.js"),
    (b"pages/repos/[owner]/[repo]/forks.js", b"//pages/repos/[owner]/[repo]/forks.js"),
    (b"pages/repos/[owner]/[repo]/git/blobs/[file_sha].js", b"//pages/repos/[owner]/[repo]/git/blobs/[file_sha].js"),
    (b"pages/repos/[owner]/[repo]/git/commits/[commit_sha].js", b"//pages/repos/[owner]/[repo]/git/commits/[commit_sha].js"),
    (b"pages/repos/[owner]/[repo]/git/matching-refs/[ref].js", b"//pages/repos/[owner]/[repo]/git/matching-refs/[ref].js"),
    (b"pages/repos/[owner]/[repo]/git/ref/[ref].js", b"//pages/repos/[owner]/[repo]/git/ref/[ref].js"),
    (b"pages/repos/[owner]/[repo]/git/tags/[tag_sha].js", b"//pages/repos/[owner]/[repo]/git/tags/[tag_sha].js"),
    (b"pages/repos/[owner]/[repo]/git/trees/[tree_sha].js", b"//pages/repos/[owner]/[repo]/git/trees/[tree_sha].js"),
    (b"pages/repos/[owner]/[repo]/hooks.js", b"//pages/repos/[owner]/[repo]/hooks.js"),
    (b"pages/repos/[owner]/[repo]/hooks/[hook_id].js", b"//pages/repos/[owner]/[repo]/hooks/[hook_id].js"),
    (b"pages/repos/[owner]/[repo]/hooks/[hook_id]/config.js", b"//pages/repos/[owner]/[repo]/hooks/[hook_id]/config.js"),
    (b"pages/repos/[owner]/[repo]/hooks/[hook_id]/deliveries.js", b"//pages/repos/[owner]/[repo]/hooks/[hook_id]/deliveries.js"),
    (b"pages/repos/[owner]/[repo]/hooks/[hook_id]/deliveries/[delivery_id].js", b"//pages/repos/[owner]/[repo]/hooks/[hook_id]/deliveries/[delivery_id].js"),
    (b"pages/repos/[owner]/[repo]/import.js", b"//pages/repos/[owner]/[repo]/import.js"),
    (b"pages/repos/[owner]/[repo]/import/authors.js", b"//pages/repos/[owner]/[repo]/import/authors.js"),
    (b"pages/repos/[owner]/[repo]/import/large_files.js", b"//pages/repos/[owner]/[repo]/import/large_files.js"),
    (b"pages/repos/[owner]/[repo]/interaction-limits.js", b"//pages/repos/[owner]/[repo]/interaction-limits.js"),
    (b"pages/repos/[owner]/[repo]/invitations.js", b"//pages/repos/[owner]/[repo]/invitations.js"),
    (b"pages/repos/[owner]/[repo]/issues.js", b"//pages/repos/[owner]/[repo]/issues.js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number].js", b"//pages/repos/[owner]/[repo]/issues/[issue_number].js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number]/comments.js", b"//pages/repos/[owner]/[repo]/issues/[issue_number]/comments.js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number]/events.js", b"//pages/repos/[owner]/[repo]/issues/[issue_number]/events.js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number]/labels.js", b"//pages/repos/[owner]/[repo]/issues/[issue_number]/labels.js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number]/reactions.js", b"//pages/repos/[owner]/[repo]/issues/[issue_number]/reactions.js"),
    (b"pages/repos/[owner]/[repo]/issues/[issue_number]/timeline.js", b"//pages/repos/[owner]/[repo]/issues/[issue_number]/timeline.js"),
    (b"pages/repos/[owner]/[repo]/issues/comments.js", b"//pages/repos/[owner]/[repo]/issues/comments.js"),
    (b"pages/repos/[owner]/[repo]/issues/comments/[comment_id].js", b"//pages/repos/[owner]/[repo]/issues/comments/[comment_id].js"),
    (b"pages/repos/[owner]/[repo]/issues/comments/[comment_id]/reactions.js", b"//pages/repos/[owner]/[repo]/issues/comments/[comment_id]/reactions.js"),
    (b"pages/repos/[owner]/[repo]/issues/events.js", b"//pages/repos/[owner]/[repo]/issues/events.js"),
    (b"pages/repos/[owner]/[repo]/issues/events/[event_id].js", b"//pages/repos/[owner]/[repo]/issues/events/[event_id].js"),
    (b"pages/repos/[owner]/[repo]/keys.js", b"//pages/repos/[owner]/[repo]/keys.js"),
    (b"pages/repos/[owner]/[repo]/keys/[key_id].js", b"//pages/repos/[owner]/[repo]/keys/[key_id].js"),
    (b"pages/repos/[owner]/[repo]/labels.js", b"//pages/repos/[owner]/[repo]/labels.js"),
    (b"pages/repos/[owner]/[repo]/labels/[name].js", b"//pages/repos/[owner]/[repo]/labels/[name].js"),
    (b"pages/repos/[owner]/[repo]/languages.js", b"//pages/repos/[owner]/[repo]/languages.js"),
    (b"pages/repos/[owner]/[repo]/license.js", b"//pages/repos/[owner]/[repo]/license.js"),
    (b"pages/repos/[owner]/[repo]/milestones.js", b"//pages/repos/[owner]/[repo]/milestones.js"),
    (b"pages/repos/[owner]/[repo]/milestones/[milestone_number].js", b"//pages/repos/[owner]/[repo]/milestones/[milestone_number].js"),
    (b"pages/repos/[owner]/[repo]/milestones/[milestone_number]/labels.js", b"//pages/repos/[owner]/[repo]/milestones/[milestone_number]/labels.js"),
    (b"pages/repos/[owner]/[repo]/pages.js", b"//pages/repos/[owner]/[repo]/pages.js"),
    (b"pages/repos/[owner]/[repo]/pages/builds.js", b"//pages/repos/[owner]/[repo]/pages/builds.js"),
    (b"pages/repos/[owner]/[repo]/pages/builds/[build_id].js", b"//pages/repos/[owner]/[repo]/pages/builds/[build_id].js"),
    (b"pages/repos/[owner]/[repo]/pages/builds/latest.js", b"//pages/repos/[owner]/[repo]/pages/builds/latest.js"),
    (b"pages/repos/[owner]/[repo]/pages/health.js", b"//pages/repos/[owner]/[repo]/pages/health.js"),
    (b"pages/repos/[owner]/[repo]/projects.js", b"//pages/repos/[owner]/[repo]/projects.js"),
    (b"pages/repos/[owner]/[repo]/pulls.js", b"//pages/repos/[owner]/[repo]/pulls.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number].js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number].js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/comments.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/comments.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/commits.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/commits.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/files.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/files.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/merge.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/merge.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/requested_reviewers.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/requested_reviewers.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews.js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews/[review_id].js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews/[review_id].js"),
    (b"pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews/[review_id]/comments.js", b"//pages/repos/[owner]/[repo]/pulls/[pull_number]/reviews/[review_id]/comments.js"),
    (b"pages/repos/[owner]/[repo]/pulls/comments.js", b"//pages/repos/[owner]/[repo]/pulls/comments.js"),
    (b"pages/repos/[owner]/[repo]/pulls/comments/[comment_id].js", b"//pages/repos/[owner]/[repo]/pulls/comments/[comment_id].js"),
    (b"pages/repos/[owner]/[repo]/pulls/comments/[comment_id]/reactions.js", b"//pages/repos/[owner]/[repo]/pulls/comments/[comment_id]/reactions.js"),
    (b"pages/repos/[owner]/[repo]/readme.js", b"//pages/repos/[owner]/[repo]/readme.js"),
    (b"pages/repos/[owner]/[repo]/readme/[dir].js", b"//pages/repos/[owner]/[repo]/readme/[dir].js"),
    (b"pages/repos/[owner]/[repo]/releases.js", b"//pages/repos/[owner]/[repo]/releases.js"),
    (b"pages/repos/[owner]/[repo]/releases/[release_id].js", b"//pages/repos/[owner]/[repo]/releases/[release_id].js"),
    (b"pages/repos/[owner]/[repo]/releases/[release_id]/assets.js", b"//pages/repos/[owner]/[repo]/releases/[release_id]/assets.js"),
    (b"pages/repos/[owner]/[repo]/releases/assets/[asset_id].js", b"//pages/repos/[owner]/[repo]/releases/assets/[asset_id].js"),
    (b"pages/repos/[owner]/[repo]/releases/latest.js", b"//pages/repos/[owner]/[repo]/releases/latest.js"),
    (b"pages/repos/[owner]/[repo]/releases/tags/[tag].js", b"//pages/repos/[owner]/[repo]/releases/tags/[tag].js"),
    (b"pages/repos/[owner]/[repo]/secret-scanning/alerts.js", b"//pages/repos/[owner]/[repo]/secret-scanning/alerts.js"),
    (b"pages/repos/[owner]/[repo]/secret-scanning/alerts/[alert_number].js", b"//pages/repos/[owner]/[repo]/secret-scanning/alerts/[alert_number].js"),
    (b"pages/repos/[owner]/[repo]/stargazers.js", b"//pages/repos/[owner]/[repo]/stargazers.js"),
    (b"pages/repos/[owner]/[repo]/stats/code_frequency.js", b"//pages/repos/[owner]/[repo]/stats/code_frequency.js"),
    (b"pages/repos/[owner]/[repo]/stats/commit_activity.js", b"//pages/repos/[owner]/[repo]/stats/commit_activity.js"),
    (b"pages/repos/[owner]/[repo]/stats/contributors.js", b"//pages/repos/[owner]/[repo]/stats/contributors.js"),
    (b"pages/repos/[owner]/[repo]/stats/participation.js", b"//pages/repos/[owner]/[repo]/stats/participation.js"),
    (b"pages/repos/[owner]/[repo]/stats/punch_card.js", b"//pages/repos/[owner]/[repo]/stats/punch_card.js"),
    (b"pages/repos/[owner]/[repo]/subscribers.js", b"//pages/repos/[owner]/[repo]/subscribers.js"),
    (b"pages/repos/[owner]/[repo]/tags.js", b"//pages/repos/[owner]/[repo]/tags.js"),
    (b"pages/repos/[owner]/[repo]/tarball/[ref].js", b"//pages/repos/[owner]/[repo]/tarball/[ref].js"),
    (b"pages/repos/[owner]/[repo]/teams.js", b"//pages/repos/[owner]/[repo]/teams.js"),
    (b"pages/repos/[owner]/[repo]/topics.js", b"//pages/repos/[owner]/[repo]/topics.js"),
    (b"pages/repos/[owner]/[repo]/traffic/clones.js", b"//pages/repos/[owner]/[repo]/traffic/clones.js"),
    (b"pages/repos/[owner]/[repo]/traffic/popular/paths.js", b"//pages/repos/[owner]/[repo]/traffic/popular/paths.js"),
    (b"pages/repos/[owner]/[repo]/traffic/popular/referrers.js", b"//pages/repos/[owner]/[repo]/traffic/popular/referrers.js"),
    (b"pages/repos/[owner]/[repo]/traffic/views.js", b"//pages/repos/[owner]/[repo]/traffic/views.js"),
    (b"pages/repos/[owner]/[repo]/zipball/[ref].js", b"//pages/repos/[owner]/[repo]/zipball/[ref].js"),
    (b"pages/repositories.js", b"//pages/repositories.js"),
    (b"pages/repositories/[repository_id]/environments/[environment_name]/secrets.js", b"//pages/repositories/[repository_id]/environments/[environment_name]/secrets.js"),
    (b"pages/repositories/[repository_id]/environments/[environment_name]/secrets/[secret_name].js", b"//pages/repositories/[repository_id]/environments/[environment_name]/secrets/[secret_name].js"),
    (b"pages/repositories/[repository_id]/environments/[environment_name]/secrets/public-key.js", b"//pages/repositories/[repository_id]/environments/[environment_name]/secrets/public-key.js"),
    (b"pages/repositories/[repository_id]/[...jarred-fake-catch-all].js", b"//pages/repositories/[...jarred-fake-catch-all].js"),
    (b"pages/scim/v2/enterprises/[enterprise]/Groups.js", b"//pages/scim/v2/enterprises/[enterprise]/Groups.js"),
    (b"pages/scim/v2/enterprises/[enterprise]/Groups/[scim_group_id].js", b"//pages/scim/v2/enterprises/[enterprise]/Groups/[scim_group_id].js"),
    (b"pages/scim/v2/enterprises/[enterprise]/Users.js", b"//pages/scim/v2/enterprises/[enterprise]/Users.js"),
    (b"pages/scim/v2/enterprises/[enterprise]/Users/[scim_user_id].js", b"//pages/scim/v2/enterprises/[enterprise]/Users/[scim_user_id].js"),
    (b"pages/scim/v2/organizations/[org]/Users.js", b"//pages/scim/v2/organizations/[org]/Users.js"),
    (b"pages/scim/v2/organizations/[org]/Users/[scim_user_id].js", b"//pages/scim/v2/organizations/[org]/Users/[scim_user_id].js"),
    (b"pages/search/code.js", b"//pages/search/code.js"),
    (b"pages/search/commits.js", b"//pages/search/commits.js"),
    (b"pages/search/issues.js", b"//pages/search/issues.js"),
    (b"pages/search/labels.js", b"//pages/search/labels.js"),
    (b"pages/search/repositories.js", b"//pages/search/repositories.js"),
    (b"pages/search/topics.js", b"//pages/search/topics.js"),
    (b"pages/search/users.js", b"//pages/search/users.js"),
    (b"pages/teams/[team_id].js", b"//pages/teams/[team_id].js"),
    (b"pages/teams/[team_id]/discussions.js", b"//pages/teams/[team_id]/discussions.js"),
    (b"pages/teams/[team_id]/discussions/[discussion_number].js", b"//pages/teams/[team_id]/discussions/[discussion_number].js"),
    (b"pages/teams/[team_id]/discussions/[discussion_number]/comments.js", b"//pages/teams/[team_id]/discussions/[discussion_number]/comments.js"),
    (b"pages/teams/[team_id]/discussions/[discussion_number]/comments/[comment_number].js", b"//pages/teams/[team_id]/discussions/[discussion_number]/comments/[comment_number].js"),
    (b"pages/teams/[team_id]/discussions/[discussion_number]/comments/[comment_number]/reactions.js", b"//pages/teams/[team_id]/discussions/[discussion_number]/comments/[comment_number]/reactions.js"),
    (b"pages/teams/[team_id]/discussions/[discussion_number]/reactions.js", b"//pages/teams/[team_id]/discussions/[discussion_number]/reactions.js"),
    (b"pages/teams/[team_id]/invitations.js", b"//pages/teams/[team_id]/invitations.js"),
    (b"pages/teams/[team_id]/members.js", b"//pages/teams/[team_id]/members.js"),
    (b"pages/teams/[team_id]/members/[username].js", b"//pages/teams/[team_id]/members/[username].js"),
    (b"pages/teams/[team_id]/memberships/[username].js", b"//pages/teams/[team_id]/memberships/[username].js"),
    (b"pages/teams/[team_id]/projects.js", b"//pages/teams/[team_id]/projects.js"),
    (b"pages/teams/[team_id]/projects/[project_id].js", b"//pages/teams/[team_id]/projects/[project_id].js"),
    (b"pages/teams/[team_id]/repos.js", b"//pages/teams/[team_id]/repos.js"),
    (b"pages/teams/[team_id]/repos/[owner]/[repo].js", b"//pages/teams/[team_id]/repos/[owner]/[repo].js"),
    (b"pages/teams/[team_id]/teams.js", b"//pages/teams/[team_id]/teams.js"),
    (b"pages/users.js", b"//pages/users.js"),
    (b"pages/users/[username].js", b"//pages/users/[username].js"),
    (b"pages/users/[username]/events.js", b"//pages/users/[username]/events.js"),
    (b"pages/users/[username]/events/public.js", b"//pages/users/[username]/events/public.js"),
    (b"pages/users/[username]/followers.js", b"//pages/users/[username]/followers.js"),
    (b"pages/users/[username]/following.js", b"//pages/users/[username]/following.js"),
    (b"pages/users/[username]/following/[target_user].js", b"//pages/users/[username]/following/[target_user].js"),
    (b"pages/users/[username]/gpg_keys.js", b"//pages/users/[username]/gpg_keys.js"),
    (b"pages/users/[username]/keys.js", b"//pages/users/[username]/keys.js"),
    (b"pages/users/[username]/orgs.js", b"//pages/users/[username]/orgs.js"),
    (b"pages/users/[username]/received_events.js", b"//pages/users/[username]/received_events.js"),
    (b"pages/users/[username]/received_events/public.js", b"//pages/users/[username]/received_events/public.js"),
    (b"pages/users/[username]/repos.js", b"//pages/users/[username]/repos.js"),
    (b"pages/users/[username]/starred.js", b"//pages/users/[username]/starred.js"),
    (b"pages/users/[username]/subscriptions.js", b"//pages/users/[username]/subscriptions.js"),
    (b"pages/zen.js", b"//pages/zen.js"),
];

// copy((await next.router.pageLoader.getPageList()).sort())
pub static VERCEL_ROUTES_LIST: RouteList = &[
    (b"pages/index.js", b"// pages/index.js"),
    (b"pages/404.js", b"// pages/404.js"),
    (b"pages/[teamSlug].js", b"// pages/[teamSlug].js"),
    (b"pages/[teamSlug]/[project].js", b"// pages/[teamSlug]/[project].js"),
    (b"pages/[teamSlug]/[project]/[id].js", b"// pages/[teamSlug]/[project]/[id].js"),
    (b"pages/[teamSlug]/[project]/[id]/[suffix].js", b"// pages/[teamSlug]/[project]/[id]/[suffix].js"),
    (b"pages/[teamSlug]/[project]/[id]/[suffix]/functions.js", b"// pages/[teamSlug]/[project]/[id]/[suffix]/functions.js"),
    (b"pages/[teamSlug]/[project]/[id]/[suffix]/source.js", b"// pages/[teamSlug]/[project]/[id]/[suffix]/source.js"),
    (b"pages/[teamSlug]/[project]/[id]/functions.js", b"// pages/[teamSlug]/[project]/[id]/functions.js"),
    (b"pages/[teamSlug]/[project]/[id]/source.js", b"// pages/[teamSlug]/[project]/[id]/source.js"),
    (b"pages/[teamSlug]/[project]/deployments.js", b"// pages/[teamSlug]/[project]/deployments.js"),
    (b"pages/[teamSlug]/[project]/domains.js", b"// pages/[teamSlug]/[project]/domains.js"),
    (b"pages/[teamSlug]/[project]/insights.js", b"// pages/[teamSlug]/[project]/insights.js"),
    (b"pages/[teamSlug]/[project]/integrations/[cfgId].js", b"// pages/[teamSlug]/[project]/integrations/[cfgId].js"),
    (b"pages/[teamSlug]/[project]/settings.js", b"// pages/[teamSlug]/[project]/settings.js"),
    (b"pages/[teamSlug]/[project]/settings/advanced.js", b"// pages/[teamSlug]/[project]/settings/advanced.js"),
    (b"pages/[teamSlug]/[project]/settings/domains.js", b"// pages/[teamSlug]/[project]/settings/domains.js"),
    (b"pages/[teamSlug]/[project]/settings/environment-variables.js", b"// pages/[teamSlug]/[project]/settings/environment-variables.js"),
    (b"pages/[teamSlug]/[project]/settings/general.js", b"// pages/[teamSlug]/[project]/settings/general.js"),
    (b"pages/[teamSlug]/[project]/settings/git.js", b"// pages/[teamSlug]/[project]/settings/git.js"),
    (b"pages/[teamSlug]/[project]/settings/integrations.js", b"// pages/[teamSlug]/[project]/settings/integrations.js"),
    (b"pages/[teamSlug]/[project]/settings/security.js", b"// pages/[teamSlug]/[project]/settings/security.js"),
    (b"pages/[teamSlug]/[project]/settings/serverless-functions.js", b"// pages/[teamSlug]/[project]/settings/serverless-functions.js"),
    (b"pages/_app.js", b"// pages/_app.js"),
    (b"pages/_error.js", b"// pages/_error.js"),
    (b"pages/_flags.js", b"// pages/_flags.js"),
    (b"pages/about.js", b"// pages/about.js"),
    (b"pages/about/[member].js", b"// pages/about/[member].js"),
    (b"pages/account.js", b"// pages/account.js"),
    (b"pages/account/billing.js", b"// pages/account/billing.js"),
    (b"pages/account/general.js", b"// pages/account/general.js"),
    (b"pages/account/git.js", b"// pages/account/git.js"),
    (b"pages/account/invoices.js", b"// pages/account/invoices.js"),
    (b"pages/account/login-connections.js", b"// pages/account/login-connections.js"),
    (b"pages/account/teams.js", b"// pages/account/teams.js"),
    (b"pages/account/tokens.js", b"// pages/account/tokens.js"),
    (b"pages/blog.js", b"// pages/blog.js"),
    (b"pages/blog/[post].js", b"// pages/blog/[post].js"),
    (b"pages/blog/preview/[post].js", b"// pages/blog/preview/[post].js"),
    (b"pages/careers.js", b"// pages/careers.js"),
    (b"pages/careers/[slug].js", b"// pages/careers/[slug].js"),
    (b"pages/careers/[slug]/preview.js", b"// pages/careers/[slug]/preview.js"),
    (b"pages/careers/preview.js", b"// pages/careers/preview.js"),
    (b"pages/case-studies/apideck.js", b"// pages/case-studies/apideck.js"),
    (b"pages/case-studies/barnebys.js", b"// pages/case-studies/barnebys.js"),
    (b"pages/case-studies/cssbattle.js", b"// pages/case-studies/cssbattle.js"),
    (b"pages/case-studies/dashing.js", b"// pages/case-studies/dashing.js"),
    (b"pages/case-studies/fireflies.js", b"// pages/case-studies/fireflies.js"),
    (b"pages/case-studies/fitt.js", b"// pages/case-studies/fitt.js"),
    (b"pages/case-studies/flowkit.js", b"// pages/case-studies/flowkit.js"),
    (b"pages/case-studies/integral.js", b"// pages/case-studies/integral.js"),
    (b"pages/case-studies/labelbox.js", b"// pages/case-studies/labelbox.js"),
    (b"pages/case-studies/mural.js", b"// pages/case-studies/mural.js"),
    (b"pages/case-studies/unspent.js", b"// pages/case-studies/unspent.js"),
    (b"pages/changelog.js", b"// pages/changelog.js"),
    (b"pages/changelog/[item].js", b"// pages/changelog/[item].js"),
    (b"pages/changelog/preview/[item].js", b"// pages/changelog/preview/[item].js"),
    (b"pages/cli.js", b"// pages/cli.js"),
    (b"pages/communications-center.js", b"// pages/communications-center.js"),
    (b"pages/confirm.js", b"// pages/confirm.js"),
    (b"pages/contact.js", b"// pages/contact.js"),
    (b"pages/contact/sales.js", b"// pages/contact/sales.js"),
    (b"pages/customers.js", b"// pages/customers.js"),
    (b"pages/customers/[slug].js", b"// pages/customers/[slug].js"),
    (b"pages/customers/preview/[slug].js", b"// pages/customers/preview/[slug].js"),
    (b"pages/dashboard.js", b"// pages/dashboard.js"),
    (b"pages/dashboard/[teamSlug]/activity.js", b"// pages/dashboard/[teamSlug]/activity.js"),
    (b"pages/dashboard/[teamSlug]/domains.js", b"// pages/dashboard/[teamSlug]/domains.js"),
    (b"pages/dashboard/[teamSlug]/domains/[domain].js", b"// pages/dashboard/[teamSlug]/domains/[domain].js"),
    (b"pages/dashboard/[teamSlug]/domains/delegate.js", b"// pages/dashboard/[teamSlug]/domains/delegate.js"),
    (b"pages/dashboard/[teamSlug]/integrations.js", b"// pages/dashboard/[teamSlug]/integrations.js"),
    (b"pages/dashboard/[teamSlug]/integrations/[cfgId].js", b"// pages/dashboard/[teamSlug]/integrations/[cfgId].js"),
    (b"pages/dashboard/[teamSlug]/integrations/[cfgId]/installed.js", b"// pages/dashboard/[teamSlug]/integrations/[cfgId]/installed.js"),
    (b"pages/dashboard/[teamSlug]/integrations/configuration.js", b"// pages/dashboard/[teamSlug]/integrations/configuration.js"),
    (b"pages/dashboard/[teamSlug]/integrations/console.js", b"// pages/dashboard/[teamSlug]/integrations/console.js"),
    (b"pages/dashboard/[teamSlug]/integrations/console/[slug].js", b"// pages/dashboard/[teamSlug]/integrations/console/[slug].js"),
    (b"pages/dashboard/[teamSlug]/integrations/create.js", b"// pages/dashboard/[teamSlug]/integrations/create.js"),
    (b"pages/dashboard/[teamSlug]/integrations/edit.js", b"// pages/dashboard/[teamSlug]/integrations/edit.js"),
    (b"pages/dashboard/[teamSlug]/project/deployments.js", b"// pages/dashboard/[teamSlug]/project/deployments.js"),
    (b"pages/dashboard/[teamSlug]/project/integrations/configuration.js", b"// pages/dashboard/[teamSlug]/project/integrations/configuration.js"),
    (b"pages/dashboard/[teamSlug]/usage.js", b"// pages/dashboard/[teamSlug]/usage.js"),
    (b"pages/dashboard/activity.js", b"// pages/dashboard/activity.js"),
    (b"pages/dashboard/domains.js", b"// pages/dashboard/domains.js"),
    (b"pages/dashboard/domains/[domain].js", b"// pages/dashboard/domains/[domain].js"),
    (b"pages/dashboard/domains/delegate.js", b"// pages/dashboard/domains/delegate.js"),
    (b"pages/dashboard/integrations.js", b"// pages/dashboard/integrations.js"),
    (b"pages/dashboard/integrations/[cfgId].js", b"// pages/dashboard/integrations/[cfgId].js"),
    (b"pages/dashboard/integrations/[cfgId]/installed.js", b"// pages/dashboard/integrations/[cfgId]/installed.js"),
    (b"pages/dashboard/integrations/console.js", b"// pages/dashboard/integrations/console.js"),
    (b"pages/dashboard/integrations/console/[slug].js", b"// pages/dashboard/integrations/console/[slug].js"),
    (b"pages/dashboard/integrations/create.js", b"// pages/dashboard/integrations/create.js"),
    (b"pages/dashboard/integrations/edit.js", b"// pages/dashboard/integrations/edit.js"),
    (b"pages/dashboard/integrations/installed.js", b"// pages/dashboard/integrations/installed.js"),
    (b"pages/dashboard/project/deployments.js", b"// pages/dashboard/project/deployments.js"),
    (b"pages/dashboard/project/insights.js", b"// pages/dashboard/project/insights.js"),
    (b"pages/dashboard/project/integrations/[cfgId].js", b"// pages/dashboard/project/integrations/[cfgId].js"),
    (b"pages/dashboard/usage.js", b"// pages/dashboard/usage.js"),
    (b"pages/deployment/redirect.js", b"// pages/deployment/redirect.js"),
    (b"pages/deployments/[host]/source.js", b"// pages/deployments/[host]/source.js"),
    (b"pages/design.js", b"// pages/design.js"),
    (b"pages/design/autocomplete.js", b"// pages/design/autocomplete.js"),
    (b"pages/design/avatar.js", b"// pages/design/avatar.js"),
    (b"pages/design/badge.js", b"// pages/design/badge.js"),
    (b"pages/design/brands.js", b"// pages/design/brands.js"),
    (b"pages/design/button.js", b"// pages/design/button.js"),
    (b"pages/design/calendar.js", b"// pages/design/calendar.js"),
    (b"pages/design/capacity.js", b"// pages/design/capacity.js"),
    (b"pages/design/checkbox.js", b"// pages/design/checkbox.js"),
    (b"pages/design/collapse.js", b"// pages/design/collapse.js"),
    (b"pages/design/color.js", b"// pages/design/color.js"),
    (b"pages/design/combobox.js", b"// pages/design/combobox.js"),
    (b"pages/design/description.js", b"// pages/design/description.js"),
    (b"pages/design/drawer.js", b"// pages/design/drawer.js"),
    (b"pages/design/entity.js", b"// pages/design/entity.js"),
    (b"pages/design/error.js", b"// pages/design/error.js"),
    (b"pages/design/feedback.js", b"// pages/design/feedback.js"),
    (b"pages/design/fieldset.js", b"// pages/design/fieldset.js"),
    (b"pages/design/file-tree.js", b"// pages/design/file-tree.js"),
    (b"pages/design/footer.js", b"// pages/design/footer.js"),
    (b"pages/design/grid.js", b"// pages/design/grid.js"),
    (b"pages/design/icon.js", b"// pages/design/icon.js"),
    (b"pages/design/icons.js", b"// pages/design/icons.js"),
    (b"pages/design/image.js", b"// pages/design/image.js"),
    (b"pages/design/input.js", b"// pages/design/input.js"),
    (b"pages/design/keyboard-input.js", b"// pages/design/keyboard-input.js"),
    (b"pages/design/link.js", b"// pages/design/link.js"),
    (b"pages/design/loading-dots.js", b"// pages/design/loading-dots.js"),
    (b"pages/design/marketing-text.js", b"// pages/design/marketing-text.js"),
    (b"pages/design/menu.js", b"// pages/design/menu.js"),
    (b"pages/design/modal.js", b"// pages/design/modal.js"),
    (b"pages/design/nextjs.js", b"// pages/design/nextjs.js"),
    (b"pages/design/note.js", b"// pages/design/note.js"),
    (b"pages/design/playground.js", b"// pages/design/playground.js"),
    (b"pages/design/popover.js", b"// pages/design/popover.js"),
    (b"pages/design/popover-menu.js", b"// pages/design/popover-menu.js"),
    (b"pages/design/progress.js", b"// pages/design/progress.js"),
    (b"pages/design/radio.js", b"// pages/design/radio.js"),
    (b"pages/design/scroller.js", b"// pages/design/scroller.js"),
    (b"pages/design/select.js", b"// pages/design/select.js"),
    (b"pages/design/show-more.js", b"// pages/design/show-more.js"),
    (b"pages/design/skeleton.js", b"// pages/design/skeleton.js"),
    (b"pages/design/snippet.js", b"// pages/design/snippet.js"),
    (b"pages/design/spacer.js", b"// pages/design/spacer.js"),
    (b"pages/design/spinner.js", b"// pages/design/spinner.js"),
    (b"pages/design/stack.js", b"// pages/design/stack.js"),
    (b"pages/design/status-dot.js", b"// pages/design/status-dot.js"),
    (b"pages/design/switch.js", b"// pages/design/switch.js"),
    (b"pages/design/table.js", b"// pages/design/table.js"),
    (b"pages/design/tabs.js", b"// pages/design/tabs.js"),
    (b"pages/design/tag.js", b"// pages/design/tag.js"),
    (b"pages/design/text.js", b"// pages/design/text.js"),
    (b"pages/design/textarea.js", b"// pages/design/textarea.js"),
    (b"pages/design/toast.js", b"// pages/design/toast.js"),
    (b"pages/design/toggle.js", b"// pages/design/toggle.js"),
    (b"pages/design/tooltip.js", b"// pages/design/tooltip.js"),
    (b"pages/design/ui.js", b"// pages/design/ui.js"),
    (b"pages/design/video.js", b"// pages/design/video.js"),
    (b"pages/design/video-card.js", b"// pages/design/video-card.js"),
    (b"pages/design/window.js", b"// pages/design/window.js"),
    (b"pages/domains.js", b"// pages/domains.js"),
    (b"pages/experts.js", b"// pages/experts.js"),
    (b"pages/experts/[slug].js", b"// pages/experts/[slug].js"),
    (b"pages/experts/[slug]/projects/[projectSlug].js", b"// pages/experts/[slug]/projects/[projectSlug].js"),
    (b"pages/git/authorize.js", b"// pages/git/authorize.js"),
    (b"pages/github/installation-approved.js", b"// pages/github/installation-approved.js"),
    (b"pages/github/installation-requested.js", b"// pages/github/installation-requested.js"),
    (b"pages/github/installed.js", b"// pages/github/installed.js"),
    (b"pages/hackathon.js", b"// pages/hackathon.js"),
    (b"pages/home.js", b"// pages/home.js"),
    (b"pages/import/[teamSlug].js", b"// pages/import/[teamSlug].js"),
    (b"pages/insights.js", b"// pages/insights.js"),
    (b"pages/integrations.js", b"// pages/integrations.js"),
    (b"pages/integrations/[slug].js", b"// pages/integrations/[slug].js"),
    (b"pages/integrations/[slug]/loading.js", b"// pages/integrations/[slug]/loading.js"),
    (b"pages/integrations/[slug]/new.js", b"// pages/integrations/[slug]/new.js"),
    (b"pages/keyboard.js", b"// pages/keyboard.js"),
    (b"pages/legal/cookie-policy.js", b"// pages/legal/cookie-policy.js"),
    (b"pages/legal/dmca-policy.js", b"// pages/legal/dmca-policy.js"),
    (b"pages/legal/dpa.js", b"// pages/legal/dpa.js"),
    (b"pages/legal/enterprise-terms.js", b"// pages/legal/enterprise-terms.js"),
    (b"pages/legal/government-requests.js", b"// pages/legal/government-requests.js"),
    (b"pages/legal/inactivity-policy.js", b"// pages/legal/inactivity-policy.js"),
    (b"pages/legal/privacy-policy.js", b"// pages/legal/privacy-policy.js"),
    (b"pages/legal/sla.js", b"// pages/legal/sla.js"),
    (b"pages/legal/sub-processors.js", b"// pages/legal/sub-processors.js"),
    (b"pages/legal/support-terms.js", b"// pages/legal/support-terms.js"),
    (b"pages/legal/terms.js", b"// pages/legal/terms.js"),
    (b"pages/legal/trademark-policy.js", b"// pages/legal/trademark-policy.js"),
    (b"pages/live.js", b"// pages/live.js"),
    (b"pages/login/[[...mode]].js", b"// pages/login/[[...mode]].js"),
    (b"pages/login/scope/[teamSlug].js", b"// pages/login/scope/[teamSlug].js"),
    (b"pages/new.js", b"// pages/new.js"),
    (b"pages/new/[teamSlug].js", b"// pages/new/[teamSlug].js"),
    (b"pages/new/[teamSlug]/clone.js", b"// pages/new/[teamSlug]/clone.js"),
    (b"pages/new/[teamSlug]/git/third-party.js", b"// pages/new/[teamSlug]/git/third-party.js"),
    (b"pages/new/[teamSlug]/import.js", b"// pages/new/[teamSlug]/import.js"),
    (b"pages/new/[teamSlug]/success.js", b"// pages/new/[teamSlug]/success.js"),
    (b"pages/new/[teamSlug]/templates.js", b"// pages/new/[teamSlug]/templates.js"),
    (b"pages/new/clone.js", b"// pages/new/clone.js"),
    (b"pages/new/git/connected.js", b"// pages/new/git/connected.js"),
    (b"pages/new/git/third-party.js", b"// pages/new/git/third-party.js"),
    (b"pages/new/import.js", b"// pages/new/import.js"),
    (b"pages/new/success.js", b"// pages/new/success.js"),
    (b"pages/new/templates.js", b"// pages/new/templates.js"),
    (b"pages/notifications/account-being-deleted.js", b"// pages/notifications/account-being-deleted.js"),
    (b"pages/notifications/account-deletion.js", b"// pages/notifications/account-deletion.js"),
    (b"pages/notifications/authentication-failed.js", b"// pages/notifications/authentication-failed.js"),
    (b"pages/notifications/cli-login-failed.js", b"// pages/notifications/cli-login-failed.js"),
    (b"pages/notifications/cli-login-incomplete.js", b"// pages/notifications/cli-login-incomplete.js"),
    (b"pages/notifications/cli-login-oob.js", b"// pages/notifications/cli-login-oob.js"),
    (b"pages/notifications/cli-login-success.js", b"// pages/notifications/cli-login-success.js"),
    (b"pages/notifications/deletion-confirmed.js", b"// pages/notifications/deletion-confirmed.js"),
    (b"pages/notifications/email-change-failed.js", b"// pages/notifications/email-change-failed.js"),
    (b"pages/notifications/email-changed.js", b"// pages/notifications/email-changed.js"),
    (b"pages/notifications/email-confirmed.js", b"// pages/notifications/email-confirmed.js"),
    (b"pages/notifications/email-signup-confirmed.js", b"// pages/notifications/email-signup-confirmed.js"),
    (b"pages/notifications/token-expired.js", b"// pages/notifications/token-expired.js"),
    (b"pages/oauth/authorize.js", b"// pages/oauth/authorize.js"),
    (b"pages/oauth/git.js", b"// pages/oauth/git.js"),
    (b"pages/oauth/verify.js", b"// pages/oauth/verify.js"),
    (b"pages/oss.js", b"// pages/oss.js"),
    (b"pages/partners.js", b"// pages/partners.js"),
    (b"pages/partners/technology.js", b"// pages/partners/technology.js"),
    (b"pages/popups/saml-sso.js", b"// pages/popups/saml-sso.js"),
    (b"pages/pricing.js", b"// pages/pricing.js"),
    (b"pages/security.js", b"// pages/security.js"),
    (b"pages/signup/[[...mode]].js", b"// pages/signup/[[...mode]].js"),
    (b"pages/solutions/angular.js", b"// pages/solutions/angular.js"),
    (b"pages/solutions/gatsby.js", b"// pages/solutions/gatsby.js"),
    (b"pages/solutions/nextjs.js", b"// pages/solutions/nextjs.js"),
    (b"pages/solutions/react.js", b"// pages/solutions/react.js"),
    (b"pages/solutions/vue.js", b"// pages/solutions/vue.js"),
    (b"pages/support/request.js", b"// pages/support/request.js"),
    (b"pages/teams.js", b"// pages/teams.js"),
    (b"pages/teams/[teamSlug]/settings.js", b"// pages/teams/[teamSlug]/settings.js"),
    (b"pages/teams/[teamSlug]/settings/billing.js", b"// pages/teams/[teamSlug]/settings/billing.js"),
    (b"pages/teams/[teamSlug]/settings/general.js", b"// pages/teams/[teamSlug]/settings/general.js"),
    (b"pages/teams/[teamSlug]/settings/git.js", b"// pages/teams/[teamSlug]/settings/git.js"),
    (b"pages/teams/[teamSlug]/settings/invoices.js", b"// pages/teams/[teamSlug]/settings/invoices.js"),
    (b"pages/teams/[teamSlug]/settings/members.js", b"// pages/teams/[teamSlug]/settings/members.js"),
    (b"pages/teams/[teamSlug]/settings/security.js", b"// pages/teams/[teamSlug]/settings/security.js"),
    (b"pages/teams/connect.js", b"// pages/teams/connect.js"),
    (b"pages/teams/create.js", b"// pages/teams/create.js"),
    (b"pages/teams/invite.js", b"// pages/teams/invite.js"),
    (b"pages/teams/invite/[inviteCode].js", b"// pages/teams/invite/[inviteCode].js"),
    (b"pages/tv.js", b"// pages/tv.js"),
    (b"pages/tv/[video].js", b"// pages/tv/[video].js"),
    (b"pages/vercel-live-auth.js", b"// pages/vercel-live-auth.js"),
    (b"pages/virtual-event-starter-ki.js", b"// pages/virtual-event-starter-ki.js"),
];

// ──────────────────────────────────────────────────────────────────────────
// PORT STATUS
//   source:     src/test_runner/harness/fixtures.zig (574 lines)
//   confidence: medium
//   todos:      1
//   notes:      Route lists are Zig anon-struct field-name→value maps consumed via @typeInfo; ported as static (key,value) slices. Consumers must iterate slice instead of struct fields.
// ──────────────────────────────────────────────────────────────────────────
