// Code generated by protoc-gen-zig
///! package opentelemetry.proto.collector.trace.v1
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
/// import package opentelemetry.proto.trace.v1
const opentelemetry_proto_trace_v1 = @import("../../trace/v1.pb.zig");

pub const ExportTraceServiceRequest = struct {
    resource_spans: ArrayList(opentelemetry_proto_trace_v1.ResourceSpans),

    pub const _desc_table = .{
        .resource_spans = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ExportTraceServiceResponse = struct {
    partial_success: ?ExportTracePartialSuccess = null,

    pub const _desc_table = .{
        .partial_success = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ExportTracePartialSuccess = struct {
    rejected_spans: i64 = 0,
    error_message: ManagedString = .Empty,

    pub const _desc_table = .{
        .rejected_spans = fd(1, .{ .Varint = .Simple }),
        .error_message = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
