// usage: node make-inputs.cjs > inputs.json
// Candidates per production of the reference: class heritage, interface heritage, class member list, modifiers,
// property declarations, methods and bodies, accessors, constructors, index signatures, parameters, decorators.
const out = [];
const g = (group, list, l) => { for (const s of list) out.push(l ? { g: group, s, l } : { g: group, s }); };

g("H class heritage: parseHeritageClauses, parseHeritageClause, parseExpressionWithTypeArguments", [
  "class C extends {}",
  "class C extends A, B {}",
  "class C extends A extends B {}",
  "class C implements A extends B {}",
  "class C implements A implements B {}",
  "class C extends A implements {}",
  "class C extends A, {}",
  "class C implements A, {}",
  "class C extends {} {}",
  "class C extends A<> {}",
  "class C extends A<T,> {}",
  "class C extends A B {}",
  "class C extends",
  "class C extends implements B {}",
  "class C implements {}",
  "class C implements A B {}",
  "class C extends A<T><U> {}",
  "class C extends a?.b {}",
  "class C extends A<T>.b {}",
  "class C extends a.b<T> {}",
  "class C extends f()<T> {}",
  "class C extends (A) {}",
  "class C extends A() {}",
  "class C extends class {} {}",
  "class C extends function() {} {}",
  "class C extends new A {}",
  "class C extends new A() {}",
  "class C extends a + b {}",
  "class C extends -a {}",
  "class C extends !a {}",
  "class C extends typeof a {}",
  "class C extends void 0 {}",
  "class C extends ++a {}",
  "class C extends delete a.b {}",
  "async function f() { class C extends await a {} }",
  "function* f() { class C extends yield {} }",
  "class C extends <T>a {}",
  "class C extends a++ {}",
  "class C extends async () => {} {}",
  "class C extends a => a {}",
  "class C extends a ? b : c {}",
  "class C extends a as B {}",
  "class C extends a! {}",
  "class C extends a!<T> {}",
  "class C extends import('a') {}",
  "class C extends import.meta {}",
  "class C extends this {}",
  "class C extends null {}",
  "class C extends 1 {}",
  "class C extends 'a' {}",
  "class C extends `a` {}",
  "class C extends a`b` {}",
  "class C extends [A][0] {}",
  "class C extends /a/ {}",
  "class C { #a; m() { class D extends #a {} } }",
  "class C extends @dec class {} {}",
  "class C extends super {}",
  "class C extends A.B.C<D> {}",
  "class C extends A<T> implements B<U>, C.D<V> {}",
  "class C extends a[0]<T> {}",
  "class C extends A<T>() {}",
  "class C extends a.#b {}",
  "class C extends A, {} {}",
  "class C extends , A {}",
  "class C extends A,, B {}",
  "class C extends A; {}",
  "class C extends A = 1 {}",
  "class C implements a.b {}",
  "class C implements A<T> {}",
  "class C implements a?.b {}",
  "class C implements A() {}",
  "class C implements (A) {}",
  "class C implements typeof A {}",
  "class C implements string {}",
  "class C implements A | B {}",
  "class C implements A & B {}",
  "class C implements A[] {}",
  "class C implements {a: 1} {}",
  "class C implements import('x').A {}",
  "class C implements new () => A {}",
  "class C implements () => void {}",
  "class C implements void {}",
  "class C implements this {}",
  "class C implements null {}",
  "class C implements unique symbol {}",
  "class C implements keyof A {}",
  "class C implements readonly A[] {}",
  "class C implements [A] {}",
  "class C implements 'a' {}",
  "class C implements 1 {}",
  "class C implements -1 {}",
  "class C implements `a` {}",
  "class C implements A extends B ? C : D {}",
  "class C implements A<> {}",
  "class C implements A<T,> {}",
  "class C implements A.B<T>.C {}",
  "class C implements A, B, {}",
  "class C implements , A {}",
  "class C implements A! {}",
  "class C implements a[0] {}",
  "class C implements A<T><U> {}",
  "class C implements infer A {}",
  "class C implements asserts x {}",
  "class C implements x is A {}",
  "class C implements any {}",
  "class C implements -a {}",
  "class C implements A + B {}",
  "class implements {}",
  "class implements implements A {}",
  "(class implements A {})",
  "(class extends A implements B {})",
  "(class C extends A, B {})",
  "class {}",
  "class C<> {}",
  "class C<T,> {}",
  "class C<T> extends A<T> {}",
  "class C",
  "class C {",
  "class C }",
  "class C ;",
  "class C<T {}",
  "class 1 {}",
  "class await {}",
  "class yield {}",
  "class let {}",
  "class static {}",
  "class enum {}",
  "class any {}",
  "class string {}",
]);

g("HI interface heritage: parseHeritageClauses(isInterface), parseTypeHeritageClauseElement", [
  "interface I extends {}",
  "interface I extends A, {}",
  "interface I implements A {}",
  "interface I extends A extends B {}",
  "interface I extends A implements B {}",
  "interface I extends A B {}",
  "interface I extends A() {}",
  "interface I extends typeof A {}",
  "interface I extends A | B {}",
  "interface I extends A[] {}",
  "interface I extends a?.b {}",
  "interface I extends (A) {}",
  "interface I extends A<> {}",
  "interface I extends A<T,> {}",
  "interface I extends void {}",
  "interface I extends {a: 1} {}",
  "interface I extends string {}",
  "interface I extends -1 {}",
  "interface I extends 'a' {}",
  "interface I extends A.B<T>, C {}",
  "interface I extends A<T><U> {}",
  "interface I extends A! {}",
  "interface I extends a[0] {}",
  "interface I extends import('x').A {}",
  "interface I extends this {}",
  "interface I extends null {}",
  "interface I extends new A {}",
  "interface I extends , A {}",
  "interface I extends A,, B {}",
  "interface I extends",
  "interface I",
  "interface I<> {}",
  "interface {}",
  "interface I extends A.#b {}",
  "interface I extends a.b.c<T>.d {}",
  "interface I extends keyof A {}",
  "interface I extends [A] {}",
  "interface I extends () => void {}",
  "interface I extends A & B {}",
  "interface I extends A extends B ? C : D {}",
]);

g("M class member list: parseList(PCClassMembers), parseClassElement", [
  "class C { 1 + 2 }",
  "class C { + }",
  "class C { ) }",
  "class C { = 1 }",
  "class C { , }",
  "class C { . }",
  "class C { => }",
  "class C { ( ) {} }",
  "class C { <T>() {} }",
  "class C { ? }",
  "class C { ! }",
  "class C { : number }",
  "class C { ...a }",
  "class C { / }",
  "class C { `a` }",
  "class C { `a`() {} }",
  "class C { 'a' }",
  "class C { 1n }",
  "class C { 1n() {} }",
  "class C { #a }",
  "class C { [a] }",
  "class C { [a]; [b] = 1; [c]() {} }",
  "class C { [] }",
  "class C { [a, b] }",
  "class C { [a, b]() {} }",
  "class C { [a }",
  "class C { @dec }",
  "class C { @dec ; }",
  "class C { @ }",
  "class C { @dec @dec2 }",
  "class C { @dec x }",
  "class C { public }",
  "class C { public; }",
  "class C { public = 1 }",
  "class C { public() {} }",
  "class C { public: number }",
  "class C { public? }",
  "class C { public! }",
  "class C { public\n x }",
  "class C { static\n x }",
  "class C { static }",
  "class C { static static x }",
  "class C { static static }",
  "class C { static static static x }",
  "class C { x y }",
  "class C { x y() {} }",
  "class C { x; y }",
  "class C { x, y }",
  "class C { x\n y }",
  "class C { x = 1 y = 2 }",
  "class C { x: number y }",
  "class C { x: number = 1 y }",
  "class C { foo bar baz }",
  "class C { function f() {} }",
  "class C { var x }",
  "class C { let x }",
  "class C { const x = 1 }",
  "class C { const x }",
  "class C { class D {} }",
  "class C { if (a) {} }",
  "class C { return }",
  "class C { import x from 'y' }",
  "class C { export x }",
  "class C { export default x }",
  "class C { default x }",
  "class C { type x = 1 }",
  "class C { interface I {} }",
  "class C { namespace N {} }",
  "class C { enum E {} }",
  "class C { is x }",
  "class C { x is y }",
  "class C { declar x }",
  "class C { pubilc x }",
  "class C { in x }",
  "class C { out x }",
  "class C { in }",
  "class C { out }",
  "class C { in = 1 }",
  "class C { * }",
  "class C { * ; }",
  "class C { * m }",
  "class C { * m() }",
  "class C { * * m() {} }",
  "class C { *[a]() {} }",
  "class C { *'a'() {} }",
  "class C { *1() {} }",
  "class C { *#a() {} }",
  "class C { * get x() {} }",
  "class C { get * x() {} }",
  "class C { async * x() {} }",
  "class C { * async x() {} }",
  "class C { m() {} = 1 }",
  "class C { m() {} ; }",
  "class C { m() {} n() {} }",
  "class C { m() {}, n() {} }",
  "class C {;;}",
  "class C { ; x ; }",
  "class C { x }}",
  "class C { x",
  "class C { m() {",
]);

g("MOD modifiers: parseModifiers, tryParseModifier, grammar of the checker", [
  "class C { public public x }",
  "class C { public private x }",
  "class C { readonly readonly x }",
  "class C { static public x }",
  "class C { readonly public x }",
  "class C { readonly static x }",
  "class C { async public m() {} }",
  "class C { async async m() {} }",
  "class C { declare declare x }",
  "class C { declare x = 1 }",
  "class C { declare m() {} }",
  "class C { declare m(): void }",
  "class C { declare get x() { return 1 } }",
  "class C { declare #x }",
  "class C { declare static x }",
  "class C { static declare x }",
  "class C { declare readonly x }",
  "class C { declare public x }",
  "class C { public declare x }",
  "class C { declare async m() {} }",
  "class C { abstract x }",
  "class C { abstract m() }",
  "abstract class C { abstract x }",
  "abstract class C { abstract m() {} }",
  "abstract class C { abstract abstract x }",
  "abstract class C { abstract static x }",
  "abstract class C { static abstract x }",
  "abstract class C { private abstract x }",
  "abstract class C { abstract private x }",
  "abstract class C { abstract public x }",
  "abstract class C { abstract async m() }",
  "abstract class C { async abstract m() }",
  "abstract class C { abstract #x }",
  "abstract class C { abstract get x() }",
  "abstract class C { abstract get x() { return 1 } }",
  "abstract class C { abstract constructor() }",
  "abstract class C { abstract override x }",
  "abstract class C { override abstract x }",
  "abstract class C { abstract declare x }",
  "abstract class C { declare abstract x }",
  "abstract class C { abstract accessor x }",
  "abstract class C { abstract [k: string]: any }",
  "abstract class C { abstract static { } }",
  "class C { export x }",
  "class C { export m() {} }",
  "class C { const x = 1 }",
  "class C { const enum }",
  "class C { override x }",
  "class C { override override x }",
  "class C { override public x }",
  "class C { readonly override x }",
  "class C { accessor x }",
  "class C { accessor accessor x }",
  "class C { accessor m() {} }",
  "class C { accessor readonly x }",
  "class C { readonly accessor x }",
  "class C { accessor static x }",
  "class C { static accessor x }",
  "class C { accessor public x }",
  "class C { accessor declare x }",
  "class C { declare accessor x }",
  "class C { accessor get x() { return 1 } }",
  "class C { accessor constructor() {} }",
  "class C { accessor x? }",
  "class C { accessor x! : number }",
  "class C { accessor #x }",
  "class C { accessor [k: string]: any }",
  "class C { accessor\n x }",
  "class C { accessor }",
  "class C { accessor = 1 }",
  "class C { accessor() {} }",
  "class C { readonly m() {} }",
  "class C { readonly get x() { return 1 } }",
  "class C { readonly constructor() {} }",
  "class C { static constructor() {} }",
  "class C { async constructor() {} }",
  "class C { override constructor() {} }",
  "class C { public constructor() {} }",
  "class C { private constructor() {} }",
  "class C { declare constructor() {} }",
  "class C { *constructor() {} }",
  "class C { get constructor() { return 1 } }",
  "class C { set constructor(v) {} }",
  "class C { async get x() { return 1 } }",
  "class C { async x }",
  "class C { async x = 1 }",
  "class C { async\n x() {} }",
  "class C { async }",
  "class C { async() {} }",
  "class C { static async *m() {} }",
  "class C { public static override readonly x = 1 }",
  "class C { private #x }",
  "class C { public #x }",
  "class C { static #x }",
  "class C { readonly #x }",
  "class C { static static() {} }",
  "class C { static readonly static x }",
  "class C { public static public x }",
  "class C { get get() { return 1 } }",
  "class C { get }",
  "class C { get; }",
  "class C { get = 1 }",
  "class C { get() {} }",
  "class C { get\n x() {} }",
  "class C { static get\n x() {} }",
  "class C { set }",
  "class C { get set x() {} }",
  "class C { static get static() { return 1 } }",
  "class C { public get x() { return 1 } }",
  "class C { get public x() { return 1 } }",
  "class C { protected x }",
  "class C { in out x }",
  "class C { default() {} }",
  "class C { export() {} }",
  "class C { const() {} }",
  "class C { const }",
  "class C { const; }",
  "class C { const = 1 }",
  "class C { enum }",
  "class C { static { } }",
  "class C { static {} static {} }",
  "class C { public static { } }",
  "class C { static static { } }",
  "class C { async static { } }",
  "class C { readonly static { } }",
  "class C { @dec static { } }",
  "class C { static\n{ } }",
  "class C { static { await } }",
  "class C { static { return } }",
  "class C { static { yield } }",
  "class C { static { arguments } }",
  "({ public x: 1 })",
  "({ public x() {} })",
  "({ static x() {} })",
  "({ readonly x: 1 })",
  "({ async x: 1 })",
  "({ async x() {} })",
  "({ get x() })",
  "({ x?: 1 })",
  "({ x!: 1 })",
  "({ m?() {} })",
  "({ m() })",
  "({ declare x: 1 })",
  "({ abstract x: 1 })",
  "({ export x: 1 })",
  "({ @dec x: 1 })",
  "({ accessor x: 1 })",
]);

g("P property declarations: parsePropertyDeclaration, parseSemicolonAfterPropertyName", [
  "class C { x @dec y }",
  "class C { x: number @dec y }",
  "class C { x = 1 @dec y }",
  "class C { x\n@dec y }",
  "class C { x: number (1) }",
  "class C { x: A (1) }",
  "class C { x: number 1 }",
  "class C { x: number y }",
  "class C { x: number = 1 2 }",
  "class C { x = 1 2 }",
  "class C { x 1 }",
  "class C { 'x' y }",
  "class C { 1 y }",
  "class C { [a] y }",
  "class C { #x y }",
  "class C { x? y }",
  "class C { x! y }",
  "class C { x?: number }",
  "class C { x!: number }",
  "class C { x?! }",
  "class C { x!? }",
  "class C { x?!: number }",
  "class C { x!?: number }",
  "class C { x?? }",
  "class C { x!! }",
  "class C { x! }",
  "class C { x! = 1 }",
  "class C { x!: number = 1 }",
  "class C { static x!: number }",
  "class C { x\n!: number }",
  "class C { x\n?: number }",
  "class C { x\n: number }",
  "class C { x\n= 1 }",
  "class C { x =\n 1 }",
  "class C { x = }",
  "class C { x: }",
  "class C { x: ; }",
  "class C { x: = 1 }",
  "class C { x = 1, y = 2 }",
  "class C { x = yield }",
  "function* g() { class C { x = yield } }",
  "async function f() { class C { x = await 1 } }",
  "class C { x = await }",
  "class C { x = a in b }",
  "for (class C { x = a in b } in {}) {}",
  "class C { x = arguments }",
  "class C { constructor }",
  "class C { constructor: number }",
  "class C { constructor = 1 }",
  "class C { constructor; }",
  "class C { 'constructor' }",
  "class C { 'constructor': number }",
  "class C { 'constructor' = 1 }",
  "class C { 'constructor'() {} }",
  "class C { ['constructor'] }",
  "class C { static constructor }",
  "class C { static prototype }",
  "class C { static prototype() {} }",
  "class C { static 'prototype' }",
  "class C { prototype }",
  "class C { #constructor }",
  "class C { #constructor() {} }",
  "class C { x<T> }",
  "class C { x<T>: number }",
  "class C { x?<T>() {} }",
  "class C { x!<T>() {} }",
  "class C { x!() {} }",
  "class C { x?() {} }",
  "class C { x?(): void }",
  "class C { x?: () => void }",
  "class C { x: number, y: number }",
  "class C { x: number; y: number }",
  "class C { const }",
  "class C { var }",
  "class C { let }",
  "class C { interface }",
  "class C { type }",
  "class C { module }",
  "class C { namespace }",
  "class C { declare }",
  "class C { declare; }",
  "class C { declare = 1 }",
  "class C { declare() {} }",
  "class C { abstract }",
  "class C { abstract() {} }",
  "class C { readonly }",
  "class C { readonly() {} }",
  "class C { override }",
  "class C { override() {} }",
  "class C { set() {} }",
  "class C { static() {} }",
  "class C { static = 1 }",
  "class C { static; }",
  "class C { static: number }",
  "class C { static? }",
  "class C { static! : number }",
  "class C { static<T>() {} }",
]);

g("METH methods and bodies: parseMethodDeclaration, parseFunctionBlockOrSemicolon, parseFunctionBlock", [
  "class C { m() }",
  "class C { m(); }",
  "class C { m()\n n() {} }",
  "class C { m() n() {} }",
  "class C { m() x }",
  "class C { m() => 1 }",
  "class C { m(): void => 1 }",
  "class C { m() : }",
  "class C { m(): void }",
  "class C { m(): void; m() {} }",
  "class C { m(): void {} }",
  "class C { m(): void 1 }",
  "class C { m<T>() }",
  "class C { m<>() {} }",
  "class C { m<T,>() {} }",
  "class C { m<T }",
  "class C { m<T>; }",
  "class C { m( }",
  "class C { m(a }",
  "class C { m(a,, b) {} }",
  "class C { m(,) {} }",
  "class C { m(a b) {} }",
  "class C { *m() }",
  "class C { async m() }",
  "class C { async *m(): void }",
  "class C { 'm'() }",
  "class C { 1() }",
  "class C { [a]() }",
  "class C { #m() }",
  "class C { m?() }",
  "class C { m!() }",
  "class C { static m() }",
  "declare class C { m() {} }",
  "declare class C { m(): void }",
  "declare class C { m() }",
  "declare class C { x = 1 }",
  "declare class C { x: number = 1 }",
  "declare class C { readonly x = 1 }",
  "declare class C { get x() { return 1 } }",
  "declare class C { get x(): number }",
  "declare class C { static { } }",
  "declare class C { constructor() {} }",
  "declare class C { *m(): any }",
  "declare class C { async m(): any }",
  "declare class C { [a](): void }",
  "declare class C { @dec m(): void }",
  "function f()",
  "function f();",
  "function f() => 1",
  "function f(): void",
  "function f(): void 1",
  "function f() x",
  "function f()\n x",
  "function f() {} = 1",
  "function f<T>()",
  "function f<>() {}",
  "function* f()",
  "async function f()",
  "declare function f() {}",
  "declare function* f(): any",
  "declare async function f(): any",
  "(function f())",
  "(function() )",
  "(function f() => 1)",
  "export default function()",
  "export default function() x",
  "export function f()",
  "if (a) function f()",
  "({ m() => 1 })",
  "({ m(): void })",
  "({ m() x })",
  "({ get x() x })",
  "({ *m() })",
  "({ async m() })",
]);

g("ACC accessors: parseAccessorDeclaration", [
  "class C { get x }",
  "class C { get x() }",
  "class C { get x(); }",
  "class C { get x() x }",
  "class C { get x() => 1 }",
  "class C { get x(a) { return 1 } }",
  "class C { get x(this: C) { return 1 } }",
  "class C { get x(this: C, a) { return 1 } }",
  "class C { get x<T>() { return 1 } }",
  "class C { get x(): number { return 1 } }",
  "class C { get x(): number }",
  "class C { get x?() { return 1 } }",
  "class C { get x!() { return 1 } }",
  "class C { get x: number }",
  "class C { get x = 1 }",
  "class C { get x; }",
  "class C { get 'x'() { return 1 } }",
  "class C { get 1() { return 1 } }",
  "class C { get [a]() { return 1 } }",
  "class C { get #x() { return 1 } }",
  "class C { get 1n() { return 1 } }",
  "class C { get *x() {} }",
  "class C { get async x() { return 1 } }",
  "class C { get static x() { return 1 } }",
  "class C { get get x() { return 1 } }",
  "class C { set x }",
  "class C { set x() {} }",
  "class C { set x(a, b) {} }",
  "class C { set x(a) }",
  "class C { set x(a): void {} }",
  "class C { set x(...a) {} }",
  "class C { set x(a?) {} }",
  "class C { set x(a = 1) {} }",
  "class C { set x(this: C, a) {} }",
  "class C { set x(this: C) {} }",
  "class C { set x<T>(a) {} }",
  "class C { set x(public a) {} }",
  "class C { set x([a]) {} }",
  "class C { set x(a,) {} }",
  "class C { static get x() }",
  "class C { static set x(a) }",
  "abstract class C { abstract get x(): number; abstract set x(v: number) }",
  "declare class C { get x(): number; set x(v: number) }",
  "declare class C { get x() }",
  "({ get x(a) { return 1 } })",
  "({ set x() {} })",
  "({ set x(a, b) {} })",
  "({ get x<T>() { return 1 } })",
  "({ set x(a): void {} })",
  "({ get x(): number { return 1 } })",
  "({ get x })",
  "({ get: 1, set: 2 })",
  "({ get x: 1 })",
  "({ get })",
  "({ get x?() { return 1 } })",
]);

g("CTOR constructors: tryParseConstructorDeclaration", [
  "class C { constructor() }",
  "class C { constructor(); constructor() {} }",
  "class C { constructor<T>() {} }",
  "class C { constructor(): void {} }",
  "class C { constructor(): C {} }",
  "class C { constructor() => 1 }",
  "class C { constructor() x }",
  "class C { constructor?() {} }",
  "class C { constructor!() {} }",
  "class C { constructor(public x) {} }",
  "class C { constructor(public x?) {} }",
  "class C { constructor(public x = 1) {} }",
  "class C { constructor(public ...x) {} }",
  "class C { constructor(public [x]) {} }",
  "class C { constructor(public {x}) {} }",
  "class C { constructor(public public x) {} }",
  "class C { constructor(public private x) {} }",
  "class C { constructor(readonly x) {} }",
  "class C { constructor(readonly readonly x) {} }",
  "class C { constructor(public readonly x) {} }",
  "class C { constructor(readonly public x) {} }",
  "class C { constructor(override x) {} }",
  "class C { constructor(public override x) {} }",
  "class C { constructor(override public x) {} }",
  "class C { constructor(static x) {} }",
  "class C { constructor(declare x) {} }",
  "class C { constructor(abstract x) {} }",
  "class C { constructor(async x) {} }",
  "class C { constructor(export x) {} }",
  "class C { constructor(accessor x) {} }",
  "class C { constructor(const x) {} }",
  "class C { constructor(in x) {} }",
  "class C { constructor(out x) {} }",
  "class C { constructor(public) {} }",
  "class C { constructor(public, y) {} }",
  "class C { constructor(public = 1) {} }",
  "class C { constructor(public: number) {} }",
  "class C { constructor(public?) {} }",
  "class C { constructor(public\n x) {} }",
  "class C { constructor(readonly) {} }",
  "class C { constructor(this: C) {} }",
  "class C { constructor(public this) {} }",
  "class C { constructor(public x); constructor(x) {} }",
  "class C { constructor(@dec x) {} }",
  "class C { constructor(@dec public x) {} }",
  "class C { constructor(public @dec x) {} }",
  "class C { constructor(private x: number, protected y = 1, public readonly z?: C) {} }",
  "class C { 'constructor'() {} }",
  "class C { 'constructor'(public x) {} }",
  "class C { \"constructor\"(): void {} }",
  "class C { constructor() {} constructor() {} }",
  "class C { static 'constructor'() {} }",
  "class C { ['constructor']() {} }",
  "declare class C { constructor(public x) }",
  "declare class C { constructor(): void }",
  "class C { m(public x) {} }",
  "class C { m(readonly x) {} }",
  "class C { m(public) {} }",
  "function f(public x) {}",
  "function f(readonly x) {}",
  "function f(private x, y) {}",
  "function f(public) {}",
  "function f(public x?: number) {}",
  "function f(public public x) {}",
  "function f(static x) {}",
  "function f(override x) {}",
  "function f(declare x) {}",
  "function f(abstract x) {}",
  "function f(async x) {}",
  "function f(export x) {}",
  "function f(accessor x) {}",
  "function f(const x) {}",
  "function f(in x) {}",
  "function f(out x) {}",
  "function f(default x) {}",
  "(function(public x) {})",
  "(public x) => 1",
  "(readonly x) => 1",
  "(public x: number) => 1",
  "async (public x) => 1",
  "(public) => 1",
  "(public, y) => 1",
  "({ m(public x) {} })",
  "({ set x(public a) {} })",
  "declare function f(public x): void",
  "function f(public x): void; function f(x) {}",
  "let f: (public x) => void",
  "let f: new (public x) => void",
  "let f: { (public x): void }",
  "let f: { m(public x): void }",
  "interface I { m(public x): void }",
  "interface I { new (public x): void }",
]);

g("IDX index signatures: isIndexSignature, parseIndexSignatureDeclaration", [
  "class C { [k: string]: any }",
  "class C { [k: string]: any; }",
  "class C { [k: string]: any, }",
  "class C { [k: string]: any x }",
  "class C { [k: string] }",
  "class C { [k: string]; }",
  "class C { [k: string]: }",
  "class C { [k: string] = 1 }",
  "class C { [k: string]: any = 1 }",
  "class C { [k: string]() {} }",
  "class C { [k: string]?: any }",
  "class C { [k: string]!: any }",
  "class C { [k]: any }",
  "class C { [k?: string]: any }",
  "class C { [k?]: any }",
  "class C { [k?, j]: any }",
  "class C { [k, j]: any }",
  "class C { [k: string, j: number]: any }",
  "class C { [k: string,]: any }",
  "class C { [...k]: any }",
  "class C { [...k: string[]]: any }",
  "class C { []: any }",
  "class C { [] }",
  "class C { [public k: string]: any }",
  "class C { [public k]: any }",
  "class C { [readonly k: string]: any }",
  "class C { [static k: string]: any }",
  "class C { [k: string = 1]: any }",
  "class C { [k = 1]: any }",
  "class C { [this: string]: any }",
  "class C { [@dec k: string]: any }",
  "class C { [{a}: string]: any }",
  "class C { [[a]: string]: any }",
  "class C { static [k: string]: any }",
  "class C { readonly [k: string]: any }",
  "class C { static readonly [k: string]: any }",
  "class C { public [k: string]: any }",
  "class C { private [k: string]: any }",
  "class C { declare [k: string]: any }",
  "class C { async [k: string]: any }",
  "class C { export [k: string]: any }",
  "class C { override [k: string]: any }",
  "class C { @dec [k: string]: any }",
  "class C { get [k: string]: any }",
  "class C { *[k: string]: any }",
  "class C { [k: 'a']: any }",
  "class C { [k: T]: any }",
  "class C { [k: string | number]: any }",
  "class C { [k in K]: any }",
  "class C { [k: string]: any\n [j: number]: any }",
  "class C { [k: string]: any [j: number]: any }",
  "class C { [async x => x]: any }",
  "class C { [await]: any }",
  "class C { [yield]: any }",
  "class C { [await: string]: any }",
  "class C { [public]: any }",
  "class C { [public: string]: any }",
  "class C { [a ? b : c]: any }",
  "class C { [a ?? b]: any }",
  "class C { [a?.b]: any }",
  "class C { [k: string }",
  "class C { [k: string",
  "class C { [k: }",
  "({ [k: string]: 1 })",
  "interface I { [k: string]: any; [j?: number]: any; [public l: string]: any }",
  "let x: { [k]: any }",
  "let x: { [k: string] }",
  "let x: { [k?: string]: any }",
  "let x: { []: any }",
  "let x: { [...k]: any }",
  "let x: { [k: string, j: number]: any }",
  "let x: { [k: string,]: any }",
  "let x: { [k: string = 1]: any }",
  "let x: { static [k: string]: any }",
  "let x: { public [k: string]: any }",
]);

g("PAR parameters: parseParameters, parseParametersWorker, parseParameter, parseNameOfParameter", [
  "function f(",
  "function f(a",
  "function f(a,",
  "function f(a b) {}",
  "function f(a, , b) {}",
  "function f(,) {}",
  "function f(a,) {}",
  "function f(a;) {}",
  "function f(a: ) {}",
  "function f(a = ) {}",
  "function f(a?) {}",
  "function f(a??) {}",
  "function f(a?: number = 1) {}",
  "function f(a? = 1) {}",
  "function f(a?, b) {}",
  "function f(a = 1, b) {}",
  "function f(a!) {}",
  "function f(a!: number) {}",
  "function f(...a) {}",
  "function f(...a, b) {}",
  "function f(...a,) {}",
  "function f(...a = []) {}",
  "function f(...a?) {}",
  "function f(...a?: number[]) {}",
  "function f(...a: number[] = []) {}",
  "function f(......a) {}",
  "function f(... ...a) {}",
  "function f(...) {}",
  "function f(a, ...) {}",
  "function f(...[a, b]) {}",
  "function f(...{a}) {}",
  "function f(...a, ...b) {}",
  "declare function f(...a,): void",
  "declare function f(...a, b): void",
  "function f(...a,): void; function f() {}",
  "function f(1) {}",
  "function f('a') {}",
  "function f(a.b) {}",
  "function f(a + b) {}",
  "function f(-a) {}",
  "function f(!a) {}",
  "function f(~a) {}",
  "function f(typeof a) {}",
  "function f(void a) {}",
  "function f(new a) {}",
  "function f(delete a) {}",
  "function f(class) {}",
  "function f(function) {}",
  "function f(if) {}",
  "function f(return) {}",
  "function f(true) {}",
  "function f(false) {}",
  "function f(null) {}",
  "function f(super) {}",
  "function f(import) {}",
  "function f(enum) {}",
  "function f(var) {}",
  "function f(with) {}",
  "function f(in) {}",
  "function f(of) {}",
  "function f(yield) {}",
  "function f(await) {}",
  "function* f(yield) {}",
  "async function f(await) {}",
  "function f(let) {}",
  "function f(static) {}",
  "function f(implements) {}",
  "function f(interface) {}",
  "function f(package) {}",
  "function f(arguments) {}",
  "function f(eval) {}",
  "function f(a, a) {}",
  "function f(#a) {}",
  "class C { #a; m(#a) {} }",
  "function f(this) {}",
  "function f(this: C) {}",
  "function f(this: C, a) {}",
  "function f(a, this: C) {}",
  "function f(this?: C) {}",
  "function f(this = 1) {}",
  "function f(this: C = 1) {}",
  "function f(...this) {}",
  "function f(this, this) {}",
  "function f(public this: C) {}",
  "function f(@dec this: C) {}",
  "class C { m(@dec this: C) {} }",
  "class C { m(public this: C) {} }",
  "class C { m(readonly this) {} }",
  "function f(this.a) {}",
  "function f(this,) {}",
  "function f(this: ) {}",
  "(this: C) => 1",
  "(this) => 1",
  "(a, this: C) => 1",
  "function f(@dec a) {}",
  "class C { m(@dec a) {} }",
  "class C { m(@dec) {} }",
  "class C { m(@dec ...a) {} }",
  "class C { m(@dec @dec2 a) {} }",
  "class C { m(@dec public a) {} }",
  "class C { m(@dec [a]) {} }",
  "class C { m(@dec {a}) {} }",
  "class C { m(@ a) {} }",
  "class C { m(a @dec) {} }",
  "(@dec a) => 1",
  "(function(@dec a) {})",
  "({ m(@dec a) {} })",
  "function f([a, b]: number[], {c, d}: any) {}",
  "function f([a b]) {}",
  "function f([a,,b]) {}",
  "function f([...a, b]) {}",
  "function f([...a,]) {}",
  "function f([a = ]) {}",
  "function f([1]) {}",
  "function f([a.b]) {}",
  "function f([a: number]) {}",
  "function f([a?]) {}",
  "function f([public a]) {}",
  "function f([this]) {}",
  "function f([#a]) {}",
  "function f([) {}",
  "function f([a) {}",
  "function f({a b}) {}",
  "function f({a,,b}) {}",
  "function f({...a, b}) {}",
  "function f({...a,}) {}",
  "function f({...{a}}) {}",
  "function f({...[a]}) {}",
  "function f({...a.b}) {}",
  "function f({a: 1}) {}",
  "function f({a: b.c}) {}",
  "function f({a: number}) {}",
  "function f({a?}) {}",
  "function f({1}) {}",
  "function f({'a'}) {}",
  "function f({1: a, 'b': c, [d]: e, 1n: g}) {}",
  "function f({a = }) {}",
  "function f({a: }) {}",
  "function f({class}) {}",
  "function f({class: a}) {}",
  "function f({public}) {}",
  "function f({public a}) {}",
  "function f({this}) {}",
  "function f({#a}) {}",
  "function f({#a: b}) {}",
  "function f({a(){}}) {}",
  "function f({get a(){}}) {}",
  "function f({) {}",
  "function f({a) {}",
  "function f({a:}) {}",
  "function f({[a]}) {}",
  "function f({[a] = 1}) {}",
  "function f({yield}) {}",
  "function f({await}) {}",
  "function f(a: number, b?: string, ...c: any[]): void {}",
  "function f(a: number,): void {}",
  "function f<T>(a: T = 1 as T) {}",
  "function f(a: number = 1, b = a) {}",
  "function f(a = b = c) {}",
  "function f(a = 1, 2) {}",
  "function f(a = yield) {}",
  "function* f(a = yield) {}",
  "async function f(a = await 1) {}",
  "function f(a = await) {}",
  "function f(a: number b) {}",
  "function f(a: number = 1 b) {}",
  "function f(a?: number b) {}",
  "function f(a ? b) {}",
  "function f(a ? : b) {}",
  "function f(a : b : c) {}",
  "function f(a = 1 = 2) {}",
  "function f(a) {} (1)",
  "function f(a]) {}",
  "function f(a} {}",
  "function f(a) ]",
  "function f[a]() {}",
  "function f{}",
  "function f",
  "function",
  "function () {}",
  "function 1() {}",
  "function class() {}",
  "function static() {}",
  "function await() {}",
  "function yield() {}",
  "function* yield() {}",
  "async function await() {}",
  "function let() {}",
  "function f.g() {}",
  "function #f() {}",
  "(function #f() {})",
  "(function await() {})",
  "(async function await() {})",
  "(function* yield() {})",
  "(function 1() {})",
  "(function class() {})",
]);

g("PAR2 arrow parameters and other callers of parseParameters", [
  "(a?) => 1",
  "(a?: number) => 1",
  "(a?, b) => 1",
  "(a? = 1) => 1",
  "(...a, b) => 1",
  "(...a,) => 1",
  "(...a = []) => 1",
  "(...a?) => 1",
  "(a,) => 1",
  "(a b) => 1",
  "(a, , b) => 1",
  "(,) => 1",
  "(a: ) => 1",
  "(1) => 1",
  "(a.b) => 1",
  "(a!) => 1",
  "(#a) => 1",
  "([a], {b}) => 1",
  "({a: 1}) => 1",
  "([a.b]) => 1",
  "(a = 1, b) => 1",
  "async (a?) => 1",
  "async (...a, b) => 1",
  "async (this: C) => 1",
  "<T>(a?) => 1",
  "<T>(public a) => 1",
  "<T>(...a, b) => 1",
  "<T>(this: C) => 1",
  "(a): void => 1",
  "(a): => 1",
  "(a) : void",
  "(a?) : void => 1",
  "a? => 1",
  "async a? => 1",
  "...a => 1",
  "public a => 1",
  "a: number => 1",
  "(a)\n=> 1",
  "a\n=> 1",
  "async\n(a) => 1",
  "async a\n=> 1",
  "(yield) => 1",
  "(await) => 1",
  "async (await) => 1",
  "function* g() { (yield) => 1 }",
  "async function f() { (await) => 1 }",
  "(arguments) => 1",
  "(eval) => 1",
  "(a, a) => 1",
  "(static) => 1",
  "(let) => 1",
  "(class) => 1",
  "(enum) => 1",
]);

g("DEC decorators: parseDecorator, parseDecoratorExpression, where they stand", [
  "@dec class C {}",
  "@dec export class C {}",
  "export @dec class C {}",
  "@dec export default class {}",
  "export default @dec class {}",
  "@dec export @dec2 class C {}",
  "@dec abstract class C {}",
  "@dec declare class C {}",
  "abstract @dec class C {}",
  "declare @dec class C {}",
  "@dec function f() {}",
  "@dec let x",
  "@dec interface I {}",
  "@dec type T = 1",
  "@dec enum E {}",
  "@dec namespace N {}",
  "@dec import x from 'y'",
  "@dec export * from 'y'",
  "@dec",
  "@dec;",
  "@ class C {}",
  "@1 class C {}",
  "@(a) class C {}",
  "@a.b class C {}",
  "@a.b() class C {}",
  "@a().b class C {}",
  "@a()() class C {}",
  "@a?.b class C {}",
  "@a?.() class C {}",
  "@a[0] class C {}",
  "@a<T> class C {}",
  "@a<T>() class C {}",
  "@a! class C {}",
  "@a.#b class C {}",
  "@new A class C {}",
  "@new A() class C {}",
  "@a`b` class C {}",
  "@class {} class C {}",
  "@function() {} class C {}",
  "@this class C {}",
  "@super class C {}",
  "@import('a') class C {}",
  "@import.meta class C {}",
  "@-a class C {}",
  "@a + b class C {}",
  "@a = b class C {}",
  "@a => a class C {}",
  "@await class C {}",
  "async function f() { @await class C {} }",
  "async function f() { @await x class C {} }",
  "async function f() { @(await x) class C {} }",
  "@yield class C {}",
  "function* g() { @yield class C {} }",
  "class C { @dec m() {} }",
  "class C { @dec() m() {} }",
  "class C { @dec x }",
  "class C { @dec x = 1 }",
  "class C { @dec static x }",
  "class C { static @dec x }",
  "class C { public @dec x }",
  "class C { @dec public @dec2 x }",
  "class C { @dec public static x }",
  "class C { public @dec static x }",
  "class C { @dec get x() { return 1 } }",
  "class C { get @dec x() { return 1 } }",
  "class C { @dec get x() { return 1 } @dec set x(v) {} }",
  "class C { @dec constructor() {} }",
  "class C { @dec 'constructor'() {} }",
  "class C { @dec static {} }",
  "class C { @dec ; }",
  "class C { @dec [k: string]: any }",
  "class C { @dec m(): void; m() {} }",
  "class C { @dec m(): void }",
  "class C { @dec declare x }",
  "class C { @dec abstract x }",
  "abstract class C { @dec abstract x }",
  "abstract class C { @dec abstract m(): void }",
  "class C { @dec #x }",
  "class C { @dec #m() {} }",
  "class C { @dec accessor x }",
  "class C { @dec ['x']() {} }",
  "class C { @dec['x']() {} }",
  "class C { @dec\n['x']() {} }",
  "class C { @a.b['x']() {} }",
  "class C { @a()['x']() {} }",
  "class C { @(a)['x']() {} }",
  "class C { @dec * m() {} }",
  "class C { @dec async m() {} }",
  "class C { @dec async * m() {} }",
  "class C { @a @b @c m() {} }",
  "class C { @a\n@b\nm() {} }",
  "class C { m(@a @b x) {} }",
  "(@dec class {})",
  "(@dec class C extends D {})",
  "x = @dec class {}",
  "export default (@dec class {})",
  "(@dec function() {})",
  "(@dec () => 1)",
  "(@dec 1)",
  "[@dec class {}]",
  "f(@dec class {})",
  "({ @dec m() {} })",
  "({ @dec x: 1 })",
  "({ @dec get x() { return 1 } })",
  "enum E { @dec A }",
  "interface I { @dec m(): void }",
  "let x: { @dec m(): void }",
  "function f(@dec a) {}",
  "class C { constructor(@dec a) {} }",
]);

g("DTS the same in a declaration file", [
  "class C { m() {} }",
  "declare class C { m(): void; x: number; constructor(a: number); get y(): number; [k: string]: any }",
  "declare class C extends A, B {}",
  "declare class C { static { } }",
  "declare class C { m(...a,): void }",
  "declare function f(...a,): void",
  "export declare class C { private x; protected y?; readonly z: number; static s; }",
  "declare class C { x = 1 }",
  "declare class C { constructor(public x) }",
  "declare abstract class C { abstract m(): void; abstract x: number }",
], "dts");

process.stdout.write(JSON.stringify(out, null, 0));
