// Research scratch: the own cases of getter-return (edge: JavaScript shapes of Bun's tree; ts: TypeScript), and ESLint's answers.
// usage: node cases/make.cjs     writes cases/edge-getter-return.json, cases/ts-getter-return.json, answers/*.jsonl
"use strict";
const fs = require("fs");
const path = require("path");
const { verify } = require("../../round2-oracle/proto-1b/eslint-side.cjs");
const D = "Object.defineProperty(a, 'b', ";
const edge = [
	// Where the report is: the start of the property or of the class member.
	"var o = { get a() {} }",
	"var o = { get\n a() {} }",
	"var o = { get // c\n a() {} }",
	"var o = { get /* c */ a() {} }",
	"var o = { /* c */ get a() {} }",
	"var o = { get [b]() {} }",
	"var o = { get [ (b) ]() {} }",
	"var o = { get 'c d'() {} }",
	"var o = { get 1e3() {} }",
	"var o = { get 0x10() {} }",
	"var o = { get 1n() {} }",
	"var o = { get get() {} }",
	"var o = { get set() {}, set get(v) {} }",
	"class A { get a() {} }",
	"class A { static get a() {} }",
	"class A { static\n get\n a() {} }",
	"class A { get #p() {} static get #q() {} static get [x]() {} }",
	"class A { static get 'a'() {} get 1() {} }",
	"class A { static { } get x() { return } }",
	"(class { get a() {} })",
	"class A { get; get get() {} }",
	// The property descriptor forms.
	D + "{ get: function () {} })",
	D + "{ get: function () { return; } })",
	D + "{ get() {} })",
	D + "{ get: () => {} })",
	D + "{ get: () => 1 })",
	D + "{ get: async () => {} })",
	D + "{ async get() {} })",
	D + "{ *get() {} })",
	D + "{ async *get() {} })",
	D + "{ get: async function* () {} })",
	D + "{ ['get']: function foo() {} })",
	D + "{ [ ('get') ]() {} })",
	D + "{ [`get`]: function () {} })",
	D + "{ [`g${e}t`]: function () {} })",
	D + "{ 'get': function () {} })",
	D + "{ get get() {} })",
	D + "{ set get(v) {} })",
	D + "{ get })",
	D + "{ get: function () {}, ...x })",
	D + "{ ...x, get: function () {} })",
	D + "({ get: function () {} }))",
	D + "{ get: (function () {}) })",
	D + "{ get: (() => {}) })",
	D + "{ getter: function () {} })",
	D + "{ get: foo ? function () {} : function () {} })",
	D + "{ get: function () {} }, extra)",
	"Object.defineProperty(a, { get: function () {} })",
	"Object.defineProperty({ get: function () {} })",
	"Object.defineProperty(...a, { get() {} })",
	"Object.defineProperty(a, ...b, { get() {} })",
	"Object['defineProperty'](a, 'b', { get() {} })",
	"Object[`defineProperty`](a, 'b', { get() {} })",
	"Object[defineProperty](a, 'b', { get() {} })",
	"Object.defineProperty?.(a, 'b', { get() {} })",
	"Object?.defineProperty?.(a, 'b', { get() {} })",
	"(Object).defineProperty(a, 'b', { get() {} })",
	"(Object.defineProperty)(a, 'b', { get() {} })",
	"new Object.defineProperty(a, 'b', { get() {} })",
	"Object.defineProperty`x`",
	"window.Object.defineProperty(a, 'b', { get() {} })",
	"Object.prototype.defineProperty(a, 'b', { get() {} })",
	"Reflect.defineProperty(a, 'b', { get() {} })",
	"Reflect['defineProperty'](a, 'b', { get: () => {} })",
	"Reflect.defineProperties(a, { b: { get() {} } })",
	"Reflect.create(a, { b: { get() {} } })",
	"Object.defineProperties(a, { b: { get() {} }, ['c']: { get() {} }, d: ({ get() {} }), ...e, f() {}, get g() {} })",
	"Object.defineProperties(a, { b: { c: { get() {} } } })",
	"Object.defineProperties({ b: { get() {} } }, { c: { value: 1 } })",
	"Object.create(a, { b: { get: function () { if (x) return 1; } } })",
	"Object.create({ b: { get() {} } })",
	"Object.create(a, b, { c: { get() {} } })",
	"Object.freeze({ get: function () {} })",
	// A declaration of the name anywhere in the file.
	"var Object; " + D + "{ get() {} })",
	"function Object() {} " + D + "{ get() {} })",
	"class Object {} " + D + "{ get() {} })",
	"import Object from 'x'; " + D + "{ get() {} })",
	"import * as Reflect from 'x'; Reflect.defineProperty(a, 'b', { get() {} })",
	"function f() { var Object; } " + D + "{ get() {} })",
	"function f(Reflect) {} Reflect.defineProperty(a, 'b', { get() {} })",
	"try {} catch (Object) {} " + D + "{ get() {} })",
	"var Reflect; " + D + "{ get() {} })",
	"var Object; var o = { get a() {} }",
	"/* globals Object:off */ " + D + "{ get() {} })",
	"/* eslint-disable getter-return */ var o = { get a() {} }",
	// The code path of the getter.
	"var o = { get a() { return; function f() { return 1; } } }",
	"var o = { get a() { function f() { return 1; } } }",
	"var o = { get a() { return (() => { return; })(); } }",
	"var o = { get a() { var f = () => 1; } }",
	"var o = { get a() { return x ? 1 : 2; } }",
	"var o = { get a() { if (x) return 1; else return 2; } }",
	"var o = { get a() { if (x) { return; } else { return 1; } } }",
	"var o = { get a() { if (x) return 1; } }",
	"var o = { get a() { x && y; return 1; } }",
	"var o = { get a() { if (x && y || z) return 1; } }",
	"var o = { get a() { if (x ?? y) return 1; else return 2; } }",
	"var o = { get a() { x ||= 1; x &&= 2; x ??= 3; } }",
	"var o = { get a() { while (true) {} } }",
	"var o = { get a() { while (true) { if (x) break; } } }",
	"var o = { get a() { while (x) { return 1; } } }",
	"var o = { get a() { do { return 1; } while (x); } }",
	"var o = { get a() { do { if (x) continue; return 1; } while (y); } }",
	"var o = { get a() { for (;;) {} } }",
	"var o = { get a() { for (;;) { if (x) break; } } }",
	"var o = { get a() { for (var i = 0; i < n; i++) { return 1; } } }",
	"var o = { get a() { for (var k in x) { return 1; } } }",
	"var o = { get a() { for (var v of x) { return 1; } return 2; } }",
	"var o = { get a() { L: for (;;) { for (;;) { break L; } } } }",
	"var o = { get a() { L: { if (x) break L; return 1; } } }",
	"var o = { get a() { throw new Error(); } }",
	"var o = { get a() { if (x) throw 1; return 2; } }",
	"var o = { get a() { switch (x) { case 1: return 1; default: return 2; } } }",
	"var o = { get a() { switch (x) { case 1: return 1; } } }",
	"var o = { get a() { switch (x) { default: return 2; case 1: } } }",
	"var o = { get a() { switch (x) { case 1: case 2: return 1; default: throw 0; } } }",
	"var o = { get a() { switch (x) { case 1: break; default: return 2; } } }",
	"var o = { get a() { try { return 1; } finally { } } }",
	"var o = { get a() { try { return 1; } catch (e) { } } }",
	"var o = { get a() { try { foo(); return 1; } catch (e) { } } }",
	"var o = { get a() { try { foo(); return 1; } catch (e) { return 2; } } }",
	"var o = { get a() { try { foo(); } catch (e) { return 2; } finally { bar(); } } }",
	"var o = { get a() { try { foo(); } finally { return 1; } } }",
	"var o = { get a() { try { return foo; } catch { } } }",
	"var o = { get a() { try { return a.b; } catch { return; } } }",
	"var o = { get a() { try { return new F; } catch { throw 1; } } }",
	"var o = { get a() { try { var [x = 1] = y; return 1; } catch { } } }",
	"var o = { get a() { try { ({ x } = 1); return 1; } catch { } } }",
	"var o = { get a() { try { return 1; } catch { } } }",
	"var o = { get a() { return a?.b; } }",
	"var o = { get a() { a?.b(); } }",
	"var o = { get a() { return; } }",
	"var o = { get a() { return void 0; } }",
	"var o = { get a() { return\n1; } }",
	"var o = { get a() { { return 1; } } }",
	"var o = { get a() { debugger; ; } }",
	"var o = { get a() { 'use strict'; } }",
	"var o = { get a() { with (x) { return 1; } } }",
	"var o = { get a() { class B { get b() {} } return 1; } }",
	"var o = { get a() { return { get b() {} }; } }",
	"class A { x = function () {}; get = () => {}; static get = function () {}; }",
	"class A { get = { get() {} }; }",
	"class A { static { var o = { get a() {} }; } }",
	"class A { get a() { return class { static { return1; } }; } }",
	"function* g() { var o = { get a() { return 1; } }; yield o; }",
	"var o = { get a() { return 1; }, get b() {}, get c() { return; }, get d() { if (x) return 1; } }",
	"var o = { get a() { return <div>{x}</div>; } }",
];
const ts = [
	"class A { get x(): number {} }",
	"class A { @dec get x() {} }",
	"class A { @dec\n  static get x() {} }",
	"class A { public static get x() {} }",
	"class A { private get x(): number {} }",
	"class A { protected static override get x() {} }",
	"abstract class A { abstract get x(): number; get y() {} }",
	"class A { get x(): number; get x() {} }",
	"class A { get x<T>() {} }",
	"class A { accessor x = 1; get y() { return; } }",
	"class A { get x() { return <any>undefined; } get y() { return } }",
	"class A { get x() { return y as number; } get z() { return y!; } }",
	"const o = { get x(): number {} }",
	"const o = { get x(): number { return 1 as number; } }",
	"Object.defineProperty(a, 'b', { get: function () {} } as PropertyDescriptor)",
	"Object.defineProperty(a, 'b', { get: (function () {}) as any })",
	"Object.defineProperty(a, 'b', { get: function () {}! })",
	"Object.defineProperty(a, 'b', <PropertyDescriptor>{ get: function () {} })",
	"Object.defineProperty(a, 'b', { get: function () {} } satisfies PropertyDescriptor)",
	"Object.defineProperty(a, 'b', ({ get: function () {} }))",
	"(Object as any).defineProperty(a, 'b', { get: function () {} })",
	"Object!.defineProperty(a, 'b', { get: function () {} })",
	"Object.defineProperty!(a, 'b', { get: function () {} })",
	"Object.defineProperty<any>(a, 'b', { get: function () {} })",
	"Object.defineProperty(a, 'b', { get: function (): number {} })",
	"Object.defineProperty(a, 'b', { get: <T>() => {} })",
	"Object.defineProperty(a, 'b', { get(this: Foo) {} })",
	"Object.defineProperties(a, { b: { get() {} } as PropertyDescriptor, c: <any>{ get() {} }, d: { get() {} }! })",
	"Object.create(a, { b: { get() {} } } as PropertyDescriptorMap)",
	"declare const Object: any; Object.defineProperty(a, 'b', { get() {} })",
	"import type Object from 'x'; Object.defineProperty(a, 'b', { get() {} })",
	"import { type Object } from 'x'; Object.defineProperty(a, 'b', { get() {} })",
	"import Object = require('x'); Object.defineProperty(a, 'b', { get() {} })",
	"type Object = number; Object.defineProperty(a, 'b', { get() {} })",
	"interface Object { a: 1 } Object.defineProperty(a, 'b', { get() {} })",
	"namespace N { export const Object = 1 } Object.defineProperty(a, 'b', { get() {} })",
	"namespace Object { export const a = 1 } Object.defineProperty(a, 'b', { get() {} })",
	"enum Object { A } Object.defineProperty(a, 'b', { get() {} })",
	"declare enum Reflect { A } Reflect.defineProperty(a, 'b', { get() {} })",
	"declare function Object(): void; Object.defineProperty(a, 'b', { get() {} })",
	"declare class Object {} Object.defineProperty(a, 'b', { get() {} })",
	"function f<Object>() { Object.defineProperty(a, 'b', { get() {} }) }",
	"class A { get x() { try { let v: Foo = 1; return 1; } catch { } } }",
	"class A { get x() { try { type T = number; return 1; } catch { } } }",
	"class A { get x() { try { return 1 as Foo; } catch { } } }",
	"class A { get x() { try { let v: number = 1; return 1; } catch { } } }",
	"class A { get x() { enum E { A } } }",
	"class A { get x(): never { throw new Error(); } }",
	"class A { constructor(private y: number) {} get x() { return this.y; } }",
	"declare class A { get x(): number; }",
	"interface I { get x(): number; }",
	"type T = { get x(): number };",
].map(code => ({ code, ext: "ts" }));
const tsx = [{ code: "class A { get x() { return <div<T>>{y}</div>; } get z() {} }", ext: "tsx" }];
fs.mkdirSync(path.join(__dirname, "../answers"), { recursive: true });
const write = (name, list) => {
	fs.writeFileSync(path.join(__dirname, `${name}.json`), "[\n" + list.map(c => JSON.stringify(c)).join(",\n") + "\n]\n");
	const lines = [];
	for (const raw of list) {
		const c = typeof raw === "string" ? { code: raw, ext: "js" } : raw;
		const r = verify(c.code, c.ext, ["getter-return"]);
		lines.push(JSON.stringify({ code: c.code, ext: r.ext, fatal: r.fatal ? r.fatal.message : undefined, eslint: r.messages.map(m => ({ line: m.line, column: m.column, message: m.message })) }));
	}
	fs.writeFileSync(path.join(__dirname, "../answers", `${name}.jsonl`), lines.join("\n") + "\n");
	const rejected = lines.filter(l => JSON.parse(l).fatal).length;
	const reports = lines.reduce((n, l) => n + JSON.parse(l).eslint.length, 0);
	console.log(`${name}: ${list.length} cases, ${rejected} that ESLint's parser rejects, ${reports} reports`);
};
write("edge-getter-return", edge);
write("ts-getter-return", [...ts, ...tsx]);
