#!/usr/bin/env python3
# Builds the ground-truth program of the shared foundation: the reference's own functions, cut out of its files by
# name, with the standard library only. The cut-out text is verbatim but for package qualifiers.
# usage: python3 build.py <typescript-go checkout> <output directory>      needs Go 1.24 or later, no network
import os, re, shutil, subprocess, sys

ref, out = sys.argv[1], sys.argv[2]
here = os.path.dirname(os.path.abspath(__file__))
shutil.rmtree(out, ignore_errors=True)
os.makedirs(out)
open(os.path.join(out, "go.mod"), "w").write("module gt\n\ngo 1.24\n")

# Whole packages that import the standard library only.
for pkg in ["stringutil", "tspath"]:
    os.makedirs(os.path.join(out, pkg))
    src = os.path.join(ref, "internal", pkg)
    for name in sorted(os.listdir(src)):
        if not name.endswith(".go") or name.endswith("_test.go") or name == "generate.go":
            continue
        text = open(os.path.join(src, name)).read()
        text = text.replace('"github.com/microsoft/typescript-go/internal/stringutil"', '"gt/stringutil"')
        open(os.path.join(out, pkg, name), "w").write(text)

def declarations(path):
    # Top-level declarations of a gofmt'ed file: name -> text, with the comment lines above it.
    lines = open(path).read().split("\n")
    decls = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^(func|type|var|const)\b(.*)$", line)
        if not m:
            i += 1
            continue
        start = i
        while start > 0 and lines[start - 1].startswith("//"):
            start -= 1
        kind, rest = m.group(1), m.group(2)
        end = i
        opens_block = line.rstrip().endswith("{") or line.rstrip().endswith("(")
        if opens_block:
            closer = "}" if line.rstrip().endswith("{") else ")"
            end = i + 1
            while not lines[end].startswith(closer):
                end += 1
        text = "\n".join(lines[start:end + 1])
        if kind == "func":
            fm = re.match(r"^\s*(?:\(([^)]*)\)\s*)?([A-Za-z_0-9]+)", rest)
            recv, name = fm.group(1), fm.group(2)
            if recv:
                name = recv.split()[-1].lstrip("*").split("[")[0] + "." + name
        elif rest.strip() == "(":
            name = kind + "@" + str(i + 1)
        else:
            name = re.match(r"^\s*([A-Za-z_0-9]+)", rest).group(1)
        decls.setdefault(name, []).append(text)
        i = end + 1
    return decls

def take(path, names):
    decls = declarations(os.path.join(ref, path))
    parts = ["// ---- " + path + " ----"]
    for name in names:
        if name not in decls:
            raise SystemExit("no declaration " + name + " in " + path + "; has " + ", ".join(sorted(decls)))
        parts.extend(decls[name])
    return "\n\n".join(parts)

def block_at(path, first_line_text):
    # The var or const block that holds the given line.
    decls = declarations(os.path.join(ref, path))
    for name, texts in decls.items():
        for t in texts:
            if first_line_text in t and ("@" in name):
                return "// ---- " + path + " ----\n" + t
    raise SystemExit("no block with " + first_line_text + " in " + path)

chunks = [
    take("internal/core/text.go", ["TextPos"]),
    take("internal/core/core.go", ["ECMALineStarts", "ComputeECMALineStarts", "ComputeECMALineStartsSeq", "UTF16Offset", "UTF16Len"]),
    take("internal/ast/utilities.go", ["PositionIsSynthesized"]),
    take("internal/scanner/scanner.go", [
        "SkipTriviaOptions", "SkipTrivia", "SkipTriviaEx", "isConflictMarkerTrivia", "scanConflictMarkerTrivia",
        "isShebangTrivia", "scanShebangTrivia", "ComputeLineOfPosition",
    ]),
    block_at("internal/scanner/scanner.go", "mergeConflictMarkerLength"),
    take("internal/vfs/internal/internal.go", ["decodeBytes", "decodeUtf16"]),
    take("internal/testrunner/test_case_parser.go", ["lineDelimiter", "optionRegex", "linkRegex"]),
]
text = "\n\n".join(chunks)

# One package holds what the reference keeps in several: the qualifiers of those go away.
for q in ["core", "scanner", "diagnostics", "ast"]:
    text = re.sub(r"\b" + q + r"\.([A-Z])", r"\1", text)

header = '''// Code generated by build.py from the reference; the declarations are verbatim but for package qualifiers.
package main

import (
	"encoding/binary"
	"iter"
	"regexp"
	"slices"
	"strings"
	"unicode/utf16"
	"unicode/utf8"

	"gt/stringutil"
)

'''
open(os.path.join(out, "extracted.go"), "w").write(header + text + "\n")
shutil.copy(os.path.join(here, "main.go"), os.path.join(out, "main.go"))
r = subprocess.run(["go", "build", "-o", "gt", "."], cwd=out, env={**os.environ, "GOFLAGS": "-mod=mod", "GOTOOLCHAIN": "local", "GOPROXY": "off"})
sys.exit(r.returncode)
