pub const PRAGMA_TEXTS: &[&[u8]] = &[
    b"/// <reference path=\"a.d.ts\" />\n/// <reference types=\"node\" />\n/// <reference lib=\"es2015\" />\nlet x;",
    b"/// <reference types=\"node\" resolution-mode=\"import\" preserve=\"true\"/>\nlet x;",
    b"/// <reference types=\"node\" resolution-mode=\"bogus\"/>\nlet x;",
    b"/// <reference no-default-lib=\"true\"/>\nlet x;",
    b"/// <reference no-default-lib=\"false\"/>\nlet x;",
    b"/// <reference foo=\"bar\"/>\nlet x;",
    b"/// <reference path='a.ts'>\nlet x;",
    b"/// <reference path=a.ts />\nlet x;",
    b"///<reference path=\"a.ts\"/>\nlet x;",
    b"///  <REFERENCE PATH=\"a.ts\"/>\nlet x;",
    b"// <reference path=\"a.ts\"/>\nlet x;",
    b"//// <reference path=\"a.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\" path=\"b.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\" types=\"t\" lib=\"l\"/>\nlet x;",
    b"/// <reference path = \"a.ts\"  />\nlet x;",
    b"/// <reference\tpath=\"a.ts\"/>\nlet x;",
    b"/// <referencepath=\"a.ts\"/>\nlet x;",
    b"/// <reference-x path=\"a.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\"\nlet x;",
    b"/// <reference path=\"unterminated />\nlet x;",
    b"/// <reference />\nlet x;",
    b"/// <amd-module name=\"m\"/>\n/// <amd-dependency path=\"p\" name=\"n\"/>\nlet x;",
    b"let x;\n/// <reference path=\"late.ts\"/>\n",
    b"#!/usr/bin/env node\n/// <reference path=\"a.ts\"/>\nlet x;",
    b"\n\n   /// <reference path=\"a.ts\"/>\n/* c */ /// <reference path=\"b.ts\"/>\nlet x;",
    b"/* block */\n/// <reference path=\"a.ts\"/>\n\"use strict\";\n/// <reference path=\"b.ts\"/>\n",
    b"// @ts-nocheck\nlet x;",
    b"// @ts-check\n// @ts-nocheck\nlet x;",
    b"// @ts-nocheck\n// @ts-check\nlet x;",
    b"//@ts-nocheck\nlet x;",
    b"//   @TS-NoCheck   trailing text\nlet x;",
    b"/// @ts-nocheck\nlet x;",
    b"/* @ts-nocheck */\nlet x;",
    b"// foo @ts-nocheck\nlet x;",
    b"// @ts-nocheckx\nlet x;",
    b"// @ts-nocheck-x\nlet x;",
    b"let x;\n// @ts-nocheck\n",
    b"// @ts-ignore\nlet x: number = 'a';\n/* @ts-expect-error */\nlet y;\n/*\n * a\n * @ts-ignore */\nlet z;",
    b"/** @jsx h */\n/* @jsxFrag Fragment */\n/* @jsxImportSource preact\n @jsxRuntime automatic */\nlet x;",
    b"// @jsx h\nlet x;",
    b"/* a@b.c @jsx h */\nlet x;",
    b"/* @JSX   h   extra */\nlet x;",
    b"/* @jsx */\nlet x;",
    b"/* @jsx\n h */\nlet x;",
    b"/* @jsx h\xe2\x80\xa8@jsxFrag F */\nlet x;",
    b"/// <reference path=\"a.ts\"/> trailing\nlet x;",
    b"/// <reference path=\"a.ts\" /> <reference path=\"b.ts\" />\nlet x;",
    b"///\t<reference path=\"\"/>\nlet x;",
    b"/// <reference types=\"a\" preserve=\"false\"/>\n/// <reference lib=\"b\" preserve=\"true\"/>\n/// <reference path=\"c\" preserve=\"true\"/>\nlet x;",
    b"\xef\xbb\xbf/// <reference path=\"a.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\"/>\r\n/// <reference path=\"b.ts\"/>\r\nlet x;",
    b"/* unterminated /// <reference path=\"a.ts\"/>",
    b"/// <reference types=\"node\" resolution-mode=\"require\"/>\n/// <reference path=\"x\" resolution-mode=\"bogus\"/>\nlet x;",
    b"// @ts-nocheck.\nlet x;",
    b"// @ts-nocheck: why\nlet x;",
    b"/// <reference path=\"a.ts\"\n",
    b"/* @jsx h\n * @jsxFrag F\n */ /* @jsxRuntime classic */\n// @ts-check\nlet x;",
    b"/***/ /**/ /** @jsximportsource p */ //\n//a\nlet x;",
    b"-->x\n/// <reference path=\"a.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\"/>\xe2\x80\xa8/// <reference path=\"b.ts\"/>\nlet x;",
    b"/// <reference path=\"a\\\"b.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\" / >\nlet x;",
    b"/// <reference PATH=\"a.ts\" Types=\"t\"/>\nlet x;",
    b"/* @jsxRunt\xc4\xb0me classic */\nlet x;",
    b"/* @JSX\xe2\x84\xaa h */\nlet x;",
    b"/// <reference path=\"a.ts\"/>\n-->\n/// <reference path=\"b.ts\"/>\nlet x;",
    b"/// <reference path=\"a.ts\"/>\n/**/\n/// <reference types=\"t\"/>\n\n// @ts-nocheck\nimport 'x';",
    b"\t\x0b\x0c \xc2\xa0/// <reference lib=\"dom\"/>\n",
    b"/// <reference lib=\"dom\"/>",
    b"",
    b"#!shebang only",
    b"#!sh\n// @ts-check",
    b"/// <reference path=\"a.ts\" resolution-mode=\"import\"/>\n/// <reference types=\"t\" resolution-mode=\"IMPORT\"/>\n/// <reference lib=\"l\" resolution-mode=\"x\"/>\n",
    b"/// <reference no-default-lib=\"true\" path=\"a.ts\"/>\n",
    b"/// <reference path=\"a.ts\" preserve=\"TRUE\"/>\n",
    b"/* @ts-check */ // @ts-nocheck\n// x @ts-check\n",
    b"//\n///\n// @\n/// <\n/// <reference\n",
    b"/// <reference path=\"./a.d.ts\" />\nlet x;",
    b"/// <reference types=\"node\" />\n",
    b"/// <reference lib=\"es2015\" />\n",
    b"/// <reference types=\"pkg\" resolution-mode=\"import\" />\n",
    b"/// <reference types='pkg' resolution-mode='require' preserve='true' />\n",
    b"/// <reference types=\"pkg\" resolution-mode=\"esm\" />\n",
    b"/// <reference no-default-lib=\"true\"/>\n/// <reference lib=\"dom\" />\n",
    b"/// <reference no-default-lib=\"false\"/>\n",
    b"/// <reference path=\"p\" lib=\"l\" types=\"t\" />\n/// <reference path=\"p\" lib=\"l\" />\n",
    b"/// <reference foo=\"bar\" />\n/// <reference />\n/// <reference path=a />\n",
    b"///<REFERENCE   PATH = \"a.ts\"   />\n///\t<reference path='b.ts'/>\n",
    b"/// <reference path=\"a.ts\"\n/// <reference path=\"b.ts\" >\n",
    b"/// <reference path=\"a.ts\" path=\"b.ts\" />\n",
    b"/// <amd-module name=\"m\" />\n/// <amd-dependency path=\"d\" name=\"n\" />\n/// <reference path=\"a.ts\" />\n",
    b"// <reference path=\"a.ts\" />\n//// <reference path=\"b.ts\" />\n",
    b"// @ts-nocheck\nlet x: number = 'a';",
    b"// @ts-check\n",
    b"/// @ts-nocheck\n",
    b"// @ts-nocheck\n// @ts-check\n",
    b"// @ts-check\n//\t @TS-NoCheck trailing words\n",
    b"// @ts-checked\n// @ts-nocheck-please\n// @ts-ignore\n// @ts-expect-error\n",
    b"let x;\n// @ts-nocheck\n/// <reference path=\"a.ts\" />\n",
    b"#!/usr/bin/env bun\n// @ts-nocheck\n/// <reference types=\"bun\" />\nlet x;",
    b"/* @ts-nocheck */\n/** @ts-check */\n",
    b"/** @jsx h */\n/* @jsxFrag Fragment */\n/* @jsxImportSource preact\n * @jsxRuntime automatic */\n",
    b"/* a@b.c @jsx h */\n/* @jsx */\n/* @JSX  H  extra */\n",
    b"// @jsx h\n",
    b"// @ts-check\n/* c */ let x; // @ts-nocheck\n",
    b"/* a */ // @ts-nocheck\n",
    b"\xef\xbb\xbf\n\n  // @ts-nocheck\n",
    b"// @ts-check\r\n/// <reference path=\"a.ts\" />\xe2\x80\xa8/// <reference path=\"b.ts\" />\r",
    b"/// <reference path=\"\xc3\xa9.ts\" />\n",
    b"",
    b"/// <reference path=\"a.ts\" />",
    b"/* @jsx h",
    b"// @ts-check2\n",
    b"// @ts-nocheck: generated\n",
    b"//\xc2\xa0@ts-check\n",
    b"//\t\t@ts-check\n",
    b"//// @ts-check\n",
    b"\xc2\x85// @ts-check\n",
    b"\xe2\x80\x8b// @ts-nocheck\n",
    b"\xe2\x80\xa8\xe2\x80\xa9/// <reference path=\"a.ts\" />\xe2\x80\xa9// @ts-check",
    b"/*/",
    b"/**/\n// @ts-check\n",
    b"/* @jsx h*/\n/**@jsxFrag F*/\n",
    b"/*\t@jsx\th\t*/\n",
    b"/*@jsx h\r\n@jsxFrag F*/\n",
    b"/* @jsx a @jsxFrag b */\n",
    b"/*\n@jsx a\n@jsx b\n*/\n",
    b"/* @ @jsx h */\n/* x@ @jsxFrag F */\n",
    b"/* @jsx h @*/\n/* @*/\n",
    b"/* @jsx\xc4\xb0mportSource p */\n",
    b"/* @jsxs h */\n/* @jsx.h x */\n",
    b"/// <reference path=\"a\" types=\"\" />\n/// <reference lib=\"\" path=\"p\" />\n",
    b"/// <reference no-default-lib=\"true\" types=\"t\" resolution-mode=\"bogus\"/>\n",
    b"/// <reference types=\"t\" resolution-mode=\"\"/>\n",
    b"/// <reference path=\"a.ts\" preserve=\"true\" resolution-mode=\"import\" />\n",
    b"/// <reference path=\"a.ts\" />\n/// <reference path=\"b.ts\" />",
    b"/// <reference path='a\"b.ts' types=\"c'd\" />\n",
    b"/// <reference path types=\"t\" />\n",
    b"/// <reference path=\"a.ts\" 1=\"x\" types=\"t\" />\n",
    b"/// <Reference Path=\"a.ts\" NO-DEFAULT-LIB=\"TRUE\" />\n",
    b"///\t \t<reference lib=\"l\"/>\n",
    b"/// <reference path=\"a.ts\" />\nlet x; /// <reference path=\"b.ts\" />\n",
    b"-->\n// @ts-nocheck\n",
    b"// @ts-ignore\n/* @ts-expect-error */\nlet x;",
    b"/* a */ /* b */\n/** c */ // @ts-nocheck\n/* d */ let x;",
    b"#!/usr/bin/env bun\r\n/// <reference types=\"bun\" />\r\n",
    b" #!x\n// @ts-check\n",
    b"\xef\xbb\xbf#!x\n// @ts-check\n",
];

pub const DIRECTIVE_VECTORS: &[(&str, &[u8], &[(u32, u32)], &str)] = &[
    ("line-ignore", b"// @ts-ignore\nlet x: number = 'a';", &[(0, 13)], "Ignore 0..13"),
    ("line-expect-error", b"// @ts-expect-error\nlet x: number = 'a';", &[(0, 19)], "ExpectError 0..19"),
    ("line-no-space-eof", b"//@ts-ignore", &[(0, 12)], "Ignore 0..12"),
    ("line-three-slashes", b"/// @ts-ignore\nlet x;", &[(0, 14)], "Ignore 0..14"),
    ("line-four-slashes", b"//// @ts-ignore\nlet x;", &[(0, 15)], "Ignore 0..15"),
    ("line-tab-space-reason", b"//\t @ts-expect-error: reason\nlet x;", &[(0, 28)], "ExpectError 0..28"),
    ("line-prefix-ignored", b"// @ts-ignored\nlet x;", &[(0, 14)], "Ignore 0..14"),
    ("line-prefix-expect-errors", b"// @ts-expect-errors\nlet x;", &[(0, 20)], "ExpectError 0..20"),
    ("line-upper-case", b"// @TS-IGNORE\nlet x;", &[(0, 13)], ""),
    ("line-not-first", b"// x @ts-ignore\nlet x;", &[(0, 15)], ""),
    ("line-space-after-at", b"// @ ts-ignore\nlet x;", &[(0, 14)], ""),
    ("line-nbsp", b"//\xc2\xa0@ts-ignore\nlet x;", &[(0, 14)], ""),
    ("line-nocheck-is-no-directive", b"// @ts-nocheck\nlet x;", &[(0, 14)], ""),
    ("line-trailing", b"let x; // @ts-ignore\nlet y;", &[(7, 20)], "Ignore 7..20"),
    ("line-crlf", b"// @ts-ignore\r\nlet x;", &[(0, 13)], "Ignore 0..13"),
    ("line-ls", b"// @ts-ignore\xe2\x80\xa8let x;", &[(0, 13)], "Ignore 0..13"),
    ("line-at-eof-after-code", b"let x;\n// @ts-expect-error", &[(7, 26)], "ExpectError 7..26"),
    ("line-empty", b"//\nlet x;", &[(0, 2)], ""),
    ("line-only-at", b"// @\nlet x;", &[(0, 4)], ""),
    ("block-one-line", b"/* @ts-ignore */\nlet x;", &[(0, 16)], "Ignore 0..16"),
    ("block-jsdoc-one-line", b"/** @ts-expect-error */\nlet x;", &[(0, 23)], "ExpectError 0..23"),
    ("block-no-space", b"/*@ts-ignore*/\nlet x;", &[(0, 14)], "Ignore 0..14"),
    ("block-last-line", b"/*\n * a\n * @ts-ignore */\nlet x;", &[(0, 24)], "Ignore 8..24"),
    ("block-first-line-only", b"/* @ts-ignore\n */\nlet x;", &[(0, 17)], ""),
    ("block-middle-line-only", b"/*\n * @ts-ignore\n * b\n */\nlet x;", &[(0, 25)], ""),
    ("block-last-line-bare", b"/*\n@ts-expect-error*/\nlet x;", &[(0, 21)], "ExpectError 3..21"),
    ("block-last-line-tabs-stars", b"/*\n\t ** @ts-expect-error */\nlet x;", &[(0, 27)], "ExpectError 3..27"),
    ("block-last-line-star-space-slash", b"/*\n\t * / ** @ts-ignore */\nlet x;", &[(0, 25)], ""),
    ("block-slash-star-slash", b"/*/ @ts-ignore */\nlet x;", &[(0, 17)], "Ignore 0..17"),
    ("block-two-on-a-line", b"/* @ts-ignore */ /* @ts-expect-error */\nlet x;", &[(0, 16), (17, 39)], "Ignore 0..16, ExpectError 17..39"),
    ("block-crlf", b"/*\r\n * @ts-ignore */\r\nlet x;", &[(0, 20)], "Ignore 4..20"),
    ("block-cr-only", b"/*\r * @ts-ignore */\rlet x;", &[(0, 19)], "Ignore 3..19"),
    ("block-ls", b"/* a\xe2\x80\xa8 @ts-expect-error */\nlet x;", &[(0, 27)], "ExpectError 7..27"),
    ("block-ps", b"/* a\xe2\x80\xa9@ts-ignore */\nlet x;", &[(0, 20)], "Ignore 7..20"),
    ("block-non-ascii-before", b"/* \xc3\xa9\n * \xc3\xa9 */ /*\xc3\xa9\n@ts-ignore */\nlet x;", &[(0, 14), (15, 33)], "Ignore 20..33"),
    ("block-empty", b"/**/ /***/\nlet x;", &[(0, 4), (5, 10)], ""),
    ("block-space-before-at-on-last-line", b"/*\n  @ts-ignore */", &[(0, 18)], "Ignore 3..18"),
    ("block-nbsp-on-last-line", b"/*\n\xc2\xa0@ts-ignore */", &[(0, 18)], ""),
    ("block-star-nbsp", b"/* *\xc2\xa0@ts-ignore */", &[(0, 19)], ""),
    ("hashbang-then-line", b"#!/usr/bin/env bun\n// @ts-expect-error\nlet x: number = 'a';", &[(19, 38)], "ExpectError 19..38"),
    ("mixed-order", b"// @ts-ignore\nlet a;\n/* @ts-expect-error */\nlet b;\n/*\n * a\n * @ts-ignore */\nlet c; // @ts-expect-error", &[(0, 13), (21, 43), (51, 75), (83, 102)], "Ignore 0..13, ExpectError 21..43, Ignore 59..75, ExpectError 83..102"),
    ("line-ignore-then-text-at", b"// @ts-ignore @ts-expect-error\nlet x;", &[(0, 30)], "Ignore 0..30"),
    ("block-trailing-text", b"/* @ts-expect-error because */\nlet x;", &[(0, 30)], "ExpectError 0..30"),
    ("line-slash-star-inside", b"// /* @ts-ignore */\nlet x;", &[(0, 19)], ""),
    ("block-line-inside", b"/* // @ts-ignore */\nlet x;", &[(0, 19)], ""),
];

pub const CONTEXT_VECTORS: &[(&str, &str, &[u8], &[(u32, u32)], &str)] = &[
    ("string-not-comment", "ts", b"let s = \"// @ts-ignore\"; let t = '/* @ts-expect-error */';", &[], ""),
    ("template-text-and-hole", "ts", b"let t = `// @ts-ignore ${ /* @ts-ignore */ 1 } // @ts-expect-error`;", &[(26, 42)], "Ignore 26..42"),
    ("regex-not-comment", "ts", b"let r = /\\/\\/ @ts-ignore/; let q = /[/*]/; // @ts-expect-error", &[(43, 62)], "ExpectError 43..62"),
    ("division-then-comment", "ts", b"let d = 4 / 2 /* @ts-ignore */ / 1;", &[(14, 30)], "Ignore 14..30"),
    ("type-args-attempt-fails", "ts", b"let r = a < /* @ts-ignore */ b > c;", &[(12, 28)], "Ignore 12..28"),
    ("type-args-attempt-kept", "ts", b"let r = f< /* @ts-ignore */ T>( /* @ts-expect-error */ x);", &[(11, 27), (32, 54)], "Ignore 11..27, ExpectError 32..54"),
    ("arrow-return-cond-reparse", "ts", b"let r = c ? (a) : /* @ts-expect-error */ b => d : e;", &[(18, 40)], "ExpectError 18..40"),
    ("arrow-return-cond-plain", "ts", b"let r = c ? (a) /* @ts-ignore */ : b;", &[(16, 32)], "Ignore 16..32"),
    ("arrow-args-type-attempt", "ts", b"let x: ( /* @ts-ignore */ a: string) => void; let y: ( /* @ts-expect-error */ string);", &[(9, 25), (55, 77)], "Ignore 9..25, ExpectError 55..77"),
    ("generic-arrow-tsx", "tsx", b"const f = <T, /* @ts-ignore */ >(x: T) => x;", &[(14, 30)], "Ignore 14..30"),
    ("async-arrow-lookahead", "ts", b"let f = async /* @ts-ignore */ x => x;", &[(14, 30)], "Ignore 14..30"),
    ("split-greater", "ts", b"let x: A<B<C /* @ts-ignore */ >> /* @ts-expect-error */ = y;", &[(13, 29), (33, 55)], "Ignore 13..29, ExpectError 33..55"),
    ("jsx-tag-line", "tsx", b"let e = <div // @ts-ignore\n  a=\"b\" // @ts-expect-error\n/>;", &[(13, 26), (35, 54)], "Ignore 13..26, ExpectError 35..54"),
    ("jsx-tag-block", "tsx", b"let e = < /* @ts-ignore */ div /* @ts-expect-error */ a /* @ts-ignore */ = /* @ts-ignore */ \"b\" />;", &[(10, 26), (31, 53), (56, 72), (75, 91)], "Ignore 10..26, ExpectError 31..53, Ignore 56..72, Ignore 75..91"),
    ("jsx-text-not-comment", "tsx", b"let e = <div>// @ts-ignore\n/* @ts-expect-error */</div>;", &[], ""),
    ("jsx-expression-container", "tsx", b"let e = <div>{/* @ts-expect-error */}{ x // @ts-ignore\n}</div>;", &[(14, 36), (41, 54)], "ExpectError 14..36, Ignore 41..54"),
    ("jsx-closing-tag", "tsx", b"let e = <div></ /* @ts-ignore */ div /* @ts-expect-error */ >;", &[(16, 32), (37, 59)], "Ignore 16..32, ExpectError 37..59"),
    ("jsx-fragment", "tsx", b"let e = < /* @ts-ignore */ > </ /* @ts-expect-error */ >;", &[(10, 26), (32, 54)], "Ignore 10..26, ExpectError 32..54"),
    ("jsx-after-element", "tsx", b"let e = <a /> /* @ts-ignore */ ; let f = <b></b> // @ts-expect-error\n;", &[(14, 30), (49, 68)], "Ignore 14..30, ExpectError 49..68"),
    ("jsx-attr-string-not-comment", "tsx", b"let e = <a b=\"// @ts-ignore\" c='/* @ts-expect-error */' />;", &[], ""),
    ("jsx-spread-attr", "tsx", b"let e = <a {...b /* @ts-ignore */ } />;", &[(17, 33)], "Ignore 17..33"),
    ("jsdoc-type-inner-line", "ts", b"/** @type {string // @ts-ignore\n} */ let x;", &[(0, 36)], ""),
    ("jsdoc-js-file", "js", b"/** @type {string} // @ts-ignore\n */ let x = 1; // @ts-expect-error\n", &[(0, 36), (48, 67)], "ExpectError 48..67"),
    ("before-eof-block", "ts", b"let x;\n/* @ts-ignore */", &[(7, 23)], "Ignore 7..23"),
    ("only-directive", "ts", b"// @ts-ignore", &[(0, 13)], "Ignore 0..13"),
    ("class-members", "ts", b"class A { /* @ts-ignore */ public x: number; // @ts-expect-error\n declare y: string; }", &[(10, 26), (45, 64)], "Ignore 10..26, ExpectError 45..64"),
    ("interface-erased", "ts", b"interface I { // @ts-ignore\n a: string; /* @ts-expect-error */ }\ntype T = /* @ts-ignore */ 1;", &[(14, 27), (40, 62), (74, 90)], "Ignore 14..27, ExpectError 40..62, Ignore 74..90"),
    ("top-level-await-module", "ts", b"export {};\n// @ts-ignore\nawait 1; /* @ts-expect-error */\nawait 2;", &[(11, 24), (34, 56)], "Ignore 11..24, ExpectError 34..56"),
    ("hashbang-then-directive-then-pragma", "ts", b"#!/usr/bin/env bun\n// @ts-ignore\n// @ts-nocheck\nlet x;", &[(19, 32), (33, 47)], "Ignore 19..32"),
];
