name: Claude Code

on:
  issues:
    types: [opened, reopened, edited, assigned]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: prompt
        name: Read Prompt
        run: |
          echo "prompt=$(cat .agent/TRIAGE.md)" >> $GITHUB_OUTPUT

      - name: Run Agent
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: ${{ steps.prompt.outputs.prompt }}
          allowed_tools: "Bash,Edit,Replace,Search"
          timeout_minutes: 5
