name: build-image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - ci-automated-build-image
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "aarch64"
            distro: "debian"
            release: "12"
          - arch: "aarch64"
            distro: "debian"
            release: "11"
          - arch: "aarch64"
            distro: "debian"
            release: "10"
          - arch: "aarch64"
            distro: "ubuntu"
            release: "2404"
          - arch: "aarch64"
            distro: "ubuntu"
            release: "2204"
          - arch: "aarch64"
            distro: "ubuntu"
            release: "2004"
          - arch: "aarch64"
            distro: "ubuntu"
            release: "1804"
          - arch: "aarch64"
            distro: "amazonlinux"
            release: "2023"
          - arch: "aarch64"
            distro: "amazonlinux"
            release: "2"
          - arch: "x64"
            distro: "debian"
            release: "12"
          - arch: "x64"
            distro: "debian"
            release: "11"
          - arch: "x64"
            distro: "debian"
            release: "10"
          - arch: "x64"
            distro: "ubuntu"
            release: "2404"
          - arch: "x64"
            distro: "ubuntu"
            release: "2204"
          - arch: "x64"
            distro: "ubuntu"
            release: "2004"
          - arch: "x64"
            distro: "ubuntu"
            release: "1804"
          - arch: "x64"
            distro: "amazonlinux"
            release: "2023"
          - arch: "x64"
            distro: "amazonlinux"
            release: "2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: latest
      - name: Setup Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        working-directory: ci
        run: bun build:linux-${{ matrix.arch }}-${{ matrix.distro }}-${{ matrix.release }}
      - name: Test
        working-directory: ci
        run: bun test:linux-${{ matrix.arch }}-${{ matrix.distro }}-${{ matrix.release }}
