name: Build Bun

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      no-cache:
        type: boolean
      canary:
        type: boolean
      assertions:
        type: boolean
      zig-optimize:
        type: string
  workflow_dispatch:
    inputs:
      no-cache:
        type: boolean
      canary:
        type: boolean
      assertions:
        type: boolean
      zig-optimize:
        type: string

jobs:
  linux-x64:
    name: Build linux-x64
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-linux-x64' || 'ubuntu-latest' }}
      tag: linux-x64
      arch: x64
      cpu: haswell
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  linux-x64-baseline:
    name: Build linux-x64-baseline
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-linux-x64' || 'ubuntu-latest' }}
      tag: linux-x64-baseline
      arch: x64
      cpu: nehalem
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  linux-aarch64:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Build linux-aarch64
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      runs-on: namespace-profile-bun-ci-linux-aarch64
      tag: linux-aarch64
      arch: aarch64
      cpu: native
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  darwin-x64:
    name: Build darwin-x64
    uses: ./.github/workflows/build-darwin.yml
    secrets: inherit
    with:
      runs-on: ${{ github.repository_owner == 'oven-sh' && 'macos-12-large' || 'macos-12' }}
      tag: darwin-x64
      arch: x64
      cpu: haswell
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  darwin-aarch64:
    name: Build darwin-aarch64
    uses: ./.github/workflows/build-darwin.yml
    secrets: inherit
    with:
      runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-darwin-aarch64' || 'macos-12' }}
      tag: darwin-aarch64
      arch: aarch64
      cpu: native
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  windows-x64:
    name: Build windows-x64
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      runs-on: windows
      tag: windows-x64
      arch: x64
      cpu: haswell
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}

  windows-x64-baseline:
    name: Build windows-x64-baseline
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      runs-on: windows
      tag: windows-x64-baseline
      arch: x64
      cpu: nehalem
      no-cache: ${{ inputs.no-cache }}
      canary: ${{ inputs.canary }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}
