name: Build Linux

permissions:
  contents: read
  actions: write

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
      tag:
        type: string
        required: true
      arch:
        type: string
        required: true
      cpu:
        type: string
        required: true
      assertions:
        type: boolean
      zig-optimize:
        type: string
      canary:
        type: boolean
      no-cache:
        type: boolean

jobs:
  build:
    name: Build Linux
    uses: ./.github/workflows/build-zig.yml
    with:
      os: linux
      only-zig: false
      runs-on: ${{ inputs.runs-on }}
      tag: ${{ inputs.tag }}
      arch: ${{ inputs.arch }}
      cpu: ${{ inputs.cpu }}
      assertions: ${{ inputs.assertions }}
      zig-optimize: ${{ inputs.zig-optimize }}
      canary: ${{ inputs.canary }}
      no-cache: ${{ inputs.no-cache }}
  on-failure:
    if: ${{ github.repository_owner == 'oven-sh' && failure() }}
    name: On Failure
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: "#FF0000"
          title: ""
          description: |
            ### ❌ [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})

            @${{ github.actor }}, the build for bun-${{ inputs.tag }} failed.

            **[View logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**
