# This workflow tests bun-release's code and the packages to ensure that npm,
# yarn, and pnpm can install bun on all platforms. This does not test that bun
# itself works as it hardcodes 1.1.0 as the version to package.
name: bun-release-test
concurrency: release-test

on:
  pull_request:
    paths:
      - "packages/bun-release/**"
      - ".github/workflows/bun-release-test.yml"

jobs:
  test-release-script:
    name: Test Release Script
    strategy:
      matrix:
        machine: [namespace-profile-bun-linux-x64, linux-arm64, macos-arm64, macos-12-large, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.machine }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packages/bun-release
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: "1.1.0"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: bun install && npm i -g pnpm yarn npm

      - name: Release
        run: bun upload-npm -- 1.1.0 test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
