name: Ecosystem Test

on:
  schedule:
    - cron: "0 15 * * *" # every day at 7am PST
  workflow_dispatch:
    inputs:
      version:
        description: "The version of Bun to run"
        required: true
        default: "canary"
        type: string
jobs:
  test:
    name: ${{ matrix.tag }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            tag: linux-x64
            url: linux/x64?avx2=true
          - os: ubuntu-latest
            tag: linux-x64-baseline
            url: linux/x64?baseline=true
          # FIXME: runner fails with "No tests found"?
          #- os: macos-latest
          #  tag: darwin-x64
          #  url: darwin/x64?avx2=true
          - os: macos-latest
            tag: darwin-x64-baseline
            url: darwin/x64?baseline=true
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - id: setup
        name: Setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-download-url: https://bun.sh/download/${{ github.event.inputs.version }}/${{ matrix.url }}
      - id: test
        name: Test
        run: bun run test:ecosystem
