name: Release bun-types
on:
  workflow_dispatch:

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'oven-sh'
    defaults:
      run:
        working-directory: packages/bun-types
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: canary
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: bun upgrade --canary; bun install

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/bun-types/dist/package.json
          token: ${{ secrets.NPM_BUN_TYPES_TOKEN }}
          tag: latest
