name: clang-tidy

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/clang-tidy.yml"
      - ".clang-tidy"
      - "package.json"
      - "scripts/**"
      - "cmake/**"
      - "src/**/*.c"
      - "src/**/*.cpp"
      - "src/**/*.h"
      - "packages/**/*.c"
      - "packages/**/*.cpp"
      - "packages/**/*.h"

env:
  BUN_VERSION: "1.1.27"
  LLVM_VERSION: "18.1.8"
  LLVM_VERSION_MAJOR: "18"

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            .clang-tidy
            package.json
            scripts
            cmake
            src
            packages
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install LLVM
        run: |
          curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash -s -- ${{ env.LLVM_VERSION_MAJOR }} all
      - name: Clang Tidy
        env:
          ENABLE_CCACHE: OFF
          LLVM_VERSION: ${{ env.LLVM_VERSION }}
        run: |
          bun run clang-tidy:diff
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "`bun run clang-tidy`"
