name: clang-tidy

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  merge_group:

env:
  BUN_VERSION: "1.2.0"
  LLVM_VERSION: "18.1.8"
  LLVM_VERSION_MAJOR: "18"

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Install LLVM
        run: |
          curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash -s -- ${{ env.LLVM_VERSION_MAJOR }} all
      - name: Clang Tidy
        env:
          LLVM_VERSION: ${{ env.LLVM_VERSION }}
        run: |
          bun run clang-tidy:diff
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "`bun run clang-tidy`"
