name: Comment on PR

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  comment:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Download Tests
        uses: actions/download-artifact@v4
        with:
          path: bun
          pattern: bun-*-tests
          merge-multiple: true
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Setup Environment
        id: env
        shell: bash
        run: |
          echo "pr-number=$(<bun-linux-x64-tests/pr-number.txt)" >> $GITHUB_OUTPUT
      - name: Generate Comment
        run: |
          cat bun-*-tests/comment.md > comment.md
          if [ -s comment.md ]; then
            echo -e "❌ @${{ github.actor }}, there are failing tests: \n$(cat comment.md)" > comment.md
          else
            echo -e "✅ @${{ github.actor }}, all tests passed!" > comment.md
          fi
          echo -e "\n**[View logs](https://github.com/oven-sh/bun/actions/runs/${{ github.event.workflow_run.id }})**" >> comment.md
          echo -e "<!-- generated-comment run-id=${{ github.event.workflow_run.id }} -->" >> comment.md
      - name: Find Comment
        id: comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ steps.env.outputs.pr-number }}
          comment-author: github-actions[bot]
          body-includes: <!-- generated-comment run-id=${{ github.event.workflow_run.id }} -->
      - name: Write Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ steps.env.outputs.pr-number }}
          body-path: comment.md
          edit-mode: replace
