name: Glob Sources

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  BUN_VERSION: "1.2.11"

jobs:
  glob-sources:
    name: Glob Sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global core.autocrlf true
          git config --global core.ignorecase true
          git config --global core.precomposeUnicode true
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup Dependencies
        run: |
          bun install
      - name: Glob sources
        run: bun scripts/glob-sources.mjs
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "`bun scripts/glob-sources.mjs`"

