name: Lint

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

env:
  BUN_VERSION: "1.3.14"

jobs:
  lint-js:
    name: "Lint JavaScript"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup Dependencies
        run: |
          bun install --frozen-lockfile
      - name: Lint
        run: bun lint
