name: Run Tests Manually

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "canary"
        type: string
      use_bun:
        description: "Use Bun?"
        required: true
        default: true
        type: boolean
jobs:
  linux-test:
    name: Tests ${{matrix.tag}} ${{github.event.inputs.version}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: linux-x64
          - tag: linux-x64-baseline
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - id: install-npm
        name: Install (npm)
        run: |
          npm install @oven/bun-${{matrix.tag}}@${{github.event.inputs.version}}
          chmod +x node_modules/@oven/bun-${{matrix.tag}}/bin/bun
          sudo cp node_modules/@oven/bun-${{matrix.tag}}/bin/bun /usr/bin/bun
      - id: test
        name: Test
        if: ${{github.event.inputs.use_bun == 'true'}}
        run: |
          bun install
          bun install --cwd test/bun.js
          bun install --cwd test/bun.js/third-party/body-parser-test
          cd packages/bun-internal-test
          bun install
          bun run test
      - id: test-node-runner
        name: Test (node runner)
        if: ${{github.event.inputs.use_bun == 'false'}}
        run: |
          bun install
          bun install --cwd test/bun.js
          bun install --cwd test/bun.js/third-party/body-parser-test
          cd packages/bun-internal-test
          bun install
          node src/runner.node.mjs
