name: Test

concurrency:
  group: ${{ github.workflow }}-${{ inputs.run-id || github.run_id }}
  cancel-in-progress: true

on:
  push:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
      run-id:
        type: string
        required: true
      baseline:
        type: boolean
        required: false
jobs:
  test:
    runs-on: ${{ inputs.run-on || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json
            bun.lockb
            test
            packages/bun-internal-test
      - name: Download Bun
        uses: actions/download-artifact@v4
        with:
          pattern: bun-${{ runner.os == 'macOS' && 'darwin' || runner.os == 'Windows' && 'windows' || 'linux' }}-${{ runner.arch == 'X64' && 'x64' || 'aarch64' }}${{ inputs.baseline && '-baseline' || '' }}
          path: ${{ runner.temp }}
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run-id || '8619678366' }}
      - name: Setup Bun
        shell: bash
        run: |
          unzip -d /usr/local/bin ${{ runner.temp }}/bun-*/bun-*.zip
          mv /usr/local/bin/bun-*/bun /usr/local/bin/bun
          which bun
          bun --version
          bun --print 'Bun.revision'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        shell: bash
        run: |
          bun install
          bun install --cwd test
          bun install --cwd packages/bun-internal-test
      - name: Run Tests
        id: test
        shell: bash
        env:
          TMPDIR: ${{ runner.temp }}
          BUN_FEATURE_FLAG_INTERNAL_FOR_TESTING: "true"
          SMTP_SENDGRID_SENDER: ${{ secrets.SMTP_SENDGRID_SENDER }}
          TLS_MONGODB_DATABASE_URL: ${{ secrets.TLS_MONGODB_DATABASE_URL }}
          TLS_POSTGRES_DATABASE_URL: ${{ secrets.TLS_POSTGRES_DATABASE_URL }}
        run: |
          node packages/bun-internal-test/src/runner.node.mjs || true
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: test-report.*
          if-no-files-found: error
          overwrite: true
