name: Test Nix Flake

on:
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/test-nix-flake.yml'
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'

jobs:
  test-nix-shell:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Check flake
        run: nix flake check --all-systems

      - name: Enter dev shell and verify tools
        run: |
          nix develop --command bash -c '
            set -e
            echo "Checking tools..."
            echo "Node.js: $(node --version)"
            echo "Bun: $(bun --version)"
            echo "Clang: $(clang --version | head -n1)"
            echo "CMake: $(cmake --version | head -n1)"
            echo "Ninja: $(ninja --version)"
            echo "Rust: $(rustc --version)"
            echo "Go: $(go version)"
            echo ""
            echo "Checking environment variables..."
            echo "CC=$CC"
            echo "CXX=$CXX"
            echo "AR=$AR"
            echo "RANLIB=$RANLIB"
            echo "LD=$LD"
            echo ""
            echo "All tools verified successfully!"
          '

      - name: Test building Bun (quick smoke test)
        run: |
          nix develop --command bash -c '
            set -e
            # This is just a smoke test to ensure the environment works
            # We'\''re not doing a full build in CI as that would take too long
            echo "Testing if cmake can configure..."
            mkdir -p build-test
            cd build-test
            cmake --version
            echo "Nix environment is working!"
          '
