name: Test Bun

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ inputs.workflow-run-id || inputs.buildkite-url || inputs.bun-version || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      workflow-run-id:
        type: string
      buildkite-url:
        type: string
      bun-version:
        type: string
  workflow_call:
    inputs:
      workflow-run-id:
        type: string
      buildkite-url:
        type: string
      bun-version:
        type: string

jobs:
  linux-x64-test:
    name: Test linux-x64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      tag: linux-x64
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  linux-x64-baseline-test:
    name: Test linux-x64-baseline
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      tag: linux-x64-baseline
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  linux-aarch64-test:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Test linux-aarch64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: namespace-profile-bun-ci-linux-aarch64
      tag: linux-aarch64
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  darwin-x64-test:
    name: Test darwin-x64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: macos-12
      tag: darwin-x64
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  darwin-aarch64-test:
    name: Test darwin-aarch64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: macos-12
      tag: darwin-aarch64
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  windows-x64-test:
    name: Test windows-x64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: windows-latest
      tag: windows-x64
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
  windows-x64-baseline-test:
    name: Test windows-x64-baseline
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      runs-on: windows-latest
      tag: windows-x64-baseline
      workflow-run-id: ${{ inputs.workflow-run-id }}
      buildkite-url: ${{ inputs.buildkite-url }}
      bun-version: ${{ inputs.bun-version }}
