name: Test

concurrency:
  group: ${{ github.workflow }}-${{ inputs.run-id || github.run_id }}
  cancel-in-progress: true

on:
  push:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
      run-id:
        type: string
        required: true
      baseline:
        type: boolean
        required: false
jobs:
  test:
    runs-on: ${{ inputs.run-on || 'ubuntu-latest' }}
    steps:
      - name: Download Bun
        uses: actions/download-artifact@v4
        with:
          pattern: bun-${{ runner.os == 'macOS' && 'darwin' || runner.os == 'Windows' && 'windows' || 'linux' }}-${{ runner.arch == 'X64' && 'x64' || 'aarch64' }}${{ inputs.baseline && '-baseline' || '' }}
          path: ${{ runner.temp }}
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run-id || '8619678366' }}
      - name: Setup Bun
        shell: bash
        run: |
          unzip -d /usr/local/bin ${{ runner.temp }}/bun-*/bun-*.zip
          mv /usr/local/bin/bun-*/bun /usr/local/bin/bun
          which bun
          bun --version
          bun --print 'Bun.revision'
      # - if: ${{ false }}
      #   name: Setup SSH
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true