name: Test

concurrency:
  group: ${{ github.workflow }}-${{ inputs.run-id || github.run_id }}
  cancel-in-progress: true

on:
  push:
  workflow_call:
    inputs:
      run-id:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: download
        name: Download bun
        uses: actions/download-artifact@v4
        with:
          pattern: bun-{darwin,linux,windows}-{x64,aarch64}{,-baseline}
          path: ${{ runner.temp }}
          github-token: ${{ github.token }}
          run-id: ${{ inputs.run-id || '8623134412' }}
      - name: Unzip bun
        run: |
          echo "${{ steps.download.outputs.download-path }}"
      
