name: Daily Root Certs Update Check

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual trigger

jobs:
  check-and-update:
    if: github.repository == 'oven-sh/bun'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest

      - name: Generate root certs and metadata
        id: generate-certs
        run: |
          cd packages/bun-usockets/
          CERT_METADATA=$(mktemp)
          bun generate-root-certs.mjs -v -f "$CERT_METADATA"
          cat "$CERT_METADATA" >> "$GITHUB_ENV"

      - name: Check for changes and stage files
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Found changes, staging modified files..."
            git add -A
            
            echo "changes=true" >> "$GITHUB_OUTPUT"
            
            # Store the list of changed files
            CHANGED_FILES=$(git status --porcelain)
            CHANGED_FILES_DELIMITER=$(uuidgen)
            {
              echo "changed_files<<$CHANGED_FILES_DELIMITER"
              echo "$CHANGED_FILES"
              echo "$CHANGED_FILES_DELIMITER"
            } >> "$GITHUB_ENV"
          else
            echo "No changes detected"
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.COMMIT_MSG }}
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "crypto: update root certificates to NSS ${{ env.NEW_VERSION }}"
          body: |
            ${{ env.COMMIT_MSG }}

            ## Changed files

            ```text
            ${{ env.changed_files }}
            ```
          branch: certs/update-root-certs
          base: main
          delete-branch: true
          labels: |
            automation
            root-certs
