name: zizmor

permissions:
  contents: read
  security-events: write

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches: [main]
    paths:
      - ".github/**"

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Run zizmor
        run: |
          pipx install zizmor
          zizmor --format sarif .github/ > zizmor.sarif || true
      - uses: github/codeql-action/upload-sarif@7fd177fa680c9881b53cdab4d346d32574c9f7f4 # v3
        with:
          sarif_file: zizmor.sarif
          category: zizmor
