// Prints what the installed bun writes for an equivalent of each source that it already parses: [source, equivalent, rename?]
const ts = new Bun.Transpiler({ loader: "ts" });
const rows = [
  ["type as = 1; let x: as;", "type QQ = 1; let x: QQ;"],
  ["type as<T> = T;", "type QQ<T> = T;"],
  ["type /* c */ as = 1", "type /* c */ QQ = 1"],
  ["type as\n= 1", "type QQ\n= 1"],
  ["let type: any; type as = 1;", "let type: any; type QQ = 1;"],
  ["function f() { type as = 1; return 1 as as }", "function f() { type QQ = 1; return 1 as QQ }"],
  ["{ type satisfies = 1 }", "{ type QQ = 1 }"],
  ["interface as {}\nfoo()", "interface QQ {}\nfoo()"],
  ["interface as { a: 1 }\nconst x = 1;", "interface QQ { a: 1 }\nconst x = 1;"],
  ["interface as<T> extends B<T> { a: T }", "interface QQ<T> extends B<T> { a: T }"],
  ["interface satisfies extends B {}", "interface QQ extends B {}"],
  ["interface as {}; foo()", "interface QQ {}; foo()"],
  ["export default interface as {}", "export default interface QQ {}"],
  ["function f() { interface as {} }", "function f() { interface QQ {} }"],
  ["export declare interface as {}", "export declare interface QQ {}"],
  ["export declare type satisfies = 1", "export declare type QQ = 1"],
  ["declare interface as { a: 1 }", "declare interface QQ { a: 1 }"],
  ["namespace as {}\nfoo()", "namespace QQ {}\nfoo()"],
  ["namespace as {};", "namespace QQ {};"],
  ["namespace as.b.c { export const a = 1 }", "namespace QQ.b.c { export const a = 1 }"],
  ["module as.b {}", "module QQ.b {}"],
  ["export namespace as { export const a = 1 }", "export namespace QQ { export const a = 1 }"],
  ["declare namespace as { const x: number; function f(): void }", "declare namespace QQ { const x: number; function f(): void }"],
  ["declare module as.b {}", "declare module QQ.b {}"],
  ["export declare namespace satisfies {}", "export declare namespace QQ {}"],
  ["namespace N { namespace as { export const x = 1 } export const y = as.x }", "namespace N { namespace QQ { export const x = 1 } export const y = QQ.x }"],
  ["namespace N { export interface as {} }", "namespace N { export interface QQ {} }"],
  ["declare global { interface as {} }", "declare global { interface QQ {} }"],
  ["namespace as {}`x`", "namespace QQ {}`x`"],
  ["interface as {}\n[x] = y", "interface QQ {}\n[x] = y"],
  // what a parse without lint keeps, after a declaration that the installed bun rejects
  ["type as = 1\ntype as any", "type QQ = 1\ntype as any"],
  ["interface as {}\ninterface as any\nfoo()", "interface QQ {}\ninterface as any\nfoo()"],
  ["namespace as {}\nnamespace as any", "namespace QQ {}\nnamespace as any"],
  ["namespace as {}\nnamespace as { foo(): void }", "namespace QQ {}\nnamespace as { foo(): void }"],
  ["interface as {}\ninterface as {} | X\nfoo()", "interface QQ {}\ninterface as {} | X\nfoo()"],
  ["type as = 1\ntype as <T>(x: T) => void", "type QQ = 1\ntype as <T>(x: T) => void"],
  ["interface as {}\ninterface as {} Foo {}", "interface QQ {}\ninterface as {} Foo {}"],
  ["namespace as {}\nnamespace as {} + 1", "namespace QQ {}\nnamespace as {} + 1"],
  // module syntax
  ['import "x"\nwith { type: "json" };', 'import "x" with { type: "json" };'],
  ['export { a } from "x"\nwith { type: "json" };', 'export { a } from "x" with { type: "json" };'],
  ['export * from "x"\nwith { type: "json" };', 'export * from "x" with { type: "json" };'],
  ['import type A from "x"\nwith { type: "json" };', 'import type A from "x" with { type: "json" };'],
  ['namespace N { import("x").then(f); }', 'namespace N { (import("x")).then(f); }'],
  ['namespace N.M { import("x"); }', 'namespace N.M { (import("x")); }'],
  ['export namespace N { import("x"); }', 'export namespace N { (import("x")); }'],
  ['namespace N { import.meta.url; }', 'namespace N { (import.meta).url; }'],
  ['namespace N { import\n("x"); }', 'namespace N { (import\n("x")); }'],
  ["abstract declare class C { m(): void }", "declare abstract class C { m(): void }"],
  ["@d abstract declare class C {}", "@d declare abstract class C {}"],
  ['enum E { ["x"], ["y"] }', 'enum E { "x", "y" }'],
  ['enum E { ["a-b"] = 1, B = E["a-b"] }', 'enum E { "a-b" = 1, B = E["a-b"] }'],
  ['const enum E { ["x"] = 1 } var v = E.x;', 'const enum E { "x" = 1 } var v = E.x;'],
  ['declare enum E { ["x"] = 1 }', 'declare enum E { "x" = 1 }'],
  ['export enum E { ["x"] = 1 }', 'export enum E { "x" = 1 }'],
  ["enum E { [`x`] = 1, [`y`] }", 'enum E { "x" = 1, "y" }'],
  ['enum E { ["x"] = "s" }', 'enum E { "x" = "s" }'],
  ['enum E { ["x"] = 1, ["y"] = x + 1 }', 'enum E { "x" = 1, "y" = x + 1 }'],
  ['namespace N { export enum E { ["x"] = 1 } }', 'namespace N { export enum E { "x" = 1 } }'],
  ['enum E { [ "x" ] = 1, }', 'enum E { "x" = 1, }'],
];
for (const [source, equivalent] of rows) {
  let now, want;
  try { now = "OK " + JSON.stringify(ts.transformSync(source)); } catch (e) { now = "ERR " + (e.errors?.[0]?.message ?? e.message); }
  try { want = ts.transformSync(equivalent).replaceAll("QQ", source.includes("satisfies") && !source.includes(" as") ? "satisfies" : "as"); } catch (e) { want = null; console.log("EQUIVALENT FAILS", JSON.stringify(equivalent), e.errors?.[0]?.message ?? e.message); continue; }
  console.log(JSON.stringify([source, want]) + ",", "//", now === "OK " + JSON.stringify(want) ? "SAME ON INSTALLED" : "installed: " + now);
}
